### ISSUE TITLE
Allow reloading of plugins

### ISSUE THREAD

**Issue by podarsmarty** [mockito/mockito#1003]
I am working on https://github.com/powermock/powermock/issues/769. With custom extension PluginSwitch's we should be able to allow switches that change whether an extension is enabled or disabled in different tests (such as choosing different MockMakers, default or custom). PluginRegistry can facilitate this if it is not final and has a static method to refresh/recreate itself.

**Comment by TimvdLippe** [comment]
Closing per https://github.com/mockito/mockito/pull/1006#issuecomment-294352517
