### ISSUE TITLE
Broken links in notable.md

### ISSUE THREAD

**Issue by szpak** [mockito/mockito#1031]
The new release notes generation mechanism provides broken links to "authors" and "improvements" in [notable.md](https://github.com/mockito/mockito/blob/76cd29eb7cf361a53a912b7aea42c56fb1603db3/docs/release-notes/notable.md):
https://github.com/mockito/mockito/blob/release/2.x/docs/release-notes/mockito/mockito/blob/release/2.x/docs/release-notes/notable.md
https://github.com/mockito/mockito/blob/release/2.x/docs/release-notes/mockito/mockito/blob/release/2.x/docs/release-notes/notable.md

Btw, is it intended to have both "doc" and "docs" dictionary?

**Comment by szczepiq** [comment]
Well spotted. Thank you!

**Comment by TimvdLippe** [comment]
This file has been removed in https://github.com/mockito/mockito/commit/a775b0668a1b4c73413b59c1c4cf11e2af4655ef#diff-51e2c26ce83e7e3a8f6325a3c24c0e4d
