### ISSUE TITLE
Want to change default argument matcher

### ISSUE THREAD

**Issue by WhiteCosmos** [mockito/mockito#1043]
Hi, I see there's a default matcher `Equals` will be set in `ArgumentsProcess`，any way to change the `Equals` matcher? I want to compare argument by fields.
```java
    public static List<Matcher> argumentsToMatchers(Object[] arguments) {
        List<Matcher> matchers = new ArrayList<Matcher>(arguments.length);
        for (Object arg : arguments) {
            if (arg != null && arg.getClass().isArray()) {
                matchers.add(new ArrayEquals(arg));
            } else {
                matchers.add(new Equals(arg)); // Want to change
            }
        }
        return matchers;
    }
```

**Comment by ChristianSchwarz** [comment]
This is the default matcher in case an raw argument was passed to a mock method.  You can define your own ArgumentMatcher and use it like this:

`when(mock.method(Mockito.argThat(myFieldMatcher))).then(..)`
