### ISSUE TITLE
Investigate Gradle build cache to speed up Travis builds

### ISSUE THREAD

**Issue by szpak** [mockito/mockito#1046]
Travis could keep local Gradle [build cache](https://docs.gradle.org/3.5/userguide/build_cache.html) in its cache between builds. Possibly also in 2.x branch as Java 7 is used to build those releases (which is still supported by Gradle 3.5).

**Comment by szczepiq** [comment]
Great idea! Do you want to take a stab at it? We should also upgrade to Gradle 3.5 because now we build on Java7!!! :)

**Comment by mockitoguy** [comment]
Let's move on. Travis CI has mixed results with Gradle caches because the latter has very complicated structure, and many unnecessary files are then cached and downloaded for each build.
