### ISSUE TITLE
How to test or mock the private method?

### ISSUE THREAD

**Issue by vicbell** [mockito/mockito#1047]
Is there any practice way to test or mock the private method? 
I must change all of the private methods to public in order to test or mock them?
Any suggestions?

**Comment by TimvdLippe** [comment]
Please read this wiki page: https://github.com/mockito/mockito/wiki/Mockito-And-Private-Methods

There are also some similar questions and answers available on Stackoverflow.

**Comment by vicbell** [comment]
Thanks!
