### ISSUE TITLE
reset/unmock class after PowerMockito.mockStatic(YOUR_CLASS.class)

### ISSUE THREAD

**Issue by LeftLegAndRightLeg** [mockito/mockito#1049]
Hi Guys,

I cannot find a way to reset/unmock a class after I do PowerMockito.mockStatic(MY_CLASS.class)

is there gonna be a way to do it ?

Best,
Bailiang

**Comment by TimvdLippe** [comment]
I think this is a PowerMockito related issue. Please report the issue on their tracker: https://github.com/powermock/powermock/issues
