### ISSUE TITLE
Release automation endless loop issue

### ISSUE THREAD

**Issue by szczepiq** [mockito/mockito#1059]
Recently I introduced a problem (PR: https://github.com/mockito/mockito/pull/1057) that created endless loop with our releases. Fallout / clean up needed:
 - [x] - stop the endless loop by reverting the commit. Thank you @TimvdLippe spotting the issue and reverting the change!
 - [x] - remove unnecessary tags
 - [x] - discard versions/artifacts that were pushed to Bintray (not "published" yet, safe to delete)
 - [x] - delete unnecessary content from [release notes file](https://github.com/mockito/mockito/blob/release/2.x/doc/release-notes/official.md)
 - [x] - fix the bug in release automation code, pr submitted, waiting for review & merge: https://github.com/mockito/mockito-release-tools/pull/103
 - [x] - test & reapply PR #1057

**Comment by szczepiq** [comment]
Waiting for review / merge: https://github.com/mockito/mockito-release-tools/pull/103

**Comment by TimvdLippe** [comment]
Fix seems fine to me. Have not executed it locally though.

**Comment by szpak** [comment]
I don't know if this is related, but the release process currently [fails](https://travis-ci.org/mockito/mockito/jobs/230865593#L796) with:
> remote: Invalid username or password.
on a git push.

**Comment by TimvdLippe** [comment]
It is sadly unrelated. It seems that @szczepiq password was reset for some reason :sob:

**Comment by szczepiq** [comment]
There is something weird going on with GitHub auth tokens. They seem to be expiring or something. I've tested locally a new token, updated Travis configuration and restarted Travis Job. We'll see if it helps.

**Comment by szczepiq** [comment]
It was fixed!
