### ISSUE TITLE
Usage of the final keyword

### ISSUE THREAD

**Issue by kobbikobb** [mockito/mockito#1063]
In the source code the usage of the final keyword is not consistent.
It is not mentioned in CONTRIBUTING.md.

Do you have a guideline for this and should it be included in CONTRIBUTING.md?
Do you feel it does not matter?

> Hey,
> 
> First thanks for reporting, in order to help us to classify issue can you make sure the following check boxes are checked ?
> 
> If this is about mockito usage, the better way is to reach out to
> 
>  - stackoverflow : http://stackoverflow.com/questions/tagged/mockito
>  - the mailing-list  : https://groups.google.com/forum/#!forum/mockito / mockito@googlegroups.com
>    (Note mailing-list is moderated to avoid spam)
>
> _This block can be removed_
> _Something wrong in the template fix it here `.github/ISSUE_TEMPLATE.md`

check that

 - [ ] The mockito message in the stacktrace have useful information, but it didn't help
 - [ ] The problematic code (if that's possible) is copied here;
       Note that some configuration are impossible to mock via Mockito
 - [ ] Provide versions (mockito / jdk / os / any other relevant information)
 - [ ] Provide a [Short, Self Contained, Correct (Compilable), Example](http://sscce.org) of the issue
       (same as any question on stackoverflow.com)
 - [ ] Read the [contributing guide](https://github.com/mockito/mockito/blob/master/.github/CONTRIBUTING.md)

**Comment by TimvdLippe** [comment]
I think it is applied rather arbitrarily, where we see it fit. No harsh guidelines or so.

**Comment by TimvdLippe** [comment]
For Java 8 we have to adopt final btw, if we want to access variables outside of lambdas. So then it would become required.

**Comment by szpak** [comment]
@TimvdLippe Java 8 relaxed a need to use the `final` keyword - variables can be [effectively final](https://docs.oracle.com/javase/tutorial/java/javaOO/localclasses.html#accessing-members-of-an-enclosing-class).

**Comment by kobbikobb** [comment]
Ok, thank you.
