### ISSUE TITLE
Complement error message

### ISSUE THREAD

**Issue by Somewater** [mockito/mockito#1065]
Exception from [cannotStubVoidMethodWithAReturnValue](https://github.com/mockito/mockito/blob/aeed5fe3b06912c35a4fd70fa61b45e1feedc9a1/src/main/java/org/mockito/internal/exceptions/Reporter.java#L447) does not inform about `doNothing()` method. But I think in many cases it is what user want to do.

**Comment by TimvdLippe** [comment]
Feel free to open a PR to fix this issue :smile: Thanks for the report.
