### ISSUE TITLE
Mockito 2.x on Android Instrumentation Tests with Kotlin is not working

### ISSUE THREAD

**Issue by magnumrocha** [mockito/mockito#1082]
Hi guys,

I am current working on a Android project using the [Kotlin language], and I’m trying mock some classes on Instrumentation Tests. As everything in Kotlin is final by default, we have the known problem of mock final classes, that only works if we apply the "mock-maker-inline" on file “org.mockito.plugins.MockMaker” inside test resources folder (eg.: src/test/resources/mockito-extensions/).

My mockito dependencies on module grade file are:

```code
compile "org.jetbrains.kotlin:kotlin-stdlib-jre7:1.1.2-3"
...

testCompile "junit:junit:4.12"
testCompile "org.jetbrains.kotlin:kotlin-reflect:1.1.2-3"
testCompile "org.mockito:mockito-core:2.8.9”
testCompile ("com.nhaarman:mockito-kotlin:1.4.0", {
    exclude group: 'org.jetbrains.kotlin'
    exclude group: 'org.mockito'
})

androidTestCompile "org.mockito:mockito-android:2.8.9”
androidTestCompile ("com.nhaarman:mockito-kotlin:1.4.0", {
    exclude group: 'org.jetbrains.kotlin'
    exclude group: 'org.mockito'
})
androidTestCompile ("com.android.support.test.espresso:espresso-core:2.2.2", {
    exclude group: 'com.android.support', module: 'support-annotations'
})
androidTestCompile ("com.android.support.test:runner0.5", {
    exclude group: 'com.android.support', module: 'support-annotations'
})
androidTestCompile ("com.android.support.test:rules:0.5", {
    exclude group: 'com.android.support', module: 'support-annotations'
})
````

For the local unit tests, the "mock-maker-inline" works properly. But for Android Instrumentations Tests it doesn't works. Reading about it on [Mockito documentation], we have: 

“Be aware that you cannot use the inline mock maker on Android due to limitations in the Android VM”.

We can’t apply the “mock-maker-inline” for Instrumentation tests.

So, how can we enable Mockito to mock final classes on Android Instrumentations Test ??

[Kotlin language]: https://kotlinlang.org/
[Mockito documentation]: https://static.javadoc.io/org.mockito/mockito-core/2.7.22/org/mockito/Mockito.html#mockito

**Comment by tmurakami** [comment]
I think there are two ways.
1. [Kotlin all-open plugin](https://kotlinlang.org/docs/reference/compiler-plugins.html#all-open-compiler-plugin)
2. [DexOpener](https://github.com/tmurakami/dexopener)

## Kotlin all-open plugin

This plugin makes classes annotated with a specific annotation open without the `open` keyword.

First, you put these files into your project:

- app/src/ **debug** /java/your/app/OpenClass.kt
```kotlin
package your.app

@Target(AnnotationTarget.ANNOTATION_CLASS)
annotation class OpenClass
```

- app/src/ **debug** /java/your/app/OpenClassOnDebug.kt
```kotlin
package your.app

@OpenClass
@Target(AnnotationTarget.CLASS)
annotation class OpenClassOnDebug
```

- app/src/ **release** /java/your/app/OpenClassOnDebug.kt
```kotlin
package your.app

@Target(AnnotationTarget.CLASS)
annotation class OpenClassOnDebug
```

Second, configure your `app/build.gradle` as follows:
```groovy
buildscript {
    repositories {
        jcenter()
    }
    dependencies {
        classpath "org.jetbrains.kotlin:kotlin-allopen:$kotlin_version"
    }
}

apply plugin: 'kotlin-allopen'

allOpen {
    annotation 'your.app.OpenClass'
}
```

Finally, annotate `OpenClassOnDebug` to the class you want to mock:
```kotlin
@OpenClassOnDebug
class YourClass
```

Now you can open classes and members only on debug mode.

## DexOpener

This library opens classes and members while testing on Android.

To use this library, configure your `app/build.gradle` as follows:
```groovy
android {
    defaultConfig {
        minSdkVersion 16 // 16 or higher
        testInstrumentationRunner 'com.github.tmurakami.dexopener.DexOpenerAndroidJUnitRunner'
    }
}

repositories {
    jcenter()
    maven { url 'https://jitpack.io' }
}

dependencies {
    androidTestCompile 'org.mockito:mockito-android:2.8.9'
    androidTestCompile 'com.github.tmurakami:dexopener:0.9.2'
}
```

**Comment by magnumrocha** [comment]
Thank you @tmurakami,

The first solution worked as I wanted.

**Comment by jaredsburrows** [comment]
@tmurakami Using your DexOpener plugin:
```
ava.lang.NoClassDefFoundError: org/mockito/internal/configuration/plugins/Plugins
        at org.mockito.internal.configuration.GlobalConfiguration.tryGetPluginAnnotationEngine(GlobalConfiguration.java:55)
```

Since Mockito-android is so large, I had to use LinkedIn's dexmaker.

**Comment by tmurakami** [comment]
What version of DexOpener are you using?
In version `0.9.2`, there are several bugs caused by ASMDEX that is an old DEX manipulation library.
Could you try using the latest version `0.10.1`?
If the problem still occurs, please file a report in the [DexOpener issues](https://github.com/tmurakami/dexopener/issues).

**Comment by jaredsburrows** [comment]
@tmurakami Sure. I am trying that now, but now the test app reaches multidex. Do you multidex for your test apks?

**Comment by jaredsburrows** [comment]
@tmurakami When turning on multidex:
```
Starting 0 tests on emulator-5554 - 4.4.2
Tests on emulator-5554 - 4.4.2 failed: Instrumentation run failed due to 'java.lang.NoClassDefFoundError'

com.android.builder.testing.ConnectedDevice > No tests found.[emulator-5554 - 4.4.2] FAILED 
No tests found. This usually means that your test classes are not in the form that your test runner expects (e.g. don't inherit from TestCase or lack @Test annotations).

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':connectedDebugAndroidTest'.
> There were failing tests. See the report at: file:///Users/<>/repo/android-gif-example/build/reports/androidTests/connected/index.html

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED in 6s
94 actionable tasks: 39 executed, 55 up-to-date
```

**Comment by tmurakami** [comment]
I'd like to investigate it, so please file a report in the DexOpener issues.

**Comment by jaredsburrows** [comment]
@tmurakami  done.

**Comment by GEllickson** [comment]
Curious, is there anything in the works to allow for easier mocking in Android Instrumentation tests besides the two approached above? 

I see the "cannot use the inline mock maker on Android due to limitations", but just wondering if some other workaround will be part of Mockito one day.

**Comment by jaredsburrows** [comment]
@GEllickson Honestly, what I have found is that Espresso should only be asserting the views have the proper data and visibility. Id add cases, I have used stubs or local mock data.

**Comment by makovkastar** [comment]
The DexOpener library worked great for me, thank you @tmurakami for creating it!
