### ISSUE TITLE
Mockito 2.8.9 available at JCenter, but not at Maven Central

### ISSUE THREAD

**Issue by juergenzimmermann** [mockito/mockito#1085]
Therefore, Spring Boot is still using Mockito 2.7.22, but not 2.8.x. Please see https://github.com/spring-projects/spring-boot/issues/9228

**Comment by szczepiq** [comment]
Thank you for reporting. We will fix this!

**Comment by szczepiq** [comment]
Fixed. Thank you very much for reporting. I also emphasized this version in [release notes](https://github.com/mockito/mockito/blob/release/2.x/doc/release-notes/official.md#289-2017-04-26-published-to-jcentermaven-central)
