### ISSUE TITLE
Timeout does not work with already affected mock

### ISSUE THREAD

**Issue by michaelilyin** [mockito/mockito#1087]
I have the following problem in mockito 1.9.5:
- I have an one mock method call with arg A
- I have an one mock method deffered call with arg B
- I tried to verify method invocation with arg B using timeout, but mockito fails with nessage that method was invoked with arg A and do not wait specified timeout.

Code:
```
   class S {
        void test(int a) {}
    }

    @org.junit.Test
    public void test() {
        final S s = mock(S.class);

        sendTestData(s);

        long start = 0, end;
        try {
            start = System.currentTimeMillis();
            verify(s, timeout(5000).times(1)).test(1);
        } finally {
            end = System.currentTimeMillis();
            System.out.println(end - start);
        }
    }

    private void sendTestData(S s) {
        s.test(2);
        new Thread(() -> {
            try {
                Thread.sleep(1000);
                s.test(1);
            } catch (InterruptedException e) {
                e.printStackTrace();
            }
        }).start();
    }
````

Output:
**26**

Argument(s) are different! Wanted:
s.test(1);
-> at Test.test(Test.java:22)
Actual invocation has different arguments:
s.test(2);
-> at Test.sendTestData(Test.java:30)

Comparison Failure: 
Expected :s.test(1);
Actual   :s.test(2);

**Comment by trcooke** [comment]
This is expected behaviour. Your test says "Verify that method 'add()' is called with argument '1', I'll wait 5 seconds for it" but the first call to 'add()' is with argument '2', hence Mockito reports a failure.

The 'verify' feature defines exact expectations on interactions with a mock. It sounds like you expect it to verify that a particular interaction happens regardless of all other interactions with the mock.

This doesn't look like an issue with Mockito.

**Comment by michaelilyin** [comment]
> It sounds like you expect it to verify that a particular interaction happens regardless of all other interactions with the mock.

Sounds reasonably, but.. Without async inocation there is no failure. If I call method 'add()' with both '2' and '1' arguments, expression `verify(s, timeout(5000).times(1)).test(1);` works fine and dont fails testcase. And it is right behaviour, yes? In this case mochito does not see that '2' was passed. Presence of '1' switched verification into passed state. But.. in this case we timeout does not needed, all works in one thread. 

And I have a mind: when we interested in operations like 'timeout'? In cases when we have async behaviour of testing code, yes? And I expect that in this case I will have same behaviour as in previous case. If argument '2' does not affect test result in sync mode, why in affect result in async mode?

> This doesn't look like an issue with Mockito.

Please give me bit more facts for approve that this case is expected.

**Comment by trcooke** [comment]
I have observed the inconsistency that you present. If I modify your example as follows then no failure is reported by Mockito v1.9.5:

    class S {
        void test(int a) {}
    }

    @org.junit.Test
    public void test() {
        final S s = mock(S.class);

        sendTestData(s);

        long start = 0, end;
        try {
            start = System.currentTimeMillis();
            verify(s, timeout(5000).times(1)).test(1);
        } finally {
            end = System.currentTimeMillis();
            System.out.println(end - start);
        }
    }

    private void sendTestData(S s) {
        s.test(2);
        s.test(1);
    }

However, this inconsistency is not observed when using the latest version of Mockito v2.8.9 where both scenarios result in a passing test, as you expect. I recommend updating your project to use the latest version.

**Comment by michaelilyin** [comment]
Ok, I'll try it. Thanks!
