### ISSUE TITLE
mockito-inline can't mock finals

### ISSUE THREAD

**Issue by martofeld** [mockito/mockito#1105]
Im trying to mock [JsonObject](https://github.com/google/gson/blob/master/gson/src/main/java/com/google/gson/JsonObject.java) using mockito-inline. When running from console it runs perfectly but when trying to use Android Studio i get 
```
org.mockito.exceptions.base.MockitoException: 
Cannot mock/spy class com.google.gson.JsonObject
Mockito cannot mock/spy because :
 - final class
```
I tried using both `@Mock JsonObject jsonObject` and `Mockito.mock(JsonObject.class)` but none of them work. Am I missing something? 

Versions:
- mockito-inline: 2.7.22 and 2.8.9
- junit: 4.12
- jdk: 1.8.0_92
- Gradle: 3.5
- Android Studio: 2.2.3 (Its a simple junit test but just in case)

```
Map<String, JsonElement> OUTER = new HashMap<>();
    Map<String, JsonElement> INNER = new HashMap<>();

    @Mock
    TypeAdapter<MockClass> adapter;
    @Mock
    TypeAdapter<JsonElement> elementTypeAdapter;
    @Mock
    JsonObject outer;
    @Mock
    JsonObject inner;

    @Before
    public void setUp(){
        MockitoAnnotations.initMocks(this);
        INNER.put("test1", new JsonPrimitive("test1"));
        INNER.put("test2", new JsonPrimitive("test2"));
        when(inner.entrySet()).thenReturn(INNER.entrySet());

        OUTER.put("test3", new JsonPrimitive("test3"));
        OUTER.put("test4", new JsonPrimitive("test4"));
        OUTER.put("inner", inner);
        when(outer.entrySet()).thenReturn(OUTER.entrySet());
    }
```

**Comment by szczepiq** [comment]
Thanks for reporting! Did you find a solution / workaround to the problem yet? It might we worth reaching out to Android community in case this is some known issue.

It looks like when you're running tests in Android studio, Mockito is not using inline mocking for some reason. Perhaps the classpath is stlightly different when you run tests in studio VS from command line.

**Comment by lenguyenthanh** [comment]
@martofeld do you have sample project for this issue? I can take a look.

**Comment by martofeld** [comment]
@szczepiq Found a workaround, quiting and opening AS again somehow makes this work. Still haven't found what causes this.

**Comment by martofeld** [comment]
@szczepiq After further investigating the issue I found the cause, if you include both mockito-android and mockito-inline as testCompile AndroidStudio does magic stuff and creates this issue. Removing the mockito-android dependency seemed to permanently fix this issue.

**Comment by jorgecoca** [comment]
@martofeld can I ask you how did you remove the "mockito-android" dependency? What exactly did you do? I'm facing the same problem, but I don't seem to find that dependency anywhere...

**Comment by martofeld** [comment]
@jorgecoca sure, i had
``` gradle
dependencies {
    ···
    testCompile "org.mockito:mockito-inline:2.7.+"
    testCompile "org.mockito:mockito-android:2.7.+"
    ···
}
```
im not sure were you might be adding your dependency but leaving the closure as follows
``` gradle
dependencies {
    ···
    testCompile "org.mockito:mockito-inline:2.7.+"
    ···
}
```
fixed my issue.

Hope this helps

**Comment by ali-naser** [comment]
I've faced similar problem. I've added 'mockito-inline' dependency from https://mvnrepository.com/artifact/org.mockito/mockito-inline/3.8.0 and followed this https://www.baeldung.com/mockito-final. Then it works. Sample code:

 ```
    private JSONMap atonQueriesMap;

	@Before
	public void setup() {
		atonQueriesMap = mock(JSONMap.class);
         when(atonQueriesMap.getString(any())).thenReturn(testQuery);
	}
```
