### ISSUE TITLE
Rule causes verification to never fail

### ISSUE THREAD

**Issue by westonal** [mockito/mockito#1106]
Tried with Mockito 2.8.9 and Mockito 2.1.0

The following is a minimal example of this issue. It will fail from a gradle run. For what it's worth, I have placed this in a new Android project and test via Android Studio and `./gradlew test` and both pass when the rule is present and fail when it is not.  

SSCCE:

```
package com.example.mockitoproblemexample;

import org.junit.Rule;
import org.junit.Test;

import static org.mockito.ArgumentMatchers.any;
import static org.mockito.Mockito.mock;
import static org.mockito.Mockito.never;
import static org.mockito.Mockito.times;
import static org.mockito.Mockito.verify;

public class MockitoTest {

    @Rule
    public SomeEmptyRule someEmptyRule = new SomeEmptyRule();

    interface MyInterface {
        void accept(Object x);
    }

    @Test
    public void I_should_fail_but_I_dont_if_rule_is_present() {
        final MyInterface c = mock(MyInterface.class);
        verify(c).accept(any());
        verify(c, never()).accept(any());
        verify(c, times(1)).accept(any());
        verify(c, times(2)).accept(any());
    }
}

```

Where the empty rule is:

```
package com.example.mockitoproblemexample;

import org.junit.rules.TestRule;
import org.junit.runner.Description;
import org.junit.runners.model.Statement;

public final class SomeEmptyRule implements TestRule {

    @Override
    public Statement apply(final Statement base, final Description description) {
        return new Statement() {
            @Override
            public void evaluate() {
            }
        };
    }
}
```

**Comment by westonal** [comment]
Full example project here: https://github.com/westonal/MockitoVerifyBugExampleRepo

**Comment by westonal** [comment]
`@RunWith(MockitoJUnitRunner.class)` does not help.

**Comment by TimvdLippe** [comment]
I think you always have to call `base.evaluate()` in your rule. That rule is JUnit specific and has nothing to do with Mockito. If the rule does not actually invoke the test (in this case the `base`), it will not do anything at all. You can test it by adding a `System.out.println()` inside your test. It should not be called.

**Comment by westonal** [comment]
@TimvdLippe Thank you very much, that's fixed it!
