### ISSUE TITLE
No release build for 2.8.39 - possible bug in Travis CI

### ISSUE THREAD

**Issue by szczepiq** [mockito/mockito#1107]
For some reason, Travis CI did not trigger the main build for version 2.8.39. In the travis dashboard for that build I can see only [3 child jobs](https://travis-ci.org/mockito/mockito/builds/237813636) whereas normally there are [4 child jobs](https://travis-ci.org/mockito/mockito/builds/237433149).

@szpak, have you seen something like that before? I'm restarting the build, let's see what happens :)

**Comment by szpak** [comment]
No, I haven't seen. There were no changes in .travis.yml and I have no idea what one of the jobs is missing. Probably (I hope) it will be automatically fixed by the next commit. It may be good to report it to Travis.

**Comment by szczepiq** [comment]
Just merged another PR, will see how many child jobs Travis job triggers this time :)

**Comment by szczepiq** [comment]
Another instance of this problem. I've contacted Travis CI support, put you guys on cc.

**Comment by szczepiq** [comment]
Commented on the ticket in Travis issue tracker (https://github.com/travis-ci/travis-ci/issues/4681#issuecomment-306102865). Here's the message from Travis CI support:

```
Thanks for reaching out and I'm sorry for this change in behavior.

This is the result of a change we released 3 days ago and it's detailed here: https://github.com/travis-ci/travis-ci/issues/4681. In brief, if you have no matrix expansion on the top level, and there is at least one job defined in `matrix.include`, the top level job is no longer included in the build matrix.

You should be able to get your old build configuration back by adding the following under `matrix.include`:


matrix:
  include:
  - jdk: oraclejdk7
  - jdk: oraclejdk7
    env: SKIP_RELEASE=true MOCK_MAKER=mock-maker-inline
  ⋮
```

I'm trying it now ;)
