### ISSUE TITLE
Upgrade request: throw exception when calling unstubbed methods

### ISSUE THREAD

**Issue by sebastientromp** [mockito/mockito#1111]
Hello,

One of the arguments I hear against using Mockito (over implementing interfaces all the way down) is that you run the risk of forgetting to stub a method. The default "return null" behavior can then, in some cases, make a test pass while there are errors in the functional logic.

I saw https://github.com/mockito/mockito/pull/54 which seemed to provide, at least in part, an answer to that.
Is there a way to achieve a similar result already? If not, would it make sense to have it part of mockito?

Thanks!

**Comment by TimvdLippe** [comment]
Thanks for your feature request. We are actually working on that right now! You can follow the progress in #1097, thanks :smile:
