### ISSUE TITLE
"Warn when these classes are mocked" options

### ISSUE THREAD

**Issue by Pr0methean** [mockito/mockito#1113]
On a project where I recently worked, the management complained a lot about unit tests unnecessarily mocking POJO-like classes when they could just as easily use the real class. It'd be nice if it were possible to configure Mockito to raise warnings whenever classes with a specific list of annotations and/or ancestor classes were mocked. If there is general agreement that mocking POJOs is usually bad, we can put com.google.protobuf.AbstractMessageLite and com.google.protobuf.nano.MessageNano (as ancestors) and com.google.auto.value.AutoValue (as an annotation) onto that list by default.

There should probably also be a @MockingDeprecated annotation that comes with Mockito and that raises the warning by default.

**Comment by TimvdLippe** [comment]
With the new framework API, you could actually implement this yourself. Create a [`MockCreationListener`](http://static.javadoc.io/org.mockito/mockito-core/2.10.0/org/mockito/listeners/MockCreationListener.html) and attach this listener during `setup`. Then you can check the type of the mock with [`getDeclaredAnnotations`](https://docs.oracle.com/javase/7/docs/api/java/lang/Class.html#getDeclaredAnnotations()) to check if the annotation exists.
