### ISSUE TITLE
Excluding issues/PRs from release notes by label

### ISSUE THREAD

**Issue by szpak** [mockito/mockito#1123]
Release notes for 2.8.44 contains:

```
 - [New features] Answer with delay in mock or spy to improve testing of asynchronous code (#1117)
 - Made it possible to delay the return of a mock or spy (#1117) (#1122)
 - Made it possible to delay the return of a mock or spy. (#1117) (#1119)
```

It would be good to exclude the two later PRs (e.g. by labels). @szczepiq Long time ago it was possible to exclude some label. Is it still possible with ShipKit?

Btw, PRs merged to other branches (here to master) could not be taken into account.

**Comment by szczepiq** [comment]
Thanks for reporting! I manually updated the release notes :)

I'm not sure what we can do here automatically. The commit messages included multiple PRs.

**Comment by szczepiq** [comment]
>It would be good to exclude the two later PRs (e.g. by labels)

How do see it working? What labels would you exclude? Would the 'excluded' labels be configurable in "shipkit.gradle" file?

**Comment by szpak** [comment]
Doing some internal changes via PR there is a chance to get it in the changelog (which maybe be not intended). If I understood it correctly, currently it is enough to just not mention the number in a commit message to skip it. It seems to be enough for me. Alternatively, there could be some label configurable in shipkit per project (maybe one by default - something opposed to noteworthy - unnoteworthy? not for changelog? skip in changelog?)

**Comment by szczepiq** [comment]
Interesting feature request. Let's see if we find it useful. Currently, it's exactly how you describe it - if you don't mention the ticket in the commit, it is not referenced.

OTOH, if there is a change worthy of pull request (instead of just ignoring), perhaps it should be mentioned in the notes.

BTW. we discontinued the idea of separate notable release notes, it was making the entire toolset too complicated.

**Comment by szczepiq** [comment]
I will close this ticket for now. We can reopen if there a clear path why/how do we implement it. We can also raise that in the http://shipkit.org project.
