### ISSUE TITLE
Version not released to Maven Central

### ISSUE THREAD

**Issue by szpak** [mockito/mockito#1127]
2 days ago I requested a [build](https://github.com/mockito/mockito/commit/04961ae3cc8093916f563d7edc223224d757a4a1) with Maven Central sync (having notable changes merged). Looking into release configuration I used `[ci maven-central-release]` and it seems to be [enabled](https://travis-ci.org/mockito/mockito/jobs/242215132#L842) in Travis.

However, that release is not [available](https://maven-badges.herokuapp.com/maven-central/org.mockito/mockito-core) in Maven Central (2.8.9 is the newest as time of raising this issue instead of 2.8.44).

@szczepiq Is there anything else (with the current release mechanism) that is needed to do to build a "notable version"?

**Comment by TimvdLippe** [comment]
I think we need to set a property on our project, looking at the line above in the Travis build you linked: 
```
project property 'maven-central-release' exists: false
```

**Comment by szczepiq** [comment]
Looking! Thank you for reporting!

**Comment by szczepiq** [comment]
Great bug report guys! It was very easy to nail down the issue!

**Comment by szczepiq** [comment]
Please review / merge: https://github.com/mockito/mockito/pull/1129

**Comment by szpak** [comment]
Worked perfectly - https://repo1.maven.org/maven2/org/mockito/mockito-core/2.8.47/
