### ISSUE TITLE
Mockito should annotate when() methods with a custom annotation @CheckReturnValue

### ISSUE THREAD

**Issue by tkruse** [mockito/mockito#1130]
Static code checkers like error-Prone and FindBugs will help detecting invalid usage of Mockito in single-call situations if Mockito source code were annotated with @CheckReturnValue.

See:
* https://github.com/joel-costigliola/assertj-core/issues/157
* http://errorprone.info/bugpattern/CheckReturnValue
* https://github.com/joel-costigliola/assertj-core/pull/695
* https://github.com/joel-costigliola/assertj-core/blob/master/src/main/java/org/assertj/core/util/CheckReturnValue.java

Note like for AssertJ, any annotation with name should do, no need to depend on a specific library with  @CheckReturnValue.

**Comment by TimvdLippe** [comment]
That seems fine to me. Please submit a pull request :smile:
