### ISSUE TITLE
mock-maker-inline slow down my tests

### ISSUE THREAD

**Issue by BraisGabin** [mockito/mockito#1142]
I actived the `mock-maker-inline` to mock no-open Kotlin classes following [this article](http://hadihariri.com/2016/10/04/Mocking-Kotlin-With-Mockito/).

Previusly my tests were kind of slow: ~20s but now the time is ~35s.

Mockito version: `2.8.47`

**Comment by raphw** [comment]
Inline mocks have to redefine classes what is expensive. The inline mock maker will therefore always be slower, unfortunately.

**Comment by carloxavier** [comment]
is there any way to improve times yet when using mock-maker-inline?
We have around 7K junit tests, and the impact is very high (seeing +3x times on testing times)

**Comment by raphw** [comment]
Unfortunately, this is the price to pay. We do already cache the more expensive parts but using the instrumentation API is very expensive, therefore, the subclassing mock maker will always be much cheaper.

In the future, there might be an extension that asserts if the mock really needs to be final but right now this is not a priority.

**Comment by BraisGabin** [comment]
I found a different option to mock Kotlin classes where you don't need `mock-maker-inline` so there isn't any performance impact: https://engineering.21buttons.com/mocking-kotlin-classes-with-mockito-the-fast-way-631824edd5ba

The main idea is use the [allopen plugin](https://kotlinlang.org/docs/reference/compiler-plugins.html).
