### ISSUE TITLE
Current version not in Maven Central

### ISSUE THREAD

**Issue by rhwood** [mockito/mockito#1150]
The latest release version on GitHub is newer than the latest release on Maven Central. Are you stopping releasing via Maven Central?

**Comment by szczepiq** [comment]
We release to maven central at slower pace following feedback from the community. More information in this [blog post](http://blog.mockito.org/2017/02/mockito-continuous-delivery-pipeline-2.0.html).

Do you need latest version in central? Are you looking to using some particular feature?

**Comment by rhwood** [comment]
It wasn't clear from looking at the README; where the Download button image shows a different version than the Maven button image.

Randall Wood
Alexandria Software
randall.h.wood@alexandriasoftware.com
http://alexandriasoftware.com

**Comment by TimvdLippe** [comment]
We could update the README to make this more clear. PR welcome.

**Comment by khmarbaise** [comment]
Unfortunately the newest release are not available in Central would be a good idea to have them there...
