### ISSUE TITLE
Mock Inline fail when mocking parent method

### ISSUE THREAD

**Issue by pseandersson** [mockito/mockito#1154]
Hi,
This is a simple case where the mockito-inline feature will fail.

```
@RunWith(MockitoJUnitRunner.class)
public class MyUnitTest {
   class TestFinal {
        public final int myFunc() {
            return 3;
        }
    }

    class TestFinal2 extends TestFinal {
        public int getValue() {
            return myFunc();
        }
    }

    @Test
    public void testFinalMock() {
        TestFinal2 tf = mock(TestFinal2.class);
        when(tf.myFunc()).thenReturn(10);
        assertThat(tf.myFunc(), is(10));
        assertThat(tf.getValue(), is(10));
    }
}
```
In what timeframe will would it be possible to solve this?

**Comment by JimLawrence** [comment]
I think this is the exact situation I'm running into. Is the error that you are having that it just ignores the Mock and starts calling the methods?

**Comment by pseandersson** [comment]
Yes, that is the case. I solved it by a work around in my real code but it didn't work out in the simple example. The workaround was:

@RunWith(MockitoJUnitRunner.class)
public class MyUnitTest {
   class TestFinal {
        public final int myFunc() {
            return 3;
        }
    }

    class TestFinal2 extends TestFinal {
        public int getValue() {
            return getTestFinal().myFunc();
        }
        public TestFinal getTestFinal() {
            return this;
        }
    }

    @Test
    public void testFinalMock() {
        TestFinal tf0 = mock(TestFinal.class);
        TestFinal2 tf = mock(TestFinal2.class);
        when(tf.getTestFinal()).thenReturn(tf0)
        when(tf0.myFunc()).thenReturn(10);
        assertThat(tf0.myFunc(), is(10));
        assertThat(tf.getValue(), is(10));
    }
}

**Comment by JimLawrence** [comment]
I didn't have the option to rewrite either the parent or child, so I created a testing class that extended the child but overrode the problem function. That solved it, but this does seem like a bug.

**Comment by ChristianSchwarz** [comment]
possibly @raphw knows more, seems like a byte-buddy issue

**Comment by szczepiq** [comment]
Thank you for reporting! Indeed it seems that something that needs to be fixed on our end. Thanks in advance to @raphw for looking at it :).

Out of curiosity, are the final methods on those classes necessary? Is it because they are 3rd party classes that you don't own?

**Comment by pseandersson** [comment]
Third party. By the way when I look again at the code I see the classes are not declared public maybe that is the reason for why it fails.

**Comment by raphw** [comment]
I had a look and everything works as expected. I assume that you want to write your test like this:

```java
@Test
public void testFinalMock() {
  TestFinal2 tf = mock(TestFinal2.class);
  when(tf.myFunc()).thenReturn(10);
  when(tf.getValue()).thenCallRealMethod(); // this is missing!
  assertThat(tf.myFunc(), is(10));
  assertThat(tf.getValue(), is(10));
}
```

**Comment by pseandersson** [comment]
True that make sense!
