### ISSUE TITLE
Unable to mock SolrJ Query

### ISSUE THREAD

**Issue by guruprasadkk** [mockito/mockito#1160]
Hi,
I am using mockito to mock the methods in my unit testing in Junit. But I am not able to mock CloudSolrClient.query() call. Even though I mocked it is going and invoking real implementation. Mocking of other methods are woring fine.

Here is my code
CloudSolrClient client = new CloudSolrClient.Builder().withZkHost(some string").build();
SolrQuery solrQuery = new SolrQuery();
/*build the query*/
client.query(solrQuery);

and my mock code is
@mock	
CloudSolrClient client;
QueryResponse response = null;
when(client.query(any(SolrQuery.class))).thenReturn(response);

Can you please help me in resolving this issue?

**Comment by ChristianSchwarz** [comment]
better ask this here-> http://groups.google.com/group/mockito

**Comment by szczepiq** [comment]
The typical reason why the method uses real behavior instead of stubbed one is that the method is final. In order to make progress on this problem I suggest to:
 - reach out on SO or the mailing list
 - create a tiny sample test that reproduces the issue and try to debug yourself

Hope that helps!
