### ISSUE TITLE
Documentation: when/thenReturn and verify (indicate if the code and mock code must be mandatorily the same)

### ISSUE THREAD

**Issue by manueljordan** [mockito/mockito#1168]
Hello 

I had this experience: 
[Correct configuration to mock Hibernate's sessionFactory.getCurrentSession()](https://stackoverflow.com/questions/45704150/correct-configuration-to-mock-hibernates-sessionfactory-getcurrentsession)

The `crud` method is:

```
@Override
public Persona saveOne(Persona persona) {
        String generatedIdentifier = (String) sessionFactory.getCurrentSession().save(persona);
        logger.info("generatedIdentifier: {}", generatedIdentifier);
        return persona;
}
```

Observe the use of `sessionFactory.getCurrentSession()`. Now his solution is:

* `when(session.save(persona)).thenReturn(persona.getId());`
* `verify(session).save(persona);`

It works with `Session` instead.

Even when the solution works, consider in read the comments of the solution. Is confuse for me, and I never seen this approach or behavior in none tutorial, I thought that for Mockito is **mandatory** do the `when/thenReturn` and `verify` respecting or reflecting the **same** code being used in the `saveOne` method. `sessionFactory.getCurrentSession().save(persona);`. 

Not sure if is totally valid. My main concern is if is even valid his comments. I want to know if it is documented or not in the current Mockito documentation.

Thanks by your understanding

**Comment by TimvdLippe** [comment]
If I understand the issue correctly, you are asking why both of the methods have to match on the same session? Looking at your implementation, you invoke `save` on a mock returned from `getCurrentSession()`. Therefore, if you do something like when(sessionFactory.getCurrentSession().save(persona)).thenReturn(persona.getId());`, you have not mocked `sessionFactory.getCurrentSession()`. That in turn returns `null`. E.g. you invoke `save(persona)` on null, which throws the exception.

By first setting up your mock from `getCurrentSession()`, you can then add verifications only on that, without having to invoke `getCurrentSession()` again to obtain the mock and setup your second stub.

Hopefully this clarifies a bit more. Feel free to reopen if you are still uncertain on Mockito's behavior.
