### ISSUE TITLE
Mockito 2 - Mocking final classes under androidTest does not work 

### ISSUE THREAD

**Issue by jolsys** [mockito/mockito#1173]
Hello,

Default behaviour of mockito-core and mockito-android does not contain functionalities to mock final classes: 
   testCompile "org.mockito:mockito-core:+"
   androidTestCompile "org.mockito:mockito-android:+"

To mock final classes under test/ package we can replace: 
testCompile "org.mockito:mockito-core:+" with testCompile "org.mockito:mockito-inline:+"

To mock finall classes under androidTest we should create a  file: 
 /mockito-extensions/org.mockito.plugins.MockMaker containing the value mock-maker-inline.
This soultion does not work. I still receive the same exception that final classes canot be mocked. 

Cheers!

**Comment by raphw** [comment]
The final mock maker does not work on Android.

**Comment by jolsys** [comment]
thanks! Do you have it on the roadmap to make it work?

**Comment by raphw** [comment]
There is no real possibility to make this work in Android at the moment as it lacks the instrumentation API on top of which we are operating. The Android VM is not a standard VM and only implements a subset of the Java specification. As long as Google does not choose to extend its JVM, I am afraid that this feature will not work.

**Comment by tmurakami** [comment]
@jolsys, if you would like to mock your final classes on Android VM, you can use the [DexOpener](https://github.com/tmurakami/dexopener) library.

**Comment by jolsys** [comment]
Thanks, I am trying to use it. I create a new project and try to follow the instruction in readme.txt but I fail. Actually I have smth like this, and it should work I guess:
build.gradle (Module:app)
`apply plugin: 'com.android.application'

android {
    compileSdkVersion 25
    buildToolsVersion "25.0.1"
    defaultConfig {
        applicationId "com.tdd.nilesh.opendex1"
        minSdkVersion 16
        targetSdkVersion 25
        versionCode 1
        versionName "1.0"
        testInstrumentationRunner 'com.github.tmurakami.dexopener.DexOpenerAndroidJUnitRunner'
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
}

dependencies {
    compile fileTree(dir: 'libs', include: ['*.jar'])
    androidTestCompile('com.android.support.test.espresso:espresso-core:2.2.2', {
        exclude group: 'com.android.support', module: 'support-annotations'
    })
    compile 'com.android.support:appcompat-v7:25.+'
    compile 'com.android.support.constraint:constraint-layout:1.0.2'
    testCompile 'junit:junit:4.12'


    androidTestCompile('com.github.tmurakami:dexopener:0.11.0', {
        exclude group: 'com.android.support', module: 'support-annotations'
    })

    androidTestCompile 'org.mockito:mockito-android:2.8.9'
}
`
build.gradle (Project:abc)
`// Top-level build file where you can add configuration options common to all sub-projects/modules.

buildscript {
    repositories {
        jcenter()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:2.3.1'

        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

allprojects {
    repositories {
        jcenter()
        maven { url 'https://jitpack.io' }
    }
}

task clean(type: Delete) {
    delete rootProject.buildDir
}
`

I receive: 
`
$ adb shell am instrument -w -r   -e debug false -e class com.tdd.nilesh.opendex1.ExampleInstrumentedTest com.tdd.nilesh.opendex1.test/android.support.test.runner.AndroidJUnitRunner
Client not ready yet..
Started running tests
Test running failed: Unable to find instrumentation info for: ComponentInfo{com.tdd.nilesh.opendex1.test/android.support.test.runner.AndroidJUnitRunner}
Empty test suite.
`

**Comment by jolsys** [comment]
Hey, Thanks I try to apply dexopener + mockito-android but I fail, I create a new project follow instructions in readme, but i receive:

`Test running failed: Unable to find instrumentation info for: ComponentInfo{com.tdd.nilesh.opendex1.test/android.support.test.runner.AndroidJUnitRunner}
`

My gradle files:
[build.gradle.txt](https://github.com/mockito/mockito/files/1260883/build.gradle.txt)
[build.gradle.Project.txt](https://github.com/mockito/mockito/files/1260888/build.gradle.Project.txt)

**Comment by tmurakami** [comment]
If you would like to run tests with adb, run "adb shell am instrument -w com.tdd.nilesh.opendex1.test/**com.github.tmurakami.dexopener.DexOpenerAndroidJUnitRunner**".
To run tests on Android Studio, specify the correct runner in the `Run/Debug Configurations` dialog.

**Comment by jolsys** [comment]
Unfortunately Android Studio 2.3.1. does not allow to set InstrumentationRunner via Run/Debug Configuration it should be smart enough to pick it up on its own but unfortunately it is not.

**Comment by tmurakami** [comment]
Could you remove your test settings from `Run/Debug Configurations` and rerun your tests?

**Comment by jolsys** [comment]
[error.txt](https://github.com/mockito/mockito/files/1263639/error.txt)
Regarding running tests from Android Studio runner:
Yes, I did and with the existing project it did not work, so I created a new one and it started working :)

Regarding terminal:
When I run the command "adb shell am instrument -w com.tdd.nilesh.opendex1.test/com.github.tmurakami.dexopener.DexOpenerAndroidJUnitRunner", I receive:
[error.txt](https://github.com/mockito/mockito/files/1263640/error.txt)
I assume I need to add a AndroidManifest.xml and specify the:
`<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    package=[your test package]>
    
    <instrumentation>
        
        <meta-data
            android:name="notPackage"
            android:value="net.bytebuddy" />
    </instrumentation>
</manifest>`

**Comment by tmurakami** [comment]
Running an independent test with using `notPackage` will fail due to the Android Testing Library specification.
The error was resolved at Android Testing Support Library 1.0. Could you test with that version?

**Comment by jolsys** [comment]
I the test against Android Testing Support Library 1.0 and it works fine. 
I can run it from android studio or from a command line. 
Thank you for your help!

**Comment by jolsys** [comment]
When I created a sample app, everything started working fine, now I try to apply dexopener to the already existing project, I do the same steps but I get this response:
[BuildConfig exception.txt](https://github.com/mockito/mockito/files/1266582/BuildConfig.exception.txt)

Not sure what I can do about this exception.

**Comment by tmurakami** [comment]
You need to put your own AndroidJUnitRunner into your `androidTest` directory and use `DexOpener.Builder`.
Please refer to [README.md](https://github.com/tmurakami/dexopener/blob/master/README.md#extending) and [example](https://github.com/tmurakami/dexopener/tree/master/dexopener-example).
