### ISSUE TITLE
[Android] Very slow (initialization?) when running androidTest on real devices

### ISSUE THREAD

**Issue by orionlee** [mockito/mockito#1177]
# Highlights: 
- I have an androidTest that stubs android PackageManager and ResolveInfo classes.  `mockito-android` seems to need excessive amount of time doing some initial setup. 
- The first test that uses the mock take 8.x seconds to complete on a device.
- For comparison, the same test that uses custom stubs (rather than Mockito or other mock framework) takes ~500ms.
- Furthermore, if I replace `mockito-android` with LinkedIn's `dexmaker-mockito`, the same test takes 1 - 2.x seconds. Similar time is observed using `mockito-core:1.9.5` with google's dexmaker
- I hope the speed of using `mockito-android` could be improved to be comparable to using LinkedIn's `dexmaker-mockito` / `mockito-core-1.x` + google's dexmaker

# Details:
- Environment:  `mockito-android` v 2.8.47, running on Android 7.1.1 device (an okay Motorola Moto E4).
   - Same results was observed with `mockito-android` v 2.6.3, so it probably was not a recent regression.

- The test (and mocks in question). See the test `t1$setUp()`, which uses Mockito to create a stub PackageManager and some stub ResolveInfos, and launch the activity under test. Running `t1$setUp()` takes 8.x secons.
https://github.com/orionlee/aDictOnCopy/blob/v0.3.18/app/src/androidTest/java/net/oldev/aDictOnCopy/MainActivityTest.java#L189

- When I change `app/build.gradle` to replace `mockito-android` with LinkedIn's `dexmaker-mockito`, I observe the speed up (from 8.x seconds to 1 - 2.x seconds). Similar result can be obtained by using `mockito-core:1.9.5` with google's dexmaker (and some minor code changes to deal with Mockito 1.x API).

- When I replace Mockito-based stubs with custom stubs (that does not use any mock framework), the same test takes ~500ms.
https://github.com/orionlee/aDictOnCopy/blob/v0.3.19/app/src/androidTest/java/net/oldev/aDictOnCopy/MainActivityTest.java#L215

- Subsequent test that creates more stubs, `t2$setUp4RemainingTests()`, takes ~250ms regardless the mock framework (including custom stubs) used, leading me to believe that mockito initialization contributes to the slow running time of the first test.

**Comment by raphw** [comment]
This has a bit to do with how mocks are created and what quality these mocks have. Byte Buddy parses generic information and annotations what triggers lazy loading of elements that are otherwise not resolved.

As a result, the mocks are guaranteed to generate correct erasures and to avoid skipping some bridge methods that should be mocked. The more primitive mock maker cannot do that but generate code much faster.

Also, the Mockito mock maker is based on creating jar files and converting them to dex on the fly. This takes extra time.

The good news is that those are more or less fixed costs per mocked class. The amout of time should not increase much. If you want to speed up the process but decrease reliability, just use another mock maker.

**Comment by orionlee** [comment]
Hi @raphw ,

To make sure I understand what you say correctly, I get you suggest that:
1. `mocktio-android` generates more complete mock, than, including but not limited to `mockito-core-1.x` + google's `dexmaker` or LinkedIn's `dexmaker-mockito` (mockito 2's equivalent one).
2. `mocktio-android` mock maker is based creating jar and dex at runtime (aka on the fly).

Speaking from a regular developer's perspective (without knowing the intricacy in creating mocks), I have 2 comments:
1. The per-mocked class extra time is probably okay for running a test suite. However, when a developer is just running individual test, the extra time the mock incurs can really impede productivity, and possibly adoption of mocks. (I know that a androidTest will never be as fast as a local unit test, still the extra slow down by mocks is quite noticeable.)

2. One possible way to improve speed could be shifting part of mock's generation to build time: developer machines, typically more powerful than the devices, would make the overall speed faster even if the exact same work were done (plus the possibility of caching / reusing generated mock classes in subsequent runs).

For example, in https://github.com/orionlee/aDictOnCopy/blob/v0.3.18/app/src/androidTest/java/net/oldev/aDictOnCopy/MainActivityTest.java#L87
```java
            PackageManager mockPkgMgr = mock(PackageManager.class, withSettings().stubOnly());
............
            when(mockPkgMgr.resolveActivity(argThat(new ArgumentMatcher<Intent>() {
```

It is conceivable it can be tweaked to something like the following:
```java
            @Mock PackageManager mockPkgMgr = mock(PackageManager.class, withSettings().stubOnly());
............
            when(mockPkgMgr.resolveActivity(argThat(new ArgumentMatcher<Intent>() {
```
such that @Mock annotation (or some other way to signal it) triggers the generation of a (generic) mock PackageManager class at build time (it seems to be the one that takes bulk of time). The behavior of the mock instance, as specified by `when`, `verify`, etc., will still be defined at runtime.

**Comment by raphw** [comment]
Hi, there is definately potential to improve things but it is not a first priority as there are alternatives around. For the build time generation, this becomes difficult if you do not know the types to mock at runtime. In the general case, this is not decidable unless you would explicitly mention the types.

Mocking on Android is still an issue, also with emerging languages like Kotlin that define final types by default. There is ground to make but we would need better infrastructure on Android to hook into to allow for this.

**Comment by orionlee** [comment]
Hi @raphw,

Thanks for the response. I could appreciate there are competing priorities. I'd leave the issue open for tracking purposes.

In my case, the alternative I ended up using is extending Android platform's `MockPackageManager` . I understand the irony that `MockPackageManager` is deprecated in favor of Mockito: I feel the speed improvement of using `MockPackageManager` is worth it in my case.

**Comment by raphw** [comment]
Yes, definetly. We piggy back on the Android DEX compiler to keep our maintenance work as little as possible and for the most, this works out well as most people seem to only integration test on devices but use something like Robolectric for unit tests to make use of, for example, the inline-mock-maker with Kotlin.

Glad this alternative works for you.
