### ISSUE TITLE
mock-maker-inline prevent mock Android native methods

### ISSUE THREAD

**Issue by StanKocken** [mockito/mockito#1178]
Recently using `mock-maker-inline`, I faced an issue with my native methods.

Here is a little example:

    package com.mytest;

    import org.junit.Assert;
    import org.junit.Before;
    import org.junit.Test;
    import org.mockito.Mock;
    import org.mockito.MockitoAnnotations;

    public class JniTest {

        @Mock
        InnerTestClass underTest;

        @Before
        public void setUp() throws Exception {
            MockitoAnnotations.initMocks(this);
        }

        @Test
        public void testCallJni() {
            Assert.assertNull(underTest.callJni());
        }

        @Test
        public void testCallJniFromJava() {
            Assert.assertNull(underTest.callJniFromJava());
        }

        public static class InnerTestClass {

            public native String callJni();

            public String callJniFromJava() {
                return callJni();
            }
        }
    }

If I don't have the file `org.mockito.plugins.MockMaker`, then I have 2 success, the 2 methods are mocked.
If I have the file `org.mockito.plugins.MockMaker` with `mock-maker-inline` inside, then `testCallJniFromJava` succeed, but not `testCallJni()`. Instead it will try to call the real method, so we have the exception:
`java.lang.UnsatisfiedLinkError: com.mytest.JniTest$InnerTestClass.callJni()Ljava/lang/String;`

Thanks

**Comment by TimvdLippe** [comment]
This is a documented limitation:
http://static.javadoc.io/org.mockito/mockito-core/2.8.47/org/mockito/Mockito.html#39

```
Some methods cannot be mocked:
Package-visible methods of java.
native methods
```

**Comment by StanKocken** [comment]
Alright, I missed this line. I will try to find a workaround.
If you think this will never be the case, then we can close this issue as won't fix.

**Comment by TimvdLippe** [comment]
This would need to be fixed in ByteBuddy and I am not sure if it is even possible. Therefore I am closing this issue for now.
