### ISSUE TITLE
Mockito 2.9.0 is significantly slower

### ISSUE THREAD

**Issue by jeffdcamp** [mockito/mockito#1179]
We just tried to upgrade to Mockito 2.9.0 (from 2.8.47) and found that our individual tests went from about 1 second to run per test to about 24 seconds to run per test.

We tried to find which release version causes the tests to run slow and found that version 2.8.50 is the first version that causes the slowdown (versions 2.8.48 and 2.8.49 run fine)

Our environment:
- Java 1.8.0_144
- Android Gradle Project (using Gradle 4.1 and Android Studio 3.0 Beta3)
- Kotlin 1.1.4-2
- JUnit 4.12

Other test dependencies
- Dagger 2.11
- threetenbp:1.3.6
- org.xerial:sqlite-jdbc:3.20.0

**Comment by TimvdLippe** [comment]
@raphw Seems to be #1136 is the culprit. Any insight or immediate thoughts about it?

**Comment by raphw** [comment]
@jeffdcamp Thanks for the description. Are you using the Android mock maker? Could you attach a profiler when running the tests to see what takes so much time?

**Comment by raphw** [comment]
If you are using the final mock maker, I see how the resolution could be problematic using the method graph compiler. This is quite expensive and I did not think much about it when implementing the correct solution. We should definetly cache the result.

**Comment by raphw** [comment]
@jeffdcamp Could you build Mockito from the branch `performance-fix` and try it out? I wonder if that fixes the regression. Thanks

**Comment by jeffdcamp** [comment]
@raphw  We are not using "Android mock maker or the final mock maker".   Yes... 2.8.50 is the version that causes the slowdowns (we tried both  2.8.48 and 2.8.49, and those 2 versions work fine).

I'll try to perform a build of Mockito "performance-fix" branch

**Comment by jeffdcamp** [comment]
@raphw I just built the "performance-fix" branch and changed the dependency on our project to "2.9.1" and that did not fix the slow down.

The following is using version 2.9.1 (Note the long run times):

![image](https://user-images.githubusercontent.com/1479095/29842041-d956de70-8cc4-11e7-9329-a7d1e88f9abc.png)

The following is using version 2.8.47:

![image](https://user-images.githubusercontent.com/1479095/29842193-58a65034-8cc5-11e7-8e13-9e023502340b.png)

**Comment by raphw** [comment]
And you really get the same behavior in 2.8.50? This seems unlikely if you are not using the inline mock maker. (Are you sure you have no mock maker configured?) The only change from 2.8.49 to 2.8.50 is in the class `MockMethodAdvice` which should not even get loaded unless you are using the mock maker in which case the versions should be identical.

Could you run the tests while profiling with something like JProfiler (there is a free trial) to see where the tests spend their time compared to before the update?

**Comment by jeffdcamp** [comment]
@raphw I just went to the git log and checked-out and built revision "Fixed flaky Bintray badge Szczepan Faber* 6/22/17 4:16 PM (1a60a8496d4b704cac115608ca67840c7d8a6865)" and tests runs fast.... 

I then checked-out revision and built revision "Fixes #1135: Properly resolve visibility bridges. (#1136) Rafael Winterhalter* 6/24/17 2:29 AM (fa66960eeb74473822fe9081246f360964da6023)" and the test run slow...

I'll see what I can do to profile....

**Comment by raphw** [comment]
Thanks for investigating! 

This is just super strange, I have no idea how this could affect the subclass mock maker.

**Comment by jeffdcamp** [comment]
@raphw Is it possible that when tests are run/executed in Android Studio / IntelliJ it might cause mock maker fire off? (sorry I don't know much about "mock maker")

**Comment by raphw** [comment]
That should not happen, for Kotlin, it might however make sense as most types are final by default.

You can set a break point in the `MockUtil::createMock` method and see what instance of `MockMaker` you have (Inline or Subclass) to see what plugin is loaded.

**Comment by jeffdcamp** [comment]
It appears to be "InlineByteBuddyMockMaker"

**Comment by raphw** [comment]
In this case, you are using the inline mock maker to support mocking of final types. I am afraid that the lookup of visibility bridges still takes too long. I will try to further improve the runtime.

**Comment by jeffdcamp** [comment]
Awesome!  Let me know if there is anything else you would like me to test/try/identify

**Comment by raphw** [comment]
I tried caching the entire graph. Could you try the performance-fix branch once more?

**Comment by jeffdcamp** [comment]
It's fixed!

The latest code on the "performance-fix" branch is back to expected speeds!  Good work!

**Comment by raphw** [comment]
Its still preliminary as it leaks memory, unfortunately. I have to work a bit more with it before merging.

Good to know that the approach is right, though! Thanks for checking

**Comment by jeffdcamp** [comment]
Let me know if you would like me to rerun my tests with updated code.

**Comment by TimvdLippe** [comment]
Thanks @jeffdcamp for the report and awesome @raphw to find the fix so quickly :heart:

**Comment by PaulWoitaschek** [comment]
Does the inline work for you in 2.9.0? Several tests here fail when mocking kotlin classes, but work in 2.8.47

**Comment by ming13** [comment]
@PaulWoitaschek, take a look at the #1183
