### ISSUE TITLE
doReturn with varargs

### ISSUE THREAD

**Issue by rdp** [mockito/mockito#118]
Basically, since we have when(mock.method()).thenReturn(x,y,z)
it would be nice to have a complementary
doReturn(x,y,z).when(mock).method()
today there is no vararg doReturn.

ref: https://groups.google.com/forum/#!topic/mockito/dHioyTNJ-ZM

**Comment by bric3** [comment]
Closing, see https://github.com/mockito/mockito/pull/129#issuecomment-68723742

**Comment by bric3** [comment]
Reopened for changelog generation

**Comment by ChristianSchwarz** [comment]
@bric3 can we close this?

**Comment by bric3** [comment]
yes thansk @ChristianSchwarz
