### ISSUE TITLE
Travis CI ERROR: JAVA_HOME is set to an invalid directory

### ISSUE THREAD

**Issue by szczepiq** [mockito/mockito#1182]
Travis CI builds started failing with "ERROR: JAVA_HOME is set to an invalid directory: /usr/lib/jvm/java-7-oracle". [Example failure](https://travis-ci.org/mockito/mockito/jobs/270842998).

```
$ ./gradlew build idea -s -PcheckJava6Compatibility && ./gradlew ciPerformRelease
ERROR: JAVA_HOME is set to an invalid directory: /usr/lib/jvm/java-7-oracle
Please set the JAVA_HOME variable in your environment to match the
location of your Java installation.
```

It looks like there was some incompatible change rolled out in Travis CI.

**Comment by TimvdLippe** [comment]
This was fixed in #1184
