### ISSUE TITLE
Ensure spring-boot can use Mockito public API

### ISSUE THREAD

**Issue by mockitoguy** [mockito/mockito#1191]
### Problem

Mockito framework integrators need robust public APIs from us. This way, they ship great Mockito integrations to their customers. We want to avoid the situation where framework integrators have to use Mockito internal APIs. This leads to overhead, relying on stale versions of Mockito, class conflicts in runtime.

spring-boot currently uses some internal API from Mockito. See https://github.com/spring-projects/spring-boot/issues/10352 for the problem statement, solution options and chosen design. 

### Solution

As discussed in spring-boot ticket, here's the API we would like to prototype:

- New "VerificationStartedListener"
- The instance of listener can be passed on mock creation
- Listener is notified when 'Mockito.verify' is invoked but before the verification is triggered
- It is possible to replace the mock object that is being verified (key feature needed by spring-boot)

### Example usage

```Java
mock(Foo.class, withSettings().verificationStartedListeners(new VerificationStartedListener() {
  public void onVerifyStarted(VerificationStartedEvent event) {
    event.getMock();
    event.setMock(arbitrayObject);
  }
}
```

**Comment by szczepiq** [comment]
I put together a prototype in "mockito-spring-boot" branch. Opened PR #1192 for visibility. How to use it?

- clone mockito and check out "mockito-spring-boot" branch
- ./gradlew publishToMavenLocal
- grab newly published version of mockito from maven local and try it out!
- I don't have Javadocs yet. This test class documents the new API (hopefully :) -> https://github.com/mockito/mockito/pull/1192/commits/1d2cd207621c13251ef89b4d7e6ca9178f8115e8?diff=unified#diff-c7b40da00e36958d90e247ac5f759871R23

Suggested next steps:

- @wilkinsona, let me know if this is enough for you to try it out!
- we can use the PR that I have opened for review comments regarding the API

**Comment by wilkinsona** [comment]
@szczepiq This looks great. I've built the `mockito-spring-boot` branch and prototyped the updates required for Spring Boot to use it: https://github.com/wilkinsona/spring-boot/tree/gh-10352. All our tests pass and, as you can hopefully see, Boot's code is now significantly simpler. Thanks very much.

**Comment by szczepiq** [comment]
Fantastic! I will polish the code / documentation and get the release out soon. Thank you for testing this out and suppling sample project!

**Comment by szczepiq** [comment]
@wilkinsona, can you try out one more time for us please?

I've cleaned up the implementation and the PR in Mockito is ready to go. I want to make sure that we ship code that works for Spring Boot. I have added some extra validation for setMock() method. Other than that I think that the API has not changed since I provided the experimental. The code is in the same branch.

Thank you in advance! :)

**Comment by wilkinsona** [comment]
@szczepiq Thanks for the opportunity to double-check things. I've built the current head of `mockito-spring-boot` branch and updated my prototype to use the resulting 2.11.0 binaries. The only change that was necessary was to update the version number so things look good from my perspective.

**Comment by mockitoguy** [comment]
We released new version today: 2.11.0. It includes the new API that Spring Boot can use.

**Comment by mockitoguy** [comment]
@wilkinsona - thank you for help and nice collaboration!

**Comment by TimvdLippe** [comment]
Closing per https://github.com/spring-projects/spring-boot/commit/027c5a0e35b81259191cae8236a1939e5e4827de :tada:

**Comment by maryroseMXXXVI** [comment]
I didn't see what is the major concern of mockito it appears 404 not see on my Github
