### ISSUE TITLE
Add Matchers.any(Object) or Marchers.any(Type)

### ISSUE THREAD

**Issue by rafaelmborges** [mockito/mockito#120]
`Matchers.any(Object)` can receive any object, and via reflection, `any()` can figure out the right type (including generics). Ex.: `any(new ImmutableSet<Foo>())`

Or maybe have a `Type` class, something like guice's `Key`. Ex: `any(new Key<ImmutableSet<Foo>>())`

**Comment by bric3** [comment]
Changes like that will be reported in #194. Closing, thanks for reporting
