### ISSUE TITLE
Define feature completeness of Mockito 2

### ISSUE THREAD

**Issue by TimvdLippe** [mockito/mockito#1210]
We have been talking about "Mockito 3" as the next major version supporting Java 8 and up. However, thus far we have not defined what feature completeness means for Mockito 2. We have been updating `master` from time to time with updates from Mockito 2, but at some point we should switch from `release/2.x` to developing on `master` again.

Which features do we want include into Mockito 2?

@mockito/core Feel free to update this issue description with a list of checkboxes of what you want to see.
@mockito/community Feel free to voice any feature you definitely want to see in Mockito 2. Keep in mind that we try to limit expansion of our public API, as we will review this when we are moving to Mockito 3. (Especially in terms of lambda-friendliness and such)

**Comment by ChristianSchwarz** [comment]
Wish list:
 * #472 Unify after() and timeout() 
 * #358 Enhancement: ArgumentCaptor.captureIf(ArgumentMatcher) 
 * #339 Last Invocation Verification Mode
 

to be continued ;-)

**Comment by TimvdLippe** [comment]
> #472 Unify after() and timeout()

Depending on our definition of the public API in Mockito 3, this could be included in either 2 or 3. I just want to prevent us from shipping an API that we revamp (or revamp related features) in the immediate next major version.

> #358 Enhancement: ArgumentCaptor.captureIf(ArgumentMatcher)

This seems to be (yet another :cry: ) generics issue. We should probably investigate the overall scope of issues and see how we can update our API  to handle generics fully. E.g. if we can update all of our API (whenever we do matching, verification, anything) to handle generics gracefully, we should probably do that first. In other words: this issue is mostly a symptom of a bigger issue, namely lack of generics support.

**Comment by ChristianSchwarz** [comment]
>> #358 Enhancement: ArgumentCaptor.captureIf(ArgumentMatcher)

>This seems to be (yet another :cry: ) generics issue.

I don't see a problem with generics in the `T captureIf(ArgumentMatcher<T>)` proposal, can you elaborate? I am more afraid of mockito's vararg expanding. Anyway it is possibly better to shift to an alternative API -> https://github.com/ChristianSchwarz/mockito-lambda/issues/5

**Comment by TimvdLippe** [comment]
Closing as duplicate of #1517
