### ISSUE TITLE
Cannot verify varargs parameter as an array

### ISSUE THREAD

**Issue by paulduffin** [mockito/mockito#1222]
Cannot verify the varargs by comparing with an array.
```
    @Test
    public void shouldVerifyVarargsAsArray() throws Exception {
        IMethods mock = mock(IMethods.class);

        mock.mixedVarargs("1", "2", "3");

        verify(mock).mixedVarargs(any(), eq(new String[] {"2", "3"}));
    }
```

**Expected:** test runs successfully
**Actual:** the test fails with an argument mismatch error.

```
org.mockitousage.verification.BasicVerificationTest > shouldVerifyVarargsAsArray FAILED
    Argument(s) are different! Wanted:
    iMethods.mixedVarargs(<any>, ["2", "3"]);
    -> at org.mockitousage.verification.BasicVerificationTest.shouldVerifyVarargsAsArray(BasicVerificationTest.java:125)
    Actual invocation has different arguments:
    iMethods.mixedVarargs("1", "2", "3");
    -> at org.mockitousage.verification.BasicVerificationTest.shouldVerifyVarargsAsArray(BasicVerificationTest.java:123)
    ...
```

This was found while upgrading from 1.9.5. In that version it was possible to achieve something similar by creating a custom ArgumentMatcher that implemented VarargMatcher. In that case the ArgumentMatcher was given the varargs as an array. However, in the latest version the same matcher is passed each vararg separately which prevents it from matching.

It is not possible to inline the array as follows because in the actual code the contents of the array are passed as an array into the method that does the verification.
`
    verify(mock).mixedVarargs(any(), eq("1"), eq("2"));
`

I tried doing something like this:
```
    verify(mock).mixedVarargs(any(), inline(new String[] {"1", "2"}));
  }
  public static <T> T inline(T[] array) {
    for (Object o : array) {
      eq(o);
    }
    return null;
  }
```

But that failed in MatchersBinder because the number of matchers provided (3) did not match the number of arguments passed in the invocation (2).

I also tried to remove the VarargMatcher from the custom ArgumentMatcher but that failed too as the number of arguments did not match in MatcherApplicationStrategy.

**Comment by TimvdLippe** [comment]
You upgraded from 1.9.5. Are you upgrading to Mockito 2 straight away or
1.10 first?

**Comment by paulduffin** [comment]
I'm actually going from 1.9.5 to 1.10.19 but 1.10.19 removed the special support for varargs in ArgumentCaptor (captureVargarg() and getVarargsValues()) which broke some tests. I fixed the tests to use capture() and getAllValues() respectively but they did not work because vararg capturing was broken.

I then patched in changes from 2.2.5 (026ba1dd1140545ea125b00a6ed3c97a91bd899f) but had to undo some of the work done to avoid depending on hamcrest (i.e. 7f20e63a7252f33c888085134d16ee8bf45f183f, ca6896347965ec1354d9e0439d9389839fc9bc5f, 35786f34e99802ff57cc3134869f82f493a30269).

I then had to patch MatcherApplicationStrategy.isLastMatcherVarargMatcher to handle
when the VarargMatcher is decorated by another class, typically LocalizedMatcher. That is not needed in the latest version because during the hamcrest changes the need to decorate matchers, including the MatcherDecorator interface, was removed.

That left me with this issue (which is hopefully the last).

**Comment by paulduffin** [comment]
The only way that I can see that this can be easily and reliably achieved is to have a special method for matching against the varargs as an array.

e.g. Something like
```
    @Test
    public void shouldVerifyVarargsAsArray() throws Exception {
        IMethods mock = mock(IMethods.class);

        mock.mixedVarargs("1", "2", "3");

        verify(mock).mixedVarargs(any(), varargsAsArray(eq(new String[] {"2", "3"})));
    }
```

Attempting to automatically infer when it should be treated as a vararg and when it should not is almost certainly going to have some edge cases when it cannot be detected properly. e.g. if we use the number of arguments (raw and expanded) against the number of matchers then we cannot differentiate between them when a single vararg matcher is provided, e.g. in the following we cannot determine whether the eq(...) matcher should be provided the single vararg directly, or wrapped in an array.

```
    @Test
    public void shouldVerifyVarargsAsArray_singleVararg() throws Exception {
        IMethods mock = mock(IMethods.class);

        mock.mixedVarargs("1", "2");

        verify(mock).mixedVarargs(any(), eq(new String[] {"2"}));
    }
```

If the matchers provided the type of object that they were going to accept then it would be possible to tell whether to pass the single vararg directly or wrapped in an array in order to make it pass but that would result in false positives when the matcher is expecting an array of a single null value but the method is called with a null array. e.g.

```
    @Test
    public void shouldNotVerify_nullArrayDifferentFromArrayContainingNull() throws Exception {
        IMethods mock = mock(IMethods.class);

        mock.mixedVarargs(null, (String[]) null);

        verify(mock).mixedVarargs(any(), eq(new String[] {null}));
    }
```

Adding varargsAsArray would also address #584 (although as I have commented there is a work around using getAllValues()). e.g.

```
@Test
public void shouldCaptureVarArgsAsArray() throws Exception {
    ArgumentCaptor<String[]> varargCaptor = ArgumentCaptor.forClass(String[].class);

    mock.varargs("1","2");   

    verify(mock).varargs(varargsAsArray(varargCaptor.capture()));

    assertThat(varargCaptor).containsExactly(new String[]{"1","2"});
}
```

**Comment by TimvdLippe** [comment]
Sadly I was not involved in the project back then. Hopefully @mockitoguy can shine some light on this issue and has an idea to tackle it.

**Comment by ChristianSchwarz** [comment]
Duplicates:  #584
Relates to: #74, #201, #211, #439, #565, #567, #583

Solution:
 * varargs must not be expanded and treaten as plain array
 * to match elements of the vararg-array a special matcher like `<T> T[] vararg(T ...args)` can be provided
 * this `vararg(..)` matcher can be treaten as special matcher on mockitos internal matcher stack that applies the passed matchers on the vararg-elements. 
 * this can't be solved in mockito 2 due to compability

**Comment by paulduffin** [comment]
Why do you say it cannot be solved in mockito 2 due top compatibility? I have a solution that appears to work and will upload soon.

**Comment by ChristianSchwarz** [comment]
@paulduffin 
>Why do you say it cannot be solved in mockito 2 due top compatibility?

This was related to the the proposal I described above. I see we had pretty similar ideas how to solve it.

>I have a solution that appears to work and will upload soon. 
Yeah I looked into your PR, it looks great. Your solution is more generic/better than the idea I had in mind :thumbsup:.

**Comment by alycecil** [comment]
It looks like https://github.com/mockito/mockito/pull/1461/files still fixes it, and can just be included as needed in test code. But it would be a nice to have.

**Comment by alycecil** [comment]
Thank you!

**Comment by big-andy-coates** [comment]
With https://github.com/mockito/mockito/pull/2807 merged, this works as expected:L

```java
@Test
public void shouldCaptureVarArgsAsArray() throws Exception {
    ArgumentCaptor<String[]> varargCaptor = ArgumentCaptor.forClass(String[].class);

    mock.varargs("1","2");   

    verify(mock).varargs(varargsAsArray(varargCaptor.capture()));

    assertThat(varargCaptor).containsExactly(new String[]{"1","2"});
}
```

... passes...
