### ISSUE TITLE
Ensure auto-replacement of deprecated methods in IntelliJ

### ISSUE THREAD

**Issue by TimvdLippe** [mockito/mockito#1225]
Per https://blog.jetbrains.com/idea/2017/10/intellij-idea-2017-3-public-preview IntelliJ can now auto-suggest replacements for deprecated methods. Once IntelliJ 2017-3 is published, let's check whether our deprecations satisfy the requirements for this check.

Maybe we can also write a static analysis check that can automatically verify that whenever we deprecated method we:
1. Link to a replacement
2. Add `@since` property
3. Is only removed in the next major version (See #945 as example)

**Comment by mureinik** [comment]
It shouldn't be too difficult to cook up a Checkstyle check that identifies a deprecated method/class that doesn't have a `@link` or `@see` tag in its javadoc. I'm not quite sure where the right place for such a check would be though. 

Can the maintainers advise on the proper place within the project structure?

**Comment by TimvdLippe** [comment]
I think this should be in the checkstyle.xml and then any custom
implementation code in a new folder. I have this issue planned for today,
so will report how far I can get :)

**Comment by TimvdLippe** [comment]
So I have tried to make this work for the past couple of hours, but unsuccesfully. I am unable to get the check implementation on the classpath to actually be recognized by the checkstyle configuration. If you have any knowledge of how to do this with checkstyle and Gradle, please let me know. Sadly http://checkstyle.sourceforge.net/writingchecks.html is lackluster in this regard.

**Comment by TimvdLippe** [comment]
Oh, my attempt is available at https://github.com/mockito/mockito/tree/custom-checkstyle

**Comment by TimvdLippe** [comment]
Intellij 2017.3 has been released: https://www.jetbrains.com/idea/whatsnew/#v2017-3

**Comment by TimvdLippe** [comment]
I no longer think we should pursue this effort.
