### ISSUE TITLE
Mockito build should not try to install anything to /usr/lib/node_modules by default

### ISSUE THREAD

**Issue by szpak** [mockito/mockito#1233]
The build of the recent Mockito is trying to install some Node JS modules globally in the system on just `gw check`. Probably no-one sane runs the build from root, but it's a bad practice IMHO.

```
> Task :javadoc
...
Installing sw-precache globally
npm WARN checkPermissions Missing write access to /usr/lib/node_modules
npm ERR! path /usr/lib/node_modules
npm ERR! code EACCES
npm ERR! errno -13
npm ERR! syscall access
npm ERR! Error: EACCES: permission denied, access '/usr/lib/node_modules'
npm ERR!  { Error: EACCES: permission denied, access '/usr/lib/node_modules'
npm ERR!   stack: 'Error: EACCES: permission denied, access \'/usr/lib/node_modules\'',
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'access',
npm ERR!   path: '/usr/lib/node_modules' }
npm ERR! 
npm ERR! Please try running this command again as root/Administrator.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/foo/.npm/_logs/2017-10-29T23_39_39_312Z-debug.log
NPM is not installed. Aborting generating service-worker
```

I would prefer to even do not install npm modules locally (in the user home directory) in the default build. Only on Travis (or on demand) with the extra `-P` switch.

**Comment by TimvdLippe** [comment]
Yeah I have been getting more annoyed about this npm install. Sadly the
theory of the service-worker does not work in practice with javadoc.
Probably its best just to revert it all. Nice experiment, sadly didnt work
out as desired :(

**Comment by mockitoguy** [comment]
Happy to see this fixed!
