### ISSUE TITLE
Enable Checkstyle rule for checking existence of license headers

### ISSUE THREAD

**Issue by TimvdLippe** [mockito/mockito#1239]
Whenever we add new files to the repository, we usually forget to add our license headers. This results in PRs such as #1227 where retroactively we add the license headers.

CheckStyle has a rule called [`Header`](http://checkstyle.sourceforge.net/config_header.html) which can enforce that we add our license header. I would propose to start enabling this rule to make sure all our source files comply to our licensing.

@mockito/core yay/nay?

**Comment by raphw** [comment]
Think it makes sense to add a check since we have it. Without it, the project will just always be inconsistent.

**Comment by mockitoguy** [comment]
Absolutely +1. Thank you!
