### ISSUE TITLE
fetchContributors always run, even when not releasing

### ISSUE THREAD

**Issue by TimvdLippe** [mockito/mockito#1248]
The task `fetchContributors` is always run, even when I am not calling `performRelease`. This happens when I execute `./gradlew clean test` or `./gradlew clean build` for example. Would be great if this task is not executed if I am not invoking any release task.

**Comment by mockitoguy** [comment]
I agree completely. Thank you for reporting!

Can you report issues and feature requests directly to Shipkit issue tracker? This helps us manage the tickets :)

**Comment by TimvdLippe** [comment]
Ah right. Done at: https://github.com/mockito/shipkit/issues/566
