### ISSUE TITLE
API changes report for Mockito

### ISSUE THREAD

**Issue by lvc** [mockito/mockito#1251]
Hi,

I'd like to share report on API changes and backward compatibility for the Mockito library: https://abi-laboratory.pro/java/tracker/timeline/mockito/

BC — binary compatibility
SC — source compatibility

The report is generated according to the article https://wiki.eclipse.org/Evolving_Java-based_APIs_2 by the https://github.com/lvc/japi-tracker tool.

Hope it will be helpful for users and maintainers of the library.

Is there a snapshot jar for the library, so I can run daily analysis for it?

Thank you.

![mockito-1](https://user-images.githubusercontent.com/1517837/32481134-13a9d180-c3a3-11e7-826b-61952a043f2e.png)

![mockito-2](https://user-images.githubusercontent.com/1517837/32481132-13637956-c3a3-11e7-8841-3d1ed4b35973.png)

**Comment by TimvdLippe** [comment]
We have previously looked at this tool. The main problem back then was that it was unable to remove `org.mockito.internal` classes from the report. It seems that it is able to deal with that now.

Some comments:

1. [2.1.0-2.2.29](https://abi-laboratory.pro/java/tracker/compat_report/mockito/2.1.0/2.2.29/f8d65/bin_compat_report.html) `MockitoFramework.addListener ( MockitoListener p1 ) [abstract]  :  void ` is not removed, it now has a new returnType `MockitoFramework`. This should be backwards compatible for all usages of this API. (The interface is not meant to be implemented by users of this library).
1. [2.6.9-2.7.22](https://abi-laboratory.pro/java/tracker/archives_report/mockito/2.6.9/2.7.22/report.html) `MockSettings.useConstructor ( ) [abstract]  :  MockSettings ` now has varargs argument `Object...` which is also backwards compatible.

We mostly treat our interfaces as user-facing, but not meant to be implemented by users. It allows us to define a clean contract between our implementation and how the user uses our API.

All in all, we depend on our test suite to make sure we remain backwards compatible. Existing tests are not allowed to change between patch and minor versions, unless they explicitly test internal APIs only. Our package `org.mockitousage` is specifically targeted to testing backwards compatibility. The sub-package `bugs` is where we add extra test suites for regression testing.

Whenever we merge a pull request, a new version is automatically pushed to [Bintray](https://bintray.com/mockito/maven). The package `mockito-development` hosts all our incremental versions.

Is there an actionable item right now for us or shall we close this issue? (Feel free to open a new issue whenever you think we broke our backwards compatibility contract).

**Comment by TimvdLippe** [comment]
Closing this issue as there is no actionable item for us. Hopefully our feedback was useful @lvc

**Comment by lvc** [comment]
Hello,

> 2.1.0-2.2.29 MockitoFramework.addListener ( MockitoListener p1 ) [abstract] : void is not removed, it now has a new returnType MockitoFramework. This should be backwards compatible for all usages of this API. (The interface is not meant to be implemented by users of this library).
    2.6.9-2.7.22 MockSettings.useConstructor ( ) [abstract] : MockSettings now has varargs argument Object... which is also backwards compatible.

Yes, both cases are source-compatible. And this is stated in the report in the `SC` section. But both cases break binary-compatibility with the `NoSuchMethodError` exception when trying to call these methods by old clients without recompile.

> We mostly treat our interfaces as user-facing, but not meant to be implemented by users.

I've marked all interfaces as non-implementable by users. Added methods to interfaces will not be reported anymore as source-incompatible changes. Reports are regenerated.

Thanks a lot for the great review!
