### ISSUE TITLE
ArgumentMatchers support for @NonNull / Kotlin non-null

### ISSUE THREAD

**Issue by olivierg13** [mockito/mockito#1255]
Hello folks,

There is an issue when using ArgumentsMatcher.eq() method with either:
- A Java @NonNull annotated param 
- A Kotlin non-null param

Example (in kotlin):
- Let's say you have a method:
`doSomething(test: String) {...}`
- When trying to do:
`Mockito.verify(mock).doSomething(ArgumentMatchers.eq("toto"))`

At runtime the test is going to fail with message:
`java.lang.IllegalStateException: ArgumentMatchers.eq("toto") must not be null`

Is there a way to return NonNull objects from the eq method?

Thank you in advance :)

**Comment by TimvdLippe** [comment]
I am going to publish a prototype soon that can probably address this issue.

**Comment by lemartin** [comment]
The `eq` problem can be addressed quite easily. A different name was only chose to not get into import hell.
```kotlin
fun <T : Any> safeEq(value: T): T = eq(value) ?: value
```

**Comment by ChristianSchwarz** [comment]
This can be fixed in mockito by changing

```java
public static <T> T eq(T value) {
        reportMatcher(new Equals(value));
        if (value == null)
            return null;
        return (T) Primitives.defaultValue(value.getClass());
}
```

to

```java
public static <T> T eq(T value) {
        reportMatcher(new Equals(value));
        return value;
}
```

**Comment by mockitoguy** [comment]
I really like @ChristianSchwarz's idea because it simplifies the code. Problem is that it is a breaking change because there could be client code depending on the value returned from ```eq```. When working with test spies, the real behavior is invoked during stubbing with ```when``` syntax. That real behavior may depend on parameters. Example:

```Java
Foo spy = spy(Foo.class);
when(spy.foo(eq("blah")).thenReturn(...);
```

I like the idea of including @ChristianSchwarz's change in next major version of Mockito.

**Comment by giovannicandido** [comment]
`any` and `isA` have the same problem

**Comment by ChristianSchwarz** [comment]
You might want to take a look at https://github.com/nhaarman/mockito-kotlin, they solved the null-return problem and other's too, like the "when"-keyword issue.

**Comment by giovannicandido** [comment]
Thanks @ChristianSchwarz,

I'm using mockito-kotlin to work around this issue.

**Comment by MRezaNasirloo** [comment]
Same for `Mockito.argThat`

**Comment by capezzbr** [comment]
How is still an outstanding issue?

**Comment by sidgate** [comment]
What is the workaround for this issue?

**Comment by davidkarlsen** [comment]
@sidgate https://github.com/nhaarman/mockito-kotlin

**Comment by ChristianSchwarz** [comment]
@sidgate for a Kotlin project i suggest https://github.com/mockk/mockk

It supports your use case, suspend functions, extensions and even static functions. It comes with a Kotlin API that feels natural.

**Comment by ericntd** [comment]
Have you tried `kotlinAny()`?

**Comment by MichalDanielDobrzanski** [comment]
How is this still an outstanding issue? x2

**Comment by jmchuster** [comment]
i ended up just creating these helper functions

```
        fun <T> anyArg(): T {
            ArgumentMatchers.any<T>()
            return uninitialized()
        }

        fun <T> eqArg(obj: T): T {
            ArgumentMatchers.eq(obj)
            return uninitialized()
        }

        private fun <T> uninitialized(): T = null as T
```

**Comment by TimvdLippe** [comment]
`mockito-kotlin` is now part of the Mockito GitHub organization and officially supported. It includes the `Matchers` API that should have support for this: https://github.com/mockito/mockito-kotlin/blob/main/mockito-kotlin/src/main/kotlin/org/mockito/kotlin/Matchers.kt

Assuming these are indeed sufficient, I think we can close this issue as fixed?

**Comment by TheoCadoret** [comment]
On my side, for the eq() ArgumentMatcher, it worked with :


```
private fun <T> eq(value: T): T { 
    ThreadSafeMockingProgress.mockingProgress().argumentMatcherStorage.reportMatcher(Equals(value))
    return value
}
```

**Comment by TheHett** [comment]
On 2021 still needed to use crunch?

**Comment by MichalDanielDobrzanski** [comment]
Always when needed.

Michał Dobrzański

**Comment by TheHett** [comment]
In kotlin need to use `org.mockito.kotlin.eq`
