### ISSUE TITLE
Create class to assert return objects

### ISSUE THREAD

**Issue by saikumar-a** [mockito/mockito#1259]
Create a class `ResultCaptor `the one like below to assert return objects. Check [here ](https://stackoverflow.com/questions/7095871/mockito-spy-how-to-gather-return-values/25694262#25694262) for detailed explanation.

```java
public class ResultCaptor<T> implements Answer {
    private T result = null;
    public T getResult() {
        return result;
    }

    @Override
    public T answer(InvocationOnMock invocationOnMock) throws Throwable {
        result = (T) invocationOnMock.callRealMethod();
        return result;
    }
}
```

**Comment by onacit** [comment]
Related to #1763, and vice versa.

**Comment by mockitoguy** [comment]
I've read the linked explanation and I don't think this use case is general enough to warrant a new API. Also, it is very easy to create ResultCaptor so no need for additional public API.

Ideally, we shouldn't care about the object created by the factory mock. The factory should have its own unit tests. Here's a general use case when working with factories:

```
//production code:
Object x = factory.create();
service.call(x);

//test code:
when(factory.create).thenReturn(dummy);
verify(service).call(dummy);
```

I hope this explains my take on this feature request. Thank you for reporting! As always, reopen if needed.

**Comment by quaff** [comment]
@mockitoguy I want do some verification on return value of spied object method call like this:
```java
RedisConnectionFactory connectionFactory = Mockito.spy(actualRedisConnectionFactory);
doSomething(); // trigger redis publish
verify(connectionFactory.getConnection()).publish(any(), any()); 
```
It will fail due to 
```
org.mockito.exceptions.misusing.NotAMockException: 
Argument passed to verify() is of type LettuceConnection and is not a mock!
Make sure you place the parenthesis correctly!
See the examples of correct verifications:
    verify(mock).someMethod();
    verify(mock, times(10)).someMethod();
    verify(mock, atLeastOnce()).someMethod();
```
How can I deal without `ResultCaptor `?
```java
RedisConnectionFactory connectionFactory = Mockito.spy(actualRedisConnectionFactory);
given(connectionFactory.getConnection()).willAnswer(resultCaptor);
doSomething(); // trigger redis publish
then(resultCaptor.getResult()).should().publish(any(), any());
```
I have created https://github.com/mockito/mockito/issues/2422, feel free to close it if this one is reopen.
