### ISSUE TITLE
anyInt() neither fails nor takes effect when used as long

### ISSUE THREAD

**Issue by ryandm** [mockito/mockito#1260]
This issue slows down adoption of Mockito2. I've recently upgraded a reasonably large amount of code onto Mockito2, and a significant pain point (time drain) has been that `anyInt()` could be passed as a `long` argument to a method being mocked with no failure, yet the mock does not take effect.

Similar to the options outlined at #1204, it would be less confusing if either (1) there is a failure at the point when `anyInt()` is used, or (2) `anyInt()` has similar behavior as Mockito1 when used to match `long`-typed parameters.

The reason I filed a new issue (instead of commenting on #1204) is because I want to call attention to the extremely confusing behavior that results when this matcher is used to mock methods: When `anyInt()` is used to mock methods, the code silently proceeds and only later may it fail due to the mock not having taken effect. When upgrading from Mockito1 to Mockito2, it can take a very long time to track down the root cause of such issues.

```java
import org.mockito.Mockito;

import java.util.function.LongToDoubleFunction;

public class Repro {

  // Example was run on jdk1.8.0_111, macOS 10.12.6

  // When run with org.mockito:mockito-core:1.10.19, the stdout is:
  // mocked with anyInt: NaN
  // mocked with anyLong: NaN

  // When run with org.mockito:mockito-core:2.8.9, the stdout is:
  // mocked with anyInt: 0.0
  // mocked with anyLong: NaN

  public static void main(String[] args) {
    LongToDoubleFunction mock = Mockito.mock(LongToDoubleFunction.class);
    Mockito.doReturn(Double.NaN).when(mock).applyAsDouble(Mockito.anyInt());
    System.out.println("mocked with anyInt: " + mock.applyAsDouble(1L));
    Mockito.doReturn(Double.NaN).when(mock).applyAsDouble(Mockito.anyLong());
    System.out.println("mocked with anyLong: " + mock.applyAsDouble(1L));
  }
}
```

**Comment by SeriyBg** [comment]
I can try to work on this one. Is it confirmed as an issue? What is the desired behavior? And, maybe someone can point me to the right direction.

**Comment by TimvdLippe** [comment]
Hm, I am torn on this one as this is actually intended behavior imo. While I do agree that the difference between Mockito 1 and 2 is annoying, per https://github.com/mockito/mockito/wiki/What%27s-new-in-Mockito-2#incompatible the types passed are now actually checked. This means that a long is not of type int and thus `anyInt` will not match.

The problem with not getting any compiler warning is annoying, but sadly an artifact of Java allowing ints to be passed as longs. We have little room for improvement in that regard :cry: 

Therefore I am inclined to say (understanding that the migration requires more work) that the Mockito 2 behavior is preferred and working as intended. I do want to acknowledge the fact that a compiler error is definitely required and will be looking if I can incorporate that into #1264 That should at least help with future migrations.

**Comment by TimvdLippe** [comment]
I have updated #1264 with an example of how these kind of errors can be caught by the compiler. You can see the added test case in https://github.com/mockito/mockito/pull/1264/commits/c7a326c85d7eb446f29b2e772d9ec218ab0d91cb#diff-ec18c77ddd391ac4420ccce995a42dd4 If you uncomment line 213, the project will not compile. This makes the matching fail-fast instead of swallowing the error.

**Comment by ryandm** [comment]
My goal was to share feedback on the upgrade experience. Thanks for hearing the feedback and incorporating it into broader API thoughts/discussions. Closing since there doesn't seem to be anything concretely actionable on this issue.
