### ISSUE TITLE
Documentation mistake

### ISSUE THREAD

**Issue by pardisb** [mockito/mockito#1262]
I think the documentation here is wrong:
https://github.com/mockito/mockito/blob/release/2.x/src/main/java/org/mockito/Mockito.java#L1646 

I believe the doReturn() syntax should be used there instead. At least when I do that it works but when I do the when(myFoo.myMethod()).thenReturn() that line itself runs the real impl of myMethod.

**Comment by SeriyBg** [comment]
Fixed here: #1268

**Comment by pardisb** [comment]
Thanks!
