### ISSUE TITLE
Error misspell

### ISSUE THREAD

**Issue by MatDls** [mockito/mockito#1275]
Console error:
"org.mockito.exceptions.misusing.NotAMockException:"
                                             ^
                                        misspell

i think it should be:
"org.mockito.exceptions.missing.NotAMockException:"

**Comment by SeriyBg** [comment]
@MatDls I don't think so :)
The word misusing mean to use something in the wrong way. This exception should appear when you try to mock an instance which is not a mock. So you are misusing `when(mock)` method by passing not a mock to it as an argument.

**Comment by TimvdLippe** [comment]
Yes this is intentional. We mean the [present participles](https://www.ef.com/english-resources/english-grammar/ing-forms/) (TIL the name of this form 😄 ) of the verb `misuse`.
