### ISSUE TITLE
Cannot override stubbed method that calls a stubbed method

### ISSUE THREAD

**Issue by r-smirnov** [mockito/mockito#1279]
Mockito 2.13.0

Overriding stubbed method that calls a stubbed method in its answer may result in a number of different failure modes:

1) WrongTypeOfReturnValue is thrown.

```java
import static org.junit.Assert.assertEquals;
import static org.mockito.Mockito.mock;
import static org.mockito.Mockito.when;

import org.junit.Test;

public class TestStubbing {
    @Test
    public void test() throws Exception {
        Foo foo = mock(Foo.class);
        Bar bar = mock(Bar.class);

        when(foo.doFoo()).thenAnswer(invocation -> String.valueOf(bar.doBar()));
        assertEquals("0", foo.doFoo());

        when(foo.doFoo()).thenReturn("");
        assertEquals("", foo.doFoo());
    }

    interface Foo {
        String doFoo();
    }

    interface Bar {
        int doBar();
    }
}
```

2) Wrong method is stubbed.

```java
import static org.junit.Assert.assertEquals;
import static org.mockito.Mockito.mock;
import static org.mockito.Mockito.when;

import org.junit.Test;

public class TestStubbing {
    @Test
    public void test() throws Exception {
        Foo foo = mock(Foo.class);
        Bar bar = mock(Bar.class);

        when(foo.doFoo()).thenAnswer(invocation -> bar.doBar());
        assertEquals(0, foo.doFoo());
        assertEquals(0, bar.doBar());

        when(foo.doFoo()).thenReturn(1);
        assertEquals(1, foo.doFoo());
        assertEquals(0, bar.doBar());
    }

    interface Foo {
        int doFoo();
    }

    interface Bar {
        int doBar();
    }
}
```

3) StackOverflowError is thrown.

```java
import static org.junit.Assert.assertEquals;
import static org.mockito.Mockito.mock;
import static org.mockito.Mockito.when;

import org.junit.Test;

public class TestStubbing {
    @Test
    public void test() throws Exception {
        Foo foo = mock(Foo.class);
        Bar bar = mock(Bar.class);

        when(foo.doFoo()).thenAnswer(invocation -> bar.doBar());
        assertEquals(0, foo.doFoo());

        when(foo.doFoo()).thenAnswer(invocation -> bar.doBar() + 1);
        assertEquals(1, foo.doFoo());
    }

    interface Foo {
        int doFoo();
    }

    interface Bar {
        int doBar();
    }
}
```

The cause is that in the MockingProgressImpl the OngoingStubbing for doFoo() invocation is replaced with the OngoingStubbing for doBar() invocation.

**Comment by r-smirnov** [comment]
One potential solution is to restore the OngoingStubbing after evaluating the answer.
[MockHandlerImpl.java.patch.txt](https://github.com/mockito/mockito/files/1590092/MockHandlerImpl.java.patch.txt)

**Comment by mockitoguy** [comment]
Wow, thank you for reporting and digging deep into this problem. You nailed down another edge case of Mockito syntax! (ping @TimvdLippe, you're collecting problems with existing syntax).

One solution to this problem is using "doReturn" syntax. However, it does not really help the user. At minimum, the error message of WrongTypeOfReturnValue and friends should indicate this potential problem.

>One potential solution is to restore the OngoingStubbing after evaluating the answer

This is potentially a good idea. Can you hack it together and submit a PR? Let's see if it breaks any existing tests.

I'm a little bit worried fixing this bug because it is an incompatible change and there might be tests out there that depend on the existing behavior.

StackOverflowError needs fixing, too. It's great that you have found all problems with this use case.

BTW. I'm traveling so please pardon spotty replies.

**Comment by TimvdLippe** [comment]
I can confirm that the prototype in #1264 does not require any changes to make this work. You can see the full passing test suite at https://github.com/mockito/mockito/pull/1264/commits/a479368f17c1d2ea2e48e96b68559e457fb2d1a0

**Comment by r-smirnov** [comment]
Created a PR #1296 with [the above patch](https://github.com/mockito/mockito/files/1590092/MockHandlerImpl.java.patch.txt) applied.

**Comment by mockitoguy** [comment]
@r-smirnov, thank you very much!!! I've opened a separate PR with your commits #1310, please take a look, read the description and let me know if something is amiss.

Your PR is a fantastic contribution (I thought that his problem is not fixable!!!) and I'm really looking forward to merging!
