### ISSUE TITLE
Automate files populated in Bintray download list

### ISSUE THREAD

**Issue by TimvdLippe** [mockito/mockito#1284]
On https://twitter.com/Tustin2121/status/950832119730835462 we received feedback that for non-Maven users, the manual download of Mockito is hard to find. The end result of that Twitter discussion was that the reporter glanced over the files tab.

It appears that Bintray supports a feature called ["Download List"](https://bintray.com/docs/usermanual/downloads/downloads_manualdownloads.html#_download_list) which is posted on the main Bintray page. In our case, this states `	
No direct downloads selected for this package.`. There appears to be [this API](https://bintray.com/docs/api/#_file_in_download_list) to populate and delete entries from this list. Maybe this process can be automated?

CC @mockitoguy as author of Shipkit

**Comment by tustin2121** [comment]
I'll also suggest adding a link to the bottom of the website's "How?" section with a link to said Bintray page, in cases where people (like me) overlook the fact that you can click on the "Download" split button at the top of the site to get to the Bintray page.

**Comment by TimvdLippe** [comment]
@tustin2121 Could you open a PR with your suggestion with an update of https://github.com/mockito/mockito.github.io/blob/master/_posts/2000-01-10-how.md ?

**Comment by tustin2121** [comment]
https://github.com/mockito/mockito.github.io/pull/36

Done. Github made it far easier than I expected.

**Comment by TimvdLippe** [comment]
Closing as wont-fix. We have updated the documentation to make it more clear.
