### ISSUE TITLE
Reflection compatibility issues with Java 9

### ISSUE THREAD

**Issue by marat-gainullin** [mockito/mockito#1295]
The following warnings occur while runnting tests on Java 9:

WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.mockito.cglib.core.ReflectUtils$2 (file:/C:/Users/mg/.gradle/caches/modules-2/files-2.1/org.mockito/mockito-all/2.0.2-beta/3e24f450275812fb354d29a58b66b8f26e13002f/mockito-all-2.0.2-beta.jar) to method java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int,java.security.ProtectionDomain)
WARNING: Please consider reporting this to the maintainers of org.mockito.cglib.core.ReflectUtils$2
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release

when running th following example:

```
package com.mockitotest;

import org.junit.AfterClass;
import org.junit.BeforeClass;
import org.junit.Test;
import org.mockito.Mockito;

import javax.servlet.ServletConfig;
import javax.servlet.ServletContext;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import java.util.Collections;
import java.util.Set;

public class MockitoJava9ExampleTest {

    private static volatile ServletConfig config;

    @BeforeClass
    public static void setup() {
        ServletContext servletContext = Mockito.mock(ServletContext.class);
        Mockito.when(servletContext.getServletContextName()).thenReturn("mockito-java9");
        Mockito.when(servletContext.getInitParameterNames()).thenReturn(Collections.enumeration(Set.of(
                "p1",
                "p2",
                "p3",
                "p4"
        )));
        Mockito.when(servletContext.getInitParameter("p1")).thenReturn("v1");
        Mockito.when(servletContext.getInitParameter("p2")).thenReturn("v2");
        Mockito.when(servletContext.getInitParameter("p3")).thenReturn("v3");
        Mockito.when(servletContext.getInitParameter("p4")).thenReturn("v4");
        Mockito.when(servletContext.getInitParameter("p5")).thenReturn("v5");
        config = Mockito.mock(ServletConfig.class);
        Mockito.when(config.getServletContext()).thenReturn(servletContext);
    }

    @AfterClass
    public static void tearDown() {
        config = null;
    }

    @Test
    public void runOnlyTest() {
        Mockito.mock(HttpServletRequest.class);
        Mockito.mock(HttpServletResponse.class);
    }
}
```
Environment :
Windows 10, Java 9, Mockito dependency: 'org.mockito:mockito-all:2.0.2-beta'

**Comment by TimvdLippe** [comment]
Please use mockito-core version 2.13.0 which should not have this issue.

**Comment by TimvdLippe** [comment]
Closing per above comment. Feel free to reopen if you are still encountering this issue with the latest version of Mockito.
