### ISSUE TITLE
java.lang.NoSuchMethodError when try mockito 2.13.0 with kotlin

### ISSUE THREAD

**Issue by september669** [mockito/mockito#1302]
Hi guys, I found an issue, when I try to mock kotlin interface with 2.13.0 i get an exception

`java.lang.NoSuchMethodError: net.bytebuddy.implementation.MethodDelegation.appendParameterBinder(Lnet/bytebuddy/implementation/bind/annotation/TargetMethodAnnotationDrivenBinder$ParameterBinder;)Lnet/bytebuddy/implementation/MethodDelegation;`

But when i downgrade to 2.9.0 all works perfect

Thanks!

**Comment by raphw** [comment]
It seems like you are mixing up Byte Buddy versions somehow. Mockito 2.13 relies on a newer Byte Buddy version. If you force usage of an older version things should work out again.

What other library is in conflict here, out of curiosity.

**Comment by PandaMonkey** [comment]
@september669 Hi, Could you show your pom file? I am interested in such version conflict problems. Maybe I can help you identify the root cause.  If you concern the privacy problem, you can also send it to my e-mail:  pandamonkey1@sina.com

**Comment by 1028332163** [comment]
keyi

**Comment by september669** [comment]
Thanks a lot! I found conflicted lib.
