### ISSUE TITLE
InlineByteBuddyMockMaker does not clean up stale mocks

### ISSUE THREAD

**Issue by moltmann** [mockito/mockito#1313]
**Repro:**

1. Mockito 2.15.2 using mockito-inline
2. With -Xmx64m run
```
@RunWith(JUnit4.class)
public class Stress {
    private static final int NUM_RUNS = 20000;

    public static class TestClass {
        public String returnA() {
            return "A";
        }
    }

    /**
     * Test that mocks that are not referenced anymore are properly cleaned up.
     */
    @Test
    public void callALotOfMocks() {
        for (int i = 0; i < NUM_RUNS; i++) {
            TestClass mock = mock(TestClass.class);
            when(mock.returnA()).thenReturn("B");

            assertEquals("B", mock.returnA());

            if (i % 1024 == 0) {
                System.out.println("Mocked " + i + "/" + NUM_RUNS);
            }
        }
    }
}
```

**Expected:**

The test eventually finishes

**Observed:**

> Mocked 0/20000
> Mocked 1024/20000
> Mocked 2048/20000
> Mocked 3072/20000
> Mocked 4096/20000
> Mocked 5120/20000
> Mocked 6144/20000
> Mocked 7168/20000
> Mocked 8192/20000
> Mocked 9216/20000
> Mocked 10240/20000
> Mocked 11264/20000
> Exception in thread "main" java.lang.OutOfMemoryError: GC overhead limit exceeded
> 	at java.lang.StringCoding$StringDecoder.decode(StringCoding.java:149)
> 	at java.lang.StringCoding.decode(StringCoding.java:193)
> 	at java.lang.String.<init>(String.java:426)
> 	at java.util.jar.Attributes.read(Attributes.java:418)
> 	at java.util.jar.Manifest.read(Manifest.java:199)
> 
> Exception: java.lang.OutOfMemoryError thrown from the UncaughtExceptionHandler in thread "main"
> 
> Process finished with exit code 1

**Analysis:**

The `InlineByteBuddyMockMaker` uses a Map<WeakRef\<Mock\>, Handler> in the `mocks` field to store the mocks and their handlers. It relies that the mocks get garbage collected to remove the entry in the map. Unfortunately if there is an invocation on the mock, the handlers keep strong references to the mock in `InterceptedInvocation.mock`, `RealMethodCall.instance`, and `SerializableRealMethodCall.instance`. These are (strong) references by the handler. Hence the mock never gets cleaned up and the map grows indefinitely.

This is not a problem if the mocks get `Mockito.reset` properly or if using a mock maker that does not store the handlers.

**Comment by mockitoguy** [comment]
Fantastic analysis, thank you! Do you want to take a stab at fixing it?

(ping @raphw, original author of the this mock maker).

**Comment by raphw** [comment]
I will have a look. Great analysis indeed. We will have to weakly reference any mock instance stored in Mockito. This is a straight forwars fi, I hope.

**Comment by raphw** [comment]
I will do it once I have time. (The kid, you k ow.)

**Comment by moltmann** [comment]
I saw two problems we need to keep in mind:
- How to weak references interact with serializability
- We have to be vigilant to prevent premature cleaning up of the mock. Is there any possible case where we can gain access to the the invocations / handler without a reference to the mock?

**Comment by moltmann** [comment]
I uploaded a fix as fb37a2e proposal even though
- I don't like that we use different kind of invocations for some tests
- The tests pass and I think I serialize properly, but I am not 100% sure as I never dealt with serialization before

**Comment by mockitoguy** [comment]
Hey guys! I was reviewing @moltmann's PR and I'm wondering what are the alternative options to solve the problem. Can we attach a state to the mock object so that MockMakers can do their magic without keeping weak maps of all mocks? @raphw, thoughts?

**Comment by raphw** [comment]
Unfortunately, I do not think that there is an alternative to weak references.

The Java instrumentation API allows the retransformation of Java byte code, it does not allow changing the shape of a class, e.g. adding fields. Naturally, the dispatcher would be placed in such a field such that the life time of a dispatcher would be implicitly bound to the mock instance. But since we cannot add this field, we have to place the instance outside of it such that we have to use weak references to reach the same effect.

Therefore, I fear that this is the only way to go.

**Comment by mockitoguy** [comment]
Thank you for explanation!

One alternative/supplemental option is to make the lifecycle of mocks more formal. For example, JUnit rule / runner / mockito session can inform the mock maker that "we're done with mock x".

**Comment by moltmann** [comment]
@mockitoguy If you can make this work, great. I see my mockmaker to be used to a legacy test suites though as they want to just mock one final method and not create a new test suite. Some older suites might not use junit or any other fancy feature.

Hence I would like to find a solution that does not require any changes outside of mockito.

**Comment by moltmann** [comment]
@mockitoguy Is there any further change you want to c0ad83a?
