### ISSUE TITLE
Add mockito-scala

### ISSUE THREAD

**Issue by bbonanno** [mockito/mockito#1333]
It would be nice to have a separate module (?) with Scala specific features and syntax sugars
I've been working on this for a while now and I think I could improve the experience of using Mockito with Scala

I'm not sure what the community thinks about a separate module for it, I think it's right to keep it clean and separated as they will be some .scala files

Things I'd initially put there would be:

- Wrapping Mockito API on traits: This is so it can either be used as now (calling the static methods on Mockito or ArgumentMatchers) or just mixing in those traits to avoid having to import each thing we want to use.
- Bridge between Java and Scala: Said traits will also fix annoying issues like Scala not playing well with Java overloaded methods that use varargs (like doReturn) or renaming the eq ArgumentMatcher given that eq in Scala is a special operator to do identity equality.
- Adding support for default arguments: Currently when you stub or verify a method with default arguments the mock gets null as the value for that param instead of the default value, this is easy to fix with some default stubbings.

And more to come

Thoughts, ideas?

Thanks

Bruno

**Comment by TimvdLippe** [comment]
I do not have a lot of Scala experience nor am actively developing Scala. Could you publish a very small PR with 1 example API to show: 1. what the original problem/annoyance was and 2. how this prototype would fix it? That way we can make a judgement call whether we want a full-blown module :smile:

**Comment by bbonanno** [comment]
@TimvdLippe sure

**Comment by TimvdLippe** [comment]
@szpak Oh yes I forgot to point that out. @bbonanno for the first PR, you can create a new subproject just like https://github.com/mockito/mockito/tree/release/2.x/subprojects/kotlinTest to have this as a separate module.

**Comment by bbonanno** [comment]
@szpak @TimvdLippe Yeah, I was thinking in doing that as adding the Scala dependencies to mockito-core looks bad from the beginning.
Keep tuned, as soon as I have something decent to show the problem and solution I'll raise a PR so you guys can check it out

**Comment by mockitoguy** [comment]
Hey @bbonanno! Thank you for suggestion! Given that the core team has no expertise in Scala, most likely we won't be publishing mockito-scala from our project. Please get the prototype working in a separate project. Make it great, then for sure you will attract community!

Thanks for suggestion! I'll close this ticket to keep our issue tracker clean.

**Comment by bbonanno** [comment]
That's a problem then, I only have permission to contribute to an existing project, not to start a new one...

**Comment by TimvdLippe** [comment]
@bbonanno Sorry for the confusion. @mockitoguy and I had an internal chat regarding this topic and I would like to clarify some things:

First of all, we have to acknowledge that the current Mockito core developers have little to none Scala programming experience. Therefore, we are reluctant to incorporate sophisticated Scala code in the Mockito core project, as we would have trouble maintaining.

Having said that, my previous comment still stands. We are open to explore the extent, difficulty and impact  of a Scala-tailored solution.

Therefore I propose the following process:

1. You first open a PR with a very small contrived example of a Scala-improved API.
1. The Mockito core developer assess this PR based on the above stated points
1. If we qualify it as feasible, we would like to request you to build the full blown module
1. At this point, we will asses again
1. If we are still comfortable, we will incorporate the code in Mockito core. If we are not, we would like to request you to transfer the code to a community-maintained package.

Sorry for our confusion and the delayed response. We wanted to make sure our communication was on the same line and correct. We are looking forward to your initial PR and the discussion.

**Comment by bbonanno** [comment]
@TimvdLippe Sorry for the lack of answers, I've been off and busy, but I expect to have something to show soon!

**Comment by bbonanno** [comment]
Hi @TimvdLippe @szpak @mockitoguy 

I've raised a PR as a draft example of what I'm proposing, if you think is ok, it needs a little bit more polishing before it can be merged, but I think the code and the tests show the intention

Please let me know your thoughts

https://github.com/mockito/mockito/pull/1362

**Comment by TimvdLippe** [comment]
This has shipped in https://github.com/mockito/mockito-scala
