### ISSUE TITLE
Issue with Mockito and JpaRepository

### ISSUE THREAD

**Issue by YLombardi** [mockito/mockito#1335]
Hello,

I don't know if this an issue with Spring JPA or with Mockito but I encountered a strange behaviour.
I create 2 Controller. In the first, I inject a Service. In the second, I inject a JpaRepository.

Now I create UnitTests for both this Controller.
For the second Controller, I mock the Repository. Everything works fine.
For the first Controller, I mock the Service. The test fail.
It seems to search to inject the Repository whereas it is not used in this Controller.

I create a very simple project to reproduce this behavior : 
https://github.com/YLombardi/mockito-spring-jpa-issue

Is it my test that is wrong or a bug ?

**Comment by TimvdLippe** [comment]
I think this is an issue with Spring, not with Mockito. There is probably an issue with the dependency injection on the fields, but that is pure guessing. From a Mockito point of view, I see nothing wrong with this test.

**Comment by YLombardi** [comment]
Thanks for this quick answer.
I will post the same issue in Spring repo.
