### ISSUE TITLE
org.mockitousage.bugs.varargs.VarargsNotPlayingWithAnyObjectTest#shouldNotAllowUsingAnyObjectForVarArgs reaches fail

### ISSUE THREAD

**Issue by moltmann** [mockito/mockito#1337]
org.mockitousage.bugs.varargs.VarargsNotPlayingWithAnyObjectTest#shouldNotAllowUsingAnyObjectForVarArgs reaches the fail statement.

**Comment by moltmann** [comment]
mock.run("a", "b");
verify(mock).run((String[]) anyObject())

does not throw an AssertionError

**Comment by moltmann** [comment]
See pull request 1339

**Comment by mockitoguy** [comment]
Thank you for pointing this out! Just finishing reviewing so that it's ready to merge!
