### ISSUE TITLE
Mockito 2.17.0 is not available in Maven Central

### ISSUE THREAD

**Issue by szpak** [mockito/mockito#1345]
Despite of having a `[ci maven-central-release] Release 2.17.0` [commit message](https://github.com/mockito/mockito/commit/a269394a73a7859ebb33a8e50090196559b8a785) the release is not available in Maven Central - [404](https://repo1.maven.org/maven2/org/mockito/mockito-core/2.17.0/) (as for now - 18 hours after the release) .

Looking at the Travis [logs](https://travis-ci.org/mockito/mockito/jobs/357816711) everything seems to be ok:
```
[performRelease] :bintrayUpload - publishing to Bintray
[performRelease]   - dry run: false, version: 2.17.0, Maven Central sync: true
[performRelease]   - user/org: szczepiq/mockito, repository/package: maven/mockito
[performRelease] :performRelease
[performRelease] 
[performRelease] Release shipped!
[performRelease]     - Release notes:      https://github.com/mockito/mockito/blob/release/2.x/doc/release-notes/official.md
[performRelease] Release was using following settings:
[performRelease]  - commit message contains '[ci maven-central-release]': true
[performRelease]  - project property 'maven-central-release' exists: false
[performRelease]  - Maven Central release is enabled: true
[performRelease] 
[performRelease] BUILD SUCCESSFUL in 1m 20s
```

Could you guys check if there is no error reported in Bintray on synchronization? The version is available in the "stable" Mockito [repository](https://bintray.com/mockito/maven/mockito/2.17.0).

**Comment by TimvdLippe** [comment]
If I understand correctly, Maven Central can take up to a couple of days to
sync. Lets see if it is pushed in the next 48 hours.

**Comment by szpak** [comment]
@TimvdLippe Not exactly. The cache for their search index can be updated with some delay. However, the artifacts are usually available in the repository after a few (several minutes). My link point directly to the repository.

Nevertheless, if you don't have any other idea how to track it down (at the Bintray side), we can wait a little bit and later on asked the Sonatype guys how their see it.

**Comment by TimvdLippe** [comment]
This is the information in Bintray:

```
Sync Status
Last Synced: Sat Mar 24 16:18:47 GMT 2018
Last Sync Status: Successfully synced and closed repo.
Last Sync Errors: N/A
Note: The responsiveness of the Maven Central gateway at Sonatype fluctuates. This operation may take several minutes depending on the weather.
```

**Comment by szpak** [comment]
Looks good. Would you mind to ask the Sonatype (using their mailing list?) at the evening about the status (unless the artifacts appears automatically)?

**Comment by TimvdLippe** [comment]
I have filed https://issues.sonatype.org/browse/OSSRH-38658

**Comment by mockitoguy** [comment]
Thanks guys for reporting and tracking this problem down!

**Comment by TimvdLippe** [comment]
This has been resolved per https://issues.sonatype.org/browse/OSSRH-38658?focusedCommentId=470757
