### ISSUE TITLE
Support @Mock injection in JUnit 5 method parameters

### ISSUE THREAD

**Issue by smoyer64** [mockito/mockito#1348]
JUnit 5 has the ability to "inject" parameters into test methods via an extensible ``ParameterResolver`` interface.  The JUnit 5 users guide provides an example that shows how such a ``ParameterResolver`` can supply mock objects as test parameters as follows (shamelessly copied from https://junit.org/junit5/docs/current/user-guide/#writing-tests-dependency-injection):

```
@ExtendWith(MockitoExtension.class)
class MyMockitoTest {

    @BeforeEach
    void init(@Mock Person person) {
        when(person.getName()).thenReturn("Dilbert");
    }

    @Test
    void simpleTestWithInjectedMock(@Mock Person person) {
        assertEquals("Dilbert", person.getName());
    }

}
```

The prototype ``MockitoExtension`` provided in the JUnit 5 samples project shows a simple implementation of the required ``supportsParameter()`` and ``resolveParameter()`` methods. (See: https://github.com/junit-team/junit5-samples/blob/r5.1.0/junit5-mockito-extension/src/main/java/com/example/mockito/MockitoExtension.java)

[ ]   Add the ability to inject mock objects into test method parameters to the official ``MockitoExtension``.  References #445

**Comment by TimvdLippe** [comment]
I am 👍 for this feature with the following use case:

Initialization of local variable mocks. Previously this would be `Mock<Generic> mock = mock(Mock.class)`. However, this loses the type-signature of `Generic`. With parameter mocks, we can do `@Mock Mock<Generic> mock` and still maintain the generic type signature.

**Comment by smoyer64** [comment]
I should also note that I haven't personally used parameter resolution the way it's shown above.  Our team generally either injects the mock object at the class level and configures it in ``@BeforeEach`` **OR** we inject the mock object in the test method and configure it at the top of the test method's block.

**Comment by TimvdLippe** [comment]
Yes agreed. Rather than some "magic" shared by methods, I think a generics-type-safe replacement for local mock initialization is a lot better.

**Comment by smoyer64** [comment]
I just edited the description of this issue to include a link to the sample ``MockitoExtension`` (I had intended to provide that reference originally).  I don't know if I'd refer to the the methods sharing the parameter instance as "magic" but without looking at the code it certainly isn't clear that the parameters are the shared if the types and names match.  I definitely think that there are use-cases for this technique and the use of ``ExtensionContext.Store`` is a great way to provide references to objects from different methods.  My main concern is that when there is a name collision and the types match, you might end up with behavior that's really hard to understand (without knowing how the underlying extension works).

I'm not sure I'm a fan of the syntax you described above as it seems more redundant than ``@Mock MyWeirdThing myWeirdMock`` - I'm guessing I'm misunderstanding your intention (I get the erasure part).

**Comment by TimvdLippe** [comment]
In Junit 4, local mock initialization would be 

```java
class Test {
  @Test
  public void test() {
    Mock<String> mock = Mockito.mock(Mock.class);
  }
  class Mock<T> {}
}
```
This would issue a warning saying that the generic type of `String` is not correctly created by `Mockito.mock`. (Even though we know that our mocks will work)

With this feature, in JUnit 5, we can have:

```java
class Test {
  @Test
  public void test(@Mock Mock<String> mock) {
  }
  class Mock<T> {}
}
```
And the compiler will not warn any longer.

**Comment by smoyer64** [comment]
I don't remember ever seeing that warning - Perhaps because I've always used the Mockito runner or rule?

**Comment by TimvdLippe** [comment]
Correct. You do not get that warning when using the runner. But then you have mocks that are used in every single test. This targets the use case where you need 1 extra mock in only 1 testcase.

**Comment by smoyer64** [comment]
And if the ``MockitoExtension`` is the JUnit 5 replacement for the runner or rule, why wouldn't those warnings also be suppressed?

**Comment by TimvdLippe** [comment]
Because the point of Mock initialization is different. JUnit 4 only supported for attributes. We are now talking about method parameters. Hopefully when I implement this logic, it is more clear to you 😄

**Comment by smoyer64** [comment]
I'm not trying to be argumentative ... but as a pretty heavy user of the prototype ``MockitoExtension`` in the https://github.com/junit-team/junit5-samples project we'd have a lot of tests to update with this syntax.  We'll also need to make sure the example in the users guide and (if they're kept) the code in the junit-samples project matches the official implementation.  At this point I should probably let junit-team (I wish I could use a mention here) coordinate that with you .

@sbrannen @marcphilipp @sormuras

**Comment by TimvdLippe** [comment]
Looking at the source of https://github.com/junit-team/junit5-samples/blob/7bf40178345d5ca837579c8ddb8c025401a98788/junit5-mockito-extension/src/main/java/com/example/mockito/MockitoExtension.java I think we should be fine. I will let you know when the PR is open so that you can test that out.

One note: the Mockito team was not involved with the development of the prototype, but I think we will approach very similar capabilities.

**Comment by smoyer64** [comment]
I was looking at https://github.com/junit-team/junit5-samples/blob/master/junit5-mockito-extension/src/test/java/com/example/mockito/MockitoExtensionWithNestedTests.java because it's got a bunch of use cases including test-local mocks and the "magic" you referred to above.  Thinking though the syntax change you're describing, I'll assume that the tests would still run but with the same warning?

I do realize that the Mockito team didn't produce the prototype and it would be unrealistic to think that you should be permanently limited by it architecturally.  I did however think that the syntax "proposed" by the prototype was consistent with the field injection that already existed in Mockito.  I'm going to assume that what is produced as the official extension will be well integrated and well maintained - and I never complain about stable tooling!

**Comment by TimvdLippe** [comment]
Opened #1350 with a proposal implementation.

**Comment by TimvdLippe** [comment]
Okay, to write down the reason I think mock sharing by parameter is not a good idea:

First of all, there is a lot of duplicate code. For every test method, you need to list the mocks, which results in duplicate. Rather, using fields for these mocks removes the duplication.

Secondly, by relying on fields, the compiler will complain when you make a typo (or change a type). With parameters, you rely on the name (String-based) and the type declared. Both are not compiler safe.

Lastly, because you can rely on fields, refactoring is a lot easier, as IDE's support renaming by field. This is not possible for parameters.

For these 3 reasons, I see field mock sharing superior to parameter mock sharing and am therefore against introducing this logic in the parameter resolution.

**Comment by sbrannen** [comment]
> For these 3 reasons, I see field mock sharing superior to parameter mock sharing and am therefore against introducing this logic in the parameter resolution.

I totally understand the rationale. 👍

**Comment by filiphr** [comment]
What about support for `@Spy` and `@Captor`? Should new issues be created, or can it be part of this one?

**Comment by TimvdLippe** [comment]
`@Spy` makes no sense, as it requires a concrete instance. `@Captor` could be done. Let's discuss that in a different issue :+1: as this issue has been resolved.

**Comment by TimvdLippe** [comment]
My memory was incorrect, as #1350 has NOT been merged yet.

**Comment by filiphr** [comment]
>`@Spy` makes no sense

You are completely right 😄.

I've created #1382 for adding support for `@Captor`

**Comment by marcphilipp** [comment]
There's `Mockito.spy(Class)` which would work for a method parameter.
