### ISSUE TITLE
Introduce PluginSwitch extension point

### ISSUE THREAD

**Issue by mockitoguy** [mockito/mockito#135]
New PluginSwitch extension point allows disabling plugins dynamically. The fundamental use case for this plugin is android/dexmaker: when dexmaker is on classpath not necessarily means that we want to run with dexmaker MockMaker. See more https://code.google.com/p/mockito/issues/detail?id=406

For more information on the plugin please refer to javadoc on PluginSwitch

**Comment by lklots** [comment]
i am running into this issue myself. Is the PluginSwitch supposed to be picked up by mockito through the classpath? And once it finds it, it will filter out the dexmaker plugin based on the logic of PluginSwitch?

**Comment by wongkwokfai** [comment]
@Stuie, 
Did you manage to get PluginSwitch working?
If yes, could youd describe what you did?

Thanks
