### ISSUE TITLE
Please consider release of non-alpha version of mockito for 3.0.0-alpha+2

### ISSUE THREAD

**Issue by aam** [mockito/mockito#1352]
flutter's automatic dependency tracking doesn't support tracking `alpha` version of packages, so it will need proper release of mockito that is at 3.0.0-alpha+2.

**Comment by jonahwilliams** [comment]
@aam you want https://github.com/dart-lang/mockito/issues

**Comment by aam** [comment]
Thanks @jonahwilliams !
