### ISSUE TITLE
Simple test taking too long to run

### ISSUE THREAD

**Issue by wolfgang-wdw** [mockito/mockito#1363]
Hello,

I am using mockito 2.18.0 and the test below takes almost a second to run in IntelliJ:

```java
class MockitoWorks {

    interface Stubee {
        int getValue();
    }

    interface Stubee2 {
        int getValue();
    }

    @Test
    void CanStub() {
        Stubee stub = mock(Stubee.class);
        when(stub.getValue()).thenReturn(1234);
        assertEquals(1234, stub.getValue());
    }

    @Test
    void CanStubAgain() {
        Stubee2 stub = mock(Stubee2.class);
        when(stub.getValue()).thenReturn(1234);
        assertEquals(1234, stub.getValue());
    }

}
```

Notably, the CanStub part takes about 900ms and CanStubAgain only 80ms so I suppose it is some kind of initialisation issue. I don't use any inline mocking, just freshly added the library and wrote this code as a smoke test.

This performance sadly makes a write test/fix test/refactor cycle pretty sluggish. 
Been using and loving Mockito for years and this seems new ish? 
Any hints would be greatly appreciated.
Thanks!
Wolfgang

**Comment by wolfgang-wdw** [comment]
Nevermind, seems to be an IntelliJ issue. Tests run fine in a gradle build.

**Comment by TimvdLippe** [comment]
Are you using junit 4 or 5?

**Comment by wolfgang-wdw** [comment]
Oops, forgot to add that. I'm using Junit 5.

**Comment by wolfgang-wdw** [comment]
I ran the same test using JUnit 4 and the result is pretty much the same. I will see if I can do some profiling.

**Comment by AdeshAtole** [comment]
What are you planning to use for profiling?

**Comment by wolfgang-wdw** [comment]
Sorry I gave up on that
