### ISSUE TITLE
ByteBuddy pollutes the temp folder with agent jar's

### ISSUE THREAD

**Issue by ChristianSchwarz** [mockito/mockito#1379]
ByteBuddy leaves hundres of `byteBuddyAgent############.jar` files in Win10 under

C:\Users\<username>\AppData\Local\Temp

![grafik](https://user-images.githubusercontent.com/1437411/39305875-e43cc99c-495e-11e8-9b72-23867fa6a74d.png)

Maybe it is a good idea to check for this specific pattern at startup and delete them.

FYI @raphw

**Comment by raphw** [comment]
This file is marked for deletion on exit if it cannot be deleted directly after its use. It is only required when using the inline-mock-maker: https://github.com/raphw/byte-buddy/blob/master/byte-buddy-agent/src/main/java/net/bytebuddy/agent/ByteBuddyAgent.java#L437

**Comment by raphw** [comment]
This did however inspire me to add a mechanism to Byte Buddy that tries to use the current Byte Buddy jar as an agent jar if that is possible what should be the case for most Mockito use cases.

**Comment by raphw** [comment]
I implemented this, in the next version, I have fixed this for Java 8 and older, the upcoming one will support Java 9 and newer without an additional jar generation.

**Comment by raphw** [comment]
I included a Byte Buddy update in https://github.com/mockito/mockito/pull/1378 - This should avoid the jar creation.

**Comment by holubec-petr** [comment]
Hi, problem with byteBuddyAgent looks like fixed but I have the same problem with **mockitoboot** file.
For each unit test run, one file is created in C:\Users\<user>\AppData\Local\Temp directory.

![mockitobootfiles](https://user-images.githubusercontent.com/10357929/53241054-be7c5f80-36a0-11e9-970f-f5a5023068b8.png)

Same behavior when running unit tests from IDEA or Gradle. Problem observed on Windows 10 and Windows Server 2012. Mockito version: 2.23.4.

**Comment by raphw** [comment]
This is unfortunately not possible to fix for us, we register the jar for deletion but as we are registering it for class loading, it is not possible to delete the file before the VM exits. We can not attempt the same trick as in Byte Buddy as we need to rename the file during the creation of the jar.

**Comment by ChristianSchwarz** [comment]
@raphw 
What about deleting those files when mockito initialized the first time?

**Comment by raphw** [comment]
Hmm, what if these files are in use by another JVM? I filed a bug with Oracle.

**Comment by ChristianSchwarz** [comment]
> Hmm, what if these files are in use by another JVM?

When these files are used by the JVM, they clould be locked. This would avoid a deletion by mockito or someone / something  else e.g. the windows drive cleanup process (`%windir%\system32\cleanmgr.exe`).

>I filed a bug with Oracle.

Sounds interesting, can you post a link?

**Comment by raphw** [comment]
I am just wondering if it can interfere with test setups like Jenkins, does Windows always need to lock files to use them?

The bug is filed here: https://bugs.openjdk.java.net/browse/JDK-8219681

**Comment by ChristianSchwarz** [comment]
> I am just wondering if it can interfere with test setups like Jenkins, does Windows always need to lock files to use them?

Yes, to my understanding this is the case. Here is what I found on wikipedia:

> Microsoft Windows uses three distinct mechanisms to manage access to shared files:
> 
> - using share-access controls that allow applications to specify whole-file access-sharing for read, write, or delete[2]
> - using byte-range locks to arbitrate read and write access to regions within a single file[3]
> - by Windows file systems disallowing executing files from being opened for write or delete access
> 

When mockito/bytebuddy keeps a read or write lock on the `mockitoboot*.jar` during its runtime  then any other windows process can't delete it. Any open file locks obtained by a process will be released by the OS  once the process is gone. Assume mockito/bytebuddy creates a new `mockitoboot*.jar` on every start it should be save to delete all that are not locked.

**Comment by raphw** [comment]
Then I suggest the following: In the Mockito Inline Mock maker:

1. detect if running Windows.
2. Start a seperate demon thread
3. Scan the folder in which the temporary file of this run was created for files and remove any other file matching the pattern.

**Comment by epromi** [comment]
this is 2024 sept and the issue still exists

**Comment by asturio** [comment]
Maybe some kind of cleanup, which can be called explicitly after tests would be nice.

**Comment by raphw** [comment]
The problem is that these files are not deletable on Windows before the VM exits. When the VM exits, it is no longer possible to run code.

**Comment by ChristianSchwarz** [comment]
@all who live in the "its <this-year> and the issue still exists" part of this town.  You are dev's you can create a PR and fix today. God helps those who help themselves.

 
https://github.com/mockito/mockito/issues/1379#issuecomment-469424570
> Then I suggest the following: In the Mockito Inline Mock maker:
> 
> 1. detect if running Windows.
> 2. Start a seperate demon thread
> 3. Scan the folder in which the temporary file of this run was created for files and remove any other file matching the pattern.
> 
> Since I am not running Windows: would you be willing to create a PR?

**Comment by raphw** [comment]
A thread won't cut it as the VM must terminate. It would require a seperate process that runs detached from its host (maybe that's not a thing on Windows). It sounds rather costly, though.

**Comment by asturio** [comment]
What could also be done is, at startup of mockito to check in the temp-folder if there are any left-overs of previous runs. This could be made inside of mockito, but also outside of it. If this cleanup is called automatically from mockito, or manually doesn't really matters.

Pros:

- If you run a CI on a windows machine, the temp-dir won't be full of left-overs (many GB), but only the left-overs of the last run (some KB).

Cons:

- It's not elegant, just a workaround
- The functionality may be in ByteBuddy, not in mockito.

**Comment by Marcono1234** [comment]
> The bug is filed here: https://bugs.openjdk.java.net/browse/JDK-8219681

The bug was closed as "Won't Fix" eventually. However, I am wondering whether the JDK could actually support that by allowing `ZipFile.OPEN_DELETE` / `DELETE_ON_CLOSE` native file system functionality for that JarFile. That is, the file would be deleted when the JVM closes it.

Have started a discussion at the [core-libs-dev mailing list](https://mail.openjdk.org/archives/list/core-libs-dev@openjdk.org/thread/HDXAJP5GKR3RXGBZ7SO4IC67YFMYBTPB/) (which has moved now to the [serviceability-dev list](https://mail.openjdk.org/archives/list/serviceability-dev@openjdk.org/thread/ADDSSROUJRSA47SW67L6TTZWPVWZIEYT/)). Let's see what the JDK maintainers think and whether that could solve this issue.

**Comment by raphw** [comment]
Last time I investigated, this was not possible on Windows, but let me know if you found that changed.
