### ISSUE TITLE
Question: How to mock Consumer<> Lambda in java 8 

### ISSUE THREAD

**Issue by gadieichhorn** [mockito/mockito#1384]
This is more of a question than a bug report. I cannot find an example for this scenario.

I need to test a calss that is using another interface as dependency injection with a lambda Consumer .

    @Builder
    public class Interactor {

        private final Gateway gateway;

        void process(String message, Consumer<String> response){
            gateway.process(message, uuid -> {
                response.accept(uuid.toString());
            });
        }
    }

The dependency is defined like so:

    public interface Gateway {
    
        void process(String message, Consumer<UUID> uuid);
    }

How would I mock the Gateway so I can provide a UUID value response to my test?

This is what I tried so far:

    @Test
    void whillReturnTheInjectedUUIDValueTest() {
    
        UUID uuid = UUID.randomUUID();
    
        Gateway gateway = Mockito.mock(Gateway.class);
        Mockito.when(gateway.process("ignored", uuid1 -> {return uuid;}));
    
        Interactor.builder().gateway(gateway).build().process("ignored", s -> {
            Assertions.assertEquals(uuid.toString(), s);
        });
    }

How should I provide the return value to the consumer on the inner Gateway class?

**Comment by ChristianSchwarz** [comment]
@gadieichhorn can this ticket be closed? Seems you found a solution in the [user group](https://groups.google.com/forum/#!topic/mockito/TsmWevThhrk)

**Comment by boukewoudstra** [comment]
I can confirm that the solutions with doAnswer works for void functions. For example:

```
doAnswer(answer -> {
            var messageConsumer = (Consumer<String>) answer.getArgument(0);
            messageConsumer.accept("TestMessage1");
            messageConsumer.accept("TestMessage2");
            messageConsumer.accept("TestMessage3");
            return null;
        }).when(mockedService).process(any(Consumer.class));
```

**Comment by TimvdLippe** [comment]
Closing per the above comment.
