### ISSUE TITLE
InjectMocks doesn't re-inject new mocks to final fields when constructor injection is used

### ISSUE THREAD

**Issue by b4sus** [mockito/mockito#1389]
Hello,

My class under test uses constructor to set final field(s), which (in test) I want to create/inject by @InjectMocks and @Mock annotation before every test method. Everything works nice in first test. Second however, the @Mock is recreated, but the @InjectMocks instance is not. As a result, if I stub in second test method, it is actually different mock then class under test is using.
Example (mocikto version 2.18.3 + testng, assertj):
```
public class ConstructorInjectionProblemTest {

    interface Foo {
        Integer bar();
    }

    static class Testee {
        private final Foo foo;

        public Testee(Foo foo) {
            this.foo = foo;
        }

        public Integer fooBar() {
            return foo.bar();
        }
    }

    @InjectMocks
    private Testee testee;

    @Mock
    private Foo foo;

    @BeforeMethod
    public void prepare() {
        MockitoAnnotations.initMocks(this);
    }

    @Test
    public void test1 () {
    }

    @Test
    public void test2() {
        when(foo.bar()).thenReturn(5);

        assertThat(testee.fooBar()).isEqualTo(5);
        //fails, because foo here (in test2()) is different then the one created in prepare()
    }
} 
```
From what I can see, mocks are re-created before every test method, but FieldInitializer.initialize() (called inside ConstructorInjection) creates the Testee instance only if it doesn't exist yet - so not before test2(). Afterwards field setter injection tries to set newly created mocks to testee - what silently fails. So when I stub in test2(), foo is different instance then testee.foo.
There is couple of workarounds, eg setting testee to null in @AfterMethod or removing the @InjectMocks and creating the Testee instance manually or removing the final modifier, etc.
Is this intended or is it a bug?

Thanks,

Juraj

**Comment by yelite** [comment]
It's a known issue with InjectMock + TestNg. See https://stackoverflow.com/questions/20046210/mockito-injectmocks-strange-behaviour-with-final-fields?answertab=active#tab-top

**Comment by bric3** [comment]
Hi, this behavior is intended and [documented](http://static.javadoc.io/org.mockito/mockito-core/2.19.1/org/mockito/InjectMocks.html).

1. Mockito respects constructor injection, as it should be in object oriented programming, that means it won't modify an object if this object has been created using constructor injection. 
2. When mockito's code read the `@InjectMocks` annotation, the field might already have been set by the user or by some other framework. And Mockito doesn't know if this is the user's intention or some other framework intention to have created the instance or just a leftover, so it backs out.
3. This feature has been designed with JUnit in mind where each test method have their own instance of the test class, while TestNG creates only a single instance of the test class.

I suggest to look at [these](https://github.com/mockito/mockito/tree/release/2.x/subprojects/testng/src/main/java/org/mockito/testng) TestNG helper classes and copy these classes over your repository.

**Comment by bric3** [comment]
Closing as won't do, because injectmocks behavior should never override final fields.

**Comment by guillaumeyan** [comment]
With jUnit 5 it became possible to launch test lifecycle by class. Does mockito will upgrade and take it in account ?

**Comment by mryan43** [comment]
A quick note for anyone stumbling on this issue and wondering how to fix this.

You can "clarify the intention" for mockito by setting your injected object to null before running initMocks() to get a new instance for each test.

in the OP's example it would look like : 

```java
  @BeforeMethod
  public void prepare() {
      testee=null; // mockito issue #1389
      MockitoAnnotations.initMocks(this);
  }
```
