### ISSUE TITLE
Add anyStream() argument matcher.

### ISSUE THREAD

**Issue by bhchandra** [mockito/mockito#1392]
Currently an explicit cast of  `(Stream<T>)` to  `any(Stream.class)` and a @SuppressWarning("unchecked") annotation at the method level is required to create a generifed argument matcher for `Stream`.

Adding `anyStream()` to the argument matchers would be nice.

Thanks!

**Comment by szpak** [comment]
It's some somehow problematic in Mockito 2.x which is Java 6 compatible.

Marking as proposed Mockito 3 feature.

**Comment by bhchandra** [comment]
thanks

**Comment by ChristianSchwarz** [comment]
@bhchandra 

since you are on Java 8 or higher `Mockito.any()` does the trick. So anyStream() or other non-primitive specializations are not required anymore.

**Comment by mockitoguy** [comment]
Thank you @ChristianSchwarz for finding a viable solution! I'll close this ticket since 'any()' can be used.
