### ISSUE TITLE
why not LenientCopyTool methods use static modifier?

### ISSUE THREAD

**Issue by kevinKaiF** [mockito/mockito#1403]
see org.mockito.internal.util.reflection.LenientCopyTool.
LenientCopyTool class is a stateless tool which has no fields. 
So I can't understand why not LenientCopyTool methods use static modifier instead creating a LenientCopyTool instance when using LenientCopyTool.

Besides, org.mockito.internal.util.reflection.FieldCopier like this.

**Comment by TimvdLippe** [comment]
Closing per above comment.
