### ISSUE TITLE
No release artifacts on jcenter or maven central since 2.18.3

### ISSUE THREAD

**Issue by rkraneis** [mockito/mockito#1406]
There have been no uploads of release artifacts to either jcenter or maven central since mockito 2.18.3. Would be nice to have these :-)

**Comment by TimvdLippe** [comment]
We always have the latest version available on jcenter: https://bintray.com/mockito/maven/mockito-development We still need to publish to Maven Central. Will do that!

**Comment by TimvdLippe** [comment]
2.19.0 has been released at http://central.maven.org/maven2/org/mockito/mockito-core/2.19.0/
