### ISSUE TITLE
remove redundant thenReturn from OngoingStubbing

### ISSUE THREAD

**Issue by GodPlaysChess** [mockito/mockito#1408]
There are two methods in  `OngoingStubbing`.
```
OngoingStubbing<T> thenReturn(T value);
OngoingStubbing<T> thenReturn(T value, T... values);

```
The one, with a single argument is redundant, because based on both documentation and implementation - it is covered by the one with varargs.

On top of that, such overloading might cause interoperability issues (at least in Scala it causes compilation error due ambiguous reference), where one needs to pass empty List as the second argument explicitly. (you may look in one of the answers here https://stackoverflow.com/questions/13358705/force-single-argument-in-scala-varargs )

**Comment by bric3** [comment]
I'm opposed to this change in 2.x, because it may break exernal libraries that require binary compatibility.

I'm OK for 3.x though. Note however that requires to allocate _de facto_ an array for each `thenReturn` / `willReturn`.

Regarding scala stuff, what about _mockito sugar_ ?

**Comment by GodPlaysChess** [comment]
I am not sure how `MockitoSugar` helps. We are indeed using it - it just creates mocks (by delegating it to Mockito), but actuall `thenReturn` is still called on `OngoingStubbing` from Mockito framework.

**Comment by bric3** [comment]
I'm closing the PR/issue. I'd like to thank you for contributing to this project @GodPlaysChess. It's relly nice to take some time and contribute. Thank you !
