### ISSUE TITLE
Possible to disable MockMaker extensions?

### ISSUE THREAD

**Issue by caltseng** [mockito/mockito#1411]
Like many people, I've been running into the below AbstractMethodError. I get that there is an incompatibility with older versions of Powermock and Mockito, but those dependencies are out of my control, as I'm working on a large code base run by many teams with external dynamic dependencies pulled in. 

Is it possible to prevent the MockMaker extensions for our tests? I fixed this issue previously by pulling in the lastest version of PowerMock and using it to override other older PowerMock dependencies, but it's broken again recently. 

java.lang.AbstractMethodError: org.powermock.api.mockito.internal.mockmaker.PowerMockMaker.isTypeMockable(Ljava/lang/Class;)Lorg/mockito/plugins/MockMaker$TypeMockability;

**Comment by mockitoguy** [comment]
Please work with PowerMock team and community to resolve this problem.

AFAIK, latest PowerMock does not use internals of Mockito so this sort of error should not happen.

I totally sympathize with your situation. You want your teams to be able to write tests uninterrupted. Please understand that we are not responsible for other projects (e.g. PowerMock) that use Mockito APIs incorrectly, and expose their users (e.g. you) to issues. Please understand that PowerMock uses all sorts of hacks to perform its magic. If you are using PowerMock, you need to accept future breakages and some maintenance burden on your team. That's the cost of being able to mock the unmockables.

Don't take it as trolling/hating PowerMock - I very much respect the PowerMock team for finding creative ways to solve a set of problems. I don't allow to use PowerMock in any of the teams I work with. If you do, please understand the implications.

I hope you will be able to resolve the issue and keep writing great tests :)
