### ISSUE TITLE
Fixes for issues #188, #211 not back-ported to Mockito 1.x

### ISSUE THREAD

**Issue by tpdi** [mockito/mockito#1412]
We still use Mockito 1.x because PowerMock only "experimentally" supports Mockito 2.x.

However, we can't upgrade from Mockito 1.9.5 to 1.10.x (any version of 1.10.x) because the bug described in #188 and fixed by #211, failure to capture arguments in mock varargs methods, was introduced in 1.10.5.

Would it be possible to back-port the fix introduced in #211 and release a version 1.10.20 with the fix?

Thanks.

**Comment by TimvdLippe** [comment]
We no longer release and support Mockito 1, so we are not making special releases sorry.
