### ISSUE TITLE
Not Stubbing Mocked Abstract Class

### ISSUE THREAD

**Issue by crsmith20** [mockito/mockito#1415]
I am using Mockito along with Spring's testing tools to test a controller class. In the controller class I am mocking an abstract class that has a method called in the controller. So I use when().thenReturn() to stub the method for the expected outcome. However, the given answer is not found in the stubbing procedure so it stubs the default answer. I have used almost the exact same set up on previous tests using the same class but with a different method and that works fine but it is something related to this method of the abstract class. I have used verify to make sure the mock was being called which it is but it just isn't stubbing the correct answer.

So in order to test the controller I am using Spring's MockMvc to perform a get request. This is my test class:

		

	when(abstractClazz.getResults(Mockito.anyString(), Mockito.anyString(), Mockito.anyListOf(Long.class),
				Mockito.anyListOf(String.class), Mockito.anyListOf(String.class), Mockito.anyListOf(String.class),
				Mockito.anyListOf(Boolean.class), Mockito.anyListOf(Long.class))).thenReturn("Success");

	MvcResult result = mockMvc.perform(get("/productFinder?g=something")
				.header("Content-type", "application/json")
				.header("website", "somewebsite.com"))
				.andExpect(status().isOk()) 
				.andReturn();
				
	verify(abstractClazz).getResults("something", "somewebsite.com", new ArrayList<Long>(), null, null, null, null, new ArrayList<Long>());
		LOG.info("Verification Successful!");
		assertEquals("Stub happens", "Success", result.getResponse().getContentAsString());`

and this is my controller:

		public ResponseEntity<String> productFinder(Model model,
			@RequestParam(value = "g", required = true) String groupURL,
			@RequestParam(value = "a", required = false) long[] attr,
			@RequestParam(value = "l", required = false) long[] locs,
			@RequestParam(value = "p", required = false) List<String> priceRanges,
			@RequestParam(value = "r", required = false) List<String> reviews,
			@RequestParam(value = "i", required = false) List<String> avail,
			@RequestParam(value = "n", required = false) List<Boolean> newArrival,
			@RequestParam(value = "per", required = false) Integer per,
			@RequestParam(value = "sort", required = false) String sortBy,
			@RequestParam(value = "page", required = false) Integer page, HttpServletRequest request) {

		String result = null;

		try {
			result = abstractClazz.getResults(groupURL, RequestUtility.getWebsite(request), arrayToList(attr), priceRanges, reviews, avail, newArrival, arrayToList(locs));
		} catch (Exception e) {
				//
		}
		if (null != result) {
			return new ResponseEntity<String>(result, getResponseHeaders(), HttpStatus.OK);
		} else {
			return new ResponseEntity<String>(HttpStatus.INTERNAL_SERVER_ERROR);
		}
	}
Now an assertion error is being thrown in the andExpect(status().isOk()) because based on the code in the controller it throws an Internal Server Error result == null, which it is since the stubbed method didn't return the correct stub.

Specs:
Windows 7 64-bit
Mockito 2.18.3
Springframework 4.1.9
byte-buddy 1.8.5
byte-buddy-agent 1.8.5
JDK1.8.0_172

I have git repository [here](https://github.com/crsmith20/AbstractClassStubbing) that has isolated and replicated the issue I am having.

**Comment by TimvdLippe** [comment]
This is likely not an issue with Mockito but with `MockMvcBuilders`. Please open an issue on their list if you still run into it.
