### ISSUE TITLE
Return Optional.empty instead of null for Optional return type

### ISSUE THREAD

**Issue by mdeinum** [mockito/mockito#1416]
Currently when using Mockito the default behavior is to return `null` for regular objects including `Optional` return types. Instead of returning `null` it would be better to return `Optional.empty()` in those cases.

**Comment by szpak** [comment]
Hmm, strange. It was [implemented](https://github.com/mockito/mockito/issues/191) long time ago. What Mockito version do you use?

**Comment by mdeinum** [comment]
Interesting. It wasn't actually my code, but rather after a question I answered on Stackoverflow (see https://stackoverflow.com/questions/51058898/spring-data-jpa-findbyid-method-returning-null-instead-of-empty-optional/51059172#51059172). 

Judging from the fact that he was using Spring Boot with a recent Spring Data JPA version I (probably wrongly) assumed it was an omission in Mockito.

**Comment by szpak** [comment]
You might be right. There is no Mockito mentioned in the question. Closing.
