### ISSUE TITLE
Add JSR 305 annotations (@NonNull / @Nullable)

### ISSUE THREAD

**Issue by cristan** [mockito/mockito#1420]
In Kotlin, I have the following code:

`@get:Rule val mockitoRule = MockitoJUnit.rule()`

This gives the following warning (on the currently latest version of Mockito: 2.19.0):

> Declaration has type inferred from a platform call, which can lead to unchecked nullability issues.

The issue is that Kotlin doesn't know whether the return value can be null or not. I can solve the warning by specifying my rule as non-null:
`@get:Rule val mockitoRule: MockitoRule = MockitoJUnit.rule()`
This is boilerplate code and puts the burden of checking whether MockitoJUnit.rule() can be null to every user of Mockito. 

This issue is non-existent if MockitoJUnit#rule would be annotated with `@NonNull`. 

I am sure there are many more instances where an explicitly provided nullability would be very welcome. Therefore, JSR 305 annotations should be added.

**Comment by TimvdLippe** [comment]
Sounds like a good idea. Feel free to submit a PR with the annotations and the corresponding tests in the kotlin subproject.

**Comment by whyicantusemyemailasusername** [comment]
Please don't use jsr 305. Long read here: https://github.com/google/guava/issues/2960

**Comment by ChristianSchwarz** [comment]
If you use Kotlin then you should consider [KMock](https://github.com/kmock) which integrates much better than Mockito to the language.

**Comment by TimvdLippe** [comment]
For Kotlin projects, we now recommend `mockito-kotlin`: https://github.com/mockito/mockito-kotlin If you are still running into any issues, please open an issue over there.
