### ISSUE TITLE
Mockito mock java method class NullPointerException

### ISSUE THREAD

**Issue by standup-jb** [mockito/mockito#1423]
I use the powermockito mock a final class .but the mock object is the null .I can't find out the reason. Could you please help me to solve this issue. My code like below.

@RunWith(PowerMockRunner.class)
@PrepareForTest(Method.class)
public class MnslistenerParserTest {

    @Test
    public void testOnApplicationEvent() {
   Method methodMock = PowerMockito.mock(Method.class);
}
}
I use the IDE debug . The methodMock is null.

**Comment by fabasoad** [comment]
Just tried this code on my machine. Here is the output message:
> org.mockito.exceptions.base.MockitoException: 
Mockito cannot mock this class: class replica.java.lang.reflect.Method$$PowerMock0.
>
>Mockito **can** only mock non-private & **non-final** classes.
If you're not sure why you're getting this error, please report to the mailing list.

Maven configuration:
```xml
<dependencies>
	<dependency>
		<groupId>org.powermock</groupId>
		<artifactId>powermock-module-junit4</artifactId>
		<version>2.0.0-beta.5</version>
		<scope>test</scope>
	</dependency>
	<dependency>
		<groupId>org.powermock</groupId>
		<artifactId>powermock-api-mockito2</artifactId>
		<version>2.0.0-beta.5</version>
		<scope>test</scope>
	</dependency>
	<dependency>
		<groupId>junit</groupId>
		<artifactId>junit</artifactId>
		<version>4.12</version>
		<scope>test</scope>
	</dependency>
</dependencies>
```

**Comment by TimvdLippe** [comment]
You should not mock `Method`, it is final.

**Comment by standup-jb** [comment]
So the final method can't be mock.
