### ISSUE TITLE
git --author does not work from CI

### ISSUE THREAD

**Issue by szczepiq** [mockito/mockito#143]
git --author does not work from CI for some reason and the automatic release does not work properly

**Comment by szpak** [comment]
I wanted to get onto this, but in the Git log I see:
```
commit f80dd4a95d78d15dfea814877d143e8e31cfd880
Author: Continuous Delivery Drone <continuous.delivery.drone@gmail.com>
Date:   Sat Aug 13 18:05:32 2016 +0000

    Increment version '2.0.101-beta' -> '2.0.102-beta' by Travis CI build 1128 [ci skip-release]
```

It was a long time ago, maybe it was fixed in the meantime? @szczepiq could you elaborate more about this issue?

**Comment by TimvdLippe** [comment]
I think this was probably fixed in the mean time. Therefore closing this issue.
