### ISSUE TITLE
Spy on java 8 default methods with interface hierarchy 

### ISSUE THREAD

**Issue by raphaelbrugier** [mockito/mockito#146]
Hi,

I've a use case where I have a base Interface defining a method, an abstract class implements this interface. A concrete class extends the abstract class and implements another interface inheriting the base interface with a default method. (Something like the usage of traits in Scala)

This works fine if the object is not spied, but when spied the delegation seems to not call the real object and returns null instead.

See test case below :

```java
public class SpyingOnDefaultMethods extends TestBase {

    public static interface InterfaceBase {
        String getFoo();
    }

    public static interface InterfaceWithDefault extends  InterfaceBase {
        default String getFoo() {
            return "foo";
        }
    }

    public static abstract class ClassBase implements InterfaceBase {}

    public static class ClassConcrete extends ClassBase implements InterfaceWithDefault {}

    @Test
    public void shouldAcceptSpyOnDefaultMethods() {
        ClassConcrete concreteClass = new ClassConcrete();
        assertEquals(concreteClass.getFoo(), "foo");

        ClassConcrete concreteClassSpied = spy(new ClassConcrete());
        assertEquals(concreteClassSpied.getFoo(), "foo");
    }
}
```

Two notes : 
- I had to compile Mockito with java 8 to add this test.
- When switching mockito codebase to Java 8, I had to explicitly add some parametrization types to have the compiler working fine

I'd like to submit a fix, but I'm discovering Mockito internals and I have yet to figure out where to start.

**Comment by Blackrush** [comment]
+1

**Comment by raphw** [comment]
Works now after removing explicit byte code version as explained in https://github.com/mockito/mockito/issues/186

**Comment by raphw** [comment]
Added a test that uses Byte Buddy to generated a default method interface only on Java 8.
