### ISSUE TITLE
Manifest has a missing package org.mockito.asm.signature

### ISSUE THREAD

**Issue by cvgaviao** [mockito/mockito#147]
the manifest of version 1.10.17 has an import for `org.mockito.asm.signature` package. that doesn't exists in the binary jar.
This makes this version unusable with OSGi.

**Comment by bric3** [comment]
@cvgaviao In recent mockito we have made the resolution optional. could that work for OSGI ?

See #104

**Comment by cvgaviao** [comment]
@bric3, I will take a look on it next monday and return to you.

**Comment by cvgaviao** [comment]
Confirmed that since 1.10.19 manifest is ok.

**Comment by bric3** [comment]
Cool thanks for the feedback :)
