### ISSUE TITLE
Travis CI consistently fails on javadoc generation for inline mocks + JDK 10

### ISSUE THREAD

**Issue by mockitoguy** [mockito/mockito#1476]
Travis CI consistently fails on javadoc generation for inline mocks + JDK 10, example:

https://travis-ci.org/mockito/mockito/jobs/415040205

**Comment by TimvdLippe** [comment]
This should be fixed since 4 hours ago: https://twitter.com/sormuras/status/1028504378062323712

**Comment by TimvdLippe** [comment]
This appears to be fixed.
