### ISSUE TITLE
Clean Dependency Separation

### ISSUE THREAD

**Issue by adligo** [mockito/mockito#148]
Hi,

   I am working on a new testing project tests4j.adligo.org,  which is a competing project to junit. Tests4j is fairly similar to junit 3 api, but ~TestCase classes are run concurrently, and lots of other bells and whistles.  During some work on tests4j_tests.adligo.org (the project which tests tests4j.adligo.org), I used some of mockito's mocking framework with great success.   
    However mockito depends on junit and hamcrest, which could potentially confuse some users of the tests4j api (i.e. which assertTrue(false); the junit one or the tests4j one?).   I am wondering if I can get org.mockito:mockito-core to split into a few jars in version 2+, so that I could remove the junit and hamcrest dependencies from the tests4j_4mockito dependency tree?
   I realize this is a huge change,  and so I just thought I would throw out the idea.
I would like something like this;

tests4j_4mockito - - - depends on - - -> mockito-mocking

mockito-core - - - depends on - - - >  mockito-mocking            
                                                           junit
                                                           hamcrest

tests4j 0.1 should be out in a month or so (on github.com), mostly for comments on the api.

TIA,
Scott

**Comment by bric3** [comment]
@adligo there have been progress on that front in 2.0, for example we have removed the mockito-all artifact.

I'll close this uuuissue, but feel free to give us feedback on the work in progress of mockito 2.0.x betas.

**Comment by adligo** [comment]
Hi Brice,

   Thank you for doing this, hopefully I will get a chance to look at it
this year.  Tests4j itself is keeping me quite busy.

Cheers,
Scott
