### ISSUE TITLE
Maven Central has latest Version only 2.21.0. Missing deployments of 2.21.1 - 2.21.4.

### ISSUE THREAD

**Issue by Tibor17** [mockito/mockito#1485]
Missing next versions 2.21.1 - 2.21.4 in Maven Central http://repo1.maven.org/maven2/org/mockito/mockito-core/

**Comment by Tibor17** [comment]
@epeee 
@raphw 
Can you check it what happened with deployments?

**Comment by szpak** [comment]
It's done intently. Please read the [README](https://github.com/mockito/mockito#how-to-release-new-version) file and related links.
