### ISSUE TITLE
My test cases fail when run together but pass individually, at android studio

### ISSUE THREAD

**Issue by MohamedTaher** [mockito/mockito#1491]
`
import io.swagger.client.models.PostShiftResponse
import org.junit.After
import org.junit.Before
import org.junit.Test
import org.mockito.Mockito
import org.mockito.Mockito.reset
import android.os.StrictMode

class MainPresenterTest {

    private lateinit var api: Api
    private lateinit var mainViewContract: MainActivity
    private lateinit var presenter: MainPresenter

    @Before
    fun setup() {

        api = Mockito.mock(Api::class.java)
        mainViewContract = Mockito.mock(MainActivity::class.java)
        presenter = MainPresenter(mainViewContract, api)

    }

    @After
    fun resetMocks() {
        reset(api, mainViewContract)
        StrictMode.setThreadPolicy(StrictMode.ThreadPolicy.Builder().build())
    }

    @Test
    fun changeShiftToOn1() {

        Shared.shiftState = ShiftStatus.OFF
        val postShiftResponse = PostShiftResponse(200, "132")

        Mockito.`when`(api.startShift()).thenReturn(postShiftResponse)

        Mockito.`when`(mainViewContract.popupErrorMessage()).then { }
        Mockito.`when`(mainViewContract.showShiftDialog()).then { }
        Mockito.`when`(mainViewContract.dismissDialog()).then { }
        Mockito.`when`(mainViewContract.showProgressDialog()).then { }

        presenter.changeShiftState()

        Mockito.verify(mainViewContract, Mockito.atLeastOnce()).showConnectingBar()
        Mockito.verify(mainViewContract, Mockito.atLeastOnce()).startServices()
        Mockito.verify(mainViewContract, Mockito.atLeastOnce()).setStartShiftLayout(false)

    }

    @Test
    fun changeShiftToOn2() {

        Shared.shiftState = ShiftStatus.OFF
        val postShiftResponse = PostShiftResponse(400, "132")

        Mockito.`when`(api.startShift()).thenReturn(postShiftResponse)

        Mockito.`when`(mainViewContract.popupErrorMessage(null)).then { }
        Mockito.`when`(mainViewContract.showShiftDialog()).then { }
        Mockito.`when`(mainViewContract.dismissDialog()).then { }
        Mockito.`when`(mainViewContract.showProgressDialog()).then { }

        presenter.changeShiftState()

        Mockito.verify(mainViewContract, Mockito.atLeastOnce()).popupErrorMessage(null)
        Mockito.verify(mainViewContract, Mockito.atLeastOnce()).showShiftDialog()

    }

    @Test
    fun changeShiftToOof1() {

        Shared.shiftState = ShiftStatus.ON
        val postShiftResponse = PostShiftResponse(200, "132")

        Mockito.`when`(api.endShift()).thenReturn(postShiftResponse)

        Mockito.`when`(mainViewContract.popupErrorMessage()).then { }
        Mockito.`when`(mainViewContract.showShiftDialog()).then { }
        Mockito.`when`(mainViewContract.dismissDialog()).then { }
        Mockito.`when`(mainViewContract.showProgressDialog()).then { }

        presenter.changeShiftState()

        Mockito.verify(mainViewContract, Mockito.atLeastOnce()).showDisconnectionErrorBar()
        Mockito.verify(mainViewContract, Mockito.atLeastOnce()).stopServices()
        Mockito.verify(mainViewContract, Mockito.atLeastOnce()).setStartShiftLayout(true)

    }

    @Test
    fun changeShiftToOof2() {

        Shared.shiftState = ShiftStatus.ON
        val postShiftResponse = PostShiftResponse(400, "132")

        Mockito.`when`(api.endShift()).thenReturn(postShiftResponse)

        Mockito.`when`(mainViewContract.popupErrorMessage()).then { }
        Mockito.`when`(mainViewContract.showShiftDialog()).then { }
        Mockito.`when`(mainViewContract.dismissDialog()).then { }
        Mockito.`when`(mainViewContract.showProgressDialog()).then { }

        presenter.changeShiftState()

        Mockito.verify(mainViewContract, Mockito.atLeastOnce()).popupErrorMessage()
        Mockito.verify(mainViewContract, Mockito.atLeastOnce()).showShiftDialog()

    }
}`

**Comment by Kiarasht** [comment]
This is likely because you are using the same instance across your tests. 
https://stackoverflow.com/questions/26561511/tests-pass-when-run-individually-but-not-when-the-whole-test-class-run

**Comment by TimvdLippe** [comment]
Closing per above comment.
