### ISSUE TITLE
Why mocked method call from lambda invocekes original implementation

### ISSUE THREAD

**Issue by Antoniossss** [mockito/mockito#1493]
Its more of a questin than (or maybe a) bug 

This orignally came from Stackoverflow https://stackoverflow.com/questions/52370786/mockito-spying-function-calls-inside-functional-interfaces?noredirect=1#comment91687051_52370786

But since I don't exacly know how Mockito internal works (thus i thought I know it is using proxies for spying) I am wondering why is that happening. 

Having simple example:
```
    class MyTest {

        private int counter=10;

        public Integer callTarget() {
            return this.counter+5;
        }

        public Integer indirectCall() {
            return this.callTarget();
        }

        Supplier<Integer> methodRefCall = this::callTarget;
        Supplier<Integer> lambdaCall = () -> this.callTarget();
    }

    @Test
    public void testspy() throws Exception {
        MyTest mybean = spy(new MyTest());
        doReturn(1000).when(mybean).callTarget();
        assertEquals(mybean.callTarget().intValue(), 1000);
        assertEquals(mybean.indirectCall().intValue(), 1000);
        assertEquals(mybean.lambdaCall.get().intValue(), 15);
        assertEquals(mybean.methodRefCall.get().intValue(), 15);
    }
```

All asserts passes. Since I thought it is using proxy that requires outside call to get invocation interception, I was surprised that second assertion passes (indirectCall) but even then I am more surprised that lamba expression call and method reference call acts differently then implementation of `indirectCall` that does the same thing that `lambdaCall` does. 

Why is that happening?

**Comment by T3rm1** [comment]
My wild guess: compiler optimizations. Maybe the code is inlined by the compiler.
What happens with another lambda that calls `indrectCall()`?

**Comment by naivekook** [comment]
I join the question, have similar problem with lambda in mocked class.

This test fails
`open class Foo {
    var foo: String? = null
    var fooLambdaHook: () -> String? = { foo }
}

class FooTest {

    @Test
    fun `test lambda hook`() {
        val mybean = spy(Foobar()).apply {
            foo = "foo"
        }
        Assertions.assertNotNull(mybean.fooLambdaHook())
    }
}`

**Comment by geaden** [comment]
Hi @naivekook! It looks like https://stackoverflow.com/a/33656445 explains it all

**Comment by Antoniossss** [comment]
Ok so long story short, lambda and method ref contains reference to `this` as real object, not spy wrapper.
