### ISSUE TITLE
Raw extraction not supported for : 'null'

### ISSUE THREAD

**Issue by T3rm1** [mockito/mockito#1495]
Mockito version 2.22.0

Sample code:

    public static class TestClass {
		private Page<String> foo;
		public Page<String> getFoo() {
			return foo;
		}
	}

	@Test
	public void doesNotWork() {
		TestClass m = mock(TestClass.class, RETURNS_DEEP_STUBS);
		when(m.getFoo().getContent().get(anyInt())).thenReturn("test");
	}

Page class is from Spring Boot (package org.springframework.data.domain). It has nothing to do with it though. I just used it because I think it shows that some basic classes need deep stubbing.

Exception occurs in second line of test method.
`org.mockito.exceptions.base.MockitoException: Raw extraction not supported for : 'null'`

**Comment by TimvdLippe** [comment]
Closing as this issue is quite old and lacks a reproduction project.

**Comment by T3rm1** [comment]
What? All you need to do is copy & paste the above code.
Also, what the above code tries to achieve is quite common. No one wants to mock every return type. Please reconsider to fix this bug.

**Comment by TimvdLippe** [comment]
The code in question does not compile with just your lines of code. Please create a reproduction project.
