### ISSUE TITLE
Newest Mockito Android fails on Android P

### ISSUE THREAD

**Issue by tmtrademarked** [mockito/mockito#1510]
The latest releases of Mockito Android appear to break compatibility with Android P. Specifically in instrumentation tests, I encounter an error when attempting to mock an Android framework class. Here's the mocking code I'm using:

```
@Override
    protected ConnectivityManager provideConnectivityManager_impl(Context context) {
        NetworkInfo info = mock(NetworkInfo.class);
        when(info.isConnectedOrConnecting()).thenReturn(true);
        ConnectivityManager manager = provide(ConnectivityManager.class);
        when(manager.getActiveNetworkInfo()).thenReturn(info);
        return manager;
    }
```

Here is the error I encounter:
```
org.mockito.exceptions.base.MockitoException:
Mockito cannot mock this class: class android.net.NetworkInfo.

Mockito can only mock non-private & non-final classes.
If you're not sure why you're getting this error, please report to the mailing list.



IMPORTANT INFORMATION FOR ANDROID USERS:

The regular Byte Buddy mock makers cannot generate code on an Android VM!
To resolve this, please use the 'mockito-android' dependency for your application:
http://search.maven.org/#search%7Cga%7C1%7Ca%3A%22mockito-android%22%20g%3A%22org.mockito%22

Java               : 0.9
JVM vendor name    : The Android Project
JVM vendor version : 2.1.0
JVM name           : Dalvik
JVM version        : 0.9
JVM info           : null
OS name            : Linux
OS version         : 4.4.124+


Underlying exception : java.lang.IllegalArgumentException: On Android P, a class injection can only be applied to BaseDexClassLoader: net.bytebuddy.dynamic.loading.MultipleParentClassLoader@ecc1346
at com.blueapron.service.mock.InstrumentAppModule.provideConnectivityManager_impl(InstrumentAppModule.java:63)
at com.blueapron.service.dagger.ApplicationModule.provideConnectivityManager(ApplicationModule.java:149)
at com.blueapron.service.dagger.ApplicationModule_ProvideConnectivityManagerFactory.proxyProvideConnectivityManager(ApplicationModule_ProvideConnectivityManagerFactory.java:44)
at com.blueapron.service.dagger.ApplicationModule_ProvideConnectivityManagerFactory.provideInstance(ApplicationModule_ProvideConnectivityManagerFactory.java:33)
at com.blueapron.service.dagger.ApplicationModule_ProvideConnectivityManagerFactory.get(ApplicationModule_ProvideConnectivityManagerFactory.java:28)
at com.blueapron.service.dagger.ApplicationModule_ProvideConnectivityManagerFactory.get(ApplicationModule_ProvideConnectivityManagerFactory.java:10)
```

The class doesn't appear to be final or private, making the error message confusing.

I have verified that the same exact test passes with the 2.19.0 libraries, and fails with anything higher, starting at 2.20.1 and continuing through the 2.23.0 libraries. So it doesn't appear to be a configuration issue with my instrumentation tests. (I initially thought this was caused by incorrectly including mockito-core instead of mockito-android, but since I can produce the failure by *only* changing the mockito version, this feels unlikely)

Any ideas what has gone wrong here?

I do solemnly swear that:
 - [ X ] The mockito message in the stacktrace have useful information, but it didn't help
 - [ X ] The problematic code (if that's possible) is copied here;
       Note that some configuration are impossible to mock via Mockito
 - [ X ] Provide versions (mockito / jdk / os / any other relevant information)
 - [ X ] Provide a [Short, Self Contained, Correct (Compilable), Example](http://sscce.org) of the issue
       (same as any question on stackoverflow.com)
 - [ X ] Read the [contributing guide](https://github.com/mockito/mockito/blob/master/.github/CONTRIBUTING.md)

**Comment by TimvdLippe** [comment]
This is probably broken by https://github.com/mockito/mockito/commit/28fa11092b55595727eb3c40059a5f632f3f29cc Could you revert the Bytebuddy version and see if that fixes it?

**Comment by tmtrademarked** [comment]
Sure thing, @TimvdLippe - I'm not 100% sure on the best way to go about that, though. Any pointers on how to most easily pull down and point to the correct artifacts? I've got it cloned, but am not sure which gradle projects represent the `core` and `android` artifacts.

(I'm assuming that `subprojects/android` is likely `mockito-android - but just trying to include the root project in my app gives a gradle error, making me suspect I'm doing this wrong)

**Comment by TimvdLippe** [comment]
You should be able to pin the version of ByteBuddy to a specific version in your `pom.xml` or Gradle file. No need to clone this repository :smile:

**Comment by PaulWoitaschek** [comment]
So this is fixed as of #1525 ?

**Comment by plastiv** [comment]
> So this is fixed as of #1525 ? 
Doesn't look so. `mockito-android 2.23.0` and `bytebuddy 1.9.3` fails with exception. same mockito and `bytebuddy 1.8.10` works for me

**Comment by PaulWoitaschek** [comment]
Use 2.23.4

**Comment by plastiv** [comment]
> Use 2.23.4

How should it fix the issue?

```
+--- org.mockito:mockito-android:2.23.4
|    +--- org.mockito:mockito-core:2.23.4
|    |    +--- net.bytebuddy:byte-buddy:1.9.3
|    |    +--- net.bytebuddy:byte-buddy-agent:1.9.3
|    |    \--- org.objenesis:objenesis:2.6
|    \--- net.bytebuddy:byte-buddy-android:1.9.3
|         +--- net.bytebuddy:byte-buddy:1.9.3
|         \--- com.jakewharton.android.repackaged:dalvik-dx:1
|              \--- com.jakewharton.android.repackaged:libcore-dex:2
```
Fails, but 
```
+--- org.mockito:mockito-android:2.23.4
|    +--- org.mockito:mockito-core:2.23.4
|    |    +--- net.bytebuddy:byte-buddy:1.9.3 -> 1.8.10
|    |    +--- net.bytebuddy:byte-buddy-agent:1.9.3 -> 1.8.10
|    |    \--- org.objenesis:objenesis:2.6
|    \--- net.bytebuddy:byte-buddy-android:1.9.3 -> 1.8.10
|         +--- net.bytebuddy:byte-buddy:1.8.10
|         \--- com.jakewharton.android.repackaged:dalvik-dx:1
|              \--- com.jakewharton.android.repackaged:libcore-dex:2
```
works. What am I missing?

**Comment by russell-shizhen** [comment]
Check the answer from: https://stackoverflow.com/a/51891596/8034839 

Try to use the version 2.18.3

```
testImplementation 'org.mockito:mockito-core:2.18.3'
androidTestImplementation 'org.mockito:mockito-android:2.18.3'
```

**Comment by tmtrademarked** [comment]
Hmm - it doesn't seem to be working for me, even with a forced ByteBuddy. Here's a code snippet from my build.gradle to force this:

```
configurations.all {
    resolutionStrategy {
        force 'net.bytebuddy:byte-buddy:1.8.10'
        force 'net.bytebuddy:byte-buddy-agent:1.8.10'
    }
}
```

And you can see in my dependencies:
```
+--- org.mockito:mockito-android:2.23.4
|    +--- org.mockito:mockito-core:2.23.4
|    |    +--- net.bytebuddy:byte-buddy:1.9.3 -> 1.8.10
|    |    +--- net.bytebuddy:byte-buddy-agent:1.9.3 -> 1.8.10
|    |    \--- org.objenesis:objenesis:2.6
|    \--- net.bytebuddy:byte-buddy-android:1.9.3
|         +--- net.bytebuddy:byte-buddy:1.9.3 -> 1.8.10
|         \--- com.jakewharton.android.repackaged:dalvik-dx:1
|              \--- com.jakewharton.android.repackaged:libcore-dex:2
```

Any further ideas what might be causing this?

**Comment by jhansche** [comment]
@tmtrademarked Try also downgrading `net.bytebuddy:byte-buddy-android:1.8.10`

**Comment by tmtrademarked** [comment]
Well, I feel silly now. That should have been obvious. Thanks! That does in fact fix the problem.

**Comment by tmtrademarked** [comment]
It looks like this may be fixed in the newest byte-buddy versions. Unpinning my byte buddy and updating to Mockito 2.24.0 (which brings in byte-buddy 1.9.7) seems to fix the problem on my builds!

**Comment by TimvdLippe** [comment]
Glad to hear! Closing per above comment.
