### ISSUE TITLE
Modifying Mockito for Android build Tools 28.0.0 against deprecation

### ISSUE THREAD

**Issue by tobimichigan** [mockito/mockito#1534]
Nice work!
Don't you think "compile", should be changed to "implementation" or "api" since its depreciating in 2018?

Additionally, you seem to miss out on a clear annotation for android build gradle for dependency purposes? ie "implementation android.bla,bla.mokito:v10:y.x".

```gradle
dependencies {
    compile libraries.bytebuddy, libraries.bytebuddyagent

    compileOnly libraries.junit4, libraries.hamcrest
    compile libraries.objenesis

    testCompile libraries.asm

    testCompile libraries.assertj

    //putting 'provided' dependencies on test compile and runtime classpath
    testCompileOnly configurations.compileOnly
    testRuntime configurations.compileOnly

    testUtil sourceSets.test.output
}
```

**Comment by TimvdLippe** [comment]
I am not sure what you mean, as the snippet you posted is already in the `build.gradle`. What is your proposed alternative?

**Comment by tobimichigan** [comment]
Summary: Ur using "compile" which is heading for deprecation come December 2018.
There is no Android build dependency annotation for android Gradle builds.

**Comment by TimvdLippe** [comment]
After reading https://docs.gradle.org/current/userguide/java_library_plugin.html it becomes more clear. We should thus move everything into `implementation`. I wonder if that is a breaking change...

**Comment by tobimichigan** [comment]
THUMBS up @TimvdLippe , excellent observation. I happy I have someone who shares my view.

**Comment by bric3** [comment]
I'm ok that parts of the gradle build are reworked. But after speaking with gradle guys `compile` scope is not going to be removed anytime soon, so there's no urgency. That being `implementation` and `api` scopes could adds some value to our consumer.

**Comment by tobimichigan** [comment]
@bric3 u said "...so there's no urgency." You sound pretty laid back...hahaha..it could be dangerous for this line of work. Its better to be preemptive, forward thinking than being overly relaxed.

**Comment by TimvdLippe** [comment]
We updated our usage of Gradle scopes in #2411 and are now using `api` as expected (Gradle 7 removed `implementation`).
