### ISSUE TITLE
stop depending on hamcrest internally

### ISSUE THREAD

**Issue by szczepiq** [mockito/mockito#154]
In order to avoid compatibility/upgrade problems we will stop depending on hamcrest internally. Hamcrest will be an optional dependency of Mockito.

**Comment by tobier** [comment]
What's the progress on this? I'd like to use Mockito with my unit tests and I'm running JUnit 4.11 that is bundled with Eclipse 4.4 that I'm using.

**Comment by bric3** [comment]
Is Hamcrest dependency a blocker for using Mockito with Eclipse 4.4 ?

-- Brice

**Comment by tobier** [comment]
@bric3 It seems that way. Eclipse 4.4 comes with JUnit 4.11 and Hamcrest 1.3, which apparently doesn't work with Mockito? Therefore when I try to run my JUnit plug-in tests for an Eclipse 4.4 RCP application it doesn't work.

**Comment by martin-g** [comment]
I use Mockito 1.9.5 and 1.10.16 with JUnit 4.11 and 4.12 combined with Hamcrest 1.3 in several applications and didn't have any issues.

**Comment by bric3** [comment]
Fells more of an Eclipse issue, if an IDE cannot work with the project
classpath...

The team / the code is clearly not near any Mockito 2.0 _final_ release.
Anyway, this task is not even started, and it will target Mockito 2.0 as
API will change.

**Comment by tobier** [comment]
@bric3 @martin-g My bad, I made a plugin for Mockito and forgot to add the dependencies to Hamcrest and Objenesis. Seems to work fine now as far as I can tell..

**Comment by philipwhiuk** [comment]
Would be nice to at least upgrade to hamcrest 1.3 (latest version I think).

**Comment by bric3** [comment]
@philipwhiuk Maybe in version 2.0. Maybe we could eventually drop the dependency (at this time nothing yet decided)

**Comment by szczepiq** [comment]
Working on this. We will use hamcrest 1.3, too.

**Comment by szczepiq** [comment]
This is completed on master.
