### ISSUE TITLE
when mock is called multiple times, and verify fails, the error message reports only the first invocation

### ISSUE THREAD

**Issue by mrenrich84** [mockito/mockito#1542]
AS A diligent dev,
I WANT TO verify that a mock will eventually get called with the specified parameters,
SO THAT I can properly test my builder class

SCENARIO
I have a builder class exposing a .with(String key, String value) method.
I created a test for testing that at a certain point the method gets called with 'foo', 'valueFoo'
I'd like to follow a test pattern where 1 test case has only 1 assertion

```
builderMock.with('bar','valueBar');
builderMock.with('foo','notValueFoo');
verify(builderMock).with('foo','valueFoo');
```

WHAT'S WRONG
Verify reports only the first invocation in the test failed logs.

```
Arguments are different! Wanted: 
builderMock.with('foo','valueFoo');
at ...
Actual invocation has different arguments:
builderMock.with('bar','valueBar');
at ...
``` 

IMO should be a list of invocation for that methods, something like:

```
// Actual invocations have different arguments:
// builderMock.with('bar','valueBar');
// at ...
// builderMock.with('foo','notValueFoo');
// at ...
```

NOTE
For anybody else having this problem, I'm rethrowing the exception raised with something like this:
```
    public static ArgumentsAreDifferent createExceptionWithEnhancedVerifyLogsFor(
            Object mockedObject,
            String invokedMethod,
            ArgumentsAreDifferent ex
    ) {
        String newline = System.getProperty("line.separator");
        String wanted = ex.getExpected();
        String actualTitle = MessageFormat.format(
                "Interactions of {0}.{1}():",
                mockedObject.getClass().getCanonicalName(), invokedMethod
        );
        String actual = mockingDetails(mockedObject).getInvocations().stream()
                .filter(invocation -> invocation.getMethod().getName().equals(invokedMethod))
                .map(Object::toString)
                .collect(Collectors.joining( newline ));
        String message = String.join(newline,
                ex.getClass().getCanonicalName(),
                "Wanted: " + wanted,
                actualTitle, actual
        );
        ArgumentsAreDifferent enhancedEx = new ArgumentsAreDifferent(message, wanted, actual);
        enhancedEx.setStackTrace(ex.getStackTrace());
        return enhancedEx;
    }
```

**Comment by mockitoguy** [comment]
Nice report, thank you! Do you want to take a stub at fixing it? I suspect that we need to tweak the reporting, so that we print other interactions, too. We do something like that for regular verification failures (as opposed to verification failures due to mismatched arguments)

**Comment by mrhampson** [comment]
I can try and take a look at this.

**Comment by mrhampson** [comment]
Just started working on this today. Doesn't seem like too bad of a change. I should have something to show later today or tomorrow.
