### ISSUE TITLE
Gradle Android cannot find version 2.23.9

### ISSUE THREAD

**Issue by marcosvbras** [mockito/mockito#1557]

**Comment by hannesa2** [comment]
I see here http://jcenter.bintray.com/org/mockito/mockito-core/ the last version is `2.23.4`

![image](https://user-images.githubusercontent.com/3314607/49525865-ed0f4900-f8ae-11e8-988b-80753407a8eb.png)

**Comment by marcosvbras** [comment]
> I see here http://jcenter.bintray.com/org/mockito/mockito-core/ the last version is `2.23.4`
> 
> ![image](https://user-images.githubusercontent.com/3314607/49525865-ed0f4900-f8ae-11e8-988b-80753407a8eb.png)

So, is the README.md file version wrong?

**Comment by TimvdLippe** [comment]
2.23.9 as available as development version: https://bintray.com/mockito/maven/mockito-development You can read on our reasoning in #911.
