### ISSUE TITLE
Api Suggestions

### ISSUE THREAD

**Issue by adligo** [mockito/mockito#156]
Hi, 

   Here are a few api suggestions, I didn't see them in the 2.0 release however I haven't really taken much time to check it out (5 min or so reading release notes).

1) I have created a few classes that can be reused for "MethodRecording" which is a Answer implementation.  If the Mockito developers like this code, they should feel free to take it and add it to Mockito.
https://github.com/adligo/my-test-repository/blob/master/src/org/adligo/tests4j_4mockito/MethodRecorder.java

2) For methods that return void on mock objects I would like to be able to write;
    MethodRecorder&lt;Void&gt; record = new MethodRecorder&lt;Void&gt;();
    PrintStream ps = mock(PrintStream.class);
    when(ps.println(any())).then(record);
In place writing;
    MethodRecorder&lt;Void&gt; record = new MethodRecorder&lt;Void&gt;();
    PrintStream ps = mock(PrintStream.class);
    doAnswer(record).when(ps).println(any());

I think this would make tests that use Mockito much clearer and easier to read.

Cheers,
Scott

**Comment by adligo** [comment]
After thinking about this a little more, perhaps the name MockMethod is better than MethodRecorder
since the class returns values in addition to recording calls;
https://github.com/adligo/tests4j_4mockito.adligo.org/blob/master/src/org/adligo/tests4j_4mockito/MockMethod.java

**Comment by bric3** [comment]
Release 2.x is an ongoing progress, expect API changes for a few months with mockito 2 PR are welcome though.

About your idea I think it should be based on the `InvocationListener` API : [invocationListeners](http://site.mockito.org/mockito/docs/current/org/mockito/MockSettings.html#invocationListeners(org.mockito.listeners.InvocationListener...)) and actually mockito is already doing it unless you tell him not (via [stubOnly](http://site.mockito.org/mockito/docs/current/org/mockito/MockSettings.html#stubOnly()))

**Comment by adligo** [comment]
I checked out InvocationListeners a little bit and it does look like there is some overlap.   However I think that MockMethod would still be quite useful as a separate API to include in Mockito, since it give you access to the actual arguments that were passed to a specific method, InvocationListeners seems to omit this at the most detail level since DescribedInvocation doesn't seem to have the actual argument/parameter instances. 
    I will leave it to the Mockito developers to actually move the code from tests4j_4mockito to Mockito if they want it, as I am busy with other work.

**Comment by bric3** [comment]
I'm not sure this kind of API should be integrated in mockito, it feels like a specific use case, not something testers do all the time. Imho I believe this this fine having some custom answers in other projects suiting the needs there.

Also I think method recording (replay) should fit in another project.

Opinion may change though, as the team grow accustomed to the idea.
