### ISSUE TITLE
AndroidX : Failed resolution of mockito/internal/invocation/realmethod/RealMethod

### ISSUE THREAD

**Issue by hannesa2** [mockito/mockito#1561]
I have Android emulator tests with these basic dependencies:

```
androidTestImplementation 'androidx.test:runner:1.1.0' 
androidTestImplementation 'androidx.test:rules:1.1.0' 
androidTestImplementation 'org.mockito:mockito-core:2.23.4'
```

and I run into 

> java.lang.NoClassDefFoundError: Failed resolution of: Lorg/mockito/internal/invocation/realmethod/RealMethod;
> at com.android.dx.mockito.DexmakerMockMaker.createMock(DexmakerMockMaker.java:43)
> at org.mockito.internal.util.MockUtil.createMock(MockUtil.java:35)
> at org.mockito.internal.MockitoCore.mock(MockitoCore.java:69)
> at org.mockito.Mockito.mock(Mockito.java:1896)
> at org.mockito.Mockito.mock(Mockito.java:1805)

any idea what's wrong here ?

**Comment by ftfeiteng** [comment]
Hi I got the same bug here. Would you please let me know how did you solve that?
