### ISSUE TITLE
java.lang.IllegalAccessError: class javax.xml.parsers.FactoryFinder

### ISSUE THREAD

**Issue by bharukaRupesh** [mockito/mockito#1562]
Hi All,

I am trying to run my Junit test but getting the below error. Any help would be really appreciated.

```I am using PowerMockRunner in my test cases.```

```java.lang.IllegalAccessError: class javax.xml.parsers.FactoryFinder``` (in unnamed module @0x6dd79214) cannot access class jdk.xml.internal.SecuritySupport (in module java.xml) because module java.xml does not export jdk.xml.internal to unnamed module @0x6dd79214
	at javax.xml.parsers.FactoryFinder.<clinit>(FactoryFinder.java:69)
	at javax.xml.parsers.DocumentBuilderFactory.newInstance(DocumentBuilderFactory.java:140)

**Comment by TimvdLippe** [comment]
I don't see any mention of Mockito in your stacktrace, so it is probably not an issue with Mockito. If you can post a reproduction with only Mockito, we can reopen this issue.

**Comment by hiteshbargujar** [comment]
@bharukaRupesh did you ever find the solution for this, I am getting the same error with Powermock. I update the libs to 2.0.0 of powermock but still getting the error.

**Comment by bharukaRupesh** [comment]
@hiteshbargujar I can't exactly recollect the solution as there were lot of such errors which I have resolved in one go.

could you please try adding ```@PowerMockIgnore({"com.sun.org.apache.xerces.*", "javax.xml.*", "org.xml.*", "javax.management.*"})``` at class level?

Probably this shall resolve your issue.

**Comment by akshay-hazari** [comment]
If you are using an older verision like Java 1.8, try using that. It shows up when there's a Java version mismatch as well.

**Comment by jorioux** [comment]
Using JDK 8 instead of 11 fixed the issue for me.

**Comment by shoomi** [comment]
Adding this at class level helped for me.
**@PowerMockIgnore({"javax.management.*", "com.sun.org.apache.xerces.*", "javax.xml.*", "org.xml.*", "org.w3c.*"})**

**Comment by skb81230** [comment]
Yes adding below worked for me in jdk11
@PowerMockIgnore({"javax.management.*", "com.sun.org.apache.xerces.*", "javax.xml.*", "org.xml.*", "org.w3c.*"})

**Comment by vpatil1311** [comment]
You can also try a VM arg something like below for JDK 9+ . It works in JDK 17 also. `--add-exports= java.xml/jdk.xml.internal=ALL-UNNAMED`

**Comment by gremi64** [comment]
I only needed this `@PowerMockIgnore({"com.sun.org.apache.xerces.*", "javax.xml.*", "org.xml.*"})`, thank you @bharukaRupesh       <3

**Comment by Tclz** [comment]
> @hiteshbargujar I can't exactly recollect the solution as there were lot of such errors which I have resolved in one go.
> 
> could you please try adding `@PowerMockIgnore({"com.sun.org.apache.xerces.*", "javax.xml.*", "org.xml.*", "javax.management.*"})` at class level?
> 
> Probably this shall resolve your issue.

thanks!

**Comment by AnasBaseer** [comment]
Hi all, I was trying to build my J-unit test but facing this error. Any help would be sincerely appreciated.
java.lang.IllegalAccessError: class javax.xml.parsers.FactoryFinder (in unnamed module @0x3c50ad4b) cannot access class jdk.xml.internal.SecuritySupport (in module java.xml) because module java.xml does not export jdk.xml.internal to unnamed module @0x3c50ad4b
**

**Comment by AlpsDevABE** [comment]
For the next person who falls into this issue. Github is mangling some of the posted solutions here. The correct ones have an ampersand after the class directive. Tclz's quote is correctly showing you the code, which is different from some of the earlier comments.

**Comment by oussama-denden** [comment]
I had the same issue after upgrading from java 8 to 11 the solution for me was to add the @PowerMockIgnore annotation but with asterisk at the end of each package name so the solution is:

@PowerMockIgnore({"javax.management.*", "com.sun.org.apache.xerces.*", "javax.xml.*", "org.xml.*", "org.w3c.*"})

But does any one have an explanation of what happening behinde the scene 
any explanation would be appreciated thanks

**Comment by DhrubajyotiSadhu** [comment]
> I had the same issue after upgrading from java 8 to 11 the solution for me was to add the @PowerMockIgnore annotation but with asterisk(*) at the end of each package name so the solution is:
> 
> `@PowerMockIgnore({"javax.management.*", "com.sun.org.apache.xerces.*", "javax.xml.*", "org.xml.*", "org.w3c.*"}) `
> 
> But does any one have an explanation of what happening behinde the scene any explanation would be appreciated thanks

Thanks solved my problem when upgrading to Java 11. Thanks  @oussama-denden
