### ISSUE TITLE
No such method error - Mockito

### ISSUE THREAD

**Issue by bharukaRupesh** [mockito/mockito#1564]
Hi All,

can anyone help me on the below error of **NoSuchMethodError: Mockito.framework( )?**

```
java.lang.NoSuchMethodError: org.mockito.Mockito.framework()Lorg/mockito/MockitoFramework;
       at org.powermock.api.mockito.mockmaker.MockMakerLoader.doLoad(MockMakerLoader.java:45)
       at org.powermock.api.mockito.mockmaker.MockMakerLoader.load(MockMakerLoader.java:36)
       at org.powermock.api.mockito.mockmaker.PowerMockMaker.<init>(PowerMockMaker.java:36)
       at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
       at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
       at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
       at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:488)
       at java.base/java.lang.Class.newInstance(Class.java:560)

 ```

**Comment by TimvdLippe** [comment]
What versions of PowerMock and Mockito are you using?

**Comment by bharukaRupesh** [comment]
I have tried using both ```2.0.0-beta.5``` and ```1.7.4 ```  but it didn't work for me.

**Comment by TimvdLippe** [comment]
2.0.0-beta is very old. The latest version is 2.23.4.

**Comment by bharukaRupesh** [comment]
Thanks @TimvdLippe ```2.23.4``` version of ```mockito-core``` has worked for me.

**Comment by Lakshmi0211** [comment]
@bharukaRupesh 

Hi, I'm getting same Error message. Please can review the compatibility.


 <dependency>
            <groupId>org.mockito</groupId>
            <artifactId>mockito-core</artifactId>
            <version>4.9.0</version>
            <scope>test</scope>
        </dependency>
        
	<dependency>
	    <groupId>org.mockito</groupId>
	    <artifactId>mockito-inline</artifactId>
	    <version>4.9.0</version>
	    <scope>test</scope>
	</dependency>
	
<dependency>
	    <groupId>org.mockito</groupId>
	    <artifactId>mockito-junit-jupiter</artifactId>
	    <version>4.9.0</version>	
	    <scope>test</scope>
	</dependency>
dependency>
            <groupId>org.powermock</groupId>
            <artifactId>powermock-module-junit4</artifactId>
            <version>2.0.9</version>
            <exclusions>
                <exclusion>
                    <groupId>junit</groupId>
                    <artifactId>junit</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>org.powermock</groupId>
                    <artifactId>powermock-core</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>org.powermock</groupId>
                    <artifactId>powermock-reflect</artifactId>
                </exclusion>
            </exclusions>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.powermock</groupId>
            <artifactId>powermock-api-mockito2</artifactId>
            <version>2.0.9</version>
            <scope>test</scope>
        </dependency>
