### ISSUE TITLE
Eclipse project setup doesn't work out-of-the-box

### ISSUE THREAD

**Issue by HoldYourWaffle** [mockito/mockito#1568]
When importing this project into eclipse there are a few issues:
- The `extTest` subproject apparently doesn't depend on the `mockito` main project
- `org.mockito.AnnotationsAreCopiedFromMockedTypeTest` indirectly references `java.nio.file.Path`, however the project's compiler level is set to 1.6. (`Path` was added in 1.7)
- The encoding for the eclipse project isn't set to UTF-8 by default
- The subprojects' project names aren't prepended with 'mockito'. This creates a lot of workspace clutter

Am I doing something wrong or is the project not set up properly?
I think I'm able to fix *some* of these things, and I'll be happy to provide a PR for this.

**Comment by HoldYourWaffle** [comment]
> I don't see this is in the source code. In what way is it depending on it?

Eclipse reports that [this](https://github.com/mockito/mockito/blob/7a3569e987c16bc74e21329e95f9954e40b38cfb/src/test/java/org/mockito/AnnotationsAreCopiedFromMockedTypeTest.java#L31) line indirectly references it from required `.class`-files.
I did some digging, `org.assertj.core.api.Assertions` from assertj-core [uses](https://github.com/joel-costigliola/assertj-core/blob/17de1de155e6d44da32aac825b19041c839bc790/src/main/java/org/assertj/core/api/Assertions.java#L27) it.

> Can we improve the names with some Eclipse specific files maybe?

Certainly! I'll create a PR.

> Also, could you post a screenshot of what your workspace looks like

![Cluttered workspace](https://i.imgur.com/91JOjTc.png)

What about the subproject not depending correctly? Seems to me that that's an issue that should come forward during build time too.

**Comment by HoldYourWaffle** [comment]
Did some more digging, [this](https://github.com/mockito/mockito/blob/aa3775ac1178b8e97435484360516a5d69d5e333/subprojects/extTest/extTest.gradle#L19) line might be causing the weird dependency. I of course have never published the core to a local maven repository, which causes this dependency to fail. Is there a reason why we can't just depend on the subproject?

**Comment by TimvdLippe** [comment]
> I did some digging, org.assertj.core.api.Assertions from assertj-core uses it.

We use these APIs in a lot of tests, so I think Eclipse is in the wrong here.

> I of course have never published the core to a local maven repository, which causes this dependency to fail.

When you compile `extTest`, it should publish publish Mockito core to your local maven repository per https://github.com/mockito/mockito/blob/aa3775ac1178b8e97435484360516a5d69d5e333/subprojects/extTest/extTest.gradle#L8-L12

However, we probably should just fix this and use the same method as in our other subprojects: https://github.com/mockito/mockito/blob/aa3775ac1178b8e97435484360516a5d69d5e333/subprojects/junit-jupiter/junit-jupiter.gradle#L9

**Comment by HoldYourWaffle** [comment]
> We use these APIs in a lot of tests, so I think Eclipse is in the wrong here.

How can eclipse be wrong? It's a fact that `java.nio.file.Path` wasn't there yet in 1.6.
Upon further investigation I found that eclipse doesn't even try to build the whole project because of this missing dependency. This makes it look like it's only that line, but it's actually the whole project that can't be build because of it.
I think that because most people don't actually use a 1.6 JDK while developing/testing this one slipped through. `assertj-core` does mention in it's readme that it requires at least 1.7.
I see 2 simple solutions:
- Put the tests in their own subproject with compiler level 1.7 (or 1.8).
- Raise the core compiler level to 1.7 (which is probably a no-go).

> However, we probably should just fix this and use the same method as in our other subprojects: 

I'll include it in my PR.

**Comment by TimvdLippe** [comment]
We locally build with JDK 1.8 and then enforce 1.6 compatibility with https://github.com/mockito/mockito/blob/0c4e494a16141a65f22605a57382a222040f340b/gradle/root/java-compatibility-check.gradle

**Comment by HoldYourWaffle** [comment]
I tried building the project while using obviously non-1.6 compatible code to test if that test actually runs, but I discovered I can't actually build the project. Something with checkstyle not being able to process the files.
Maybe animal sniffer doesn't check included dependencies correctly?

**Comment by TimvdLippe** [comment]
This was addressed in #1573.
