### ISSUE TITLE
Issue with mocking type in "java.util.*", Java 12

### ISSUE THREAD

**Issue by sormuras** [mockito/mockito#1615]
After upgrading Mockito from `2.23.4` to `2.24.0` we can't run JUnit 5's tests anymore. The error message reads:
```
    org.mockito.exceptions.base.MockitoException: 
    Mockito cannot mock this class: interface java.util.concurrent.locks.Lock.
    Mockito can only mock non-private & non-final classes.
    If you're not sure why you're getting this error, please report to the mailing list.
```
Find the complete stacktrace here: https://travis-ci.org/junit-team/junit5/jobs/488684907

Note, that using Mockito `2.24.0` using Java 11 (and 13 locally) did work out! See this build matrix: https://travis-ci.org/junit-team/junit5/builds/488684905

Workaround: revert to Mockito `2.23.4` for the time being via https://github.com/junit-team/junit5/commit/754f1eb0f106ab043d79de546d49769690a731b6

**Comment by TimvdLippe** [comment]
Suspiciously, the type is again in the `java.util` package. That leads me to believe any type definitive in there can't be mocked.

**Comment by sormuras** [comment]
> That leads me to believe any type definitive in there can't be mocked.

Using `2.24.0`. It works with the older version.

**Comment by raphw** [comment]
The package should not be an issue, but I'll check.

**Comment by raphw** [comment]
There is a dot missing after the package name....

**Comment by TimvdLippe** [comment]
Haha well spotted! Might be a simple String concatenation typo.

**Comment by TimvdLippe** [comment]
This is probably the mistake: https://github.com/mockito/mockito/blob/00cc06b387c3af8aaaed3a14fcb38df7d69db6c1/src/main/java/org/mockito/internal/creation/bytebuddy/SubclassBytecodeGenerator.java#L101

Should be:

```java
 typeName = InjectionBase.class.getPackage().getName() +"." + features.mockedType.getSimpleName();
```

**Comment by raphw** [comment]
Yes, very much.

Can it be that we don't have a test case for mocking a 'java.' type?

Are yoilu on your machine? I'll fix it next week otherwise.

**Comment by TimvdLippe** [comment]
Sadly not. I can work on it tomorrow as well. Luckily we have a test suite now 🎉

**Comment by TimvdLippe** [comment]
Or if @sormuras is available to make that PR, that would be amazing as well 😄 Our tests are specified in https://github.com/mockito/mockito/blob/f11705be91ee3545bc006908b34425f1fc359898/subprojects/module-test/src/test/java/org/mockito/moduletest/ModuleHandlingTest.java

**Comment by sormuras** [comment]
Great, Tim!

Any plans to sync current release to Maven Central, soon? 2.24.0 is the latest one that was uploaded: http://central.maven.org/maven2/org/mockito/mockito-core/maven-metadata.xml

**Comment by TimvdLippe** [comment]
I wanted to do so, but I first wanted to get some other issues resolved with @raphw Hopefully we can get to that next week. (but seems like we hit a JDK bug 🎉 )

**Comment by TimvdLippe** [comment]
Mockito 2.24.5 should be available on Maven central later today.

**Comment by sormuras** [comment]
Looks good on 12: https://travis-ci.org/junit-team/junit5/jobs/495011557
