### ISSUE TITLE
Consider renaming TooLittleActualInvocations

### ISSUE THREAD

**Issue by hdpe** [mockito/mockito#1623]
I agree with the commenter [here](https://github.com/mockito/mockito/issues/1088#issuecomment-303374289) that the exception name `TooLittleActualInvocations` is not ideal.

The correct English would be `TooFewActualInvocations` (where "few" is the opposite of "many" - as used in `TooManyActualInvocations`).

I appreciate this isn't the most critical issue ever raised, but it would make this assertion failure more readable!

As the existing class is non-final, I imagine it could be changed without breaking existing client code via subclassing and deprecating the original. Please let me know if it would be helpful for me to pick this up (or instead if the change wouldn't be desirable, or I'm otherwise missing something).

Thanks

**Comment by TimvdLippe** [comment]
I would welcome a PR for this :smile:
