### ISSUE TITLE
Documentação Mockito

### ISSUE THREAD

**Issue by alexmaia-ufg** [mockito/mockito#1625]
Boa noite prezados,

Sou aluno da Universidade Federal de Goiás - Brasil, estou lhes enviando este, para solicitar algumas informações sobre o Mockito. Estou fazendo um trabalho para a universidade, e necessito saber sobre a arquitetura, requisitos, e demais partes técnicas do do Framework. 

Se possível enviar um documento de arquitetura, diagramas, modelo arquitetural, documentos de requisitos  e demais artefatos de documentação de software e código.

Desde já agradeço, abraços.

Att, Alex Maia
Sistemas de Informação - UFG

**Comment by TimvdLippe** [comment]
Google translate gave the following:

> Good night dear ones
>
> I am a student at the Federal University of Goiás - Brazil, I am sending you this, to request some information about Mockito. I am doing a job for the university, and I need to know about the architecture, requirements, and other technical parts of the Framework.
>
> If possible send an architecture document, diagrams, architectural template, requirements documents and other software documentation artifacts and code.
>
> Thanks in advance, hugs.
>
> Att, Alex Maia
> Information Systems - UFG

We do not have architecture designs as far as I know and I am not sure if we are going to provide one in the near future. Maybe our wiki has some useful information for your project? https://github.com/mockito/mockito/wiki

**Comment by alexmaia-ufg** [comment]
Grato pela resposta.

Tendo em vista a ausência de um projeto, teria a possibilidade de vocês me descrever a arquitetura, só falar um pouco sobre ela.  se é em camadas, pipeline, MCV ou qual tipo seria.  Uma descrição para que u possa ter uma visão mais de alto nível. 

Fico a disposição.

**Comment by TimvdLippe** [comment]
> Thanks for the reply.
> 
> In view of the absence of a project, it would be possible for you to describe me the architecture, just to say a little about it. whether it's layered, pipeline, MCV or what type it would be. A description so that u can get a higher level view.
>
> I'm available.

Mockito is a mocking library. It does not use a specific architectural pattern like MVC. https://delftswa.gitbooks.io/desosa-2017/content/mockito/chapter.html might be of your interest.

**Comment by alexmaia-ufg** [comment]
Muito obrigado, vai ser muito útil. Abraços

**Comment by TimvdLippe** [comment]
> Thank you very much, it will be very useful. Hugs

No problem!
