### ISSUE TITLE
Release build is failing

### ISSUE THREAD

**Issue by TimvdLippe** [mockito/mockito#1645]
After the latest Shipkit update, our Travis is failing: https://travis-ci.org/mockito/mockito/jobs/501397895#L1693 It fails with

```
[commit]  2 files changed, 11 insertions(+), 2 deletions(-)
[performRelease]   External process [commit] completed.
[performRelease] [tag] fatal: tag 'v2.24.8' already exists
```

@mstachniuk could you take a look?

**Comment by epeee** [comment]
@TimvdLippe it looks like we fixed this one in https://github.com/mockito/shipkit/pull/782.
I can do some local testing and provide a PR for this one soon (shipkit version update).

**Comment by TimvdLippe** [comment]
Thanks for that @epeee Looking forward to that PR.

**Comment by mockitoguy** [comment]
Thank you guys!
