### ISSUE TITLE
OOME contributed to by UnnecessaryStubbingsReporter in lenient mode

### ISSUE THREAD

**Issue by brianfromoregon** [mockito/mockito#1657]
Hi

Upgraded to 2.23.4 from an older version and saw failed tests due to unnecessary stubbings. Fixed those failures by using lenient mode [withSettings().lenient()] and then saw an OOME. Heap dump showed UnnecessaryStubbingsReporter was a main contributor. We fixed by increasing heap size. However seems like potential improvement for mockito, if my mock uses lenient mode then you needn't use heap space to track unnecessary stubbings because they will not be reported.

Pretty minor, but wanted to report the suggestion. Thanks.

**Comment by mockitoguy** [comment]
Thank you for reporting! What version did you migrate from? Do you use "normal" mockito or some flavor (such as "inline")?

**Comment by brianfromoregon** [comment]
We upgraded from 1.10.19. We probably use normal mockito as I'm not aware of any other flavors such as inline. We often use MockitoJUnitRunner in tests.

**Comment by TimvdLippe** [comment]
We fixed a major memory issue in #1683. Are you still seeing this problem?

**Comment by TimvdLippe** [comment]
Closing per above comment.
