### ISSUE TITLE
Improve IDE UX comparison failure for JUnit5

### ISSUE THREAD

**Issue by mockitoguy** [mockito/mockito#1663]
When JUnit4 is used and the test is invoked from IDE (IDEA or Eclipse), and we are getting "arguments are different" MockitoVerificationError, the IDE gets nice "click to see the difference" link in the test failure, providing neat comparison pop-up.

We want to provide this feature for JUnit5, too. We do not want to add a new dependency on mockito (e.g. OpenTest4J). Rather, we can use reflection just like we do it now for JUnit4 or how AssertJ integrates with JUnit5.

Spin-off from #1656

**Comment by mockitoguy** [comment]
Changing the exception type is an incompatible change in a strict sense. However, we need to be able to improve the framework by tweaking the exceptions if needed. We always strive to be compatible. There are no known legit use cases why our users would want to catch & handle specific Mockito exceptions. It's OK to change the type of ArgumentsAreDifferent exception.

**Comment by kriegfrj** [comment]
I'm happy to take this on, per your request. The hardest part was the question of whether/how to handle backward compatibility. Should have a PR submitted by Monday.

**Comment by mockitoguy** [comment]
> The hardest part was the question of whether/how to handle backward compatibility

We are OK with this incompatible change (see my other comment). Thanks for taking this on!!!
