### ISSUE TITLE
OngoingStubbing failing to call doReturn value for covariant types

### ISSUE THREAD

**Issue by kirillzh** [mockito/mockito#1675]
Code sample:
```kotlin
interface Foo {
  fun bar(): Single<Bar<Int>>
}

sealed class Bar<T> {
  data class A<T>(val a: T) : Bar<T>()
}

class Test {
  val foo = mock<Foo> {
    on { bar() } doReturn Single.just(Bar.A(1))
  }
}
```
Received error: 
```
error: none of the following functions can be called with the arguments supplied:
public infix fun <T> OngoingStubbing<???>.doReturn(t: ???): OngoingStubbing<???> defined in com.nhaarman.mockito_kotlin
public fun <T> OngoingStubbing<???>.doReturn(t: ???, vararg ts: ???): OngoingStubbing<???> defined in com.nhaarman.mockito_kotlin
public inline infix fun <reified T> OngoingStubbing<Single<Bar<Int>>>.doReturn(ts: List<Single<Bar<Int>>>): OngoingStubbing<Single<Bar<Int>>> defined in com.nhaarman.mockito_kotlin
    on { bar() } doReturn Single.just(Bar.A(1))
```

Calling `thenReturn()` from original Mockito library however compiles just fine:
```kotlin
on { bar() }.thenReturn(Single.just(Bar.A(1))
```
It's seems that the type is getting lost along the way so I tried to define my own infix function with covariant type like so but that gave type mismatch:
```kotlin
infix fun <E> OngoingStubbing<out E>.myReturn(t: E): OngoingStubbing<out E> = thenReturn(t)
```

I think the problem here is that `Single` doesn't have covariant type which doesn't allow us to establish relationship between the types. Initial code works as expected if the `Bar` value is being wrapped in something with covariant types, e.g. Kotlin's `List`:

```kotlin
interface Foo {
  fun bar(): List<Bar<Int>>
}

sealed class Bar<T> {
  data class A<T>(val a: T) : Bar<T>()
}

class Test {
  val foo = mock<Foo> {
    on { bar() } doReturn listOf(Bar.A(1))
  }
}
```

I'm not sure if that's `org.mockito:mockito-core` or `com.nhaarman:mockito-kotlin-kt` issue.

Mockito: `org.mockito:mockito-core:2.7.5`
Mockito Kotlin: `com.nhaarman:mockito-kotlin-kt1.1:1.5.0`
Kotlin: `1.2.71`
JDK: 1.8

**Comment by TimvdLippe** [comment]
I think this should be filed at https://github.com/nhaarman/mockito-kotlin instead.

**Comment by kirillzh** [comment]
Submitted this ticket in the wrong place, it's meant to go to https://github.com/nhaarman/mockito-kotlin, closing. Ticket number: https://github.com/nhaarman/mockito-kotlin/issues/335.
