### ISSUE TITLE
Make it easier to to mock java.lang.Optional as return value of a Method

### ISSUE THREAD

**Issue by bfarka** [mockito/mockito#1681]
When you do extensive testing/mocking on some APIs which return Optionals on you end up writing somehting like

`Mockito.when(foo.getBaa()).thenReturn(Optional.of(myBaaValue)); `

many times.

this happend to me when writing many test on my Spring Applications and I mockted the Repository types into my Services (https://docs.spring.io/spring-data/commons/docs/current/api/org/springframework/data/repository/CrudRepository.html).

I suggest to have a dedicated threnReturnOptional() method so you can write something like

`Mockito.when(foo.getBaa()).thenReturnOptional(myBaaValue); `

**Comment by TimvdLippe** [comment]
Is this a worthwhile addition? We are not going a lot in terms of readability nor in terms of conciseness. Both statements are fairly long and express the same thing.

**Comment by bric3** [comment]
You can leverage the mockito API this way :

```
when(foo.getBaa()).then(returnOptionalOf(myBaaValue));
```

Where `returnOptionalOf()` is a static factory method that implements `Answer`.

**Comment by bfarka** [comment]
@bric3: Thx for you input, but IMHO i don't see the big difference...

since when(foo.getBaa)).thenReturn(Optional.ofNullable(myBaaValue));

use a a static factory method too since ofNullable could be static imported too..


@TimvdLippe / @bric3: the big difference in my suggestion would be it simply would make the API a bit more fluent. The IDE would have a chance to suggest me the  

`thenReturnOptional`

method when typing Opt... and i would not need to use any other static factory for the optional. 


of course on the other hand you could count my idea as a pollution of the API, but if Optional would not be such a common type in modern java frameworks/applications i would not file this request...

**Comment by TimvdLippe** [comment]
This is a strawman, so forgive me for that, but the same would be true for things like `thenReturnSetOf`. We would introduce an api for the most common types. We did that in the Matchers API (for set, list and map), but we regard that as a mistake.

I do agree that the IDE argument is valid. So it is more an argument of IDE usefulness vs API "bloat".

**Comment by mockitoguy** [comment]
> the same would be true for things like thenReturnSetOf

Very true (and even more: thenReturnListOf, thenReturnMapOf, thenReturnCollectionOf, ...). It does not seem as a good evolution of the API. Also, we would need to add ```doReturnOptionalOf``` and ```willReturnOptionalOf``` methods for consistency.

@bfarka, I hope you understand and you will continue to happily use Mockito :)

**Comment by yemanaung** [comment]
support
