### ISSUE TITLE
CompletableFuture unit tests mocking

### ISSUE THREAD

**Issue by javvajiamani** [mockito/mockito#1691]
I technically wanted the Execute the unit test for this particular step ```List<CompletableFuture<Data>> futureList= future.join();``` Not sure how to mock the future variable. I have return the tests to validate the ```oracleRepo.extractSpecificNameAndEventTypes(firstName, lastName)``` and ```nameEventTypesMap->sendNameData(nameEventTypesMap.values(),method```

```extractSpecificNameAndEventTypes``` returns ```Map<String, NameEventTypes>```

```sendNameData``` returns ```List<CompletableFuture<Data>>```

```CompletableFuture<List<CompletableFuture<Data>>> future= CompletableFuture.supplyAsync(()->{
        if(firstName!= null) {
            return oracleRepo.extractSpecificNameAndEventTypes(firstName, lastName);
        } else {
            return oracleRepo.extractAllNameAndEventTypes();
        }
    },oracleExecutor).thenApplyAsync(nameEventTypesMap->sendNameData(nameEventTypesMap.values(),method),NameExecutor);
    if(async){
        return result;
    }else{
        List<CompletableFuture<Data>> futureList= future.join();
        if(futureList==null || futureList.isEmpty()){
            return result;
        }
       return futureList.stream().map(CompletableFuture::join).collect(Collectors.toList());
    }```

**Comment by TimvdLippe** [comment]
I think this issue is more appropriate for StackOverflow: https://stackoverflow.com/questions/tagged/mockito
