### ISSUE TITLE
multiple thenThrow doesn't override previous stub, instead throws first stub's exception

### ISSUE THREAD

**Issue by G8XSU** [mockito/mockito#1719]
If I create a mock and stub a method so it throws an exception and do that twice the first exception will be thrown upon invoking the second stub instruction.

Ideally i could work by writing multiple testcases but it is inconsistent behavior considering thenReturn will override the previous stub. 
(Mentioned n documentation: Warning : if instead of chaining .thenReturn() calls, multiple stubbing with the same matchers or arguments is used, then each stubbing will override the previous one.) https://static.javadoc.io/org.mockito/mockito-core/2.11.0/org/mockito/Mockito.html#stubbing_consecutive_calls

Request is to override previous stub for thenThrow as well to be consistent with thenReturn.
Example:
```
@Test
    void exceptionConversionTest()  {

        when(mockDao.get(any(), any())).thenThrow(new InvalidRequestException(""));
        assertThrows(ConvertedInvalidRequestException.class,
                () -> documentStorage.load(MockDocumentCreator.getDocumentId()));

        when(mockDao.get(any(), any())).thenThrow(new DependencyFailureException(""));
        assertThrows(
                ConvertedDependencyFailureException.class,
                () -> documentStorage.load(MockDocumentCreator.getDocumentId()));
    }
```

**Comment by TimvdLippe** [comment]
Duplicate of #1237

**Comment by G8XSU** [comment]
Should we edit the previous issue to include Re-stubbing with "exceptional to exceptional" along with "exceptional to non-exceptional" ?

**Comment by TimvdLippe** [comment]
The exception is already thrown before, so I don't think that is necessary. They have the same root cause, which is that the `mockDao.get(any(),any())` throws, not the invocation of `thenThrow`.
