### ISSUE TITLE
Update hamcrest-core to version 1.3

### ISSUE THREAD

**Issue by tatacalu** [mockito/mockito#172]
Hi there,

It would be nice if mockito-core would depend on hamcrest-core 1.3 instead of 1.1 so that both mockito and junit [latest versions] would depend on the same 3rd party library.

Thanks in advance!

**Comment by superole** [comment]
I agree.
It would be nice to depend on a version of hamcrest-core that is not eight years old...

**Comment by bric3** [comment]
Hi thanks for your interest. I think your comment are indeed just right, yet compatibility has always been the primary concern here.

Nevertheless mockito 2.0.x will probably ditch the hamcrest dependency. We still have to think that through. But it will happen, hence the reason why we didn't merge this PR.

**Comment by tatacalu** [comment]
Cool, thank you for the update! Cheers!
