### ISSUE TITLE
Keep ArgumentMatchers.isNull(Class)

### ISSUE THREAD

**Issue by HaloFour** [mockito/mockito#1729]
The Javadoc for `ArgumentMatchers#isNull(Class)` currently shows that the method is deprecated and slated to be removed in Mockito 3.0:

> ```java
>      * @deprecated With Java 8 this method will be removed in Mockito 3.0. This method is only used for generic
>      * friendliness to avoid casting, this is not anymore needed in Java 8.
> ```

While I agree that Java's improved generic inference has removed many cases in which you might need this overload I am still finding it useful for cases where I need to disambiguate overloads declared on the mocked object.

For instance, say I have the following class I wish to mock:

```java
public class JsonDeserializer {
    public <T> T deserialize(String json, Class<T> clazz) { ... }
    public <T> T deserialize(byte[] json, Class<T> clazz) { ... }
}
```

I must do the following to mock either `deserialize` overload:

```java
JsonDeserializer mock = mock(JsonDeserializer.class);

// warns on call to deprecated method
doThrow(NullPointerException.class).when(mock).deserialize(isNull(byte[].class), any(Class.class));

// error due to ambiguous method call
doThrow(NullPointerException.class).when(mock).deserialize(isNull(), any(Class.class));

// must cast in order to avoid ambiguity if isNull(Class) is removed
doThrow(NullPointerException.class).when(mock).deserialize((byte[]) isNull(), any(Class.class));
```

While casting does solve the issue, I prefer the syntax of using the deprecated method.  I'd appreciate if leaving that overload of `isNull` would be considered.

**Comment by TimvdLippe** [comment]
> While casting does solve the issue, I prefer the syntax of using the deprecated method.

This is an artifact from the Java language specification for the need of casting when using overloaded methods. From Mockito's perspective, both methods read the same and one is not particularly shorter than the other. Since removing is removes API surface and confusion without any clear downside, we will still schedule it for removal.
