### ISSUE TITLE
Ignoring invocations on a spy()?

### ISSUE THREAD

**Issue by fge** [mockito/mockito#173]
Note that I am aware that the code I currently have has a design fault precisely because of this but here goes... Mockito core version 1.10.19

The project in question is [this](https://github.com/fge/java7-fs-base); I am trying to ease the development of new `FileSystem` instances and a pain point is the attributes.

The problem is in fact described in this question on StackOverflow:

http://stackoverflow.com/q/28573595/1093528

Basically, I'd like to be able to write the test, provided that there exists a (statically imported) `Mockito.ignoreInvocation`:

```java
@Test
public void setOwnerTest()
    throws IOException
{
    final UserPrincipal owner = mock(UserPrincipal.class);

    ignoreInvocation(writer).setAttributeByName("owner", owner);

    verify(writer, only()).setOwner(same(owner));
}
```

Maybe this is already possible? I have looked at the javadoc and so far it doesn't seem to me like it is.

**Comment by bric3** [comment]
**As `writer` is the spy**, as explained in the SO question this is what you want:

```java
// with BDDMockito
willDoNothing().given(writer).setAttributeByName("owner", owner);

// with regular API
doNothing().when(writer).setAttributeByName("owner", owner);
```

**Comment by bric3** [comment]
Overlooked the question, the snippet isn't actually about stubbing.

Anyway, looking more at the SO question, the test code is doing a  _partial mocks_, and it this is not something possible with the curent design of mockito. It's probably not something that we will improve anytime soon.
