### ISSUE TITLE
Mocks of one Junits affects next junit in queue of buid

### ISSUE THREAD

**Issue by afridshaikh** [mockito/mockito#1737]
Hi,

let's say there are two different Junits(T1, T2) having their own mocks for Class A.

whenever I execute classes separately. they without any issue. But when I make a build T1 executes perfectly without any issue but T2 fails because of mock are being used from T1 and not T2.

if I change the sequence of Execution in the build by changing the name of T1 to T321, so now Tests execution order in maven build will be T2 then T321, It works fine. If I remove T321 or T1 altogether, Still T1 works fine.

Can anyone explain where exactly it's going wrong?

Thanks.

**Comment by TimvdLippe** [comment]
This issue lacks a reproduction case. There is probably left-over state from your tests that you need to clean up. I would advise you to ask the question on StackOverflow instead for debugging help.
