### ISSUE TITLE
Release 3.0.1?

### ISSUE THREAD

**Issue by anilkumarmyla** [mockito/mockito#1738]
It seems the git tag 3.0.1 is not released to maven central. Expected or tagging made incorrectly?

**Comment by TimvdLippe** [comment]
This is explained in https://github.com/mockito/mockito/blob/release/3.x/README.md#how-to-release-new-version

> Not every version is published to Maven Central.

**Comment by anilkumarmyla** [comment]
apologies

**Comment by iemejia** [comment]
Mmm this is closed but the jars are not there. Does it make sense to reopen it?

**Comment by TimvdLippe** [comment]
This is working as intended. We don't publish all jars to Maven Central. We publish to Maven Central roughly every month.
