### ISSUE TITLE
"Bad" Test Name Detection (Research proposal, feedback needed)

### ISSUE THREAD

**Issue by Jianwei-Wu-1** [mockito/mockito#1740]
Hello Developers for mockito/mockito:

I'm Jianwei Wu, and a PhD student from University of Delaware. I'm conducting an evaluation of my current research work, and the following contents are partial results of my research. In order to evaluate my work, I might need your feedbacks for the following contents.

Explanation of the contents: 
The following contents are some improvements of existing test names in your Github project (this project). The first line shows the original test names, and the second line shows our extracted components from the test name and the test body. If they are not matching, then we will consider it "bad" for the test name. "Better" test name means we take the extracted components from the test body to provide a "better" version of the test name. For your feedbacks, you can accept or reject our modification, and a partial accept or reject is also welcomed. Any other kinds of feedbacks or comments are also welcomed.

Contents: 
TestName: nestedWhenTest (SpyStubbingMisuseTest)
SC body action: thenReturn(oneMC)
SC body predicate: N/A(inner)
SC body scenario: out(outer1)
SC name action: null(Regex)
SC name predicate: nestedWhenTest(Regex)
SC name scenario: Test(Regex)
-> 
unmatched with name
unmatched with name
unmatched with name
-> 
"Better" test name -> ThenReturn(...)Out(...)

TestName: test (StubbingInTestUsed)
SC body action: simpleMethod (Alternative Action: simpleMethod=2 )
SC body predicate: assertEquals
SC body scenario: thenReturn (Alternative Scenario: mock=1 )
SC name action: null(Regex)
SC name predicate: null(Regex)
SC name scenario: null(Regex)
-> 
unmatched with name
unmatched with name
unmatched with name
-> 
"Better" test name -> SimpleMethod(...)Equals(...)ThenReturn

TestName: usage (VerboseLoggingOfInvocationsOnMockTest)
SC body action: willReturn | verboseLogging
SC body predicate: N/A
SC body scenario: foo
SC name action: null(Regex)
SC name predicate: null(Regex)
SC name scenario: null(Regex)
-> 
unmatched with name
unmatched with name
unmatched with name
-> 
"Better" test name -> WillReturn/VerboseLogging(...)Foo

TestName: any_matcher (MatchersTest)
SC body action: forObject[Only] (Alternative Action: forObject=5 )
SC body predicate: assertEquals[Only]
SC body scenario: thenReturn (Alternative Scenario:  )
SC name action: null(Regex)
SC name predicate: null(Regex)
SC name scenario: null(Regex)
-> 
unmatched with name
unmatched with name
unmatched with name
-> 
"Better" test name -> ForObject(...)Equals(...)ThenReturn
---End

Thank you so much for your help and any feedback would be appreciated!
Jianwei Wu

**Comment by TimvdLippe** [comment]
Our tests are largely written as integration tests "as if the user would use Mockito". Therefore, I don't think these findings are as relevant for the Mockito test suite as they are for other users. Good luck with your research nonetheless!
