### ISSUE TITLE
Clarify Javadoc of RETURNS_SMART_NULLS, default answer in Mockito 3.0.0?

### ISSUE THREAD

**Issue by arend-von-reinersdorff** [mockito/mockito#1743]
[Javadoc for Mockito.RETURNS_SMART_NULLS](https://static.javadoc.io/org.mockito/mockito-core/3.0.0/org/mockito/Mockito.html#RETURNS_SMART_NULLS) in version 3.0.0 still says:

> ReturnsSmartNulls will be probably the default return values strategy in Mockito 3.0.0

As Mockito 3.0.0 has been released this could now be clarified. I see #971 is still open, so it looks like the default answer has not been changed?

**Comment by TimvdLippe** [comment]
Yes that should be updated to 4.0.0 now, as we decided not to make any API changes in 3.0.0.
