### ISSUE TITLE
Typo in error message 

### ISSUE THREAD

**Issue by GBouerat** [mockito/mockito#1747]
https://github.com/mockito/mockito/blob/885e69420baa2a382f4394b85dc84cb6fe17fff6/src/test/java/org/mockito/internal/creation/bytebuddy/InlineByteBuddyMockMakerTest.java#L219

"VM does not not support modification of given type"
should be 
"VM does not support modification of given type"

**Comment by TimvdLippe** [comment]
Feel free to open a PR with a fix.
