### ISSUE TITLE
Gradle could not resolve org.mockito:mockito-core:2.+.

### ISSUE THREAD

**Issue by frextrite** [mockito/mockito#1754]
- [x] The mockito message in the stacktrace have useful information, but it didn't help
 - [ ] The problematic code (if that's possible) is copied here;
       Note that some configuration are impossible to mock via Mockito
 - [x] Provide versions (mockito / jdk / os / any other relevant information)
 - [ ] Provide a [Short, Self Contained, Correct (Compilable), Example](http://sscce.org) of the issue
       (same as any question on stackoverflow.com)
 - [ ] Read the [contributing guide](https://github.com/mockito/mockito/blob/release/3.x/.github/CONTRIBUTING.md)

```
14:29:32.099 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] > Could not resolve org.mockito:mockito-core:2.+.
14:29:32.099 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   Required by:
14:29:32.099 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]       project :
14:29:32.099 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]    > Failed to list versions for org.mockito:mockito-core.
14:29:32.099 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]       > Unable to load Maven meta-data from https://repo.maven.apache.org/maven2/org/mockito/mockito-core/maven-metadata.xml.
14:29:32.099 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]          > Could not HEAD 'https://repo.maven.apache.org/maven2/org/mockito/mockito-core/maven-metadata.xml'. Received status code 403 from server: Forbidden
```

Getting 403 Forbidden recently on OpenJDK 11 builds on Travis for some strange reason. OpenJDK 12 works fine.

Build Log error line: https://travis-ci.org/frextrite/coala-jetbrains/jobs/569380032#L4180 and another https://travis-ci.org/frextrite/coala-jetbrains/jobs/569293740#L4186

**Comment by TimvdLippe** [comment]
Could you check if the solution in #1750 would resolve this? I think this is a Travis issue and not a Mockito issue.

**Comment by frextrite** [comment]
Sure, I'll report this to Travis upstream aswell.

**Comment by TimvdLippe** [comment]
Closing this, as it appears to be a Travis issue outside of Mockito's control.
