### ISSUE TITLE
Any plan to add ResultCaptor

### ISSUE THREAD

**Issue by long-forgotten** [mockito/mockito#1763]
Hello team,

I've read several articles and posts about adding a ResultCaptor, and i would say it resolves part of my problems. However, what I really want is to use and verify those results during verification stage, just like `ArgumentCaptor` does, similar to below pseudo code

```java

Mockito.verifyResult(mockedObject, Mockito.times(1)).querySecurityPolicy(
                resultCaptor.capture());
// Then we can get result of mocked methods like this
resultCaptor.getValue();
// or
resultCaptor.getAllValues();
```

Regards,
Arthur

**Comment by onacit** [comment]
Related to #1259 and vice versa.

**Comment by mockitoguy** [comment]
Hi! How is your suggestion different from the current ArgumentCaptor API (copy-paste from the docs):

```
     ArgumentCaptor<Person> argument = ArgumentCaptor.forClass(Person.class);
     verify(mock).doSomething(argument.capture());
     assertEquals("John", argument.getValue().getName());
```

Please reopen if needed! Thank you for reporting.
