### ISSUE TITLE
Are strict stubs really the default in v3?

### ISSUE THREAD

**Issue by pasku** [mockito/mockito#1769]
The Strictness.STRICT_STUBS javadoc reads: "Planned as default for Mockito v3.".

I'm using "org.mockito:mockito-core:3.0.0" and strict stubs do not seem to be the default behaviour. Are they actually going to be the default in any release soon?

**Comment by TimvdLippe** [comment]
It is not. Mockito 3 only requires Java 8 as minimum. No other api changes were made. Could you submit a PR (similar to #1745) thats updates the doc?

**Comment by pasku** [comment]
What would be the easiest way of enabling it in Junit 5 given that I’m already using another Junit extension and lifecycle Per class?

`@ExtendWith(VertxExtension.class)
@TestInstance(TestInstance.Lifecycle.PER_CLASS)`

**Comment by pasku** [comment]
@TimvdLippe I just sent the PR. Any chance you could help me with the previous question? Also, is there an ETA for v4? Thanks very much.

**Comment by TimvdLippe** [comment]
The Junit 5 extension should already use strict stubs by default, does it not?

**Comment by pasku** [comment]
It does in fact seem to use strict stubs but I just double-checked and it does not throw UnnecessaryStubbingException when it should. PotentialStubbingProblem does work perfectly though.
