### ISSUE TITLE
How to use it in gradle 

### ISSUE THREAD

**Issue by lhholylight** [mockito/mockito#1770]
I used it like this testImplementation 'org.mockito:mockito-core:3.0.6',
, but there was an anomaly.  
Failed to resolve: org.mockito:mockito-core:3.0.6

and user testImplementation 'org.mockito:mockito-core:2.28.2' is ok

**Comment by szpak** [comment]
From the main (README) page:
![image](https://user-images.githubusercontent.com/148013/64233440-7b733280-cef4-11e9-9307-76d54badb3f8.png)
Plus:
> Note: not every version is published to Maven Central.

With the more detailed information [down the page](https://github.com/mockito/mockito#how-to-release-new-version).
