### ISSUE TITLE
Upgrade byte-buddy to a 1.10.x release

### ISSUE THREAD

**Issue by carterkozak** [mockito/mockito#1771]
Currently mockito uses an older build of byte-buddy. I don't see any documentation or issues suggesting that there's a reason to avoid using a newer version, though the contribution documentation doesn't mention dependency upgrades.

**Comment by pitschr** [comment]
:+1:  it should be officially upgraded to newer version of byte-buddy.

I am experiencing "Unsupported class file major version 57" (=Java 13)

**Comment by TimvdLippe** [comment]
We had an attempt in #1772 but Travis was unhappy. If someone could revive that PR and fix the build, that would be greatly appreciated!
