### ISSUE TITLE
Mockito matchers used in "when" impact the "there was one"

### ISSUE THREAD

**Issue by timgent** [mockito/mockito#178]
If you use an `any` matcher in a `when`, then if you later try and verify another method was called on the same mock it passes regardless of whether the arguments matched.

Example when it (wrongly) passes, as the method "shouldBeCalled" is called, but not with the given argument:

```scala
val mockedService = mock[MockedService]

when(mockedService.myMethod(any).thenReturn("Response")

serviceBeingTested.methodBeingTested

there was one(mockedService).shouldBeCalled("Incorrect Argument")
```

Example when it fails as it should:

```scala
val mockedService = mock[MockedService]

when(mockedService.myMethod("actualArgumentBeingUsed").thenReturn("Response)

serviceBeingTested.methodBeingTested

there was one(mockedService).shouldBeCalled("Incorrect Argument")
```

**Comment by bric3** [comment]
Hi @timgent 

I'm not reproducing, could you write a JUnit test reproducing the faced issue, with the latest version of mockito and in java please.

**Comment by bric3** [comment]
Hi,

I'll close this issue as, there's no feedback and no reproducible errors.
