### ISSUE TITLE
Make google code issue history available on our new website

### ISSUE THREAD

**Issue by bric3** [mockito/mockito#179]
[Google code is shutting down (for real)](http://google-opensource.blogspot.fr/2015/03/farewell-to-google-code.html)

* March 12, 2015 - New project creation disabled.
* August 24, 2015 - The site goes read-only. You can still checkout/view project source, issues, and wikis.
* January 25, 2016 - The project hosting service is closed. You will be able to download a tarball of project source, issues, and wikis. These tarballs will be available throughout the rest of 2016.

As we still have valuable discussion there we should have a way to make them available elsewhere for consultation.

**Comment by szczepiq** [comment]
Let's drop the Google issues. If they are important, they will resurface.

**Comment by bric3** [comment]
I still think there have been interesting discussion there, and we should have a way to keep them available, static pages would be enough, and anyway it's not a big issue

**Comment by szczepiq** [comment]
We don't seem to have time for this. If we want to do it, we can reopen.
