### ISSUE TITLE
Typo in Mockito.java Javadoc: "verification" in wiki link

### ISSUE THREAD

**Issue by mjustin** [mockito/mockito#1791]
https://github.com/mockito/mockito/blob/f8581c6e875dc3fb587fe31e85d025ef4d110a3f/src/main/java/org/mockito/Mockito.java#L2579

There's a missing "i" in the wiki link:

```
https://github.com/mockito/mockito/wiki/Greedy-algorithm-of-verfication-InOrder
https://github.com/mockito/mockito/wiki/Greedy-algorithm-of-verification-InOrder
```

**Comment by TimvdLippe** [comment]
Feel free to send a PR!

**Comment by GGeethanjali** [comment]
I am ready to pick this up
