### ISSUE TITLE
Receiving Error on usage of OR - Additional Matcher

### ISSUE THREAD

**Issue by surapuramakhil** [mockito/mockito#1796]
> Hey,
> 
> First thanks for reporting, in order to help us to classify issue can you make sure the following check boxes are checked ?
> 
> If this is about mockito usage, the better way is to reach out to
> 
>  - stackoverflow : http://stackoverflow.com/questions/tagged/mockito
>  - the mailing-list  : https://groups.google.com/forum/#!forum/mockito / mockito@googlegroups.com
>    (Note mailing-list is moderated to avoid spam)
>
> _This block can be removed_
> _Something wrong in the template fix it here `.github/ISSUE_TEMPLATE.md`

check that

 - [ ] The mockito message in the stacktrace have useful information, but it didn't help
 - [ ] The problematic code (if that's possible) is copied here;
       Note that some configuration are impossible to mock via Mockito
 - [ ] Provide versions (mockito / jdk / os / any other relevant information)
 - [ ] Provide a [Short, Self Contained, Correct (Compilable), Example](http://sscce.org) of the issue
       (same as any question on stackoverflow.com)
 - [ ] Read the [contributing guide](https://github.com/mockito/mockito/blob/release/3.x/.github/CONTRIBUTING.md)

I am getting this error when  trying to use of Additional matcher

Error:(439, 90) java: reference to or is ambiguous
  both method or(long,long) in org.mockito.AdditionalMatchers and method <T>or(T,T) in org.mockito.AdditionalMatchers match

my code:

`or(isNull(),anyLong())`
 
Mockito version: 2.23.4

**Comment by TimvdLippe** [comment]
This is a Java language issue, not a Mockito issue. Also, you probably want to use [`nullable(Long.class)`](https://static.javadoc.io/org.mockito/mockito-core/3.1.0/org/mockito/ArgumentMatchers.html#nullable-java.lang.Class-) instead.

**Comment by surapuramakhil** [comment]
@TimvdLippe thanks for helping. but I am trying to understand is that way of having function is useful for JVM based languages like Kotlin, Scala etc?

**Comment by TimvdLippe** [comment]
Sorry, I don't understand your question. Could you elaborate?
