### ISSUE TITLE
ArgumentMatcher any(Class<T>) doesn't work during stubbing

### ISSUE THREAD

**Issue by ideskov** [mockito/mockito#1808]
Hey everybody,

I just stumbled upon a very weird issue with ArgumentMatchers. A bit of background - I'm testing a REST endpoint in a Spring Boot application written in Kotlin and using WebFlux. I have managed to reproduce the issue in a small project and pushed it here -> https://github.com/ideskov/mockito-arg-matcher

Essentially, when I try to do
```Kotlin
Mockito.`when`(mock.foo(any(Bar::class.java))).thenReturn("Mocked done".toMono())
```
I get
```
org.mockito.exceptions.misusing.InvalidUseOfMatchersException: 
Misplaced or misused argument matcher detected here:

-> at ideskov.mockito.MockitoHandlerTest.test mockito argument matchers(MockitoHandlerTest.kt:26)

You cannot use argument matchers outside of verification or stubbing.
Examples of correct usage of argument matchers:
    when(mock.get(anyInt())).thenReturn(null);
    doThrow(new RuntimeException()).when(mock).someVoidMethod(anyObject());
    verify(mock).someMethod(contains("foo"))

This message may appear after an NullPointerException if the last matcher is returning an object 
like any() but the stubbed method signature expect a primitive argument, in this case,
use primitive alternatives.
    when(mock.get(any())); // bad use, will raise NPE
    when(mock.get(anyInt())); // correct usage use

Also, this error might show up because you use argument matchers with methods that cannot be mocked.
Following methods *cannot* be stubbed/verified: final/private/equals()/hashCode().
Mocking methods declared on non-public parent classes is not supported.
```
If I replace the argument with a String and do ```anyString()``` instead of ```any(Class<T>)```, it works just fine.

Not sure if it's a problem with Kotlin/Reactor and have no idea how to even start investigating. Any help would be greatly appreciated.

**Comment by TimvdLippe** [comment]
Could you send us a PR with a failing test case that reproduces your problem in isolation? Then we can debug and see what is going on :smile:

**Comment by TimvdLippe** [comment]
Could you send us a PR with a failing test case that reproduces your problem in isolation? Then we can debug and see what is going on :smile:

**Comment by ideskov** [comment]
Solution discussed in linked PR. Thanks

**Comment by santunioni** [comment]
where is the linked pr?
