### ISSUE TITLE
Warning when multiple instances of Mock exist

### ISSUE THREAD

**Issue by joshes** [mockito/mockito#181]
I've ran into this a few times now and think that an error/warning message could be used. The situation is having two interfaces of the same type being mocked via annotations, then injecting via @InjectMocks. 

It seems at run/test time, that there is some probability either will be chosen.

Admittedly, this is an edge case, but would be faster to track down if there was a warning perhaps that multiple instances of the same interface were found, but no injection point (Constructor, Property, etc) was found that applies. 

I put together an example which is reproducible easily on my machine under the following:
- JDK 1.6 + Mockito 1.9.0

I don't mind looking into providing a fix for this myself, but wanted to formalize it here before looking into it.

If you run the following a few times, you'll get different assertion errors each time, depending on which MyService gets injected.

    package example;

    import org.junit.Test;
    import org.junit.runner.RunWith;
    import org.mockito.InjectMocks;
    import org.mockito.Mock;
    import org.mockito.runners.MockitoJUnitRunner;
    import org.springframework.beans.factory.annotation.Autowired;
    import org.springframework.stereotype.Service;

    import static org.mockito.Mockito.verify;

    @RunWith(MockitoJUnitRunner.class)
    public class ExampleTest {

        @Service
        public static class MyService {

            public void doSomething() {
            }

        }

        @Service
        public static class MyClass {

            private final MyService myService;

            @Autowired
            public MyClass(MyService myService) {
                this.myService = myService;
            }

            public void doSomethingWithService() {
                myService.doSomething();
            }

        }

        @Mock
        private MyService myServiceInstance1;
        @Mock
        private MyService myServiceInstance2;
        @InjectMocks
        private MyClass myClass;

        @Test
        public void test1() throws Exception {
            myClass.doSomethingWithService();
            verify(myServiceInstance1).doSomething();
            verify(myServiceInstance2).doSomething();
        }
    }

**Comment by bric3** [comment]
Hi,

This is a known, documented and wanted behavior. If by warning you mean writing a line to the console, this could probably done, however if it's about raising an exception then I'm not sure this is the smart move.

**Comment by szczepiq** [comment]
Since the current behavior is intermittent why it is considered wanted?

Cheers!

**Comment by bric3** [comment]
Also @joshes I think more recent version of mockito have a more reproducible behavior (check 1.9.5, 1.10.19)

The wanted behavior I'm speaking about is **to not fail if injection cannot happen**, because a developper **may choose to inject them afterward**.

**Comment by joshes** [comment]
Thanks for the explanation @bric3  - that makes sense.
