### ISSUE TITLE
FR: add Mockito.timeout(java.time.Duration) and after(java.time.Duration)

### ISSUE THREAD

**Issue by kluever** [mockito/mockito#1815]
Representing durations as `long`'s is very error prone. We've seen (and fixed) hundreds of unit mismatch bugs inside of Google.

We (Guava) have recently updated most of our public APIs to add `java.time.Duration`-based overloads. [Caffeine](https://github.com/ben-manes/caffeine/issues/221) and [Selenium](https://github.com/SeleniumHQ/selenium/issues/7187) have done so as well.

Basically, I'd like to see the following APIs added:
`Mockito.after(java.time.Duration)`
`Mockito.timeout(java.time.Duration)`

And ideally the `long`-accepting APIs would be deprecated.

**Comment by TimvdLippe** [comment]
That would makes sense to me. Feel free to open a PR to add these methods.

@mockito/developers We have a lot of evidence of `long`s being misused in common API's. Do you have any concerns if we deprecate the `after(long)` in favor of `after(java.time.Duration)` (and the same for `timeout`)?

**Comment by kluever** [comment]
Ideally we'd plumb the `Duration` all the way through the various layers of Mockito:

- `org.mockito.verification.After`
- `org.mockito.verification.Timeout`
- `org.mockito.internal.verification.VerificationOverTimeImpl`
- `org.mockito.internal.util.Timer`

I assume `After` and `Timeout` need to maintain backwards compatibility, but the latter 2 are in an `internal` package - does that mean I don't need to maintain backwards compatibility? Am I free to make breaking changes to those APIs?

**Comment by TimvdLippe** [comment]
Yes, any API in `org.mockito.internal` is not included in our semver policy and we are free to change.

**Comment by bric3** [comment]
I second that, now that mockito 3 is java 8 based !
