### ISSUE TITLE
Copy on mockito.org has typo

### ISSUE THREAD

**Issue by gttaylor** [mockito/mockito#182]
![image](https://cloud.githubusercontent.com/assets/11153471/6722280/3eccad30-ce2b-11e4-9925-7bee57c41d30.png)
Under More Info

"@InjectMocks: automatically inject mocks/spies fiels annotated with @Spy or @Mock"

should read 

"@InjectMocks: automatically inject mocks/spies fields annotated with @Spy or @Mock"

**Comment by bric3** [comment]
@gttaylor  Thanks for the report :)

FYI for site issue please use the issue tracker of mockito/mockito.github.io.
