### ISSUE TITLE
Feature request: Method to reset mock interactions/invocations without resetting stubs

### ISSUE THREAD

**Issue by mjiderhamn** [mockito/mockito#183]
I'm still missing the ability to reset the invocations on a mock, while keeping all the stubbing, so this is a GitHub equivalent of https://code.google.com/p/mockito/issues/detail?id=316

Some background discussion exists in a [thread](https://groups.google.com/forum/#!topic/mockito/5G-XnpIhP3s) that also refers to [issue 84](https://code.google.com/p/mockito/issues/detail?id=84) for which there already [is a GitHub issue](https://github.com/mockito/mockito/issues/86).

**Comment by bric3** [comment]
Hi, in your use case could you be interested to stubbing only i.e. not interested by verifications ?

In this case there's this setting may prove useful : `withSettings().stubOnly()`

**Comment by mjiderhamn** [comment]
No, that would not solve my problem.

My current issue is that I have a large number of permutations (x * y) of input data, and the plan was to create reusable methods for one of the "dimensions" (`x_case1()`, `x_case2()`, `x_case3()`, ...) and then from each test case of the other dimensions (`@Test y_case1()`) call the methods of the first dimension **and pass a mock as a parameter**. That way I can set up the stubbing once, for the Y dimension, and then test and `verify()` the different X scenarios with that stub.

The workaround in this case could be to pass a lambda that does the stubbing, after each scenario has created it's mock.

(I do agree it would be preferable in this particular case to refactor this to something that is more testable, and hopefully I can get part of the way there, but sometimes reality is just complex and it is definitely not the first time I've missed this particular feature in Mockito.)

**Comment by bric3** [comment]
OK

Well at the moment the team is clearly busy in other RL projects. If you manage to make a nice PR (see the contributing guide) of this feature before we do work on it, which seems most probable we may integrate your work :)

**Comment by diversit** [comment]
I created a new issue (#284) for removing any invocations which have been verified. In my optioning resetting the invocations would then not been needed anymore and the current reset can stay as-is. This also give you a stronger guarantee that you're really verifying all invocations of the mock.
