### ISSUE TITLE
java.lang.instrument ASSERTION FAILED ***: "!errorOutstanding" with message transform method call failed at JPLISAgent.c line: 844

### ISSUE THREAD

**Issue by i337911** [mockito/mockito#1831]
Using Mock
settingsParameters = doReturn(settingsParameters).when(mobileServiceClientTest).getSettingsParameters(anyString(),anyString(), anyString());

the test case can pass, but the error will show 
*** java.lang.instrument ASSERTION FAILED ***: "!errorOutstanding" with message transform method call failed at JPLISAgent.c line: 844

**Comment by TimvdLippe** [comment]
Please provide a minimal reproducible test case that shows the issue. The above message seems like a JDK internal issue on your local machine.
