### ISSUE TITLE
Test Failure due to Autogenerated Suffix: "<mock>.MockitoMock.123456789"

### ISSUE THREAD

**Issue by skis** [mockito/mockito#1836]
Hello Team,
When I run the JUnits using IntelliJ/Eclipse the tests are good. However, when I run the same code with Jenkins and run it as part of Automated Tests, One of the tests fails with an IllegalArgumentException (**_thrown from proprietary framework class_**) with a reason that the mock name and the expected name do not match.

The Mock name passed at runtime has some strange suffix ".MockitoMock.123456789" (**NOTE**: _123456789_ is not the exact number that I see in the exception. However, _a 9 digit random number is present_)

Could you suggest what in Mockito might be causing the mock to be generated with that strange suffix?

Thanks

check that

 - [x] The mockito message in the stacktrace have useful information, but it didn't help
 - [ ] The problematic code (if that's possible) is copied here;
       Note that some configuration are impossible to mock via Mockito
 - [x] Mockito 2.24.5, Open JDK 11
 - [ ] Provide a [Short, Self Contained, Correct (Compilable), Example](http://sscce.org) of the issue
       (same as any question on stackoverflow.com)
 - [x] Read the [contributing guide](https://github.com/mockito/mockito/blob/release/3.x/.github/CONTRIBUTING.md)

**Comment by TimvdLippe** [comment]
Is the testing framework performing reflection on the type? That will likely fail, as mocks are proper subclasses of the type-to-be-mocked. We generate these suffixes to avoid class name clashes when generating these subclasses.

**Comment by skis** [comment]
No, there is no reflection in my case. The problem doesn't occur when I run the test on its own. But, when I run it as part of larger test execution i.e. overall test execution for the application which includes all the JUnits using Jenkins, that is when I run into this problem.

**Comment by TimvdLippe** [comment]
We will need the full test case to be able to debug this issue sorry :cry: We don't know if this is an issue in Mockito or in the proprietary framework.

**Comment by skis** [comment]
Yeah, had a feeling about that... I will try to put something together 😢 
Hopefully by EOD.

**Comment by skis** [comment]
I noticed deep within the proprietary framework there is a block of code that relies on Reflection.
However, a question: Why would the test run successfully when I run from Eclipse/IntelliJ but, not when I run it from Jenkins? Any clues?

I am still working on to put together a mockup of sort to share here for your suggestions.

**Comment by skis** [comment]
@TimvdLippe - It may not be possible to setup a sample that I may share here.
A question about below syntax though

Example:

```
@Mock 
Vehicle vehicle;
@Mock(Answers.RETURNS_MOCKS)
Type car;

Mockito.doCallRealMethod().when(vehicle).initializeVehicle(car);
```

When executed, the actual `initializeVehicle` method is run obviously. However, the argument `car` also invokes the real implementation. Is it possible to have the real method `initializeVehicle` executed on the `vehicle` but, not on the `car`?

_Note_: I tried to force tell that `car` should use the Mocks and not the real implementation.

**Comment by TimvdLippe** [comment]
I am not sure if I understand. Could you write it as a JUnit test that I can run? You can open a PR and I can fetch your patch and debug it.

**Comment by skis** [comment]
Sure, I will do that. Thanks

**Comment by skis** [comment]
Could not put together sample code that could be shared and so, closing the ticket.
