### ISSUE TITLE
Improve the error message on contains method

### ISSUE THREAD

**Issue by mdeinum** [mockito/mockito#1838]
When using Mockito and in this specific case using `extracting("name1", "name2").contains(val1, val2)` or the functional one `extracting(it -> it.getName1(), it -> it.getName()).contains(val1, val2)`. In case of a value not matching the error message is not as descriptive as one likes to be. 

Currently it is :
```
Expecting:
  <[null, 2019-12-05T07:57:38.531, null]>
to contain exactly (and in same order):
  <[null, 2019-12-05T07:57:38.531, null]>
but some elements were not found:
  <[2019-12-05T07:57:38.531]>
and others were not expected:
  <[2019-12-05T07:57:38.531]>
```
And at first glance it isn't apparent what is wrong, as the values appear to match. However as it turned one one was a `LocalDateTime` and the other a `java.util.Date`. 

When comparing a single property with `isEqualTo` the error message is more descriptive

```
java.lang.AssertionError: 
Expecting:
 <"2019-12-05T07:59:56.439 (LocalDateTime@43f02ef2)">
to be equal to:
 <"2019-12-05T07:59:56.439 (Date@239a307b)">
but was not.
```

Now it is directly apparent what the error is as the type and hashcode is included in the error message. 

It would be beneficial of the message from contains could also include the type and hashcode in the error message.

**Comment by mockitoguy** [comment]
Can you double check that this is a valid Mockito issue? The error message "Expecting... to be equal to..." smells like Hamcrest. Mockito does not produce such Strings.

If this is not Mockito issue, please close the ticket. Thanks!

**Comment by mockitoguy** [comment]
Actually, I'll close it and if you believe it's Mockito problem, just reopen. Thanks for reporting and for using Mockito!

**Comment by mdeinum** [comment]
I must have been sleeping or in dire need of a holiday, this should have been an AssertJ issue and not a Mockito issue. Sorry for the inconvenience.

**Comment by mockitoguy** [comment]
No problem!
