### ISSUE TITLE
Allow @MockitoSettings to be inherited

### ISSUE THREAD

**Issue by fabianMendez** [mockito/mockito#1853]
- [X] The mockito message in the stacktrace have useful information, but it didn't help
 - [X] The problematic code (if that's possible) is copied here;
       Note that some configuration are impossible to mock via Mockito
 - [X] Provide versions (mockito / jdk / os / any other relevant information)
 - [X] Provide a [Short, Self Contained, Correct (Compilable), Example](http://sscce.org) of the issue
       (same as any question on stackoverflow.com)
 - [X] Read the [contributing guide](https://github.com/mockito/mockito/blob/release/3.x/.github/CONTRIBUTING.md)

I have a base test class which among other things mocks a "serviceLocator" and a very common class used by many other services:

```java
@ExtendWith(MockitoExtension.class)
public abstract class DomainServiceTests<T> {
	@Mock
	protected ServiceLocator sl;

	@Spy
	protected UserEnvironmentService userEnvironment;

	@BeforeEach
	public void setup() throws Exception {
		Mockito.when(sl.get(UserEnvironmentService.class)).thenReturn(userEnvironment);
	}
}
```

But whenever any test try to mock the get method of this serviceLocator with a different class I get an UnnecessaryStubbingException:

```
org.mockito.exceptions.misusing.UnnecessaryStubbingException:
    Unnecessary stubbings detected.
    Clean & maintainable test code requires zero unnecessary code.
    Following stubbings are unnecessary (click to navigate to relevant line of code):
      1. -> at *.DomainServiceTests.setup(DomainServiceTests.java:24)
    Please remove unnecessary stubbings or use 'lenient' strictness. More info: javadoc for UnnecessaryStubbingException class.
```

Then I specify the strictness in the base test class 

```java
@MockitoSettings(strictness = Strictness.WARN)
public abstract class DomainServiceTests<T> {
```
But even though the strictness is not seen by mockito.

I have debugged the code and found that the strictness is retrieved by searching the annotation on the method and the class of the test

https://github.com/mockito/mockito/blob/b2b66f430a5bf890135c0c25872bf9869eb09aec/subprojects/junit-jupiter/src/main/java/org/mockito/junit/jupiter/MockitoExtension.java#L143-L145

This eventually calls 

https://github.com/junit-team/junit5/blob/5e41ebe612fd67e905f96f1dd3184a071b65be17/junit-platform-commons/src/main/java/org/junit/platform/commons/util/AnnotationUtils.java#L108-L112
```java
public static <A extends Annotation> Optional<A> findAnnotation(AnnotatedElement element, Class<A> annotationType) {
	Preconditions.notNull(annotationType, "annotationType must not be null");
	boolean inherited = annotationType.isAnnotationPresent(Inherited.class);
	return findAnnotation(element, annotationType, inherited, new HashSet<>());
}
```

So if you annotate `MockitoSettings` with `java.lang.annotation.Inherited` it will work (I turned the inherited variable to true using the debugger to confirm).

For now I will have to annotate every test class with
```java
@MockitoSettings(strictness = Strictness.WARN)
```

I am using  Gradle 7.0 with JUnit 5.5.2

Thanks

**Comment by TimvdLippe** [comment]
Feel free to send a PR with a fix. Awesome issue description :)

**Comment by ngueno** [comment]
Hi @TimvdLippe 

I am currently using the **mockito-junit-jupiter v3.2.4** and I can see that `@MockitoSettings` still does not have inheritance support:

```
@ExtendWith(MockitoExtension.class)
@Retention(RUNTIME)
public @interface MockitoSettings {
   ...
}
```
Do you know when, or, if there is any plans to release a new version of mockito-junit-jupiter containing this improvement?

For now I am including the annotation on each test, but it would be great to refactor and keep it on just my AbstractTest class.

**Comment by TimvdLippe** [comment]
New version should be pushing to Maven Central as we speak: https://github.com/mockito/mockito/commit/0a3064df2cbfcbf3145db54320c704971600ac6d

**Comment by ngueno** [comment]
@TimvdLippe That's awesome!

Unfortunately Travis is not very happy:

```
[performRelease] > Could not sync 'mockito/maven/mockito/3.3.0' to Maven Central: HTTP/1.1 400 Bad Request [status:Sync Failed, messages:[Failed to close repository: orgmockito-1399. Server response:

[performRelease]    <nexus-error>

[performRelease]     <errors>

[performRelease]       <error>

[performRelease]         <id>*</id>

[performRelease]         <msg>Unhandled: Repository: orgmockito-1399 has invalid state: closed</msg>

[performRelease]       </error>

[performRelease]     </errors>

[performRelease]   </nexus-error>, Dropping existing partial staging repository.]]
```

**Comment by TimvdLippe** [comment]
That's sadly a known issue with Maven Central, but the artifact should be installable for you: https://repo1.maven.org/maven2/org/mockito/mockito-core/3.3.0/
