### ISSUE TITLE
Allow Java 8 default ("defender") methods to be tested

### ISSUE THREAD

**Issue by hbf** [mockito/mockito#186]
Java 8 allows default methods on interfaces. It seems like a legitimate use case to test these, by mocking the results of non-default methods of the interface. Here's a (hypothetical) example that currently doesn't work with Mockito:

```java
import org.junit.Assert;
import org.junit.Test;
import org.mockito.Mockito;

public class Java8DefaultMethodTest {

    interface I {
        int i();
        default int f() {
            return i() + 1;
        }
    }

    @Test
    public void testFAddsOne() {
        I h = Mockito.mock(I.class);
        Mockito.when(h.i()).thenReturn(2);
        Assert.assertEquals(3, h.f());
    }
}
```

What is needed to make this work?

I've tried adding `Mockito.when(h.f()).thenCallRealMethod()` but this didn't work. Also, there has been a related question (see Google Code ticket [#456](https://code.google.com/p/mockito/issues/detail?id=456)) which is similar in that it is related to Java 8 default methods but not the same because it deals with _implementations_ of interfaces containing default methods.

**Comment by bric3** [comment]
Hi,

Thank you very much for the unit test. I know we are a bit late to support nifty Java 8 stuff. It'll come eventually in some 2.0 beta.

**Comment by hbf** [comment]
That's exciting news! Thanks for the great work. 

I'm wondering whether in the meantime there's a way to make this work in the 1.x branch? I've played around quite a bit but haven't found a way.

**Comment by bric3** [comment]
@hbf I'm excited too by nifty stuff of Java 8 too, yet we need some time to do this work and research on this, and most of us are quite busy IRL or other part of our job.

**Comment by uweschaefer** [comment]
If there was a way to vote for this issue, i would :)

**Comment by spmallette** [comment]
:+1:

**Comment by raphw** [comment]
This works now after removing the explicit Java version number for mocks:

```java
    interface I {
        int i();
        default int f() {
            return i() + 1;
        }
    }

    @Test
    public void testFAddsOne() {
        I h = Mockito.mock(I.class);
        when(h.i()).thenReturn(2);
        when(h.f()).thenCallRealMethod();
        assertEquals(3, h.f());
    }
```

This test runs green. Unfortunately, adding it requires a Java 8 language level for Mockito. (Byte Buddy only generates Java 8 code if it is possible, Java 6 is still fully supported.)

**Comment by bric3** [comment]
At that time CGLIB was still used too. So thanks to ByteBuddy in general as well. It offers many more features than CGLIB.

**Comment by bric3** [comment]
If you don't mind, I'd like to close this ticket when we have a test for that.

**Comment by raphw** [comment]
I do not. Just that this would require a Java 8 source level for building Mockito.

**Comment by bric3** [comment]
Yeah that's the issue, I had ideas on that matter regarding CI. However I didn't have time to experiment yet.

**Comment by szczepiq** [comment]
Perhaps mockito should move to java 8. If someone use java7 he can use
older mockito ;) Thoughts?

**Comment by uweschaefer** [comment]
+1 for J8 version

**Comment by bric3** [comment]
I'd like that too. But ain't happening on 2.x, as this may be too much of a breaking change.

Actually I'm thinking something _à la_ AssertJ i.e. another majoré version, like mockito 3 that will be jdk8 only.

**Comment by raphw** [comment]
I can offer to implement tests that are precompiled and only executed on Java 8 VMs as I did for Byte Buddy: https://github.com/raphw/byte-buddy/blob/master/byte-buddy-dep/src/test/java/net/bytebuddy/test/utility/JavaVersionRule.java

**Comment by bric3** [comment]
Interesting.

I remember I implemented some gradle sub project only activated on jdk8 in gradle some time ago but lost it due to SSD failure. I'm still with mixed feelings about all approaches.

**Comment by xenoterracide** [comment]
Does mockito support plugins? maybe there could be a separate jar that people could install separately if using java8 that does this. Like Hibernate has an extension for Java 8 types.

Either way having problems with this, more or less blocks me from using Mockito for my probject.

**Comment by raphw** [comment]
I think you misunderstood. Mockito already supports defender methods, only the tests would require Java 8.

**Comment by xenoterracide** [comment]
oh, well I guess I read this wrong then, my bad. cool.

**Comment by raphw** [comment]
No worries. And thanks for trying out the beta. If you experience anything that could be solved better, please drop a line and we'll try to improve the beta before its release!

**Comment by bric3** [comment]
I feel like we should close this issue, or do these pre-compiled java 8 tests

**Comment by runeflobakk** [comment]
Typically, default methods are convenience methods which calls abstract methods which must be implemented by concrete classes. They offer some alternate ways to access the regular abstract interface methods, and as such the behaviour of the default methods are directly dependent on how abstract methods are mocked (or not). Trivial example:

```java
interface A {
  byte[] process(InputStream in);

  default byte[] process(byte[] bytes) {
    return process(new ByteArrayInputStream(bytes));
  }
}
```

When mocking `A`, I am only interested in stubbing the `transform(InputStream in)`method, and not worry about if my code calls the method accepting an `InputStream` or a `byte[]` argument.

I use the following code to say "call all real default methods":

```java
mock(A.class, withSettings()
   .defaultAnswer(invocation -> invocation.getMethod().isDefault() ? invocation.callRealMethod() : RETURNS_DEFAULTS.answer(invocation)));
```

Just wanted to tell about my use case, and maybe it is such a common case that the API should offer some easy way to do just that? This enables me to just stub the abstract method, and the result of the default method depends on the abstract method.

(And I really wish it was possible to define _final_ default methods in Java interfaces, but that's another discussion :wink: )

**Comment by messo** [comment]
@runeflobakk thanks for sharing your solution. Exactly what I was looking for :+1: I think it would be nice to have this as "default" settings for interfaces with default methods.

**Comment by hbf** [comment]
@messo +1 for having this as a default

**Comment by messo** [comment]
The only strange thing do, that `when(mock.defaultInterface()).thenResult(...)` counts towards the invocation count in `verify(mock, times(<x>)).defaultInterface()`. That seems to be a bug or something

**Comment by raphw** [comment]
I did add a unit test now using Byte Buddy that generates an interface with a default method only when the executing Java VM supports Java 8.

**Comment by bric3** [comment]
interesting commit https://github.com/mockito/mockito/commit/8408b63b194ab319ffb1cb249e95af46e942cb01 ;)

**Comment by hbf** [comment]
@raphw You say that the test

```java
    interface I {
        int i();
        default int f() {
            return i() + 1;
        }
    }

    @Test
    public void testFAddsOne() {
        I h = Mockito.mock(I.class);
        when(h.i()).thenReturn(2);
        when(h.f()).thenCallRealMethod();
        assertEquals(3, h.f());
    }
```

passes for you. I'm trying this against Mockito 1.10.19 and it fails:

    java.lang.NoSuchMethodError: java.lang.Object.f()I

Are you using the 2.x branch?

**Comment by raphw** [comment]
Yes, this only work for the new versiin

**Comment by hbf** [comment]
Ok, thanks, @raphw for clarifying!
