### ISSUE TITLE
Javadoc sort error

### ISSUE THREAD

**Issue by Sailfishc** [mockito/mockito#1861]
Hey, i'm a mockito beginer, i learn mockito example on https://javadoc.io/doc/org.mockito/mockito-core/latest/org/mockito/Mockito.html , i want to try the lastest version of 2.x，on website, i found lastest  version of 2.x is 2.9.0，but the last version is  2.28.2, the sort is not friendly for beginer. i think this is a sort error . thank you.

![3961579502286_ pic_hd](https://user-images.githubusercontent.com/13750989/72706241-78719980-3b98-11ea-9c40-d12f5f38361c.jpg)

**Comment by bric3** [comment]
Hi @Sailfishc,

This has nothing to do with mockito. We do not manage javadoc.io. If you have suggestions you should report them here: https://github.com/maxcellent/javadoc.io

**Comment by Sailfishc** [comment]
thanks
