### ISSUE TITLE
Invalid package reference in library; not included in Android: java.lang.instrument. Referenced from net.bytebuddy.agent.ByteBuddyAgent.

### ISSUE THREAD

**Issue by Drjacky** [mockito/mockito#1876]
- [ ] The mockito message in the stacktrace have useful information, but it didn't help
 - [ ] The problematic code (if that's possible) is copied here;
       Note that some configuration are impossible to mock via Mockito
 - [X] Provide versions (mockito / jdk / os / any other relevant information)
 - [X] Provide a [Short, Self Contained, Correct (Compilable), Example](http://sscce.org) of the issue
       (same as any question on stackoverflow.com)
 - [X] Read the [contributing guide](https://github.com/mockito/mockito/blob/release/3.x/.github/CONTRIBUTING.md)

mockito-kotlin: 2.2.0
mockito-core: 2.23.0
mockito-inline: 2.22.0

Error when I use `./gradlew build`:
> ../../../../../../.gradle/caches/modules-2/files-2.1/net.bytebuddy/byte-buddy-agent/1.9.0/37b5703b4a6290be3fffc63ae9c6bcaaee0ff856/byte-buddy-agent-1.9.0.jar: Invalid package reference in library; not included in Android: java.lang.instrument. Referenced from net.bytebuddy.agent.ByteBuddyAgent.
> ../../../../../../.gradle/caches/modules-2/files-2.1/net.bytebuddy/byte-buddy-agent/1.9.0/37b5703b4a6290be3fffc63ae9c6bcaaee0ff856/byte-buddy-agent-1.9.0.jar: Invalid package reference in library; not included in Android: java.lang.management. Referenced from net.bytebuddy.agent.ByteBuddyAgent.ProcessProvider.ForCurrentVm.ForLegacyVm.

Which of course we can ignore it by:
```groovy
android {
        lintOptions {
        warning 'InvalidPackage'
    }
```

**Comment by TimvdLippe** [comment]
This is most likely a problem in your local setup. If you are able to provide a self-contained reproduction case, feel free to reopen this issue.

**Comment by isuPatches** [comment]
I started to find this after upgrading Mockito to 3.3.3.  The previous version of 2.28.2 did not show this lint warning/error.

```
  Errors found:
  
  /Users/patches/.gradle/caches/modules-2/files-2.1/net.bytebuddy/byte-buddy-agent/1.10.5/d1c949ee74c3421ffd3d9159c867777ded928448/byte-buddy-agent-1.10.5.jar: Error: Invalid package reference in net.bytebuddy:byte-buddy-agent; not included in Android: java.lang.instrument. Referenced from net.bytebuddy.agent.ByteBuddyAgent. [InvalidPackage]
  /Users/patches/.gradle/caches/modules-2/files-2.1/net.bytebuddy/byte-buddy-agent/1.10.5/d1c949ee74c3421ffd3d9159c867777ded928448/byte-buddy-agent-1.10.5.jar: Error: Invalid package reference in net.bytebuddy:byte-buddy-agent; not included in Android: java.lang.management. Referenced from net.bytebuddy.agent.ByteBuddyAgent.ProcessProvider.ForCurrentVm.ForLegacyVm. [InvalidPackage]
  /Users/patches/.gradle/caches/modules-2/files-2.1/org.mockito/mockito-core/3.3.3/4878395d4e63173f3825e17e5e0690e8054445f1/mockito-core-3.3.3.jar: Error: Invalid package reference in org.mockito:mockito-core; not included in Android: javax.tools. Referenced from org.mockito.internal.creation.bytebuddy.InlineByteBuddyMockMaker. [InvalidPackage]
```
