### ISSUE TITLE
Unbalanced HTML tags in Javadoc of UnnecessaryStubbingException

### ISSUE THREAD

**Issue by rillig-tk** [mockito/mockito#1880]
In the [Javadoc of that class](https://javadoc.io/static/org.mockito/mockito-core/3.3.1/org/mockito/exceptions/misusing/UnnecessaryStubbingException.html), the `<code` is not closed properly. Because of this, the following paragraphs are rendered in monospace font as well.

While here, `effect not` should be `effect of not`.

**Comment by TimvdLippe** [comment]
Could you send us a PR to fix this?

**Comment by rillig-tk** [comment]
Wouldn't it be easier if you just added the missing `</code>` and `of`? It's just two words.

**Comment by TimvdLippe** [comment]
Yeah, if you could open a PR to make that change we can fix it 😄

**Comment by rillig-tk** [comment]
Closed due to too complicated workflow.

**Comment by TimvdLippe** [comment]
Let's reopen so that someone else can make the PR.
