### ISSUE TITLE
Properties with Mock annotations are initialized after TestRules since Mockito 2.26.0+

### ISSUE THREAD

**Issue by sarod** [mockito/mockito#1884]
- [x] The mockito message in the stacktrace have useful information, but it didn't help
 - [x] The problematic code (if that's possible) is copied here;
       Note that some configuration are impossible to mock via Mockito
 - [x] Provide versions (mockito / jdk / os / any other relevant information)
 - [X] Provide a [Short, Self Contained, Correct (Compilable), Example](http://sscce.org) of the issue
       (same as any question on stackoverflow.com)
 - [X] Read the [contributing guide](https://github.com/mockito/mockito/blob/release/3.x/.github/CONTRIBUTING.md)

The following code works find with Mockito 2.25.1 but fails with 2.26.0+ with the 
IllegalStateException("myMock property need to be setup first") being thrown.
```java
import org.junit.Rule;
import org.junit.Test;
import org.junit.rules.ExternalResource;
import org.junit.runner.RunWith;
import org.mockito.Mock;
import org.mockito.junit.MockitoJUnitRunner;

@RunWith(MockitoJUnitRunner.class)
public class MockitoBug {
	@Mock
	private Object myMock;
	@Rule
	public ExternalResource myRule = new ExternalResource() {
		@Override
		protected void before() throws Throwable {
			if (myMock == null) {
				throw new IllegalStateException("myMock property need to be setup first");
			}
		}
	};
	@Test
	public void myTest() {}
}
```

After some investigation I think the root cause of this breaking change is https://github.com/mockito/mockito/commit/49e6311fcf774f6931ffbb627702e4fb99ef3604

**Comment by sarod** [comment]
I tried to use MockitoJUnit.rule() instead of MocktioJunitRunner but I it fails (in both 2.25 and 2.26+)

**Comment by sarod** [comment]
For the record I found a workaround using RuleChain

```java
public class MockitoBug {

	@Mock
	private Object myMock;

	public ExternalResource myRule = new ExternalResource() {
		@Override
		protected void before() throws Throwable {
			if (myMock == null) {
				throw new IllegalStateException("myMock property need to be setup first");
			}
		}
	};
	
	@Rule
	public RuleChain ruleChain = RuleChain.outerRule(MockitoJUnit.testRule(this)).around(myRule);

	@Test
	public void myTest() {
		//
	}
}
````

**Comment by TimvdLippe** [comment]
As I understand it, you are implicitly relying on the ordering behavior of the runner and the rule, which is brittle. The Rule documentation states that if you rely on the behavior of multiple rules/runners, you should use RuleChain. Therefore, I think your solution is valid and WAI.

**Comment by sarod** [comment]
Agreed. I'll close the issue.
