### ISSUE TITLE
Add java.time types to ReturnsEmptyValues

### ISSUE THREAD

**Issue by kluever** [mockito/mockito#1885]
Just as `String` and `Optional` are special cased, I wonder if we should have defaults for `Duration` and `Instant` (one might even be able to make a case for doing all of the `java.time` as well actually...)

**Comment by TimvdLippe** [comment]
Happy to merge a PR for this 😄

**Comment by mikolajczykmarcin** [comment]
I can code it, I should finish today or tomorrow, my first gh contribution :)

**Comment by tommai78101** [comment]
Question to @mikolajczykmarcin 

Do you also need `OffsetDateTime` and `ZonedDateTime`?

**Comment by mikolajczykmarcin** [comment]
> Question to @mikolajczykmarcin
> 
> Do you think it's a good idea to add the same for `OffsetDateTime` and `ZonedDateTime`? They are also used as alternatives to `LocalDateTime`, in that they both store more information, like time zones and GMT/DST.

we decided to remove instant/date/time empty values as it was not obvious that EMPTY value means EPOCH. so only Period and Duration has been left for this issue

**Comment by tommai78101** [comment]
Thanks for the info.
