### ISSUE TITLE
Deprecation doc is wrong

### ISSUE THREAD

**Issue by biergit** [mockito/mockito#1887]
https://github.com/mockito/mockito/blob/560adf377677a4a2c658a0b24e2f9c2e0b373c20/src/main/java/org/mockito/Mockito.java#L2252 should suggest using `verifyNoMoreInteractions` instead of `verifyNoInteractions` as discussed [here](https://github.com/mockito/mockito/issues/989)

**Comment by TimvdLippe** [comment]
Happy to merge a PR for this 😄

**Comment by TimvdLippe** [comment]
Closing per https://github.com/mockito/mockito/pull/1889#issuecomment-600358917 Sorry for the trouble!

**Comment by biergit** [comment]
A quite confusing but reading all the JavaDoc then it makes sense. Sorry for this :)
