### ISSUE TITLE
Documentation typo

### ISSUE THREAD

**Issue by hamid-nazari** [mockito/mockito#1888]
I found a little typo in Mockito's latest documentation (javadoc on `org.mockito.Mockito`); at the end of the second sentence under [note #31](https://javadoc.io/static/org.mockito/mockito-core/3.3.3/org/mockito/Mockito.html#serilization_across_classloader) it reads 

> ..., _inclusing_ answers.

which must be corrected to 

> ..., **including** answers.

**Comment by TimvdLippe** [comment]
I will be happy to merge a PR for this 😄
