### ISSUE TITLE
ArgumentMatchers.matches not working

### ISSUE THREAD

**Issue by sysmat** [mockito/mockito#1905]
* Ver. mockito-core:3.3.3
* Java Pattern and java Matcher

```java
Pattern pat = Pattern.compile("^zman-server-");
Matcher mat = pat.matcher("zman-server-store.properties");
mat.find() // return true
```

* Mockito matcher not wrking:

```
when(streamer.load( matches(pat))).thenReturn(stream);

Output:
- this invocation of 'load' method:
    streamer.load(
    "zman-server-store.properties"
);
 - has following stubbing(s) with different arguments:
    1. streamer.load("");

```

**Comment by dean-burdaky** [comment]
Hello,

I've taken a look at the issue and after doing some digging I found that `matches(Pattern)` uses [`java.util.regex.Matchers.matches()`](https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/util/regex/Matcher.html#matches()) in `org.mockito.internal.matchers.Matches.matches(Object)` which requires the entire region to match, not just some sub-region like [`Matchers.find()`](https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/util/regex/Matcher.html#find()) does. This means that your matcher fail when testing to see if your answer, `thenReturn(stream)`, is suitable for the mock's `load(...)` invocation.

I'll probably make a PR with the solution, appropriate acceptance testing and any needed documentation changes.

**Comment by sysmat** [comment]
Thx, that explain a lot.
