### ISSUE TITLE
The project/framework lacks user guide documentation for new users

### ISSUE THREAD

**Issue by maald** [mockito/mockito#1918]
As a new end user, I cannot find a single user guide or decent documentation. The javadoc reads like it's written as a quick review for someone who already knows the ins/outs of Mockito and just need some sample code. I don't even know what or how Mockito works and the first couple of lines are talking about "mockito inline". 

Most open source projects have really great user guides and documentation. Sadly not this one.
Here is just a short list of amazing documentations:
[JUnit User Guide ](https://junit.org/junit5/docs/current/user-guide/)
[CDI User Guide](https://docs.jboss.org/cdi/learn/userguide/CDI-user-guide.html)
[Spring](https://docs.spring.io/spring/docs/current/spring-framework-reference/index.html)
[Jersey](https://eclipse-ee4j.github.io/jersey.github.io/documentation/latest/index.html)
...

**Comment by TimvdLippe** [comment]
From our main website mockito.org we link to our documentation: https://javadoc.io/doc/org.mockito/mockito-core/latest/org/mockito/Mockito.html Were you able to find this documentation? If so, could you explain what is complicated for you? If not, do you maybe know how you missed it and what we can do to prevent that from happening?

**Comment by maald** [comment]
I'm looking for a little more explanation on how the framework works. I'm sure I can spend my time browsing the source code to figure it out but that's totally unproductive.

Here's a tiny example:

`
 //You can mock concrete classes, not just interfaces
 LinkedList mockedList = mock(LinkedList.class);

 //stubbing
 when(mockedList.get(0)).thenReturn("first");

 //following prints "first"
 System.out.println(mockedList.get(0));
`


I can just copy/paste that and never care to learn how Mockito actually works. The API looks very simple but it's so counter-intuitive. 
I found myself asking: where's the explanation on what's going on in that code? Like `mockedList.get(0)` is just a simple method call in java. Let's assume a mocked instance returns a primitive int. How does `when(T methodcall)` which is just another method call in java magically knows what mocked instance methods you called from the return value (primitive int)? in other words, will this work too

`
int literalValue = 0;
when( literalValue ).thenReturn("first");

int returnValue = mockedInstace.getIntValue(); 
when( returnValue ).thenReturn("first");
`

That's the missing documentation. The sample code is great for a quick review but where is the explanation? I attached a couple of user guides/documentation of other major open source projects. It very disappointing that a major project like Mockito doesn't even have anything that remotely looks like a real user guide. 

This was asked 7 years ago and has just 2 answers https://stackoverflow.com/questions/14440270/how-does-mockito-when-invocation-work . It feels like no one actually knows how it works because there is no documentation that you can read and understand what's going on/it's just magic/copy paste.


Sorry if this comment sounds like a rant but I'm super disappointed at the lack of documentation; I was super excited to finally have the time to learn Mockito but now it's just going to be copy/paste magic tool that I use.

**Comment by TimvdLippe** [comment]
Users are not supposed to know how Mockito internally works, that is the job of the maintainers (aka us). The stackoverflow question you linked is a decent explanation of it. But then again, you as a user are not supposed to know about everything that is going on behind the scenes to make the test work as you do.

Our user guide is tailored to explain what you need to do to **express your intent**. As long as you can tell Mockito what to do (e.g. **when** you invoke this method **then return** this value), we will handle the rest. It is therefore Mockito's job to adhere to these expectations and make sure we don't break them.

If you are interested in contributing to Mockito, a read through the source code is required and strongly encouraged. In general, our implementation should be readable even for those without strong knowledge of Proxy implementations and bytecode generation.

If you want to understand the core parts of Mockito on bytecode generation, there is excellent documentation of ByteBuddy at https://bytebuddy.net/#/ Then again, I don't advice you to read through that documentation if you don't have strong skills in JVM internals and are a beginner in Java programming.

**Comment by maald** [comment]
I agree that end users generally don't need to understand how the framework is implemented. The issue I'm trying to communicate is the following: when you take something as simple as a method call and turn it on a magic, I think it's reasonable to expect so explanation. That way when I debug some code, I know where to look. Will this code work the same? By Java rules, yes it's just a simple method call. What about Mockito? Will it break if I split the code into multiple lines like the second one.

```java
when( mockedInstace.getIntValue() )....

int returnValue = mockedInstace.getIntValue(); 
when( returnValue )...

int literalValue = 0;
when( literalValue )....

```

The current documentation of course doesn't discuss the implementation (as expected) but also does answer that simple question.

**Comment by TimvdLippe** [comment]
Closing this, as I don't think this is worthwhile to include in our main documentation. If the behavior of Mockito is not intuitive, I consider that a bug instead of a lack of documentation.
