### ISSUE TITLE
Kotlin Result seems to behave weirdly when trying to be returned with Mockito

### ISSUE THREAD

**Issue by adrianhescalante** [mockito/mockito#1930]
I am facing an issue when trying to use the Kotlin Result in my project. I am trying to mock the return value as shown here:
```kotlin
`when`(useCase.getA()).thenReturn(Result.success(ObjectA("testName")))
```
The exception when trying to use that returned Result is this one: `java.lang.ClassCastException: kotlin.Result cannot be cast to ObjectA`

An interesting thing I found when debugging is that if I check the returned value of that `useCase.getA()` function, it returns an object with description `Success(Success(ObjectA(name=testName)))`. A regular Result returns this description `Success(ObjectA(name=name))`. I guess that's the reason it's failing, it seems there is like a nested Result object, so I am assuming there is something wrong with Mockito when handling the Kotlin Result class.

This is a [gist](https://gist.github.com/adrianhescalante/30449c876608fb7283e52c4d6acc5ad6)  I created to test it. There are two tests, one with the Kotlin Result and another one with a quick Result implementation (OwnResult) to check there is not something wrong I am doing myself.

I am using Mockito 3.3.3 on an Android project with Java 8.

**Comment by ChristianSchwarz** [comment]
@adrianhescalante You can try mockk instead if you use kotlin

**Comment by adrianhescalante** [comment]
Yes, I migrated the project to Mockk in the end. Thank you.

**Comment by TimvdLippe** [comment]
For Kotlin projects, we now recommend `mockito-kotlin`: https://github.com/mockito/mockito-kotlin If you can still reproduce this issue, please open an issue over there and we can investigate further.
