### ISSUE TITLE
feature request: provide a config to prevent mocks returned from mocks

### ISSUE THREAD

**Issue by grimreaper** [mockito/mockito#1937]
Returning a mock from a mock is a sign of poor test design. In order to guide users into doing the right thing, we should provide a method to allow mockito to throw an exception when this happens. This is similar to how to strictstubs throws an exception for unused stubs. Since this is a different concern from orthogonal config from the existing "strict" level it should be a different knob.

**Comment by TimvdLippe** [comment]
I don't think this is something Mockito should implement. Instead, you can use a checker framework such as ErrorProne (http://github.com/google/error-prone) to turn this in a compilation error.
