### ISSUE TITLE
Mockito-inline fails to choose correct method to mock for Kotlin classes with "reified" methods in Java tests

### ISSUE THREAD

**Issue by juv** [mockito/mockito#1943]
Hi, 

I am running into a Mockito (mockito-inline) problem when mocking a final Kotlin class in Java.
The method that I want to mock: [`fun header(header: String): String? = req.getHeader(header)`](https://github.com/tipsy/javalin/blob/master/javalin/src/main/java/io/javalin/http/Context.kt#L248)
The method that Mockito is choosing in a random way on execution of the test... which is causing an exception: [`inline fun <reified T : Any> header(header: String) = header(header, T::class.java)`](https://github.com/tipsy/javalin/blob/master/javalin/src/main/java/io/javalin/http/Context.kt#L251-L255)

My way to mock the method is like this, see entire test method below: 
`when(context.header("Authorization")).thenReturn(test1);`  

Because Mockito is choosing the method with return type `Validator` instead of the method with return type `String`, my tests throw an exception.

The exception that occur in my tests in a **random amount** of the test runs, i.e. **sometimes my test works and sometimes the wrong method is chosen**:
```
org.mockito.exceptions.misusing.WrongTypeOfReturnValue: 

String cannot be returned by header()
header() should return Validator
***
If you're unsure why you're getting above error read on.
Due to the nature of the syntax above problem might occur because:
1. This exception *might* occur in wrongly written multi-threaded tests.
   Please refer to Mockito FAQ on limitations of concurrency testing.
2. A spy is stubbed using when(spy.foo()).then() syntax. It is safer to stub spies - 
   - with doReturn|Throw() family of methods. More in javadocs for Mockito.spy() method.

    at my.package.stupidTest1(JavalinTest.java:28)
```
Can someone explain why Mockito is choosing different methods in each test run? As far as I know, `reified` Kotlin methods should be hidden for Java applications and thus Mockito is not working correctly in this manner? 

------------

There have been several people that reproduced this issue, please see https://github.com/tipsy/javalin/issues/979 

To reproduce:
1. Create a Java maven project with JDK compiler source/target value 1.8 in the maven `<properties>` element
```    
<maven.compiler.source>1.8</maven.compiler.source>
<maven.compiler.target>1.8</maven.compiler.target>
```
2. Add mockito dependency
```
<dependency>
  <groupId>org.mockito</groupId>
  <artifactId>mockito-core</artifactId>
  <version>3.2.0</version>
  <scope>test</scope>
</dependency>
```
3. Add Javalin dependency
```
<dependency>
  <groupId>io.javalin</groupId>
  <artifactId>javalin</artifactId>
  <version>3.8.0</version>
</dependency>
```
4. Create the file `resources/mockito-extensions/org.mockito.plugins.MockMaker` with content `mock-maker-inline` [so that final Kotlin classes can be mocked](https://github.com/mockito/mockito/wiki/What%27s-new-in-Mockito-2#mock-the-unmockable-opt-in-mocking-of-final-classesmethods)
5. Create a test class that contains only a single method
```
 @Test
  void stupidTest1() {
    Context context = mock(Context.class);

    String test1 = "hello123";
    when(context.header("Authorization")).thenReturn(test1);
  }
```
6. Run the test

**Comment by juv** [comment]
There is some more detailed information in the Javalin project issue, but it looks like this is a problem of Mockito: https://github.com/tipsy/javalin/issues/979

**Comment by juv** [comment]
I have run the tests with `-Dnet.bytebuddy.dump=` VM option.
Four files are being created:
```
Mode                LastWriteTime         Length Name
----                -------------         ------ ----
-a----       05.06.2020     13:51          32459 io.javalin.http.Context-original.1591357905226.class
-a----       05.06.2020     13:51          51869 io.javalin.http.Context.1591357905226.class
-a----       05.06.2020     13:51           1474 java.lang.Object-original.1591357904445.class
-a----       05.06.2020     13:51           2884 java.lang.Object.1591357904445.class
```
I've zipped them and attached them below. Hope this helps.

[mockito-net.bytebuddy.dump.zip](https://github.com/mockito/mockito/files/4735867/mockito-net.bytebuddy.dump.zip)

**Comment by ChristianSchwarz** [comment]
@juv For kotlin use mockk instead

**Comment by raphw** [comment]
So, the problem is that the `Context` class defines two methods named `header` that accept a `String` argument:

```java
public final <T> io.javalin.core.validation.Validator<T> header(java.lang.String);
public final java.lang.String header(java.lang.String);
```

In Java, this would be illegal due to the ambiguity. I assume that the type inference in Java infers `T` of `when` as `Object` which is why this compiles in the first place. It then chooses the version of `header` that returns `Validator` when the reflection API is used to query for a method `header` that takes `String` as an argument since that method is declared first. In this case, Kotlin breaks with the Java standard library's conventions. Since Mockito does not know about Kotlin and relies on the standard library, it ends up choosing the wrong method. 

You can try setting the type explicitly:

```java
Mockito.<String>when(context.header("Authorization")).thenReturn(test1);
```

Not sure if this works but it might give the compiler the right indication. Maybe we need to stop using `getDeclaredMethod` and rather iterate ourselves to make Mockito sensitive to this by also checking the return type and using `getDeclaredMethods` (I assume Mockk is doing this) but this would come at a cost of performance.

**Comment by juv** [comment]
@raphw unfortunately, setting the type explicitly with `Mockito.<String>when(context.header("Authorization")).thenReturn(test1);` did not help. The same exception is thrown:

```
org.mockito.exceptions.misusing.WrongTypeOfReturnValue: 
String cannot be returned by header()
header() should return Validator
```

**Comment by raphw** [comment]
I assume we would need to include the return type in the method location processor. In Java, the return type is not part of the unique signature. This is an incompatibility of Mockito with Kotlin, we would probably need a project like *mockito-scala* for Kotlin to address this.

**Comment by TimvdLippe** [comment]
For Kotlin projects, we now recommend `mockito-kotlin`: https://github.com/mockito/mockito-kotlin If you can still reproduce this issue, please open an issue over there and we can investigate further.
