### ISSUE TITLE
Stubbing Order and PotentialStubbingProblems

### ISSUE THREAD

**Issue by viktornordling** [mockito/mockito#1959]
Mockito version: 3.3.3

Hi,

I'm trying to get clarity on when `PotentialStubbingProblem`s are being reported and when they are not.

If we have the following test:

```
@Test
void stubOrderingAndPotentialStubbingProblems() {
    MyClass mock = mock(MyClass.class);
    when(mock.myMethod("hello")).thenReturn("hi");

    MyClassUnderTest myClassUnderTest = new MyClassUnderTest(mock);
    myClassUnderTest.myMethodUnderTest();
}
```

Where:

```
public class MyClassUnderTest {

    private MyClass myClass;

    public MyClassUnderTest(MyClass myClass) {
        this.myClass = myClass;
    }

    public void myMethodUnderTest() {
        myClass.myMethod("hello");
        myClass.myMethod("not hello");
    }
}
```

Then Mockito will _not_ report any `PotentialStubbingProblem`s. However, if we simply swap the order of the two calls in the `myMethodUnderTest` method, like so:

```
    public void myMethodUnderTest() {
        myClass.myMethod("not hello");
        myClass.myMethod("hello");
    }
```

Then Mockito _will_ report `PotentialStubbingProblem`s. I understand that this is probably related to https://github.com/mockito/mockito/pull/1539, but it does seem inconsistent that Mockito reports a "potential problem with my stubbing" in one of these cases and not in the other, when in fact the stubbing is equally correct or wrong in both cases.

Can you explain why this happens and can we perhaps make it more clear somewhere [around here](https://github.com/mockito/mockito/blob/885e69420baa2a382f4394b85dc84cb6fe17fff6/src/main/java/org/mockito/exceptions/misusing/PotentialStubbingProblem.java#L33)?

Thanks!

**Comment by TimvdLippe** [comment]
Yes this is working as intended per #1539. It is difficult to choose the correct behavior, but we think the current behavior is the most intuitive for users.
