### ISSUE TITLE
Stable version (1.10.19) and HEAD don't build on Android

### ISSUE THREAD

**Issue by fluentfuture** [mockito/mockito#196]
I'm trying to upgrade my company's mockito version to 1.10.19 and ran into Android build breakage, caused by asm class file versioning issue.

```
Warning: org.mockito.asm.util.CheckSignatureAdapter:
    can't find referenced class org.mockito.asm.signature.SignatureVisitor
```

I downloaded cglib-and-asm-1.0.jar and found that while there is org/mockito/asm/util/CheckSignatureAdapter.class in the jar, there isn't org/mockito/asm/signature pacakge.

The cglib-and-asm-1.0-sources.jar does have the missing .java files.

This currently blocks the Mockito upgrade.

**Comment by bric3** [comment]
This is a warning, I'm not familiar with mockito and android though. Anyway this _issue_ has been there for a long time I think.

**Comment by szczepiq** [comment]
We will address this but it's hard to estimate when. Contributions welcome.

**Comment by fluentfuture** [comment]
Our Android build considers any warning as a broken build so I can't upgrade.

Strictly, I would think Android doesn't need any of the ASM or CGLib stuff but apparently stripping them out of the jar doesn't build either.

**Comment by bric3** [comment]
> Our Android build considers any warning as a broken build so I can't upgrade.

OK. Is it standard ?

Also could you check with mockito 1.10.18 ? There's been a change (f789a3b820da4c9369c51f4f75c537243c3d4317) in the manifest entries for errors with OSGI issues. Could that be related?

Maybe stripping ASM/CGLIB **and** cleaning the manifest file could do the trick ?

**Comment by fluentfuture** [comment]
We are currently using 1.9.5. On Maven Central, it's the latest version that still had "org/mockito/asm/signature" package in the jar file.

The manifest change was made on Nov 25 2014, newer than 1.10.5.

Stripping out cglib and asm caused dangling reference in ClassImposterizer.class and other errors that I don't know if it's related to this. And I'd hope to avoid messing with the jar files any further. It appears that we already have code checked in that depend on mockito/internal classes that no longer exist. That means there are enough source compatiblity issues I need to solve in addition to the binary compatibility issue.

I don't work on Android projects so I can't tell for sure if stopping at warning is a standard build process. It's not a single project failing to build though. The error message suggests to use a -dontwarn flag so that sounds like a non-default option to me?

Warning: there were 4 unresolved references to classes or interfaces.
         You may need to add missing library jars or update their versions.
         If your code works fine without the missing classes, you can suppress
         the warnings with '-dontwarn' options.
         (http://proguard.sourceforge.net/manual/troubleshooting.html#unresolvedclass)
Error: Please correct the above warnings first.

By the way, I'm trying to upgrade Mockito for the entire Google codebase to use. The company policy is for all projects to always depend on a single version of any third party dependency. So while I don't know if it's standard, the impact is company wide.

**Comment by bric3** [comment]
OK, thanks for the explanation @fluentfuture.

I'd like to look into it, but I don't have much free time now. However if you have better options to contribute we will welcome them.

Note that I'm working on completely removing CGLIB and use Bytebuddy instead in version 2.0. The work is almost complete, but some work is needed on the delivery scripts.

**Comment by raphw** [comment]
Android has some extended validation that the standard Java platform does not consider a break. For example, Android does not allow for unresolveable dependencies. cglib imports only those parts of ASM that are actively used. However, some parts of cglib's ASM code references static dependencies that are never reached and can therefore never break the application. Android does not accept it.

I had a similar issue with Byte Buddy but since Byte Buddy officially supports Android, it does not longer break it.

**Comment by szczepiq** [comment]
Thanks guys for feedback!!!

@fluentfuture , 

1. What it the situation now? I can look into the discrepancy between jar and source jar but I want to make sure this is  still useful.
2. We're considering mockito 2.0 to require java 1.8 (e.g. minimum compatibility 1.8). Is this a problem for google / android?

Cheers!

**Comment by fluentfuture** [comment]
Hi,

Sorry for the lack of response.

Yes. I believe this would still be very useful (even though I have personally switched to the C++ side of things).

Google will pretty soon move to Java 8. So I don't think the requirement is a problem for us.

**Comment by szczepiq** [comment]
Does it mean that android goes java 8 too?

Thanks!

**Comment by fluentfuture** [comment]
Hi. Sorry I think I jumped to conclusion too early.

Android won't move to Java 8 as soon as I thought. 

But I just learned that we do have work-arounds planned so when the regular Java switches to Java 8, we can dance around the restriction and have Android builds use an older version.

In short, it's not a deal breaker but needs some workaround.

**Comment by raphw** [comment]
To be honest, I would recommend against upgrading to Java 8. Few people have adapted it yet and so far, it would only affect testability. Give it some more months, at least.

**Comment by szczepiq** [comment]
Ok, thanks for info!

**Comment by bric3** [comment]
@raphw I still would like to see mockito 2 be pure Java 8. Mockito 1.x already works well for previous JDK. And JDK8 pushes types that used on a regular basis, I feel that Mockito should support them in the API, and that's without speaking of the defender method or lambdas.

> A non-representative study executed by baeldung.com from May 2015 finds that 38% of their readers have adopted Java 8. Prior to that, a late 2014 study by Typsafe had claimed 27% Java 8 adoption among their users.

**Comment by raphw** [comment]
@bric3 You might just be right about this. Java 8 adoption is pretty high and I assume that it could pay off for supporing easy integration with Java 8 types. Also, tests can run on a JVM v8 without compiling artifacts to v7 or before.

**Comment by TimvdLippe** [comment]
@fluentfuture was this issue resolved and can we close it?

**Comment by fluentfuture** [comment]
No. I later found that I didn't have to upgrade Mockito for Android tests,
so it was moot.

**Comment by bric3** [comment]
@fluentfuture So Do you suggest that this issue can be closed ?
