### ISSUE TITLE
Documentation: `@Mock` on method parameters

### ISSUE THREAD

**Issue by jamietanna** [mockito/mockito#1960]
While writing [an article about using `@Mock` as a method parameter](https://www.jvt.me/posts/2020/06/27/mockito-mock-parameter/), I noticed that the [JavaDoc for Mockito](https://javadoc.io/doc/org.mockito/mockito-core/latest/org/mockito/Mockito.html#mock_annotation) doesn't mention the ability to use `@Mock` as a parameter to a test method.

How would be best to add that as a PR, given it's dependent on the test runner?

I was thinking something like:

```
 * <h3 id="9">9. <a class="meaningful_link" href="#mock_annotation" name="mock_annotation">Shorthand for mocks creation - <code>&#064;Mock</code> annotation</a></h3>
 *
 * <ul>
 * <li>Minimizes repetitive mock creation code.</li>
 * <li>Makes the test class more readable.</li>
 * <li>Makes the verification error easier to read because the <b>field name</b>
 * is used to identify the mock.</li>
 * </ul>
 *
 * <pre class="code"><code class="java">
 *   public class ArticleManagerTest {
 *
 *       &#064;Mock private ArticleCalculator calculator;
 *       &#064;Mock private ArticleDatabase database;
 *       &#064;Mock private UserProvider userProvider;
 *
 *       private ArticleManager manager;
 *
 *       @Test
 *       void testSomething(@Mock ArticleDatabase database) {
 * </code></pre>
```

**Comment by TimvdLippe** [comment]
We mention that information in https://javadoc.io/doc/org.mockito/mockito-junit-jupiter/latest/org/mockito/junit/jupiter/MockitoExtension.html as we don't support initiating Mocks on parameters with JUnit4. Therefore, we should add a parameter something like:

```java
 *       @Test
 *       void testSomething(@Mock ArticleDatabase canOnlyBeInstantiatedWithJUnit5) {
```

Other than that, please open a PR 😄

**Comment by jamietanna** [comment]
Oh I didn't realise that, thanks! I'll amend my article with that knowledge too.

Am I OK to add a PR for both the v2 and v3 documentation, given it works on both versions?

**Comment by TimvdLippe** [comment]
We no longer publish v2 updates, so v3 only.
