### ISSUE TITLE
how to handle anystring() with null mockito 3.0

### ISSUE THREAD

**Issue by singh039** [mockito/mockito#1964]
Since we are migrating from 1.10.19 to 3.0, a statement like: when(someClass.someMethod(anyString())).thenReturn("someValue");

Sometimes, anyString() returns null value and this statement was working fine with mockito 1.10.19 but with mockito 3.0, it is giving below error as:-

org.mockito.exceptions.misusing.InvalidUseOfMatchersException: Invalid use of argument matchers! 0 matchers expected, 1 recorded: -> at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallStatic(CallSiteArray.java:55)

This exception may occur if matchers are combined with raw values: //incorrect: someMethod(anyObject(), "raw String"); When using matchers, all arguments have to be provided by matchers. For example: //correct: someMethod(anyObject(), eq("String by matcher"));

Because Mockito 3.0 does not support for null value. Can anyone help me, how can I handle this situation.

Thanks

**Comment by TimvdLippe** [comment]
The exception you listed should not be affected by the change that `anyString()` no longer matches `null`. Could you please post a small reproduction case that we can analyze as to what is going on?

**Comment by TimvdLippe** [comment]
Closing per above comment.
