### ISSUE TITLE
Mockito treat FactoryBean`s wrong

### ISSUE THREAD

**Issue by D-Mikh** [mockito/mockito#1966]
- mockito-core 3.3.3. (spring-boot-starter-test 2.3.1)
- java version "1.8.0_241"

I faced a trouble not be able to mock mybatis mapper. Mybatis register it's beans as FactoryBean's.  When I started debugging I've noticed that when MockitoPostProcessor determine names of beans to be replaced in case of FactoryBeans mokito only examine OBJECT_TYPE_ATTRIBUTE attribute of bean which is not mandatory to implement as a result mocked bean just put beside original. Since mokito`s bean doesn't marked as primary so during component inicalization original bean just picked in order.

Here is a test project to reproduce: https://github.com/D-Mikh/demo

MockitoPostProcessor#getExistingBeans(ConfigurableListableBeanFactory, ResolvableType)

**Comment by TimvdLippe** [comment]
Could you explain what you mean with "wrong"? Reading this issue description, it is unclear what the observed and expected behavior is.

**Comment by D-Mikh** [comment]
Hi there! Expected behavior is mocked bean in Application Context:)

**Comment by TimvdLippe** [comment]
This is likely an issue in spring-boot instead. Please open an issue on their repository, or ask the question on a site like StackOverflow. From this description, this does not appear to be an issue with Mockito.

**Comment by D-Mikh** [comment]
MockitoPostProcessor try to determine whether factoryBean is appopriate by exmine "attributes" property of beanDefenition instead of metadata

**Comment by D-Mikh** [comment]
all regular beans mocked just fine

**Comment by D-Mikh** [comment]
it`s definitely a Mockito issue:(
