### ISSUE TITLE
Static method mocks incompatible with MockitoExtension (NotAMockException)

### ISSUE THREAD

**Issue by olada** [mockito/mockito#1967]
Hello,

I am experimenting with the newly released functionality of mocking static methods.
It appears that static mocks are not compatible with the `MockitoExtension` designed for JUnit 5.
Following error message is produced when using the extension:
```
org.mockito.exceptions.misusing.NotAMockException: Argument passed to Mockito.mockingDetails() should be a mock, but is an instance of class java.lang.Class!
```
Full Stacktrace: [static-mock-mockito-extension-stacktrace.txt](https://github.com/mockito/mockito/files/4908237/static-mock-mockito-extension-stacktrace.txt)

I have created following minimal example which is composed of a `Utils` class (containing the static method) and a `UtilsUser` class (calls the static Utils method). `UtilsUserTest` tests the functionality of the `UtilsUser` class.

```java
public class Utils {
    public static long millis() {
        return System.currentTimeMillis();
    }
}
```

```java
public class UtilsUser {
    public long use() {
        return Utils.millis();
    }
}
```

```java
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.InjectMocks;
import org.mockito.MockedStatic;
import org.mockito.Mockito;
import org.mockito.junit.jupiter.MockitoExtension;

import static org.junit.jupiter.api.Assertions.assertEquals;

@ExtendWith(MockitoExtension.class)
class UtilsUserTest {
    @InjectMocks
    private UtilsUser utilsUser;

    @Test
    void use() {
        try (MockedStatic<Utils> mockedUtils = Mockito.mockStatic(Utils.class)) {
            mockedUtils.when(Utils::millis).thenReturn(17L);
            assertEquals(17L, utilsUser.use());
        }
    }
}
```
When converting this test to a test which does not use the extension (removing `@ExtendWith`, removing `@InjectMocks`, adding `= new UtilsUser()` after the field declaration), the test passes.

Can you tell me if there is something special I have to accomodate for when using the static mocks in JUnit Jupiter?
Or is this indeed a bug (which you can hopefully reproduce)?

I am using mockito-inline and mockito-junit-jupiter in version 3.4.0.

Thanks in advance and thanks for the new static mocks functionality!
David

**Comment by raphw** [comment]
Thanks for reporting. We already found the error, it slipped us. I think we can have a release ready fairly soon.

**Comment by jglink** [comment]
Is this already released?
Because I have the same issue with the latest mockito version 3.5.13
Thanks

**Comment by kishan1301** [comment]
I used @ExtendWith(SpringExtension.class) instead of MockitoExtension.class and it worked.
Not sure if you're intended to test it with MockitoExtension itself.
