### ISSUE TITLE
Unable to use the mockito extension mechanism to mock on final classes for Java 13 and above

### ISSUE THREAD

**Issue by sima-zhu** [mockito/mockito#1969]
> Hey,
> 
> First thanks for reporting, in order to help us to classify issue can you make sure the following check boxes are checked ?
> 
> If this is about mockito usage, the better way is to reach out to
> 
>  - stackoverflow : http://stackoverflow.com/questions/tagged/mockito
>  - the mailing-list  : https://groups.google.com/forum/#!forum/mockito / mockito@googlegroups.com
>    (Note mailing-list is moderated to avoid spam)
>
> _This block can be removed_
> _Something wrong in the template fix it here `.github/ISSUE_TEMPLATE.md`

check that

 - [x] The mockito message in the stacktrace have useful information, but it didn't help
```
IndexBatchExceptionTests.setup:27 Mockito
Mockito cannot mock this class: cla...
```
 - [x] The problematic code (if that's possible) is copied here;
       Note that some configuration are impossible to mock via Mockito
```
// The final class to test
public final class IndexDocumentsResult {
}
```

```
// The test to mock class
public class IndexBatchExceptionTests {
    private IndexDocumentsResult result;
    @BeforeEach
    public void setup() {
        result = mock(IndexDocumentsResult.class);
    }
}
```

We use the way of putting single file `src/test/resources/mockito-extensions/org.mockito.plugins.MockMaker` to make it work **for Java 11**. However, the code does not work once we migrate to **Java 13**
 - [x] Provide versions (mockito / jdk / os / any other relevant information)
* Mockito-core: 3.0.0
* jdk: Zulu-14
* os: Windows
 
 - [x] Provide a [Short, Self Contained, Correct (Compilable), Example](http://sscce.org) of the issue
       (same as any question on stackoverflow.com)
**Expect to see the test passed.**
 - [x] Read the [contributing guide](https://github.com/mockito/mockito/blob/release/3.x/.github/CONTRIBUTING.md)

**Comment by sima-zhu** [comment]
The issue has been opened for a week. Anyone can take a look?

**Comment by sima-zhu** [comment]
Ping for response

**Comment by TimvdLippe** [comment]
Thanks for filing the issue. Could you please provide us a minimal reproduction case that we can clone/download to debug the issue? Thanks in advance!

**Comment by TimvdLippe** [comment]
Closing per the above comment.
