### ISSUE TITLE
Mockito.after() method accepts negative timeperiods and subsequent verifications always pass

### ISSUE THREAD

**Issue by Nedskib** [mockito/mockito#197]
e.g.

    Runnable runnable = Mockito.mock(Runnable.class);
    Mockito.verify(runnable, Mockito.never()).run(); // passes as expected
    Mockito.verify(runnable, Mockito.after(1000).never()).run(); // passes as expected
    Mockito.verify(runnable, Mockito.after(-1000).atLeastOnce()).run(); // passes incorrectly

**Comment by bric3** [comment]
Well spotted, thx

**Comment by lukasz-szewc** [comment]
I can try to fix that, but need to know what exactly is the issue here:
Should negative values is after throw immediate exception? or maybe negatives are allowed here (negative value means - immediately)?

**Comment by Nedskib** [comment]
I would vote for an IllegalArgumentException being thrown.

**Comment by lukasz-szewc** [comment]
The same is happening for *timeout* method:
e.g. 

```
       SomeClazz mock = Mockito.mock(SomeClazz.class);
       Mockito.verify(mock, timeout(-100)).someMethod(); //passes, which is incorrect
```

If method was invoked, then it passes, but this negative timeout is at least confusing:

```
        SomeClazz mock = Mockito.mock(SomeClazz.class);
        mock.someMethod();
        Mockito.verify(mock, timeout(-100)).someMethod(); //passes
```
