### ISSUE TITLE
Update FAQ for mocking static 

### ISSUE THREAD

**Issue by eraonel** [mockito/mockito#1976]
Since 3.4.0 there is support for mocking static.

Form: https://github.com/mockito/mockito/wiki/FAQ 

"Can I mock static methods?

No. Mockito prefers object orientation and dependency injection over static, procedural code that is hard to understand & change. If you deal with scary legacy code you can use JMockit or Powermock to mock static methods."

I guess it needs an update :-)

//mike

**Comment by TimvdLippe** [comment]
Updated thanks!
