### ISSUE TITLE
mockStatic throws StackOverflowError when mocking Arrays.

### ISSUE THREAD

**Issue by msteinbeck** [mockito/mockito#1979]
Hi,

I tried to mock `Arrays.sort` with your new `mockStatic` function:

```java
try (MockedStatic<Arrays> mock = mockStatic(Arrays.class)) {
    int[] ints = new int[] { 3, 2, 1 };
    mock.when(() -> Arrays.sort(ints)).thenReturn(ints);
}
```
but `mockStatic(Arrays.class)` throws:

`Exception: java.lang.StackOverflowError thrown from the UncaughtExceptionHandler in thread "main"`. I know that the documentation says: "We recommend against mocking static methods of classes in the standard library...". Yet, this behaviour is unexpected.

I included Mockito as follows:

```xml
<properties>
  <mockito.version>3.4.2</mockito.version>
</properties>
...
<dependency>
  <groupId>org.mockito</groupId>
  <artifactId>mockito-core</artifactId>
  <version>${mockito.version}</version>
  <scope>test</scope>
</dependency>
<dependency>
  <groupId>org.mockito</groupId>
  <artifactId>mockito-inline</artifactId>
  <version>${mockito.version}</version>
  <scope>test</scope>
</dependency>
<dependency>
  <groupId>org.mockito</groupId>
  <artifactId>mockito-junit-jupiter</artifactId>
  <version>${mockito.version}</version>
  <scope>test</scope>
</dependency>
```

**Comment by raphw** [comment]
The test case causes class loading where the class loader relies on `Arrays`.

I expect that we will run on a few common problems with system classes and I think for now we will just add them to a list of forbidden classes that throw an explicit exception.

On the long run, we might just instrument class loading to avoid the application of static (and construction) mocks during class loading. This can also be achieved using the stack walker without instrumentation once we drop Java 8 support.

**Comment by TimvdLippe** [comment]
I am closing this as wontfix, as we shouldn't support stubbing `Arrays.sort`. Any implementation of your stub will be wrong for user code, causing it to hide potential problems. Please use the standard `Arrays.sort` implementation instead.

**Comment by PoetAndPoem4Hu** [comment]
Hi, @raphw, can I translate your description as "not supported static mock system class" in mockito?

**Comment by raphw** [comment]
There's a lot of issues with these system classes. They are used in Mockito's code and many methods are intrinsified. Therefore, we recommend against it.
