### ISSUE TITLE
PowerMockito 2.0.7 broken when InjectingAnnotationEngine.injectMocks became private

### ISSUE THREAD

**Issue by Pr0methean** [mockito/mockito#1981]
PowerMockito 2.0.7 defines the class PowerMockitoInjectingAnnotationEngine which extends InjectingAnnotationEngine and calls its injectMocks method. Commit b3fc349e8e525e41f34ff04aca8c3140ff2b335a makes that method private and changes its return type, causing a NoSuchMethodError. A quick fix would be to make the method protected and, once that change is released, recompile PowerMockito against it; however, this may require users to upgrade both at the same time. As well, the returned AutoCloseable would never get closed; a quick-and-dirty fix would be to close it in finalize().

**Comment by Pr0methean** [comment]
See also https://github.com/powermock/powermock/issues/1055, in case it's decided to fix this on the PowerMock side.

**Comment by Pr0methean** [comment]
This is fixed by commit 12ba5936b736a2886220f9ae4a6492558dba4e14, which is in release 3.4.4.

**Comment by raphw** [comment]
I reverted the regression in the merge commit that added some error messages for system classes that should not be mocked statically.
