### ISSUE TITLE
README should refer the latest available documentation

### ISSUE THREAD

**Issue by valfirst** [mockito/mockito#1985]
**Actual:**
README contains link `latest documentation` 
http://javadoc.io/page/org.mockito/mockito-core/2/org/mockito/Mockito.html 
which redirects to 
https://javadoc.io/static/org.mockito/mockito-core/2.9.0/org/mockito/Mockito.html 
(Note: version is `2.9.0`)

**Expected:**
The link `latest documentation` should point to the latest available documentation 
http://javadoc.io/page/org.mockito/mockito-core/3/org/mockito/Mockito.html
which redirects to 
https://javadoc.io/static/org.mockito/mockito-core/3.4.4/org/mockito/Mockito.html 
at the current moment (Note: version is `3.4.4`).

**Comment by TimvdLippe** [comment]
Feel free to open a PR :)
