### ISSUE TITLE
MockitoExtension cannot be used with JUnit 5 in OSGi integration tests

### ISSUE THREAD

**Issue by wborn** [mockito/mockito#1997]
The Mockito junit-jupiter JAR is missing OSGi bundle manifest entries so it cannot be used in OSGi integration tests.

We run some OSGi integration tests (using bnd) that have `@Mock`s so it would be easier if these mocks can be initialized by annotating classes with `@MockitoExtension` instead of using `MockitoAnnotations.openMocks(this)`, see for example this [FirmwareUpdateServiceTest](https://github.com/openhab/openhab-core/blob/43cb68c9d753faf3a88cfd19c4fc015c8289f880/itests/org.openhab.core.thing.tests/src/main/java/org/openhab/core/thing/internal/firmware/FirmwareUpdateServiceTest.java).

What may complicate adding the manifest entries is that `MockitoExtension` is [importing](https://github.com/mockito/mockito/blob/b87fad310bf59b94035028dc478089ded2a9198a/subprojects/junit-jupiter/src/main/java/org/mockito/junit/jupiter/MockitoExtension.java#L27-L29) internal classes which [aren't exported](https://github.com/mockito/mockito/blob/b87fad310bf59b94035028dc478089ded2a9198a/gradle/mockito-core/osgi.gradle#L19) by the mockito-core bundle. What may help is to make junit-jupiter a bundle fragment with mockito-core as host.

**Comment by kriegfrj** [comment]
Fragments can be a bit of a pain.

@rotty3000 could offer some advice here - he did the OSGi metadata port for the JUnit 5 project itself. They had a similar problem, in that some of the bundles relied on internal packages of other bundles. I think that they ended up exporting the "internal" packages, but flagged them with an attribute to mark them as "internal use only".

**Comment by timothyjward** [comment]
I would also like to see a solution to this issue. Making the mockito-junit-jupiter jar into a fragment which exports the `MockitoExtension` package and attaches to mockito-core does sound like a good plan.

**Comment by rotty3000** [comment]
I've got a set of changes that makes mockito-junit-jupiter work in OSGi using the same strategy that junit5 used to identify "friend" packages that are exported but not intended for public use outside of _mockito_.

@raphw do you think your team would be interested?

**Comment by raphw** [comment]
Looks good to me, I had a look at the build and I know too little about OSGi to understand the effect the API guardian dependencies have but since the classes only carry annotations and the dependency is not required, I do not see any chance of a regression.

@TimvdLippe - could you have a second look, you know the build better then me. To me it looks like a good merge.

**Comment by rotty3000** [comment]
For your edification:
a) apiguardian does not bring with it any runtime dependencies (confirmed by the OSGi metadata)
b) the interaction between [API guardian and bnd is explained here](https://bnd.bndtools.org/instructions/export-apiguardian.html)
c) the build adds a `verifyOSGi` gradle task glued onto `check` to make sure that future changes do not break the relationship required between mockito-core and mockito-junit-jupiter such that they continue working together in OSGi

**Comment by wborn** [comment]
Today I tried a recent version of Mockito 5 with OSGi but it doesn't work anymore, see also #2708. :disappointed: 
Perhaps some of the commenters here can help with fixing it?

**Comment by TimvdLippe** [comment]
@wborn Unfortunately I don't have a lot of experience with OSGi, but would be happy to review a PR that fixes it (with an included regression test). Apologies for the breakage!

**Comment by raphw** [comment]
I think there needs to be some form of import of the boot loader package that we add. Not sure if such an import is considered in OSGi, but I'd need a reproduction to look into it.
