### ISSUE TITLE
how to mock a static method with parameters and void return type?

### ISSUE THREAD

**Issue by dgqypl** [mockito/mockito#2027]
public static void method(String param1,String param2){...}

I want to know how to use mockito 3.5.5 to mock the said situation? Can anyone help?

> the [Online Documentation](https://javadoc.io/doc/org.mockito/mockito-core/latest/org/mockito/Mockito.html#48) just show how to mock static method with no parameter and string return type.

**Comment by raphw** [comment]
Use mockStatic and then specify the mock in the returned instance.

**Comment by dgqypl** [comment]
> Use mockStatic and then specify the mock in the returned instance.

can you show me a code snippet?thx

**Comment by dgqypl** [comment]
> Use mockStatic and then specify the mock in the returned instance.

I use below code can work,but not sure it is correct:

MockedStatic aUtilMock = mockStatic(AUtil.class);
aUtilMock.when(()->AUtil.staticMethod(...)).then(invocationOnMock -> null);

**Comment by raphw** [comment]
You should use the mock static within a try with resources block.

You can find more info in Mockito's readme.

**Comment by dgqypl** [comment]
> You should use the mock static within a try with resources block.
> 
> You can find more info in Mockito's readme.

try (MockedStatic mocked = mockStatic(Foo.class)) {
 mocked.when(Foo::method).thenReturn("bar");
 assertEquals("bar", Foo.method());
 mocked.verify(Foo::method);
 }

the above is mock static method with string return type? my question is how to mock static with **void return type**, not the **try with resources block** , of course i know that it should in a try with resources block, but that's not my question.

**Comment by fqyuan** [comment]
> > You should use the mock static within a try with resources block.
> > You can find more info in Mockito's readme.
> 
> try (MockedStatic mocked = mockStatic(Foo.class)) {
> mocked.when(Foo::method).thenReturn("bar");
> assertEquals("bar", Foo.method());
> mocked.verify(Foo::method);
> }
> 
> the above is mock static method with string return type. my question is how to mock static with **void return type**, not the **try with resources block** , of course i know that it should in a try with resources block, but that's not my question.

> Same question with you, the documention seems to provide no link of static void method.

**Comment by TimvdLippe** [comment]
If I understand the requests correctly, https://javadoc.io/doc/org.mockito/mockito-core/latest/org/mockito/MockedStatic.html is in need of a `doReturn` method, analogous to https://javadoc.io/doc/org.mockito/mockito-core/latest/org/mockito/Mockito.html#doReturn-java.lang.Object-

**Comment by dgqypl** [comment]
> If I understand the requests correctly, https://javadoc.io/doc/org.mockito/mockito-core/latest/org/mockito/MockedStatic.html is in need of a `doReturn` method, analogous to https://javadoc.io/doc/org.mockito/mockito-core/latest/org/mockito/Mockito.html#doReturn-java.lang.Object-

So, how to write?

**Comment by TimvdLippe** [comment]
You can't write these yet, as it requires an update to Mockito. I would welcome a PR that adds the required API changes to `MockedStatic` to make that work (assuming that we don't require additional bytecode generators)

**Comment by dgqypl** [comment]
> You can't write these yet, as it requires an update to Mockito. I would welcome a PR that adds the required API changes to `MockedStatic` to make that work (assuming that we don't require additional bytecode generators)

Thank you very much!

**Comment by Cybermite** [comment]
I think the method would be doNothing() since doReturn(Object) requires a return type. If you're not partially mocking the class, then you should be able to just do verify calls to validate the arguments. I'm not seeing a reason why you'd need to set that up (using "when") _prior_ to calling the method-under-test, but might just be my lack of understanding.

@dgqypl @fqyuan

Does this work for you:

```java
@Test
public void test1()
{
    try (MockedStatic<Fake> mockedStatic = mockStatic(Fake.class))
    {
        Fake.doOps("op1", "op2");
        mockedStatic.verify(() -> Fake.doOps("op1", "op2")); // passes
        // mockedStatic.verify(() -> Fake.doOps("op1", "op3")); // fails
        // mockedStatic.verify(() -> Fake.doOps("op2", "op2")); // fails
        // mockedStatic.verify(() -> Fake.doOps("op2", "op3")); // fails

        // verify multiple times
        Fake.doOps("op2", "op3");
        Fake.doOps("op2", "op3");
        mockedStatic.verify(times(2), () -> Fake.doOps("op2", "op3"));
    }
}

public static class Fake
{
    public static void doOps(String op1, String op2)
    {
    }
}
```

**Comment by marcello-dev** [comment]
> If I understand the requests correctly, https://javadoc.io/doc/org.mockito/mockito-core/latest/org/mockito/MockedStatic.html is in need of a `doReturn` method, analogous to https://javadoc.io/doc/org.mockito/mockito-core/latest/org/mockito/Mockito.html#doReturn-java.lang.Object-

I want to link this issue and this reply to a StackOverflow [question](https://stackoverflow.com/a/63841319/8484783) that has faced the same issue. The question is "How to mock just one static method in a class using Mockito?".

**Comment by rimuln** [comment]
This works for me with Mockito 3.5.13
`    try (MockedStatic<Hibernate> mockedHibernate = mockStatic(Hibernate.class)) {
      mockedHibernate.when(() -> Hibernate.initialize(any())).then(invocation -> null);
      for (Object collection : collections) {
        Hibernate.initialize(collection);
      }
      mockedHibernate.verify(times(collections.length), () -> Hibernate.initialize(any()));
    }`

**Comment by kenzhaoyihui** [comment]
> This works for me with Mockito 3.5.13
> 
> ```java
>     try (MockedStatic<Hibernate> mockedHibernate = mockStatic(Hibernate.class)) {
>       //seems that next line not needed
>      //mockedHibernate.when(() -> Hibernate.initialize(any())).then(invocation -> null);
>       for (Object collection : collections) {
>         Hibernate.initialize(collection);
>       }
>       mockedHibernate.verify(times(collections.length), () -> Hibernate.initialize(any()));
>     }`
> ```

cannot works for me with mockito version 4.6.0

**Comment by JumBe08** [comment]
I ended up in this Issue, looking for an answer to the same question. Somehow, it was slipping past me at first read (Shouldn't this issue be closed? @TimvdLippe ), but @Cybermite and @gliptak  suggestions did work for me, @dgqypl @fqyuan . 

When I mocked the class which had the static method in my case, and tried to call said method, it did nothing like I needed. It ignored the static method's logic and kept running the test. 

Also worth mentioning, that in Cyber's example, the static method is directly called in the Try-With-Resources block, but it didn't had to. In my test, I was testing "ObjectA.methodA". This method is calling a static method from another class (e.g. "ClassB.StaticMethod") midway and it still worked, the method was executed but its logic ignored and the test kept going.

**Comment by TimvdLippe** [comment]
Closing per the above comments, thanks!

**Comment by Demonian** [comment]
@TimvdLippe I believe the issue should still be opened. We should consider cases when it is needed to test doThrow() execution from static void method. which seems not be possible right now. E.g. This will not work
```
try (MockedStatic<TestStatic> mockedTest= mockStatic(TestStatic.class)) {
      mockedTest.when(() -> TestStatic.methodA()).thenThrow(new TestException())
      TestService testService = new TestService();
      // testService.methodB() will call TestStatic.methodA() in try/catch block and will remap
      // the initial TestException to RemappedTestException
      assertThrows(RemappedTestException.class, testService.methodB());
    }
```

Right now this test will just fail because exception will not be thrown from static mock. Any suggestions?
