### ISSUE TITLE
Mockito issue with "org.checkerframework" library on Java 8

### ISSUE THREAD

**Issue by pangivan** [mockito/mockito#2029]
Dear developer:

Version: 2.24
Java: 1.8.0_265
OS: Windows 10

Hi, I was using Mockito for the project and somehow we need to use java 1.8 instead of 9+, it triggers new issue when we include org.checkerframework (checker) library as part of the project.

Here's the details

In Attacher.class:

line:53 ->        
 `Object virtualMachineInstance = virtualMachineType.getMethod("attach", String.class).invoke(STATIC_MEMBER, processId);`

When getMethod executes, the className is set to checker framework and instead of null. Therefore, it will cause this line not able to invoke the method properly. Hence, the jar will not create.

**Comment by TimvdLippe** [comment]
Thanks for filing the issue. Could you please provide us a minimal reproduction case that we can clone/download to debug the issue? Thanks in advance!

**Comment by TimvdLippe** [comment]
Closing per the above comment.
