### ISSUE TITLE
Introduce BDD InOrder verification

### ISSUE THREAD

**Issue by mkordas** [mockito/mockito#203]
Follow-up to the [discussion](https://groups.google.com/forum/#!topic/mockito/wr1As1fg_-U).

[BDDMockito](http://site.mockito.org/mockito/docs/current/org/mockito/BDDMockito.html) is great, but right now it doesn't support InOrder verification. Here is my proposition:

##### Initialization and invocations:
```java
List firstMock = mock(List.class);
List secondMock = mock(List.class);
 
firstMock.add("was called first");
secondMock.add("was called second");
secondMock.add("was called second");

InOrder inOrder = inOrder(firstMock, secondMock);
```

##### Current non-BDD solution:
```java
inOrder.verify(firstMock).add("was called first");
inOrder.verify(secondMock).add("was called second");
```

##### Proposition 1:
```java
inOrder.then(firstMock).should().add("was called first");
inOrder.then(secondMock).should(times(2)).add("was called second");
```

##### Proposition 2:
```java
then(firstMock).should(inOrder).add("was called first");
then(secondMock).should(inOrder, times(2)).add("was called second");
```

I'm open to other propositions. What do you think? 
I can proceed with PR as soon as we will agree on API.

**Comment by bric3** [comment]
It seems like a nice idea, let's introduce ordered BDD. I'd favor proposition 2, it reads better imho.

Since we are in a beta phase, we can try and see if the API works with this proposition. Also it should probably be easier to implement.

**Comment by bric3** [comment]
Also sorry for this late reply

**Comment by mkordas** [comment]
@bric3, I've implemented the second proposition. I also like it more and implementation was really easy - please see #222.
