### ISSUE TITLE
Please slow down releases to central

### ISSUE THREAD

**Issue by hazendaz** [mockito/mockito#2036]
This was an issue with mockito a few years back.  It seems now mockito team is again releasing to central nearly every update.  This is overwhelming projects such as MyBatis that use dependabot with excessive updates.  While we could block patch updates from mockito, it would be preferable that we don't have to.  Can Mockito team go back to bundling releases and releasing on less frequency?  I don't think every last change needs to be in central.  I've yet to see any benfit or fix that even affects our usage in this release style.  I am aware many nodejs libraries do this but on java side there are practically no repos I'm aware of with this heavy of a release frequency.

For MyBatis we use mockito in around 20 modules or more.  So we get alerted in all of them at once.  Further due to a separate bug with dependabot, my forks get doubled up.  It's inconvenient in general.

**Comment by TimvdLippe** [comment]
We have had several issues with Maven Central, including several issues in the last minor release that warranted multiple patch releases. We don't expect this cadence to continue for future releases.

**Comment by hazendaz** [comment]
@TimvdLippe Thank you!  That helps understand what is going on.  Hopefully this ticket will help others seeing this as well.  Appreciate your quick response.

**Comment by raphw** [comment]
That sounds like the use of dependabot is the problem, if you ask me. Maybe just run it once a week from a cron?

Mockito has a large user base and introducing a new feature is often uncovering obscure regressions that we try to fix as quickly as possible, otherwise the number of reported issues can quickly overwhelm us. A row of short-paced update releases

**Comment by hazendaz** [comment]
Correct, I have also followed up with them as well.  It's the load in general that I'm being hit with where I end up with somewhere around 60 emails from mybatis repos and my forks along with other projects usage.  This was good enough for me here to understand the release speed.  I just recalled when mockito was changed few years back to more quickly release to central and thought that was becoming the norm.  Appreciate your response.  Thanks.

**Comment by asolntsev** [comment]
I love Mockito and happy to see any new release. 

@hazendaz You probably need to setup Dependabot somehow. Or you don't need at all. Or you should refactor dependencies declaration so that Mockito (and other common dependencies) would be declared in one place, not in all 30 modules.
