### ISSUE TITLE
Getting nullpointer exception when mocking method with BiFunction and Consumer Generic methods in Java 8

### ISSUE THREAD

**Issue by d-saravanan** [mockito/mockito#2037]
I have below method in my code in a Helper class which is generic so that I can process and return back any type of data using the responseHandler

```
 public <T> T doHttpPost(String url, String data, BiFunction<String, Integer, T> responseHandler, Consumer<Exception> exceptionHandler) {
...
}
```
The above method is used as below

`return APIClient.doHttpPost(url, EmptyString, null, null);`

During writing my unit test methods, I am using the mock which is setup as below,

```
doAnswer(ans -> true).when(apiClient).doHttpPost(anyString(), anyString(), any(BiFunction.class), any(Consumer.class));
doAnswer(ans -> true).when(apiClient).doHttpPost(anyString(), any(HttpEntity.class), any(BiFunction.class), any(Consumer.class));

```

However, the null pointer exception still occurred, hence I tried to change the above as below in the mock setup and still getting the null pointer exception

```
when(apiClient.doHttpPost(anyString(), anyString(), any(BiFunction.class), any(Consumer.class))).thenReturn(true);
when(apiClient.doHttpPost(anyString(), any(HttpEntity.class), any(BiFunction.class), any(Consumer.class))).thenReturn(true);
```
The mock setup for other regular methods are working fine, they have no generic implementations.
When I checked the method call in the watch window in IntelliJ IDE, i found that the method returns null instead of true which is configured in the mock. If there is a way to find why these 2 methods in the mock are not setup correctly, it will be easy for fixing.

I also tried to setup the mock to take any argument (though this is invalid because the above mocks will still accept null, but checking if there is any option requiring to write the mock like this

`doAnswer(ans -> true).when(apiClient).doHttpPost(anyString(), anyString(), any(), any());`

when using the below invocation methods,
`
return jenkinsAPIClient.doHttpPost(url, EmptyString, null, null);`
The test fails with the below error
```

Argument(s) are different! Wanted:
APIClient#0 bean.doHttpPost(
    <any string>,
    <any string>,
    <any java.util.function.BiFunction>,
    <any java.util.function.Consumer>
);
testcasename(ServiceTests.java:435)
Actual invocations have different arguments:
APIClient#0 bean.doHttpPost(
    "nulljob/CL217R/job/One/doRename?newName=aYbf8y8FRirlgXQoz7ySNhQqNp870xY0tZ9O6sSSBlbfgktoM7zb3UNdMNbKMQM9amMLio9KMzLtoOmnuj9z0wvA72h1L8oSGbLVqQQbmso4PTXMhFMfc14we03",
    "",
    null,
    null
);
```
In case, I use the below method call,

`return jenkinsAPIClient.doHttpPost(url, EmptyString, jenkinsAPIClient.successStatusCheck, jenkinsAPIClient.GenericExceptionHandler);`
The test case fails with the below error
```

Argument(s) are different! Wanted:
APIClient#0 bean.doHttpPost(
    <any string>,
    <any string>,
    <any java.util.function.BiFunction>,
    <any java.util.function.Consumer>
);
testcasename(ServiceTests.java:435)
```
Actual invocations have different arguments:
```
APIClient#0 bean.doHttpPost(
    "nulljob/CL217R/job/One/doRename?newName=aYbf8y8FRirlgXQoz7ySNhQqNp870xY0tZ9O6sSSBlbfgktoM7zb3UNdMNbKMQM9amMLio9KMzLtoOmnuj9z0wvA72h1L8oSGbLVqQQbmso4PTXMhFMfc14we03",
    "",
    null,
    APIClient$$Lambda$128/2000563893@360bc645
);

```

I assume that this model of implementation will be supported but I guess that I am missing some minor change which is breaking my tests and taking more days to figure out.

**Comment by TimvdLippe** [comment]
Thanks for filing the issue. Could you please provide us a minimal reproduction case that we can clone/download to debug the issue? Thanks in advance!

**Comment by TimvdLippe** [comment]
Closing per the above comment.
