### ISSUE TITLE
InlineByteBuddyMockMaker doesn't mock parent's methods

### ISSUE THREAD

**Issue by NikolayKul** [mockito/mockito#2044]
Hello there!
It looks like `org.mockito.internal.creation.bytebuddy.InlineByteBuddyMockMaker` doesn't mock parent's methods if the parent is written in Java. Can be reproduced in 3 steps:
1. Create 2 classes:
```
// java
public class Parent {
    public CharSequence getName() {
        return "parent name";
    }
}

// kotlin
class Child : Parent() {
    val name : String = "child name"
}
```
2. Enable `mock-maker-inline`.
3. Test classes as follows:
```kotlin
@Test
fun `check child name`() {
    val mocked = Mockito.mock(Child::class.java)
    Mockito.`when`(mocked.name).thenReturn("mocked name")

    // ok
    assertEquals("mocked name", mocked.name)

    // fails because "(mocked as Parent).name" returns "parent name"
    assertEquals("mocked name", (mocked as Parent).name)
}
```

Interesting details:
1. The test passes if I convert `Parent` from Java to Kotlin though on the byte code level they call the same getter function:
```
INVOKEVIRTUAL com/.../Parent.getName ()Ljava/lang/CharSequence
```
2. The test doesn't pass if I use "open" modifier for `Child`.
3. The test passes if I use "open" modifier for `Child` and disable `mock-maker-inline`.

Environment:
- Mockito version is '3.5.9'
- Kotlin version is '1.3.70'

**Comment by raphw** [comment]
I am wondering if Kotlin does something strange and keeps a side object for the parent cast. This sort of breaks Mockitos housekeeping of what is a mock and what not. Is (mocked as Parent) not identical to mocked?

**Comment by TimvdLippe** [comment]
For Kotlin, please use `mockito-kotlin`: https://github.com/mockito/mockito-kotlin If you can still reproduce this issue, please open an issue over there and we can further investigate. Thanks!
