### ISSUE TITLE
java.lang.AbstractMethodError in 2.21.0 ++ version

### ISSUE THREAD

**Issue by ryanrvldo** [mockito/mockito#2059]
I'm using mockito 3.3.3 in android (kotlin) to test my fragment. I'm mock my navController with mockito. But get something error with logcat that I've been posted below. But, when I'm using mockito 2.21.0 below my test passed. I dont know what is wrong with 2.21.0 ++ version.
```java
java.lang.AbstractMethodError: abstract method "java.util.List org.mockito.invocation.Invocation.getArgumentsAsMatchers()"
at org.mockito.internal.invocation.InvocationMatcher.<init>(InvocationMatcher.java:38)
at org.mockito.internal.invocation.MatchersBinder.bindMatchers(MatchersBinder.java:30)
at org.mockito.internal.handler.MockHandlerImpl.handle(MockHandlerImpl.java:59)
at org.mockito.internal.handler.NullResultGuardian.handle(NullResultGuardian.java:29)
at org.mockito.internal.handler.InvocationNotifierHandler.handle(InvocationNotifierHandler.java:33)
at com.android.dx.mockito.InvocationHandlerAdapter.invoke(InvocationHandlerAdapter.java:58)
```

**Comment by cmoiccool** [comment]
Same issue here while following this codelab : https://codelabs.developers.google.com/codelabs/advanced-android-kotlin-training-testing-test-doubles/#10
The issue can be reproduced following the codelab only changing the versions to the last versions, including Mockito to version 3.3.3 i have received the same error which was solved when changing mockito version to 2.21.0.
In my case the versions used in the Project Gradle file were:
```
// Define versions in a single place
ext {
    // Sdk and tools
    // Support library and architecture components support minSdk 14 and above.
    minSdkVersion = 14
    targetSdkVersion = 28
    compileSdkVersion = 28

    // App dependencies
    androidXVersion = '1.0.0'
    androidXTestCoreVersion = '1.3.0'
    androidXTestExtKotlinRunnerVersion = '1.1.2'
    androidXTestRulesVersion = '1.2.0-beta01'
    androidXAnnotations = '1.0.1'
    androidXLegacySupport = '1.0.0'
    appCompatVersion = '1.2.0'
    archLifecycleVersion = '2.2.0'
    archTestingVersion = '2.1.0'
    cardVersion = '1.0.0'
    coroutinesVersion = '1.3.2'
    dexMakerVersion = '2.12.1'
    espressoVersion = '3.3.0'
    fragmentVersion = '1.2.5'
    fragmentKtxVersion = '1.2.5'
    hamcrestVersion = '1.3'
    junitVersion = '4.13'
    materialVersion = '1.2.1'
    mockitoVersion = '3.3.3'
    recyclerViewVersion = '1.1.0'
    robolectricVersion = '4.3.1'
    roomVersion = '2.2.5'
    rulesVersion = '1.0.1'
    timberVersion = '4.7.1'
    truthVersion = '0.44'
}
```

**Comment by rachmanabdau** [comment]
I got this error in version 3.6.0 but it works fine in version 2.8.9 while using codelab testing from udacity.

**Comment by ELTEGANI** [comment]
> I got this error in version 3.6.0 but it works fine in version 2.8.9 while using codelab testing from udacity/google.

yes it works will in 2.8.9 version

**Comment by pitoszud** [comment]
The same error with org.mockito:mockito-core:3.3.1

Stepping into, I noticed the following errors:
Method threw 'java.lang.AbstractMethodError' exception. Cannot evaluate android.util.SparseArray.toString()
then
Method threw 'java.lang.AbstractMethodError' exception. Cannot evaluate androidx.navigation.NavController_1_Proxy.toString()

Downgrading to org.mockito:mockito-core:2.19.0 fixes the issue
