### ISSUE TITLE
Is it possible to give mock objects a name, then inject them by using the names?

### ISSUE THREAD

**Issue by zxa4fd** [mockito/mockito#2062]
For instance if I have:

```
public class MockitoTest {

    @Mock(name = "b2")
    private B b2;

    @Mock(name = "b3")
    private B b3;

}
```
and

```
public class ToInjectTo {
    B property
}
```

how do I specify if I want to use 'b2' or 'b3'?

**Comment by mockitoguy** [comment]
Based on my understanding of your use case, here're your options:

- use consistent naming. InjectMocks respects the mock name and tries to match by name (see the docs for InjectMocks)
- don't use InjectMocks - create the object under test explicitly. It's usually a one-liner so shouldn't impact the clarity of tests.

Hope that helps!

**Comment by zxa4fd** [comment]
Thanks!
