### ISSUE TITLE
(documentation) Semantic Versioning Page out of date

### ISSUE THREAD

**Issue by jplaisted** [mockito/mockito#2063]
The [semantic versioning documentation for mockito](https://github.com/mockito/mockito/wiki/Semantic-Versioning) seems out of date. It mentions a master branch, when there is no master branch :)

> Beta indicates that the version is directly generated from the master branch of the git repository.

This document is linked directly from the repo's main README.

 - [ ] The mockito message in the stacktrace have useful information, but it didn't help
 - [ ] The problematic code (if that's possible) is copied here;
       Note that some configuration are impossible to mock via Mockito
 - [ ] Provide versions (mockito / jdk / os / any other relevant information)
 - [ ] Provide a [Short, Self Contained, Correct (Compilable), Example](http://sscce.org) of the issue
       (same as any question on stackoverflow.com)
 - [x] Read the [contributing guide](https://github.com/mockito/mockito/blob/release/3.x/.github/CONTRIBUTING.md)

**Comment by TimvdLippe** [comment]
Fixed. Thanks for reporting.
