### ISSUE TITLE
Mockito fails an otherwise correct(?) test under certain conditions

### ISSUE THREAD

**Issue by loosebazooka** [mockito/mockito#2067]
- [x] The mockito message in the stacktrace have useful information, but it didn't help
 - [x] The problematic code (if that's possible) is copied here;
         https://github.com/loosebazooka/mockito-failure/tree/master
 - [x] Provide versions (mockito / jdk / os / any other relevant information):
         JVM:          1.8.0_242 (AdoptOpenJDK 25.242-b08)
         OS:           Linux/amd64
         Gradle:  6.1.1
 - [x] Provide a [Short, Self Contained, Correct (Compilable), Example](http://sscce.org) of the issue
         https://github.com/loosebazooka/mockito-failure/tree/master
 - [x] Read the [contributing guide](https://github.com/mockito/mockito/blob/release/3.x/.github/CONTRIBUTING.md)

I have a working test that works when run alone. If the test is run with other tests in the test class it fails. Just one other Mockito.verify causes the test failure. The details are in the example provided: https://github.com/loosebazooka/mockito-failure/tree/master

**Comment by TimvdLippe** [comment]
I think you are running into the thread-safety issue as documented at https://github.com/mockito/mockito/wiki/FAQ#is-mockito-thread-safe

**Comment by loosebazooka** [comment]
Oh so it's a timing thing then, the mock method is being called on another thread and then we verify before it happens?

**Comment by TimvdLippe** [comment]
Yes that's what I think is going on here. You would need to make sure you wait the scheduled task has finished before you run the verification.

**Comment by loosebazooka** [comment]
Yeah that makes sense. I think we can close this.
