### ISSUE TITLE
Issue with Bundle-Version manifest header when used in Eclipse PDE development

### ISSUE THREAD

**Issue by joeshannon** [mockito/mockito#2083]
The MANIFEST.MF currently contains e.g.: `Bundle-version: 3.6.0`

Due to the lowercase 'v' this appears to not be properly recognised by Eclipse PDE so is giving me errors on min versioned require bundle directives.

The standard headers at  https://www.osgi.org/bundle-headers-reference/ define it as `Bundle-Version` (capital V).

After a small amount of research it looks like OSGi specification possibly does accept case insensitive headers but haven't found definitive source.

In any case, changing it would keep it consistant with the other headers.

**Comment by TimvdLippe** [comment]
Seems like we hit this issue after we fixed an initial typo in #2070. Do you mind sending a PR to change it to a capital V?

**Comment by joeshannon** [comment]
Done, thanks for quick response!
