### ISSUE TITLE
ClassCastException with mockito when upgrading from JDK8 to JDK12

### ISSUE THREAD

**Issue by usherfu** [mockito/mockito#2086]
Hey,

First of all thanks for the great work.

With following example test case, we are facing an CCE issue when running with JDK12, however with JDK8 there is no problem

```
public class CopyHelperTest {

    public class CopyHelper<T extends Map<String, Object>> {
            public T copy() {
                T deepCopy = (T) new HashMap<String, Object>();
                return deepCopy;
        }
    }

    public interface MeasurementConcepts extends Map<String, Object> {

    }

    private MeasurementConcepts copiedConceptMock = mock(MeasurementConcepts.class);
    private CopyHelper<MeasurementConcepts> copyHelper = mock(CopyHelper.class);
    
    @Test
    public void copyHelperTest_checkcast(){
        when(copyHelper.copy()).thenReturn(copiedConceptMock);
    }
  
}
```

```
1) copyHelperTest_checkcast(CopyHelperTest)
java.lang.ClassCastException: class java.util.HashMap cannot be cast to class CopyHelperTest$MeasurementConcepts (java.util.HashMap is in module java.base of loader 'bootstrap'; CopyHelperTest$MeasurementConcepts is in unnamed module of loader 'app')
	at CopyHelperTest.copyHelperTest_checkcast(CopyHelperTest.java:33)
```

I understood from previously reported issue #357, that it is due to the bug fix since Java9.   I am trying to follow the discussion (https://github.com/mockito/mockito/pull/1612 and https://github.com/google/error-prone/issues/1616), and a few workarounds posted, i.e. https://github.com/spring-projects/spring-data-jdbc/commit/d91344751d35d6e0d9534f26f3c52b9e254c8773.  However, since there are a few different cases as mentioned https://github.com/mockito/mockito/issues/357#issuecomment-236135414, I am not sure if my particular situation is fixable, or simply because of incomplete understanding of the issue.

Hence the question:
1. Is the case posted supported by Mockito using Java 12?
2. Am I heading to the right direction with https://github.com/spring-projects/spring-data-jdbc/commit/d91344751d35d6e0d9534f26f3c52b9e254c8773? Or any pointer or example code snippet is appreciated.   

Thank you!

Environment :
Java 8: openjdk version "1.8.0_265"

Java 12: java version "12.0.1" 2019-04-16
junit-4.13.1
both mockito-all-2.0.2-beta and mockito 3.6.0

**Comment by TimvdLippe** [comment]
No this is not supported, as you are returning a `HashMap` while in the stub you are returning a different subclass of `Map` that isn't `HashMap`. The behavior has indeed changed in JDK9 and is not something Mockito can do anything about 😢
