### ISSUE TITLE
Mockito fails (bytebuddy is to blame most probably) with "Could not create type"

### ISSUE THREAD

**Issue by wind57** [mockito/mockito#2090]
This is the sample you can run on your own to see how to re-produce: https://github.com/wind57/mockito-bug-sandbox

It's definitely something with bytebuddy here, because the sample above works in two cases:

if I disable:

```
    //.sslContext(contextTwo())
   ...
   //.sslContext(contextOne())

```

in `Provider.java`

_or_ if I entire remove:

```
//private static final Sandbox TWO = new Sandbox(Provider.clientTwo());
```

in `Sandbox.java`

**Comment by raphw** [comment]
The problem is your class. `Sandbox` defines these two fields:

```java
private static final Sandbox ONE = new Sandbox(Provider.clientOne());
private static final Sandbox TWO = new Sandbox(Provider.clientTwo());
```

When the `SSLContext` is defined, the methods for it return `null` what causes an exception during class initialization. This prevents the class from being initialized and therefore loaded what fails the instrumentation.

I tried to add an improved error message in this PR: https://github.com/mockito/mockito/pull/2098

**Comment by wind57** [comment]
Thank you Rafael, but that `return null` was only to simply the test. If i replace with:

```
    private static SSLContext contextOne() {
        try {
            return SSLContext.getInstance("SSL");
        } catch (NoSuchAlgorithmException e) {
            e.printStackTrace();
            throw new RuntimeException("just because");
        }
    }

    static SSLContext contextTwo() {
        try {
            return SSLContext.getInstance("SSL");
        } catch (NoSuchAlgorithmException e) {
            e.printStackTrace();
            throw new RuntimeException("just because");
        }
    }
```

I would get the same problem. What is more weird is if I do not do any changes at all and simply remove one of the providers : 

```
// remove this provider
//private static final Sandbox TWO = new Sandbox(Provider.clientTwo());
```

it would still fail. I still don't think this has anything to do with the example set-up...

**Comment by raphw** [comment]
Did you remove both static fields? Try running a test that only contains: 

    ClassLoader.forName(Sandbox.class.getName(), true, Sandbox.class.getClassLoader())

And see if it fails. I assume that it still does.

**Comment by wind57** [comment]
oh! I see your point now, I stand corrected. I also like very much the addition of the actual error that will happen.
