### ISSUE TITLE
Return empty value for Iterables

### ISSUE THREAD

**Issue by blasd** [mockito/mockito#210]
http://code.google.com/p/mockito/issues/detail?id=175

I expect an Iterable to be mocked by default with an empty Iterable. I understand from the initial issue this behavior would be introduced in Mockito 2, but beta-8 still returns null.

Could we return null for Iterables ?

Should we have the same behavior for Iterator ?

Thanks

**Comment by bric3** [comment]
Yes it should, thanks for the reminder :)

**Comment by bric3** [comment]
Fixed by 8ceb04a
