### ISSUE TITLE
StackOverFlow trying Mock java.lang.Math

### ISSUE THREAD

**Issue by andfs** [mockito/mockito#2105]
<img width="741" alt="Captura de Tela 2020-11-20 às 19 59 15" src="https://user-images.githubusercontent.com/16955808/99857930-20664380-2b6b-11eb-8643-29ce2ad9eeaf.png">
At this point, seems we get a loop in calls that causes StackOverFlow when trying to static mock java.lang.Math

**Comment by TimvdLippe** [comment]
Please do not mock `java.lang.*` classes, as Mockito us built on top of these. Please use the real method/class.
