### ISSUE TITLE
Release process misses commit message tag

### ISSUE THREAD

**Issue by TimvdLippe** [mockito/mockito#2110]
https://github.com/mockito/mockito/runs/1447478222#step:4:168

https://github.com/mockito/mockito/commit/fde5abb9f044a6b614eeb6a8c63d25fffe2df210 did contain `[ci maven-central-release]` and therefore should have published.

**Comment by mockitoguy** [comment]
on it

**Comment by mockitoguy** [comment]
Should work now and there is a version in maven central: https://bintray.com/mockito/maven/mockito/3.6.28#central
