### ISSUE TITLE
Introduce Mockito#dummy method to create particular dummy test doubles

### ISSUE THREAD

**Issue by fappel** [mockito/mockito#213]
I just stumbled across the implementation notes on dummy test doubles inGerard Meszaros' xUnit Test Patterns book and noticed that he proposes to throw a RuntimeException (I probably would prefer more specifically a UnsupportedOperationException). I guess this is meant to ensure the contract that there should be no method calls ever on a dummy stand-in. Which sounds reasonable to me.

When using mockito test doubles it seems that this usually is omitted as people consider it probably to cumbersome to stub every method to throw such an exception (Just an example: http://www.agile-engineering.net/2011/11/test-doubles-with-mockito.html, and to be honest I didn't do it by myself...).

But even if done, when functionality is added to the component that the dummy replaces, adoption of the dummy doubles could easily be overlooked. Hence I wonder if it wouldn't be neat to have a convenience method that does this configuration out of the box? Or would the value added be too small, because using a dummy accidently outside of its designated purpose happens only once in a while?

Anyway, thanks for the great tool!

**Comment by bric3** [comment]
Hi,

Are you looking for `Mockito.mock(type, answer_that_raise_exceptions)` ?

I don't understand really why dummy are brought here, and anyway **mocking
value object is wrong!** INstead have builders or factory that can create
these objects.

Anyway xUnit pattern book may not be up to date regarding mocking or unit
testing. I'd favor other books instead or take some distance with it.

For example : This book is great, yet some test implementation are a bit
outdated in my humble opinion, however the approach to software development
is great : Growing Object Orient Software guided by Tests.
Or some other specifically on Mockito, there a few out there.



-- Brice

**Comment by fappel** [comment]
Hi,

 

thanks and sorry for bothering, I wasn't aware of that possibility - shame on me. Just gave it a try with the snippet

 

    Runnable runnable = mock( Runnable.class, ( Answer )invocation -> { 

      throw new UnsupportedOperationException(); 

    }  );

    runnable.run();

 

and it worked as expected. So if needed, a little helper should do the trick.

 

Agreed the Dummy example in Meszaros' book probably isn't well chosen, but in general I find his test double classification not too bad. Anyway, thanks for the book proposal, but I read it already and indeed it was a good experience trying out the approach it describes in a small project last year ;-)

 

 

Regards

Frank

 

 

 

Von: Brice Dutheil [mailto:notifications@github.com] 
Gesendet: Samstag, 18. Juli 2015 16:55
An: mockito/mockito
Cc: Frank Appel
Betreff: Re: [mockito] Introduce Mockito#dummy method to create particular dummy test doubles (#213)

 

Hi,

Are you looking for `Mockito.mock(type, answer_that_raise_exceptions)` ?

I don't understand really why dummy are brought here, and anyway **mocking
value object is wrong!** INstead have builders or factory that can create
these objects.

Anyway xUnit pattern book may not be up to date regarding mocking or unit
testing. I'd favor other books instead or take some distance with it.

For example : This book is great, yet some test implementation are a bit
outdated in my humble opinion, however the approach to software development
is great : Growing Object Orient Software guided by Tests.
Or some other specifically on Mockito, there a few out there.



-- Brice

**Comment by bric3** [comment]
@fappel By the way I remember a blog post by the infamous Uncle Bob about mocks, doubles, etc. Definitely a great read !

http://blog.8thlight.com/uncle-bob/2014/05/14/TheLittleMocker.html

**Comment by fappel** [comment]
@bric3 Thanks again. Usually I'm a big 'fan' of Uncle Bob and I know this post, but for once I think he's not accurate enough when describing mocks. I tend to go with Authors defining mocks as doubles that cause tests to fail in their excercise phase, in case they are not meeting the expected behavior. This has an advantage when it comes down to the failure trace, as this points directly to the cause of the problem - whereas spys causes the failure 'after the fact' in the verification phase. From that point of view Bob's mock is also a spy.

**Comment by sabram** [comment]
I know this is an old thread, but I too would value a dummy() method. Just a wrapper around the code discussed above. For example:

    /**
     * Creates a dummy that throws an UnsupportedOperationException upon invocation of any method.
     * Typically used when you are forced to pass an argument but you do not expect it to be used.
     *
     * <pre class="code"><code class="java">
     *   Foo dummy = dummy(Foo.class);
     *   dummy.anything(); //will throw UnsupportedOperationException
     * </code></pre>
     *
     * @param classToDummy class or interface to dummy
     *
     * @return dummy object
     */
    public static <T> T dummy(Class<T> classToDummy) {
        return mock( classToDummy, (Answer) invocation -> {
            throw new UnsupportedOperationException();
        }  );
    }

    @Test(expected = UnsupportedOperationException.class)
    public void dummy_should_throw_ex_on_any_invocation() {
        List dummy = Dummy.dummy(List.class);
        dummy.toString();
    }


In Uncle Bob's example, he implemented the interface himself, but rolling your own is a minor pain. 
As @fappel suggested, I think having dummy() or @Dummy would be a nice convenience.

I don't mind trying the grunt work and issuing a PR, but @bric3 do you still think a bad idea?
