### ISSUE TITLE
Shortcuts with async-related types (CompletableFuture, Mono, Flux)

### ISSUE THREAD

**Issue by v1nc3n4** [mockito/mockito#2133]
Hi

I'm using reactive programming, with the [Reactor](https://projectreactor.io/) library, and I write unit tests for my components. The more I write test with Mockito, the more I see the library may miss some shortcuts to program stubs and return predefined results encapsulated in a `CompletableFuture`/`Mono`/`Flux` publisher.

For example, the following stubbing:
```java
// Item save(Item item);
when(itemRepository.save(any(Item.class))).then(AdditionalAnswers.returnsFirstArg());
```
has no equivalent in reactive programming such as:
```java
// CompletableFuture<Item> save(Item item);
when(itemRepository.save(any(Item.class))).then(AdditionalAnswers.returnsCompletableFutureOfFirstArg()));
```

The only solution I found was to create custom answers to handle this scenario.
Am I doing something wrong?
How can I write less verbose test with reactive-style programming?

Thanks in advance for your help!
Regards

**Comment by TimvdLippe** [comment]
A custom answer would indeed be the appropriate solution for this use case. It is unlikely we are going to be shipping that in mockito-core itself, so we encourage these kind of answers to be bundled with the library that implements these patterns/types as well.
