### ISSUE TITLE
objenesis dependency in INDEX.LIST (mockito-all)

### ISSUE THREAD

**Issue by sixinli** [mockito/mockito#214]
Hi,

It seems like mockito-all is coming all the dependencies in the package, why is there a dependencies on objenesis-2.1.jar in the INDEX.LIST? This is actually breaking my build because I don't have that jar. :(

Thanks,
Sixin

**Comment by bric3** [comment]
Hi,

I have no idea what is this INDEX.LIST file, the CI certainly don't generate one.

As you can see the 1.10.19 POM doesn't declare any extra dependencies : http://search.maven.org/#artifactdetails%7Corg.mockito%7Cmockito-all%7C1.10.19%7Cjar

And for the record, with 2.x mockito-all artifact will disappear and use the regular dependencies mechanism.

**Comment by sixinli** [comment]
Hi, 

sorry for the confusion. So I downloaded "mockito-all-1.10.19.jar" from the link you mentioned and unzip the jar. Inside that folder, there's a META-INF folder, if you open that, there's an INDEX.LIST file.

Thanks,
Sixin

**Comment by bric3** [comment]
I've just looked at it ; that file (`INDEX.LIST`) comes from the objenesis jar, mockito-all just packages everything in the same jar including objenesis and hamcrest and files in META-INF.

If something breaks your build I don't see why that would have anything to do with it.

**Comment by sixinli** [comment]
So in INDEX.LIST, it says it depends on the objenesis jar, which means I would have the jar ready in the right spot. But mockito-all comes with objenesis in its packages, it doesn't make sense for it to ask for yet another external objenesis jar?

**Comment by bric3** [comment]
> So in INDEX.LIST, it says it depends on the objenesis jar

That doesn't make sense, as this file is in the the original objenesis jar, this file cannot mean objenesis depends on objenesis. See [objneseis jar](https://bintray.com/artifact/download/easymock/distributions/objenesis-2.1-bin.zip).
