### ISSUE TITLE
Mockito can no longer mock nested interface on JDK 16-ea+28 and 17.ea+3

### ISSUE THREAD

**Issue by marcphilipp** [mockito/mockito#2156]
After upgrading from JDK 16-ea+28 and 17.ea+1 to 16-ea+30 and 17.ea+3, respectively, Mockito can no longer mock an interface that is defined inside another interface:

```
org.mockito.exceptions.base.MockitoException:
Mockito cannot mock this class: interface org.junit.platform.engine.support.hierarchical.Node$DynamicTestExecutor.

Mockito can only mock non-private & non-final classes.
If you're not sure why you're getting this error, please report to the mailing list.


Java               : 16
JVM vendor name    : Oracle Corporation
JVM vendor version : 16-ea+30-2130
JVM name           : OpenJDK 64-Bit Server VM
JVM version        : 16-ea+30-2130
JVM info           : mixed mode, sharing
OS name            : Mac OS X
OS version         : 10.16
```

Gradle build scan: https://ge.junit.org/s/7nva27dj6tilo/tests/:junit-jupiter-engine:test/org.junit.jupiter.engine.descriptor.TestFactoryTestDescriptorTests$Streams/streamsFromTestFactoriesShouldBeClosed()#1

I tried upgrading to 3.6.48 but it did not resolve the issue.

Code is here: https://github.com/junit-team/junit5/blob/5c64fceacb596a182a25853f7fcaeaefe23abfa7/junit-platform-engine/src/main/java/org/junit/platform/engine/support/hierarchical/Node.java#L282

**Comment by raphw** [comment]
Interesting, the variable *C* should never occur in the context of the interface, which is implicitly static. I will have a look, thanks for reporting!

**Comment by raphw** [comment]
You are observing this problem: https://github.com/raphw/byte-buddy/issues/991

I am of the opinion that this is a bug in a recent change of OpenJDK but I will await some feedback, worst case I need to adjust Byte Buddy to handle this inconsistency.

**Comment by TimvdLippe** [comment]
@raphw Am I correct to understand this issue has been fixed per https://github.com/raphw/byte-buddy/issues/991#issuecomment-760452474 ?

**Comment by marcphilipp** [comment]
I can confirm that the issue no longer appears with 16.ea+32 and 17.ea+5.

**Comment by iloveeclipse** [comment]
@raphw : is the patch in this release below already? 
https://github.com/raphw/byte-buddy/releases/tag/byte-buddy-1.10.22

**Comment by raphw** [comment]
It is a fix in the JDK, not Byte Buddy.
