### ISSUE TITLE
Have Mockito.once to simplify Mockito.times(1)

### ISSUE THREAD

**Issue by divinedragon** [mockito/mockito#2166]
Most verification counts in Tests are `Mockito.times(1)`. Having a handly `Mockito.once()` would simplify the test and make them more readable.

**Comment by TimvdLippe** [comment]
I don't think this addition is desirable. It increases our API surface for little gain. If we were to add this method, then for the same reason you would add `twice()` and-so-forth. Since our API surface is already large, I don't think we should add such methods.

I will let the other core members chime in if they disagree. Otherwise I will close this ticket in a couple of days.

**Comment by divinedragon** [comment]
@TimvdLippe I understand the rational of increased API surface, but there are very less tests that would require a `twice` or even less `thrice` methods. A request to add more similar methods would be very unlikely. My argument is purely from the the readability of the tests.

This 
```Mockito.verify(mock, once()).method(any());```

reads much better than

```Mockito.verify(mock, times(1)).method(any());```

**Comment by TimvdLippe** [comment]
I have to respectfully disagree that the former reads better than the latter. Since this is a subjective argument, I value the impact on our API surface more, for which I noted above my hesitations of increasing our surface with this method.

**Comment by grimreaper** [comment]
(I am not a core team member)

I do see why `once` can be considered categorically dissimilar from twice and higher and would not lead to a slippery slope. However, I also don't see a strong argument for its inclusion: its not shorter, easier to follow, or possibly implemented differently.   It would be merely an API of convenience.

**Comment by iherasymenko** [comment]
How about `Mockito.verify(mock).method(something)` ? Imo this is a reasonable alternative that has been available for a while.

**Comment by TimvdLippe** [comment]
Closing this issue for now. Given that the default behavior of `Mockito.verify` is to imply `times(1)`, omitting the VerificationMode is better than adding a new alias for it.

Thanks everyone for your contributions!

**Comment by mehr-licht** [comment]
> I don't think this addition is desirable. It increases our API surface for little gain. If we were to add this method, then for the same reason you would add `twice()` and-so-forth. Since our API surface is already large, I don't think we should add such methods.
> 
> I will let the other core members chime in if they disagree. Otherwise I will close this ticket in a couple of days.

There's no reason to add twice(). If there was then never() should be replaced by Mockito.times(0)
