### ISSUE TITLE
Release to maven central does not finish

### ISSUE THREAD

**Issue by TimvdLippe** [mockito/mockito#2167]
We tried to publish 3.7.0 to Maven Central today, but its build does not terminate and is not showing any logs: https://github.com/mockito/mockito/runs/1644731561

**Comment by mockitoguy** [comment]
Attempted a manual publish to central from Bintray UI...

**Comment by mockitoguy** [comment]
Manual publish from Bintray UI worked out: https://repo1.maven.org/maven2/org/mockito/mockito-core/3.7.0/

**Comment by wborn** [comment]
Thanks for the quick release! It works fine for me (https://github.com/openhab/openhab-core/pull/2075). :+1:

**Comment by TimvdLippe** [comment]
This appears to be fixed, as we successfully published 3.7.7 to Maven central based on https://github.com/mockito/mockito/commit/7b940bcead5240bd030bbe7acbb51c10be0a452b
