### ISSUE TITLE
Feature request: Unify order of parameters

### ISSUE THREAD

**Issue by bohni** [mockito/mockito#2173]
Hello,

I just stumbled accross the switched order of the VerificationMode parameter

    org.mockito.Mockito.verify(T, VerificationMode)
vs

    org.mockito.MockedStatic.verify(VerificationMode, Verification)

Is there a reason, the VerificationMode from MockitoStatic is at first position?

**Comment by TimvdLippe** [comment]
No, this might be a simple oversight. @raphw I think we can reverse the order? We would need to add an overload and then deprecate the existing one, which we can delete in Mockito 4.0.0.

**Comment by raphw** [comment]
No, I don't think I had an intention with the order, possibly to have the lambda last what often works better with languages like Kotlin. But I think consistency is the better goal.

**Comment by TimvdLippe** [comment]
@bohni Do you mind sending us a PR with the added method + deprecation?

**Comment by bohni** [comment]
OK, I will take a look
