### ISSUE TITLE
A test annoatatekd with @RunWith(PowerMockRunner.class) would throw NotAMockException if mock-inline is also used in the same project

### ISSUE THREAD

**Issue by rxue** [mockito/mockito#2181]
Problematic code:

    @RunWith(PowerMockRunner.class) 
    @PrepareForTest({DBHandlerCalc.class})
    public class CalculationTest {
        @Test //junit 4
        public void testWithPowerMock() {
            Powermockito.mockStatic(DBHandlerCalc.class);
            //Powermockito.when() and thenReturn() is called
        }
    }

List of relevant software versions:

* JDK 8
* juni 5.4.0
* mockito with mockito-inline 3.4.0
* powermock 2.0.9 with junit 4.12

When working in a **legacy code** base, where there are existing tests using the *powermock* in combination with **junit 4**, as *powermock* is not actively developed anymore probably due to its tight dependency on junit 4 only without the extension support on junit 5 and its boilerplate coding style etc., on the other hand the *mockito* was actively updated  already to version 3.4+ with a by-product library, **mockito-inline**, supporting mockito's new built-in `mockStatic` functionality. So getting rid of the powermock usage would make the maintanence and future development work simpler, and thus I added the *mock-inline* library.

However, after adding the *mock-inline* library and then executing the legacy tests annotated with the `@RunWith(PowerMockRunner.class)`, `NotAMockException` were encountered

**Comment by TimvdLippe** [comment]
This is an issue with Powermock, most likely https://github.com/powermock/powermock/issues/1034

**Comment by rxue** [comment]
Oh yeah! The association between _powermock_ and _mockito_ is unidirectional, say powermock has dependency on mockito, but mockito should know nothing about powermock. From the layered architecture aspect, mockito is on the lower level whereas powermock is on top of mockito.

Right? :)
