### ISSUE TITLE
Migrate away from JCenter repository

### ISSUE THREAD

**Issue by lwasyl** [mockito/mockito#2197]
jcenter is going away soon: https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/

I'm sure you're well aware, it's just an issue to track progress on this.

**Comment by TimvdLippe** [comment]
We won't be publishing every version to Maven Central (#911), but we will be publishing to a separate Nexus.

**Comment by TiKevin83** [comment]
Any update on this? Bintray is being sunset in 4 days and the documentation still points to the latest updates for mockito only being on Bintray.

**Comment by Bananeweizen** [comment]
Also the homepage has a bintray badge, which is meanwhile broken.

**Comment by TimvdLippe** [comment]
This is scheduled to be fixed next weekend. Thanks for your patience!
