### ISSUE TITLE
java.lang.NullPointerException: any() must not be null

### ISSUE THREAD

**Issue by s-ilnar** [mockito/mockito#2200]
Mockito version 3.4.0
Kotlin version 1.4.10

When trying to execute `when(mapper.transform(any()).thenReturn(mappedData)`

Crash occurs  `java.lang.NullPointerException: any() must not be null`

How can this be solved?

**Comment by TimvdLippe** [comment]
For Kotlin projects, please use `mockito-kotlin` instead: https://github.com/mockito/mockito-kotlin

**Comment by gilangtiket** [comment]
been stuck for hours because of this ambiguous import, `mockk` FTW!

**Comment by BoP-haeger** [comment]
> For Kotlin projects, please use `mockito-kotlin` instead: https://github.com/mockito/mockito-kotlin

Good explanation 
https://www.damirscorner.com/blog/posts/20221223-MockitoAndNonNullTypesInKotlin.html
