### ISSUE TITLE
Please do a release, as we want to use mockito on jdk 17.

### ISSUE THREAD

**Issue by XenoAmess** [mockito/mockito#2212]
Hi.
I'm tracking why commons-io will fail ci on JDK17.
After tracking I finally found out the latest mockito relase use ASM 9.0 which cannot handle jdk 17.
As you are using 9.1 now, who can handle JDK17,  I hope we can get it a release...
Thanks!
https://github.com/xenoamess-fork/commons-io/runs/1945142044

check that

 - [ ] The mockito message in the stacktrace have useful information, but it didn't help
 - [ ] The problematic code (if that's possible) is copied here;
       Note that some configuration are impossible to mock via Mockito
 - [ ] Provide versions (mockito / jdk / os / any other relevant information)
 - [ ] Provide a [Short, Self Contained, Correct (Compilable), Example](http://sscce.org) of the issue
       (same as any question on stackoverflow.com)
 - [ ] Read the [contributing guide](https://github.com/mockito/mockito/blob/release/3.x/.github/CONTRIBUTING.md)

**Comment by TimvdLippe** [comment]
Sadly we can't guarantee yet that Mockito fully works on JDK 17, given that Gradle doesn't support JDK 16+ (https://github.com/mockito/mockito/pull/2211#issuecomment-782884920) That said, I can publish a new release to Maven Central this week, which seems appropriate regardless of JDK 17 support.
