### ISSUE TITLE
Possible Regression with Java 15 or JUnit 5

### ISSUE THREAD

**Issue by fdutton** [mockito/mockito#2228]
I have a Java 8 project using JUnit 4.12 that I upgraded to Java 15 and JUnit 5.7.1. Both are using Mockito 3.6.28.

The old, Java 8 and JUnit 4, project makes extensive use of `doCallRealMethod` to test default interface methods. The new, Java 15 and JUnit 5, project fails with the following MockitoException:
```
Cannot call abstract real method on java object!
Calling real methods is only possible when mocking non abstract method.
```

Before I try isolating the issue by upgrading my Java 8 project to JUnit 5, I wanted to see if this is known issue that already has a solution.

**Comment by TimvdLippe** [comment]
We are not aware of any specific problems. Once you figured out which upgrade is the culprit, feel free to reopen this issue.
