### ISSUE TITLE
Mockito.spy works incorrectly with java 16

### ISSUE THREAD

**Issue by nedis-ua** [mockito/mockito#2231]
Using JDK 16 the following test:
```
public class UnitTest {

    private final java.util.logging.Logger realLogger = java.util.logging.Logger.getLogger("test");

    private final java.util.logging.Logger loggerSpy = Mockito.spy(realLogger);

    @Test
    void test() {
        loggerSpy.isLoggable(Level.INFO);
    }
}
```
throws the exception:

```
java.lang.NullPointerException: Cannot read field "levelValue" because "this.config" is null
	at java.logging/java.util.logging.Logger.isLoggable(Logger.java:2032)
	at rxmicro.logger@0.10-SNAPSHOT/io.rxmicro.logger.jul.UnitTest.test(UnitTest.java:36)
```

The cause of this exception is that the spy (`loggerSpy`) created by the Mockito does not contain field values from the original object, i.e. `realLogger`:
![image](https://user-images.githubusercontent.com/3287489/111614421-41246a00-87e8-11eb-8a34-6246dad6d34a.png)

Environment:

Operating System: `Ubuntu 18.04.5 LTS`
Kernel: `Linux 5.4.0-56-generic`
Architecture: `x86-64`
**JDK: openjdk version "16" 2021-03-16
OpenJDK Runtime Environment Zulu16.28+11-CA (build 16+36)
OpenJDK 64-Bit Server VM Zulu16.28+11-CA (build 16+36, mixed mode, sharing)**
Junit version: `5.7.1`
Mockito version: `3.7.7`

**It seems that this problem is actual only for JDK 16, because if I use `JDK 15`, `JDK 14`, `JDK 13`, `JDK 12` and `JDK 11`, this code does not throw any exceptions and during debug I see that the spy instance contains initialized fields from the original object:**

![image](https://user-images.githubusercontent.com/3287489/111616017-0fac9e00-87ea-11eb-9fa3-749b3570a75a.png)

**Comment by raphw** [comment]
You'd need to use mockito-inline or open your classes for Mockito as the reflection API is limited from Java 16 and later.

**Comment by TimvdLippe** [comment]
Closing per the above comment.
