### ISSUE TITLE
Clean up old branches

### ISSUE THREAD

**Issue by JeremybellEU** [mockito/mockito#224]
Currently the repository contains a lot of old branches.

![image](https://cloud.githubusercontent.com/assets/5948271/8020909/9a942064-0c8b-11e5-88c2-179eb7f40ce2.png)

Is there a specific reason why they are not deleted? For example branch issue230 has been merged into master back in 2012, but the branch is still alive.

Deleting old branches would make it easier to see ongoing contributions from pull-requests by both contributors and external users.

**Comment by bric3** [comment]
Yeah I was thinking the same thing, actually I deleted those branches on my clone a few hours ago already.

**Comment by bric3** [comment]
More I'm thinking about removing version branches and replace them by tags

**Comment by JeremybellEU** [comment]
Yes that sounds reasonable. Tags are a lot more suitable in these situations.

**Comment by bric3** [comment]
They are anyway an artifact of the transformation from mercurial to github, at that time I didn't quite get git, and I wanted something more _mercurially_, now those branches don't make sense anymore.

**Comment by bric3** [comment]
Cleaned a few already, I'll take care of the version branch tomorrow

**Comment by szczepiq** [comment]
Reopen if needed!
