### ISSUE TITLE
Android latest version is 3.8.0

### ISSUE THREAD

**Issue by AndreSand** [mockito/mockito#2252]
Hi,

Looks like we can't update to 3.8.20, since it's not on maven yet https://mvnrepository.com/artifact/org.mockito/mockito-core.

For Android use version 3.8.0.

**Comment by TimvdLippe** [comment]
https://github.com/mockito/mockito#how-to-release-new-version

> Not every version is published to Maven Central.

We publish a new version to Maven Central about once a month.
