### ISSUE TITLE
Mockito Inline Mock Maker - throws Exception - Argument passed to when() is not a mock

### ISSUE THREAD

**Issue by msnkishore** [mockito/mockito#2253]
Hi,

I wanted to mock static methods, hence used dependency "mockito-inline" 3.8 version instead of "mockito-core"

The static method mocks work fine but my old tests that mock interfaces fail with the below error

`org.mockito.exceptions.misusing.NotAMockException: 
Argument passed to when() is not a mock!
Example of correct stubbing:
    doThrow(new RuntimeException()).when(mock).someMethod();`

Reverting to using mockito-core solves the issue but then I would not be able to mock static methods

Is there any way we can choose different mockito engines (Subclass/Inline) for each class?

Regards
msn

**Comment by msnkishore** [comment]
Duplicate of https://github.com/mockito/mockito/issues/1980, MockResolver fixed the issue

**Comment by Kosmo1** [comment]
@msnkishore Exactly how did MockResolver fix the issue? I just ran into this same issue when using v3.4.0, and changing to v3.6.0 (which included #2042 and the MockResolver support) did not resolve the issue. Please tell me how to get Mockito to recognize @SpyBeans - thank you.

**Comment by woonys** [comment]
I also faced the same issue with the version to v3.6.0.
