### ISSUE TITLE
Exclude internal package from javadoc

### ISSUE THREAD

**Issue by bric3** [mockito/mockito#226]
Internal package don't need to be included in the javadoc generation, just like the jdk doesn't have `com.sun` package

In the javadoc that may be done via a doclet since `exclude '**/internal/**'` raise javadoc errors

```groovy
doclet = "qualified.name.of.DocletExclude"
docletpath = [rootProject.file('./gradle/doclet-exclude.jar')]
```

**Comment by szczepiq** [comment]
Great idea.
