### ISSUE TITLE
Mockito fails to work in Java 11 with JPMS modules

### ISSUE THREAD

**Issue by rgoers** [mockito/mockito#2282]
I am migrating Log4j 2 to fully support JPMS. In doing that the unit tests that use Mockito are all failing with

    java.lang.IllegalStateException: Could not initialize plugin: interface org.mockito.plugins.MockMaker (alternate: null)
    Caused by: java.lang.IllegalStateException: Internal problem occurred, please report it. Mockito is unable to load the default implementation of class that is a part of Mockito distribution. Failed to load interface org.mockito.plugins.MockMaker
    Caused by: java.lang.reflect.InvocationTargetException
    Caused by: java.lang.NoClassDefFoundError: net/bytebuddy/dynamic/loading/ClassInjector$UsingReflection
    Caused by: java.lang.ClassNotFoundException: net.bytebuddy.dynamic.loading.ClassInjector$UsingReflection

If is set system property "org.mockito.internal.noUnsafeInjection" to true then it fails the same way trying to access $UsingLookup. 

Note that this worked fine with the same versions of Mockito and byte-buddy when a module-info.java wasn't present.

Do I need to add an --add-opens for something?

**Comment by raphw** [comment]
Are you using mockito-inline? Otherwise you'd need to open your module to Mockito.

**Comment by rgoers** [comment]
No, Log4j does not use mockito-inline. I'm not really sure what that is to be honest. I didn't write any of the stuff that uses Mockito in Log4j. 
I don't understand how opening the module to Mockito will help resolve a class not found exception in byte buddy? Wouuln't Mockito have to open something?

**Comment by raphw** [comment]
Mockito cannot open anything. Modules are fully encapsulated. Try replacing mockito-core with mockito-inline in your dependencies and make sure to use the latest version. Alternatively, do you have a reproducing branch?

**Comment by rgoers** [comment]
I have checked the code into the jpms-mockito-fails branch of https://github.com/apache/logging-log4j2.  Clone the repo, checkout that branch and then run mvn clean install. You will need Java 11  and I believe you will need at least Maven 3.6.1.

**Comment by TimvdLippe** [comment]
https://github.com/apache/logging-log4j2/compare/jpms-mockito-fails has the full diff. Since this diff is quite large, would it be possible to separate the directory rename? That would hopefully make it a bit easier for us to digest what the diff is and what the potential culprit could be. Thanks!

**Comment by rgoers** [comment]
No, it wouldn't be possible. Prior to this change Log4j-core was an automatic module and the tests were not modules at all. To convert to a JPMS module the tests also had to be converted to comply with JPMS. The tests were being passed downstream for other modules to use in tests but they shared the same package name as the main module. So the tests being passed on had to be split. Plus some of the test classes were using the log4j-api package namespace. 

The diff is that Log4j-core used to have an automatic module name, which meant while it had a name it really wasn't a JPMS module. It didn't have all the restrictions placed on it that named modules do so everything was open. Because of the change, all the tests now run on the module path instead of the class path, which means everything has to conform to JPMS.

**Comment by raphw** [comment]
The reason is pretty obvious: Byte Buddy is missing from the class path. I do not know how the module path is assembled, but I assume that the tool you are using does not know how to process an automatic module such as Mockito that requires a dependency. I set a breakpoint in the test and class in question and the *net.bytebuddy* module is not on the module path while the class path is empty.

We'll see how to improve the error message in such a case, I assume the tooling around the module system is still lacking a few details so this might just pay off.

**Comment by rgoers** [comment]
Thanks. That is interesting since the class shows up with mvn dependency:tree and clearly is there since just adding the requires for it fixes the problem. I'm not sure why that didn't occur to me. I'd guess it is the surefire plugin setting up the class path and module path, or something it delegates to. It sure would have been nice to have had some kind of warning message that dependencies were being ignored. Anyway, I will close this issue.

**Comment by TimvdLippe** [comment]
@raphw we have some background information and attempts in #2604 I would love to review a PR for that, but afaik it wasn't particularly straightforward task to do.
