### ISSUE TITLE
Regression in @Mock and Rules initialization   

### ISSUE THREAD

**Issue by protocol7** [mockito/mockito#2288]
Hey,

In 2.26.0, there was a regression introduced in how @Mock's are initialized with respect to Rule's in MockitoJUnitRunner. In this change https://github.com/mockito/mockito/commit/49e6311fcf774f6931ffbb627702e4fb99ef3604, the initialization of @Mock's is moved to be run within the rule, meaning that any @Mock's are uninitialized before the rule's base statement is executed. 

Here's a test that works in 2.25.1 but fails in 2.26.0. I'm not sure is the initialization order is defined and part of the API, but we noticed this as it breaks a large number of tests for us.

```
import org.junit.Rule;
import org.junit.Test;
import org.junit.rules.TestRule;
import org.junit.runner.Description;
import org.junit.runner.RunWith;
import org.junit.runners.model.Statement;
import org.mockito.Mock;
import org.mockito.junit.MockitoJUnitRunner;

import java.util.function.Supplier;

import static org.junit.Assert.assertNotNull;

@RunWith(MockitoJUnitRunner.class)
public class MockitoMockInitationTest {

  public static class MyRule implements TestRule {
    private final Supplier<TestInterface> parameter;

    public MyRule(final Supplier<TestInterface> parameter) {
      this.parameter = parameter;
    }

    @Override
    public Statement apply(final Statement statement, final Description description) {
      return new Statement() {
        public void evaluate() throws Throwable {
          // this is the crucial bit, before 2.26.0 @Mock's are initiated already before the base statement is evaluated
          assertNotNull(parameter.get());
          statement.evaluate();
        }
      };
    }
  }

  interface TestInterface {}

  @Mock private TestInterface mock;
  @Rule public MyRule rule = new MyRule(new Supplier<TestInterface>() {
    @Override
    public TestInterface get() {
      return mock;
    }
  });

  @Test
  public void placeholderTest() {
  }
}
```

**Comment by TimvdLippe** [comment]
Yes this is an intentional change. Previously, we were breaking the `@Rule` interface in JUnit which we rectified. Essentially, the old behavior would be somewhat equivalent to `static { MockitoAnnotations.initMocks(this);`, which JUnit did not officially support.

If you rely on ordering between rules/runners, then you should use `RuleChain`. https://junit.org/junit4/javadoc/4.12/org/junit/rules/RuleChain.html In that case, it becomes:

```java
@Rule public Rule rules = RuleChain.outerRule(MockitoJUnit.rule())
    .around(new MyRule(new Supplier<TestInterface>() {
      @Override
      public TestInterface get() {
        return mock;
      }
    }));
```

**Comment by protocol7** [comment]
That makes sense, thanks for the confirmation :)
