### ISSUE TITLE
Print the fully qualified class names if the simple class names are the same

### ISSUE THREAD

**Issue by kluever** [mockito/mockito#2311]
I have 2 overloads of a method:
* `setDeadline(java.time.Duration)`
* `setDeadline(org.joda.time.Duration)`

There's a mocking failure in a test (calling the wrong overload), but the error message isn't super helpful:

```
1) myMethod(com.google.frobber.MyClassTest)
Argument(s) are different! Wanted:
myClass.setDeadline(
    (Duration) PT1S
);
-> at com.google.frobber.MyClassTest.myMethod(MyClassTest.java:287)
Actual invocation has different arguments:
myClass.setDeadline(
    (Duration) PT1S
);
```

The output attempts to include the classnames to help disambiguate, but in this case, the simple class names are identical (`Duration`). We should be able to detect this, and print the FQCNs if the simple names are equal.

Alternatively, we could always print the FQCNs:

https://github.com/mockito/mockito/blob/6f9108b833323345bd926f10914224d3e0a11b80/src/main/java/org/mockito/internal/matchers/Equals.java#L55

(We already do something similar in Truth.)

**Comment by TimvdLippe** [comment]
This is probably a relatively simple change. For anybody who is looking to contribute to Mockito, this is a good starter bug!

**Comment by saurabh7248** [comment]
I would love to try to fix this.

**Comment by TimvdLippe** [comment]
@saurabh7248 Awesome. Looking forward to the PR!

**Comment by chaehwanli** [comment]
Sorry, I got some misunderstanding. I revert my PR. :)

**Comment by TimvdLippe** [comment]
@chaehwanli Looking at https://github.com/chaehwanli/mockito/commit/2175bfb43e75d80976d75ab0338aaf751cdee9eb I think that would be the correct fix for this. Do you mind sending that as a PR?

**Comment by chaehwanli** [comment]
@TimvdLippe 
Oh.. thank you for your review~ I will send again at night in KST. I'm at office. :)

**Comment by saurabh7248** [comment]
@chaehwanli changes would have printed the full name even when the classes would have different simple names.
I have added a list of indexes in PrintSettings which would do this only for arguments having same simple names.

**Comment by TimvdLippe** [comment]
@saurabh7248 Ah good catch. Thank you so much both of you to work on this and iterating on a solution 😄  That approach SGTM. I think there are some small improvements we can make in terms of code structure, but I like that approach as well.

If you could open a PR, then we start discussing the implementation there and iterate on that separately from this issue thread. Thank you for your work thus far!

**Comment by saurabh7248** [comment]
Have opened a pull request [here](https://github.com/mockito/mockito/pull/2320).

**Comment by TimvdLippe** [comment]
Fixed in https://github.com/mockito/mockito/commit/1ad82350765566b2afabbab9ec15ad5ccd54951a
