### ISSUE TITLE
NullPointerException from android.os.Messenger.getBinder

### ISSUE THREAD

**Issue by leaves7984** [mockito/mockito#2326]
Hi there,

We are currently facing this NullPointerException error from android.os.Messenger.getBinder with Robolectric version 4.3.1 and Mockito version 2.18.3. And we are not seeing this error with Robolectric version 4.0.1 and Mockito version 2.18.3.

java.lang.NullPointerException
	at android.os.Messenger.getBinder(Messenger.java:67)
	......

Here is the code we did:
@RunWith(BaseRobolectricTestRunner.class)
....
@Mock private Handler handlerMock;
.....
IBinder binder = new Messenger(handlerMock).getBinder();

We created a mock Handler object as handlerMock and pass into Messenger to create an IBinder object.

Not sure why this error is showing up with different Robolectric version. Please help to point us what could be the potential cause of this Java Null Pointer error.

**Comment by TimvdLippe** [comment]
This is most likely an issue with Robolectric. Please open an issue on their repository for further help.
