### ISSUE TITLE
mockito 2.0.14 fails to mock jetty httpclient

### ISSUE THREAD

**Issue by christophsturm** [mockito/mockito#233]
this fails:
<pre>
     import org.eclipse.jetty.client.HttpClient;
    HttpClient httpClient = mock(HttpClient.class);
</pre>
(jetty 9.2.10.v20150310)

with mockito 2.0.2-beta i can mock that class without a problem. 

stacktrace:
<pre>
java.lang.IllegalAccessError: tried to access class org.eclipse.jetty.util.component.ContainerLifeCycle$Managed from class org.eclipse.jetty.client.HttpClient$MockitoMock$362486671
	at org.eclipse.jetty.client.HttpClient$MockitoMock$362486671.<clinit>(Unknown Source)
	at sun.reflect.GeneratedSerializationConstructorAccessor2.newInstance(Unknown Source)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:408)
	at org.objenesis.instantiator.sun.SunReflectionFactoryInstantiator.newInstance(SunReflectionFactoryInstantiator.java:45)
	at org.objenesis.ObjenesisBase.newInstance(ObjenesisBase.java:73)
	at org.mockito.internal.creation.instance.ObjenesisInstantiator.newInstance(ObjenesisInstantiator.java:14)
	at org.mockito.internal.creation.bytebuddy.ByteBuddyMockMaker.createMock(ByteBuddyMockMaker.java:27)
	at org.mockito.internal.util.MockUtil.createMock(MockUtil.java:33)
	at org.mockito.internal.MockitoCore.mock(MockitoCore.java:59)
	at org.mockito.Mockito.mock(Mockito.java:1392)
	at org.mockito.Mockito.mock(Mockito.java:1270)
</pre>

**Comment by bric3** [comment]
Is this an OSGI package ?

**Comment by bric3** [comment]
Also a general principle when mocking is _to not mock types you don't own_, there's several reasons for that see that [wiki page](https://github.com/mockito/mockito/wiki/How-to-write-good-tests)

**Comment by christophsturm** [comment]
yeah, i know about that rule. this is from a really tiny method and i just want to check that it invokes the start method. 

jdk8, jetty 9.2.10

**Comment by raphw** [comment]
The `Managed` inner class is package-private: http://grepcode.com/file/repo1.maven.org/maven2/org.eclipse.jetty/jetty-util/9.1.3.v20140225/org/eclipse/jetty/util/component/ContainerLifeCycle.java#ContainerLifeCycle.Managed

This class should never be accessible from `org.eclipse.jetty.client.HttpClient` or any mock which both live in another package. I assume that you have a version clash on your class path. Creating a mock can trigger class path resolutions via the introspection that is required to create the mock.

**Comment by christophsturm** [comment]
ok but the HttpClient class can be instantiated just fine by calling its constructor

client = new HttpClient();

**Comment by christophsturm** [comment]
also the managed enum is only used inside ContainerLifeCycle.

**Comment by raphw** [comment]
I see what the problem is. Byte Buddy overrides the public method `ContainerLifeCycle::addBean(Object o, Managed managed)` in order to mock it. For this, the mock references the `Managed` class which is however package private.

While this is a rather poorly designed API as the method should itself be package-private as it cannot be used outside of the package, Byte Buddy should be smart enough to figure this out. It is a small fix, I have it ready some time this week. Thanks for reporting!

**Comment by christophsturm** [comment]
thanks. I agree that the package structure and api design of jetty is a bit strange.

**Comment by bric3** [comment]
@raphw Thanks for the investigation

**Comment by bric3** [comment]
@christophsturm Thanks for the feddback too, note mockito 2.0.0 is still in beta phase

**Comment by christophsturm** [comment]
sure! we will just continue to use 2.0.2-beta for now which works great.

**Comment by bric3** [comment]
You can use a more recent beta 2.0.8, the last version before switching to bytebuddy

**Comment by raphw** [comment]
Byte Buddy 0.6.9 is released which should fix the issue. Sorry for the hick-up.

**Comment by bric3** [comment]
No problem, you were blazingly fast !
