### ISSUE TITLE
How to mockito a new object in a method？

### ISSUE THREAD

**Issue by afreetgo** [mockito/mockito#2339]
> Hey,
>
> How to mockito a new object in a method？
>for example: 
`

        public void add(String msg){
               User user = new User();
               boolean isFlag = user.send(msg);
               if(isFlag){
                      .....
               }else{
                      ....
              }
      }

`
> How to mock the send method executed by the user object?
>Similar to "whenNew" method in powermock, is there the same function in mockito?

**Comment by EugeneLesnov** [comment]
Hi! I don't think it is an use-case for mockito. You can try to redesign the architecture of your application. I don't really know what your software is doing about..but seems like `User` is entity (data that persisted to the database) or DTO (data transfer object).
If so, in both cases, such objects should not have behavior, and therefore should not be mocked.

**Comment by afreetgo** [comment]
MessageClient  is an SDK provided by a third party。
`
         public void add(Message message)
            MessageClient client = new MessageClient(message.getUrl());
            boolean isFlags = client.send(message.getContent());
            if(isFlags){
                ... 
            }else{
                ...
            }
        }
`

**Comment by EugeneLesnov** [comment]
Provided code looks correct. So, you don't have any problems now?

**Comment by afreetgo** [comment]
MessageClient Objects can only be created by “new MessageClient(message.getUrl()) ”

**Comment by EugeneLesnov** [comment]
Then just make a wrapper class to encapsulate all work with MessageClient. In this way, you can easily mock that wrapper

**Comment by afreetgo** [comment]
It would be better to have a method like powermocker's "whenNew".

**Comment by kamenskyen** [comment]
> It would be better to have a method like powermocker's "whenNew".

+++

**Comment by TimvdLippe** [comment]
You can now mock object construction with the inline mock maker and `Mockito.mockConstruction`. For more information, see https://javadoc.io/doc/org.mockito/mockito-core/latest/org/mockito/Mockito.html#49
