### ISSUE TITLE
how to mock the static android.util.Log.i(String, String) 

### ISSUE THREAD

**Issue by lannyf77** [mockito/mockito#2348]
having a class which internally generates error msg and using static function of android,util.Log.i(String, String) to log the error (it could be some other static function to recored the failure).

```
class Util {

    public static void handleIntent(Intent intent, String Tag, String failMsg) {
        ...
            
        if (true) { // for test
            String s = failMsg; //getError(failCode);
            Log.i(Tag, s);
        }
        ...
    }
}
```

and the test is to verify the error message is logged (using mockito-inline 3.8.0):
```
 @Test
 public void test_log() {

    try (MockedStatic<Log> logMock = Mockito.mockStatic(Log.class)) {

        Intent intent = getIntent();

        // test
        Util.handleIntent(intent, "theTag", "+++TEST1");

        // verify
        Mockito.verify(logMock, times(1)).i(eq(theTag), eq("+++TEST1")); //<== does not compile
        Log.i(eq("+++TEST1"), eq(dataStr));

     }
 }
```

with `Mockito.verify(logMock, times(1))` only, it got error:
```
org.mockito.exceptions.misusing.NotAMockException: 
Argument passed to verify() is of type MockedStaticImpl and is not a mock!
Make sure you place the parenthesis correctly!
See the examples of correct verifications:
    verify(mock).someMethod();
    verify(mock, times(10)).someMethod();
    verify(mock, atLeastOnce()).someMethod();

```
how to mock the `android.util.Log` and verify its `static android.util.Log.i(String, String)` has been called with the string?

(powermock is not the option. it was using powermock and after update the mockito to 3.8.0 and powermock to 2.0.9, it starts to get a lot errors, and was suggested to replace the powermock with mockito-inline.)

**Comment by lannyf77** [comment]
was not using the right mock, this one works, not sure if there is better one
```
try (MockedStatic<Log> logMock = Mockito.mockStatic(Log.class)) {

            // test
            Util.handleIntent(intent, "theTag", "+++TEST1");
            logMock.verify(() -> Log.i(eq("theTag"), eq("+++TEST1"), times(1));

        }
```

**Comment by TimvdLippe** [comment]
Closing per the above comment.
