### ISSUE TITLE
Add ability to cleanly stub/verify overloaded methods

### ISSUE THREAD

**Issue by jhale1805** [mockito/mockito#2350]
## Current Limitation
In the current version of Mockito (3.11.2 at the time of writing), I'm not finding a good way to stub or verify overloaded methods.

Consider the following class:
```java
class Foo {

  int bar(boolean setting) { ... };
  int bar(boolean setting, int otherSetting) { ... };

}
```

If I wanted to stub an invocation of *either* `bar()` method, I currently have to stub *both* versions of the method independently.
Similarly, if I wanted to verify that *either* of the `bar()` methods had been called, I'd have to verify each one independently.

[This StackOverflow post](https://stackoverflow.com/q/46038220/14765128) illustrates the difficulty of finding a good workaround for this use case.

## Impact
- Tests become cluttered with multiple stubs/verifications, obscuring the primary purpose of the test.
- The removal of an overloaded method breaks all tests that stub/verify that method.
- The addition of an overloaded method creates the potential for uncaught errors in tests that stub/verify the existing overloaded methods.

## Possible Solutions
- Add an optional String parameter to the `when()` and `verify()` methods that will identify the overloaded method to stub/verify. 
     - As of yet I've never used Java's Reflection API, but a quick search inclines me to think this functionality could be powered by iterating through [Class.getDeclaredMethods()](https://docs.oracle.com/javase/8/docs/api/java/lang/Class.html#i25) and checking each `Method` object's [getName()](https://docs.oracle.com/javase/8/docs/api/java/lang/reflect/Method.html#i11) to identify which methods should be stubbed.
```java
Foo mockFoo = mock(Foo.class);

// Proposed format
verify(mockFoo, never(), 'bar');  

// This would be equivalent to the following, but would still work 
// if `bar(String)` were added or `bar(boolean)` were removed.
verify(mockFoo, never()).bar(anyBoolean());
verify(mockFoo, never()).bar(anyBoolean(), anyInt());
```

- Create a version of an ArgumentMatcher that can match all versions of an overloaded method.
```java
Foo mockFoo = mock(Foo.class);

// Proposed format
when(mockFoo.bar(anyArgs()).thenReturn(42);   // `anyArgs()` returns the proposed ArgumentMatcher.

// This would be equivalent to the following, but would still work 
// if `bar(String)` were added or `bar(boolean)` were removed.
when(mockFoo.bar(anyBoolean())).thenReturn(42);
when(mockFoo.bar(anyBoolean(), anyInt())).thenReturn(42);
```

## Forseen Complications
- When stubbing overloaded methods with different return types, how would Mockito reconcile a valid value to return?
- The first "Possible Solution" can't be updated automatically when someone refactors a method name via his/her IDE.
- If using the first "Possible Solution", what happens if the given string doesn't match any method on the mock object?

**Comment by EugeneLesnov** [comment]
Hi, @jhale1805 
This variant looks fine enough:

`Mockito.verify(mock, Mockito.never(), "methodName");`

If the given method name string doesn't match any method on the mock, an exception will be thrown… Something like `java.lang.NoSuchMethodException` which feels fair.

@TimvdLippe please, take a look at this issue. It seems useful from my point of view.

**Comment by TimvdLippe** [comment]
I don't think we should do this. Even though overloaded methods use the same name, it is important to know which one was called. From a JVM-perspective, these methods are distinct. It's only to a human that they mean the same thing, but in reality they could have vastly different behavior.

Sadly, this is how overloaded methods are implemented on the JVM and I don't think we should deviate from this. Additionally, using strings to refer to methods without any compile time guarantee will invariably lead to code changes in the future that will break (if you rename the method, etc...).

For overloaded methods, I did an investigation if we can design an alternative API to more cleanly handle this use case (#1264), but the conclusion is that currently on the JVM that is not possible (without even more hacks).

That is to say, while I acknowledge that the overloaded methods might have a special meaning in your application, from a JVM (and thus Mockito perspective), it is going to be difficult to build compatibility for that. Therefore, I am closing this as wont fix, sorry 😢
