### ISSUE TITLE
Apply @CheckReturnValue more aggressively

### ISSUE THREAD

**Issue by kluever** [mockito/mockito#2363]
Mockito has a local copy of [`@CheckReturnValue`](https://github.com/mockito/mockito/blob/main/src/main/java/org/mockito/CheckReturnValue.java) (presumably to avoid a dependency on [errorprone](https://github.com/google/error-prone), but it's only used on a few APIs.  There's a _lot_ of additional APIs that it could be applied to, an in fact the best solution is often to annotate entire classes (and then opt-out specific APIs) or entire packages (via `package-info.java`).

Top APIs to add `@CheckReturnValue` to:
* `org.mockito.ArgumentMatchers`
* `org.mockito.ArgumentCaptor`
* `org.mockito.Mockito`
* `org.mockito.stubbing.Stubber`

**Comment by TimvdLippe** [comment]
Just to double-check that I understand the behavior of `@CheckReturnValue`. If we were to add it to `org.mockito.Mockito`, it can automatically ignore any method that returns `void`?

**Comment by kluever** [comment]
Indeed, it only affects non-void methods. Additionally, it's often easier to add it to the class, and if there are methods where it is _OK_ to ignore the return value, then those methods would be marked with `@CanIgnoreReturnValue`.
