### ISSUE TITLE
how to solve gradle sync failed after 'Add basic Android instrumented and unit tests'

### ISSUE THREAD

**Issue by chaehwanli** [mockito/mockito#2378]
Hello

I got gradle sync fail with 'Add basic Android instrumented and unit tests'(#2360).

> This version of the Android Support plugin for IntelliJ IDEA (or Android Studio) cannot open this project, please retry with version 4.2 or newer.

I think that it is caused with below.

build.gradle
> classpath 'com.android.tools.build:gradle:4.2.1' 

the downgrading of gradle version is needed but I'm not sure it is proper...
> classpath 'com.android.tools.build:gradle:4.1.2'

Regards

**Comment by TimvdLippe** [comment]
Yes, I ran into the same issue. Fix is up at #2380 Apologies for the breakage!
