### ISSUE TITLE
mockStatic does not support static native methods

### ISSUE THREAD

**Issue by nadernader99** [mockito/mockito#2391]
### Issue Summary 

 Mockito is failing with 'MissingMethodInvocationException' while attempting to mock a class with static native methods. The class and unit test below will reproduce the issue. I am only able to mock either static methods with Mockito.mockStatic() or native methods with standard Mockito.mock(), but not methods that are both native and static.

### Mockito Error Message

org.mockito.exceptions.misusing.MissingMethodInvocationException: 
when() requires an argument which has to be 'a method call on a mock'.
For example:
    when(mock.getArticles()).thenReturn(articles);

Also, this error might show up because:
1. you stub either of: final/private/equals()/hashCode() methods.
   Those methods *cannot* be stubbed/verified.
   Mocking methods declared on non-public parent classes is not supported.
2. inside when() you don't call method on mock but on some other object.

### Code to Reproduce Issue

```
public class StaticStuff {

    public static native String nativeStaticNoParams();
    
}
```

```
    @Test
    public void testMockingStaticMethodWithoutParameters() {

        try(MockedStatic<StaticStuff> attic = Mockito.mockStatic(StaticStuff.class)) {

            attic.when(StaticStuff::nativeStaticNoParams).thenReturn("BAR");
            assertThat(StaticStuff.nativeStaticNoParams()).isEqualTo("BAR");
        }
    }
```
### Version Info

Mockito Core and Inline version: 3.11.2
Java version: 15.0.2. 
OS version: Windows 10 - build 19043.1165

**Comment by shreelakshmijoshi** [comment]
Hi @nadernader99 ! 
I am a new open source contributor and would like to know more about the issue, could you please provide some extra references to help me understand this better ?

**Comment by nadernader99** [comment]
Mockito.mockStatic() uses [net.asm.bytebuddy.Advice](https://github.com/raphw/byte-buddy/blob/3d94c344e6224b1c1058caf1068fa60e12a95414/byte-buddy-dep/src/main/java/net/bytebuddy/asm/Advice.java#L160) to wrap static methods with method exit and enter advice that will provide the mockito intercept behavoir. This retransformation/redefine of the class occurs within [InlineDelegateByteBuddyMockMaker.createStaticMock()](https://github.com/mockito/mockito/blob/b04c7039031c170dae5f90acb3ec74c16289886f/src/main/java/org/mockito/internal/creation/bytebuddy/InlineDelegateByteBuddyMockMaker.java#L562). This call redefines the mocked class methods with [InlineBytecodeGenerator.transform()](https://github.com/mockito/mockito/blob/b04c7039031c170dae5f90acb3ec74c16289886f/src/main/java/org/mockito/internal/creation/bytebuddy/InlineBytecodeGenerator.java#L393). This results in applying the advice by wrapping each method in bytebuddy's [Advice.wrap()](https://github.com/raphw/byte-buddy/blob/3d94c344e6224b1c1058caf1068fa60e12a95414/byte-buddy-dep/src/main/java/net/bytebuddy/asm/Advice.java#L508) method.

The draw back of this design is that it does not wrap native or abstract methods. This is documented as expected behavior for the bytebuddy Advice class. An enhancement to support static native methods would need to also apply an additional transform to replace static native methods with mockito interceptors.

For my project, I require a third-party library that relies heavily on static native methods. These native methods access compute intensive system resources, making them very problematic for testing. I have created my own light-weight mocking implementation using bytebuddy retransformation. I was successful in intercepting all static native methods, and replacing their behavoir with a simple default stub return value. Ideally, the Mockito.staticMock() would support this, but with all the advanced behavior customization and verification that is Mockito's strength.

If it would be useful, I can provide example code for the static native mocking that I have implemented.

**Comment by nadernader99** [comment]
Doing more testing, I have discovered that adding the mockito-inline dependency _also_ breaks native method mocking for regular not static methods.  So this issue goes beyond mockStatic, and is associated with mockito-inline.

The following is a test which mocks a native class from ffmpeg-platorm, a bytedeco native framework:

```
import org.bytedeco.ffmpeg.avutil.AVFrame;
import org.junit.Test;
import org.mockito.Mockito;

import static junit.framework.TestCase.assertEquals;
import static org.mockito.Mockito.when;

public class MockitoNativeTest {

    @Test
    public void canMockAVFrame() {

        AVFrame mock = Mockito.mock(AVFrame.class);

        when(mock.pts()).thenReturn(123L);

        assertEquals(123L, mock.pts());
    }
}
```

AVFrame.pts() is a non-static native method. When this test is built with _only_ the mockito-core depenency, it passes. When this test is built with the mocktio-core _and_ mockito-inline dependencies, if fails on the 'when(mock.pts())...' line, which invokes the real native method instead of setting up the mock.  I believe this is for the same reason that static native methods fail in mockito-inline. It uses a different strategy, leveraging bytebuddy Advice, which does not handle native methods.

Should I modify the title of this issue to indicate that mockito-inline does not support native mocking for both static and non-static methods?

It would be great to make progress on this issue while mockito-inline is still incubating. Would it be helpful to contribute a native code test suite? These can be challenging to write because they require c/c++ and JNI coding. I would recommend created a bytedeco base project with simple set of native interface classes. This is something I could contribute if there was a limited set of build platforms in which these tests are expected to run.

**Comment by TimvdLippe** [comment]
Unfortunately, one of the limitations of `mockito-inline` is the inability to mock native methods. This is documented on our website: https://javadoc.io/doc/org.mockito/mockito-core/latest/org/mockito/Mockito.html#39

One workaround is to wrap the method invocation into a non-native method and you stub that method out. However, I don't think it is possible to implement support for mocking these methods (@raphw can ultimately confirm). Therefore, I am closing this as "Infeasible" for now and as documented on our website. That said, if we can workaround the limitation, that would be grand of course!
