### ISSUE TITLE
Regression with InOrder verification after #2369

### ISSUE THREAD

**Issue by cushon** [mockito/mockito#2394]
The following test starts failing after https://github.com/mockito/mockito/commit/123beb8311ed6303ba71d682cff8434fe36b7f0f. It looks like the change to call actual `equals` and `hashCode` methods is catching a call to `equals` inside the implementation of `InOrder`.

```java
package com.test;

import static org.mockito.Mockito.inOrder;
import static org.mockito.Mockito.spy;

import org.junit.Test;
import org.mockito.InOrder;

public class AppTest {

  static class Foo {
    void foo() {}
  }

  @Test
  public void test() {
    Foo mock1 = spy(new Foo());
    Foo mock2 = spy(new Foo());
    mock1.foo();
    InOrder order = inOrder(mock1, mock2);
    order.verify(mock1).foo();
    order.verifyNoMoreInteractions();
  }
}
```

```
No interactions wanted here:
-> at com.test.AppTest.test(AppTest.java:22)
But found this interaction on mock 'foo':
-> at java.base/java.util.LinkedList.indexOf(LinkedList.java:609)
	at com.test.AppTest.test(AppTest.java:22)
```

**Comment by smcvb** [comment]
I am experiencing a similar issue after upgrading to version 3.12.0.
More specifically, the `AnnotatedSagaRepositoryTest#testLoadedFromNestedUnitOfWorkAfterCreateAndStore` test (found [here](https://github.com/AxonFramework/AxonFramework/blob/2eeacc4e225d0f3739b0c7d4e4ba37358795407c/modelling/src/test/java/org/axonframework/modelling/saga/repository/AnnotatedSagaRepositoryTest.java#L91)) has started failing, and it follows a similar pattern as described by @cushon.
You can find the failing issue in the GitHub Actions under Axon Framework issue [#1913](https://github.com/AxonFramework/AxonFramework/pull/1913).

**Comment by TimvdLippe** [comment]
Thanks for reporting! Taking a look now to figure out what is going on here.

**Comment by TimvdLippe** [comment]
Fix up at #2395

**Comment by TimvdLippe** [comment]
3.12.1 is currently being pushed to Maven Central. It should be available in a couple of hours.

**Comment by smcvb** [comment]
Thanks for the quick fix here, @TimvdLippe. I can confirm that 3.12.1 solved the aforementioned problem for Axon Framework.
