### ISSUE TITLE
Some VerificationModes don't have a toString implementation.

### ISSUE THREAD

**Issue by LeMikaelF** [mockito/mockito#2412]
Some user-facing VerificationModes don't have a `toString()` implementation. This includes:

- `AtMost`
- `Only`
- `After`
- `Timeout`

I ran into this issue while using Mockito with a proprietary [Jasmine](https://jasmine.github.io/)-like library for JUnit. Here is a short example written with JUnit and the open-source runner [Oleaster](https://github.com/mscharhag/oleaster):

```
@RunWith(OleasterRunner.class)
public class DemoTest {

    private MyClass myClass;

    {
        describe("demo", () -> {

            beforeEach(() -> {
                myClass = Mockito.mock(MyClass.class);
                myClass.myMethod();
            });

            verifyMyMethodCalled(atLeast(1));
            verifyMyMethodCalled(atMost(1));
            verifyMyMethodCalled(only());
            verifyMyMethodCalled(after(1));
        });
    }

    private void verifyMyMethodCalled(VerificationMode verificationMode) {
        it(String.format("should call myMethod. %s", verificationMode), () -> {
            verify(myClass, verificationMode).myMethod();
        });
    }
}
```

Extracting the assertion and the test-naming part to a specific method (`verifyMyMethodCalled(VerificationMode verificationMode)`) saves a lot of boilerplate and helps with maintainability, especially since a real-life test class will most likely be longer than this example. However, the following screenshot shows why the last 3 verificationModes aren't so helpful without a proper `toString()` method:

![image](https://user-images.githubusercontent.com/22927506/131226758-72a58f27-c1fb-44e2-8db2-70ab5476c7f5.png)

I fixed this, in my use case, this by extending the offending `VerificationMode` in a custom factory method:
```
private static VerificationMode atMost(int times) {
    return new AtMost(times) {
        @Override
        public void verify(VerificationData data) {
            super.verify(data);
        }

        @Override
        public String toString() {
            return "Wanted invocations count: at most " + times;
        }
    };
}
```
This quickly becomes cumbersome however, if you want to do it for multiple `VerificationMode`s or in multiple projects. Since most user-facing `VerificationMode`s already have a `toString()` method (e.g. `atLeast` in my example), the missing `toString()` methods could be included in Mockito.

I have a PR that is almost ready for this, and would gladly submit it.

EDIT: added `Timeout` to the list.

**Comment by TimvdLippe** [comment]
> I have a PR that is almost ready for this, and would gladly submit it.

Yes that seems good to me, looking forward to it!
