### ISSUE TITLE
When Java files are converted to Kotlin - Mockito test fails with org.mockito.exceptions.misusing.UnfinishedVerificationException

### ISSUE THREAD

**Issue by snijsure** [mockito/mockito#2416]
I am currently using Mockito 3.12.4.

I have seen that Android tests that use ```@RunWith(AndroidJUnit4::class)``` have suddenly stopped running and they fail with error

org.mockito.exceptions.misusing.UnfinishedVerificationException: 
Missing method call for verify(mock) here:
-> at XXXX.methodName(...)

Example of correct verification:
    verify(mock).doSomething()

Also, this error might show up because you verify either of: final/private/equals()/hashCode() methods.
Those methods *cannot* be stubbed/verified.
Mocking methods declared on non-public parent classes is not supported.

All the Kotlin classes are marked as "open", but I still get the above error!! Is there a specific version of JRunner / AndroidRunner I should be using?

**Comment by TimvdLippe** [comment]
Please use https://github.com/mockito/mockito-kotlin for Kotlin tests.
