### ISSUE TITLE
Roadmap for Mockito.MockedStatic<T>

### ISSUE THREAD

**Issue by sfc-gh-vparaschiv** [mockito/mockito#2433]
Hello.

What is the current roadmap for [`Mockito.MockedStatic<T>`](https://github.com/mockito/mockito/blob/caf35b24e2764df0498469526ecb3e7ec68a0430/src/main/java/org/mockito/MockedStatic.java#L27)?

Is it feature complete, or there are new features planned for it? Any other changes expected, before graduating?

How stable is the current implementation?

When is it expected for it to graduate out of incubation? Will it ever?

What work should be done and in general what else needs to happen to reach that? Maybe the community can help with that work. 

Thanks a lot for your open-source contributions!
--Vasile

---

_P.S. Don't know if these questions should be answered by @raphw, who seems to be the author of `Mockito.MockedStatic<T>` based on github history, or somebody else._

**Comment by raphw** [comment]
They are stable but we did not know that they covered all cases appropriately when we released the mock maker. I do not personally think that we need further changes and I consider them as safe to use. We just discussed this internally and I think it is likely that we simply remove the annotations from any API that we consider stable.

**Comment by sfc-gh-vparaschiv** [comment]
> They are stable but we did not know that they covered all cases appropriately when we released the mock maker. I do not personally think that we need further changes and I consider them as safe to use. We just discussed this internally and I think it is likely that we simply remove the annotations from any API that we consider stable.

@raphw, thanks a bunch for your prompt response.

Ball-pack wise, would you expect that to happen in days, weeks, or months?

o( _ _ )o

**Comment by raphw** [comment]
I'd say weeks, but the decision seems pretty solid so I would not worry about the annotation still being present.

**Comment by TimvdLippe** [comment]
Yeah I will prepare a PR this week to promote all incubating APIs to stable, included in Mockito 4.0.
