### ISSUE TITLE
StackOverflowError in MockitoSerializationIssue.java

### ISSUE THREAD

**Issue by fluentfuture** [mockito/mockito#244]
In MockitoSerializationIssue.filterStackTrace(), it calls ```filter.filter(this)```, which then calls getStackTrace() again, causing an infinite recursion.

**Comment by szczepiq** [comment]
Well spotted. We'll fix it. Any chance for PR?

**Comment by fluentfuture** [comment]
Sorry I should really have sent a PR with the bug report.

I'm recently pretty swamped. Spent a day and an evening trying to upgrade Mockito (thought it was a low-hanging fruit) but then had to draw the line because fixing all the breakage in Google's codebase had started to look like a sizable project.

**Comment by szczepiq** [comment]
Thanks a lot for the reports. This is great stuff. Thank you for pushing
mockito upgrade at G. This helps a lot because you have already fleshed out
a couple of bugs.

**Comment by bric3** [comment]
Closed via 817b04b
