### ISSUE TITLE
when I use @InjectMocks with @Spy Annotation together  I get a question 

### ISSUE THREAD

**Issue by bailingxuanyi** [mockito/mockito#2459]
Thanks for you provide mocktio plugin First

I want to use mockito 4.0 to test full link code in my business scene 
so I find a strange situation when I initialize this testing instance using @InjectMocks with @Spy annotation together 

show example code 

  public class Test1 {
            @Rule
            public MockitoRule rule = MockitoJunit.rule();

            @InjectMocks
            AControllor aController;

            @InjectMocks
            @Spy
            AServiceImpl aService;

            @Mock
            AMapper aMapper;
     }

 AServiceImpl 's  instance can be created in Test1 's instance  but  if Test1 class not extends any SuperClass ,  In AControllor 's object , this instance (aService) is always null point ,   AServiceImpl 's instance can not be injected in AControllor's instance ;

Except in the following case

   public class Base {
          @Rule
          public MockitoRule rule = MockitoJunit.rule();
      }

  public class Test1 extends Base {
          @InjectMocks
          AControllor aController;
  
          @InjectMocks
          @Spy
          AServiceImpl aService;
  
          @Mock
          AMapper aMapper;
      }

if I  write that Test1 class extends Base class , AServiceImpl 's instance can be injected in AControllor's instance 

I see mockito 4.0 source code , SpyAnnotationEngine class  [56, 57] line

SpyAnnotationEngine create spy instance not be allowed  with @InjectMocks annotation （Why does author write that ）
so spy instance init at last if I use @spy and @injectmocks together, DefaultInjectionEngine [25] handleSpyAnnotation 

----------------------

在这里非常感谢作者提供的mockito 4.0这个工具
我在使用这个工具时候遇到了一个问题，我使用场景是期望对我的整个业务链路代码的进行单元化测试，这时候就希望把
Controller, Service ,Dao 整个链路的代码串联起来进行测试，于是我就发现上面这个问题，如果Test1这个类不继承任何的
类的话，像上面这种写法AServiceImpl对象是不会被注入到 AControllor 里的，虽然我已经用@Spy注解进行标识了，具体
原因我查看了mocktio4.0的源码，发现在SpyAnnotationEngine 56，57行有if语句判断，
 MemberAccessor accessor = Plugins.getMemberAccessor();
        for (Field field : fields) {
            if (field.isAnnotationPresent(Spy.class)
                    && !field.isAnnotationPresent(InjectMocks.class)) {

如果存在@InjectMocks注解就不初始化这个实例了，我尝试着把这个判断（!field.isAnnotationPresent(InjectMocks.class)）去掉，这时候程序运行看起来没有问题了，这里我就很疑惑，为什么作者这里会这样写，这样会导致@Spy和@Injectmocks的一起使用这两个注解的对象初始化的阶段发生变更，在DefaultInjectionEngine [25]行代码才会进行初始化，于是就出现了上面这种情况, 如果Test1继承了Base这个类，aService这个对象就能注入到aController里面，否则则不成功

**Comment by temp-droid** [comment]
Hi @bailingxuanyi , it is explained in the javadoc of `SpyAnnotationEngine`:

>  * If the field is also annotated with the <strong>compatible</strong> &#64;InjectMocks then the field will be ignored,
> * The injection engine will handle this specific case.

https://github.com/mockito/mockito/blob/main/src/main/java/org/mockito/internal/configuration/SpyAnnotationEngine.java#L43

One solution in your case is to create the spy manually, instead of using the annotation.
You could for example do:

```java
@ExtendWith(MockitoExtension.class)
class AControllerTest {

  @InjectMocks
  private AController aController;

  @InjectMocks
  private AService aService = spy(AService.class);

  @Test
  void test() {
    // when
    aController.aMethod();
    // then
    verify(aService).aMethod();
  }
}
```
Another solution would be to mock your `AServiceImpl` class to avoid dealing with its dependencies.
And the last solution I can think of is to do the dependency injection yourself. `@InjectMocks` is not supposed to handle all cases, only help reduce boilerplate when possible.

**Comment by TimvdLippe** [comment]
Thanks for the response @temp-droid! Closing this issue as such. If you have any further questions, please post on StackOverflow: https://stackoverflow.com/questions/tagged/mockito
