### ISSUE TITLE
Clarify Javadoc of RETURNS_SMART_NULLS, default answer in Mockito 4.0.0?

### ISSUE THREAD

**Issue by flyaway2112** [mockito/mockito#2460]
[Javadoc for Mockito.RETURNS_SMART_NULLS](https://www.javadoc.io/doc/org.mockito/mockito-core/latest/org/mockito/Mockito.html#RETURNS_SMART_NULLS) in version 4.0.0 still says:

> ReturnsSmartNulls will be probably the default return values strategy in Mockito 4.0.0

As Mockito 4.0.0 has been released this could now be clarified. I see #971 is still open, so it looks like the default answer has not been changed?

See also: https://github.com/mockito/mockito/issues/1743

**Comment by TimvdLippe** [comment]
Hm. Yeah. In retrospect, I think it is better to remove this statement altogether. As far as I know, we are not planning on making this change anytime soon and therefore I also think it doesn't make sense to commit to a particular version.

Do you mind sending us a PR that removes the sentence?
