### ISSUE TITLE
Mockito.spy on FileChannel fails on Java 17

### ISSUE THREAD

**Issue by jamesmudd** [mockito/mockito#2465]
When updating my projects to run on Java 17 I came across this issue. Here is some example code to reproduce it
```
import org.mockito.Mockito;
import java.io.IOException;
import java.nio.channels.FileChannel;
import java.nio.file.Files;
import java.nio.file.StandardOpenOption;

class Scratch {
	public static void main(String[] args) throws IOException {
		FileChannel fileChannel = FileChannel.open(Files.createTempFile("test", "txt"), StandardOpenOption.WRITE);
		Mockito.spy(fileChannel);
	}
}
```
When this code is executed on Java 11 it runs but on Java 17 it fails with this error
```
Exception in thread "main" org.mockito.exceptions.base.MockitoException: 
Mockito cannot mock this class: class sun.nio.ch.FileChannelImpl.

Mockito can only mock non-private & non-final classes.
If you're not sure why you're getting this error, please report to the mailing list.


Java               : 17
JVM vendor name    : Oracle Corporation
JVM vendor version : 17.0.1+12-39
JVM name           : OpenJDK 64-Bit Server VM
JVM version        : 17.0.1+12-39
JVM info           : mixed mode, sharing
OS name            : Linux
OS version         : 5.11.0-38-generic


Underlying exception : org.mockito.exceptions.base.MockitoException: 
Cannot adjust module graph for modules in the bootstrap loader

class sun.nio.ch.FileChannelImpl is declared by the bootstrap loader and cannot be adjusted
Requires package export to class org.mockito.codegen.InjectionBase: true
Requires adjusted reading of class org.mockito.codegen.InjectionBase: false
	at java.base/java.util.Optional.orElseGet(Optional.java:364)
	at io.jhdf.Scratch.main(scratch_6.java:13)
Caused by: org.mockito.exceptions.base.MockitoException: 
Cannot adjust module graph for modules in the bootstrap loader

class sun.nio.ch.FileChannelImpl is declared by the bootstrap loader and cannot be adjusted
Requires package export to class org.mockito.codegen.InjectionBase: true
Requires adjusted reading of class org.mockito.codegen.InjectionBase: false
	at net.bytebuddy.TypeCache.findOrInsert(TypeCache.java:153)
	at net.bytebuddy.TypeCache$WithInlineExpunction.findOrInsert(TypeCache.java:366)
	at net.bytebuddy.TypeCache.findOrInsert(TypeCache.java:175)
Connected to the target VM, address: '127.0.0.1:37353', transport: 'socket'
	at net.bytebuddy.TypeCache$WithInlineExpunction.findOrInsert(TypeCache.java:377)
	... 2 more
```
`FileChannel` is a public, non-final class. So i'm assuming this issue is something to do with tighter encapsulation of JVM internals. It is possible to extend `FileChannel` yourself so i'm not clear this is really the issue either. Would be great to get your thoughts. For context in the real case the spy is used to verify lazy loading of parts of the file.

**Comment by temp-droid** [comment]
Hi @jamesmudd , I think the issue comes from `sun.nio.ch.FileChannelImpl` which is used as implementation for the `FileChannel` abstract class.

In JDK11 the package containing `FileChannelImpl` is [not exported](https://github.com/AdoptOpenJDK/openjdk-jdk11/blob/master/src/java.base/share/classes/module-info.java#L242) by their `module-info.java`. It is highly possible JDK17 made it even less permissive and you can't access it anymore.

**Comment by temp-droid** [comment]
I cannot reproduce on Windows 10 with
```
openjdk version "17" 2021-09-14
OpenJDK Runtime Environment (build 17+35-2724)
OpenJDK 64-Bit Server VM (build 17+35-2724, mixed mode, sharing)
```
nor
```
openjdk version "17.0.1" 2021-10-19
OpenJDK Runtime Environment (build 17.0.1+12-39)
OpenJDK 64-Bit Server VM (build 17.0.1+12-39, mixed mode, sharing)
```
with
```
<dependency>
    <groupId>org.mockito</groupId>
    <artifactId>mockito-inline</artifactId>
    <version>4.0.0</version>
</dependency>
<dependency>
    <groupId>org.mockito</groupId>
    <artifactId>mockito-junit-jupiter</artifactId>
    <version>4.0.0</version>
</dependency>
```

@jamesmudd : can you tell us which `mockito` dependencies you are using? Or zipping/pushing the project where you can reproduce it?
And trying with `mockito-inline:4.0.0` if you don't use it already?

**Comment by jamesmudd** [comment]
Your right I was using `mockito-core:4.0.0` switching to `mockito-inline:4.0.0` does fix this example code. My actual tests still fail but think that seems to be a difference in the interactions verified. I will have more  of a look at that.. Would you expect the inline version to be a drop in replacement?

**Comment by temp-droid** [comment]
> Would you expect the inline version to be a drop in replacement?

From Mockito javadoc:

> As a convenience, the Mockito team provides an artifact where this mock maker is preconfigured. Instead of using the mockito-core artifact, include the mockito-inline artifact in your project. Note that this artifact is likely to be discontinued once mocking of final classes and methods gets integrated into the default mock maker.

https://javadoc.io/doc/org.mockito/mockito-core/latest/org/mockito/Mockito.html#39

I hope this does answer your question.

**Comment by jamesmudd** [comment]
Thanks. I have rewritten the test too use mocking not spy and it now works on java 17. It works both with core and inline.
