### ISSUE TITLE
Cannot stub hashcode

### ISSUE THREAD

**Issue by cdalexndr** [mockito/mockito#2476]
The following test fails:
```
   @Test
    public void test() {
        Object obj = Mockito.mock(Object.class);
        doReturn(1).when(obj).hashCode();
        assertEquals(obj.hashCode(), 1);
    }
```

mockito 3.12.4, jdk zulu-11, win10

check that

 - [x] The mockito message in the stacktrace have useful information, but it didn't help
 - [x] The problematic code (if that's possible) is copied here;
 - [x] Provide versions (mockito / jdk / os / any other relevant information)
 - [x] Provide a [Short, Self Contained, Correct (Compilable), Example](http://sscce.org) of the issue
       (same as any question on stackoverflow.com)
 - [x] Read the [contributing guide](https://github.com/mockito/mockito/blob/main/.github/CONTRIBUTING.md)

**Comment by temp-droid** [comment]
Hi @cdalexndr , Mockito is not able to stub the `hashCode` method.
If I modify your example to:
```java
Object obj = Mockito.mock(Object.class);
when(obj.hashCode()).thenReturn(1);
assertEquals(obj.hashCode(), 1);
```
the error displayed tells you about it:
```
org.mockito.exceptions.misusing.MissingMethodInvocationException: 
when() requires an argument which has to be 'a method call on a mock'.
For example:
    when(mock.getArticles()).thenReturn(articles);

Also, this error might show up because:
1. you stub either of: final/private/equals()/hashCode() methods.
   Those methods *cannot* be stubbed/verified.
   Mocking methods declared on non-public parent classes is not supported.
[...]
```

**Comment by TimvdLippe** [comment]
Thanks @temp-droid for the response. Completely correct 😄 Closing as such.
