### ISSUE TITLE
push cglib into a separate jar

### ISSUE THREAD

**Issue by szczepiq** [mockito/mockito#248]
Since the default MockMaker / class proxy engine is based on ByteBuddy there is no point in shipping mockito with cglib based MockMaker. This guarantees clean codebase and prevents users from depending on cglib.

If there is need, we will support cglib MockMaker as an external jar. MockMaker is a pluggable mechanism in Mockito to allow different class proxy makers (used in android).

**Comment by thekingnothing** [comment]
Powermock still depends on `CglibMockMaker`, so users how want use Powermock with Mockito need this Jar in Maven repository. Are you going to put it in Maven Central?

**Comment by raphw** [comment]
Powermock needs to update at some point but as I understand it, the cglib mock maker will be published as a seperate artifcat.

**Comment by bric3** [comment]
Powermock already has some internal mockito classes repackaged, maybe @johanhaleby could be interested to have all the cglib mockmaker repackaged on the Powermock side until it is updated to work with Mockito and ByteBuddy.

**Comment by johanhaleby** [comment]
Yeah, I think that would probably be the easiest way forward. I personally won't have time to port powermock to non cglib in the near future.
