### ISSUE TITLE
Incomplete stack trace returned from spy inside another spy

### ISSUE THREAD

**Issue by holubec-petr** [mockito/mockito#2489]
Hi,

due to the fix of issue #2238, the returned stack trace is not complete when an exception is thrown from a spy inside another spy.
The problem appeared in released version 3.9.0 (specifically 3.8.14) and still exists in 4.1.0.

I wrote a unit test simulating this behavior:
https://github.com/holubec-petr/mockito/blob/stack_trace_clean_up/src/test/java/org/mockito/internal/creation/bytebuddy/InlineDelegateByteBuddyMockMakerTest.java#L272

Problem is that the method `MockMethodAdvice.hideRecursiveCall()` is too aggressive when removing stack trace frames.

Check that
 - [x] The mockito message in the stacktrace have useful information, but it didn't help
 - [x] The problematic code (if that's possible) is copied here;
       Note that some configuration are impossible to mock via Mockito
 - [x] Provide versions (mockito / jdk / os / any other relevant information)
 - [x] Provide a [Short, Self Contained, Correct (Compilable), Example](http://sscce.org) of the issue
       (same as any question on stackoverflow.com)
 - [x] Read the [contributing guide](https://github.com/mockito/mockito/blob/main/.github/CONTRIBUTING.md)

**Comment by TimvdLippe** [comment]
Do you mind sending us a PR with the regression test and a corresponding fix? That would be awesome 🎉

**Comment by holubec-petr** [comment]
I'm thinking about some fix the last few days and I don't know if I'll be able to provide any generic-enough fix.

Maybe that's just my lack of knowledge of why is this stack trace cleaning implemented and what frames exactly we want to remove.

For example, this unit test:
https://github.com/mockito/mockito/blob/main/src/test/java/org/mockito/internal/creation/bytebuddy/InlineDelegateByteBuddyMockMakerTest.java#L270
Why exactly those 3 elements should remain in stack trace after cleaning?
