### ISSUE TITLE
How to Spy a String

### ISSUE THREAD

**Issue by vhshemanth** [mockito/mockito#2502]
Lets us consider a class
Class Sample{
@value(${value})
String value;

@autowired
Service service;
}

How can I get the actual value of String value while using the test as follows
Class SampleTest{
@injectmocks
Sample sample;

@spy
Service service;
}

How can I get the actual value of the string ? I cant use @spy for a string

**Comment by TimvdLippe** [comment]
It appears you are using Spring and Mockito together. It is better to ask for guidance on StackOverflow: https://stackoverflow.com/questions/tagged/mockito
