### ISSUE TITLE
Possible memory leak MockMethodDispatcher

### ISSUE THREAD

**Issue by ericntd** [mockito/mockito#2503]
There's definitely memory leak in our unit tests
It's happening in a lot of tests, not some specific tests
<img width="1203" alt="memory leak with CmbSyncRunnableTest" src="https://user-images.githubusercontent.com/19919208/145238983-fe415eb9-fb99-406b-94bf-409bfe93859c.png">

I took a heap dump and analyzed it with Eclipse Memory Analyzer
The following came out as the 2nd leak suspect
```
Class Name | Shallow Heap | Retained Heap
-- | -- | --
java.util.concurrent.ConcurrentHashMap$Node[128] @ 0x7abc89f10 | 528 | 18,432,792
table java.util.concurrent.ConcurrentHashMap @ 0x7a3eeaa38 | 64 | 18,432,856
target org.mockito.internal.util.concurrent.WeakConcurrentMap$WithInlinedExpunction @ 0x7a3eeaa00 | 40 | 18,432,912
graphs org.mockito.internal.creation.bytebuddy.MockMethodAdvice @ 0x7a3eea9b8 | 48 | 18,433,032
val java.util.concurrent.ConcurrentHashMap$Node @ 0x7a3eea998 | 32 | 18,433,064
[14] java.util.concurrent.ConcurrentHashMap$Node[16] @ 0x7a3eea948 | 80 | 25,347,336
table java.util.concurrent.ConcurrentHashMap @ 0x7a2d05fe8 | 64 | 25,347,400
DISPATCHERS class org.mockito.internal.creation.bytebuddy.inject.MockMethodDispatcher @ 0x7a3036098 System Class | 8 | 25,348,288
```
![Mockito memory leak](https://user-images.githubusercontent.com/19919208/145238536-cb38777b-a616-4c36-96c3-aa22a004ff13.png)

Versions of jUnit and Mockito I'm using:
```
junit                    : "junit:junit:4.12",
        mockito                  : "org.mockito:mockito-core:2.24.5",
        mockito_android          : "org.mockito:mockito-android:2.24.5",
        mockito_inline           : "org.mockito:mockito-inline:3.9.0",
        mockito_kotlin           : "org.mockito.kotlin:mockito-kotlin:3.2.0",
```

Any advices to what I can do?

**Comment by TimvdLippe** [comment]
Can you try calling `MockitoFramework.clearInlineMocks()` as documented in https://javadoc.io/doc/org.mockito/mockito-core/latest/org/mockito/Mockito.html#47 and see if that resolves the issue?

**Comment by ericntd** [comment]
I will, thanks @TimvdLippe 
It will take me a considerable amount of time to apply it to all of my tests though
Will not be able to get back so soon as a result

**Comment by TimvdLippe** [comment]
Closing per above comment.
