### ISSUE TITLE
Remove `ExpectedException` from internal test suite

### ISSUE THREAD

**Issue by TimvdLippe** [mockito/mockito#2510]
The rule is not ideal, as it will trigger even if the test fails for a completely different reason. Instead, we should use `assertj` with `assertThatThrownBy` to denote which specific line should trigger the exception.

**Comment by TimvdLippe** [comment]
#2511 contains an example replacement. The expectation is that we do the same for all the other test suites we have lying around.

**Comment by temp-droid** [comment]
Should we include the existing `assertj` `assertThatThrownBy` cases to make them consistent with the use of lambda instead of runnable?

**Comment by TimvdLippe** [comment]
@temp-droid I don't think we need a dedication cleanup for that, but if you are changing a test that has runnables, then yes let's convert them to lambdas instead. Do you want to take on this task? Thanks in advance!

**Comment by temp-droid** [comment]
@TimvdLippe Do you want to remove `@Test(expected = […].class)` oriented tests too?

**Comment by TimvdLippe** [comment]
Yes to both of these, thanks!
