### ISSUE TITLE
Cannot mock static method

### ISSUE THREAD

**Issue by WilliamChen-luckbob** [mockito/mockito#2528]
Here is my code, it is simple:
```
public class FakeTokenUtil {
    public static String getToken(){
        return "123123123123";
    }
}
```
```
    @Test
    public void mockStatic() {
        MockedStatic<FakeTokenUtil> mock = Mockito.mockStatic(FakeTokenUtil.class);
        mock.when(FakeTokenUtil::getToken).thenReturn("666666");
        System.out.println(FakeTokenUtil.getToken());
    }
```

Here is my dependency.
It is higher than version 3.4.x but I still not able to mock a static method !
```
            <dependency>
                <groupId>org.mockito</groupId>
                <artifactId>mockito-core</artifactId>
                <version>3.12.4</version>
                <scope>test</scope>
            </dependency>
            <dependency>
                <groupId>org.mockito</groupId>
                <artifactId>mockito-inline</artifactId>
                <version>3.12.4</version>
                <scope>test</scope>
            </dependency>
```
Then I received an exception told me to use mockito-inline...
```
org.mockito.exceptions.base.MockitoException: 
The used MockMaker SubclassByteBuddyMockMaker does not support the creation of static mocks

Mockito's inline mock maker supports static mocks based on the Instrumentation API.
You can simply enable this mock mode, by placing the 'mockito-inline' artifact where you are currently using 'mockito-core'.
Note that Mockito's inline mock maker is not supported on Android.
```
I'm pretty sure that mockito-inline is imported to my application.

I've tried [this way](https://asolntsev.github.io/en/2020/07/11/mockito-static-methods/) to remove `mockito-core` and keep `mockito-inline` but found it impossible. In this way, IDEA cannot even resolve method `Mockito.mockStatic`.

Can anyone help me with this? Thanks a lot!

**Comment by WilliamChen-luckbob** [comment]
problem solved by [this method](https://javadoc.io/static/org.mockito/mockito-core/4.2.0/org/mockito/Mockito.html#39)

![9194cc66af4c63e9893d9ff1b8eee73](https://user-images.githubusercontent.com/58684828/147474332-9de87f30-836f-44c6-a213-e7684410b74b.png)
just adding a file like this to force turn on the inline mock mode
![image](https://user-images.githubusercontent.com/58684828/147474360-fd06b77a-6393-4745-9f75-94086d308480.png)

**Comment by FelicityAmiao** [comment]
My project is not maven project, instead by import jar by my self. 
I solved my problem by import mockito-inline jar as 'Classes', then can clear see the imported jar in idea's 'Extenal Libraries', which imported same as mockito-core jar.
![image](https://user-images.githubusercontent.com/40057410/221723397-31af17e9-44f7-4008-be21-a704ed3ba90a.png)
![image](https://user-images.githubusercontent.com/40057410/221723469-ea6acac6-ae73-4e6d-8c7c-7b8be9f40632.png)
