### ISSUE TITLE
Can't verify on synchronized methods of objects

### ISSUE THREAD

**Issue by bonifaido** [mockito/mockito#253]
Because they are holding the object's lock when verify(object).method() is called, so if another thread tries to call the method it can't.

**Comment by raphw** [comment]
Thanks for your pull request. The idea was good but I think this is easier to adress by extending Byte Buddy's API. I added a possibility to transform a method's modifier and adapted the changes: https://github.com/mockito/mockito/pull/257

Your test case should however be kept to avoid breaking this feature in the future!
