### ISSUE TITLE
NPE when calling await on a spied CyclicBarrier

### ISSUE THREAD

**Issue by cowclaw** [mockito/mockito#2540]
Hello, I think we found a regression in mockito.

Calling `await()` on a spy wrapped around a `CyclicBarrier` yields a `NullPointerException` starting with java 16.
While it works on jdk 11 to 15, I can reproduce the issue on jdk 16 and 17 (adoptopenjdk / adoptium temurin).  I tested mockito version 4.2.0 on an Ubuntu 20.04.3 LTS (kernel 5.4.0-91-generic)

Below is an example:

```java
import java.util.concurrent.CyclicBarrier;

import org.mockito.Mockito;

public class CyclicBarrierSpying {

	public static void main(String[] args) {
		try {
			CyclicBarrier cyclicBarrier = new CyclicBarrier(1);
			cyclicBarrier.await(); // works fine

			CyclicBarrier spy = Mockito.spy(cyclicBarrier);
			spy.await(); //throws java.lang.NullPointerException: Cannot invoke "java.util.concurrent.locks.ReentrantLock.lock()" because "lock" is null
		} catch (Exception e) {
			throw new RuntimeException(e);
		}
	}

}
```
stacktrace:

```
Exception in thread "main" java.lang.RuntimeException: java.lang.NullPointerException: Cannot invoke "java.util.concurrent.locks.ReentrantLock.lock()" because "lock" is null
	at CyclicBarrierSpying.main(CyclicBarrierSpying.java:15)
Caused by: java.lang.NullPointerException: Cannot invoke "java.util.concurrent.locks.ReentrantLock.lock()" because "lock" is null
Caused by: java.lang.NullPointerException: Cannot invoke "java.util.concurrent.locks.ReentrantLock.lock()" because "lock" is null

	at java.base/java.util.concurrent.CyclicBarrier.dowait(CyclicBarrier.java:203)
	at java.base/java.util.concurrent.CyclicBarrier.await(CyclicBarrier.java:362)
	at CyclicBarrierSpying.main(CyclicBarrierSpying.java:13)
```

See https://github.com/cowclaw/mockito-regression for a ready-to-run example.

I checked that:

 - [X] The mockito message in the stacktrace have useful information, but it didn't help
 - [X] The problematic code (if that's possible) is copied here;
       Note that some configuration are impossible to mock via Mockito
 - [X] Provide versions (mockito / jdk / os / any other relevant information)
 - [x] Provide a [Short, Self Contained, Correct (Compilable), Example](http://sscce.org) of the issue
       (same as any question on stackoverflow.com)

**Comment by temp-droid** [comment]
Hi @cowclaw ,

I tried to reproduce it but didn't succeed on my Windows 10 laptop. 
I tried with the following JDKs:

- Amazon Corretto version 16.0.2
- Eclipse Temurin 16.0.2
- Oracle OpenJDK 17
- Eclipse Temurin 17.0.1
- IBM JDK 17.0.1

I did get a warning though:
```
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.mockito.internal.util.reflection.ReflectionMemberAccessor (file:/C:/Users/XXX/.gradle/caches/modules-2/files-2.1/org.mockito/mockito-core/4.2.0/9f543564b680a7595176cd2c49c1b93863a2b8c2/mockito-core-4.2.0.jar) to field java.util.concurrent.CyclicBarrier.lock
WARNING: Please consider reporting this to the maintainers of org.mockito.internal.util.reflection.ReflectionMemberAccessor
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
```

**Comment by cowclaw** [comment]
@temp-droid thanks for trying.

@bwaldvogel set up a gitlab workflow including the aforementioned jdk versions showing that it does indeed not work for 16 and 17. See https://github.com/cowclaw/mockito-regression/actions/runs/1707661763

**Comment by TimvdLippe** [comment]
@ColdFireIce Does it work if you use `mockito-inline`?

**Comment by TimvdLippe** [comment]
Yes we recommend to use `mockito-inline` in this case, starting with Java 17. For more information, see #2589
