### ISSUE TITLE
task mockitoJavadoc fails when compiling in windows

### ISSUE THREAD

**Issue by mat013** [mockito/mockito#256]
When compiling the mockito project using gradle in a command line in Windows following compile error occurs:

javadoc: error - Illegal package name: "<script"
javadoc: error - Illegal package name: "type="
javadoc: error - Illegal package name: "text/javascript"
javadoc: error - Illegal package name: "src="
javadoc: error - Illegal package name: "{@docRoot}/js/jdk6-project-version-insert.js"
javadoc: error - Illegal package name: "></script>"
javadoc: error - Illegal package name: "<script"
javadoc: error - Illegal package name: "type="
javadoc: error - Illegal package name: "text/javascript"
javadoc: error - Illegal package name: "src="
javadoc: error - Illegal package name: "{@docRoot}/js/jquery-1.7.min.js"
javadoc: error - Illegal package name: "></script>"
javadoc: error - Illegal package name: "<script"
javadoc: error - Illegal package name: "type="
javadoc: error - Illegal package name: "text/javascript"
javadoc: error - Illegal package name: "src="
javadoc: error - Illegal package name: "{@docRoot}/js/highlight-8.6-java/highlight.pack.js"
javadoc: error - Illegal package name: "></script>"
javadoc: error - Illegal package name: "<link"
javadoc: error - Illegal package name: "rel="
javadoc: error - Illegal package name: "type="
javadoc: error - Illegal package name: "text/css"
javadoc: error - Illegal package name: "href="
javadoc: error - Illegal package name: "{@docRoot}/js/highlight-8.6-java/styles/obsidian.css"
javadoc: error - Illegal package name: "/>"
javadoc: error - Illegal package name: "<script"
javadoc: error - Illegal package name: "type="
javadoc: error - Illegal package name: "text/javascript"
javadoc: error - Illegal package name: ">"
javadoc: error - Illegal package name: "="
javadoc: error - Illegal package name: "&&"
javadoc: error - Illegal package name: "parseInt($.browser.version)"
javadoc: error - Illegal package name: "<"
javadoc: error - Illegal package name: "9;"
javadoc: error - Illegal package name: "if(!usingOldIE)"
javadoc: error - Illegal package name: "{"
javadoc: error - Illegal package name: "$("
javadoc: error - Illegal package name: ").append("
javadoc: error - Illegal package name: "<link rel=\"
javadoc: error - Illegal package name: "icon\\"
javadoc: error - Illegal package name: " href=\"
javadoc: error - Illegal package name: "{@docRoot}/favicon.ico?v=cafebabe\\"
javadoc: error - Illegal package name: ">"
javadoc: error - Illegal package name: ")"
javadoc: error - Illegal package name: "$("
javadoc: error - Illegal package name: ","
javadoc: error - Illegal package name: "window.parent.document).append("
javadoc: error - Illegal package name: "<link rel=\"
javadoc: error - Illegal package name: "icon\\"
javadoc: error - Illegal package name: " href=\"
javadoc: error - Illegal package name: "{@docRoot}/favicon.ico?v=cafebabe\\"
javadoc: error - Illegal package name: ">"
javadoc: error - Illegal package name: ")"
javadoc: error - Illegal package name: "hljs.initHighlightingOnLoad();"
javadoc: error - Illegal package name: "injectProjectVersionForJavadocJDK6("
javadoc: error - Illegal package name: "Mockito 2.0.29-beta API"
javadoc: error - Illegal package name: ","
javadoc: error - Illegal package name: "em#mockito-version-header-javadoc7-header"
javadoc: error - Illegal package name: ","
javadoc: error - Illegal package name: "em#mockito-version-header-javadoc7-footer"
javadoc: error - Illegal package name: ");"
javadoc: error - Illegal package name: "}"
javadoc: error - Illegal package name: "</script>"
javadoc: error - Illegal package name: ""
javadoc: warning - No source files for package stylesheet
javadoc: warning - No source files for package var
javadoc: warning - No source files for package usingOldIE
javadoc: warning - No source files for package $.browser.msie
javadoc: warning - No source files for package head
javadoc: warning - No source files for package shortcut
javadoc: warning - No source files for package head
javadoc: warning - No source files for package shortcut
64 errors
8 warnings

I tracked the issue down to gradle/javadoc.gradle where the gradle scripts sets the bottom property to a java script with multiple lines. 

Changing that to a single line seems to be make it possible to complete the mockitoJavaDoc task without any errors.

**Comment by bric3** [comment]
I think most of us work on Linux/OSX, it probably has to do with the JDK
version and windows line endings.

So minifying this javascript code may work ?

-- Brice

**Comment by bric3** [comment]
Fixed via 34f8c69

**Comment by mat013** [comment]
Hi Brice

Unfortunately it did not work... I have submitted an alternative suggestion

br

Meang
