### ISSUE TITLE
Verification with JUnit3 (ClassCastException instead of ArgumentsAreDifferent)

### ISSUE THREAD

**Issue by jibidus** [mockito/mockito#2569]
Hi all,

Here the issue I get when I run following code with **Mockito 4.3.1** and **JUnit 3.8.2** (Fedora, OpenJDK 1.8):

```java
App app = mock(App.class);
app.buildGreeting("bill");
verify(app).buildGreeting("bob");
```

I get a `java.lang.ClassCastException`, instead of a `ArgumentsAreDifferent`.

Here is the stack trace: 
```
class org.mockito.exceptions.verification.junit.ArgumentsAreDifferent cannot be cast to class java.lang.AssertionError (org.mockito.exceptions.verification.junit.ArgumentsAreDifferent is in unnamed module of loader 'app'; java.lang.AssertionError is in module java.base of loader 'bootstrap')
java.lang.ClassCastException: class org.mockito.exceptions.verification.junit.ArgumentsAreDifferent cannot be cast to class java.lang.AssertionError (org.mockito.exceptions.verification.junit.ArgumentsAreDifferent is in unnamed module of loader 'app'; java.lang.AssertionError is in module java.base of loader 'bootstrap')
	at org.mockito.internal.junit.ExceptionFactory.createArgumentsAreDifferentException(ExceptionFactory.java:46)
	at org.mockito.internal.exceptions.Reporter.argumentsAreDifferent(Reporter.java:339)
	at org.mockito.internal.verification.checkers.MissingInvocationChecker.checkMissingInvocation(MissingInvocationChecker.java:61)
	at org.mockito.internal.verification.Times.verify(Times.java:37)
	at org.mockito.internal.verification.MockAwareVerificationMode.verify(MockAwareVerificationMode.java:30)
	...
```

You can find a project dedicated to this issue: https://github.com/jibidus/mockito-bug-with-junit3.

I took a look at Mockito source code, and it seems that:
- The root cause seems to be in `ExceptionFactory` class: `createArgumentsAreDifferentException()` returns a new instance of `ArgumentsAreDifferent` which is casted to `AssertionError`. But `ArgumentsAreDifferent` extends `junit.framework.ComparisonFailure`, and this class does not extend `AssertionError` in JUnit3 (unlike in Junit4).
- This behavior is tested in `ExceptionFactoryTest`, but tests about JUnit3 are wrong, since current classpath with Junit4 is used.
- Current version of Mockito depends on JUnit4 (`compileOnly` dependency) : maybe Mockito should officially not support Junit3 ?

**Comment by TimvdLippe** [comment]
Unfortunately, Mockito no longer supports JUnit 3. Therefore, we recommend upgrading to JUnit 4 with the latest version of Mockito.

We should probably remove our JUnit3 support from `ExceptionFactoryTest`. Do you mind sending us a PR to do so?

**Comment by jibidus** [comment]
Thanks for your answer.
Yes, I can do that.
