### ISSUE TITLE
When mocking the static method, the static method that does not specify the return value returns a null value, why not return the value of the original logic?

### ISSUE THREAD

**Issue by dengqi1999** [mockito/mockito#2575]
`
public class Test {

    public static String getName() {
        return "name";
    }

    public static String getTest() {
        return "test";
    }
}

    @Test
    public void test() {
        try (MockedStatic<Test> theMock = Mockito.mockStatic(Test.class)) {
            theMock.when(Test::getTest).thenReturn("test123");
            System.out.println(Test.getTest());
            System.out.println(Test.getName());
        }
    }
`
When I call getName method, I get "null", why not "name"

**Comment by TimvdLippe** [comment]
`mockStatic` will treat the whole class as a "mock". Therefore, any static method you invoke will by default start returning `null`, unless you specify a stubbed value on your own. This is similar to when you mock a regular class, for which any instance method will start returning `null` unless you explicitly stub a method. If you want to invoke the default behavior for a mock, you can use https://javadoc.io/static/org.mockito/mockito-core/4.3.1/org/mockito/Mockito.html#CALLS_REAL_METHODS
