### ISSUE TITLE
mockito-inline vm warning

### ISSUE THREAD

**Issue by pincseitz** [mockito/mockito#2590]
Hello, currently I have following message during my still successful tests:

`[ERROR] OpenJDK 64-Bit Server VM warning: Sharing is only supported for boot loader classes because bootstrap classpath has been appended`

The message only occurs, if I include `mockito-inline:` but not if I only inlclude `mockito-core` using
- Mockito 4.3.1
- Mockito-jupiter 2.23.0
- JUnit Jupiter 5.4.0
- Maven 3.6.1
- JDK temurin-17.0.2+8

**Comment by raphw** [comment]
Nothing we can do about it as we append the boot loader what disables its sharing. Can be safely ignored.

**Comment by pincseitz** [comment]
Thanks for answering

**Comment by quaff** [comment]
> The message only occurs, if I include `mockito-inline:` but not if I only inlclude `mockito-core` using

 It still occurs if only include `mockito-core`.
```
$ gradle dependencies|grep mockito
|    +--- org.mockito:mockito-core:5.3.0
|    +--- org.mockito:mockito-junit-jupiter:5.3.0
|    |    \--- org.mockito:mockito-core:5.3.0 (*)

```

**Comment by raphw** [comment]
It does now as it uses the inline mock maker by default.

**Comment by i-bermudezl** [comment]
@raphw can you describe why is the warning?

And will it be corrected for future releases?

**Comment by raphw** [comment]
The warning basically states that the boot path was altered and cannot be shared among VMs. This can have performance impact but it should not be an issue.
