### ISSUE TITLE
VerificationWithDescriptionTest seems to be in the wrong package

### ISSUE THREAD

**Issue by mat013** [mockito/mockito#262]
When importing the Mockito project into Eclipse it has been discovered that there is a wrong package error for VerificationWithDescriptionTest. The class is in package org.mockitousage.verification, however the file location is src/test/java/org/mockito/internal/verification/VerificationWithDescriptionTest.java.

Does anyone have an explanation why it does come with a compilation error when running from the command prompt

**Comment by bric3** [comment]
Eclipse is wrong !
This test is intentionally in `org.mockitousage`, this package helps us to drive design and api usage via unit test. ;)

**Comment by mat013** [comment]
It seems like I am using all the wrong tools (Windows now eclipse *lol*)

However it also have a red squiggle in IntelliJ when you open the file.

Well I guess that pull request is not going in then... may I suggest that a
comment is written then... so someone else will not make the same mistake :)

I did not quite understand what you mean by drive design and api usage via
unit test. Could you explain it to me?

br

Meang

**Comment by bric3** [comment]
It's all about TDD (Test Driven Development), that is to use tests as a tool to develop code.
You can lookup on google for more, but here's the basic idea :

> You write first your test, a very simple one, then you write code to make it pass, then you write another failing test, and go back to code to make it pass. With this rapid feedback loop, the developed code can be achieve with very few bugs.

While this may seem like a non-necessary gimmick, it is very powerful as it allows the developer to think about how his code is used before he even wrote it. This avoid the scenario we all went through during our studies where we write code, then see if it works, then we discover there's bug here and there, and that we didn't think about how to integrate the code here, etc...

It really is related to things like _emergent design_. Nowadays I wouldn't even work without practicing TDD. Here's the first anti-pattern of TDD : 

> Don't ask your boss if one should do TDD.
> _It's like asking him if one should write bug free code ;)_

> It seems like I am using all the wrong tools (Windows now eclipse *lol*)

I'm not a fan of Eclipse, and IntelliJ is for me the superior choice, but that doesn't mean it is right or bug free either ;)
