### ISSUE TITLE
Missing errorprone module for 4.5.0 in central as release was done with jdk 8

### ISSUE THREAD

**Issue by hazendaz** [mockito/mockito#2623]
Error prone module is missing for 4.5.0 and not in the 4.5.0 bom.  Looking at the source code changes and release action, it appears jdk 8 was used to release and its ignored unless jdk 11 is used.  Can someone check?

**Comment by TimvdLippe** [comment]
Ah ugh, yes that's a mistake. We will need to update our GitHub actions configuration to run the release job on JDK 11. Do you mind sending us a PR that updates the job matrix to skip the release on JDK 8 and runs it on JDK 11?

**Comment by hazendaz** [comment]
Yes I can do so later tonight.

Sent from my Verizon, Samsung Galaxy smartphone
Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by TimvdLippe** [comment]
@raphw can you release 4.5.1 on `main` including #2624? That should fix our ErrorProne artifact.

**Comment by raphw** [comment]
Triggered one just now.

**Comment by TimvdLippe** [comment]
https://repo1.maven.org/maven2/org/mockito/mockito-errorprone/4.5.1/ has been released 🎉

**Comment by hazendaz** [comment]
Thanks @TimvdLippe @raphw for quick turn around
