### ISSUE TITLE
Introduce option to disable inline-mock-maker for a specific instance

### ISSUE THREAD

**Issue by JojOatXGME** [mockito/mockito#2626]
In order to ease the migration to the inline mock maker in big projects, it would nice if the mock make can be changed for individual mocks. This would allow projects to change the default mock maker to `inline-mock-maker` without immediately fixing all edge cases where the new mock maker doesn't work.

Such option could be provided over a new method on the `MockSettings` class.

**Comment by astromme** [comment]
+1 

We have a situation where we'd like to mock a JNI interface with native methods. These methods are unsupported by the new inline mockmaker according to https://javadoc.io/doc/org.mockito/mockito-core/latest/org/mockito/Mockito.html, but we need to use inline in other parts of our codebase.

**Comment by deepakab03** [comment]
Will this change be ported to Mockito 5.x ? 
It is required there since breakpoints on Spied objects don't work with the new inline mock maker. It works with mockito-subclass, but it would be good to have the option to specify a mock maker where required rather than change the default jar used..
