### ISSUE TITLE
Idea: Mockito.stub and Mockito.dummy methods

### ISSUE THREAD

**Issue by tlinkowski** [mockito/mockito#2630]
Hi, feel free to close this issue if this idea was already discussed and rejected (I couldn't find it).

## What

Idea: add the following two convenience methods to `Mockito` class:

```java
public class Mockito {

    // ...

    /**
     * Creates a Test Stub.
     * <p>
     * See: http://xunitpatterns.com/Test%20Stub.html
     */
    @CheckReturnValue
    public static <T> T stub(Class<T> type) {
        return mock(type, withSettings().stubOnly());
    }

    /**
     * Creates a Dummy Object.
     * <p>
     * See: http://xunitpatterns.com/Dummy%20Object.html
     */
    @CheckReturnValue
    public static <T> T dummy(Class<T> type) {
        return mock(type, withSettings().stubOnly().defaultAnswer(invocation -> {
            throw new IllegalStateException("Methods cannot be called on a Dummy Object - tried to call " + invocation.getMethod().getName());
        }));
    }
}
```

## Why

This is based on three out of five test doubles described at [xUnitPatterns](http://xunitpatterns.com/Test%20Double.html):
1. Mock Object (`mock`): provides stubbings ✔, records invocations ✔
2. Test Stub (`stub`): provides stubbings ✔, records invocations ✘
3. Dummy Object (`dummy`): provides stubbings ✘, records invocations ✘

Some thoughts:
- `stub` would probably be used more frequently than `withSettings().stubOnly()`
   - to me, writing the full `mock(..., withSettings().stubOnly())` was always too much but writing `stub(...)` instead of `mock(...)` seems much better
- `dummy` wouldn't probably be used very often but maybe it's still worth to have it for explicitness
   - I use it rarely because I rarely need dummies but when I do, I like to make it explicit that it's not even a stub (it's just something I pass and there's no interaction with it)

**Comment by TimvdLippe** [comment]
This pattern has previously been discussed in #1778 and I don't think we have changed our stance on introducing a separate method for this. We recommend introducing an alias for `withSettings.stubOnly()` in your personal project if you prefer that pattern.

**Comment by tlinkowski** [comment]
Hi, thanks for the link - interesting read. Now it's much clearer to me why it's like this - I didn't realize you consider "stubOnly" to be an implementation detail rather than a full type of [test double](https://en.wikipedia.org/wiki/Test_double).

Apparently, the term "test double" itself is not as popular as I imagined. That said, I'd gladly hear pros and cons of Mockito adopting and propagating the concept of Test Doubles (by providing full-blown support for four of them: mock, spy, stub, dummy).

PS. Of course, you're right it's easy to add those methods on one's own (an extra class like `MockitoUtil` + static import from it).
