### ISSUE TITLE
Any way to enable Strict Stubbing when using Mockito.mock() without using @Mock?

### ISSUE THREAD

**Issue by sivaprasadreddy** [mockito/mockito#2648]
Hi,
I am using mockito-core 4.5.1 and JUnit 5. I can use `MockitoExtension` and `@Mock` annotation and by default I get Strict Stubbing behaviour. However, if I use `Mockito.Mock(MyClass.class)` to create mock it seems Strictness is not enabled. Even if I stub unnecessary methods it is not giving any error. 

I know I can work around this by using MockitoExtension to create mocks using @Mock, but is there any way to enable Strict Stubbing while using `Mockito.mock(MyClass.class);`

```
class ProductServiceTest {

    private ProductRepository productRepository;
    private ProductService productService;

    @BeforeEach
    void setUp() {
        productRepository = Mockito.mock(ProductRepository.class);
        productService = new ProductService(productRepository);
        // this is unnecessary method stubbing but it is not giving any error
        Mockito.when(productRepository.findAllActiveProducts()).thenReturn(List.of());
    }

    @Test
    void shouldReturnOnlyActiveProducts() {
        BDDMockito.given(productRepository.findAll()).willReturn(List.of(p1, p2));
        productService.findAll(); // which calls productRepository.findAll()
    }
}
```

**Comment by TimvdLippe** [comment]
I would have though that we supported this feature with our `MockSettings`. While looking that up, I discovered that we do ship [`lenient()`](https://javadoc.io/static/org.mockito/mockito-core/4.5.1/org/mockito/MockSettings.html#lenient()), but we don't ship an equivalent API to set the strictness to `STRICT_STUBS`. I consider that a deficiency of the API, for which we should add an option. Therefore, +1 to this feature request.

In hindsight, we shouldn't have shipped `mockSettings.lenient()`, but instead add `mockSettings.strictness(Strictness)`. We have the same issue with `@Mock`: https://javadoc.io/doc/org.mockito/mockito-core/latest/org/mockito/Mock.html#lenient()

Therefore, I propose we update both `MockSettings` and `@Mock` to accept a new setting called `strictness` which sets the `Strictness`. We can then deprecate both `lenient()` options, as they would be a shortcut for `strictness(Strictness.LENIENT)`.

@sivaprasadreddy Would you like to contribute this feature to Mockito?

**Comment by sivaprasadreddy** [comment]
@TimvdLippe Sure, I will contribute to this feature.

**Comment by sivaprasadreddy** [comment]
@TimvdLippe I have raised a PR https://github.com/mockito/mockito/pull/2650 and the GH Actions pipeline is waiting for approval https://github.com/mockito/mockito/actions/runs/2368951973.

**Comment by sivaprasadreddy** [comment]
@TimvdLippe The PR build failed (https://github.com/mockito/mockito/actions/runs/2368951973) because of an error in Javadoc comment, which I have fixed now.
