### ISSUE TITLE
`verify(someMock, never()).someMethod()` should suppress `UnnecessaryStubbingException`

### ISSUE THREAD

**Issue by guw** [mockito/mockito#2649]
I have an abstract base class for some (integration style) tests. This class sets up a mock/spy based on input provided by the specific subclass. After performing tests I assert for one of two states. 

- There can only be one state out of two possible states.
- If either state is asserted, I want the test to be ok
- If none of the states is assert, I want Mockito to fail with `UnnecessaryStubbingException`

Here is some code:
```
@ExtendWith(MockitoExtension.class)
public abstract class IntegrationTestForCommands<T extends Command> {
	private final Class<T> commandClass;
	private T command;
	private Object saveResult;

	public IntegrationTestForCommands(Class<T> commandClass) {
		this.commandClass = commandClass;
	}

	@BeforeEach
	protected void setUp() throws Exception {
		command = mock(commandClass, withSettings().useConstructor().defaultAnswer(CALLS_REAL_METHODS));
		// also tried spy(commandClass) but same result

		// intercept save result
		doAnswer(invocation -> saveResult = invocation.callRealMethod()).when(command).save(any());
	}

	protected void assertNoSaveResult() {
		assertNull(saveResult, "Unexpected save when executing the command!");
		try {
			verify(command, never()).save(any());
		} catch (Exception e) {
			fail("unexpected exception", e);
		}
	}

	protected void assertSaveResult() {
		assertNotNull(saveResult, "Nothing was saved!");
		try {
			verify(command, times(1)).save(any());
		} catch (Exception e) {
			fail("unexpected exception", e);
		}
	}
}
```

The specific test classes would then do:
```
@Test
public final void noop_test() throws Exception {
	...
	assertNoSaveResult();
}

@Test
public final void update_test() throws Exception {
	...
	assertSaveResult();
}
```

What happens is that the *update_test* works nicely but *noop_test* fails with `UnnecessaryStubbingException` for `doAnswer(...).when(command).save(any());`

I think this should not fail because I explicitly assert for the method to never be invoked.

Mockito 4.5.1

**Comment by TimvdLippe** [comment]
Unfortunately, the way Mockito interacts with the JVM, we can't determine that we are in a when-never statement upon invocation 😢 However, since Mockito will throw the exception if the call is unexpected (which `never()` does as well), I think we have equivalent behavior here. Therefore, while not ideal that you can't explicitly state `never()`, I think the current solution is still sufficient.
