### ISSUE TITLE
Regression? Strictness set in `@MockitoSettings` ignored after upgrade from 4.5.1 to 4.6.0

### ISSUE THREAD

**Issue by big-andy-coates** [mockito/mockito#2656]
Upgrading from Mockito 4.5.1 to 4.6.0 and it looks to me as though https://github.com/mockito/mockito/pull/2650 or something around there has introduced a regression.

I'm seeing `PotentialStubbingProblem` exceptions where previously there were none, because the test class is annotated with `@MockitoSettings(strictness = Strictness.LENIENT)`.

The issue seems to be that `StrictnessSelector` prefers the strictness set in the mock to the test level strictness, and the mock _defaults_ to `STRICT_STUBS`, so always overrides the strictness set in `@MockitoSettings`.

I've added a failing example test that demonstrates the issue here:  https://github.com/big-andy-coates/mockito/pull/1

The above test fails with:

```
expected: 
  Optional.empty
 but was: 
  Optional[org.mockito.exceptions.misusing.PotentialStubbingProblem: 
  Strict stubbing argument mismatch. Please check:
   - this invocation of 'test' method:
      rootMock.test("Bar");
      -> at org.mockitousage.ProductionCode.simpleMethod(ProductionCode.java:9)
   - has following stubbing(s) with different arguments:
      1. rootMock.test("Foo");
        -> at org.mockitousage.StrictnessTest$LenientMockitoSettings.should_not_throw_on_potential_stubbing_issue(StrictnessTest.java:176)
  Typically, stubbing argument mismatch indicates user mistake when writing tests.
  Mockito fails early so that you can debug potential problem easily.
  However, there are legit scenarios when this exception generates false negative signal:
    - stubbing the same method multiple times using 'given().will()' or 'when().then()' API
      Please use 'will().given()' or 'doReturn().when()' API for stubbing.
    - stubbed method is intentionally invoked with different arguments by code under test
      Please use default or 'silent' JUnit Rule (equivalent of Strictness.LENIENT).
  For more information see javadoc for PotentialStubbingProblem class.]
```

 - [x] The mockito message in the stacktrace have useful information, but it didn't help
 - [x] The problematic code (if that's possible) is copied here;
       Note that some configuration are impossible to mock via Mockito
 - [x] Provide versions (mockito / jdk / os / any other relevant information)
 - [x] Provide a [Short, Self Contained, Correct (Compilable), Example](http://sscce.org) of the issue
       (same as any question on stackoverflow.com)
 - [x] Read the [contributing guide](https://github.com/mockito/mockito/blob/main/.github/CONTRIBUTING.md)

**Comment by TimvdLippe** [comment]
That indeed sounds like a regression, apologies for that. Since we already have a PR with a regression test, can one of you also supply the fix for it? If all other tests in our suite pass, we should be good to go.

**Comment by big-andy-coates** [comment]
No worries! ;)

I'm happy to submit a PR, but before I do I think its worth discussing what the fix should be.

It seems to me that the issue is the default values for strictness introduced by @sivaprasadreddy.  By defaulting the new strictness to `Strictness.STRICT_STUBS` the test level strictness gets ignored.  

I'd therefore suggest removing the defaults, i.e. setting them to `null`. However, this looks like it would undo part of the intent of @sivaprasadreddy's PR, which is to default to `STRICT_STUBS`.

I'll have a quick hack about to see how things turn out, but any thoughts on this appreciated.

**Comment by TimvdLippe** [comment]
The intent of the PR was to introduce a new API surface for configuring strictness, not to change the default. So I consider it a regression that the new default became STRICT_STUBS. Not sure how I missed that in the review.

Setting it to an unset value (e.g. null) sounds like the appropriate solution to me.

**Comment by TimvdLippe** [comment]
Looking at the original PR again, I indeed completely overlooked the default values. These should have been `LENIENT` rather than `STRICT_STUBS`. If we change them to `LENIENT`, I think we retain the correct behavior?

**Comment by big-andy-coates** [comment]
I think changing defaults won't fix the issue that the defaults stop the test level settings ever taking affect.

**Comment by TimvdLippe** [comment]
If I understand the new code of the `StrictnessSelector` correctly, we now always take the `strictness` set in the creation settings. That's because it is initialized to a non-null value. However, we have a field that is of type `Strictness` that we can assign `null` to. Then we change the default of the annotation value to `LENIENT` and then I think the logic will work as it did before, doesn't it?

**Comment by big-andy-coates** [comment]
I don't think so.  The `MockAnnotationProcessor` will copy the default (`LENIENT`) from the annotation into the settings

**Comment by TimvdLippe** [comment]
What if we add a new value to `org.mockito.quality.Strictness` called `TEST_DEFAULT_VALUE` which is our "not set" value. Then we check if that value exists in the creation settings and don't set it if that's the default. We can then explicitly document the strictness to say "the test suite strictness value will take precedence".

It's not ideal to ship this to users, but I think it's the most explicit and also will fix this issue?

**Comment by big-andy-coates** [comment]
Yeah, I had thought of that. It would fix the issue and wouldn't be a breaking change for 4.6.0 -> 4.6.1, but...

It leaves this `TEST_DEFAULT_VALUE` in the enum, and the enum is used in other places and in all those other places does it actually make sense to use it? i.e. are we polluting the API going forward to work around this bug in 4.6.0?

As I see it the two options are:

1. Add local enum to `Mock` class with a `NOT_SET` value
    * pros: cleaner API going forward
    * cons: breaking change for anyone using the new `strictness` value of the `@Mock` class, which was released in 4.6.0.
2. Add a `TEST_DEFAULT_VALUE` to the existing `Strictness` enum.
    * pros: not a breaking change.
    * cons: more ambiguous API moving forward.

I'm happy to go with either.

**Comment by TimvdLippe** [comment]
In that case, I think option 1 is the cleanest. Since we just shipped the new feature, I would be okay wit changing that. It is unfortunate, but something that we can patch over after a day.

**Comment by big-andy-coates** [comment]
OK, PR coming soon...

(FYI, I've just been trying to raise the PR for option 2 and its not pretty, so I think this is the right call)

**Comment by nbrugger-tgm** [comment]
I encountered the NPE by @chadlwilson in java (not groovy) should a new ticket created for it - or just bump the already existing one #2667

**Comment by chadlwilson** [comment]
If the root cause is the same (sourceFile location not known for a `StackTraceElement`) and you have an easier way to replicate it, I imagine the same issue is fine. I haven't test it, but can imagine it might be possible to get the same error if running tests against code deliberately compiled without relevant debug symbols (`-g:none` or similar).
