### ISSUE TITLE
Update javadoc of `Strictness.STRICT_STUBS`

### ISSUE THREAD

**Issue by happylynx** [mockito/mockito#2679]
https://github.com/mockito/mockito/blob/c4cce85decc1639db41209696131d41e6d722d2f/src/main/java/org/mockito/quality/Strictness.java#L68

https://github.com/mockito/mockito/blob/c4cce85decc1639db41209696131d41e6d722d2f/src/main/java/org/mockito/MockSettings.java#L371

It looks like despite of the plan, `LENIENT` is still the default in version 4.

**Comment by TimvdLippe** [comment]
I would be happy to review a PR that removes the sentence altogether

**Comment by uladkaminski** [comment]
I am ready to prepare to prepare PR, but I don't have permissions to push
