### ISSUE TITLE
MockedConstruction has side effects even after close() (with Sub-/Superclass)

### ISSUE THREAD

**Issue by eNBeWe** [mockito/mockito#2680]
I am not 100% sure, but I think this is a bug. (Might be me just doing something wrong, but I don't see anything)

I prepared a small example [here](https://github.com/eNBeWe/mockito-bug) with most recent versions of mockito-inline (4.6.1) and junit5 (5.8.2). I prepared it on Ubuntu, using OpenJDK 11, but I also experienced this issue on other systems.

In short, I have two tests, each mocking constructors. The two constructors are related to each other, via inheritance. Both constructor mocks are auto-closed through try-with-resource.
If I first mock the subclass constructor, close it again and then mock the superclass constructor and create a subclass object, my test fails. If I do it the other way around, my tests work.

```
class SuperClass {}

class SubClass extends SuperClass {
	public boolean isOtherValue() {
		return true;
	}
}
```
```
@TestMethodOrder(OrderAnnotation.class)
class FailingTest {

	@Test
	@Order(1)
	void testThingsFirst() {
		try (MockedConstruction<SubClass> mocked = Mockito.mockConstruction(SubClass.class)) {
			System.out.println("Running testCreateStuff");
		}
	}

	@Test
	@Order(2)
	void testThingsSecond() {
		try (MockedConstruction<SuperClass> constructionMock = Mockito.mockConstruction(SuperClass.class)) {
			System.out.println("Running testOtherValue");
			SubClass testee = new SubClass();
			assertTrue(testee.isOtherValue());
		}
	}
}
```
```
[ERROR] Tests run: 2, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.793 s <<< FAILURE! - in de.enbewe.bug.mockito.FailingTest
[ERROR] de.enbewe.bug.mockito.FailingTest.testThingsSecond  Time elapsed: 0.039 s  <<< FAILURE!
org.opentest4j.AssertionFailedError: expected: <true> but was: <false>
```

So it seems the old, closed subclass-constructor is becoming active again, when I mock the superclass. 

I tried to find some more info / debug more, but I don't really understand enough of the internals of Mockito.

**Comment by TimvdLippe** [comment]
@raphw Does this ring any bells?

**Comment by raphw** [comment]
Ah, I see what is happening:

When we mock a constructor, it is mocked even if it is invoked from a subclass that is not mocked. A class will be marked as a mock in any case, therefore. If the subclass constructor was however not mocked before, it is not instrumented. Therefore, the mocking is only partial in the one "working" case.

I will see that we avoid this by checking the stack.
