### ISSUE TITLE
Add "Download" section to menu in http://mockito.org/

### ISSUE THREAD

**Issue by turbanoff** [mockito/mockito#269]
I don't understand why it wasn't done previously.
Now it's look strange to not have searchable Download links with last/stable version at main site page.

**Comment by bric3** [comment]
you can click on the badges

**Comment by turbanoff** [comment]
@bric3 It's counterintuitive. Badge shows only latest version (not stable). I'm unable to find badge when I search "download"

**Comment by bric3** [comment]
Github project shows both I'll sync the website. However I don't see that as counter intuitive, quite the contrary. Bintray and maven are our distribution platforms.

**Comment by bric3** [comment]
Unfortunately at the moment badge service is having a hard time, it will get back up sometime later.
