### ISSUE TITLE
Mockito spy is unable to verify protected method call from within an anonymous class

### ISSUE THREAD

**Issue by catchsvix** [mockito/mockito#271]
Here's my scenario:

```java
public interface Invoker
{
    void invoke();
}
```

```java
public class Foo
{
   private Invoker m_invoker;

   public Foo()
   {
       m_invoker = new Invoker(){
           
            public void invoke(){
              bar();
            }
       };
   }

   protected void bar() 
   {
       System.out.println("bar is indeed invoked! but the verification on spy fails");
   }
   
   public doInvoke()
   {
        m_invoker.invoke();
   }
  
}
```

```java
public class FooTests
{
   Foo m_foo = Mockito.spy(new Foo());
   @Test
   public void testVerifyBarIsInvoked()
   {
       m_foo.doInvoke();

       //THIS VERIFICATION FAILS.... SAYS BAR ISN'T INVOKED
       Mockito.verify(m_foo, times(1)).bar();
   }
}
```

**Comment by catchsvix** [comment]
mockito 1.9.5

**Comment by bric3** [comment]
Unfortunately this kind of code design is not supported by spies.

What's happening here is that when mockito creates the spy it creates a **shallow** copy of `new Foo()`, thus copying the inner class reference. But this inner class has already been constructed with a reference on the original (non-spy) `Foo` hence the call is not intercepted by Mockito.

Mockito probably won't be modified to explore the object graph to change all references just to support this kind of design (which is not wrong by the way).

There's several workaround that that may work for your code, depending on what the code is really supposed to achieve.

 * Don't use Mockito spies, thus thinking in input/output tests

 * Pass the `Foo` reference at invocation time, it requires however changing the `invoke` signature :

    ```java
    public class Foo {
        private Invoker m_invoker;

        public Foo() {
            m_invoker = new Invoker() {
                public void invokeOn(Foo foo) {
                    foo.bar();
                }
            };
        }

        protected void bar() {
            System.out.println("bar invoked");
        }

        public void doInvoke() {
            m_invoker.invokeOn(this);
        }
    }
    ```

 * Creates a new invoker upon each `doInvoke`, here `Invoker` could be passed around to another collaborator that will do the invocation, or else : 

    ```java
    public class Foo {
        public Foo() { }
    
        protected void bar() {
            System.out.println("bar invoked");
        }
    
        public void doInvoke() {
            new Invoker() {
                public void invoke() {
                    bar();
                }
            }.invoke();
        }
    }
    ```

 * Use a fully fledged container that can inject the invoker, but the test here will change, as you will inject an `Invoker` mock.
