### ISSUE TITLE
TypeSafeMatching.getArgumentType causes slowdowns due to Class.getMethods copying

### ISSUE THREAD

**Issue by j-baker** [mockito/mockito#2728]
Originally reported in #2720, splitting out for fix in separate PR.

> The second slowdown that seemed to be affecting me comes from TypeSafeMatching.getArgumentType. This iterates through all of the methods on the argument matcher class to find the appropriate matches method, seemingly also for each method call. By performing this operation, a lot of JVM internal datastructures get copied - it calls Class.getMethods, which copies all the > methods on the class. This method could probably be cached on a per-class basis.

**Comment by TimvdLippe** [comment]
#2729 fixed this, but referenced the wrong issue number.
