### ISSUE TITLE
Refactor Gradle setup to get more seamless IDE integration

### ISSUE THREAD

**Issue by j-baker** [mockito/mockito#2730]
I've been putting forward a couple of contributions and I've been tripped up with some code style stuff. Basically, I'm getting tripped up because I'm used to my IDE doing most of the work for me, which isn't happening right now with Mockito. It's no major deal, but as a quality of life thing you might want to investigate it the next time you take a pass over the Gradle setup?

The company I work for has a Gradle plugin where IntelliJ and Eclipse are automatically configured with code style, copyright, etc settings, and a formatter is set up to automatically enforce appropriate formatting on save. I personally find this workflow extremely ergonomic and it tends to drop most of the potential for errors.

For some pointers:

1. [Code style templates are dropped into a project subfolder](https://github.com/palantir/dialogue/blob/develop/.baseline/idea/intellij-java-palantir-style.xml)
2. [IntelliJ is configured to use the code style settings](https://github.com/palantir/gradle-baseline/blob/develop/gradle-baseline-java/src/main/groovy/com/palantir/baseline/plugins/BaselineIdea.groovy#L133). N.b. this class supports both .ipr and native gradle import. We consider it hard enough to support .ipr files in recent versions of Java and the native Gradle import sufficiently good that this is effectively deprecated.
3. [If the formatter exists, prompt the user to set up a plugin to run it on save (along with organize imports)](https://github.com/palantir/gradle-baseline/blob/develop/gradle-baseline-java/src/main/groovy/com/palantir/baseline/plugins/BaselineIdea.groovy#L580)
4. [Separately, tell IntelliJ to automatically format the code and ask them to install the formatting plugin if there isn't one already](https://github.com/palantir/palantir-java-format/blob/develop/gradle-palantir-java-format/src/main/groovy/com/palantir/javaformat/gradle/PalantirJavaFormatIdeaPlugin.java#L83)

I'd recommend you pick up the plugins wholesale (they work real nice and come with a bunch of static analysis that saves time in practice) but they don't support Java 8 anymore. Either way, the specific snippets that configure IntelliJ are, if you fancy applying them to a project one-off, reasonably straightforward.

Don't know if this is something you'd want to try, but figured that you might want to be aware.

**Comment by TimvdLippe** [comment]
It's unlikely we will adopt propietary plugins, unless absolutely crucial for the development workflow. In this case, the spotless configuration should already be sufficient to tackle the code style and formatting changes, which you can run on the command line with `./gradlew spotlessApply` (which will also remove unused imports). I understand that you have a preferred IDE workflow, but I think it is better for open source projects like Mockito to be as barebones as reasonable to avoid lock-in to one specific part of our userbase.

**Comment by j-baker** [comment]
I think if you'd rather not integrate with IDEs that's absolutely reasonable. For avoidance of doubt, I'm not proposing adopting any proprietary code, rather showing the Gradle code snippets that show IntellIJ and Eclipse how to do the right thing.
