### ISSUE TITLE
java.lang.IllegalAccessError: class javax.xml.datatype.FactoryFinder

### ISSUE THREAD

**Issue by y17v** [mockito/mockito#2737]
Hi All,

I am trying to run my Junit test but getting the below error. Any help would be really appreciated.

I am using PowerMockRunner in my test cases.
And Maven Dependencies are:

      <artifactId>mockito-core</artifactId>
      <version>3.6.28</version>
      
      <artifactId>powermock-module-junit4</artifactId>
      <version>2.0.9</version>

      <artifactId>powermock-api-mockito2</artifactId>
      <version>2.0.9</version>
      
Error:
java.lang.IllegalAccessError: class javax.xml.datatype.FactoryFinder (in unnamed module @0x53b8afea) cannot access class jdk.xml.internal.SecuritySupport (in module java.xml) because module java.xml does not export jdk.xml.internal to unnamed module @0x53b8afea
at javax.xml.datatype.FactoryFinder.<clinit>(FactoryFinder.java:70)
at javax.xml.datatype.DatatypeFactory.newInstance(DatatypeFactory.java:169)

**Comment by TimvdLippe** [comment]
This is most likely an issue with Powermock and not related to Mockito. I recommend upgrading your version of Mockito and try to remove your usage of Powermock and see if the issue persists.
