### ISSUE TITLE
Functions `Mockito.when().thenReturn` is broken if it's split into multiple lines

### ISSUE THREAD

**Issue by jirijanak** [mockito/mockito#2748]
I tried to update Mockito from 4.6.1 to 4.8.0 and tests started to fail. During debug I have found out it's just because of code formating. If I change that, tests start passign again.

I have following code in my project
```
       @BeforeEach
        void beforeEach() {
            authHelper = Mockito.mock(AuthHelper.class);
            Mockito.when(authHelper.hasAnyOfGlobalRoles(anyString()))
                    .thenReturn(false);

            userInfoHelper.setAuthHelper(authHelper);

            UserInfo person = new UserInfo();
            person.setCnum("CNUM_TEST");
            person.setEmail("one@example.com");
            person.setCommonName("User One");
            Mockito.when(userInfoHelper.getUserInfo())
                    .thenReturn(person);
```

Debug "stops" after line with `Mockito.when()`, method `beforeEach()` doesn't finish at all. It just terminates, no info is printed into the console.

If I change
```
            Mockito.when(authHelper.hasAnyOfGlobalRoles(anyString()))
                    .thenReturn(false);
```
to single line
```
            Mockito.when(authHelper.hasAnyOfGlobalRoles(anyString())).thenReturn(false);
```
everything works again.

Behavior is same on my local MacOS, on my colleagues Windows and Linux based machines.
JVM:         11.0.15-ea (Eclipse OpenJ9 openj9-0.32.0)
OS:           Mac OS X 12.5.1 aarch64

Can this get fixed, please?

 - [ ] The mockito message in the stacktrace have useful information, but it didn't help
 - [X] The problematic code (if that's possible) is copied here;
       Note that some configuration are impossible to mock via Mockito
 - [X] Provide versions (mockito / jdk / os / any other relevant information)
 - [X] Provide a [Short, Self Contained, Correct (Compilable), Example](http://sscce.org) of the issue
       (same as any question on stackoverflow.com)
 - [X] Read the [contributing guide](https://github.com/mockito/mockito/blob/main/.github/CONTRIBUTING.md)

**Comment by TimvdLippe** [comment]
Thanks for filing the issue. Could you please provide us a minimal reproduction case that we can clone/download to debug the issue? Thanks in advance!

**Comment by jirijanak** [comment]
Can't reproduce it anymore. Not sure - maybe issue was on my side. Closing.
