### ISSUE TITLE
Backward incompatible change from TestRule to MethodRule

### ISSUE THREAD

**Issue by trothwell** [mockito/mockito#275]
Per: http://junit.org/apidocs/org/junit/rules/MethodRule.html
> Note that MethodRule has been replaced by TestRule, which has the added benefit of supporting class rules.

`MethodRule` doesn't support `RuleChain` as it only supports `TestRule`.

Consider the usage:
```java
// previously
RuleChain.outerRule(new MockitoJUnitRule(this)); // good

// now
RuleChain.outerRule(new MockitoJUnitRule(this)); // broken
RuleChain.outerRule(MockitoJUnit.rule()); // broken
```

**Comment by trothwell** [comment]
Also consider how to solve ordering issue of multiple method rules.
https://github.com/junit-team/junit/issues/383

**Comment by bric3** [comment]
I think this a reasonable change for Mockito 2.0, minimum Junit version would be 4.9 then

**Comment by bric3** [comment]
I just checked the signature of `TestRule`, but we have a problem, `RuleChain.outerRule(MockitoJUnit.rule());` cannot work as `TestRule` do not pass the target on which the rule should be applied. And that is for a reason, `TestRule` can be executed on the _"class"_ scope with the `@ClassRule` annotation.

```java
public interface TestRule {
	Statement apply(Statement base, Description description);
}
```

In my opinion, JUnit `RuleChain` should support `MethodRule`
