### ISSUE TITLE
MockitoException thrown when up upgrading from Mockito 4.7.0 to 4.8.0

### ISSUE THREAD

**Issue by milosimpson** [mockito/mockito#2752]
Error message with Mockito 4.8.0 running on jdk 11.   This test works on 4.7.0 with jdk11.
```
[2022-09-14 17:04:18,285] ERROR Thread Thread[KafkaLogicalClusterEventsListener,5,main] died (org.apache.zookeeper.server.NIOServerCnxnFactory:87)
org.mockito.exceptions.base.MockitoException: Caught an unexpected exception while stack walking.
This is unexpected and is likely due to a change in either Java's StackWalker or Reflection APIs.
It's worth trying to upgrade to a newer version of Mockito, or otherwise to file a bug report.
```

The test code uses a Spy, and want to check the invocations on a method after "starting" it.
```
    try (KafkaConsumer<String, byte[]> spyConsumer = Mockito.spy(createEventsKafkaConsumer(EVENTS_LC_TOPIC));
         KafkaLogicalClusterEventsListener syncLCService = new KafkaLogicalClusterEventsListener(
                 spyConsumer, roleBindingChangePublisherService,
                 new DeadLetterQueue(lcDlqProducer, EVENTS_LC_DLQ_TOPIC),
                 trustDataChangePublisherService)) {
      KafkaLogicalClusterEventsListener spySyncLCService = Mockito.spy(syncLCService);

      // the syncLCService that is being spied extends Thread so we need to start it, test dies on this line 
      spySyncLCService.start();   

      // never gets here with 4.8.0
      Mockito.verify(spySyncLCService, after(3000).times(5))
        .extractLogicalCluster(ArgumentMatchers.argThat((record) -> { ... }
```

 - [x] The mockito message in the stacktrace have useful information, but it didn't help
 - [x] The problematic code (if that's possible) is copied here;
       Note that some configuration are impossible to mock via Mockito
 - [x] Provide versions (mockito / jdk / os / any other relevant information)
 - [ ] Provide a [Short, Self Contained, Correct (Compilable), Example](http://sscce.org) of the issue
       (same as any question on stackoverflow.com)
 - [x] Read the [contributing guide](https://github.com/mockito/mockito/blob/main/.github/CONTRIBUTING.md)

**Comment by TimvdLippe** [comment]
Can you please post the full stacktrace?

**Comment by milosimpson** [comment]
That is the problem, it doesn't throw an exception, it just prints that line.

`org.mockito.exceptions.base.MockitoException: Caught an unexpected exception while stack walking.
This is unexpected and is likely due to a change in either Java's StackWalker or Reflection APIs.
It's worth trying to upgrade to a newer version of Mockito, or otherwise to file a bug report.`

I put a try catch throwable around the  `spySyncLCService.start();` and caught nothing.

If I debug in intellij, I can see where that MockitoException message gets generated, but it gets swallowed, and the Mockito.verify calls fails.

<img width="1960" alt="Screen Shot 2022-09-15 at 11 27 21 AM" src="https://user-images.githubusercontent.com/1203207/190459258-9da5b0c0-5c7f-48c4-b2f3-c9e9dbc6e828.png">

<img width="1924" alt="Screen Shot 2022-09-15 at 11 22 15 AM" src="https://user-images.githubusercontent.com/1203207/190459284-a277f64b-569e-48ca-a712-9fae22c1c2b6.png">

**Comment by TimvdLippe** [comment]
Hm, I would have to debug this myself to figure out what is going on here. Can you submit a PR with a regression test to our test suite so that we can reproduce the issue?

**Comment by milosimpson** [comment]
I can try as an off the clock thing.   I can unblock by just using 4.7.0.

**Comment by TimvdLippe** [comment]
While looking through the relevant code, I saw that we swallow the nested Exception: https://github.com/mockito/mockito/blob/73a861f778e117ad0ccd7388b8d7a614e65c1623/src/main/java/org/mockito/internal/debugging/Java9PlusLocationImpl.java#L153

To aid debuggability, we should pass `e` as second argument to the constructor of `MockitoException`.

And just in case, did you any other `RuntimeException` in your logs, coming from https://github.com/mockito/mockito/blob/73a861f778e117ad0ccd7388b8d7a614e65c1623/src/main/java/org/mockito/internal/debugging/Java9PlusLocationImpl.java#L173 ?

**Comment by TimvdLippe** [comment]
Closing this for now, but if you would like to propose a patch that solves the regression, I will happily review it!
