### ISSUE TITLE
Can't mock on JDK 19 because `when` is a restricted identifier

### ISSUE THREAD

**Issue by SentryMan** [mockito/mockito#2755]
Hello there,

It seems I cannot mock anything with mockito when I use JDK 19. Trying to use the mockito `when` function throws compilation error `Syntax error on token "RestrictedIdentifierWhen", delete this token`

Mockito Version 4.8.0
JDK: 19.ea.36-openjdk

**Comment by TimvdLippe** [comment]
Can you please post your full code snippet?

**Comment by SentryMan** [comment]
Yeah, stuff like this doesn't compile.

```
var mock = Mockito.mock(TestObject.class);

doReturn("testString").when(mock).getString();
```

**Comment by TimvdLippe** [comment]
@raphw I can't find any references to restricted identifiers in the JDK, nor anything mentioned in the release notes. Are you aware of any efforts by the JDK folks that would mark `when` as a restricted identifier? I imagine that this will break all our usages of Mockito

**Comment by raphw** [comment]
@SentryMan You are using an EA build. Maybe there is some issue with the compiler or with your IDE using this EA version? There is nothing wrong with the code and I would not know of a new restriction.

**Comment by pzygielo** [comment]
I guess, the message
> Syntax error on token "RestrictedIdentifierWhen", delete this token

comes from ECJ (https://github.com/eclipse-jdt/eclipse.jdt.core/blob/a96a8bc163398dd385cabc9a462b446399c1bc84/org.eclipse.jdt.core/compiler/org/eclipse/jdt/internal/compiler/problem/messages.properties#L259)
But `"RestrictedIdentifierWhen"` there comes from code being compiled. However _full code snippet_ that it was asked for is incomplete and has no such token.
I see no Java, IDE, nor mockito to be blamed so far.

**Comment by SentryMan** [comment]
Well lads, it looks like my eclipse was to blame. regular mvn builds seems to work. Apologies for the the time wasted.
