### ISSUE TITLE
The constructor simulation case in Mockito is not available

### ISSUE THREAD

**Issue by YAGAMIL** [mockito/mockito#2757]
I used it in my code
`new OSSClient(String.class, DefaultCredentialProvider.class, ClientConfiguration.class)`
I refer to this  [document(https://javadoc.io/static/org.mockito/mockito-core/4.8.0/org/mockito/Mockito.html#mocked_construction)](https://javadoc.io/static/org.mockito/mockito-core/4.8.0/org/mockito/Mockito.html#mocked_construction)

But such use seems to be ineffective and the case I read is as follows

![image](https://user-images.githubusercontent.com/16757285/191406158-44897b0b-b095-434b-b22e-6628b7f07b7b.png)

My unit test pseudocode is as follows
```java
try (MockedConstruction<OSSClient> mocked = mockConstruction(OSSClient.class)) {
    OSSClient client = new OSSClient("", mock(DefaultCredentialProvider.class), mock(ClientConfiguration.class));
    when(client.generatePresignedUrl(any(), any(), any())).thenReturn(mock(URL.class));
    result = ossManager.getTempDownloadUrl(1L, "osskey", new Date());
    assertNotNull(result);
}
```
`OssManager#getTempDownloadUrl` will call` ossclient#generatepresignedurl` to generate a url
But in this way, result will return null, and the `OSSClient` generated by the constructor is as follows
![image](https://user-images.githubusercontent.com/16757285/191407450-fcb2d516-a27a-49f7-9e66-06d19576fcc8.png)

This case confirms that the official Javadoc cases I refer to are invalid or incorrect
But I found it somewhere else and it works
And this way of using is not reflected in the document, I think the document needs to be improved and improved, I saw that there are some other overloaded methods are not related to the case to explain

```java
try (MockedConstruction<OSSClient> mocked = mockConstruction(OSSClient.class,
		(mock, context) -> when(mock.generatePresignedUrl(any(), any(), any())).thenReturn(mock(URL.class)))) {
	result = ossManager.getTempDownloadUrl(1L, "osskey", new Date());
	assertNotNull(result);
}
```
In this way, although the construction generated 'OSSClient' is still
![image](https://user-images.githubusercontent.com/16757285/191409561-a01d9d59-edbc-4f55-b438-06be6efd0739.png)
But url is the URL instance of Mock
![image](https://user-images.githubusercontent.com/16757285/191409634-b606b059-e57b-4210-b82e-a713c0ae71b8.png)

Second, I also found that in the above case, I specified that the method return null on the second call or throw an exception, but this did not work

```java
try (MockedConstruction<OSSClient> mocked = mockConstruction(OSSClient.class,
		(mock, context) -> when(mock.generatePresignedUrl(any(), any(), any())).thenReturn(mock(URL.class)).thenReturn(null)
		)) {
	result = ossManager.getTempDownloadUrl(1L, "osskey", new Date());
	assertNotNull(result);

	result = ossManager.getTempDownloadUrl(1L, "osskey", new Date());
	assertNull(result);
}

```
The second call also returns a mock URL object
![image](https://user-images.githubusercontent.com/16757285/191410275-e54b5e4a-e5d9-4614-9cf1-74b6a610a709.png)
Specifying that a second call to 'thenThrow()' does not work either
![image](https://user-images.githubusercontent.com/16757285/191410545-3f6af018-c3ad-407a-aa56-3ab1a908cb33.png)

So if I want to verify the return value of the second time or simulate an exception, I have to write this
```java
try (MockedConstruction<OSSClient> mocked = mockConstruction(OSSClient.class,
		(mock, context) -> when(mock.generatePresignedUrl(any(), any(), any())).thenReturn(mock(URL.class))
				.thenThrow(new ClientException()))) {
	result = ossManager.getTempDownloadUrl(1L, "mirror_file", new Date());
	assertNotNull(result);
}
try (MockedConstruction<OSSClient> mocked = mockConstruction(OSSClient.class, (mock,
		context) -> when(mock.generatePresignedUrl(any(), any(), any())).thenThrow(new ClientException()))) {
	result = ossManager.getTempDownloadUrl(1L, "mirror_file", new Date());
	assertNull(result);
}

```

**Comment by TimvdLippe** [comment]
When you mock the constructor, it will return a mock. Therefore, your `new OSSClient("", mock(DefaultCredentialProvider.class), mock(ClientConfiguration.class));` will ignore the two mocks you pass in and give you a brand new OSSClient that doesn't have anything in it.

Since the constructed object is a mock, it isn't initialized using the regular flows. If you rely on the fields being initialized using the regular constructor, you should use a Spy instead (and create a real object by invoking the constructor).
