### ISSUE TITLE
Mockito.spy on relocated object gets incorrect result

### ISSUE THREAD

**Issue by viirya** [mockito/mockito#2761]
Hi Mockito developers,

Recently we have encountered an issue about Mockito on relocated object. The thing is that we are going to make a jar as shadow one by relocating its dependencies inside. However, some codes working before cannot work after it. These codes are based on Mockito.spy, e.g.:

```java
public class A {
  HiveClientPool clients;

  public void func() {
      HiveClientPool clientPool = new HiveClientPool(2, new Configuration());  // this will initiate `ClientPoolImpl` with pool size 2. clientPool.clients are initiated
  
      clients = Mockito.spy(clientPool); // clients.clients becomes null after spying on `clientPool`
  }

  public void otherFunc() {
    // Some codes use `clients`
  }
}
```

`HiveClientPool` extends an abstract class `ClientPoolImpl` where the constructor initiates a variable:

```
public ClientPoolImpl(int poolSize) {
    this.clients = new ArrayDeque<>(poolSize);
}
```

Before relocation, the `clients` from `Mockito.spy` works well. After relocation, we got NPE when accessing `clients` inside `ClientPoolImpl` through the spy-ed clients.

Is it a bug or is there anything we need to do to make `Mockito.spy` work for relocated object?

Environment:

Mockito Version: 3.7.7/3.12.4
Scala 2.12 + Java 11
MacOS 12.6 on M1 Macbook Pro

**Comment by TimvdLippe** [comment]
If you are shadowing classes, it means that Mockito most likely resolves to the original location and can't find it. If you are shadowing classes, make sure to also update infrastructure such as your `ClassLoader` to correctly resolve the classes for Mockito.

**Comment by viirya** [comment]
Thanks @TimvdLippe for the feedback.

Actually we are removing the relocation now. But the spy object is still not working.

I simplified it further to test.

```java
class TestMock {
  private int testInt = -1;

  public TestMock() {
    this.testInt = 1;
  }

  public int getTestInt() {
    return testInt;
  }
}
```

Then I get a spy object:

```java
TestMock testMock1 = new TestMock();
TestMock testMock2 = Mockito.spy(testMock1);
```

I suppose that `testInt` of `testMock1` and `testMock2` should be same. But `testMock1.getTestInt()` returns 1, and `testMock2.getTestInt()` return 0.

So it seems that `spy` doesn't copy the status of `testMock1` and also doesn't invoke `TestMock` constructor.

**Comment by viirya** [comment]
FYI, the above issue was resolved after upgrading to newer Mockito library.
