### ISSUE TITLE
Give me some sugar with @MockitoTest instead of @ExtendsWith(MockitoExtension.class)

### ISSUE THREAD

**Issue by HerrDerb** [mockito/mockito#2762]
Mockito ist great for unit testing. I use it a lot. But the first thing I always do is to create a new Annotation:

```
@ExtendWith(MockitoExtension.class)
@Retention(RetentionPolicy.RUNTIME)
@Target(ElementType.TYPE)
public @interface MockitoTest {}
```

Its much more handy and readable to just write `@MockitoTest` instead of `@ExtendsWith(MockitoExtension.class)` which looks very technical.

This `@MockitoTest` could be part of the library.

**Comment by TimvdLippe** [comment]
We would like to keep mockito-core lean and minimal on its own. Such an annotation sounds good, but we recommend shipping it in your projects.
