### ISSUE TITLE
How to spy object construction?

### ISSUE THREAD

**Issue by achifal** [mockito/mockito#2769]
Is there a way to spy construction? I can write something like
```
try (MockedConstruction<A> mock = Mockito.mockConstruction(
        A.class, Mockito.withSettings().defaultAnswer(Answers.CALLS_REAL_METHODS)
)) 
```
And then get the desired object through `mock.constructed()`. But in this case, I get a `NullPointerException` because the object's constructor was not called and the fields I needed were not initialized. That is, when some real method is called (due to `CALLS_REAL_METHODS`), then my fields are still not initialized. Also, I don't want to mock those fields, I just want the actual constructor to be called.

**Comment by TimvdLippe** [comment]
If you rely on the real fields to be constructed as normal, you should create a normal spy and inject it into your subject-under-test. If you mock the constructor, then the regular constructor will not be invoked and the fields remain as-is. This is by design.

**Comment by janimationd** [comment]
For older code or code we don't own, we don't always have the option to modify the code to use dependency injection. It seems the best way to do this should be using `spiedInstance()`:
```
Foo foo = new Foo();
try (var ignored = mockConstruction(Foo.class, withSettings().spiedInstance(foo))) {
   ...
}
```
But this doesn't seem to work. Any ideas for how to accomplish this?

**Comment by pbertie** [comment]
I managed to get this working without `spiedInstance()`, I hit the same issues when setting it to call real methods. If you mock each method to point to a real class it can work, not very fun if you need lots of methods to hook up. Also, if you are going to have more than once instance created that would get complicated as you need to create the real instances before the try block.

Note: You must use `doAnswer()` rather than `when()` so calls are made to the real class on each invocation.

```java
final ByteArrayInputStream inputStream = new ByteArrayInputStream("1\n2\n3\n".getBytes(UTF_8));
final BufferedReader reader = new BufferedReader(new InputStreamReader(inputStream, UTF_8));
try (final MockedConstruction<BufferedReader> mockedBufferReader = mockConstruction(BufferedReader.class,
        withSettings().spiedInstance(reader),
        (mock, context) -> doAnswer(invocation -> reader.readLine()).when(mock).readLine())) {

    //doTestStuffThatReadsAllContent();

    final BufferedReader mockReader = mockedBufferReader.constructed().getFirst();
    verify(mockReader, times(4)).readLine();

} catch (IOException e) {
    fail("Unexpected Exception");
}
```
