### ISSUE TITLE
Is there any plan to mock a private static void method?

### ISSUE THREAD

**Issue by pandaapo** [mockito/mockito#2773]
Is there any plan to support mocking a  `private static void` method in the future?

**Comment by TimvdLippe** [comment]
No we don't support stubbing private methods.

**Comment by pandaapo** [comment]
> No we don't support stubbing private methods.

Thanks. Is there any plan to support injecting a `private static final` field in the future?

**Comment by TimvdLippe** [comment]
No. You can use regular reflection to do so.
