### ISSUE TITLE
Checksum fail for mockito-core v. 4.8.1 from Maven central

### ISSUE THREAD

**Issue by m2ger** [mockito/mockito#2774]
Currently using mockito-core and mockito-inline version 4.8.0. When checking for updates with Maven, the following error is shown for mockito-core; not for mockito-inline for which Maven reports that a newer version in available:
```
$ mvn -U versions:display-dependency-updates
...
[INFO] artifact org.mockito:mockito-inline: checking for updates from central
[INFO] artifact org.mockito:mockito-core: checking for updates from central
[WARNING] *** CHECKSUM FAILED - Checksum failed on download: local = '00ff2e8bdb88c732d394596688971d6377e5b914'; remote = '4fdade104ea957631aeb57082146766d40426c74' - RETRYING
[WARNING] *** CHECKSUM FAILED - Checksum failed on download: local = '00ff2e8bdb88c732d394596688971d6377e5b914'; remote = '4fdade104ea957631aeb57082146766d40426c74' - IGNORING
...
[INFO] The following dependencies in Dependencies have newer versions:
...
[INFO]   org.mockito:mockito-inline ............................ 4.8.0 -> 4.8.1
```

**Comment by TimvdLippe** [comment]
Which checksum are you comparing it to? The checksum for `mockito-core:4.8.1` is `1327bd8e0fab61be72d2cbe8b7b72f789f88644c9d5da5be23f9ec2a47c476ce` (https://repo1.maven.org/maven2/org/mockito/mockito-core/4.8.1/mockito-core-4.8.1.jar.sha256)

**Comment by m2ger** [comment]
Maven is checking this one for updates: https://repo1.maven.org/maven2/org/mockito/mockito-core/maven-metadata.xml.sha1

```
$ curl https://repo1.maven.org/maven2/org/mockito/mockito-core/maven-metadata.xml.sha1
4fdade104ea957631aeb57082146766d40426c74t
$ wget https://repo1.maven.org/maven2/org/mockito/mockito-core/maven-metadata.xml
$ sha1sum maven-metadata.xml
00ff2e8bdb88c732d394596688971d6377e5b914  maven-metadata.xml
```

The sha1 matches for mockito-online, for example.

**Comment by TimvdLippe** [comment]
Hm, we don't control these files. So I fear this is a maven-central problem 😢 Looking at the content, it lists 4.8.0 as the latest version (https://repo1.maven.org/maven2/org/mockito/mockito-core/maven-metadata.xml) which is indeed incorrect.

I will contact maven-central and attempt to get this resolved. Thanks for reporting!

**Comment by m2ger** [comment]
Thanks. And, just to be clear that downloading mockito-core 4.8.1 from maven central does not have any issues; just checking for newer versions.

**Comment by TimvdLippe** [comment]
Yes, I marked it as minor for now, since most of the integrations are working as expected. Still, it would be good to get this sorted out.

**Comment by m2ger** [comment]
This has been fixed. https://repo1.maven.org/maven2/org/mockito/mockito-core/maven-metadata.xml has now:
```xml
<latest>4.8.1</latest>

<lastUpdated>20221021175233</lastUpdated>
```

and the checksum also matches.
