### ISSUE TITLE
Incorrect default return values for generic Type overridden methods (with fix)

### ISSUE THREAD

**Issue by DanielZlotin** [mockito/mockito#278]
Using version 2.0.2-beta, observed with previous versions.

Default return values returns null on invocation by mock of methods with T return type, where T is defined as method parameter, even when this method is overridden in subclass with a specific primitive wrapper class.

Example:

```java

abstract class BaseFoo<T> 
{
    public abstract T bar();
}

class Foo extends BaseFoo<Integer> 
{
    @Override
    public Integer bar() {
        return 0;
    }
}

class Moo
{
	public <T> T doBar(final BaseFoo<T> foo)
	{
		return foo.bar();
	}
}


@Test 
public void test() {
    int result = mock(Moo.class).doBar(new Foo());    //   NullPointerException!
    assertThat(result).isNotNull().isZero();    //  even when assigned to Integer, still null.
}

```

This happens because type erasure of the method return type. 

I managed to solve this by checking equality of the generic return type against each generic type parameter in the Method arguments, then using Google GSON's TypeToken to find the actual raw type from the Invocation's arguments (corresponding by index)
This is not perfect but its working in my test suite of 2600+ tests (under 2.5 seconds)

```java

public class Issue278Answers implements Answer<Object>
{
	private final Answers	delegate	= Answers.RETURNS_DEFAULTS;
	
	@Override
	public Object answer(final InvocationOnMock invocation) throws Throwable
	{
		final Object r = delegate.answer(invocation);
		if (r != null)
			return r;
		return getGenericDefaultReturnValue(invocation);
	}
	
	private Object defaultReturnValue(final Class<?> type)
	{
	   ... taken from RETURN_DEFAULTS ...
	}
	
	private Object getGenericDefaultReturnValue(final InvocationOnMock invocation)
	{
		final Method m = invocation.getMethod();
		if (m.getGenericReturnType() instanceof Class)
			return defaultReturnValue((Class<?>) m.getGenericReturnType());
		for (int i = 0; i < m.getGenericParameterTypes().length; i++)
			if (invocation.getArguments()[i] != null && isSameGenericReturnType(m.getGenericReturnType(), m.getGenericParameterTypes()[i]))
				return getGenericReturnValue(invocation.getArguments()[i]);
		return null;
	}
	
	private Object getGenericReturnValue(final Object argument)
	{
		final Type returnType = TypeToken.getSuperclassTypeParameter(argument.getClass());
		final Class<?> resultType = TypeToken.get(returnType).getRawType();
		return defaultReturnValue(resultType);
	}
	
	private boolean isSameGenericReturnType(final Type genericReturnType, final Type genericParameterType)
	{
		return genericParameterType instanceof ParameterizedType && ((ParameterizedType) genericParameterType).getActualTypeArguments().length == 1
				&& ((ParameterizedType) genericParameterType).getActualTypeArguments()[0] == genericReturnType;
	}
}

--------


@Test 
public void test() {
    int result = mock(Moo.class, new Issue278Answers()).doBar(new Foo());
    assertThat(result).isNotNull().isZero();    //  passes
}
```

**Comment by bric3** [comment]
@DanielZlotin Thanks for reporting. Generic return type is still a work in progress, have tried the latest beta ?

Could you make a Pull Request ?

**Comment by DanielZlotin** [comment]
I just realized I'm using `'org.mockito:mockito-all:+'` which is deprecated. I switched to `'org.mockito:mockito-core:+'` but without my fixed `Answers` I'm still getting `null` instead of zeros and empty `List`s etc.

Sure, I'll make a pull request but how is integrating with `TypeToken` from GSON will work? Do I need to provide tests for it? what about licensing?

**Comment by bric3** [comment]
I took time to look into your code, rather than on the phone. I'm not sure what this code is supposed to assert as `Moo` is mocked and `Foo` is a concrete implementation.

Anyway, in this code example there is type erasure (the Java compiler clears any generic types you see in the code). And here `<T> T doBar(final BaseFoo<T> foo)`, the type variable `T` is not bounded so the compiler will erase it as `Object`. Mockito will only see `Object` being returned here, the default value of `Object` is `null`.

--------------------------------

Again I'm not sure how the test is written but since `Moo` is a mock, I'd rather use standard stubbing API to return something, rather than relying on invoking a concrete `Foo` here. Otherwise there's no isolation in this test.

```java
BDDMockito.given(moo_mock.doBar(isA(Foo.class))).willReturn(1_000);
BDDMockito.given(moo_mock.doBar(isA(BaseFoo.class))).willReturn(Collections.emptyList());
```

**Comment by bric3** [comment]
So there nothing really we can do on Mockito. Don't bother do a Pull Request :)

**Comment by DanielZlotin** [comment]
I disagree about the usage and isolation: In my tests `Moo` is a `Network`ing class, and `Foo` is a specific `HttpRequest`. When I test `Foo` obviously I test only `Foo`. Same thing when I test `Moo`. 

But when I test a class which uses the `Network` to call a `HttpRequest` of type `Foo` inside some logical flow of a method, some of the time I specify a response for `Moo` (like your example) , but a lot of the times I want mockito to return smart nulls for `HttpRequests`  (like return false and zero) and not throw `NullPointerException` just because I assign the response to a primitive type. `Moo` is a mock of type `Stub` and all I want is the correct dumb-object behavior rather the test-only case of `NullPointerException`.

`Moo` is a mock (a `stub`) which I pass to the class under test. This is as RSPy as I can see from here

In any case, you have my solution, feel free to use it or not :) Mockito is great! :)

**Comment by bric3** [comment]
I'm not sure I follow you, real code sample would explain much better ;)
Also what is RSP ?

**Comment by DanielZlotin** [comment]
I meant SRP (single responsibility), with regards to isolation.

some quick pseudocode:

```java

public class ClassUnderTest
{
	private final Network	network;
	
	public ClassUnderTest(final Network network)
	{
		this.network = network;
	}
	
	int getUserCount(final UserType type)
	{
		if (type == UserType.Normal)
			return network.performRequest(new GetNormalUsers()).size();
		else
			return network.performRequest(new GetSpecialUserCount());
	}

	public void doSomething()
	{
		if(getUserCount(UserType.Special)>0)
			doSomethingSpecial();
		else
			doSomethingNormal();
	}
        
}

---

public class Network
{
    public <T> T performRequest(final HttpRequest<T> request) {...}
}

---

public abstract class HttpRequest<T> {
...  // creates formal http request with params etc
    protected abstract T parseResponse(HttpResponse response, byte[] content) throws RuntimeException;
} 

---

public class GetNormalUsers extends HttpRequest<List<User>>
{

... // url, params, body, etc...

	@Override
	protected List<User> parseResponse(final HttpResponse response, final byte[] content) throws RuntimeException
	{
		... // parse response and return List<User>
	}
}

---

public class GetSpecialUserCount extends HttpRequest<Integer> {...}

---


The test code:

	@Test
	public void testSomeBehavior() throws Exception
	{
		ClassUnderTest uut = new ClassUnderTest();
		uut.doSomething() // null pointer exception!
                ... other test code ...
	}

```

Now I know all about `when(mock).thenReturn(...)`  and I use it in every place when I need a special return value in order to test some behavior, or when testing things directly connected to the response. But when I don't care about the response of the mock, and all I want is a smart null return value I think Mockito should be smart enough to handle generic return types and not force me to sprinkle my test code with useless stuff like: 
```java
when(network.performRequest(isA(GetNormalUsers.class))).thenReturn(new ArrayList<User>());
when(network.performRequest(isA(GetSpecialUserCount.class))).thenReturn(0);
```
in every test case. 

It just makes the test code less readable where it really shouldn't be as we're talking about empty return values in places where I don't really care about a response. 

Even worst, returning `null` on return type of `List<>` is kinda OK, but return `null` on result of type `int` just blows the code up! because of auto-boxing 
I get NullPointerException if the `HttpRequest` is of type `extends HttpRequest<Integer>` in a code like this:

```java

    int result = mockNetwork.performRequest(new HttpRequest<Integer>{...});

```

My solution handles it pretty good I think and I'm using it with 2600+ tests and no problems yet... 
You already did something very similar to this in your `ReturnsEmptyValues` class but I just took it 1 step further, actually checking the generic return type and comparing it with the input arguments to get the actual response type for the smart nulls.

I hope I made things clear :)
