### ISSUE TITLE
The all SpyBean members is null

### ISSUE THREAD

**Issue by VasilyBorisovich** [mockito/mockito#2781]
Hello,

I am trying to do a test on class with SpyBean dependency,
```
   class Test {
        @SpyBean A a;
	@SpyBean B b;
		
	@Before
        public void setUp() {
          MockitoAnnotations.openMocks(this);
	}

       @Test  public void testA() { .. }
}
```

In real implementation the class A inject class B and another classes.
```
    class A {
	    @Inject 
		B b;
		@Inject 
		C c;
		...
	}
```

In the test scenario I expected that the spy class A will contain a spybean object B, but all members of class a are null.
The spy object b in the Test is not null.
Why are all the members of the spy object a in the Test class is null?

```
versions used
mockito-core-4.0.0.jar
mockito-junit-jupiter-4.0.0.jar
```

**Comment by TimvdLippe** [comment]
`@SpyBean` is not part of Mockito, but a third-party dependency. You need to follow up with the maintainer of that dependency to understand better what is going wrong.
