### ISSUE TITLE
Mocking varargs method with `any(String[].class)` doesn't work as expected

### ISSUE THREAD

**Issue by big-andy-coates** [mockito/mockito#2796]
This issue is related to a resolved issue  https://github.com/mockito/mockito/issues/2644, which was resolved in 4.7.0 by https://github.com/mockito/mockito/pull/2664.

As per the comment by @perlun in the above PR: https://github.com/mockito/mockito/pull/2664#issuecomment-1319816402

@big-andy-coates I found a similar semi-related issue I think... With 4.7.0, this now works correctly:

```java
        doAnswer(answerVoid((VoidAnswer2<String, Object[]>)
                logger::info
        )).when(mock)
                .info(any(), (Object[]) any());
```

_However_, if I try to use this form which is slightly more ergonomic:

```java
        doAnswer( answerVoid( (VoidAnswer2<String, Object[]>)
                logger::info
        ) ).when( mock )
                .info( any(), any( Object[].class ) );
```

...the mocking will fail to intercept these method calls. :thinking: No error when creating the mock, but it just won't detect the method calls as expected.

I _presume_ this has again something to do with the varargs parsing. `javac` resolves those two calls to the correct/same `logger.info()` overload, so so far so good.

Do you want me to create a separate issue/repro repo for this? I'm not even sure if it's something that can be (easily) fixed, I just happened to see it now while trying to "clean up our code"... :sweat_smile:

_Originally posted by @perlun in https://github.com/mockito/mockito/issues/2664#issuecomment-1319816402_

**Comment by big-andy-coates** [comment]
I've done some digging and the reason the above fails is that Mockito is using the last matcher to match all varags parameters.

Let's simplify the example to make it easier to explain:

For example,

Given:

```java
   String varargMethod(int x, String... args);
```

With setup:

```java
when(theMock.varargMethod(eq(1), any(String[].class)).thenReturn("whatever");
```

When the mock encounters a call like:

```java
theMock.varargMethod(1, "a", "b");
```

It uses the first `eq(1)` matcher to match the first argument, which passes. It then see's there are more parameters to the call than matchers, so it uses the last matcher for any additional arguments, i.e. it tries to match `any(String[].class)` against `"a"` and against `"b"`. Of course, both of these fail and hence the method returns `null`, not `"whatever"`.

If the test code is changed to:


```java
when(theMock.varargMethod(eq(1), any(String.class)).thenReturn("whatever");
```

...then it works.  Indeed, any of the following work:

```java
// Matches any call with one _or more_ String parameters
when(theMock.varargMethod(eq(1), any(String.class)).thenReturn("whatever");
when(theMock.varargMethod(eq(1), any()).thenReturn("whatever");

// Matches any call with two _or more_ String parameters
when(theMock.varargMethod(eq(1), any(String.class), any(String.class)).thenReturn("whatever");
when(theMock.varargMethod(eq(1), any(), any()).thenReturn("whatever");
```

## Conclusion

This could be seen as a bug: the code code see that the last parameter is vararg, and effectively treat the `any(String[].class)` as `any(String.class)`.  However, we'd need to thing through the edge cases of this and how such a change would affect existing usages.

or...

This could be seen as intentional behaviour. 

## Releated

Interestingly, there used to be a [`anyVargs`](https://static.javadoc.io/org.mockito/mockito-core/1.10.19/org/mockito/Matchers.html#anyVararg%28%29) method, but it was removed.

There was also a PR that got close to merging that might have solved this and other varargs related issues...

There are also a whole host of other issues pertaining to issues with varargs.

Unfortunately, I personally don't have time to sift through them all to distill the underlying issues and a suitable solution...

**Comment by TimvdLippe** [comment]
Given our shenanigans with var args, I feel link our current solution is the most pragmatic and least-surprising. As you noted, we have had loads of back-and-forths on the issue of varargs, with numerous competing implementations and surprising behavior with each one. Acknowledging that there are still edge cases that are annoying, I think what we have today is the best we got. So therefore I think I would qualify this as

> This could be seen as intentional behaviour.

**Comment by big-andy-coates** [comment]
I'd kind of agree, given I don't have time to fix what looks to be a complicated issue, and there are workarounds.

But then I got looking into this closely related https://github.com/mockito/mockito/issues/1593, and was thinking about a fix, and I may have a solution.

I'll throw up a hack PR to see if we think the approach can work.
