### ISSUE TITLE
ReturnsDeepStubsConcurrentTest fails with `ArrayIndexOutOfBoundsException`

### ISSUE THREAD

**Issue by big-andy-coates** [mockito/mockito#2808]
I'm noticing a flaky test when testing locally.

`ReturnsDeepStubsConcurrentTest` fails fairly frequently with `java.lang.ArrayIndexOutOfBoundsException`.

The exception is being thrown from `InvocationContainerImpl#getStubbingsAscending()`:

```java
 public Collection<Stubbing> getStubbingsAscending() {
      List<Stubbing> result = new LinkedList<>(stubbed);  <-- THIS LINE THROWS
      Collections.reverse(result);
      return result;
  }
```

...and looks to be caused by `stubbed` not being protected by a `synchronized`.

Happy to fix, but wanted to check its not intentionally this way...

**Comment by TimvdLippe** [comment]
Not intentional. Looking forward to the PR!
