### ISSUE TITLE
CALLS_REAL_METHODS does not respect interface default methods

### ISSUE THREAD

**Issue by sooniln** [mockito/mockito#2818]
CallsRealMethods.java checks for abstract methods (in which case it bails and falls back to default behavior), but does not recognize default methods on interfaces as being non-abstract.

Current code:

```
@Override
public Object answer(InvocationOnMock invocation) throws Throwable {
    if (Modifier.isAbstract(invocation.getMethod().getModifiers())) {
        return RETURNS_DEFAULTS.answer(invocation);
    }
    return invocation.callRealMethod();
}
```

Possible fix:

```
@Override
public Object answer(InvocationOnMock invocation) throws Throwable {
    if (Modifier.isAbstract(invocation.getMethod().getModifiers()) && !invocation.getMethod().isDefault()) {
        return RETURNS_DEFAULTS.answer(invocation);
    }
    return invocation.callRealMethod();
}
```

Rationale: in addition to behaving more like one would expect (why would calling a real method skip default methods - are those not real?), this specifically enables test scenarios for APIs that use default methods for backwards compatibility. Ie:

```
private interface ITest {
  int thing1();

  default int thing2() {
    return 0;
  }
}

@Test
public void testTest() {
  ITest t = spy(ITest.class);
  t.thing2();
  verify(t).thing1();
}
```

**Comment by mathieufortin01** [comment]
> but does not recognize default methods on interfaces as being non-abstract

It should. According to `Method.isDefault()`:

> A default method is a public non-abstract instance method, that
     is, a non-static method with a body, declared in an interface
     type.

If your test is right, it feels like its behaving correctly, ie `t.thing1()` not being called, and 0 returned. If you change your interface for the following it should pass correctly (according to a test I just did):
```
private interface ITest {
  int thing1();

  default int thing2() {
    return thing1();
  }
}
```

**Comment by sooniln** [comment]
Sorry, looking back at my comment I clearly had a slight brainfart, but your interpretation is correct. Retesting this, you're right, this works just fine in Java. I think the problem may be Android specific... Let me test that, but in either can I think this can be closed as it doesn't appear to be a mockito issue but perhaps an Android one.
