### ISSUE TITLE
staticMock not returning clean values when mocked

### ISSUE THREAD

**Issue by HerrDerb** [mockito/mockito#2822]
There is weird behaviour with `mockStatic`
When mocking the 'java.time.Instant' class, and defining a non mocked return value, it still behaves in some parts as mocked and some operations do not work as expected

```
    @Test
    void test() {
        Instant now = Instant.now();
        try (MockedStatic<Instant> instantMock = mockStatic(Instant.class)) {
            instantMock.when(Instant::now).thenReturn(now);

            Instant nowFromMock = Instant.now();
            assertEquals(now, nowFromMock);
            Instant future = nowFromMock.plus(Duration.ofSeconds(1));
            assertNotNull(future); // this should not be null, but currently is
        }
    }
```
Dependency: org.mockito:mockito-inline
Version: 4.9.0

**Comment by BegBang** [comment]
You can use Mockito.CALLS_REAL_METHODS to correct this behaviour:
`try (MockedStatic<Instant> instantMock = mockStatic(Instant.class, CALLS_REAL_METHODS)) {`
