### ISSUE TITLE
Change in final hashCode behavior between mockito-core vs mockito-inline

### ISSUE THREAD

**Issue by aswath80** [mockito/mockito#2837]
Mockito-core's default behavior calls the real final method on mocks. When switching to mockito-inline, the real final methods are no longer invoked. There are final overriden hashCode implementations that were previously invoked by default by mockito-core that are no longer invoked by mockito-inline. Also mockito-inline does not allow hashCode stubbing. Is there a suggested way around for this problem ?

Versions tested: 4.7, 4.10

`
public class MockitoInlineHashTest {

    static class Sample {

        private final int h;

        Sample(final int h) {
            this.h = h;
        }

        final int hash() {
            return this.h;
        }

        @Override
        public final int hashCode() { // Called by mockito-core but not mockito-inline
            return hash();
        }
    }

    @Test
    void test() {
        final Sample s = mock(Sample.class);

        when(s.hash()).thenReturn(57); // Stubbing works in mockito-core but not in mockito-inline
        //doCallRealMethod().when(s).hashCode(); // Does not work
        System.out.println(s.hashCode());
    }
}
`

**Comment by TimvdLippe** [comment]
`hashCode` can not be stubbed/verified: https://github.com/mockito/mockito/blob/6b818baa1006338501a5fde5ba368593475cee9c/src/test/java/org/mockitousage/misuse/InvalidUsageTest.java#L105-L107 Therefore, you can not rely on Mockito to stub or not stub this method.

**Comment by aswath80** [comment]
Thanks @TimvdLippe , what is the recommendation for using mocks as map keys ? There are cases where the real objects can not be instantiated and mocks are needed and these mocks used as map keys.

With mockito core and subclass mocking, the final hashCode implementation of the mock is invoked and that has changed with mockito inline. I understand the rational behind tests to be independent of mock's hashCode but exploring options that avoids code changes to get around this mockito behavior change from mockito-core to mockito-inline.

**Comment by TimvdLippe** [comment]
You are recommended to use a different object as map key and wrap the mock (type) with it. You shouldn't use mocks or rely on their behaviour to provide stable hashcode and equals, as these typically depend on the fields/getters and these are stubbed out for mocks by default.
