### ISSUE TITLE
Unable to spy @Spy annotated field after migrated spring boot version from 2.7.7 to 3.0.1

### ISSUE THREAD

**Issue by mertbahadir** [mockito/mockito#2853]
Hello Guys,

I am facing an issue and I couldn't find a way to solve this.

Before changing the spring boot version from 2.7.7 to 3.0.1 tests are passing

Mockito versions:
core -> 4.8.1 (coming from spring-boot-starter-test:3.0.1)
inline -> 4.11.0 (defined in pom.xml)
junit-jupiter -> 4.8.1 (coming from spring-boot-starter-test:3.0.1)

```
<spring-boot.version>3.0.1</spring-boot.version>
```

```
  <dependency>
    <groupId>org.springframework.boot</groupId>
    <artifactId>spring-boot-starter-web</artifactId>
    <version>${spring-boot.version}</version>
    <scope>provided</scope>
  </dependency>

  <dependency>
    <groupId>org.springframework.boot</groupId>
    <artifactId>spring-boot-starter-test</artifactId>
    <version>${spring-boot.version}</version>
    <scope>test</scope>
  </dependency>
```

and @Spy annotated field is 

```
    @Spy
    private DefaultListableBeanFactory defaultListableBeanFactory
```

Error Message:
```
org.mockito.exceptions.base.MockitoException: Unable to initialize @Spy annotated field 'defaultListableBeanFactory'.

Mockito cannot mock this class: class org.springframework.beans.factory.support.DefaultListableBeanFactory.
```

**I just found that main cause is spring version change from 5.x to 6.x because when I changed the version of spring-beans to 5.3.24 tests are ok. but with version 6.x they are all failing. Mockito cannot mock DefaultListableBeanFactory class after spring version 6.x**

Java               : 17
JVM vendor name    : Amazon.com Inc.
JVM vendor version : 17.0.5+8-LTS
JVM name           : OpenJDK 64-Bit Server VM
JVM version        : 17.0.5+8-LTS
JVM info           : mixed mode, sharing
OS name            : Mac OS X
OS version         : 12.2.1

Can you help me to solve this problem?
If more details are needed I'm happy to provide.
Thanks in advance.

**Comment by TimvdLippe** [comment]
This is unlikely to be related to Mockito. Please contact the maintainers of Spring Boot at https://github.com/spring-projects/spring-boot/ for further assistance.

**Comment by mertbahadir** [comment]
Thank you so much for help <3
