### ISSUE TITLE
Make sure the tests use mock maker with intended member accessor

### ISSUE THREAD

**Issue by reta** [mockito/mockito#2855]
It seems like there is a gap in tests: the tests get mock maker instance (from environment setting) but not the member accessor it supposed to be used with. As such, the tests used reflection, not module accessor, all the time (see please https://github.com/mockito/mockito/pull/2834#issuecomment-1374876590).

check that

 - [ ] The mockito message in the stacktrace have useful information, but it didn't help
 - [ ] The problematic code (if that's possible) is copied here;
       Note that some configuration are impossible to mock via Mockito
 - [ ] Provide versions (mockito / jdk / os / any other relevant information)
 - [ ] Provide a [Short, Self Contained, Correct (Compilable), Example](http://sscce.org) of the issue
       (same as any question on stackoverflow.com)
 - [ ] Read the [contributing guide](https://github.com/mockito/mockito/blob/main/.github/CONTRIBUTING.md)

@TimvdLippe I could take it if you don't mind, thank you

**Comment by TimvdLippe** [comment]
Go ahead 👍
