### ISSUE TITLE
Vararg verification failures on 4.11.0

### ISSUE THREAD

**Issue by ZOlbrys** [mockito/mockito#2856]
Consider the following code:

```
package com.xyz.packagexyz

open class TestService {
    fun doSomethingElse(message: String, vararg args: Any) {
        print("message: $message, args: $args")
    }
}

class TestClass(val service: TestService) {
    fun doSomething(message: String, vararg args: Any) {
        service.doSomethingElse(message, args)
    }
}
```

With code testing this:
```
internal class TestClassTest {
    private val mockService = mock<TestService>()
    private val testClass = TestClass(mockService)

    @Test
    fun test() {
        val message = "message"
        val arg1 = "arg1"
        testClass.doSomething(message, arg1)

        verify(mockService).doSomethingElse(message, arrayOf(arg1))
    }
}
```

Using mockito 4.11.0, the test here fails with
```
Argument(s) are different! Wanted:
testService.doSomethingElse(
    "message",
    ["arg1"]
);
-> at com.xyz.packagexyz.TestService.doSomethingElse(TestClass.kt:5)
Actual invocations have different arguments:
testService.doSomethingElse(
    "message",
    ["arg1"]
);
-> at com.xyz.packagexyz.TestClass.doSomething(TestClass.kt:11)
```

On 4.10.0 the test above passes successfully.  Any ideas?

edit: this was also asked on [stackoverflow](https://stackoverflow.com/questions/75034431/mockito-4-11-0-vararg-changes-causes-test-to-fail-how-to-properly-test-vararg) which includes some workarounds that IMO do not make sense to use (I feel like a bug is happening with the code above), but maybe I am mistaken.

**Comment by MrBean355** [comment]
Experiencing the same.

**Comment by TimvdLippe** [comment]
Instead of `arrayOf`, you should use `eq` instead: https://github.com/mockito/mockito/blob/2418419a1915bd234332eac2b4d5de85622d4699/src/test/java/org/mockitousage/matchers/VarargsTest.java#L491

While the behavior did change, the usage of `arrayOf` worked accidentally and the official usage should be `eq`. Therefore, I think this is okay and an instance of https://www.hyrumslaw.com/ Apologies for the convenience!

**Comment by ZOlbrys** [comment]
Thanks for the info @TimvdLippe, unfortunately I'm not able to make my tests pass still.

I tried using `eq` as such: 

```
verify(mockTree).d(eq(message), eq(arrayOf<Any>(arg)))
```
```
verify(mockTree).d(eq(message), eq(arrayOf(arg)))
```
```
verify(mockTree).d(eq(message), eq(Array<Any>(1) { arg }))
```
```
verify(mockTree).d(eq(message), eq(Array(1) { arg }))
```
Which all have the same failure message as the original post.  The second param is clearly expecting an array:

```
Actual invocations have different arguments:
testService.doSomethingElse(
    "message",
    ["arg1"]
);
```
So I need to pass in some sort of array object for equals/verification testing.

I also created various the arrays of `Any` and `String` types outside of the verify call and passed it in as a param, etc but all are failing still - am I missing something here? Sorry if so.

`fun doSomethingElse(message: String, vararg args: Any)` has two params.  The first is a regular `String`, the second is a `vararg` of `Any` values.  I think the first regular param is causing this to be different than the example you linked above.

The test you linked is associated with the`int varargs(String... string);` method in `IMethods` right?  Are there any tests similar to what you linked that use a method with two params?  `mixedVarargs` or `mixedVarargsReturningString`, or `varargsString` for example, where the test would check the first value and then the varargs value?

Thank you!

**Comment by TimvdLippe** [comment]
You should use `eq` without `arrayOf` at all:

```
verify(mockTree).d(eq(message), eq(arg))
```

**Comment by ZOlbrys** [comment]
Sorry for mixing my sample code up (`mockTree` in the last post vs `mockService` etc, but this code:

```
    @Test
    fun test() {
        val message = "message"
        val arg1 = "arg1"

        testClass.doSomething(message, arg1)

        verify(mockService).doSomethingElse(eq("message"), eq(arg1))
    }
```

Does not pass the verification.  The output says:

```
Argument(s) are different! Wanted:
testService.doSomethingElse(
    "message",
    "arg1"
);
-> at com.xyz.packagexyz.doSomethingElse(TestClass.kt:5)
Actual invocations have different arguments:
testService.doSomethingElse(
    "message",
    ["arg1"]
);
```

Mockito is expecting an array here.... I think this is the issue.

**Comment by TimvdLippe** [comment]
Hm, this works for Java I am pretty sure. Can you use `mockito-kotlin` and see if that works for you?

**Comment by ZOlbrys** [comment]
Hey @TimvdLippe, when the code under test is written in Java, the tests pass - as you have expected :).  So the issue must be in Kotlin code using varargs interacting with Mockito in some way.

The original kotlin classes are in the original post, so I'll post the Java classes here for reference.

```
public class TestServiceJava {
    public void doSomethingElse(String message, Object... args) {
    }
}

...

public class TestClassJava {
    private final TestServiceJava service;

    public TestClassJava(TestServiceJava service) {
        this.service = service;
    }

    public void doSomething(String message, Object... args) {
        service.doSomethingElse(message, args);
    }
}
```

Using these classes, the kotlin test in the original post (modified to use `eq(arg1)` as directed), as well as a java version of the same tests both pass, using regular mockito for java/kotlin tests and mockito kotlin for kotlin tests (I wanted to test all variations)

So:

- java source code being tested = PASS
- kotlin source code being tested = FAILED

What do you suggest? Is this a mockito issue? (using regular mockito with kotlin source results in failures) - or should I open a ticket against mockito-kotlin (or something else entirely!)

Thank you for the suggestions so far.  I've been super perplexed by this, glad I was able to find the differences in behavior for different languages!

**Comment by TimvdLippe** [comment]
This is probably an issue with `mockito-kotlin` (which we also maintain). Let's move the discussion over there.

**Comment by ZOlbrys** [comment]
Sure, I can create a new issue on `mockito-kotlin` and copy the details.
