### ISSUE TITLE
Default mock of `Optional` is not `empty` when using `RETURN_DEEP_STUBS`

### ISSUE THREAD

**Issue by big-andy-coates** [mockito/mockito#2865]
Version affected: Mockito: 4.x & 5.x

If you create a mock with `RETURN_DEEP_STUBS`, then any method that returns a collection will, by default, return an empty collection, i.e. `isEmpty` returns `true`, etc.  This is great, as it means no additional configuration of the mock is required before passing to logic that would attempt to access elements of the collection.

However, the same is not true for `Optional`, (and I'm assuming `OptionalLong` etc): if `RETURN_DEEP_STUBS` is used, methods that return `Optional` aren't treated in any special way and just return a default mock with not stubbing configured. This means `isEmpty` returns `false`, but `get()` returns `null`.   This breaks the contract of `Optional`, causing test failures that aren't actually valid, or requiring manual configuration of the `Optional` mock to do-the-right-thing, cluttering test code.

Here's an example test that demonstrates this:

```java
interface Address {
   Optional<String> getState();
}

@Test
public void shouldDefaultDeepMockOptionalsToEmpty() {
    final Address address = mock(Address.class, RETURNS_DEEP_STUBS);

    assertThat(address.getState()).isEqualTo(Optional.empty());  // <--- fails
}

@Test
public void shouldDefaultMockOptionalsToEmpty() {
    final Address address = mock(Address.class); // <-- no RETURNS_DEEP_STUBS

    assertThat(address.getState()).isEqualTo(Optional.empty());  // <--- passes
}
```

Note the second test, which doesn't use deep mocking, passes.

 - [x] The mockito message in the stacktrace have useful information, but it didn't help
 - [x] The problematic code (if that's possible) is copied here;
       Note that some configuration are impossible to mock via Mockito
 - [x] Provide versions (mockito / jdk / os / any other relevant information)
 - [x] Provide a [Short, Self Contained, Correct (Compilable), Example](http://sscce.org) of the issue
       (same as any question on stackoverflow.com)
 - [x] Read the [contributing guide](https://github.com/mockito/mockito/blob/main/.github/CONTRIBUTING.md)

**Comment by big-andy-coates** [comment]
Looks like collections suffer the same, defaulting to `isEmpty` being `false`.

**Comment by TimvdLippe** [comment]
This should have been covered in https://github.com/mockito/mockito/blob/0aba0d5b031b4282c9b6686add2b443bda761817/src/main/java/org/mockito/internal/stubbing/defaultanswers/ReturnsEmptyValues.java#L132 but I am not sure why that is breaking. #2731 is supposed to tackle that, but it needs to be rebased. Feel free to submit a PR that fixes this issue!

**Comment by schlosna** [comment]
I'm seeing a similar test failures with deep stubs and methods returning `Optional<Long>` and `OptionalLong` after the upgrade to Mockito 5.x in https://github.com/palantir/tritium/pull/1635 . The exception we see is below:

```
java.lang.ClassCastException: class com.github.benmanes.caffeine.cache.Policy$Eviction$MockitoMock$nsH7a8Ju cannot be cast to class java.lang.Long (com.github.benmanes.caffeine.cache.Policy$Eviction$MockitoMock$nsH7a8Ju is in unnamed module of loader 'app'; java.lang.Long is in module java.base of loader 'bootstrap')
	at com.palantir.tritium.metrics.caffeine.CaffeineStats.lambda$weightedSize$1(CaffeineStats.java:60)
	at com.palantir.tritium.metrics.caffeine.CaffeineCacheMetricsTest.lambda$weightedSize$2(CaffeineCacheMetricsTest.java:87)
	at org.assertj.core.api.AbstractObjectAssert.returns(AbstractObjectAssert.java:1106)
	at com.palantir.tritium.metrics.caffeine.CaffeineCacheMetricsTest.weightedSize(CaffeineCacheMetricsTest.java:87)
```

**Comment by big-andy-coates** [comment]
@schlosna, as far was I'm aware, this was not a regression, just an existing issue, effecting at least the latest 4.x and 5.x versions. 

What version were you updating from?

**Comment by schlosna** [comment]
> @schlosna, as far was I'm aware, this was not a regression, just an existing issue, effecting at least the latest 4.x and 5.x versions. 
> 
> What version were you updating from?

I saw this in https://github.com/palantir/tritium/pull/1635 when upgrading from Mockito 4.11.0 to 5.0.0 and running on JDK 17. 

I tried dropping the tests above into a mockito clone locally, but they did not reproduce. I can try a few more things to try to reproduce.

**Comment by big-andy-coates** [comment]
Should we consider leaving it as a mock, but stubbing the `isPresent` method to return `false`?  This would require the mock to be `lenient`, but I think that's preferable to the current non-sensical defaults.

**Comment by AndreasTu** [comment]
The PR #3097 would now return `true` for all `Optional.isEmpty()` classes when using `RETURNS_DEEP_STUBS`, but the returned objects are still mocks and the behavior can be changed by the user.

The behavior of `Collection.isEmpty()` remains the same.
