### ISSUE TITLE
Broken link in `CONTRIBUTING.md`

### ISSUE THREAD

**Issue by Stephan202** [mockito/mockito#2868]
Something I noticed while opening a PR yesterday: the `CONTRIBUTING.md` file contains [what should be](https://github.com/mockito/mockito/blame/0aba0d5b031b4282c9b6686add2b443bda761817/.github/CONTRIBUTING.md#L57) a link to some document talking about well-designed APIs, except that the link text is an unrelated sentence.

I couldn't trace the revision back to a PR discussion, so unsure what this was meant to link to. Maybe @bric3 remembers?

**Comment by TimvdLippe** [comment]
I think this was a copy-paste error. Let's remove the link and keep just the text.
