### ISSUE TITLE
Unstable test after Mockito 5.0.0 upgrade

### ISSUE THREAD

**Issue by ratoaq2** [mockito/mockito#2874]
I get the following error message in my CI environment, but randomly. Sometimes it fails with this message and sometimes it passes.

```
Unfinished stubbing detected here:
-> at com.sompackage.SomeClassTest.someTestMethod(SomeClassTest.java:258)

E.g. thenReturn() may be missing.
Examples of correct stubbing:
    when(mock.isOk()).thenReturn(true);
    when(mock.isOk()).thenThrow(exception);
    doThrow(exception).when(mock).someVoidMethod();
Hints:
 1. missing thenReturn()
 2. you are trying to stub a final method, which is not supported
 3. you are stubbing the behaviour of another mock inside before 'thenReturn' instruction is completed
 ```

Some information:

We're upgrading from Mockito 4.11.0 to 5.0.0
We're using BDD (given / when / then )
Java 17 - OpenJDK17U-jdk_x64_linux_hotspot_17.0.1_12.tar.gz

We did several CI runs without code change. We use maven with junit jupiter to run our tests in parallel (4 forks):
- Run 1 - All 50k tests were green and no issue
- Run 2 - All 50k tests were green and no issue
- Run 3 - 15 failures with the exception above

What I noticed is that all these 15 failures has a common pattern when mocking the methods (inlining a mock of another class):

```
   given(mockOne.getFoobar()).willReturn(mock(AnotherClass.class));
```

I wish I could provide a failing test scenario, but running the test locally it just passes.

Bellow is a snippet of one of the smallest tests that failed in the last run:
```java
    @Mock
    private EntityDao entityDao;

    @Test
    public void someTest() {
        given(entityDao.readById(123)).willReturn(Arrays.asList(mock(MyEntity.class)));
    }
```

**Comment by ratoaq2** [comment]
Yes, I checked our source code base and I have around 500 cases like this. We can change that if that's not really supported.

What's strange is that it was never failing before (with older Mockito versions) and now it's failing randomly in our CI with Mockito 5.0.0

Since I wasn't sure if that's a bug introduced in the new version, I decided to report. And I wasn't sure about if that inline mock was the problem or not.

**Comment by TimvdLippe** [comment]
It's probably the inline mockmaker. You can try to run with `mockito-subclass` and see if the error persists.

**Comment by ratoaq2** [comment]
I'm willing to stick with the standard mockmaker from Mockito (from 5.0.0 onwards, I believe the inline mockmaker is the one to use)

I just need to understand if we're talking about:
1. a potential bug in the inline mockmaker
2. or an invalid mockito usage that should be avoided: `given(mockOne.getFoobar()).willReturn(mock(AnotherClass.class));`


If `1.` then I can do more tests switching to `mockito-subclass` and see if the issue persists or not

If `2.`, then I'll need to change all violations in our codebase and try to make sure it's not introduced again. If that's an invalid mockito usage, wouldn't be the case for mockito to be strict and always throw an exception in such cases?


And thank you for your prompt response.

**Comment by ratoaq2** [comment]
I have one more information to share. The failures that I have are all for the very same mocked class.

There are several cases where I have:

```
given(mockOne.getOne()).willReturn(mock(ClassOne.class));
given(mockOne.getTwo()).willReturn(mock(ClassTwo.class));
given(mockOne.getThree()).willReturn(mock(ClassThree.class));
```

and the failure occurs on ClassThree... And on other test classes, similar pattern. And the failure only happens for the very same ClassThree

And the ClassThree is an abstract class.

**Comment by ratoaq2** [comment]
I wasn't able to reproduce it locally in a test case.

I'll just document the case, if someone else faces the same issue or similar:

- The issue was happening around 30% of the times when executing our whole test suite in Jenkins.
- We had around 600+ use cases of the pattern `given(mockOne.getOne()).willReturn(mock(ClassOne.class));`
- But the failures were happening only for a specific abstract class (which happens to have almost 3k lines of code 😢 )
- For this class, we had only 40+ occurrences  of the pattern  `given(mockOne.getOne()).willReturn(mock(ClassOne.class));`
- We refactored these 40+ occurrences and now the whole test suite is very stable.

**Comment by TimvdLippe** [comment]
Closing per the above comment. Glad you were able to figure it out!

**Comment by shogv48** [comment]
how was this solved?
