### ISSUE TITLE
Mockito-inline dependency after upgrade 5.0.0

### ISSUE THREAD

**Issue by EugenMayer** [mockito/mockito#2877]
After reading that mockito switched to mockito-inline by default (with 5.0.0) i expected either mockito-core to have a mockito-inline dependency, or mockito-inline has been merged into mockito-core.

Interestingly neither of this is the case (since mockito-inline has a 5.0.0 release and no mockito-inline transitive dependency is found in https://mvnrepository.com/artifact/org.mockito/mockito-core/5.0.0 )

The concrete question is, how should we go about the current explicit dependency on mockito-inline. Should it be removed with 5.0.0 or should it stay?

**Comment by TimvdLippe** [comment]
Good question. For explicitness, you can still depend on mockito-inline, but behaviourally it will have no effect. It would be similar if you would use `mockito-subclass` on Mockito 4. That said, I guess we can remove it in the next release, as it was only used during the transition period for Mockito 5. Not sure if we should simply stop publishing the artifact or we consider that a breaking change for the BOM. @raphw WDYT?

**Comment by raphw** [comment]
I would also say that we remove it. Typically, you'd depend on standard Mockito but we wanted to give a simple pom choice to switch the default as it normally is related to a project's setup. Mockito core contains all code for all mock-makers, but its a configuration file that defines what mock maker is used.

**Comment by TimvdLippe** [comment]
Okay, in that case we should remove `mockito-inline` as our subproject (https://github.com/mockito/mockito/blob/91223f830552ce3bb5daf7095f4f30767e072b96/settings.gradle.kts#L6) and the actual subproject (https://github.com/mockito/mockito/tree/main/subprojects/inline)

**Comment by EugenMayer** [comment]
Nice that the removal took the price here, since i also think this makes life easier for all sides IMHO. It is easier to maintain (less packages to publish), easier to upgrade for the user and easier in the dependency handling / docs too.

Thank you for working on that @valfirst !

**Comment by CharlelieBouvier** [comment]
What about performance issues. Bytecode injection is very slow compared to subclass. Why is this not mentioned si the changelog ?

**Comment by dhrubo-os** [comment]
I tried :

`testImplementation group: 'org.mockito', name: 'mockito-core', version: '5.5.0'`

and

`testImplementation group: 'org.mockito', name: 'mockito-inline', version: '5.2.0'`


But both cases I'm facing issue like:

```
The used MockMaker SubclassByteBuddyMockMaker does not support the creation of static mocks

Mockito's inline mock maker supports static mocks based on the Instrumentation API.
You can simply enable this mock mode, by placing the 'mockito-inline' artifact where you are currently using 'mockito-core'.
Note that Mockito's inline mock maker is not supported on Android.
org.mockito.exceptions.base.MockitoException: 
The used MockMaker SubclassByteBuddyMockMaker does not support the creation of static mocks

Mockito's inline mock maker supports static mocks based on the Instrumentation API.
You can simply enable this mock mode, by placing the 'mockito-inline' artifact where you are currently using 'mockito-core'.
Note that Mockito's inline mock maker is not supported on Android.
```


My code is:

```
    try (MockedStatic<RestActionUtils> loader = Mockito.mockStatic(RestActionUtils.class)) {
            loader.when(() -> RestActionUtils.isSuperAdminUser(clusterService, client)).thenReturn(true);
        }
```

where `isSuperAdminUser` is a static method


Any guidance will be helpful. Thanks.
