### ISSUE TITLE
Mickito 5.0 breaks vararg argument capture in Kotlin

### ISSUE THREAD

**Issue by emartynov** [mockito/mockito#2878]
All code and tests are Kotlin code.

Have code: 

```
class PreferencesRepository {
    suspend fun getPreferences(
        vararg preferences: String
    ): Map<String, Any> 
{}
```

Write tests:
```
        val preferencesRepository: PreferencesRepository = mock()
        val preferencesCapture = argumentCaptor<String>()
        whenever(preferencesRepository.getPreferences(anyVararg())) doReturn emptyMap()

        verify(preferencesRepository).getPreferences(preferencesCapture.capture())
```

Run test and observe:
```
at PreferencesRepository.getPreferences(PreferecesRepository.kt:11)
Actual invocations have different arguments:
preferencesRepository.getPreferences(
    [String, String]
);
```

**Comment by emartynov** [comment]
I also tried to find a java test for this case and could not find it.

**Comment by TimvdLippe** [comment]
This breaking change is documented in the release notes. Please use `any` with the appropriate type.

**Comment by emartynov** [comment]
@TimvdLippe it is an argument capture line and not a stubbing line. We don't use annotations but we use `argumentCaptor` function. 

If I change that line to:
```
        val preferencesCapture = argumentCaptor<Array<String>>()
```

I get a compilation error:
```
Type mismatch 
```

So, I was probably wrong to create issue for mockito project. And I should move it to the kotlin mockito project.
