### ISSUE TITLE
Clean up JDK-8 related code

### ISSUE THREAD

**Issue by reta** [mockito/mockito#2879]
Since Mockito `5.0.0` has JDK-11 baseline (🥳 ), we could clean up all JDK-8 code:
 - Remove `Java8LocationImpl`
 - Remove `Java8LocationFactory`
 - Check for any other places JDK-8 is checked for 
 - Check for any pre-JDK-8 code (https://github.com/mockito/mockito/pull/2731)

@TimvdLippe I think this is a good time to clean up, what do you think? (I could take care of that).

Thank you!

**Comment by TimvdLippe** [comment]
Yes I agree. #2731 already started this, but it stalled
