### ISSUE TITLE
The bytebuddy version used by mockito is incompatible with JDK17

### ISSUE THREAD

**Issue by JoeJoe1989** [mockito/mockito#2885]
> Hey,
>
> First thanks for reporting, in order to help us to classify issue can you make sure the following check boxes are checked ?
>
> If this is about mockito usage, the better way is to reach out to
>
>  - stackoverflow : https://stackoverflow.com/questions/tagged/mockito
>  - the mailing-list  : https://groups.google.com/forum/#!forum/mockito / mockito@googlegroups.com
>    (Note mailing-list is moderated to avoid spam)
>
> _This block can be removed_
> _Something wrong in the template fix it here `.github/ISSUE_TEMPLATE.md`

check that

 - [ ] The mockito message in the stacktrace have useful information, but it didn't help
 - [ ] The problematic code (if that's possible) is copied here;
       Note that some configuration are impossible to mock via Mockito
 - [ ] Provide versions (mockito / jdk / os / any other relevant information)
 - [ ] Provide a [Short, Self Contained, Correct (Compilable), Example](http://sscce.org) of the issue
       (same as any question on stackoverflow.com)
 - [ ] Read the [contributing guide](https://github.com/mockito/mockito/blob/main/.github/CONTRIBUTING.md)

Hi,

I got an error "java.lang.NoSuchMethodException: java.security.AccessController.reflected$doPrivileged(java.security.PrivilegedAction)
" when building in JDK 17 and this was attributed to bytebuddy shaded by mockito.

<img width="713" alt="image" src="https://user-images.githubusercontent.com/6061826/214393762-ff2d7ba8-87f8-461e-a243-782584aceaee.png">

What is the current version of bytebuddy that is being used by mockito? Would you be able to upgrade the bytebuddy version to >=1.12.19 per [release note](https://github.com/raphw/byte-buddy/blob/master/release-notes.md) which hopefully address the issue.  cc @raphw (author of bytebuddy) 

"Avoid access error when using unsafe API on Java 17 with an active security manager."

**Comment by TimvdLippe** [comment]
Mockito 5.0.0 already uses the latest version of ByteBuddy and is compatible with Java 19+.

**Comment by JoeJoe1989** [comment]
@TimvdLippe Hi, actually, I already upgraded to Mockito 5.0.0 and the error persisted (with stack trace pointing to bytebuddy)

"org.mockito:mockito-core:5.0.0"

**Comment by JoeJoe1989** [comment]
Actually, I already upgraded to Mockito 5.0.0 when I made the original post and I have verified that 5.0.0 is being used. The error and stack trace (as can be seen from the screenshot) pointed to bytebuddy. So I guess the root cause is from bytebuddy side (even with the latest version 1.12.22). cc @raphw

**Comment by joaociardullo** [comment]
Como resolver pessoal
