### ISSUE TITLE
Please enable the PR update button

### ISSUE THREAD

**Issue by TWiStErRob** [mockito/mockito#2900]
Hi, @TimvdLippe [asked for a rebase](https://github.com/mockito/mockito/pull/2894#pullrequestreview-1284064852), but the button is not shown on GitHub, could an admin please enable this setting?

https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/configuring-pull-request-merges/managing-suggestions-to-update-pull-request-branches

Before
![image](https://user-images.githubusercontent.com/2906988/216783968-fa663588-4ee7-421e-91ab-ef2da2b2e6ae.png)

Expected: to have an Update button in the lower right corner.

**Comment by TimvdLippe** [comment]
This option should now be enabled, thanks for the pointer!

**Comment by TWiStErRob** [comment]
Nice, thanks. For the record, the UI changed to:
![image](https://user-images.githubusercontent.com/2906988/216791873-582cc37a-b42d-413f-8cb7-9b11e951063d.png)

**Comment by TWiStErRob** [comment]
(This means contributors can do way more things from the GitHub UI, even from mobile, without a computer ;) )
