### ISSUE TITLE
Undocumented change in the ArgumentCaptor behaviour

### ISSUE THREAD

**Issue by sergeykad** [mockito/mockito#2907]
After switching from Mockito 4.8.0 to 5.1.1 one of my tests started to fail with the following message: 
```
Argument(s) are different! Wanted:
MessageUtil.send(
    <Capturing argument: byte[]>
);
-> at com.company.MessageUtil.send(MessageUtil.java:54)
Actual invocations have different arguments at position [0]:
MessageUtil.send(
    "My text message"
...
```

Apparently, the issue was that the captor was declared as `ArgumentCaptor<byte[]> captor;`  but the validated method is declared as `MessageUtil.send(Object obj)`. Changing the captor to `ArgumentCaptor<Object> captor;` solved the issue.

The same captor worked correctly in the earlier Mockito version and its Javadoc states the following: "This utility class *doesn't do any type checks*. The generic signatures are only there to avoid casting in your code."

**Comment by TimvdLippe** [comment]
This was implemented in #2842 and is an intended change, but we indeed forgot to document it. I have added this to the release notes of Mockito 5: https://github.com/mockito/mockito/releases/tag/v5.0.0
