### ISSUE TITLE
Bad performance after upgrading from 1.9.5

### ISSUE THREAD

**Issue by actunderdc** [mockito/mockito#2909]
After upgrading Mockito from version 1.9.5 to version 3.7.7, the performance of our unit tests is very bad. More specific, it seems that it takes about 1 second to start any suite of tests from a class file. From what we have tried to profile, the majority of the time is consumed until the first @Mock is realized. As a concrete example, using Mockito 1.9.5, the time to start the first test of a class was about 0,8 seconds, now it is between 1,8-2 seconds. We are using Java 11 and the problem reproduces on both Windows & Linux.

We digged further this problem and created a sample application to show the performance degradation:
https://github.com/actunderdc/MockitoPerformance

In this project, simply replacing **Mockito 5.1.1 with 1.9.5** means almost half of the execution time (70-80 ms instead of 120-130ms). Strangely, it seems that JUnit 4.12 vs 4.13.2 also matters, but despite the JUnit version chosen, the performance with Mockito 5.1.1 was always poorer. A table with concrete execution times can be seen in the readme.md file from the sample application I provided.

It may seem a small difference in milliseconds, but in our sample project we are having only one service, one repository and one test class. We suppose that once the project grows with more and more services and mocks, the gap of execution time between Mockito versions increases.
In production, 1 extra second for each test class makes a huge difference :(.

FYI: @raphw

**Comment by raphw** [comment]
Are you running single tests or a whole suite? It's documented how attaching an agent costs, and what can be done to reduce this cost by preattaching it. Furthermore, you can explicitly use the subclass agent, if you want to avoid paying the extra price and have no plans of updating to Java 17.

**Comment by actunderdc** [comment]
We are running a whole suite, we noticed that the time has increased in both scenarios: Whole suite and single tests. We tried adding the **-javaagent:C:\Users\blabla\.ivy2\cache\byte-buddy-agent\byte-buddy-agent-1.12.23.jar** parameter to the VM arguments, but we noticed no difference.

Our test suite class looks like this:

**_@RunWith(ClasspathSuite.class)
@ClassnameFilters({ "package.test.*", "package.util.*" })
@IncludeJars(true)
public class AllTestsSuite {
}_**

Are we missing something here? Can you link us to the documentation on how to use the (sub)agent? Thank you very much in advance!

**Comment by raphw** [comment]
That sounds unlikely, either the agent should speed up things or at least the class cache which avoids the duplicate instrumentation.

Have you tried mockito-subclass?

**Comment by actunderdc** [comment]
Hi @raphw ,

Adding mockito-subclass jar dependency seems to help, but not enough. It's still poorer than Mockito V1. I made a simple Maven Project with only 5 of our tests (I can't upload them to maven as they test some of our proprietary code) and here are the results in 3 different scenarios:

**Mockito V1.9.5 -> 0,677 seconds**
![2023-02-13 14_36_42 261](https://user-images.githubusercontent.com/2520276/218460406-b55efba9-5050-4c4b-86cf-9a9410db03bd.png)


**Mockito V5.1.1 (without mockito-subclass) -> 3,542 seconds**
![2023-02-13 14_38_16 837](https://user-images.githubusercontent.com/2520276/218460615-52b506ea-b60c-4eb7-8233-b29c6b72d71b.png)


**Mockito V5.1.1 (with mockito-subclass) -> 1,665 seconds**
![2023-02-13 14_39_30 031](https://user-images.githubusercontent.com/2520276/218460787-60c8bb47-f724-4a1e-8bfb-796773d245af.png)

As it can be easily spotted, mockito-subclass reduces the time from 3,542s to 1,665s but it is still a lot compared to 0,677s.

I am also attaching below a VisualVM snapshot from production (Mockito 3.7.7 there, no mockito-subclass; PowerMock 2.0.4 there also) with our more than 3600 tests which take about 6 minutes to complete. The bytebuddy class seems to do some costly operations:

[Production_Mockito_3.7.7.zip](https://github.com/mockito/mockito/files/10722317/Production_Mockito_3.7.7.zip)

![2023-02-13 14_16_51 025](https://user-images.githubusercontent.com/2520276/218462681-f9f504d9-34f6-42dd-b61a-58c269de006d.png)

![2023-02-13 14_18_00 788](https://user-images.githubusercontent.com/2520276/218462869-9f76c833-c157-46a3-8d14-716196b67b71.png)

**Comment by raphw** [comment]
Mockito used to be much simpler. Also, the previous code generation missed many corner cases. Finally, even if we removed the many additional checks we add to secure functional mocking, and reverted back to using subclass mocking, it would not work on Java 17 and up, or with the module system. So there is not much we can do about all that. 

There's a `ProxyMockMaker` (check the javadoc), if you only mock interfaces, this might be a satisfactory alternative.

**Comment by actunderdc** [comment]
Thank you, @raphw , for your suggestion. Indeed, with **ProxyMockMaker**, the mocking of interfaces is really fast, but as far as I understood from the documentation (and tested), using this option limit us to only mocking interfaces, other classes cannot be mocked the "standard" way.

**Comment by raphw** [comment]
No, the JVM does not support the constructor workaround without using an agent from JDK 17 upwards. Then mockito-inline is the way to go.

**Comment by actunderdc** [comment]
Thank you for all the information, things are clearer for us now, I am closing the ticket.
