### ISSUE TITLE
Use maven import mockito-inline that version is 4.6.1, but mockito-core is 1.10.19

### ISSUE THREAD

**Issue by Qixxxxx** [mockito/mockito#2925]
Hi, I imported dependency for maven project:
<dependency>
                <groupId>org.mockito</groupId>
                <artifactId>mockito-inline</artifactId>
                <version>4.6.1</version>
                <scope>test</scope>
</dependency>
But the verison of mockito-core is not 4.6.1, it is 1.10.19. Low versioncause many methods to be unavailable.

![Snipaste_2023-02-24_17-56-04](https://user-images.githubusercontent.com/57171227/221148992-e95d4e50-d4a8-4351-83af-a7e13de40027.png)

**Comment by TimvdLippe** [comment]
There will be a different dependency that transitively depends on Mockito 1. Use a dependency analysis plugin for your build system to inspect where it is coming from.
