### ISSUE TITLE
Enable Github Discussions

### ISSUE THREAD

**Issue by jfrantzius** [mockito/mockito#2943]
Hi,
I think it would be great to have https://github.com/features/discussions enabled for the Mockito repo as a forum for the wider Mockito community. Some reasons coming to my mind: 
* lowering the barrier to participate: the current mailing list requires another user registration + GMail account
* better UX: mailing list isn't so nicely integrated with Github (link unfurling etc.).
* ability to create separate groups e.g. for Q&A and Mockito development
* fewer issues: if it was easier to discuss problems, people might open fewer issues

Please see https://docs.github.com/en/discussions/quickstart for how to set it up, which sounds relatively easy IMHO.

**Comment by TimvdLippe** [comment]
https://github.com/mockito/mockito/discussions now exists, thanks for the suggestion! Let's see how it evolves and what value it brings.
