### ISSUE TITLE
Mockito 5.2.0 performance loss

### ISSUE THREAD

**Issue by robertotru** [mockito/mockito#2944]
Hello,

I'm trying to migrate my company repositories to Mockito 5.2.0 from version 4.9.0.  Bytebuddy dependency moved from 1.12.18 to 1.14.1.
We also use JUnit 5 and vintage (versions 5.9.1 and related dependencies)

I see for the largest project that overall runtime moved from 5m 10s to 11m 40s.

Any idea for such a big loss? What should I look for?

**Comment by TimvdLippe** [comment]
Can you keep the version of Mockito the same and only update ByteBuddy and see if that makes a difference?

**Comment by robertotru** [comment]
Hello Tim,

Thanks for reaching me out.

Sure, I can give it a try.
I downgraded as suggested. Dependencies are now set as follows
 
 ```kotlin
api("org.mockito:mockito-core:5.2.0") { isTransitive = false }
api("org.mockito:mockito-junit-jupiter:5.2.0") { isTransitive = false }
api("net.bytebuddy:byte-buddy:1.12.18") { isTransitive = false }
api("net.bytebuddy:byte-buddy-agent:1.12.18") { isTransitive = false }
api("org.objenesis:objenesis:3.3") { isTransitive = false }
```    
Didn't change
<img width="202" alt="image" src="https://user-images.githubusercontent.com/2987914/225747143-b115ebca-7b57-4b9f-ba87-17bdf85ab5c7.png">
Still the same runtime (11m and 30s).

**Comment by robertotru** [comment]
Tried the other way round. Set these dependencies

```kotlin
api("org.mockito:mockito-core:4.9.0") { isTransitive = false }
api("org.mockito:mockito-junit-jupiter:4.9.0") { isTransitive = false }
api("net.bytebuddy:byte-buddy:1.14.1") { isTransitive = false }
api("net.bytebuddy:byte-buddy-agent:1.14.1") { isTransitive = false }
api("org.objenesis:objenesis:3.3") { isTransitive = false }
```
and the runtime get back to the usual runtime

<img width="110" alt="image" src="https://user-images.githubusercontent.com/2987914/225751070-b406280d-a636-4dd0-9791-eff5a4c370d3.png">

**Comment by TimvdLippe** [comment]
Right. In that case, it is most likely the mockito-inline mockmaker. You can use `mockito-subclass` to use the old mockmaker, but I would advise you to keep using the inline mockmaker.
