### ISSUE TITLE
Function name is incorrect.

### ISSUE THREAD

**Issue by ByoungJoonIm** [mockito/mockito#2955]
I saw [DoAnswerStyleStubbing](https://github.com/mockito/mockito/blob/96eb5e0cbff80a1545b1093db1baf4e33a2041e7/src/main/java/org/mockito/internal/stubbing/DoAnswerStyleStubbing.java#L27-L29) class code.
I thought that below is correct.

```java
boolean isSet() {
    return !answers.isEmpty();
}
```
After execute `setAnswers` function with answers, instance will return `isSet is false`.
I think it looks strange.

And [InvocationContainerImpl](https://github.com/mockito/mockito/blob/96eb5e0cbff80a1545b1093db1baf4e33a2041e7/src/main/java/org/mockito/internal/stubbing/InvocationContainerImpl.java#L112-L114) also need to be changed as follow.
```java
public boolean hasAnswersForStubbing() {
    return doAnswerStyleStubbing.isSet();
}
```

**Comment by TimvdLippe** [comment]
@ByoungJoonIm Feel free to send us a PR that fixes this.

**Comment by ellaella12** [comment]
Hi I made a pr that fixes this, thank you
