### ISSUE TITLE
ClassCastException when combining InjectMocks with generified Mock field

### ISSUE THREAD

**Issue by jsteenbeeke** [mockito/mockito#2958]
When calling `MockitoAnnotations.openMocks(this);` on a class that contains an `@InjectMocks` target, a ClassCastException occurs when the target has a field that is generified and provided by one of the mocks in said class.

```java
public class OpenMocksTest
{
	@InjectMocks
	protected ConcreteJob job;

	@Mock
	JobInstance<ConcreteJob> instance;

	@BeforeEach
	public void initMocks()
	{
		openMocks(this);
	}

	@Test
	public void testMockExists()
	{
		assertNotNull(job);
	}
}
```

I've attached a Maven project which demonstrates this flaw. Downgrading the Mockito version to `5.1.1` fixes the issue.

[mockito-5.2.0-bug.zip](https://github.com/mockito/mockito/files/11123059/mockito-5.2.0-bug.zip)

**Comment by TimvdLippe** [comment]
Probably a regression introduced in #2923. @jfrantzius can you please take a look?

**Comment by jfrantzius** [comment]
Looking at it...

**Comment by jfrantzius** [comment]
That's an interesting recursive construct  that I'm surprised the compiler accepts, but then there surely shouldn't be a `ClassCastException` anyway ...
```java
public class ConcreteJob extends AbstractJob<ConcreteJob>
```
(a class that uses itself as a type parameter for its superclass? 🤯 )

**Comment by jfrantzius** [comment]
@TimvdLippe WDYT?

**Comment by csdavidson09** [comment]
@jfrantzius I don't think this actually requires recursion to reproduce. I think this might be the same issue I am running into without recursion, please correct me if I am wrong.

[mockito-5.2.0-bug-v2.zip](https://github.com/mockito/mockito/files/11152018/mockito-5.2.0-bug-v2.zip)
