### ISSUE TITLE
Missing maven for v5.3.0

### ISSUE THREAD

**Issue by top-master** [mockito/mockito#2969]
The releases page shows [v5.3.0](https://github.com/mockito/mockito/releases/tag/v5.3.0) being out since a while, but it's not available at:

https://mvnrepository.com/artifact/org.mockito/mockito-core

**Comment by TimvdLippe** [comment]
That site takes about 24 hours before it is up-to-date. The release is already on Maven Central: https://repo1.maven.org/maven2/org/mockito/mockito-core/5.3.0/
