### ISSUE TITLE
Fix for #2958 eliminates CCE but leads to NPE

### ISSUE THREAD

**Issue by cpovirk** [mockito/mockito#2974]
Hi, we have one pesky test ([one from an OfficeDev repo](https://github.com/OfficeDev/ews-java-api/blob/master/src/test/java/microsoft/exchange/webservices/data/sync/ChangeCollectionTest.java)) that starts failing with the recent `@InjectMocks` changes. First it was the `ClassCastException` that was reported in #2958, but after the fix for that, it's a `NullPointerException`:

```
$ git clone git@github.com:cpovirk/ews-java-api.git -b mockitonpe # or check out 3ed334391d09f20e36ecd8e2a0efb3529085e1c6 if you prefer a SHA

$ cd ews-java-api

$ mvn clean install -Dtest=ChangeCollectionTest -Dmaven.javadoc.skip
...
java.lang.NullPointerException
  at org.mockito.internal.configuration.injection.filter.TypeBasedCandidateFilter.getSuperTypes(TypeBasedCandidateFilter.java:79)
  at org.mockito.internal.configuration.injection.filter.TypeBasedCandidateFilter.isCompatibleTypes(TypeBasedCandidateFilter.java:58)
  at org.mockito.internal.configuration.injection.filter.TypeBasedCandidateFilter.lambda$isCompatibleTypes$0(TypeBasedCandidateFilter.java:62)
  ...
```

I'll attach the full log, along with logs from the CCE days and from before the `@InjectMocks` changes.
- NPE: [530.txt](https://github.com/mockito/mockito/files/11237061/530.txt)
- CCE: [521snapshot.txt](https://github.com/mockito/mockito/files/11237062/521snapshot.txt)
- passing: [512snapshot.txt](https://github.com/mockito/mockito/files/11237060/512snapshot.txt)

**Comment by cpovirk** [comment]
Presumably Tim or someone is going to loop in @jfrantzius again, so let me get ahead of the game :)

(As best I can tell so far, the recent changes have been good things, just with the usual growing pains for us as we pick them up.)

**Comment by jfrantzius** [comment]
Hi @cpovirk , when I try to `mvn clean install` that project, I get this error:
```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.3:compile (default-compile) on project ews-java-api: Compilation failure: Compilation failure:
[ERROR] /Users/joerg.frantzius/git/ews-java-api/src/main/java/microsoft/exchange/webservices/data/core/request/ServiceRequestBase.java:[54,25] package javax.xml.ws.http does not exist
[ERROR] /Users/joerg.frantzius/git/ews-java-api/src/main/java/microsoft/exchange/webservices/data/property/complex/TimeChange.java:[43,22] package javax.xml.bind does not exist
[ERROR] /Users/joerg.frantzius/git/ews-java-api/src/main/java/microsoft/exchange/webservices/data/core/request/ServiceRequestBase.java:[406,14] cannot find symbol
[ERROR]   symbol:   class HTTPException
[ERROR]   location: class microsoft.exchange.webservices.data.core.request.ServiceRequestBase<T>
[ERROR] /Users/joerg.frantzius/git/ews-java-api/src/main/java/microsoft/exchange/webservices/data/core/response/ExecuteDiagnosticMethodResponse.java:[128,32] incompatible types: java.util.Iterator<javax.xml.stream.events.Namespace> cannot be converted to java.util.Iterator<javax.xml.stream.events.Attribute>
[ERROR] /Users/joerg.frantzius/git/ews-java-api/src/main/java/microsoft/exchange/webservices/data/property/complex/TimeChange.java:[224,22] cannot find symbol
[ERROR]   symbol:   variable DatatypeConverter
[ERROR]   location: class microsoft.exchange.webservices.data.property.complex.TimeChange
[ERROR] /Users/joerg.frantzius/git/ews-java-api/src/main/java/microsoft/exchange/webservices/data/property/complex/TimeChange.java:[229,22] cannot find symbol
[ERROR]   symbol:   variable DatatypeConverter
[ERROR]   location: class microsoft.exchange.webservices.data.property.complex.TimeChange
[ERROR] -> [Help 1]
```
Are there any magic incantations necessery besides `mvn clean install`?

**Comment by cpovirk** [comment]
Thanks for having a look!

Are you on the `mockitonpe` branch of my fork? The error you're seeing looks like the ones I had at `master`. I had to hack around some problems that arise with a Java version newer than Java 8.

**Comment by jfrantzius** [comment]
Hm, did you push that branch? I can't find it here https://github.com/OfficeDev/ews-java-api/branches/all?query=mockitonpe

**Comment by cpovirk** [comment]
Ah, it's on my fork. (I'm not an OfficeDev developer; we just have the test imported into our own repo.)

https://github.com/cpovirk/ews-java-api/tree/mockitonpe

**Comment by jfrantzius** [comment]
OK, I can reproduce the NPE, having a look ...
