### ISSUE TITLE
In the same test case, CGLIB$CALLBACK_0 have been reset

### ISSUE THREAD

**Issue by stoneCrystal** [mockito/mockito#2977]
In my testcase, I call my two spring bean in my testcase. following is the sample code.
the FundService mock is not correct in callbackService.callback() call. and I found  the CGLIB$CALLBACK_0 been changed when
callbackService.callback() call,  **the invocationContainerImpl stubbed is empty.**

`public class TestTopUpServcie{

@MockBean
private FundService fundservice;

@Autowired
private  TopUpService topupService;

@Autowired
private CallbackService. callbackService;

@Test
public void testTopUp(){

//do the mock 
Mockito.doReturn(new TopupResponse()).when(fundservice).topUp(any());

//in this method call, the mock(fundService.topUp()) is correct, **return the TopUpResponse object.**
topupService.topup();

//in this method call,  the mock(fundService.topUp()) is only **return null object**
callbackService.callback();

}`

mockito version
        <dependency>
            <groupId>org.mockito</groupId>
            <artifactId>mockito-all</artifactId>
            <version>1.10.19</version>
        </dependency>

**Comment by TimvdLippe** [comment]
Please upgrade your version of Mockito.

**Comment by stoneCrystal** [comment]
> org.mockito
> mockito-all
> 1.10.19

**Comment by stoneCrystal** [comment]
> Please upgrade your version of Mockito.

upgrade to which version?
