### ISSUE TITLE
ObjenesisHelper references in MockMaker-independent code

### ISSUE THREAD

**Issue by tomball** [mockito/mockito#298]
A couple of references to org.objenesis classes in code that is otherwise independent of bytecode-based mocks:

src/main/java/org/mockito/internal/stubbing/answers/ClonesArguments.java
src/main/java/org/mockito/internal/stubbing/answers/ThrowsExceptionClass.java

Both of these classes use ObjenesisHelper.newInstance(Class), which differs from Class.newInstance() in that no constructors are called. Is that necessary for these classes? If not, then updating to Class.newInstance() makes Mockito fully platform-independent (at least for platforms that define a MockMaker). If it is necessary, can this call be moved into MockMaker?

I'm happy to make the changes once the team decides on the best approach.

**Comment by szczepiq** [comment]
I'm with you.

The interactions with objenesis should be better isolated. MockMaker might be a reasonable idea. Technically, creating instances of things is not MockMaker's responsibility. So perhaps there is a better way? A different extension point? Check out org.mockito.plugins package.

**Comment by tomball** [comment]
It looks like you already did most of the work! The org.mockito.internal.creation.instance package defines Instantiator with the correct method, so it looks like all that's to be done to make this cross-platform is to move Instantiator to org.mockito.plugins, and update InstantiatorProvider to check for a plugin before assigning a ObjenesisInstantiator to InstantiatorProvider.INSTANCE.

If you're comfortable with that approach, I'll make the changes and submit a pull request.

**Comment by patspam** [comment]
Any updates on this?

**Comment by tomball** [comment]
Fixed in [current source](https://github.com/mockito/mockito/commit/e8640baba7eeaf4d333696492b6868feb115094f). Mockito's TravisCI continuous build successfully built the change, but for some reason since late last June CI builds can't be posted to [Mockito's releases page](https://github.com/mockito/mockito/releases). I guess someone from the project will need to hand-roll the next release, or fix the project's Travis CI configuration.

**Comment by patspam** [comment]
Thanks @tomball !

**Comment by tomball** [comment]
New ObjenesisHelper references were added in release/2.x branch to org/mockito/internal/stubbing/BaseStubbing.java and org/mockito/internal/stubbing/StubberImpl.java.
