### ISSUE TITLE
In the same test case, invocationContainer stubbed have been reset to empty

### ISSUE THREAD

**Issue by stoneCrystal** [mockito/mockito#2980]
In my testcase, I call my two spring bean in my testcase. following is the sample code.
the FundService mock is not correct in callbackService.callback() call. and I found the invocationContainer#stubbed been changed when
callbackService.callback() call, the invocationContainer stubbed is empty.
![image](https://user-images.githubusercontent.com/7323503/232651590-b39e1c8e-607a-4578-87c2-4274eeb5bbd8.png)

`public class TestTopUpServcie{

@MockBean
private FundService fundservice;

@Autowired
private TopUpService topupService;

@Autowired
private CallbackService. callbackService;

@test
public void testTopUp(){

//do the mock
Mockito.doReturn(new TopupResponse()).when(fundservice).topUp(any());

//in this method call, the mock(fundService.topUp()) is correct, return the TopUpResponse object.
topupService.topup();

//in this method call, the mock(fundService.topUp()) is only return null object
callbackService.callback();

}`

mockito version
mockito-core 4.11.0
JDK1.8

**Comment by stoneCrystal** [comment]
Which version I should upgrade?  or any other issue?

**Comment by TimvdLippe** [comment]
We don't maintain `@MockBean`. Please report the issue to Spring
