### ISSUE TITLE
Provide a variant of assertArg that works well with checked exceptions

### ISSUE THREAD

**Issue by wilkinsona** [mockito/mockito#2982]
https://github.com/mockito/mockito/pull/2949 is a great new feature, thank you. While trying to make use of it in Spring Boot, I came across a situation that would benefit from the consumer of the argument being able to throw checked exceptions:

```java
then(this.client).should().executeOpen(any(HttpHost.class), assertArg((request) -> {
	assertThat(request).isInstanceOf(HttpPost.class);
	assertThat(request.getUri()).isEqualTo(this.uri);
	assertThat(request.getFirstHeader(HttpHeaders.CONTENT_TYPE)).isNull();
	assertThat(request.getFirstHeader(HttpClientTransport.REGISTRY_AUTH_HEADER)).isNull();
	assertThat(response.getContent()).isSameAs(this.content);
}), isNull());
```

In this example, `request` is an `org.apache.hc.client5.http.classic.methods.HttpPost` and `getUri()` and `getContent()` throw `URISyntaxException` and `IOException` respectively. As a result, the above snippet does not compile.

I can work around this by using AssertJ's `ThrowingConsumer`:

```java
then(this.client).should().executeOpen(any(HttpHost.class), assertArg((ThrowingConsumer<HttpPost>) (request) -> {
	assertThat(request).isInstanceOf(HttpPost.class);
	assertThat(request.getUri()).isEqualTo(this.uri);
	assertThat(request.getFirstHeader(HttpHeaders.CONTENT_TYPE)).isNull();
	assertThat(request.getFirstHeader(HttpClientTransport.REGISTRY_AUTH_HEADER)).isNull();
	assertThat(response.getContent()).isSameAs(this.content);
}), isNull());
```

As you can see, it requires a cast which is ever so slightly inelegant. It also won't help a Mockito user who doesn't use AssertJ. Would you consider adding a `ThrowingConsumer` interface to Mockito along with a variant of `assertArg` that takes a `ThrowingConsumer` rather than a `Consumer`?

**Comment by TimvdLippe** [comment]
Yes that sounds like a useful alternative API! I am not sure if we need to keep both in Mockito 6, but that we will need to see. Do you mind sending us a PR with the new API and corresponding tests? Thanks!

**Comment by nicolas-ot** [comment]
I am working on this
