### ISSUE TITLE
MockedStatic<T> declares an unused type parameter

### ISSUE THREAD

**Issue by martinandersson** [mockito/mockito#2986]
This is a snippet from the [class definition](https://github.com/mockito/mockito/blob/baf59c48eafa7b8cc0e18fc4d6539634a41b36cc/src/main/java/org/mockito/MockedStatic.java):

```
 * @param <T> The type being mocked.
 */
public interface MockedStatic<T> extends ScopedMock {
```

The type parameter `T` does not appear anywhere else in the class file, and so it appears that the parameter is not used 🤔

There is already in Java, a quote unquote "any" type, leading the purist developer to write this:

`try (MockedStatic<?> mock = mockStatic(Something.class)) { ...`

If you have declared the unused type parameter for a rational reason, such as an anticipated evolution of the API within the current major release which will make use of the type parameter, et cetera, then it would be helpful to have it noted in the JavaDoc. Otherwise people, like myself, can get kind of confused?

I understand that at runtime the type will matter, we just gave the class as an argument. But I don't see the linkage between that and having an unused type parameter in the class definition. The _type parameter_ `T` simply doesn't matter 🤔🤯😂

**Comment by TimvdLippe** [comment]
It matters for the current implementation: https://github.com/mockito/mockito/blob/6e0c22890a5da72f4a919ede3fb2ae25b9eeab8e/src/main/java/org/mockito/internal/MockedStaticImpl.java#L32

To make sure we can change the implementation in the future without affecting compatibility, we will leave the type parameter here.
