### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by benmccann** [mockito/mockito#299]
I get memory leaks in my project whenever I use Mockito. I have a hunch this is because Mockito uses the wrong classloader, but I'm not quite sure. Please see the sample project I made to reproduce this:

https://github.com/benmccann/play-mockito-bug

**Comment by szczepiq** [comment]
Hey,

Thanks for reporting! Do you have a chance to debug this problem? We don't use sbt and I'm not sure when can we take a look at this problem.

**Comment by szczepiq** [comment]
What version of mockito do you use?

**Comment by benmccann** [comment]
I'm willing to put in some effort, but I'm afraid that I might have some difficulty finding the problem and could really use some help

I'm using 1.10.19. I tested with 2.0.31-beta also and it appears there as well.

**Comment by raphw** [comment]
Could you create a heap dump of your program when your application is leaking? This might give us the necessary hint!

**Comment by benmccann** [comment]
Sure. Here you go
https://www.dropbox.com/s/2ioabsh4yw2umcy/play-mockito.hprof?dl=0

**Comment by benmccann** [comment]
I'm going to close this issue since I was able to reproduce it without Mockito being present. Thank you for the help

**Comment by bric3** [comment]
@benmccann Also on another related topic, at some point with play framework, it was necessary to disable class caching. See [`IMockitoConfiguration.enableClassCache()`](http://site.mockito.org/mockito/docs/current/org/mockito/configuration/IMockitoConfiguration.html#enableClassCache())
