### ISSUE TITLE
Mockito 5 any() does not match a vararg int[] argument anymore. I need to use any(int[].class) to get the ArgumentMatcher to work

### ISSUE THREAD

**Issue by hensan64** [mockito/mockito#2998]
Mockito 5.2.0/5.3.1 any() ArgumentMatcher does not match a vararg int[] argument anymore.
I need to use any(int[].class) to get the ArgumentMatcher to work.

This mocking does NOT WORK:
when(myMock.myMethod(eq(myOtherMock), any()).thenReturn(myResultMap);

This mocking DOES WORK:
when(myMock.myMethod(eq(myOtherMock), any(int[].class))).thenReturn(myResultMap);

**Comment by TimvdLippe** [comment]
This breaking change is listed in the release notes of Mockito 5: https://github.com/mockito/mockito/releases/tag/v5.0.0

**Comment by hensan64** [comment]
Hello @TimvdLippe 

In the Javadoc for ArgumentMatcher::any() it says:
- "Matches anything, including nulls and varargs."
- This is not true for Mockito 5.x.x

Have you forgotten to update the Javadoc?

BR Henrik Sandström

**Comment by TimvdLippe** [comment]
@hensan64 Good catch on the wrong JavaDoc for these methods. Let me add these caveats to the JavaDoc.
