### ISSUE TITLE
Official support TestNG with mockito-testng artifact

### ISSUE THREAD

**Issue by edudar** [mockito/mockito#300]
Is there any chance for resurrection of https://code.google.com/p/mockito/issues/detail?id=304? It looks like it still lives as 3 classes outside of official repository only... Thanks!

**Comment by szczepiq** [comment]
We should do it. It's been postponed for later but we need to deal with this. Thanks for the reminder and an upvote.

**Comment by skabashnyuk** [comment]
Hello
Is there any chance to resurrect this task?
If it helps I can be a volunteer with sonatype negotiation to promote this artifact to maven central.
WDYT?

**Comment by Siarhei-Yarkavy** [comment]
+1 this feature could very useful

**Comment by skabashnyuk** [comment]
@bric3 @szczepiq 
I would like to make a PR with ability to deploy TestNG support artifacts to nexus.
I assume  this lines 
https://github.com/mockito/mockito/blob/release/2.x/subprojects/android/android.gradle#L17
https://github.com/mockito/mockito/blob/release/2.x/subprojects/inline/inline.gradle#L17
are responsible for that.

Are you ok guys if I'm add it here 
https://github.com/mockito/mockito/blob/release/2.x/subprojects/testng/testng.gradle#L53
Thx

**Comment by TimvdLippe** [comment]
This was released on https://github.com/mockito/mockito-testng
