### ISSUE TITLE
assertArg returns null

### ISSUE THREAD

**Issue by roelvandun** [mockito/mockito#3002]
> Hey,
>
> First thanks for reporting, in order to help us to classify issue can you make sure the following check boxes are checked ?
>
> If this is about mockito usage, the better way is to reach out to
>
>  - stackoverflow : https://stackoverflow.com/questions/tagged/mockito
>  - the mailing-list  : https://groups.google.com/forum/#!forum/mockito / mockito@googlegroups.com
>    (Note mailing-list is moderated to avoid spam)
>
> _This block can be removed_
> _Something wrong in the template fix it here `.github/ISSUE_TEMPLATE.md`

check that

 - [x] The mockito message in the stacktrace have useful information, but it didn't help
 - [x] The problematic code (if that's possible) is copied here;
       Note that some configuration are impossible to mock via Mockito
 - [x] Provide versions (mockito / jdk / os / any other relevant information)
 - [ ] Provide a [Short, Self Contained, Correct (Compilable), Example](http://sscce.org) of the issue
       (same as any question on stackoverflow.com)
 - [ ] Read the [contributing guide](https://github.com/mockito/mockito/blob/main/.github/CONTRIBUTING.md)

First of all, thanks for adding `assertArg()`!

I'm using mockito 5.3.1

It seems to always return `null`, which throws a warning for a `@NotNull` annotated parameter.

<img width="623" alt="image" src="https://user-images.githubusercontent.com/4869370/236662085-442c4b86-15f7-4b29-bfa1-68c9b022bbfc.png">

<img width="502" alt="image" src="https://user-images.githubusercontent.com/4869370/236662214-8162f207-562b-4fc6-8972-02c7a86b399c.png">

**Comment by TimvdLippe** [comment]
IntelliJ need to update their analysis to treat `assertArg` the same as all the other `ArgumentMatchers` methods (where they already ignore this warning).
