### ISSUE TITLE
PowerMock incompatible with JDK17 and mockito-core-3.10

### ISSUE THREAD

**Issue by KajolS14** [mockito/mockito#3021]
Trying to upgrade junit from JDK 11 that is developed using mockito-all-1.10.19.jar and powermockito-1.7.3 jars to JDK-17 with mocktio-core-3.10.0.jar.

Getting lots of exception on upgrading this junit like WhiteBoxImpl, InitialisationException, IllegalStateException.

**Comment by TimvdLippe** [comment]
Please report this issue with Powermock.
