### ISSUE TITLE
Add extraInterfaces setting to IMockitoConfiguration

### ISSUE THREAD

**Issue by julien-breda** [mockito/mockito#3044]
Hi,

With bytebuddy it seems difficult to see if an object is a mock or a spy : Enhancer.isEnhanced from CGLIB has no alternative.
=> https://groups.google.com/g/byte-buddy/c/snuqL4Qp41Q/m/T1zCYi1T2kMJ question 5

For some reasons (like a legacy test framework ...)  I need to know if an object is such a mock or a spy.
I saw the extraInterfaces setting in Mockito.withSettings() and I thought it would be great to be able to activate it globally in a project, so that each "mockito enhanced" object would implement a custom interface without adding withSettings to all of my usages.
This custom interface will let me know if an object is a mock/a spy.

An alternative would be to add such an interface, let's say org.mockito.Enhanced, in Mockito core and add this to all mock or spy objects.

Thanks for reading.

**Comment by TimvdLippe** [comment]
If you would like all of your mocks to use this interface, I recommend creating your own `mock()` method, adding the interface to your mock and then call `Mockito.mock`.

Internally, we do mark mocks and use `MockUtil.isMock` for this: https://github.com/mockito/mockito/blob/91f18ea1648e389bea06289d818def7978e82288/src/main/java/org/mockito/internal/util/MockUtil.java#L132 However, this is not a supported public API, so I recommend instead creating your own `mock` method for this.

**Comment by julien-breda** [comment]
Writing my own mock method has 2 drawbacks :
- I need to change all of my tests to use it, and it would be huge. That's exactly why I opened this issue.
- It will lead me to additionnal maintenance.

Why don't you want to add this existing Mockito configuration to IMockitoConfiguration whose Javadoc says "For now there are not many configuration options but it may change in future." ?

As you said, MockUtil is in internal package so I won't use it : you also may change its package to let people use it if you prefer.

**Comment by TimvdLippe** [comment]
The configuration can be enhanced on a per-mock basis, but we explicitly do not have a notion of global configuration. I understand you have a higher maintenance burden yourself, but the alternative is that you put that maintenance burden on all users of Mockito. Given that there currently is only one request for this, the burden for it to fix in your project is significantly lower than if it were in `mockito-core` and the fact that we don't have a global configuration setting atm, I think it's best to close this for now. We can always re-evaluate if more users have this use case.
