### ISSUE TITLE
Mockito#reset Condescending Documentation

### ISSUE THREAD

**Issue by Blafasel3** [mockito/mockito#3046]
Hello,

I just realised that the method `Mockito.reset()` existed at all. The documentation in the most recent version states:

>  Smart Mockito users hardly use this feature because they know it could be a sign of poor tests.

At the core, I totally agree, this shouldn't be necessary. Nevertheless, the first sentence of the comment feels rather rude / condescending. I suggest a rephrase to something like

> Using this method could be a sign of poor tests. \<rest of the doc here\>

Would help with that.

See the following link: https://github.com/mockito/mockito/blob/main/src/main/java/org/mockito/Mockito.java#L2581

**Comment by TimvdLippe** [comment]
Yes that is certainly true. Do you mind sending us a PR to improve the wording?
