### ISSUE TITLE
maven plugin / property to set default mockmaker. 

### ISSUE THREAD

**Issue by mamtananavati** [mockito/mockito#3059]
We are migrating to the latest mockito-inline and this means in our large codebase we have to use the Mockmaker.SUBCLASS in quite a number of places because of how the tests are written currently. We do intend to move away from this but that is an extensive migration effort. Instead of having to change the mockmaker in multiple test classes, is there a way to set the default property to SUBCLASS for the timebeing?

**Comment by TimvdLippe** [comment]
Yes this is already possible and mentioned in the release notes (https://github.com/mockito/mockito/releases/tag/v5.0.0):

> If you want to use the subclass mockmaker instead, you can use the new `mockito-subclass` artifact (published on Maven Central along with all our other artifacts).

**Comment by mamtananavati** [comment]
Thank you, just what i was looking for !!
