### ISSUE TITLE
Interface method signature for cglib.proxy.CallbackFilter different between github and Maven built Jar

### ISSUE THREAD

**Issue by anticlockwise** [mockito/mockito#307]
After trying to use Powermock 1.6.2 with a Mockito 1.10.19 jar built from source on my own laptop led to:

    AbstractMethodError: org.powermock.api.mockito.repackaged.ClassImposterizer$2.accept(java.lang.Method, java.util.List<Method>)

However, with the prebuilt jar for mockito-all 1.10.19 from Maven central works perfectly with Powermock 1.6.2.

After some digging, I found that the method signatures for org.mockito.cglib.proxy.CallbackFilter#accept are different between what's there in github source and what's there in the Maven central built jar. The signatures are:

Github source: accept(Method method, List<Method> methods)
Maven built jar: accept(Method method)

Powermock 1.6.2. is using the latter

Just wondering why there is such a discrepancy?

**Comment by raphw** [comment]
Cglib has a history of incompatible API changes. As the given builds of Mockito and Powermock use different versions of cglib, these versions can unfortunately clash. Mockito does however repackage cglib into its own namespace to avoid this. You probably did not use the repackaged jar from the build.
