### ISSUE TITLE
Why i can't mock a method call for super class ?

### ISSUE THREAD

**Issue by lingluan533** [mockito/mockito#3084]
> Hey,
>
i hava a method inputTxt(ParamType param) in Father class ,and i invoke inputTxt in Child class,  i want to test Child class and i want to mock inputTxt method. How can i do ,i have tried many plan but not get expected value.
like :
  Method inputEnTxt = PowerMockito.method(Father.class, "inputTxt", ParamaType.class);
 PowerMockito.replace(inputTxt).with(new InvocationHandler() {
            @Override
            public Object invoke(Object proxy, Method method, Object[] args) throws Throwable {
                return true;
            }
        });

 it's still to call real method inputTxt.

**Comment by TimvdLippe** [comment]
Please file an issue for Powermock instead
