### ISSUE TITLE
Can't mock InetSocketAddress on Java 8 because hashcode throw NPE

### ISSUE THREAD

**Issue by pwielgolaski** [mockito/mockito#310]
I'm trying to run simple test, but it fail with NPE

```
import junit.framework.Assert;
import org.junit.Test;
import org.mockito.Mockito;

import java.net.InetSocketAddress;

public class InetSocketAddressTest {
    @Test
    public void testSocketAddress() throws Exception {
        InetSocketAddress address = Mockito.mock(InetSocketAddress.class);
        Mockito.when(address.toString()).thenReturn("address");
        Assert.assertEquals("address", address.toString());
    }
}

```

How can I resolve it?

**Comment by raphw** [comment]
You cannot. Unfortunately, `hashCode` and `equals` are declared to be `final` by `InetSocketAddress`. Mockito does however rely on these methods for all of its internal validation. Whenever these methods are triggered, they rely on a state that the mocking circumvented such that the null pointer exception is thrown.

**Comment by xingfudeshi** [comment]
mark
