### ISSUE TITLE
ThrowsExceptionClass is urealiable - exception doesn't containt stack trace

### ISSUE THREAD

**Issue by zbigniewTomczak** [mockito/mockito#312]
The `ThrowsExceptionClass` is using `ObjenesisHelper.newInstance` which happens to have different strategy of creating objects depending on the JVM used. 
I'm using Java HotSpot VM. On this machine ,created `Throwable`, is initalized with all nulls.
As a result calling `throwable.fillInStackTrace()` has no effect and there is no chance the stack trace is ever filled. You can easily observe this behaviour by this sample code:

```java
Throwable t = (Throwable) ObjenesisHelper.newInstance(Throwable.class);
t.fillInStackTrace();
t.printStackTrace();
```

After a bit of struggling I ended up using `ThrowsException` instead of `ThrowsExceptionClass`.

Objenesis strategy to create instances is dependent on VM name (returned by `System.getProperty("java.vm.name")`) so there is no 100% guarantee that this behaviour is reproduced on your machine.

**Comment by bric3** [comment]
OK thanks for the report, can you make a pull request to document that behaviour for `ThrowsExceptionClass`

**Comment by lloydjm77** [comment]
Thanks @zbigniewTomczak for doing the research on this.  I just added the documentation.  It's in PR #381.
