### ISSUE TITLE
Add Rusts Mockito library to the "Mockito-for-other-languages" section in the Wiki

### ISSUE THREAD

**Issue by Oliver-Hanikel-esatus** [mockito/mockito#3130]
Mockitos [Github Wiki](https://github.com/mockito/mockito/wiki/Mockito-for-other-languages) is missing a reference to [Rusts Mockito library](https://github.com/lipanski/mockito).

**Comment by TimvdLippe** [comment]
Not sure if it qualifies, but we don't have strong requirements for inclusion anyways. Feel free to add it id you want.
