### ISSUE TITLE
publish new beta version?

### ISSUE THREAD

**Issue by PascalSchumacher** [mockito/mockito#318]
The last published beta version is mockito-core-2.0.31 from 21-Jul-2015. It would be very nice if a new beta version could be published (if it is not too much bother).

BTW: Thanks for creating mockito. :)

**Comment by raphw** [comment]
There is something wrong with the script. There is already an issue for it but I could not yet figure out what has changed. Maybe the account credentials were changed?

**Comment by bric3** [comment]
cc @szczepiq

**Comment by raphw** [comment]
I managed to make Travis publish a new version. Let us hope the drone keeps running after this one!

**Comment by bric3** [comment]
Nice thank you @raphw, I planned to look at it next week

**Comment by PascalSchumacher** [comment]
Thanks!
