### ISSUE TITLE
Mockito.verify not run as expected when callback

### ISSUE THREAD

**Issue by loyispa** [mockito/mockito#3195]
> Hey,
>
> First thanks for reporting, in order to help us to classify issue can you make sure the following check boxes are checked ?
>
> If this is about mockito usage, the better way is to reach out to
>
>  - stackoverflow : https://stackoverflow.com/questions/tagged/mockito
>  - the mailing-list  : https://groups.google.com/forum/#!forum/mockito / mockito@googlegroups.com
>    (Note mailing-list is moderated to avoid spam)
>
> _This block can be removed_
> _Something wrong in the template fix it here `.github/ISSUE_TEMPLATE.md`

check that

 - [ ] The mockito message in the stacktrace have useful information, but it didn't help
```
Exception in thread "main" Wanted but not invoked:
aggregator.record("123");
-> at prometheus.exporter.jgc.collector.Example$Aggregator.record(Example.java:41)

However, there was exactly 1 interaction with this mock:
aggregator.receive("123");
-> at prometheus.exporter.jgc.collector.Example.main(Example.java:24)


	at prometheus.exporter.jgc.collector.Example$Aggregator.record(Example.java:41)
	at prometheus.exporter.jgc.collector.Example.main(Example.java:25)
```
 - [ ] The problematic code (if that's possible) is copied here;
```
  public class Example {
    public static void main(String[] args) {
        Aggregator aggregator = Mockito.spy(new Aggregator());
        aggregator.receive("123");
        Mockito.verify(aggregator, Mockito.times(1)).record("123");
    }

    static class Aggregator implements Callback {
        private Parser parser;

        public Aggregator() {
            this.parser = new Parser();
            parser.callback = this;
        }

        public void receive(String line) {
            parser.parse(line);
        }

        public void record(String event) {
            System.out.println("record was called: " + event);
        }

        @Override
        public void call(String line) {
            record(line);
        }
    }

    static class Parser {
        private Callback callback;

        public void parse(String line) {
            callback.call(line);
        }
    }

    interface Callback {
        void call(String line);
    }
}
```
 - [ ] Provide versions (mockito / jdk / os / any other relevant information)
5.5.0, 5.8.0
 - [ ] Provide a [Short, Self Contained, Correct (Compilable), Example](http://sscce.org) of the issue
       (same as any question on stackoverflow.com)
 - [ ] Read the [contributing guide](https://github.com/mockito/mockito/blob/main/.github/CONTRIBUTING.md)

**Comment by loyispa** [comment]
If I use wrong, how can I know that record has been called?  Thanks.

**Comment by GiorgioRicca** [comment]
Hello, I believe the issue might be here:

`Aggregator callbackSpy = Mockito.spy(new Aggregator());
`

I have checked, and it seems to work by modifying it as follows:


`Aggregator callbackSpy = Mockito.spy(Aggregator.class);
`

The error you reported could be related to the constructor call. The constructor itself makes a call to the call method, but it wasn't called in the expected context (i.e., during the actual method invocation). Instead, it was called during the creation of the mock (during the "new" operation).

I hope I have resolved the issue.

**Comment by loyispa** [comment]
@GiorgioRicca  Thank you for the reply.  I'm a little confused about that **Aggregator.call**  was not called by constructor. Did I understand it wrong?

**Comment by GiorgioRicca** [comment]
When you execute


`new Aggregator();
`


you are explicitly calling the constructor, thus creating an instance that you are "spying" on. However, afterward, you don't use the instance itself for the test, but rather the one returned by the spy method.

Or simply use .class
