### ISSUE TITLE
Is it possible to use to mock some paths in sysfs?

### ISSUE THREAD

**Issue by jabrena** [mockito/mockito#321]
I am developing a java library which it interacts with a Linux environment and I would like to know if it is possible to use mockito in testing phase.

The class which interacts with sysfs is:
https://github.com/jabrena/ev3dev-lang-java/blob/master/library/src/main/java/ev3dev/hardware/Sysfs.java

I would like to simulate values using mockito.

any idea?

**Comment by bric3** [comment]
Nope `Sysfs` is using `static` methods. in my opinion should create a test util that can create a virtual environment in a temporary folder. More or less like `chroot` for tests.
