### ISSUE TITLE
Documentation on javadoc.io needs attention

### ISSUE THREAD

**Issue by michaelMarquard** [mockito/mockito#3212]
Hello 

Since most of your reference documentation is based on javadoc.io I just want to point your attention to the javadoc.io issue https://github.com/maxcellent/javadoc.io/issues/159

It seems that this issue is of minor importance to the javadoc.io team 
but maybe it is important for you... 

As a work around:
Maybe there is a way to generate your documentation without the search field?

Best regards,

Michael

**Comment by TimvdLippe** [comment]
Happy to review a PR that tweaks our JavaDoc configuration. It hasn't had much love lately. The navigation link CSS is also broken, so that needs to be fixed as well (https://github.com/mockito/mockito.github.io/issues/60)

**Comment by scordio** [comment]
Hi @TimvdLippe, I could give a stab at this one as I've been fixing similar issues lately in AssertJ where we have a custom stylesheet (assertj/assertj#3191 and assertj/assertj#3324).

Looking at:

https://github.com/mockito/mockito/blob/3db5df66858ba94aa5776bae97becac62ee45407/.github/workflows/ci.yml#L207-L211

do I understand correctly that Mockito is released with Java 17, i.e., the Javadoc gets generated under Java 17?

Would you consider an upgrade to Java 21, assuming it's compatible with the rest of the build?

This is what we do in AssertJ (still retaining Java 8 compatibility for the actual JAR).

**Comment by TimvdLippe** [comment]
With Mockito 5, we support Java 11+. We currently indeed publish from Java 17 and if upgrading that release job to Java 21 would fix the JavaDoc issues, I am all for it. Would love to review a PR that takes a stab at this!

**Comment by scordio** [comment]
Just for reference, https://www.javadoc.io/doc/org.mockito/mockito-core/5.4.0/index.html appears to be the latest correctly rendered Javadoc.

**Comment by scordio** [comment]
I noticed [`mockito-junit-jupiter`](https://www.javadoc.io/doc/org.mockito/mockito-junit-jupiter/latest/index.html) doesn't have a custom stylesheet. I assume the [stylesheet](https://github.com/mockito/mockito/blob/main/src/javadoc/stylesheet.css) of `mockito-core` should be applied also here, right?

**Comment by TimvdLippe** [comment]
Yes it should indeed be applied there as well

**Comment by scordio** [comment]
I wasn't able to do a 1 to 1 conversion but I tried to replicate the style as much as possible.

Now I only need to figure out why #3226 fails 🙃 

Here's a preview:

<img width="1511" alt="Screenshot 2024-01-08 at 01 42 08" src="https://github.com/mockito/mockito/assets/26772046/a208478b-960a-4ccb-8c21-a528a1e2d45c">

<img width="1512" alt="Screenshot 2024-01-08 at 01 45 11" src="https://github.com/mockito/mockito/assets/26772046/273e87d5-3eed-44ce-bc29-9f3f50d34958">

<img width="667" alt="Screenshot 2024-01-08 at 01 45 44" src="https://github.com/mockito/mockito/assets/26772046/4f066a4d-75e3-4692-8836-4a75ee8d288c">

<img width="1512" alt="Screenshot 2024-01-08 at 01 50 38" src="https://github.com/mockito/mockito/assets/26772046/886c374e-ed19-4a89-9394-8a536c55de23">

<img width="1512" alt="Screenshot 2024-01-08 at 01 50 56" src="https://github.com/mockito/mockito/assets/26772046/e3626fff-4cdf-42e4-a58b-446f9b01f649">

**Comment by TimvdLippe** [comment]
That looks great! Thanks for picking this up
