### ISSUE TITLE
Fail a call on a mock that isn't stubbed

### ISSUE THREAD

**Issue by henrykuijpers** [mockito/mockito#3224]
It would be nice if we can somehow configure Mockito so that it fails when calling a method on a mock, that doesn't have a stub.

I.e.:

```
final UUID uuid = mock(UUID.class);
when(uuid.node()).thenReturn(5L);

uuid.clockSequence();
```

In this piece of code, I get an exception from Mockito, which is highly desired: It tells me that I have a stub in place for `UUID#node`, which is not called.

But I would also like to get an exception for the fact that I call `clockSequence`, while I did not provide a stub for it.

It would assist in creating more robust unit tests, since always relying on the default values might not be the best idea.

**Comment by TimvdLippe** [comment]
You can use "strict mocks" for this, introduced in Mockito 2.1: https://javadoc.io/doc/org.mockito/mockito-core/latest/org/mockito/Mockito.html#40
