### ISSUE TITLE
How to mock private static method in Mockito 

### ISSUE THREAD

**Issue by Nikhilkarande33** [mockito/mockito#3233]
Hey,

i want to get rid of PowerMock by using Mockito and need any alternative for below code using Mockito.

Optional<String> imageTemplate = readImageTemplate();
when(EmailRender.class,"_readImageTemplate").thenReturn(imageTemplate);

_readImageTemplate is private static method in EmailRender class

**Comment by TimvdLippe** [comment]
We do not support mocking these kind of methods. Please abstract away these methods or refactor your code to facilitate testing.
