### ISSUE TITLE
Is `Boolean.TRUE` really equal to `true` ?

### ISSUE THREAD

**Issue by biergit** [mockito/mockito#3238]
`assertThat(Boolean.TRUE).isEqualTo(true)` -> success
`assertThat((Boolean)null).isNotEqualTo(Boolean.TRUE)` -> success
`assertThat((Boolean)null).isNotEqualTo(true)` -> Expecting actual not to be null.

**Comment by TimvdLippe** [comment]
This is a question for AssertJ and not Mockito.

**Comment by biergit** [comment]
Oops, sorry about that @TimvdLippe
