### ISSUE TITLE
Mockito bom missing artifact in maven central for java21

### ISSUE THREAD

**Issue by hazendaz** [mockito/mockito#3240]
The following artifact is in the mockito bom but does not exist in maven central.  

```xml
      <dependency>
        <groupId>mockito</groupId>
        <artifactId>java21</artifactId>
        <version>5.9.0</version>
      </dependency>
```

This seems like it should not have been put in the bom.  This commit brought it in https://github.com/mockito/mockito/commit/a0cc22d73c184d0367f38c4d4d34de71c030c9b7.

**Comment by TimvdLippe** [comment]
Whoops good catch. We need to rename that to `java21-test` per our exclusion logic in https://github.com/mockito/mockito/blob/917352266b61870c47a7da97965778f0288d50cb/subprojects/bom/bom.gradle#L18 Contributions welcome!

**Comment by PranotiPD** [comment]
shall I fix it?

**Comment by TimvdLippe** [comment]
Yes feel free to send a PR to fix the name of the subproject
