### ISSUE TITLE
issue :-  Mockito with ParameterizedRowMapper

### ISSUE THREAD

**Issue by harishkaparwan** [mockito/mockito#325]
Hi All,

Could you please  share  Mockito example  with Spring Jdbc ParameterizedRowMapper.

I am not able  return anything using below code sample:-

	Mockito.when(jdbcTemplate.query(SQL,ParameterizedRowMapper,SQL_PARAMS )).thenReturn(ListObject);

  It always returns   <b> <i>ListObject.size()=0; </i> </b>

  Expected output  :-  <b>ListObject.size()>0; </b>

**Comment by bric3** [comment]
Please keep the mailing list for such questions; original : https://groups.google.com/d/msg/mockito/tOgh_6N5gA8/c61Oq_ieCAAJ

**Comment by tyagikumarvineet** [comment]
Hi @bric3 / @harishkaparwan ,

Could you please advise , how it issue was fixed? I am facing the same issue.

Thanks
Vineet
