### ISSUE TITLE
Kotlin language support for Mockito

### ISSUE THREAD

**Issue by szczepiq** [mockito/mockito#328]
It would be cool to make sure that Mockito can be easily used with Kotlin.

I found this issue so far: http://stackoverflow.com/questions/30305217/is-it-possible-to-use-mockito-in-kotlin It is relatively easy to fix - return new Object() instead of null

**Comment by nhaarman** [comment]
Is there a workaround users can use for now? The suggested solution the SO answer provides does not work anymore in the latest version of Kotlin.

**Comment by szczepiq** [comment]
Are you a kotlin user and want to use Mockito?

You could create your own 'anyObject()' method that delegates Mockito's but returns not-null.

Or use spock to test/mock your kotlin code.

**Comment by nhaarman** [comment]
So it's about creating a non-null value _after_ Mockito's any() has been called right?
I've tried using mock(), but this is not allowed because of Mockito's internal state validation. Is it safe to bypass this validation like so?:

```kotlin
private fun <T> uncheckedMock(clzz: Class<T>): T {
    val impl = MockSettingsImpl<T>().defaultAnswer(Answers.RETURNS_DEFAULTS) as MockSettingsImpl<*>
    val creationSettings = impl.confirm(clzz)
    return MockUtil().createMock(creationSettings) as T
}
```
It works, but I'm wondering whether this may break some things.

**Comment by szczepiq** [comment]
It should be good. I'd love to have first class support to Kotlin at some point.

**Comment by bric3** [comment]
Let's do that in another module then. For example in Scala Mockito is supported thanks to ScalaTest's [MockitoSugar](http://www.scalatest.org/user_guide/testing_with_mock_objects#mockito). And groovy guys it with [mockito-groovy-support](https://github.com/cyrusinnovation/mockito-groovy-support).

**Comment by szpak** [comment]
Should it be a submodule in Mockito codebase or rather an external module in Mockito ecosystem (like the two previously mentioned)?

**Comment by szczepiq** [comment]
I don't know. Feels like it should be separate from Mockito GitHub repo so that it has it's own release cycle and maintainers. Unless we get excited about Kotlin enough :)

**Comment by bric3** [comment]
yes exactly, i wrote _module_ but I was more thinking about repository with a different life cycle indeed.

**Comment by nhaarman** [comment]
Would this repository be under control by Mockito? I've been creating some helper functions that make Mockito work a bit better with Kotlin. If not, I'd be happy to create a repo myself.

**Comment by szczepiq** [comment]
>Would this repository be under control by Mockito?

I don't think so. It should be controlled by folks passionate about Kotlin
and using Mockito with Kotlin. We have a slightly different focus.

Cheers!

On Wed, Jan 20, 2016 at 11:43 AM, Niek Haarman <notifications@github.com>
wrote:

> Would this repository be under control by Mockito? I've been creating some
> helper functions that make Mockito work a bit better with Kotlin. If not,
> I'd be happy to create a repo myself.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mockito/mockito/issues/328#issuecomment-173337247>.
>



-- 
Szczepan Faber
Founder mockito.org; Core dev gradle.org
tweets as @szczepiq; blogs at blog.mockito.org

**Comment by nhaarman** [comment]
I have created a new repo for this:

https://github.com/nhaarman/mockito-kotlin

**Comment by raphw** [comment]
Perfect, I cannot promise anything but I will most likely keep an eye on it. I recently started learning Kotlin myself and I must say that I really like the language. Even better if the Mockito integration improves.

**Comment by Tazmain** [comment]
Hi all, 

While kockito-kotlin, is an answer, it does not work well when using spring and mockito with @MockBean.  A work around found here https://stackoverflow.com/questions/30305217/is-it-possible-to-use-mockito-in-kotlin, does work for sending anyObject to a function that takes a kotlin class. 

I know it's a long stretch by maybe mockito could include private fun <T> anyObject(): T {
    return Mockito.anyObject<T>()
} something that achieves this for kotlin users?
