### ISSUE TITLE
Finalize Mockito Runners

### ISSUE THREAD

**Issue by szczepiq** [mockito/mockito#332]
Currently, we have a couple of Mockito Runners that are a part of public API but they are largely unknown:
 - ConsoleSpammingMockitoJUnitRunner
 - VerboseMockitoJUnitRunner

They attempt to improve the testing / TDD experience by adding warnings for following scenarios:
     - a) unused stubbing
     - b) stubbed method called with different args (and a special variant of a)

Example of a warning:

----

 *** Stubbing warnings from Mockito: ***

stubbed with those args here   -> at org.mockitousage.junitrunner.ModellingVerb
BUT called with different args -> at org.mockitousage.junitrunner.ModellingVerboseMockitoTest.shouldLogUnusedS
This stubbing was never used   -> at org.mockitousage.junitrunner.ModellingVerboseMockitoTest.shouldLogUnusedStubbingWarning
This stubbing was never used   -> at org.mockitousage.junitrunner.ModellingVerboseMockitoTest.shouldLogUnusedStubbingWarningWh

----

The rationale is explained in the javadoc of the above runners. In 2.0 let’s include stubbing warnings in the default behavior of JUnit rule and the default runner.

Challenges that need thinking through:
 - feature parity with JUnit rule
 - clean API so that the warning system can be integrated with other runners
 - some API to get hold of those warnings programmatically
 - feature toggle
     - disable completely
     - disable by test / test class / stubbing?
 - how can this be tested?

**Comment by bric3** [comment]
> how can this be tested?

Using `JUnitCore`, there's already a few tests that uses it.

> * feature toggle
>   * disable completely
>   * disable by test / test class / stubbing?

Using the plugin switch functionality ?
Note there's some idea in the pull request to toggle stuff per test / test class. However I don't feel this is mature enough to be integrated, in mockito yet.

In my opinion the `Rule` is the the right place to configure mockito per test.
