### ISSUE TITLE
potential editorconfig enhancement

### ISSUE THREAD

**Issue by christopher-spires** [mockito/mockito#3347]
I noticed that the CONTRIBUTING.md file has IntelliJ IDEA instructions.  But those settings are not in the .editorconfig file.  May have been added to IntelliJ since the last time that file was generated.

i.e.
```
[*]
charset = utf-8
[*.java]
ij_java_align_multiline_throws_list = true
ij_java_align_multiline_annotation_parameters = true
ij_java_annotation_parameter_wrap = off
ij_java_blank_lines_after_imports = 1
ij_java_blank_lines_before_imports = 1
ij_java_class_count_to_use_import_on_demand = 100
ij_java_imports_layout = static java.**,static javax.**,$*,|,java.**,javax.**,*
ij_java_insert_inner_class_imports = true
ij_java_layout_static_imports_separately = true
ij_java_method_call_chain_wrap = off
ij_java_names_count_to_use_import_on_demand = 100
ij_java_throws_list_wrap = off
```
( I think those are the one listed in the file but not in .editorconfig file)

**Comment by TimvdLippe** [comment]
Feel free to contribute! In any case, for auto-formatting we run `./gradlew spotlessApply`

**Comment by thachlp** [comment]
Hi @TimvdLippe @christopher-spires, I created a pr for this, please help review
