### ISSUE TITLE
Move root project to dedicated core folder

### ISSUE THREAD

**Issue by bric3** [mockito/mockito#3444]
Currently the main Mockito source code lives in the root folder. This is not ideal:

1. That means that we have next to each other `src/main/java` and `subprojects`, this is strange and almost confusing for any new contributors. 
2. This doesn't align with what other notable projects (spring, micronaut, micrometer, etc.) do, i.e. they have a root folder and their various components are located in sub-modules of the root folder.
3. The root Gradle build script has to mix configurations for both the root project, `mockito-core` and the subprojects

We could imagine something like this :

```
├── ./mockito-core
└── ./mockito-extensions
│   ├── ./bom
│   └── ./subclass-mockmacker 
└── ./mockito-integration-tests
    ├── ...
    └── ./java-21-tests
```

This will enable a clear separation of the build scripts.

Cons, git will perceive this as a move and could make diffs a tad more difficult, by using a `--follow`. Even in IntelliJ automatically follows the file when looking at the file history (clicking on the colored line expand them with the new name).

<img width="49%" src="https://github.com/user-attachments/assets/a053f4cf-3501-4d20-b3a9-5ca8d383fe69"><img width="49%" src="https://github.com/user-attachments/assets/6fd44ab6-2a16-40f8-b7f8-442844dbd1df">

Github has improved at [tracking this](https://github.blog/changelog/2022-06-06-view-commit-history-across-file-renames-and-moves/).

I believe the benefit outweighs this issue. 

----
As a side note: This is not the first time that sources are moved in Mockito history, when Mockito moved from SVN to Mercurial, then to git, the source folder was also different (we had `src` then `src/main/java`).

Depends on #3443

**Comment by raphw** [comment]
I think that's a good idea, too. I had to look for it more than once as there are so many subprojects now that it creates a mental barrier. +1 for moving.
