### ISSUE TITLE
Non-beta 2.x release?

### ISSUE THREAD

**Issue by mcandre** [mockito/mockito#346]
When can we get an official 2.x release outside of beta?

**Comment by szpak** [comment]
There is no a clear answer so far, but see the discussions in #123 and #297. Btw, the [mailing list](https://groups.google.com/forum/#!forum/mockito) seems to be a better place to ask questions like that.

**Comment by szczepiq** [comment]
We'll do it.

On Sat, Jan 30, 2016 at 3:04 PM, Marcin Zajączkowski <
notifications@github.com> wrote:

> There is no a clear answer so far, but see the discussions in #123
> <https://github.com/mockito/mockito/issues/123> and #297
> <https://github.com/mockito/mockito/issues/297>. Btw, the mailing list
> <https://groups.google.com/forum/#!forum/mockito> seems to be a better
> place to ask questions like that.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mockito/mockito/issues/346#issuecomment-177326081>.
>



-- 
Szczepan Faber
Founder mockito.org; Core dev gradle.org
tweets as @szczepiq; blogs at blog.mockito.org

**Comment by raphw** [comment]
I am closing this for cleaning up as we already have issue https://github.com/mockito/mockito/issues/123

**Comment by szczepiq** [comment]
@Andrew, thanks for reminding us. This is helpful, we want to know that the
community is waiting.

On Sun, Jan 31, 2016 at 4:55 AM, Rafael Winterhalter <
notifications@github.com> wrote:

> I am closing this for cleaning up as we already have issue #123
> <https://github.com/mockito/mockito/issues/123>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mockito/mockito/issues/346#issuecomment-177494372>.
>



-- 
Szczepan Faber
Founder mockito.org; Core dev gradle.org
tweets as @szczepiq; blogs at blog.mockito.org
