### ISSUE TITLE
Disabled Mock Triggers NPE when Checking isMock

### ISSUE THREAD

**Issue by Kramermp** [mockito/mockito#3469]
check that
 - [X] The mockito message in the stacktrace have useful information, but it didn't help
 - [X] The problematic code (if that's possible) is copied here;
       Note that some configuration are impossible to mock via Mockito
 - [X] Provide versions (mockito / jdk / os / any other relevant information)
 - [X] Provide a [Short, Self Contained, Correct (Compilable), Example](http://sscce.org) of the issue
       (same as any question on stackoverflow.com)
 - [X] Read the [contributing guide](https://github.com/mockito/mockito/blob/main/.github/CONTRIBUTING.md)

There is the ability to trigger a NullPointerException by calling `isMock` on a disabled mock. This behavior should probably be changed to either return true, because a DisabledMock is still a mock or `isMock` should throw a `DisabledMockException` because you are interacting with a disabledMock.
 
Problematic Code is: `DisabledMockHandler#getMockSettings` returning `null` here breaks the logic for determining if an object a mock.
```
@Override
    public MockCreationSettings getMockSettings() {
        return null;
    }
```
NPE Source is in the following loop of `MockUtil#getMockHandlerOrNull`. 
```
for (MockMaker mockMaker : mockMakers.values()) {
            MockHandler<?> handler = mockMaker.getHandler(mock);
            if (handler != null) {
                assert getMockMaker(handler.getMockSettings().getMockMaker()) == mockMaker;
                return handler;
            }
        }
```

Stack Trace Snippet:
```
java.lang.NullPointerException: Cannot invoke "org.mockito.mock.MockCreationSettings.getMockMaker()" because the return value of "org.mockito.invocation.MockHandler.getMockSettings()" is null
	at org.mockito.internal.util.MockUtil.getMockHandlerOrNull(MockUtil.java:160)
	at org.mockito.internal.util.MockUtil.isMock(MockUtil.java:147)
	at org.mockito.internal.util.DefaultMockingDetails.isMock(DefaultMockingDetails.java:32)
	at org.mockito.internal.framework.DefaultMockitoFrameworkTest.behavior_after_clear_inline_mocks_is_mock(DefaultMockitoFrameworkTest.java:226)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:569)
```

The following unit test reproduces the issue. This unit test can be added to `DefaultMockitoFrameworkTest` and will fail for an NPE. This test should probably be modeled to either trigger a `DisabledMockException` or `return true` because a DisabledMock is still a mock.
```

    @Test
    public void behavior_after_clear_inline_mocks_is_mock() {
        // clearing mocks only works with inline mocking
        assumeTrue(Plugins.getMockMaker() instanceof InlineMockMaker);
        PersonWithName obj = mock(PersonWithName.class);
        when(obj.getMyName()).thenReturn("Bob");
        assertEquals("Bob", obj.getMyName());
        assertTrue(mockingDetails(obj).isMock());
        framework.clearInlineMocks();

        try {
            mockingDetails(obj).isMock();
        } catch (DisabledMockException e) {
            return;
        }
        Assert.fail("Should have thrown DisabledMockException");
    }
 ```

**Comment by Kramermp** [comment]
There actually seems to be a lot of weirdness around the disabled mocks and their `null` MockSettings. I think it might make sense to implement a DisableMockSettings that allows for some interactions with disabled mocks but will throw a DisabledMockException on any interactions with the mock settings. It would help prevent against a lot of weird NPEs.

**Comment by Kramermp** [comment]
Too add to the weirdness, there is a functional difference between the way `clearInlineMock(mock)` and `clearInlineMocks()` works. So if you clear and individual mock you can call `isMock()` and it will return false. However, if you call `clearInlineMocks()` it will trip an NPE when calling `isMock()`. 

```
@Test
    public void clears_mocks() {
        // clearing mocks only works with inline mocking
        assumeTrue(Plugins.getMockMaker() instanceof InlineMockMaker);

        // given
        List list1 = mock(List.class);
        assertTrue(mockingDetails(list1).isMock());
        List list2 = mock(List.class);
        assertTrue(mockingDetails(list2).isMock());

        // when
        framework.clearInlineMock(list1);

        // then
        assertFalse(mockingDetails(list1).isMock());
        assertTrue(mockingDetails(list2).isMock());

        framework.clearInlineMocks();
        assertFalse(mockingDetails(list1).isMock());
        assertFalse(mockingDetails(list2).isMock()); // This now trips an NPE.
    }
```

**Comment by TimvdLippe** [comment]
We changed the behaviour in https://github.com/mockito/mockito/pull/3424 where we pass in the original `settings` object into the mockhandler. We probably should clone the settings and update it accordingly and pass that in. Do you mind opening a PR?

**Comment by Kramermp** [comment]
I'm working on PR. The way the original settings are passed has some weird behavior as well, because it results in inconsistent behavior for repeated calls to `clearInlineMocks()`. Any duplicate calls to `clearInlineMocks()` will fail for NPEs, because we clone in the previous setting according to the handler, after the first clear call the handler is a DisabledHandler and will only return nulls, this will lead to an NPE on any subsequent calls. So I think we need to implement some why for the DisabledHandler to return a sane MockCreationSettings Object. Right now my approach is private DisabledMockSettings type that is within the Handler that will just throw any exceptions on an interaction. 

I'm also going to bundle in the unification of the logic of  `clearMocks()` and `clearMock()`.

```
    @Test
    public void clears_mocks_repeatedly() {
        // clearing mocks only works with inline mocking
        assumeTrue(Plugins.getMockMaker() instanceof InlineMockMaker);

        // given
        List list1 = mock(List.class);
        assertTrue(mockingDetails(list1).isMock());
        List list2 = mock(List.class);
        assertTrue(mockingDetails(list2).isMock());

        framework.clearInlineMocks();
        framework.clearInlineMocks(); // This now trips an NPE.
        assertFalse(mockingDetails(list1).isMock());
        assertFalse(mockingDetails(list2).isMock()); 
    }
    ```
