### ISSUE TITLE
Why does a stubOnly mock keeps reference of the last invocation?

### ISSUE THREAD

**Issue by RomainPiel** [mockito/mockito#348]
I was looking at a memory leak caused by a mock in our tests and I noticed that creating a mock this way 

```java
Foo foo = mock(Foo.class, withSettings().stubOnly());
```
will still keep the last invocation in memory:
https://github.com/mockito/mockito/blob/c303e49b60d10960b4155bc1202483b08fa4ec9d/src/main/java/org/mockito/internal/stubbing/InvocationContainerImpl.java#L141
https://github.com/mockito/mockito/blob/c303e49b60d10960b4155bc1202483b08fa4ec9d/src/main/java/org/mockito/internal/verification/SingleRegisteredInvocation.java#L16

I was wondering if that was on purpose? I thought the whole point of `stubOnly()` was to prevent allocating too much memory for nothing by preventing `verify()` on a mock. I think something like that would make more sense:

```java
public class EmptyRegisteredInvocation implements RegisteredInvocations, Serializable {

    public void add(Invocation invocation) {
        // do nothing
    }

    public void removeLast() {
        // do nothing
    }

    public List<Invocation> getAll() {
        return Collections.emptyList();
    }

    public boolean isEmpty() {
        return true;
    }
}
```

**Comment by TimvdLippe** [comment]
This seems reasonable. I don't think we do this for Mockito 2.0, but 2.1 instead. It does require an investigation if this is backwards incompatible though.

**Comment by bric3** [comment]
This is not a bug, otherwise mockito can't record the stub itself.

**Comment by davidburstromspotify** [comment]
@bric3 If you don't mind, could you elaborate on this (5 years later)? I'm also facing a memory leak like this and found this ticket.

**Comment by davidburstromspotify** [comment]
Yeah, that looks what I'd expect too. Considering there are test cases that fail, I guess there's a risk that some projects accidentally use the incorrect behaviour when pure stubs are used. In that case, I suppose the migration is easy: Don't use `stubOnly`. ?
