### ISSUE TITLE
A question about mock thenCallRealMethod()

### ISSUE THREAD

**Issue by 1054522381** [mockito/mockito#351]
code as:

```java
List list1 = Mockito.mock(ArrayList.class);
list1.add(1);
Mockito.when(list1.isEmpty()).thenCallRealMethod();
System.out.println("isEmpty:" + list1.isEmpty());
```

question:why the list1 is empty? why the real method has not been invoked?

**Comment by thekingnothing** [comment]
Seems to me you have misunderstanding how Mockito works. In the first line you create a mock for `ArrayList.class` and don't pointed default `Answer`, so 
> By default, for all methods that return value, mock returns null, an empty collection or appropriate primitive/primitive wrapper value (e.g: 0, false, ... for int/Integer, boolean/Boolean, ...).
(from [docs](http://docs.mockito.googlecode.com/hg/org/mockito/Mockito.html#2)).

So then you call `list1.add(1);` the mocked method is called and nothing is added to list. So next two strings work correct and really method is invoked, but as I mentioned, your list is empty, whats why you get `isEmpty:true`.

If you change code: 
`List list1 = Mockito.mock(ArrayList.class);

		Mockito.when(list1.add(anyInt())).thenCallRealMethod();

		list1.add(1);
		Mockito.when(list1.isEmpty()).thenCallRealMethod();

		System.out.println("isEmpty:" + list1.isEmpty());` 

then the real method `add` will be invoked and you will get an exception.

**Comment by bric3** [comment]
@thekingnothing thanks for answering
@1054522381 Please use the mailing list or SO for questions ;)
