### ISSUE TITLE
Mockito:5.14.2 Warning: Mockito is currently self-attaching...

### ISSUE THREAD

**Issue by maximkovalenko-hc** [mockito/mockito#3512]
Using `mockito-core:5.14.2` and `spring-boot:3.3.5 ` shows this warning:
```
Mockito is currently self-attaching to enable the inline-mock-maker. 
This will no longer work in future releases of the JDK. 
Please add Mockito as an agent to your build what is described in Mockito's documentation: https://javadoc.io/doc/org.mockito/mockito-core/latest/org/mockito/Mockito.html#0.3
```
![image](https://github.com/user-attachments/assets/76200243-d754-4d60-a5a3-d413c44bd717)

However the previous versions of mockito (5.13.0, 5.12.0, 5.11.0...) don't have it.

Can we run the latest version of mockito without "_Mockito is currently self-attaching..._" warning?

More details:
mockito-core:5.14.2
mockito-junit-jupiter:5.14.2
spring-boot:3.3.5
Oracle GraalVM 21.0.5+9.1

**Comment by TimvdLippe** [comment]
Are you sure that your Mockito version resolves to 5.14.2? We haven't made changes in this minor version compared to the previous ones.

**Comment by maximkovalenko-hc** [comment]
Yes, I can confirm that it's reproduced under the version 5.14.2

**Comment by jurgis-sipols** [comment]
It might be done in 5.14.0, PR `https://github.com/mockito/mockito/pull/3437/files#diff-dc8b58b0826ca3b51eee39cb3066094b326a7fd2a3d55e492b25e7dea4ab1ad7`

Maybe it should not be shown in case `-XX:+EnableDynamicAgentLoading` is used?

Also, it is worth mentioning that explicit agent solution suggested by https://javadoc.io/doc/org.mockito/mockito-core/latest/org/mockito/Mockito.html#0.3 for the Maven builds does not work under this set-up and with Surefire plugin `3.5.2`

**Comment by raphw** [comment]
I can look into resolving the XX options. However, the warning is there for a reason. Your builds will start failing with Java 22+, so you unfortunately need to adjust your test plugin configuration.

**Comment by raphw** [comment]
I added a change that would suppress the option if `-XX:+EnableDynamicAgentLoading` is enabled. The :spotlessApply target seems to have disappeared, @TimvdLippe?

**Comment by TimvdLippe** [comment]
Might have been broken by the recent build refactorings @bric3 ?

**Comment by bric3** [comment]
Hi yes!
In gradle terms `:` is the root project, and mockito core code base used to be in the root project, now it's in mockito-core. Since the root project has no more code there's not anymore spotless tasks.

* So if you want to apply to mockito-core, use

   ```
   ./gradlew :mockito-core:spotlessApply
   ```
* If you just want to execute spotless apply in any submodule, use

   ```
   ./gradlew spotlessApply
   ```

   Note the lack of leading `:` which indicates the task will be searched in all projects.

**Comment by raphw** [comment]
Indeed, thanks. I just ran a command from my console history and fell over that.
