### ISSUE TITLE
Instructions on configuring mockito as agent lacks a Gradle Groovy DSL example (currently only Kotlin DSL)

### ISSUE THREAD

**Issue by EugenMayer** [mockito/mockito#3519]
# Setup

- mockito: 5.14.2
- gradle: 8.11.1
- java: 21
- linux

Followed the instructions on https://javadoc.io/static/org.mockito/mockito-core/5.14.2/org/mockito/Mockito.html#0.3

my catalog (amongs other things)
```toml
[versions]
mockito = "5.14.2"

[libraries]
mockito-core = { module = "org.mockito:mockito-core", version.ref = "mockito"}
```

```groovy
var mockitoAgent = configurations.create("mockitoAgent")

dependencies {
    // java agent based mockito configuration see https://github.com/mockito/mockito/pull/3454
    mockitoAgent(javaDeps.mockito.core) { isTransitive = false }
}
```

# Issue

Running gradle, i get the error for the line `mockitoAgent(javaDeps.mockito.core) { isTransitive = false }`

```
Could not find method call() for arguments [map(valueof(DependencyValueSource)), common_dependencies_tests_e6abh55rycnig0zejb3yxvkrs$_run_closure1$_closure3@d78cf57] on configuration ':core:mockitoAgent' of type org.gradle.api.internal.artifacts.configurations.DefaultUnlockedConfiguration.
```

# What i tried

I also tried

```groovy
mockitoAgent("org.mockito:mockito-core:5.14.2") {
        isTransitive = false
}
```

# Assumption
Is it a gradle version incompatibility (gradle 8.11.1) or something else? I'am using groovy

**Comment by bric3** [comment]
The documented instructions work fine with Gradle 8.11.1 when using kotlin dsl (which is the default in `gradle init` now, and the preferred way nowadays).

The `call` here seems to suggest a groovy DSL gradle script.

```
Could not find method call() for arguments [map(valueof(DependencyValueSource)), common_dependencies_tests_e6abh55rycnig0zejb3yxvkrs$_run_closure1$_closure3@d78cf57] on configuration ':core:mockitoAgent' of type org.gradle.api.internal.artifacts.configurations.DefaultUnlockedConfiguration.
```

Also your snipped shows `javaDeps.mockito.core` shouldn't it be `libs.javaDeps.mockito.core` ?
I'm away from keyboard at the moment. But I would suggest to adapt the documentation _example_ to the `build.gradle` if that's your case. Or eventually convert your script to kotlin dsl.

```kotlin
 val mockitoAgent = configurations.create("mockitoAgent")
 dependencies {
     testImplementation(libs.mockito)
     mockitoAgent(libs.mockito) { isTransitive = false }
 }
 tasks {
     test {
         jvmArgs("-javaagent:${mockitoAgent.asPath}")
     }
 }
```

**Comment by EugenMayer** [comment]
> Also your snipped shows javaDeps.mockito.core shouldn't it be libs.javaDeps.mockito.core ?
this depends how you define your catalog

```kotlin
dependencyResolutionManagement {
    versionCatalogs {
        create("springDeps") {
            from("...")
        }
        create("javaDeps") {
            from("...")
        }
    }
}
```

Becomes esp important if you use more then one catalog.

> The documented instructions work fine with Gradle 8.11.1 when using kotlin dsl (which is the default in gradle init now, and the preferred way nowadays).

I know, but since kts syntax is by far not in feature parity with groovy ( most importantly the `apply from: ` limitations due to strong typing ), which makes splitting up build gradle files very hard (without starting the huge effort of convention plugins) - so not everyone yet is keen to use it. (i love kotlin, but here, it is not just a straight win)

>  Or eventually convert your script to kotlin dsl.
is there a way to go the other way around? What would be the counter part in groovy?

Thanks for the help

**Comment by bric3** [comment]
> Is there a way to go the other way around? What would be the counter part in groovy?

Here's how the same example can be done in groovy, note I'm still using the default catalog "libs" here.

```groovy
configurations {
    mockitoAgent
}
dependencies {
    mockitoAgent(libs.mockito) {
        transitive = false
    }
}
tasks {
    test {
        jvmArgs += "-javaagent:${configurations.mockitoAgent.asPath}"
    }
}
```

----

_Out of scope for this issue._

On the kotlin dsl side, you mentioned the limitations of _`apply from:` due to strong typing_. COuld you be more explicit, I never encountered problems for `apply from` in particular. I indeed had to write things differently in `kts` by using names explicitly like `named` / `getByName` but that's what the Groovy Dsl does under the hood anyway and not specific to split files ; personally I actually find it safer because it's more explicit.

**Comment by bric3** [comment]
> Maybe we should add the non kts example to the docs?

Yes I will. Meanwhile I will rename this issue, so it will be easier to find.

----

I see your point. I lived with it in the past. But now I think it's worth to invest in Kotlin DSL plugins. Maybe something like this https://github.com/melix/includegit-gradle-plugin from @melix could work for you ?

**Comment by harimm** [comment]
Thanks for the solution! I had been stumped on this issue since yesterday.
