### ISSUE TITLE
InlineDelegateByteBuddyMockMaker.clearAllMocks triggers a NPE

### ISSUE THREAD

**Issue by adrian-tarau** [mockito/mockito#3558]
Due to OOM, we had to clear the cache of the inline mocker. The project that had the OOM is now fine. However, another project exhibits an issue in a few tests where we call _MockUtil.isMock_.

```
Caused by: java.lang.NullPointerException: Cannot invoke "org.mockito.mock.MockCreationSettings.getMockMaker()" because the return value of "org.mockito.invocation.MockHandler.getMockSettings()" is null
        at org.mockito.internal.util.MockUtil.getMockHandlerOrNull(MockUtil.java:160)
        at org.mockito.internal.util.MockUtil.isMock(MockUtil.java:147)
```

Looking at the code, since the purpose of the rest of existing mocks to to fail on reuse, it would be better to just create default settings instead of reusing the one used to create the mock?

Instead of 

```
public void clearAllMocks() {
        mockedStatics.getBackingMap().clear();

        for (Entry<Object, MockMethodInterceptor> entry : mocks) {
            MockCreationSettings settings = entry.getValue().getMockHandler().getMockSettings();
            entry.setValue(new MockMethodInterceptor(DisabledMockHandler.HANDLER, settings));
        }
    }
```

use

```
public void clearAllMocks() {
        mockedStatics.getBackingMap().clear();

        for (Entry<Object, MockMethodInterceptor> entry : mocks) {
            entry.setValue(new MockMethodInterceptor(DisabledMockHandler.HANDLER, Mockito.withSettings()));
        }
    }
```

**Comment by TimvdLippe** [comment]
Can you provide a reproduction case so we can understand the situation you are running into? Mocks in the backing map should all be real and thus a NPE shouldn't happen (in theory).

**Comment by adrian-tarau** [comment]
It is impossible to provide a setup that reproduces everything we have. What is interesting is that running all tests under IDE (IntelliJ) does not exhibit the issue, but running the tests with Maven does.

Let me replace the call and see if it fails. If it does, I could use the value when the handler is NULL.

**Comment by adrian-tarau** [comment]
OK, 5.15.1 works fine, and it revealed an issue:

> Caused by: org.mockito.exceptions.misusing.DisabledMockException: Mock accessed after inline mocks were cleared

It would be nice to tell which mock (the type) was reused. I guess we will hunt down these mocks and wait for the next release :)

**Comment by adrian-tarau** [comment]
I'll open a feature request for a DisabledMockException with mock information. Thanks.
