### ISSUE TITLE
Add MockitoHamcrest.varArgThat

### ISSUE THREAD

**Issue by manderson23** [mockito/mockito#356]
It would be useful to support something like the following:

`verify(a).amethod(eq(1), varArgThat(arrayContainingInAnyOrder(arg1, arg2, arg3)));`

For now I'm using the solution at http://stackoverflow.com/a/31142703/70795

**Comment by terebesirobert** [comment]
Hi,
I would like to work on this. Thanks

**Comment by marcingrzejszczak** [comment]
@terebesirobert have you done anything about this?

**Comment by terebesirobert** [comment]
HI,
I saw that nobody is answering on this, so I didn't. Sorry, I'm new on this.

**Comment by marcingrzejszczak** [comment]
So are you planning to do sth about it? :)

**Comment by terebesirobert** [comment]
If it's not urgent, I would like to give it a try. Right now I don't really have time for this. WDYT?

**Comment by marcingrzejszczak** [comment]
Be our guest :) It would be nice to see this in an example.

**Comment by terebesirobert** [comment]
Thanks. Could you please take a look at #358

**Comment by manderson23** [comment]
I've just upgraded to 2.2.15 and can now replace

`verify(a).amethod(eq(1), varArgThat(arrayContainingInAnyOrder(arg1, arg2, arg3)));`

with

`verify(a).amethod(1, arg1, arg2, arg3);`

**Comment by TimvdLippe** [comment]
@manderson23 Is your issue resolved and can we close this ticket?

**Comment by manderson23** [comment]
@TimvdLippe happy for this to be closed.
