### ISSUE TITLE
v2.0.42-beta - Cannot mock interface which extends a generic interface

### ISSUE THREAD

**Issue by messo** [mockito/mockito#359]
Hi!

The following tiny example doesn't work:
```java
public class MockTest {

    @Test
    public void mock() {
        Mockito.mock(MyIterable.class);
    }

    public interface MyIterable extends Iterable<Double> {
    }
}
```

I get:

> org.mockito.exceptions.base.MockitoException: 
> Mockito cannot mock this class: interface hu.messo.MockTest$MyIterable
> 
> Mockito can only mock visible & non-final classes.
> If you're not sure why you're getting this error, please report to the mailing list.
> 
> Underlying exception : java.lang.IllegalArgumentException: object is not an instance of declaring class

My original interface is much more complex, but this showcases the issue. Is there any way to make it work?

Kind regards,
Bálint

**Comment by messo** [comment]
This might be also related: The following generates the same error:

```java
public class MockTest {

    @Test
    public void mock() {
        Mockito.mock(Magic.class);
    }

    interface Magic {
        void doMagic(Iterable<Double> operands);
    }

}
```

**Comment by raphw** [comment]
I cannot reproduce this, both tests do not raise any errors on my machine.

Are you sure that your setup is legit?

**Comment by messo** [comment]
@raphw I have just tried it on an other machine, and it works perfectly. Even these examples, even the more complex one. I will check it again on the other machine, but it seems the problem is at my side.

Thanks for the help!

**Comment by raphw** [comment]
FYI, the problem is related to running an outdated version of Java 8. See this ticket for reference: https://github.com/mockito/mockito/issues/362

**Comment by messo** [comment]
Thanks for the clarification ;)
