### ISSUE TITLE
Mockito doesnt work with arquillian, missing dependecy SignatureVisitor

### ISSUE THREAD

**Issue by gpor89** [mockito/mockito#363]
Hey,

I am trying to use mockito within arquillian testing platform on jboss standalone server.

configuration:
pom.xml
`<dependency>
            <groupId>org.mockito</groupId>
            <artifactId>mockito-all</artifactId>
<version>1.10.19</version>
            <scope>test</scope>
        </dependency>`

Test:
`mocking one class T...

@Deployment
ShrinkWrap.create(...).addPackages(true, "org.mockito")...
`
returns java.lang.NoClassDefFoundError: org/mockito/asm/signature/SignatureVisitor

after opening mockito library i can't find this class, neither signature package. Documentation says that mockito doesn't use cglib anymore. Why my deployment keeps asking for it?

**Comment by PascalSchumacher** [comment]
@gpor89 As far as I know mockito 1.x uses cglib. Cglib was removed for mockito 2.x.

**Comment by raphw** [comment]
This should be resolved in 2.0 where the manifest is fixed. I am therefore closing this issue.
