### ISSUE TITLE
Mockito fails to mock methods results on Kotlin classes.

### ISSUE THREAD

**Issue by magillus** [mockito/mockito#364]
Reproduction project located at: https://github.com/magillus/UnitTestProject

We found issue with mocking method's response, executed the mocked service method.
In test project we have 2 TestService classes ([TestService - kotlin](https://github.com/magillus/UnitTestProject/blob/master/app/src/main/java/tests/com/unittestproject/TestService.kt), [TestService2 - java](https://github.com/magillus/UnitTestProject/blob/master/app/src/main/java/tests/com/unittestproject/TestService2.java)), one written in java other written in kotlin.
Same tests were mocking the TestService and method's return value.
Kotlin TestService based unit test failed while executing the mocked method, while Java TestService based unit test succeeded.

[Unit Test](https://github.com/magillus/UnitTestProject/blob/master/app/src/test/java/tests/com/unittestproject/ReproduceUnitTest.java)

note: project also used PowerMockito as alternative with same results.

**Comment by szpak** [comment]
I'm not a Kotlin user, but there were some issues with return values in Kotlin (#328). Can you give [mockito-kotlin](https://github.com/nhaarman/mockito-kotlin) a try?

**Comment by magillus** [comment]
Thank you for response, however mockito-kotlin doesn't help, still uses mockito under the hood.

**Comment by magillus** [comment]
it was fixed by opening the kotlin function - as @clackbib pointed out in pull request
https://github.com/magillus/UnitTestProject/pull/1
