### ISSUE TITLE
Wrong return type as a result of getGenericReturnType() on Spy object class

### ISSUE THREAD

**Issue by vladad** [mockito/mockito#378]
Hello,
I have simple class which one method returns generic list:

    private static class TestClass
	{
		public List<String> getList()
		{
			return null;
		}
	}

I want to get generic return type via reflection:

    @Test
	public void testMockito() throws Exception
	{
		TestClass standard = new TestClass();
		TestClass spy = spy(new TestClass());

		Type standardReturnType = standard.getClass().getMethod("getList", null).getGenericReturnType();
		Type spyReturnType = spy.getClass().getMethod("getList", null).getGenericReturnType();
	}

But results are different:

    standardReturnType = {sun.reflect.generics.reflectiveObjects.ParameterizedTypeImpl@2117} "java.util.List<java.lang.String>"

    spyReturnType = {java.lang.Class@78} "interface java.util.List"

And I cannot get generic type &lt;String&gt; in test, because there is only Class instance instead of ParameterizedType.

My Mockito version is 1.10.19.

Thanks.

**Comment by raphw** [comment]
We have changed the byte code provider with the latest beta. This is already resolved in the current build. Please update to the current 2.0 state. The version is stable only with the possibility of API changes or the removal of deprecated code.
