### ISSUE TITLE
JUnit rule logs warnings about unsued / misused stubs

### ISSUE THREAD

**Issue by szczepiq** [mockito/mockito#384]
### Why

When test fails, the failure might be caused by misused stubs. Hence, it might be worth to log out debugging information to the System out (e.g. misused stubs, unused stubs).

### Plan

- [ ] document 2.x change
- [x] tweak the warning message
- [ ] add behavior to the runner
- [ ] add silent runner
- [ ] add silent setting to the rule (or warnings level for all / exception only / none)
- [ ] deprecate/remove console spamming runner

### Impl

The JUnit rule or the runner will potentially include following info in the output (somehow): https://gist.github.com/szczepiq/38619fd8766c66c46dff4dc2b6db06ec

I'm wondering if "Mockito.validateMockitoUsage();" should automatically print warnings. We could provide boolean parameter to control printing of the warnings.

**Comment by szczepiq** [comment]
On it.

**Comment by ChristianSchwarz** [comment]
I like the feature! What do you think about a `rule().strict()` that doesn't emit logs but fails asap?

A note to the API:
 * How do we prevent misuse like -> `rule().strict().strict()` ? What about `rule(LOG_WARNINGS)` aka `rule()`, `rule(SILENT)`, `rule(FAIL_FAST)`

**Comment by szczepiq** [comment]
Christian, very cool ideas!!! 

I'm not sure I'll have time for it before 2.0. However, I want the new default behavior in rule / runner in 2.0 so that users see what it is doing. Then we can grow and add strict mode.

**Comment by t1** [comment]
@szczepiq: I like this feature very much. Also that the `MockitoJUnitRunner` fails by default is good. I think a note in the javadoc of `UnnecessaryStubbingException` to use `MockitoJUnitRunner.Silent` would be helpful.

We often have quite complex test fixtures, and it's cumbersome to switch absolutely each and every stub on or off... some methods simply have to be there; it's also not necessary to verify if they've been invoked. So it would be great to be able to disable it for some stubs, but leave it on for others.

**Comment by TimvdLippe** [comment]
@t1 That seems like a reasonable idea. Want to make a PR for that?

**Comment by szczepiq** [comment]
Good feedback. I think that MockitoHint class should also mention that it is possible to silence the new mechanism.

**Comment by szczepiq** [comment]
#609

**Comment by Sarev0k** [comment]
The [MockitoHint](http://site.mockito.org/mockito/docs/current/org/mockito/quality/MockitoHint.html) documentation seems to indicate that this will give you warnings about mismatched arguments, when using the MockitoJUnitRunner.  However, from my experience this doesn't seem to work with Mockito 2.1.

Here's the source I'm trying:
```java
Foo foo = mock(Foo);
when(foo.bar('baz')).thenReturn('bar');

foo.bar('baz');
foo.bar('test'); // expected to get a warning here
```

Is there something else I need to do to enable this functionality?

**Comment by szczepiq** [comment]
Thank you for feedback!

>Is there something else I need to do to enable this functionality?

This is how they were implemented. Runner should also report mismatches because it helps with debugging. The reason it does not do it today is because I wanted to limit the noise.

We will fix this issue. Also, we will consider always printing warning when stub args mismatch, even if one does not use runner / rule.

Do you want to open a separate ticket to track this improvement?

Thanks for reporting!

**Comment by Sarev0k** [comment]
I've opened #725 to track this.

**Comment by sanjaypujare** [comment]
Came across this after running into this in my test :
```
[MockitoHint] MyTest.checkSomething (see javadoc for MockitoHint):
[MockitoHint] 1. Unused -> at MyTest.test1(MyTest.java:584)
```
It is complaining about this (line 584):
```
   when(mockObject.getPeerHost()).thenReturn("peer-host-from-mock");
```
Now my issue is this: this particular method `getPeerHost()` is indeed not called when the code works as expected e.g. something like this:
```
   if (newMethod()) {
      ...
       String peerHost = mockObject.getPeerHost();
       // use peerHost in further processing
      ...
   }
```
`newMethod()` is the new code being added and should correctly return `false`. However if there is a bug in `newMethod()` and it returns `true` then I want `getPeerHost()` to return some value which will cause a failure that I can detect. So this requires me to mock a method even if it is not called in normal processing and there is no bug in the code. I think that should not generate a warning. Has this been addressed?

**Comment by sanjaypujare** [comment]
Do I need to open a new issue as I cannot reopen this?

**Comment by mockitoguy** [comment]
> Do I need to open a new issue as I cannot reopen this?

Yes, please.

> Has this been addressed?

Yes. For example, you can use ```lenient().when(...)``` stubbing to avoid reporting an unused stubbing. However, in your test case, I would simply write ```verify(mockObject, never()).getPeerHost();```.

Hope that helps!

**Comment by mockitoguy** [comment]
My recommendation is to use lenient() + strict stubbing for this use case.

If you feel we should still discuss the use case ``verify(never())`` vs. ``when(...).thenThrow(...)`` then please open a separate ticket.

Hope that helps and thank you for feedback!
