### ISSUE TITLE
Support for JUnit 5 (JUnit Lambda)

### ISSUE THREAD

**Issue by raphw** [mockito/mockito#390]
I think we should support JUnit 5 with Mockito 2. Currently, we maintain an optional dependency on JUnit four but the JUnit 5 API is completely incompatible to the old one. I already explored the extension mechanism a bit and for our use case, it is quite trivial.

There are some caveats with JUnit 5, for example the possibility to reuse a test instance what would require us to extend the rule for reseting mocks between runs but it is more than doable. Actually, I suggest making `@Mock` a meta annotation, this way, we can completely drop the MockitoJUnitRunner runner and the MockitoJUnit rule and make the setup even easier.

The JUnit 5 API is still in alpha. How do we do this?

**Comment by szpak** [comment]
JUnit 5 seems to support only Java 8. Is its API Java 7 compatible? Or maybe you meant Mockito 3 (incoming just after Mockito 2, but with official Java 8 support :) )?

**Comment by raphw** [comment]
That is why I would suggest to put it into a side-project. JUnit 5 is compiled to Java 8 byte code but we could deliver the integration in Java 6 nevertheless.

**Comment by ChristianSchwarz** [comment]
JUnit 5 looks very promising, extensions replacing [Runner, Rule & ClassRule](http://junit.org/junit5/#extension-model). 

Surprise surprise :sparkles: , here is a sample -> the [MockitoExtension](https://github.com/junit-team/junit5-samples/blob/master/junit5-mockito-extension/src/main/java/com/example/mockito/MockitoExtension.java)

**Comment by TimvdLippe** [comment]
While I do think it is worth exploring, in my eyes pushing this to Mockito 3.0 with Java 8 seems more safe. This also gives time for the JUnit team to tinker everything and push to beta, to reduce the compatibility burden for jumping on the train too soon.

**Comment by TimvdLippe** [comment]
Merging this into #445
