### ISSUE TITLE
Deprecate MockitoJUnitRunner in favor of MockitoRule?

### ISSUE THREAD

**Issue by ChristianSchwarz** [mockito/mockito#391]
Since we have the comfortable MockitoRule I wonder if MockitoJUnitRunner can be marked as deprecated and removed in Mockito 2. Is there a need to have 2 concepts for the same task? Maybe I overlooked something.

**Comment by raphw** [comment]
For older versions of JUnit, the Rule mechanism is not available. On the other side, people should have upgraded when using Mockito 2.

**Comment by szczepiq** [comment]
Let's keep the runner for now. We can deprecate / remove it in the future, though.

**Comment by szczepiq** [comment]
Thanks for the idea, though!
