### ISSUE TITLE
Can't click "release notes" link from mockito.org

### ISSUE THREAD

**Issue by adamv-dev9** [mockito/mockito#393]
The "release notes" link on mockito.org that links to GitHub fails to load on Chrome 50 OS X with this error in the console:

`Refused to display 'https://github.com/mockito/mockito/blob/master/doc/release-notes/official.md' in a frame because an ancestor violates the following Content Security Policy directive: "frame-ancestors 'none'".`

**Comment by szczepiq** [comment]
Thanks for reporting!

For the time being, you can "open in new tab".

I'll try to resolve this issue.

On Fri, Apr 15, 2016 at 10:51 AM, Adam Vandenberg <notifications@github.com>
wrote:

> The "release notes" link on mockito.org that links to GitHub fails to
> load on Chrome 50 OS X with this error in the console:
>
> Refused to display '
> https://github.com/mockito/mockito/blob/master/doc/release-notes/official.md'
> in a frame because an ancestor violates the following Content Security
> Policy directive: "frame-ancestors 'none'".
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/mockito/mockito/issues/393>
>



-- 
Szczepan Faber
Founder @ mockito.org | Twitter @ szczepiq
Author @ https://www.linkedin.com/today/author/6016386

**Comment by szczepiq** [comment]
I poked around but I don't know quite how to fix it easily. I need to move
to a different domain service provider. I will plan on doing that.

On Sat, Apr 16, 2016 at 10:10 AM, Szczepan Faber <szczepiq@gmail.com> wrote:

> Thanks for reporting!
>
> For the time being, you can "open in new tab".
>
> I'll try to resolve this issue.
>
> On Fri, Apr 15, 2016 at 10:51 AM, Adam Vandenberg <
> notifications@github.com> wrote:
>
>> The "release notes" link on mockito.org that links to GitHub fails to
>> load on Chrome 50 OS X with this error in the console:
>>
>> Refused to display '
>> https://github.com/mockito/mockito/blob/master/doc/release-notes/official.md'
>> in a frame because an ancestor violates the following Content Security
>> Policy directive: "frame-ancestors 'none'".
>>
>> —
>> You are receiving this because you are subscribed to this thread.
>> Reply to this email directly or view it on GitHub
>> <https://github.com/mockito/mockito/issues/393>
>>
>
>
>
> --
> Szczepan Faber
> Founder @ mockito.org | Twitter @ szczepiq
> Author @ https://www.linkedin.com/today/author/6016386
>



-- 
Szczepan Faber
Founder @ mockito.org | Twitter @ szczepiq
Author @ https://www.linkedin.com/today/author/6016386

**Comment by bric3** [comment]
@szczepiq `mockito.org` redirects to github via an iframe. That is the reason of the problem.

```html
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Frameset//EN" "http://www.w3.org/TR/html4/frameset.dtd">
<HTML><HEAD><TITLE></TITLE></HEAD>
<FRAMESET ROWS="*"><FRAME NAME=997 NORESIZE SRC="http://mockito.github.io">
<NOFRAMES><BODY><A HREF="http://mockito.github.io">click here</A></BODY></NOFRAMES></FRAMESET></HTML>
```

In order to set properly the domain you need to change the way `mockito.org` is redirected. That should be doable in your DNS provider (probably by removing some entries).

However I advise to change DNS configuration to use register the `CNAME` entry on `mockito.org` not `site.mockito.org`, and update accordingly the `CNAME` file on https://github.com/mockito/mockito.github.io



Currently : 

```bash
❯ dig +nocmd +nostats +noadditional +noquestion +nocomment any site.mockito.org
site.mockito.org. 3011    IN      CNAME   mockito.github.io.
mockito.org.            85811   IN      NS      dns2.home.pl.
mockito.org.            85811   IN      NS      dns.home.pl.
mockito.org.            85811   IN      NS      dns3.home.pl.
❯ dig +nocmd +nostats +noadditional +noquestion +nocomment any mockito.org
mockito.org.           86257   IN      SOA     dns.home.pl. admin.home.pl. 1456474041 10800 3600 604800 3600
mockito.org.            3457    IN      MX      10 mockito.org.
mockito.org.            2986    IN      A       89.161.255.6
mockito.org.            85786   IN      NS      dns2.home.pl.
mockito.org.            85786   IN      NS      dns3.home.pl.
mockito.org.            85786   IN      NS      dns.home.pl.
mockito.org.            85786   IN      NS      dns.home.pl.
mockito.org.            85786   IN      NS      dns2.home.pl.
mockito.org.            85786   IN      NS      dns3.home.pl.
```

**Comment by bric3** [comment]
By the way this will solve this issue as well : https://github.com/mockito/mockito.github.io/issues/3

**Comment by bric3** [comment]
And this one too : https://github.com/mockito/mockito.github.io/issues/11

**Comment by TimvdLippe** [comment]
@szczepiq could you move `site.mockito.org` to `mockito.org`?

**Comment by szczepiq** [comment]
Sure, how do I do that?

**Comment by TimvdLippe** [comment]
Um I do not know, I do not have access to the server :p Just copy your configuration from site.mockito.org to mockito.org?

**Comment by bric3** [comment]
Or give us access ;)

**Comment by szczepiq** [comment]
Sure, access to what?

**Comment by bric3** [comment]
to the DNS provider ;)

**Comment by bric3** [comment]
So we can either try configure it or make the move to another DNS just like your plan.
And maybe share the expanse of this domain.

**Comment by szczepiq** [comment]
This should be fixed now. My domain provider started offering 301 redirect.

Regarding access to domain provider - I didn't find a way to configure the access per domain, and I don't intend to share access to all my domains at this time. Thanks for understanding ;)
