### ISSUE TITLE
WrongTypeOfReturnValue when abstract class have two abstract method

### ISSUE THREAD

**Issue by manorip** [mockito/mockito#399]
Hey
I found a strange problem, when i create a abstract class:

```java
abstract class AbstractClass {
    abstract protected Long lol();
    abstract protected String wow();
    public String give() {
        wow();
        lol();
        return "give";
    }
}
```

and i have another class extends abstract Class:

```java
public class ClassExtendsAbstractClass extends AbstractClass {
@Override
 protected Long lol() {
        return 2L;
    }
    @Override
    protected String wow() {
        return "WOW";
    }
}
```

and I have class:
```java
public class A {
  private ClassExtendsAbstractClass classExtendsAbstractClass;
  public A(ClassExtendsAbstractClass classExtendsAbstractClass) {
    this.classExtendsAbstractClass = classExtendsAbstractClass;
  }
  public String doSomeThing(){
    return classExtendsAbstractClass.wow();
  }
}
```

and when i try mock method doSomeThing() from A class in test:

```java
  @Mock
  private ClassExtendsAbstractClass classExtendsAbstractClass;
  private A a;

  @Before
  public void before(){
    Mockito.when(classExtendsAbstractClass.give()).thenReturn("aaa");
  }
  @Test
  public void test() {
    a = new A(classExtendsAbstractClass);
  }
```

I get the error:

> org.mockito.exceptions.misusing.WrongTypeOfReturnValue: 
> String cannot be returned by lol()
> lol() should return Long

This is strange behavior, because the method `lol()` should not be called, but when I delete one abstract method everything is good.

**Comment by raphw** [comment]
Have you tried updating to the latest beta? We changed the byte code provider so this might already be resolved.

**Comment by manorip** [comment]
I using 2.0.2- beta from maven repository: http://mvnrepository.com/artifact/org.mockito/mockito-all/2.0.2-beta

**Comment by raphw** [comment]
We are currentlz at beta 2.0.50. I also just ran your example and everything seems to be fine.

**Comment by manorip** [comment]
When i try use 2.0.50-beta [](http://search.maven.org/#artifactdetails%7Corg.mockito%7Cmockito-core%7C2.0.50-beta%7Cjar) i have error:

> Caused by: java.lang.ClassNotFoundException: org.mockito.cglib.proxy.Callback

**Comment by raphw** [comment]
Seems like you have different mockito versions in your project. The current version does no longer depend on cglib.

**Comment by manorip** [comment]
I had dependency to powermock-api-mockito that created the problem . Now everything is working properly

**Comment by raphw** [comment]
Perfect, thanks for reporting this back.
