### ISSUE TITLE
Vararg method call on mock object fails when used org.mockito.AdditionalAnswers#delegatesTo

### ISSUE THREAD

**Issue by andreyrmg** [mockito/mockito#407]
I try to mock interface with varargs method and default implementation in final class and get this error:
```
java.lang.IllegalArgumentException: wrong number of arguments

	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.mockito.internal.stubbing.defaultanswers.ForwardsInvocations.answer(ForwardsInvocations.java:31)
	at org.mockito.internal.handler.MockHandlerImpl.handle(MockHandlerImpl.java:93)
	at org.mockito.internal.handler.NullResultGuardian.handle(NullResultGuardian.java:29)
	at org.mockito.internal.handler.InvocationNotifierHandler.handle(InvocationNotifierHandler.java:38)
	at org.mockito.internal.creation.MethodInterceptorFilter.intercept(MethodInterceptorFilter.java:51)
```

I run the following code:
```java
public class DefaultAnswerDemo {

    public interface Foo {
        void bar(String baz, Object... args);
    }

    public static final class FooImpl implements Foo {

        @Override
        public void bar(String baz, Object... args) {
            System.out.println("bar");
        }

    }

    @Test
    public void defaultAnswerTest() {
        Foo fooImpl = new FooImpl();

        Foo foo = mock(Foo.class, withSettings()
                .defaultAnswer(delegatesTo(fooImpl)));

        foo.bar("baz", 12, "45", 67.8);
    }

}
```

This is happens because org.mockito.internal.invocation.InvocationImpl by default expands varargs arguments to flat list. And I have no idea, how correctly fix this.

**Comment by ChristianSchwarz** [comment]
This is a bug in [ForwardsInvocations](https://github.com/mockito/mockito/blob/master/src/main/java/org/mockito/internal/stubbing/defaultanswers/ForwardsInvocations.java#L41), as you already investigated the expanded varargs are passed to the delegate.

The current implementation does this:
```
result = delegateMethod.invoke(delegatedObject, arguments);
```
Mockito look for method with the signature `String,int,String,double` for the given arguments ("baz",12,"45",67.8), but such a method doesn't exists.

To fix the issue the raw/unexpanded arguments must be used

```
Object[] rawArguments = ((Invocation)invocation).getRawArguments(); 
result = delegateMethod.invoke(delegatedObject, rawArguments);
```
Now Mockito looks for method signature `String,Object[]` which is the var args method you want. Note: It is safe to cast to `Invocation` here cause answers always get a Invocation-Instance passed from `MockHandlerImpl`. 

If I find some time I will send a PR with a fix or you or some one else start to fix it.

**Comment by andreyrmg** [comment]
Here is PR. I thought about cast, but may be better pull up method [org.mockito.invocation.Invocation#getRawArguments](https://github.com/mockito/mockito/blob/master/src/main/java/org/mockito/invocation/Invocation.java#L42) to interface [org.mockito.invocation.InvocationOnMock](https://github.com/mockito/mockito/blob/master/src/main/java/org/mockito/invocation/InvocationOnMock.java)?

**Comment by ChristianSchwarz** [comment]
@andreyrmg 
Pulling `getRawArguments()` up to `InvocationOnMock` would help in this narrow use case. On the other side it bloat the public API and migth confuse clients that implement custom Answer's, which method to choose `getArguments()` or `getRawArguments()`.  

WDYT?

**Comment by andreyrmg** [comment]
Yes, I agree with you. But I think, this is already a bit confusing that method `getArgument()` returns expanded varargs. Maybe we need two methods `getArguments()` and `getExpandedArguments()`?

**Comment by ChristianSchwarz** [comment]
Adding new API or changing existing behaviour need to be discussed with the core-members.
 
I agree with you, `getArguments()` should return unaltered/not expanded arguments. The current `getArguments()` implementation has also the problem that is can't distinguish an null-vararg argument / `varArgMethod(new Type[]{null})` from an null-varag array / `varArgMethod((Type[])null)`.
