### ISSUE TITLE
Selective capturing matcher

### ISSUE THREAD

**Issue by zglagola** [mockito/mockito#409]
Creating an issue tracker for a feature request.

A small team i've been working with has created an extended use case wrapping Mockito. We'd like to add in some of the functionality that we've found to be particular useful during our own development.

One such item is an ArgumentCaptor that matches on a provided ArgumentMatcher. We've had several use cases within our own library where we'd like capture an argument that meets a certain condition, and leverage that captured argument for additional verification or reporting.

You _could_ capture the value, then match it against the provided matcher in a separate step. This alleviates the extra work.

Usage example:
We have an API that emits a host of Kafka (http://kafka.apache.org/) events. It's hyper-critical that we have high test coverage for the various events that we emit, so we created a separate TestNG reporter (http://testng.org/javadocs/org/testng/IReporter.html) to generate a basic coverage report (events tested / total events). As the user makes verification on the events they've emitted (using custom matchers), we capture and log them to the reporter.

**Comment by terebesirobert** [comment]
Hi,
I've implemented something similar some time ago. 
https://github.com/mockito/mockito/pull/375
What do you think, is this what you are looking for?
Thanks,
    Robert

**Comment by zglagola** [comment]
Very similar! Though, it feels a bit like a rocket ship when a golf cart is needed?

From an API perspective, does an `ArgumentCaptor` make sense if you call `captureIf` in multiple contexts?

EX:
```
verify(myMock).myMethod(captor.captureIf(matcher1), captor.captureIf(matcher2), captor.captureIf(matcher3))
List myList = captor.getAllValues();
```
What does myList contain? A list of captured arguments via different matchers? How are they related?

What do you think Robert?

**Comment by terebesirobert** [comment]
@zglagola 

Hi,
It will return 3 different values that are captured by the 3 different matchers. What would you expect to happen?

Thanks

**Comment by ChristianSchwarz** [comment]
@zglagola 
In this case the captor contains all arguments that satisfy the corresponding matcher. I have thougt about an API like `ArgumentCaptor#forClass(Class, ArgumentMatcher)` too, but dropped the idea because the the captor can not be created by `@Mock`. The changes made in PR #375 by @terebesirobert are flexible enough to add your proposed API too.

Good to see that this kind of feature has some support in the community. I hope this makes it easier for the mockito core team to decide if such a feature should be added or not.
For the record this issue address the same feature: #160 "AdditionalMatchers logical matchers don't capture arguments"

**Comment by zglagola** [comment]
@ChristianSchwarz 
Excellent point, you're right. I definitely think there is a gap with the current conception.

@terebesirobert 
With the above point i certainly think your solution makes sense here. Especially since specifying an `ArgumentMatcher` in an annotation feels a bit ridiculous.

My earlier concern, i'm wondering if users will want to know the matchers which captures a particular value, hence asking what they all have in common. In the earlier example:

```
verify(myMock).myMethod(captor.captureIf(matcher1), captor.captureIf(matcher2), captor.captureIf(matcher3))
List myList = captor.getAllValues();
```

`myList` contains 3 values that potentially have no relationship to one another outside of the fact that they used the same `ArgumentCaptor` instance. As an extension to `ArgumentCaptor#forClass`, you have a guarantee that everything was captured in a single context (class and argument matcher combination) since that was how the `ArgumentCaptor` was instantiated.

What do you think? Is that a feature or an issue?

**Comment by terebesirobert** [comment]
@zglagola 

Hi,

I would say that it is a feature. We could have a new method called, something like `getAllValuesCapturedBy(mathcer)`, which will return all the values captured by the matcher. 
As the method name suggests, it should returned all the values captured by the `ArgumentCaptor`.

WDYT?

**Comment by zglagola** [comment]
@terebesirobert 

Hmmm, that feels like feature bloat though, doesn't it? It looks like we are still in the qualification phase of 'is this a useful addition to Mockito', which i certainly think it is. Adding various ways to mix and match feels like overkill?

With respect to feature vs. issue, could you help me understand your perspective better? Want to understand how the additional flexibility is a need vs. a want.

**Comment by terebesirobert** [comment]
@zglagola 
I don't really think is a need, 'cause I don't know why someone would expect to have some kind of relationship between the values returned when using the same `ArgumentCaptor`. WDYT?

**Comment by zglagola** [comment]
@terebesirobert 
Good point. I don't think there is a valid use case to justify needing that context today. Future aside, I feel much more aligned now :)

**Comment by terebesirobert** [comment]
@zglagola 
Thanks.

**Comment by ChristianSchwarz** [comment]
@zglagola 
Can this issue be closed in favor of #375?

**Comment by zglagola** [comment]
@ChristianSchwarz 
yup!

**Comment by ChristianSchwarz** [comment]
@bric3 @TimvdLippe @raphw 
This ticket can be closed. See 2 comments above.
