### ISSUE TITLE
objenesis INDEX.LIST should not be included in mockito-all jar

### ISSUE THREAD

**Issue by jchomicki** [mockito/mockito#418]
INDEX.LIST is meant as an optimization when loading a jar, as it points to relevant files for the jar thus circumventing a linear search. When creating a fat jar, this file should be left out for each extra included jar as it is meant to work for that jar alone.

Right now, the objenesis library included in mockito-all is not having it's INDEX.LIST deleted before inclusion in the final fat jar. This is causing a FileNotFound Exception in URLClassPath$JarLoader.getJarFile because it is trying to use the INDEX.LIST to find objenesis-2.1.jar when it does not exist in this case.

Started seeing this in 1.10.16 and last checked 2.0.2-beta.

**Comment by PascalSchumacher** [comment]
2.0.2-beta was the last version of mockito for which a mockito-all.jar was published. I can not find any mention of mockito-all in the current build scripts and `gradle assemble` does not build a mockito-all.jar, so I guess this issue can be closed.

**Comment by raphw** [comment]
mockito-all was removed and should no longer be used.
