### ISSUE TITLE
Changes to InvocationOnMock API should include version info

### ISSUE THREAD

**Issue by MichaelHackett** [mockito/mockito#420]
PR #365 added a new method, `getArgument`, to `InvocationOnMock`, and deprecated `getArgumentAt`, but the new docs do not mention the version at which the new method was added and from what version the deprecation is in effect. This is confusing for users who are still using the 1.10.x series when using the Javadocs on the mockito.org website (which just shows the latest docs).

A quick update to the docs in `InvocationOnMock` will solve this. I haven't yet noticed other instances of this, but a quick sweep of the recent changes might be worth doing, to see if the same sort of update needs to be done elsewhere.

**Comment by PascalSchumacher** [comment]
This issue can be closed as the deprecated `getArgumentAt` method was removed completely recently.

**Comment by MichaelHackett** [comment]
Removing the old method from the docs only "solves" part of the problem. A `@since` tag should still be added to `getArgument`, and ideally the method doc should mention that it replaces `getArgumentAt` (to make it easier to transition existing code to the new version).
