### ISSUE TITLE
Whitebox.setInternalState for private static final fields

### ISSUE THREAD

**Issue by andreicristianpetcu** [mockito/mockito#422]
Hello,

Can you please add the ability for [Whitebox.setInternalState](https://github.com/mockito/mockito/blob/74e312b7a9236a43eb543bd3184607b75375bc40/src/main/java/org/mockito/internal/util/reflection/Whitebox.java#L22-L31) to be invokable on classes with private static final field?

```java
Whitebox.setInternalState(ClassToTest.class, "LOG", mockLog);
```

I did not understand where is the best place to add a feature request. I hope this is the best place.

Thank you

**Comment by marcingrzejszczak** [comment]
Hi! Why would you even want to do that? It sounds like a absolutely terrible idea to do that. Can you provide some use case?

**Comment by andreicristianpetcu** [comment]
Thank you for the fast reply!
I need to test that a class behaves in different ways if the log level is debug or not and so I need to mock the logger. If debug is enabled my class will do some heavy computation. The logger is fetched with the classic SLF4J API `LogFactory.getLog(ClassToTest.class)`.

I can use powermock to mock `LogFactory.getLog` but things get quite complicated quite fast since this is invoked only once when the class is loaded. A cleaner solution would be to set the mock logger before the test.

I am working on a low level logging API so I cannot rely on dependency injection.

**Comment by TimvdLippe** [comment]
@andreicristianpetcu I think setter injection would be better and cleaner. In your test, you set the logger via this method. In your default behavior you only set it in your constructor.

**Comment by andreicristianpetcu** [comment]
Loggers are per class and not per instance. If I make my log field not a static final field SonarQube starts to complain. I can add a false positive to SonarQube but the rest of the company uses this behavior.

**Comment by TimvdLippe** [comment]
Well you have two options:
1. Make the setter static too. In your `@Before` set the logger to your mock, but storing the original logger. In `@After` set the logger back to the original logger.
* Deal with the deficiency of SonarQube and make this an exception. It is a tool to assist you during development, but not a holy grail imo.

**Comment by andreicristianpetcu** [comment]
I know that SonarQube is not a holy grail but I cannot change the SonarQube settings.
Would you refuse a pull request adding this feature? I imagine it is quite small.

**Comment by marcingrzejszczak** [comment]
Another solution is to wrap the logger in a class that you can inject. 

```
class LoggerProxy {

private static final Logger ...


void debug(...) {}
void info(...) {}

}
```

and then in your class you can call

```
class YourClass {
private final LoggerProxy proxy;

YourClass(LoggerProxy proxy) {
this.proxy = proxy;
}

void someMethod() {
loggerProxy.debug(...); // <-- this you can stub
}
```

I'd vote strongly against such a feature as allowing to set private final static fields. But that's just my vote ;)

**Comment by andreicristianpetcu** [comment]
I don't feel comfortable to write code specially to make my code testable.

Believe me I tried all possible options. I think setting the LOG field using reflection is the simplest. Right now we do it with a class who's purpose is to only set this field in several places. The only two options that I have:
 - use this class;
 - add the feature to upstream (in this case Mockito).

If you would not accept such a feature I will not add it but I think it adds value. I think setting private instance fields using reflection as it is currently implemented in Mockito is a bad practice but I use it anyway since there are some really rare cases where this is the best option. Setting private static final fields is the same as setting private instance fields: bad practice but needed from time to time.

**Comment by marcingrzejszczak** [comment]
Normally you shouldn't actually verify if stuff has been logged. If that's so important to you then IMO you should use good practices to achieve that solution. Maybe @bric3 or @szczepiq has some other opinion on this but I don't think that allowing more hacks to test a logger without injecting it through a constructor is a good idea.

**Comment by andreicristianpetcu** [comment]
I understand you will not use this feature, but do you consider it harmful?

**Comment by marcingrzejszczak** [comment]
I consider it allowing people write bad code. But that's only my opinion.
If others feel that this is a good feature to add then I'm not going to
object.

**Comment by TimvdLippe** [comment]
I have to side with @marcingrzejszczak here. Adding this functionality will likely result in bad code because the production code is not testable. I do not see making code testable as a problem.

**Comment by andreicristianpetcu** [comment]
Ok then. I'll try to make a pull request tonight and I hope it gets accepted :)

**Comment by marcingrzejszczak** [comment]
So I can assume that we can close this

**Comment by 7--** [comment]
> Hi! Why would you even want to do that? It sounds like a absolutely terrible idea to do that. Can you provide some use case?

Could you please explain to me why using a static class variable is a terrible idea?

**Comment by will-sargent-eero** [comment]
> I need to test that a class behaves in different ways if the log level is debug or not and so I need to mock the logger.

In this situation, you would set the logger's logging level to DEBUG from your logging framework, rather than mocking the logger.  For example in Logback:

```
LoggerContext loggerContext = (LoggerContext) LoggerFactory.getILoggerFactory();
ch.qos.logback.classic.Logger logger = loggerContext.getLogger(fullyQualifiedClassName);
logger.setLevel(Level.toLevel(logLevel));
```
