### ISSUE TITLE
Brief Question About Mockito Internal Interface

### ISSUE THREAD

**Issue by alinebrito** [mockito/mockito#428]
Dear Mockito developers,

I am a master student at UFMG, Brazil. Currently, I am researching the use of internal interfaces by client projects. I mean, public interfaces for use only by internal modules (e.g., org.mockito.internal.util.MockUtil).

In my research, I found 329 internal interfaces in Mockito (see the list at: [Internal Interfaces Mockito](https://www.dropbox.com/s/i3dyi4mvpyzd1lu/)). By mining data provided by the [Boa Language and Infrastructure](http://boa.cs.iastate.edu/), I also found 331 client projects that are using these internal interfaces. Therefore, these internal interfaces are usual in other projects.

1. Did you know that internal interfaces are used by clients?
2. From the presented interfaces, there is some interface that is a candidate to be promoted to the public one?

**Comment by ChristianSchwarz** [comment]
Very interesting research! Why the hell do projects rely on non API interfaces :cold_sweat:, thats scary ? Do you have a list of these projects? Are they open source ? It would be interesting to see why and how these projects use the internal API. Maybe there is a lack of features or people tend to workaround bugs or fix them locally.

Thank you for providing your research results here, I think it is very valueable!

|Position	| Interface |	Projects |	Files |
|------------|------------|----------------|--------|
|1 |	org.mockito.internal.util.reflection.Whitebox |	59	| 206|
|2 |	org.mockito.internal.stubbing.answers.ThrowsException |	47	 | 119|
|3	|org.mockito.internal.util.MockUtil	|35|	163|
|4	|org.mockito.internal.verification.VerificationModeFactory	|33	|118|
|5	|org.mockito.internal.verification.Times|	31|	70|
|6	|org.mockito.internal.matchers.GreaterThan|	30|	34
|7	|org.mockito.internal.verification.VerificationModeFactory.times|	19|	36|
|8	|org.mockito.internal.stubbing.answers.CallsRealMethods|	18|	46|
|9	|org.mockito.internal.matchers.Equals|	16	|34|
|10	|org.mockito.internal.stubbing.answers.Returns|	16|	30|

**Comment by alinebrito** [comment]
Hi Christian,  thanks for your feedback!

This is the list of Mockito clients who are using internal interfaces: [Mockito Clients](https://www.dropbox.com/s/qmv1vxg1fwfowpr/). They are GitHub projects. We analyzed 7.393 Mockito  clients (in 2015).

Exemple: `org.mockito.internal.matchers.Matches` is used in project  `wpa\Simulator`, file [TransactionServiceTest.java](https://github.com/wpa/Simulator/blob/7a8234e602bf889ab9f41b5f7e280b1d4779664a/src/test/java/com/wpa/projects/simulator/transactions/TransactionServiceTest.java), line 19.

**Comment by TimvdLippe** [comment]
It seems that quite some internal classes are used instead of relying on the implementation provided by the `Mockito.*` method. E.g. `Times` should be obtained via `Mockito.times()`. I am not sure if we can do something about that.

Regarding `Whitebox`: we had a discussion last week in #422 on what to do with this class. So it seems that quite some projects are relying on this (in my opinion bad practice) class.

**Comment by alinebrito** [comment]
Hi @TimvdLippe 

Thanks for your feedback! It is very useful for my research. This is my main goal, clients projects with this bad practice.

**Comment by raphw** [comment]
I will close this issue as resolved as the matter seems to be discussed.

**Comment by alinebrito** [comment]
Yes, my question was answered. Thanks for the answers!
