### ISSUE TITLE
Fix swinging concurrent tests

### ISSUE THREAD

**Issue by ChristianSchwarz** [mockito/mockito#433]
The following concurrent tests fail currently with a >50% chance. This should be fixed!

Here is a build with multiple failed test that are related to concurrent issues #763 https://travis-ci.org/mockito/mockito/builds/128143294
```
VerificationAfterDelayTest.shouldVerifyNormallyWithSpecificTimes 
VerificationWithTimeoutTest.shouldAllowMixingOnlyWithTimeoutAndFail
VerificationWithTimeoutTest.shouldAllowMixingOtherModesWithTimeout
VerificationWithTimeoutTest.shouldAllowMixingOnlyWithTimeout 
VerificationWithTimeoutTest.shouldAllowMixingOtherModesWithTimeoutAndFail
```

**Comment by raphw** [comment]
Those are time-out-dependant test. Those are generally a bit hard to test but I have never seen them fail. Maybe it depends on how busy Travis is at the moment.

**Comment by TimvdLippe** [comment]
Oh right, the original PR was closed so Travis could not pull the branch :stuck_out_tongue_closed_eyes:

Looking at our build history it seems to be happening very rarely. So if it happens again we should restart the build. If it then fails again a manual inspection should be done.
