### ISSUE TITLE
PluginStackTraceFilteringTest failing locally

### ISSUE THREAD

**Issue by TimvdLippe** [mockito/mockito#435]
https://github.com/mockito/mockito/commit/55ade1ed251e54e11986dd176afedcf81c36d56d introduced changes that causes the `PluginStackTraceFilteringTest` to be failing on my machine.

```
org.mockitousage.plugins.stacktrace.PluginStackTraceFilteringTest > pluginFiltersOutStackTraceElement FAILED
    junit.framework.AssertionFailedError at PluginStackTraceFilteringTest.java:41
```

@raphw I have tried to debug this issue but sadly I have close to zero experience with these classes. Do you maybe have a clue why this tests seems to be failing? The weird thing is that they do not appear to be failing on Travis (https://travis-ci.org/mockito/mockito/builds/137135688)

**Comment by TimvdLippe** [comment]
I just ran the tests in IntelliJ and it is not failing there. So running `./gradlew build` from the command line fails, but in the IDE it does not.

**Comment by PascalSchumacher** [comment]
For me it does not matter if I run the tests from gradle or inside Eclipse. This tests always fails.

**Comment by raphw** [comment]
Fails for me as well, currently looking into it.

**Comment by TimvdLippe** [comment]
While rebasing on #338 it seems that that PR fixes this issue. See https://github.com/mockito/mockito/pull/338/commits/1df7f093ee9cb553bd9a16fdc56061f902a7a963
