### ISSUE TITLE
ArgumentCaptor and ArgumentMatcher can't be mixed in varargs

### ISSUE THREAD

**Issue by ChristianSchwarz** [mockito/mockito#439]
In the given test below the ArgumentCaptor should captor only the char 'c':

```
    @Captor
    private ArgumentCaptor<Character> argumentCaptor;
    
    @Test
    public void capturesVararg() throws Exception {
        mock.varargs(42, 'c');

        verify(mock).varargs(eq(42), argumentCaptor.capture());
       
       assertThat(argumentCaptor.getAllValues()).containsExactly('c');
    }
```

The test fails with this message:

```
Actual and expected should have same size but actual size was:
  <2>
while expected size was:
  <1>
Actual was:
  <[42, 'c']>
Expected was:
  <['c']>
```

Note that we see here 2 bugs:
 - a wrong argument index was captored
 - an `int `was captored by an  `ArgumentCaptor<Character> ` -> #565

**Comment by bric3** [comment]
Yes `ArgumentCaptor` was not designed to be type aware. Though I like API with the least surprises, it should be fixed.

Thanks for reporting.

**Comment by ChristianSchwarz** [comment]
Note to my self: here is the solution [Gist ](https://gist.github.com/ChristianSchwarz/d755aa54e3637b0bd5f76bde3b882605)

**Comment by szczepiq** [comment]
This improvement makes Mockito easier to use and more intuitive. That's exactly the direction we should take Mockito. Thanks!!!
