### ISSUE TITLE
Mock serialization can fail with NullPointerException when using Java 6

### ISSUE THREAD

**Issue by PascalSchumacher** [mockito/mockito#450]
When the test MocksSerializationTest#BUG_ISSUE_399_try_some_mocks_with_current_answers is run with Java 6 it fails with:

>java.lang.NullPointerException
    at java.util.LinkedList.writeObject(LinkedList.java:942)
    ...
    at org.mockitoutil.SimpleSerializationUtil.serializeMock(SimpleSerializationUtil.java:34)

The test works fine when run with Java 7.

To get the build to succeed with Java 6 I had to disable the test for this java version.

**Comment by raphw** [comment]
This seems to be a Java 6 bug. The public version has not seen updates in years.
