### ISSUE TITLE
Either revert recent Functional Interfaces change or change JavaDoc

### ISSUE THREAD

**Issue by ashleyfrieze** [mockito/mockito#453]
I've been reading the Javadoc regarding `ArgumentMatcher` and I noticed a couple of things. Relating back to the changes of #338 

- The example of how to override it is still based around `Object` rather than `T`
- Someone has very deliberately decided not to make it use `T` in the past and now we've changed that.

> The argument is not using the generic type in order to force explicit casting in the implementation. This way it is easier to debug when incompatible arguments are passed to the matchers. You have to trust us on this one. If we used parametrized type then ClassCastException would be thrown in certain scenarios.

My view at the time was that changing it to `T` would remove the class casting and that this would be a good thing. It was kind of necessary to have it as `T` so that the lambda expressions in Java 8 could infer the right types.

The rationale about a class cast exception giving weird results kind of makes sense, but does that really really happen? It seems it's either solve one problem or the other.

What do folks think? I'll happily amend the code either way.

**Comment by ChristianSchwarz** [comment]
I can't imagine a scenario where the parameterized type cause problems and why it aids debuging if no type parameter is used.

@all Do we have examples that illustrate the described problem? If not the JavaDoc should be removed!

**Comment by ashleyfrieze** [comment]
#454 is one way we could wrap this up. Sorry for not noticing it sooner!

**Comment by TimvdLippe** [comment]
If we receive such a report, we should catch such an exception and log an appropriate error why this is happening. For now I can't see this breaking, but I am happy to be proven wrong.
