### ISSUE TITLE
Retrieving Arguments for ArgumentMatchers from other mocks not working inline

### ISSUE THREAD

**Issue by sourcecase** [mockito/mockito#466]
> Hey,
> 
> First thanks for reporting, in order to help us to classify issue can you make sure the following check boxes are checked ?
> 
> If this is about mockito usage, the better way is to reach out to
> 
>  - stackoverflow : http://stackoverflow.com/questions/tagged/mockito
>  - the mailing-list  : https://groups.google.com/forum/#!forum/mockito / mockito@googlegroups.com
>    (Note mailing-list is moderated to avoid spam)
>
> _This block can be removed_
> _Something wrong in the template fix it here `.github/ISSUE_TEMPLATE.md`

check that

 - [ ] The mockito message in the stacktrace have useful information, but it didn't help
 - [ x] The problematic code (if that's possible) is copied here;
       Note that some configuration are impossible to mock via Mockito
```java
import org.junit.Test;
import org.mockito.ArgumentMatcher;
import org.mockito.Mockito;

public class MockitoIssue {

    private static class MockitoIssueStringMatcher implements ArgumentMatcher<String> {

        private String expected;

        public MockitoIssueStringMatcher(String expected) {
            this.expected = expected;

        }

        @Override
        public boolean matches(String object) {

            return object.equals(expected);
        }

        public String toString() {

            return "[MockitoIssueStringMatcher]";
        }

    }

    private static class Fancy {

        public void foo(String s0, String s1) {

            System.out.println(s0 + s1);
        }
    }

    private static class FancyOther {

        public String bar() {

            return "bar";
        }
    }



}
```
Working
```java
    @Test
    public void testSftpService() {

        FancyOther fancyOther = Mockito.mock(FancyOther.class);
        Fancy fancy = Mockito.mock(Fancy.class);
        Mockito.when(fancyOther.bar()).thenReturn("bla");
        fancy.foo("blubb", fancyOther.bar());
        String barString = fancyOther.bar();
        Mockito.verify(fancy).foo(Mockito.any(String.class), Mockito.argThat(new MockitoIssueStringMatcher(barString)));
    }
```

Not working
```java
    @Test
    public void testSftpService() {

        FancyOther fancyOther = Mockito.mock(FancyOther.class);
        Fancy fancy = Mockito.mock(Fancy.class);
        Mockito.when(fancyOther.bar()).thenReturn("bla");
        fancy.foo("blubb", fancyOther.bar());
        //String barString = fancyOther.bar();
        Mockito.verify(fancy).foo(Mockito.any(String.class), Mockito.argThat(new MockitoIssueStringMatcher(fancyOther.bar())));
    }
```
 - [ x] Provide versions (mockito / jdk / os / any other relevant information)
2.0.71-beta
 - [x ] Provide a [Short, Self Contained, Correct (Compilable), Example](http://sscce.org) of the issue
       (same as any question on stackoverflow.com)
see above
 - [ ] Read the [contributing guide](https://github.com/mockito/mockito/blob/master/.github/CONTRIBUTING.md)

This is just a small issue, so thanks for the awesome framework and fix if desired.
Best regards
Chris

**Comment by raphw** [comment]
This is an implicit consequence of how Mockito is implemented. In order to validate your input, Mockito captures called methods in thread local buffers where the invocation order is important. If you mock objects, you should not rely on the return values of mocked objects during validation. You example should rather look like the following:

```java
final String value = "bar";
Mockito.when(fancyOther.bar()).thenReturn(bar);
fancy.foo("blubb", fancyOther.bar());
Mockito.verify(fancy).foo(Mockito.any(String.class), Mockito.argThat(new MockitoIssueStringMatcher(value)));
```

**Comment by sourcecase** [comment]
@raphw Thanks for the hint!
