### ISSUE TITLE
Feature Request ArgumentCaptor.getValueAt(index)

### ISSUE THREAD

**Issue by vanniktech** [mockito/mockito#473]
Instead of `argumentCaptor.getAllValues().get(1)`, `argumentCaptor.getValueAt(1)` would be pretty handy.

If this is something you'd want, I'm more than happy to post a PR.

**Comment by TimvdLippe** [comment]
Yes that seems like a valid proposal. Looking forward to your pull request :smile:

**Comment by ChristianSchwarz** [comment]
@vanniktech 
Whould you mind to name the method `getValue()` ?

**Comment by TimvdLippe** [comment]
@ChristianSchwarz given that [`getValue`](http://site.mockito.org/mockito/docs/current/org/mockito/ArgumentCaptor.html#getValue()) already exists, I would prefer to keep the naming `getValueAt(int)`

**Comment by ChristianSchwarz** [comment]
@TimvdLippe Why not overload it? Or even better rename `getValue() `to `getFirstValue()`  WDYT?

**Comment by vanniktech** [comment]
I'm also fine with `getValue(index)`

Maybe also predefine some methods like

`getFirstValue()`, `getSecondValue()` and `getThirdValue()`. Usually at least I don't use more than 3.

**Comment by ChristianSchwarz** [comment]
> ~~Or even better rename getValue()to getFirstValue()~~

Errr my fault, `getValue()` should be renamed to `getLastValue()` ofcourse, seem like the method doesn't communicate its intend very well.

@vanniktech +1 for adding `getFirstValue()` and so on!

**Comment by bric3** [comment]
I propose something a bit more verbose but more expressive, like :

```
captor.onInvocation(1).getValue();
```

`getValueAt`, `getFirstValue`, don't express much about the importance of invocation count.

**Comment by vanniktech** [comment]
Since there has been lots of discussion about the API and what `ArgumentCaptor` should really do and what not, I ended up extending `ArgumentCaptor` for now via Kotlin.
