### ISSUE TITLE
Clean up wiki

### ISSUE THREAD

**Issue by TimvdLippe** [mockito/mockito#480]
The current wiki contains old articles with sometimes incorrect information. The wiki should be cleaned up or merged with mockito.org.

**Comment by bric3** [comment]
@TimvdLippe I've cleaned up the wiki a bit, do you have other stuff in mind ?

**Comment by bric3** [comment]
related to #487

**Comment by TimvdLippe** [comment]
Yes this looks very nice. I went through all the pages and it looks a lot better now. Awesome job!
