### ISSUE TITLE
Npe when migrating from mockito 1.9.0 to 1.10.19

### ISSUE THREAD

**Issue by martofeld** [mockito/mockito#485]
When trying to migrate from mockito 1.9.0 to 1.10.19 I get the following stacktrace
```
java.lang.RuntimeException: java.lang.NullPointerException
	at com.google.dexmaker.DexMaker.generateAndLoad(DexMaker.java:388)
	at com.google.dexmaker.stock.ProxyBuilder.buildProxyClass(ProxyBuilder.java:252)
	at com.google.dexmaker.mockito.DexmakerMockMaker.createMock(DexmakerMockMaker.java:56)
	at org.mockito.internal.util.MockUtil.createMock(MockUtil.java:33)
	at org.mockito.internal.MockitoCore.mock(MockitoCore.java:59)
	at org.mockito.Mockito.mock(Mockito.java:1285)
	at org.mockito.Mockito.mock(Mockito.java:1163)
```
This happens any time I try to mock something using the `mock(Class)` method

Useful information:
Os: OSx Capitan
IDE: Idea
Other libs:
 - Robolectric 3.0
 - Multidex
 - Junit 4.12

 - [x] The mockito message in the stacktrace have useful information, but it didn't help
 - [x] The problematic code (if that's possible) is copied here;
       Note that some configuration are impossible to mock via Mockito
 - [x] Provide versions (mockito / jdk / os / any other relevant information)
 - [x] Provide a [Short, Self Contained, Correct (Compilable), Example](http://sscce.org) of the issue
       (same as any question on stackoverflow.com)
 - [x] Read the [contributing guide](https://github.com/mockito/mockito/blob/master/.github/CONTRIBUTING.md)

**Comment by TimvdLippe** [comment]
@martofeld could you test out with the different patch version between these two releases? The comparison of v1.9.0 and v1.10.19 consists of 880 commits so it is very hard to track the issue down in this large quantity. Preferably the two consecutive versions where it first worked and after upgrading to the new version it breaks.

**Comment by martofeld** [comment]
@TimvdLippe thanks for the answer. After I submitted the issue i kept on investigating and found out it was an issue with the dexmaker lib. When said lib is removed from project everything keeps working as expected.
