### ISSUE TITLE
Provide upgrade guide for Mockito 2.0

### ISSUE THREAD

**Issue by TimvdLippe** [mockito/mockito#487]
The upgrade guide should depict all breaking changes since 1.10.19 as well as new functionality.

* http://abi-laboratory.pro/java/tracker/compat_report/mockito/1.10.19/2.0.79-beta/2afce/bin_compat_report.html lists all changes to the public API.
* Remove new tag from changes introduced in 1.10, several sections starting at http://site.mockito.org/mockito/docs/current/org/mockito/Mockito.html#29
* The changelog at https://github.com/mockito/mockito/blob/master/doc/release-notes/official.md

The guide should help developers estimate the amount of effort required to update to Mockito 2.0. If we provide enough tools to ease the process, Mockito 2.0 adoption will be faster.

**Comment by bric3** [comment]
Note that some objects should be ignored in that report `http://abi-laboratory.pro/java/tracker/compat_report/mockito/1.10.19/2.0.79-beta/2afce/bin_compat_report.html`

**Comment by TimvdLippe** [comment]
@raphw If you are busy with other tasks, shall we split this ticket and assign others to the subtasks to alleviate your workload?

**Comment by bric3** [comment]
Where are we on this ?

**Comment by bric3** [comment]
I'm closing this issue as it seems to be done, not really a _migration guide_ but a _what's new in mockito 2_.

For reference see wiki page : https://github.com/mockito/mockito/wiki/What%27s-new-in-Mockito-2
