### ISSUE TITLE
Remove Whitebox class

### ISSUE THREAD

**Issue by TimvdLippe** [mockito/mockito#489]
The original question stems from #422 where additional changes were requested. This class seems to stimulate bad testing practices. Mockito only uses this class in [JUnitFailureHacker](https://github.com/mockito/mockito/blob/196ff979da156caa07e19f57e4849637d8bede1a/src/main/java/org/mockito/internal/util/junit/JUnitFailureHacker.java) which consequently is only used in [VerboseMockitoJUnitRunner](https://github.com/mockito/mockito/blob/196ff979da156caa07e19f57e4849637d8bede1a/src/main/java/org/mockito/runners/VerboseMockitoJUnitRunner.java). Given the nature of this class and only 1 usage in the library, I think we should remove it to prevent users from obtaining bad testing habits.

**Comment by marcingrzejszczak** [comment]
Oh yeah - please do :P

**Comment by TimvdLippe** [comment]
Usages on GitHub code derived with Google BigQuery: https://bigquery.cloud.google.com/results/eco-silicon-124112:bquijob_30e42d3_155cf5a5f13?pli=1

```sql
SELECT
  cont.sample_repo_name,
  repo.watch_count
FROM
  [fh-bigquery:github_extracts.contents_java_2016] as cont
JOIN [bigquery-public-data:github_repos.sample_repos] as repo
  ON cont.sample_repo_name = repo.repo_name  
WHERE
  cont.content CONTAINS 'import org.mockito.internal.util.reflection.Whitebox'
GROUP BY cont.sample_repo_name, repo.watch_count
ORDER BY repo.watch_count DESC
LIMIT
  500;
```

Most of the repositories seem to rely on PowerMock instead, which already has a different Whitebox class defined. Therefore I think it is safe to say we can deprecate and remove the class and those users who are explicitly relying on the behavior are likely users of PowerMock too.

**Comment by bric3** [comment]
Yes go on.

**Comment by szczepiq** [comment]
Thanks for removing this class. It's an internal class. People should never depend it. If they did, they need handle the problem ;)
