### ISSUE TITLE
Provide Java 9 compatibility

### ISSUE THREAD

**Issue by szpak** [mockito/mockito#520]
Once having Mockito 2.0 out the door it would be good to explore Java 9 compatibility.

Basic todo list:
- [x] - migration to Gradle 3.0 (2.x doesn't support Java 9)
- [x] - Travis build with Java 9
- [x] - successful Mockito project build with Java 9
- [x] - fix all disabled tests when the new ASM version is available - #863

Open Java 9 related [issues](https://github.com/mockito/mockito/issues?q=is%3Aissue+is%3Aopen+label%3Ajava-9).

**Comment by bric3** [comment]
I agree with that however note that mockito 2.1 should still be Java 5 compatible (we still build Java 5 binaries with Java 6).
Before that we need to branch mockito 2.x to support old JDKs and make mockito 3 Java 8 min.

**Comment by bric3** [comment]
Damn I didn't see this change. I'm on my phone.

However that's fine for me.

**Comment by bric3** [comment]
Maybe something to mention in the migration guide though.

**Comment by bric3** [comment]
Otherwise for  2.1 I think we will only include few API refactoring like `ArgumentCaptor`. And bugfixes otherwise it will delay serious work on mockito 3.
Also I don't want to backport java 8 code to mockito 2.
My idea is to have a `2.x` branch

**Comment by TimvdLippe** [comment]
I think this is ready now?

**Comment by raphw** [comment]
ASM 6 is still in alpha: http://search.maven.org/#search%7Cgav%7C1%7Cg%3A%22org.ow2.asm%22%20AND%20a%3A%22asm%22

**Comment by bric3** [comment]
Really don't focus too much on Java 9 it's still months away.

**Comment by ceki** [comment]
For your information, logback uses Mockito version 1.10.19 which is apparently not Java 9 compatible. It follows that logback build fails under Java 9.

**Comment by raphw** [comment]
Mockito 2 is Java 9 compatible.

**Comment by ceki** [comment]
Great. Thank you.

**Comment by sdfelts** [comment]
Running on version 1.9.5 with Jigsaw b162 with --permit-illegal-access.

I'm seeing the following warning.  
WARNING: Illegal access by org.mockito.cglib.core.ReflectUtils$2 (file:gradle_cache/caches/modules-2/files-2.1/org.mockito/mockito-all/1.9.5/79a8984096fc6591c1e3690e07d41be506356fa5/mockito-all-1.9.5.jar) to method java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int,java.security.ProtectionDomain) 

Is this fixed in 2.x?  Or is there handling if this call fails?

**Comment by TimvdLippe** [comment]
It might be fixed with Mockito 2 yes, as we are not using CGLib anymore. No promises though 😉

**Comment by sdfelts** [comment]
I confirmed that the org.mockito.cglib.core.ReflectUtils is gone in 2.x and mockito no longer depends on net.sf.cglib.core.

**Comment by raphw** [comment]
Byte Buddy 1.7.2 now supports Java 9 class files.

**Comment by szczepiq** [comment]
>Byte Buddy 1.7.2 now supports Java 9 class files.

Should we just bump bytebuddy to the latest version? Cheers!

**Comment by TimvdLippe** [comment]
Closing as at last #863 has been fixed as well. Java 9 woohoo 🎉
