### ISSUE TITLE
Unable to verify spy behavior when spying on proxy

### ISSUE THREAD

**Issue by zkendall** [mockito/mockito#529]
When spying on a proxy instance (discovered with springs `@Transactional`), Mockito's verify(mock) method, will nearly always return successful even when the expectations are absurd.

I wrote this test to demonstrate the unexpected behavior: [Test of Spying on Proxy](https://gist.github.com/zkendall/b42f0a86418b6329163ab06f366264d4)

**Comment by bric3** [comment]
Yes Spring proxies and other classes are difficult to spy, for that reason we have created `AdditionalAnswers.delegatesTo(instance)` (since 1.9.5)

**Comment by bric3** [comment]
So instead of : `spy(proxy)` use `mock(TestSubject.class, delegatesTo(springProxy)).

However if annotations are need to read, then you'll need mockito 2 beta. Because mockito 1.x uses CGLIB which doesn't copies annotations on the mockito subclass. Mockito 2 uses the great bytebuddy.

**Comment by zkendall** [comment]
Thanks for the reply. Glad there is an alternative.

However, it still seems like a bug that the verification() defaults to true for unsupported operations like this. Is that not fixable? If someone does `verify(proxy, times(99999)).doWork();` That should fail!

**Comment by bric3** [comment]
That's the purpose of the message here :

```
org.mockito.exceptions.misusing.UnfinishedVerificationException: 
Missing method call for verify(mock) here:
-> at VerifySpyProxyTest.testSpyOnProxy_1(VerifySpyProxyTest.java:49)

Example of correct verification:
    verify(mock).doSomething()

Also, this error might show up because you verify either of: final/private/equals()/hashCode() methods.
Those methods *cannot* be stubbed/verified.
Mocking methods declared on non-public parent classes is not supported.
```

The thing is that the Spring proxy class **is not final**, but the CGLIB generated classes override methods with the final modifier, so method `doWork` **is final**. Mockito does not fail mock creation if the class is not final, and thus allows to stub non final methods.

**Comment by zkendall** [comment]
My point is--I don't understand the internals of verify(). In this case, why does verify() give a false positive? That's like a cardinal sin for a test framework :)

**Comment by bric3** [comment]
Because the `doWork` method of the spring proxy is not intercepted by Mockito (because it's final), thus `verify` does not know which method to verify. In a later phase Mockito detects that and raises `UnfinishedVerificationException`

The false positive you are mentioning is probably this ?

```java
    @Test(description = "Works when run alone, but fails when run as suite after testSpyOnProxy_1")
    public void testSpyOnProxy_55() {
        proxy.doWork();
        verify(proxy, times(55)).doWork();
        // Console shows doWork() and doAspect() called 1 time and then UnfinishedVerificationException.
    }
```

This is because the TestNG do not rest mocks after usage. And `reset` perform some validation.
As Mockito is better integrated with JUnit it performs some validation after the test when used with a runner or a rule.

You can probably mimic this behaviour with an `@AfterMethod` invoking `Mockito.validateMockitoUsage()`

**Comment by marcingrzejszczak** [comment]
If you use Spring Boot's new testing features then you shouldn't have this
problem anymore. Do you use Spring Boot or just Spring?

**Comment by zkendall** [comment]
marcingrzejszczak,
We are using spring-boot. Haven't upgraded to 1.4 yet though. What about it do you think would address this problem?

**Comment by marcingrzejszczak** [comment]
Maybe I didn't get the problem but in SpringBoot we do take care of issues with proxies. Check out these docs - http://docs.spring.io/spring-boot/docs/current/reference/html/boot-features-testing.html#boot-features-testing-spring-boot-applications-mocking-beans . If you annotate a bean with @MockBean then you will get the proper Mockito bean of that object.

**Comment by zkendall** [comment]
Looks great. Thanks for the tip!

**Comment by praveenk007** [comment]
> So instead of : `spy(proxy)` use `mock(TestSubject.class, delegatesTo(springProxy))`.
> 
> However if annotations are need to read, then you'll need mockito 2 beta. Because mockito 1.x uses CGLIB which doesn't copies annotations on the mockito subclass. Mockito 2 uses the great bytebuddy.

This doesnt seem to work. I am using below powermockito version
```
compile group: 'org.powermock', name: 'powermock-module-junit4', version: '2.0.0'
compile group: 'org.powermock', name: 'powermock-api-mockito2', version: '2.0.0'
```
