### ISSUE TITLE
Provide a method of attaching arbitrary data to a mock

### ISSUE THREAD

**Issue by philwebb** [mockito/mockito#539]
This is an enhancement request first discussed with @TimvdLippe on a [Spring Boot Issue](https://github.com/spring-projects/spring-boot/issues/6520#issuecomment-238654957).

We have a need to attach some additional meta-data to a mock when it's created so that we can act on it at a later point. We currently do this by subverting the `InvocationListener` system (see Spring Boot's [`MockRest`](https://github.com/spring-projects/spring-boot/blob/v1.4.0.RELEASE/spring-boot-test/src/main/java/org/springframework/boot/test/mock/mockito/MockReset.java) class) but a first class API would be most welcome.

Ideally the API to attach meta-data would look something like this:

```java
Foo foo = mock(Foo.class, withSettings().attribute("baz", "bar"));
```

To retrieve the data the `MockCreationSettings` interface could be used. Since Mockito 2 will require Java 8 perhaps a default method could be added to save calling `MockUtil.getMockSettings(...)`? Something like:

```java
Object attribute = MockCreationSettings.get(foo).getAttribute("baz");
// attribute == "bar"
```

**Comment by TimvdLippe** [comment]
One little nit: Mockito 2 is compatible with Java 6 not Java 8. I think this is a good proposal for the new API, let's see what the others think :smile:

**Comment by philwebb** [comment]
Whoops! That line would read as follows then:

```java
Object attribute = MockUtils.getMockSettings(foo).getAttribute("baz");
```

**Comment by raphw** [comment]
I am not sure about this. It feels to me like this should rather be solved by for example a weak map from the mock to the required attribute. Essentially, this is what weak references are for. Would this not be an alternative for you here?

**Comment by philwebb** [comment]
Yes, that's always an option. We can also continue to abuse the `InvocationListener` mechanism. I'm personally not a great fan of using weak map static fields, but that's just a personal preference.

**Comment by raphw** [comment]
The problem that have with this is that very few people will use this functionality while it adds maintenance cost and opens for leaks. I think weak references are the better option to approach this.

**Comment by philwebb** [comment]
The only thing I don't think will work with the weak map is if `withSettings().serializable()` is set _and_ the mock has been serialized/deserialized. I think our current `InvocationListener` hack will work with though so we'll just keep things as they are.

I'll close this one.
