### ISSUE TITLE
improve Mockito.mockingDetails API

### ISSUE THREAD

**Issue by szczepiq** [mockito/mockito#541]
In order to make the API cleaner & expose useful information:

1. MockingDetails.getInvocations() throws meaningful exception when passed object is not a mock and documents this behavior
2. getMockedType() and getExtraInterfaces() are replaced with getMockCreationSettings() that returns MockCreationSettings instance.

**Comment by bric3** [comment]
OK but let's deprecate them instead of removing them (possibly in mockito 3).

**Comment by szczepiq** [comment]
Given that getMockedType() and getExtraInterfaces() are unreleased yet (e.g. 2.0), do you still opt for deprecation?

**Comment by bric3** [comment]
good point, let's remove them then !
