### ISSUE TITLE
new API MockingDetails.getStubbings for advanced users and integrations

### ISSUE THREAD

**Issue by szczepiq** [mockito/mockito#542]
One of the principles of designing Mockito is "opinionated features on top of unopinionated toolkit". This ticket is an example of this promise. Opinionated feature: unused stubs detection - new feature of Mockito 2. Unopinionated toolkit: API to get stubbing information from a mock object - this very ticket.

Building high level features on top of on top of low level public API makes the framework flexible and extensible for unidentified use cases and scenarios.

New MockingDetails.getStubbings() -> Collection<Stubbing> api provides information about the stubbings declared for given mock. We use this internally to implement #384, let's expose it for advanced users / framework integrators.

**Comment by szczepiq** [comment]
Created a preview PR for this feature: #676

**Comment by szczepiq** [comment]
I'm about to finish off this feature and roll out 2.2.0. This way, we avoid showing 2.2.0-beta.

**Comment by TimvdLippe** [comment]
Um I do not think that was the plan, given our milestone 2.2.0. There are other issues we want to fix in 2.2.0. Let's not publish the release until we have fixed these issues. See https://github.com/mockito/mockito/milestone/3 Most of these issues have a PR already open

**Comment by szczepiq** [comment]
Let's adjust the plans. Including multiple changes/features into single compatible version is an anti-pattern.

**Comment by TimvdLippe** [comment]
I have to disagree. We published 2.1 less than a week ago, releasing 2.2.0 now would be way too soon. Moreover, we have discussed the feature set for 2.2.0 targeting to improve the ArgumentCaptor. Releasing a minor version with this 1 new api seems redundant, annoying on the user site and will result in an overload of minor version upgrades. Therefore I would like to stick to our plan and include this extra api in to 2.2.0.

**Comment by szczepiq** [comment]
The reason we need to release 2.2.0 is to remove 2.2.0-beta version from being the latest in central.

I'm with you that it feels too small feature for minor version. However, it solves the problem above and it is consistent with semantic versioning :)

Mockito release process (continuous delivery) does not include multiple features in a single version, with the exception for major version releases. I consider the 2.2.0 milestone as rough plan for what's after 2.1.0 but not a feature set to include in a specific version. Every new feature / change will ship a separate version, like 2.2.1, 2.2.2, etc.

**Comment by bric3** [comment]
> The reason we need to release 2.2.0 is to remove 2.2.0-beta version from being the latest in central.

I don't agree. We don't have to release a new version just not see 2.2.0-beta.1.

I think betas is a very good thing, albeit maybe not on central, or as a snapshot, whatever. And betas are a good thing for that, I still think they could stay on bintray.

> I consider the 2.2.0 milestone as rough plan for what's after 2.1.0 but not a feature set to include in a specific version.

You may consider that, but that is clearly not the intended when I gathered these item togetber as a milestone.

Users may want incremental update on a website but developers don't like it when it's about libraries. Let's not rebrand beta release without the beta tag.

**Comment by szczepiq** [comment]
There is a wiki page that describes current release model of Mockito. I thought that you wrote this wiki yourself :)

C'mon @bric3, accept continuous delivery and move on. Let's innovate, learn and win rather than stick to the old ways!

**Comment by bric3** [comment]
It was written to help what's happening on this front. It doesn't mean I'm fully sold to it. I do like the continuous delivery of betas or maintenance rereleased really do! But I'm not comfortable to release just every change happening on `release/2.x` or `master`.

Also the 2.2 is a continuation of what couldn't be done in 2.1, there's some interesting feedback from the community to wait for, there's some refactoring on captors that also may need some feedback, etc. 

> Let's innovate, learn and win rather than stick to the old ways!

This is not mutually exclusive. Also the old ways aren't always bad. But in this case there's middle ground to find. 

On stackoverflow some were confused about incremental releases, same for answering this is an additional step to get the specific version that brought this change.
