### ISSUE TITLE
Unexpected new public API: VerificationWrapper, VerificationWrapperInOrder, VerificationCollectorImpl

### ISSUE THREAD

**Issue by szczepiq** [mockito/mockito#551]
It looks like some classes leaked to the public API: VerificationWrapper, VerificationWrapperInOrder, VerificationCollectorImpl

They seem like internal classes because:
a) they are concrete implementation where public API should be an interface
b) no javadoc
c) looking at their API, they don't seem like something we want to expose to the users :)

We need to fix it before 2.0, perhaps it's just the matter of moving it to internal packages.

**Comment by TimvdLippe** [comment]
`VerificationCollectorImpl` is package-protected and is not generated in the Javadoc either: http://site.mockito.org/mockito/docs/current/org/mockito/junit/package-summary.html

The other `VerificationWrapper`s can be package-protected too.

**Comment by szczepiq** [comment]
This is a good point!

I suggest we move it to internal package anyway. This way:
- it is consistent how we manage public / private API
- it can be used more easily by devs who experiment / hack (e.g. they know what they are doing when using private API :)
- it is less error prone (e.g. when someone forgets to remove 'public' or when someone adds 'public' not realizing consequences)
