### ISSUE TITLE
Fix again javadoc stylesheet

### ISSUE THREAD

**Issue by bric3** [mockito/mockito#552]
Previously we had a nice javadoc stylesheet. That worked well with JDK6.
Then we used travis that was only allowing OracleJDK7, that came with a better javadoc stylesheet so we dropped ours.

Now since the release of mockito 2.x is using openjdk6, we should reintroduce a better stylesheet.

Current state ❌ 
http://site.mockito.org/mockito/docs/2.0.100-beta/org/mockito/Mockito.html
<img width="712" alt="screen shot 2016-08-13 at 19 41 59" src="https://cloud.githubusercontent.com/assets/803621/17644719/cecc5ec4-618e-11e6-912e-9b0dcd7e94db.png">

Previous ✅ 
http://site.mockito.org/mockito/docs/2.0.0-beta/org/mockito/Mockito.html
<img width="877" alt="screen shot 2016-08-13 at 19 45 32" src="https://cloud.githubusercontent.com/assets/803621/17644722/d71bcd08-618e-11e6-831a-a01c47e8cc61.png">

**Comment by TimvdLippe** [comment]
Is this as simple as turning back on this line? https://github.com/mockito/mockito/blob/b0393eafeeb81b6c75e40a82b81672543777ca9a/gradle/javadoc.gradle#L55

**Comment by bric3** [comment]
Probably but I need to check before. The file may have been removed. And the javadoc tool is _picky_ especially in old version of the JDK.

**Comment by bric3** [comment]
Actually we should revert this commit 3a057b3eff2be528a1fed41852a990cff87a72c1, when JDK7 was the only option on travis

**Comment by bric3** [comment]
It seems the javadoc tool of openjdk6 generates a different HTML than Sun JDK 6. Thus the stylesheet is not working properly.

<img width="748" alt="screen shot 2016-08-24 at 11 56 56" src="https://cloud.githubusercontent.com/assets/803621/17926642/35b9d2cc-69f2-11e6-9614-61648cafeb18.png">

Yet again an issue with OpenJDK6...
