### ISSUE TITLE
Checks.checkNotNull should emit IllegalArgumentException instead of NPE

### ISSUE THREAD

**Issue by szczepiq** [mockito/mockito#554]
Checks.checkNotNull emits NPE. I think it is better to emit IAE, because:
 - IAE is more specific whereas NPE is more generic. Specific exception is easier to test.
 - Specific exception gives better experience for users, NPE is often assumed to be developer error.

This change is not backwards compatible.

@bric3, thoughts?

**Comment by marcingrzejszczak** [comment]
Definitely! Personally I hate throwing NPEs. NPE can be thrown because you've forgotten to inject sth and your test (if you test for an NPE exception to be thrown) will pass.

**Comment by bric3** [comment]
Agreed
