### ISSUE TITLE
Update Gradle to 3.0

### ISSUE THREAD

**Issue by TimvdLippe** [mockito/mockito#561]
Gradle 3.0 is released so we can look into upgrading. Potentially we can rewrite our scripts into Kotlin.

**Comment by bric3** [comment]
After we branch out `release/2.x` ;)

**Comment by szpak** [comment]
Kotlin? We need to discuss it before :)

**Comment by TimvdLippe** [comment]
Yes we can discuss it in this issue. I have not looked into Kotlin at all so have no opinion atm. You do?

**Comment by szpak** [comment]
There are some limitations in Kotlin scripts. It is highlighted also in the [release notes](https://docs.gradle.org/3.0/release-notes):
> we are working intensely to make Gradle Script Kotlin fully production ready by the end of the year

In addition we have quite extensive build logic written in Groovy and I don't know it is worth to rewrite it just to have nicer code completion in Idea for those not very often times where there is something to change.

**Comment by TimvdLippe** [comment]
Seem decent arguments to not switch to Kotlin yet :+1:

**Comment by bric3** [comment]
However gradle 3.0 still allows groovy, so that's not a blocker to switch

**Comment by szpak** [comment]
And should "always" will:
> Groovy is still the primary build language for Gradle scripts and will **always** be supported

**Comment by szczepiq** [comment]
+1 to keeping groovy build scripts :)

**Comment by szczepiq** [comment]
We cannot do it right now because Gradle 3.0 does not build with java6 and current release is still for java6 :( Let's close and revisit later. We won't forget to bump Gradle :)

**Comment by TimvdLippe** [comment]
We will switch from Java 6 soon and this issue has not been resolved yet. Therefore reopening to be tracked in waffle.
