### ISSUE TITLE
Verification of an empty varargs call fails when isNotNull() is used

### ISSUE THREAD

**Issue by ChristianSchwarz** [mockito/mockito#567]
The follwing tests fail unexpected with : "Argument(s) are different"

```
@Test
public void shouldMatchVarArgs_isNotNull()   {
    mock.varargs();
    verify(mock).varargs(isNotNull());
}

@Test
public void shouldMatchVarArgs_isNotNullArray()   {
    mock.varargs();

    verify(mock).varargs((String[])isNotNull());
}
```

Expected is that the tests pass cause an empty vararg array is not null!

**Comment by bric3** [comment]
Thanks for the report

**Comment by big-andy-coates** [comment]
With https://github.com/mockito/mockito/pull/2807 merged, the second test above can be achieved, not through casts, but through using the variant of `isNotNull` that takes a type:

```java
@Test
public void shouldMatchVarArgs_isNotNullArray()   {
    mock.varargs();

    verify(mock).varargs((String[])isNotNull(String[].class));
}
```

However, the first test is invalid:

```java
@Test
public void shouldMatchVarArgs_isNotNull()   {
    mock.varargs();
    verify(mock).varargs(isNotNull());
}
```

This previously would have matched a `varargs()` call with 1 or more parameters, and now matches a call with exactly 1 parameter. Hence the `verify` call would fail in both cases as the method is called with no parameters.
