### ISSUE TITLE
Deprecate Mockito.debug().printInvocations() API

### ISSUE THREAD

**Issue by szczepiq** [mockito/mockito#577]
I'm trying to get closure on awkward Mockito.debug().printInvocations() API. The API is semi-internal, package-protected and deprecated :) This API is simply unfinished (just like the verbose JUnit runner was unfinished until recently).

Options for Mockito.debug().printInvocations()

1. delete this API without replacement, wait for users feedback if they need it.
2. move to MockingDetails.printInvocations() and make public (already planned in #543)
3. move to Mockito.framework().printInvocations() and make public
4. option 2) + some composite mocking details API so that we can print invocations across multiple mocks
5. ?

My thinking:

1) Tempting, we already have 'verbose mode'. Still, it feels the feature is useful and is mentioned on SO (http://stackoverflow.com/questions/11802088/how-do-i-enable-mockito-debug-messages). I don't think users will request this feature even if it is useful because they can use existing API and hack up a solution.
2) I like it. However, it is not as powerful because usually we want to investigate the behavior / stubbing of multiple mocks. MockingDetails only covers a single mock. Original printInvocations() method neatly shows interactions/stubbings in order across multiple mock objects.
3) Mockito.framework() already exists so we could use it. However, it feels that printing invocations is not really for framework integrators so I don't think it is a good place for this API.
4) Option (2) with the multi-mock feature. I kinda like it. Example how it could work:

Mockito.mockingDetails(mock).isMock();
Mockito.mockingDetails(mock).getInvocations();
Mockito.mockingDetails(mock).printInvocations();

~~Mockito.mockingDetails(mock, mock2, mock3).isMock();~~
Mockito.mockingDetails(mock, mock2, mock3).getInvocations();
Mockito.mockingDetails(mock, mock2, mock3).printInvocations();

Signatures:

public MockingDetails mockingDetails(Object mock); //existing
public CompositeMockingDetails mockingDetails(Object ... mocks); //new
MockingDetails extends CompositeMockingDetails //API consistency

CompositeMockingDetails //new interface
CompositeMockingDetails.getInvocations()
CompositeMockingDetails.printInvocations()
CompositeMockingDetails.getStubbings() //see #542
  
Your thoughts?

**Comment by bric3** [comment]
`debug` has been deprecated for a long time, let's document the deprecation a bit more in `debug`, then in 3.0 remove the deprecated API.

**Comment by bric3** [comment]
Otherwise it seems reasonable, and a nice idea.

**Comment by szczepiq** [comment]
After 2.0 is out, I'll start working on this. Perhaps we can have a nice 2.1 release with some interesting features :D. Tentative plan is: 2.1 has new public API and debug becomes cleanly deprecated until 3.0. Feedback is welcome!

**Comment by szczepiq** [comment]
Closing this ticket as it will be fixed by #543
