### ISSUE TITLE
ArgumentCaptor can't capture varargs-arrays

### ISSUE THREAD

**Issue by ChristianSchwarz** [mockito/mockito#584]
Relates to: #439, #565, #567, #583 

ArgumentCaptor can't capture varargs-arrays.

```
@Test
public void shouldCaptureVarArgsAsArray() throws Exception {
    ArgumentCaptor<String[]> varargCaptor = ArgumentCaptor.forClass(String[].class);

    mock.varargs("1","2");   

    verify(mock).varargs(varargCaptor.capture());

    assertThat(varargCaptor).containsExactly(new String[]{"1","2"});
}
```

**Expected:** A `ArgumentCaptor<String[]>` should be able to capture the varargs-array as a whole.
**Actual:** The ArgumentCaptor captures no arrays but every single argument passed to the varargs method. The following exception is thrown:

```
java.lang.AssertionError: 
Actual and expected should have same size but actual size was:
  <2>
while expected size was:
  <1>
Actual was:
  <["1", "2"]>
Expected was:
  <[["1", "2"]]>
```

**Comment by bric3** [comment]
For reference this issue is not new ; see #74, #201, #211

**Comment by paulduffin** [comment]
Can you not just use varargCaptor.getAllValues() to access the list of arguments passed as varargs and then compare that?

**Comment by ChristianSchwarz** [comment]
@paulduffin 

> Can you not just use varargCaptor.getAllValues() to access the list of arguments passed as varargs and then compare that?

This is not always possible cause `getAllValues()` returns all ever captured values.

```java
when(mock).addVararg(captor.capture());
mock.addVararg(1,2);
mock.addVararg(3,4);
mock.addVararg(5,6);

captor.getAllValues() // {1,2,3,4,5,6}
```

vs.

```java
when(mock).addVararg(captor.capture());
mock.addVararg(1,2,3);
mock.addVararg(4,5,6);

captor.getAllValues() // {1,2,3,4,5,6}
```

**Comment by big-andy-coates** [comment]
With https://github.com/mockito/mockito/pull/2807 merged, `argumentCaptor(String.class)` will capture a single value passed to a varargs parameter, where as `argumentCaptor(String[].class)` will capture any number of values.
