### ISSUE TITLE
ArgumentCaptor A single `capture()` call captures all vararg elements.

### ISSUE THREAD

**Issue by ChristianSchwarz** [mockito/mockito#585]
A single `ArgumentCaptor.capture()` call captures all vararg elements.

```
mock.varargs("1","2","3");

// captures "1","2","3"
verify(mock).varargs(c.capture()); 

// fails with arguments are different
verify(mock).varargs(c.capture(),
                               c.capture()); 


// captures "1","2","3"
verify(mock).varargs(c.capture(),
                               c.capture(),
                               c.capture()); 

```

**Expected:** One capture() call should only capture one vararg argument
**Actual:** A single `ArgumentCaptor.capture()` call captures all vararg elements.

**Comment by szczepiq** [comment]
The current actual behavior is more intuitive IMHO.

**Comment by bric3** [comment]
I agree with @szczepiq, the behaviour makes sense today, that's what I would expect from `capture`

However I think `ArgumentCaptor` could benefit from a more explicit API, for hardened tests on vararg. I think it should happen in 2.1.

I'm not sure we will change the behavior or introduce a new API, we will see.

**Comment by ChristianSchwarz** [comment]
The problem of "a single captor captures all varags" is that you can not ensure that only one argument is passed. Here an example:

```
mock.vararg("1","2"); 
verify(mock).vararg(captor.capture()); 
//^ should fail cause we want to verify that only one 
//  argument was passed and we want capture it
```

**Comment by szczepiq** [comment]
I don't get the example. I can add assertions on captured values, can I not?

**Comment by ChristianSchwarz** [comment]
> I can add assertions on captured values

Sure, but you can't use the capturing matcher to verify the number of arguments passed to the varargs method like e.g. `isNotNull()` does.

In the following scenario you can't ensure that the method was always called with exactly 2 arguments:
``` java
mock.vararg("1","2","3"); 
mock.vararg("4","5"); 
mock.vararg("6"); 
verify(mock, times(3)).vararg(captor.capture()); 
```

Maybe this works, haven't tested:
``` java
mock.vararg("1","2","3"); 
mock.vararg("4","5"); 
mock.vararg("6"); 
verify(mock, times(3)).vararg(or(anyString(),captor.capture()),
                              or(anyString(),captor.capture()))); 
```

**Comment by szczepiq** [comment]
Hmmm, I take your point that this case is not possible to test ATM. Is it a real use case from one of your tests? It seems like an ultra corner case.

**Comment by big-andy-coates** [comment]
With #2835 this now works:

```java
ArgumentCaptor<String[]> captor = ArgumentCaptor.forClass(String[].class);
mock.vararg("1","2","3"); 
mock.vararg("4","5"); 
mock.vararg("6"); 
verify(mock, times(3)).vararg(captor.capture()); 

// captor.getAllValues() will return List.of(new String[]{"1","2","3"}, new String[]{"4","5"}, new String[]{"6"})
```
