### ISSUE TITLE
Mockito Javadoc has a TODO about hamcrest

### ISSUE THREAD

**Issue by bric3** [mockito/mockito#593]
```java
 * TODO rework the documentation, write about hamcrest.
 *
 */
@SuppressWarnings("unchecked")
public class Mockito extends ArgumentMatchers {
```

https://github.com/bric3/mockito/blob/18133aa0cb5b51c0472fb8b33ab0a22aa9f0fbf3/src/main/java/org/mockito/Mockito.java#L1207-L1207

Let's remove it or fix it.

**Comment by szczepiq** [comment]
On it. Thanks!
