### ISSUE TITLE
Make the build script aware of the release branch

### ISSUE THREAD

**Issue by bric3** [mockito/mockito#594]
Releasing from the `master` branch has advantages developer wise, however when users that are hit by a bug and that `master` has significantly changed we cannot propose a stable enough release (example 2.0 betas releases, even the 1.10.x series had some instabilities API wise).

In order to enable the team and contributors in general to fix issues while still allowing bigger work on the next version I propose the following change in branch and release _process_.

1. Branch out to `release/2.x`
   1. Release `2.0.0`
   2. Patch issue
   3. Release `2.0.1`
   4. Additional work on 2.1
   5. Release `2.1.0`
   6. ...
   7. Forget about `2.1.x`
   8. Critical fixes only get released
2. Upgrade `master` to `3.0.0-beta-<build number>`
  1. Start mockito `3.0.0` progress there (like java 8 only, drop APIs)

Also with recent change in the build script we could now release and check the release version with the branch.

See 
* https://github.com/mockito/mockito/commit/b6a402f16e9222605638efe9b57eccc80a197f9e#diff-33cf41d9669aaef72ca19c641dc57d47R68
* https://github.com/mockito/mockito/issues/586#issuecomment-242076979
* https://github.com/mockito/mockito/pull/483#issuecomment-231323266

**Comment by szczepiq** [comment]
@bric3, this is great. Thank you for finally describing the workflow!!!

**Comment by bric3** [comment]
I'll try to work on this this week

**Comment by szczepiq** [comment]
The plan makes perfect sense. Let's zoom into implementation details. For example:

1. Create 2 active branches: "master" and "release"
2. Set version.properties in "master" to 3.0.0-beta.1, automatically publish per push
3. Set version.properties in "release" to 2.1.0-rc.1, automatically publish per push (?)
  a. At some point change version.properties in "release" to "2.1.0", automatically publish per push

I know that travis can now get version from commit message. How would this work for keeping 2 active branches / publishing RCs?

**Comment by TimvdLippe** [comment]
If you want to publish a RC for the v2 branch, you checkout that branch, then commit with `Prepare release candidate [ci-release v2.1.0-RC.1]` on that branch and it should be good to go.

**Comment by bric3** [comment]
I'd rather go for a branch out model like described in https://github.com/mockito/mockito/issues/594#issue-172969427, so we (and interested parties) can still release a important patch for an old mockito version.

**Comment by bric3** [comment]
@szczepiq I'm waiting on the release note of #582 to branch out to `release/2.x`

**Comment by TimvdLippe** [comment]
That should be working fine right? With the versionproperties separate in each branch (and the manual releases).

**Comment by bric3** [comment]
Yes, but not with a single `release` branch.

> 1. Create 2 active branches: "master" and "release"

**Comment by TimvdLippe** [comment]
Oh sorry, I misread that. Yes we must have a release branch for every major semver version. Reading is hard sometimes :stuck_out_tongue_winking_eye: So +1 for me for @bric3 model, which I also was trying to describe.

**Comment by szczepiq** [comment]
When do we use magic incantation in the commit message and when not?

There is an approach with fully automated releases:

1. Create "v2" branch (or something like that), that still publishes Beta.
2. Test it out, so that Beta is neatly released from "v2".
3. Change version in "v2" into RC, remove top of the release notes, push.
4. Iterate on the fixes, every push creates new RC.
5. At some point, change version to "2.1.0", push.
6. Any push to "v2" publishes new 2.1.*

For 2 active dev branches (e.g. mockito3 beta in master and v2) we need to split release notes (e.g. notes/v2.md and notes/v3.md). It's not blocking v2 release, we can do it later.

Awesome, I'm getting excited, we'll have RC before JavaOne! :)

**Comment by TimvdLippe** [comment]
> Any push to "v2" publishes new 2.1.*

I would instead have the drone only push betas. E.g. 2.1.1-beta.*.

**Comment by szczepiq** [comment]
No more betas please :) Continuous delivery is signature feature of Mockito project.

**Comment by TimvdLippe** [comment]
While that is true, for every pull request we would release a new patch version. I am not a fan of that. Preferably update less, but more meaningful for the end-user. If you are continuously producing new non-beta artifacts, I think end-users tend to wait with upgrading instead. It's sad that gradle/maven can't import from master instead, but I think we should try to keep our semver versions clean.

**Comment by bric3** [comment]
This is an old debate, that we had on the mailing list a couple of years ago.

@szczepiq I know you are an advocate of each commit can be a release, I heard about your talk. This is really nice pushing forward for continuous delivery however I don't agree that every single commit should be released especially on libraries.

For example 1.10.x series was nice but felt less stable to many users. Some merged PR introduced the Mockito rule and the API had to be changed. Some incorrect behavior had to be fixed, some were fixed later in the beta. I'm not sure this builds trust in the library.

Also with this big changes cannot fit in your model : should we have released in between PR of the JUnit feature, after all there was enough interesting and working features already. 
For mockito 3 we will target java 8, there's a lot of clean up, maybe some rewriting, doing so we may break things, that happens even with tests, this phase should not be seen as something else than a beta.

**Comment by bric3** [comment]
> For 2 active dev branches (e.g. mockito3 beta in master and v2) we need to split release notes (e.g. notes/v2.md and notes/v3.md). It's not blocking v2 release, we can do it later. 

Exactly. Note that 2.x branch should see most activities, but the scope is limited. And after 2.1 we could declare 2.x in_maintainance_ mode.

**Comment by szczepiq** [comment]
I'm happy to rekindle the discussion. If you convince me, I win win because I learn more :)

>Also with this big changes cannot fit in your model

Why cannot the big feature be developed in a branch?

>For example 1.10.x series was nice but felt less stable to many users.

"felt less stable" - do you have concrete data?

Some thoughts:

- users don't have to upgrade to every version
- we could do minor version bump every month or so, combine the release notes and do bigger announcement

>Some merged PR introduced the Mockito rule and the API had to be changed
>Some incorrect behavior had to be fixed, some were fixed later in the beta.

I'm not convinced that this is a problem of CD. This could happen in the traditional release model, too.

I'm a fan of CD because:
 - it forces to care about quality, documentation, compatibility of every PR
 - it gives features to users faster
 - it provides features incrementally, the smaller the change, the lower chance of regression
 - it helps with project maintenance - users test and pick up new versions faster

Let's say that we don't do CD. How would the release look like? You would release once in a while using magic String in commit message?

**Comment by bric3** [comment]
@szczepiq I don't say abandon CD, I like the CD, for the reason you mentioned. But let's not make a  release per se, like today maybe label them as `beta` or `build` this builds shows progress and still allows interested users to try mockito current work.

>> Also with this big changes cannot fit in your model

> Why cannot the big feature be developed in a branch?

Yes they can, but sometime those are incomplete or buggy. Like having thread safety, or whatever else.

**Comment by bric3** [comment]
>> For example 1.10.x series was nice but felt less stable to many users.

> "felt less stable" - do you have concrete data?

Actually this _data_ comes the issue and PR we had at that time, questions asked on SO and from my own colleagues experience. However I don't have those answers in mind as it's been a long time ago.

**Comment by bric3** [comment]
> * users don't have to upgrade to every version

Indeed.

> * we could do minor version bump every month or so, combine the release notes and do bigger announcement

Yeah that works, but with previous point I think this could just be intermediary _preview_ / _milestone_ releases along with other regular beta builds.

**Comment by szczepiq** [comment]
>Yes they can, but sometime those are incomplete or buggy. Like having thread safety, or whatever else.
And even so when these features land it is just possible to go back on some features, APIs, behaviour that was developed in a previous release.

Let's not push buggy or incomplete features :) The stability problem should be solved by high quality PRs, well designed, documented, and tested.

We can push "build" versions, etc. from branch if we see that it's a good idea.

>Actually this data comes the issue and PR we had at that time, questions asked on SO and from my own colleagues experience. However I don't have those question/gh issues in mind as it's been a long time ago.

It seems there aren't concrete datapoints at this time. I'd rather not change the CD strategy, wait for concrete data, re-evaluate as needed.

**Comment by bric3** [comment]
In the end I couldn't work on it this week, I'll try next week.
