### ISSUE TITLE
Review and update documentation for 2.1.0

### ISSUE THREAD

**Issue by szczepiq** [mockito/mockito#596]
- [x] update the migration guide (should be easy, there are not many breaking changes, if we miss out we can update in following RC)
- [x] add information about bytebuddy in the migration guide
- [x] mention noteworthy 2.0.0 features (should be easy, there are not many, plus they are already documented :)
- [x] fix odd TODO #593
- [x] review/update @since tags so that they say 2.1.0

Final steps I plan doing (by the EOD Wednesday, tomorrow), in order:

- [x] Test release from release/test (in progress, see Travis CI)
- [x] Merge/cherry-pick changes from "release/test" to master
- [x] Move announcement / motivation text (https://github.com/mockito/mockito/blob/rc-release-notes-demo/doc/release-notes/official.md) to top of "What's new in Mockito 2"
- [x] Final pass over "What's new in Mockito 2", make the information exciting and compelling, emphasize use cases, add missing links
- [x] Update the 2.1.0 information in main Mockito class to link to "What's new in Mockito 2". See "TODO 596" in code
- [x] Review Continuous Delivery [wiki page](https://github.com/mockito/mockito/wiki/Mockito-Continuous-Delivery)
- [x] Update the announcement text (https://github.com/mockito/mockito/blob/rc-release-notes-demo/doc/release-notes/official.md) so that instead of tons of text it just links to "What's new in Mockito 2"
- [x] Review release checklist (mostly done) - #620
- [x] Optional - Add some info in the 'What's new in Mockito 2' about the next steps for engs (e.g. ask to use the new version and give feedback).

**Comment by TimvdLippe** [comment]
There were separate issues for these points. For example the last point was already fixed by @brice3 in a recent PR

**Comment by szczepiq** [comment]
This list nicely summarizes the incompatible changes: https://github.com/mockito/mockito/issues?utf8=✓&q=label%3A%221.*%20incompatible%22%20

**Comment by TimvdLippe** [comment]
@bric3 has started the migration guide: https://github.com/mockito/mockito/wiki/What's-new-in-mockito-2.0---2.1

**Comment by TimvdLippe** [comment]
Migration guide has been updated and I did a small spell check. That LGTM.

**Comment by bric3** [comment]
Thanks @TimvdLippe
@raphw @szpak @marcingrzejszczak @szczepiq if you want to add other stuff to this migration guide ?

**Comment by raphw** [comment]
Sorry, I won't find time for anything before JavaZone next week is over. Afterwards, I will have a look!

**Comment by szczepiq** [comment]
Given long weekend coming, I can commit to finalize my review / amendments by the end of Wed next week (9/7). Apologies it is not as fast as the crew would like!

Keep in mind that you don't need me to pull the trigger!!!

Guys, we're so close now! It's exciting :)))))

**Comment by bric3** [comment]
@raphw No problem. Enjoy JavaZone. Also do some advertisement on mockito 2 ;)

**Comment by marcingrzejszczak** [comment]
I've checked out the migration guide and I found it really good. I was missing an example of a default method but I think @TimvdLippe added that.

I haven't done much (to say the least) with regards to this release so I don't have much to write from myself. Like I told @szczepiq and @bric3 I'm overwhelmed with other projects but I'll try to be more active in the upcoming months (don't promise anything though :/ ).

Definitely I can take over testing questions and support if there are some! :)

**Comment by TimvdLippe** [comment]
I just remembered this, have to add tomorrow: lazy verification.

**Comment by TimvdLippe** [comment]
Lazy verification mention added: https://github.com/mockito/mockito/wiki/What's-new-in-Mockito-2/_compare/e0b49e128f97d703e616c01f0a4893da5295098e...10ba7530dff7a72ef869a16872aca8514c7c8c0a

**Comment by bric3** [comment]
Cool. This morning I tidied up a bit the wiki, mostly these two : added side page, improved a lot the home page.

**Comment by TimvdLippe** [comment]
Really like these changes, looks a lot nicer!

Op wo 31 aug. 2016 om 14:30 schreef Brice Dutheil <notifications@github.com

**Comment by szczepiq** [comment]
Guys, the "What's new in Mockito 2" is fantastic!!! Thanks a lot!

**Comment by szczepiq** [comment]
I like the "What's new in Mockito 2". I'm reviewing Mockito main javadoc. I might have some edits to the "What's new" wiki, will see :)

**Comment by bric3** [comment]
Yep sure ;)

**Comment by bric3** [comment]
@szczepiq I think we can close this issue since you reviewed Mockito class :P

**Comment by szczepiq** [comment]
I have some edits, hold on :) I'll finish by tomorrow!

**Comment by bric3** [comment]
Ok we ll monitor the check boxes ;)

**Comment by bric3** [comment]
@szczepiq Be sure to check out this wiki page as well. https://github.com/mockito/mockito/wiki/Mockito-Continuous-Delivery

And fix or correct issues, I think this could be a starting point if you want to extract the _CDD_

**Comment by TimvdLippe** [comment]
> Move announcement / motivation text (https://github.com/mockito/mockito/blob/rc-release-notes-demo/doc/release-notes/official.md) to top of "What's new in Mockito 2"

I would rather not do this since it clutters the content. That wikipage should be only about "What's new in Mockito 2", not what is upcoming in Mockito 3.

> Final pass over "What's new in Mockito 2", make the information exciting and compelling, emphasize use cases, add missing links

Not sure what you mean with "exciting and compelling" but I would rather not change the current text of the features. Let's keep it formal and clear.

**Comment by mkordas** [comment]
@TimvdLippe migration guide does not mention two BDD enhancements I've developed: #212 and #311. I think it's worth sharing it with the world :)

**Comment by TimvdLippe** [comment]
@mkordas Yes definitely, I have added them!

**Comment by mkordas** [comment]
@TimvdLippe thank you!

**Comment by szczepiq** [comment]
>I would rather not do this since it clutters the content. That wikipage should be only about "What's new in Mockito 2", not what is upcoming in Mockito 3.

Good feedback. I'll think how to do it best.

>Not sure what you mean with "exciting and compelling" but I would rather not change the current text of the features. Let's keep it formal and clear.

By compelling I mean ensuring that every feature describes the 'why' well enough (e.g., "why should I care about the feature"). Perhaps this requirement is already met. If that's the case, I don't need to make changes :)

**Comment by szczepiq** [comment]
Ah I didn't finish all I wanted :(. I'm pretty happy though. If someone else want's to pick up the work, go for it and pull the trigger :) Otherwise I can pick up the work tomorrow.

@TimvdLippe, I considered your feedback about the 'what's new' page. Eventually, I went ahead and added introduction section. I hope it's ok ;) I added table of contents for people to quickly jump to improvements or incompatibilities. I didn't change much of the original text after all. It's well written. @bric3 , @TimvdLippe GREAT WORK!!!! You contributed not only great code but also great docs. Too many times I see that docs are not emphasized enough in software projects. Docs are part of the product and must be as high quality as code. Thanks for honoring this principle in Mockito.

Damn, I'm proud of this release and you guys!!!!!!!!!! :)))))))))))))))))))))))))))))))))

**Comment by TimvdLippe** [comment]
The introduction looks good! Glad the wording of the changes remained
fairly the same :)

**Comment by szczepiq** [comment]
Made more progress. I didn't finish on time. My new ETA is weekend :) However, you don't need me to do the release :)

**Comment by bric3** [comment]
I'l just wait for #628 to be merged then I'll make this branch `release/2.x`

**Comment by szczepiq** [comment]
Woah, I'm done!

T_H_A_N_K_S for patience and for pushing me & all of us to make progress on the release.
