### ISSUE TITLE
Finalize announcement text and ensure it's on release checklist

### ISSUE THREAD

**Issue by szczepiq** [mockito/mockito#607]
Feedback needed for: https://github.com/mockito/mockito/blob/rc-release-notes-demo/doc/release-notes/official.md

Cheers!!!

**Comment by ChristianSchwarz** [comment]
* "Continuous Delivery Drone" is listed as contributor

**Comment by szczepiq** [comment]
>"Continuous Delivery Drone" is listed as contributor

I don't mind that. It looks cool and promotes our CD pipeline cheaply :)

> Idea: some examples that illustrate the new features would be nice, maybe with a comparision mockito 1 vs 2

I like this idea. I would hope that good examples are provided in Javadoc where features are documented :) I would rather link to the doc with examples from the release notes (e.g. rather than including examples in the release notes document). This way the release notes doc remains 1-minute read that does not require too much brain power to process.

**Comment by bric3** [comment]
@szczepiq I did some archeology and tagged a lot more PR / issues with the milestone 2.1.

**Comment by szczepiq** [comment]
@bric3, thanks a lot. This is very useful!

**Comment by bric3** [comment]
Are you OK to switch the branch today ?

**Comment by szczepiq** [comment]
I'd rather wait until tomorrow. I'd like consolidate release notes. Main mockito class still have half-finished breaking changes list.

I'm thinking of adding the announcement text to the top of the "what's new in Mockito". Then, have the "official.md" link to the wiki page.

**Comment by szczepiq** [comment]
Closing, this one, added the remaining steps I plan on doing for documentation in: #596

BTW. Travis is trying to release from "release/test" branch as I write this update ;) Keep thumbs up!!!

**Comment by bric3** [comment]
Ok
