### ISSUE TITLE
Extract continuous delivery automation to standalone library

### ISSUE THREAD

**Issue by TimvdLippe** [mockito/mockito#608]
Originally proposed by @szczepiq in https://github.com/mockito/mockito/commit/db9b49f0ac6edeff12b33b47e290e10c2f99a68b#diff-b92bb31979d48c9946d7a14ada3baa2eR16

We could expose our buildSrc for other libraries, by turning it into a library itself. This does require:
- Clear documentation
- Clear code
- Expose configuration by XML or JSON files
- Agnostic of environment (e.g. untangle from Travis)

**Comment by szczepiq** [comment]
Fantastic!!!

**Comment by TimvdLippe** [comment]
Fixed in #751
