### ISSUE TITLE
Silent JUnit runner and quiet JUnit rule are better expose in the docs

### ISSUE THREAD

**Issue by szczepiq** [mockito/mockito#609]
See great feedback from a user in #384

**Comment by bric3** [comment]
https://github.com/mockito/mockito/issues/384#issuecomment-243044175

**Comment by bric3** [comment]
@szczepiq This is not the javadoc but I've mentioned a bit the runner in the what's new / migration guide in the wiki in the improvement section 

https://github.com/mockito/mockito/wiki/What%27s-new-in-Mockito-2

**Comment by TimvdLippe** [comment]
Per https://github.com/mockito/mockito/issues/720#issuecomment-257087017 the message of `UnnecessaryStubbingException` should be improved to mention `MockitoJUnitRunner.Silent`.
