### ISSUE TITLE
Create and test release checklist

### ISSUE THREAD

**Issue by szczepiq** [mockito/mockito#620]
Create and test release checklist. I'm happy to start working on it tomorrow morning.

**Comment by szczepiq** [comment]
Hey guys, how does it sound:

- release preparation:
  - create “release/v2” branch (name of the branch ok?)
  - update release notes document (see: #621)
  - test the release
    - make javadoc changes, push
    - iterate on the fixes (automated release is unfortunately coupled with ‘master’ branch but it shouldn’t be difficult to fix) until this works
- release checklist:
  - update version in “version.properties” in “release/v2” branch to 2.1.0
  - push!!! Everything “should” just work :)
  - when Travis build completes:
    - take a look at the automated release notes if they need some tweaking
    - take a look at the mockito.org site if it needs some tweaking (release notes link to v2.md, etc.)
    - announce via twitter (the release notes document has one sentence at the top that is twitter-ready 😃)
    - announce on the mailing list (other places as needed?)

**Comment by bric3** [comment]
`release/2.x` ?

**Comment by bric3** [comment]
> take a look at the mockito.org site if it needs some tweaking (release notes link to v2.md, etc.)

Done. Look at #621

**Comment by szczepiq** [comment]
2.x looks kind of funky ;) Is this how people do it? Tim?

**Comment by TimvdLippe** [comment]
There is no golden rule, usually up to the team to decide. I prefer the release/2.x too

**Comment by szczepiq** [comment]
Cool, it's decided then

**Comment by TimvdLippe** [comment]
I am going to instantiate this process and checklist

**Comment by TimvdLippe** [comment]
I have added 2 subreddits to announce to post-release

**Comment by TimvdLippe** [comment]
Release has been started on Travis: https://travis-ci.org/mockito/mockito/jobs/158990021

**Comment by TimvdLippe** [comment]
Artifact has been succesfully generated at https://jcenter.bintray.com/org/mockito/mockito-core/2.1.0-RC.1/

**Comment by TimvdLippe** [comment]
Announced on Twitter and mailing list. We can do Reddit later?

**Comment by bric3** [comment]
Why not! I don't think much people read reddit though, in my opinion we should only update channels we maintain and follow.

**Comment by TimvdLippe** [comment]
You would rather refrain from posting to Reddit? Fine by me, but I do think we have a potential audience there :smile:

**Comment by bric3** [comment]
Not refrain, but the team may not follow this channel, I barely follow the mailing list or SO, I probably won't reddit.

**Comment by TimvdLippe** [comment]
Ah I see. Personally I read /r/programming so I could maintain/answer questions. Will do it all later though, maybe when we have an official release.

Since the RC has been published I am closing this ticket.
