### ISSUE TITLE
Javadoc CSS width issue

### ISSUE THREAD

**Issue by lukasz-szewc** [mockito/mockito#629]
There is some minor problem with element width (CSS) on javadoc site.
Some elements are too wide and are causing horizontal scroll bar to show up.

I post picture to show what is going on.

https://s9.postimg.io/xlbg2e0ul/mockito_javadoc.png

**Comment by bric3** [comment]
I don't had the problem when I tested the css the problem but that depend on the browser. 

If you know how to fix it that would be awesome!

**Comment by bric3** [comment]
Just saw the PR thanks!

**Comment by lukasz-szewc** [comment]
Probably after this change there will be still horizontal scroll-bar because I saw some other elements longer then 100% (with padding, margins and borders) . Even if they are - they will not be as significant as ones solved in PR.
