### ISSUE TITLE
Possible solution to spy final class

### ISSUE THREAD

**Issue by WalterInSH** [mockito/mockito#632]
Hi 
I've noticed that Mockito cannot spy final class,  this really bothers me when I use spring proxy. I know I can get the real target from the proxy before spying it. But I just really need the proxy.

I wrote a handy class to solve this.

```
public class CallRealMethodAnswer implements Answer{

    private Object target;

    public CallRealMethodAnswer(Object target){
         this.target = target;
    }

    @Override
    public Object answer(InvocationOnMock invocation) throws Throwable {
    return ReflectionUtils.invokeMethod(
              invocation.getMethod(),
              target,
              invocation.getArguments());
    }
}
```

It works like spy(), but without those limits.

I'm wondering if it's useful for someone else.

**Comment by bric3** [comment]
Have a look at `AdditionalAnswers.delegateTo` that may come to help in such case.

**Comment by WalterInSH** [comment]
@bric3 Yes! Hah! Thank you very much!

**Comment by bric3** [comment]
You're welcome ;)
