### ISSUE TITLE
Mockito machers exception 

### ISSUE THREAD

**Issue by yboug** [mockito/mockito#644]
> Hey,
> 
> I use a Mockito when with matchers
`Mockito.when(aRepository.searchForList(
    Mockito.any(LocalDateTime.class),
    Mockito.anyLong(), 
    Mockito.anyBoolean()
)).thenReturn(mockedSearchForList);`

>so after i run tests, have this exception
`org.mockito.exceptions.misusing.InvalidUseOfMatchersException: Invalid use of argument matchers! 0 matchers expected, 3 recorded:`

>this exception may occurs if i mix matchers and real values, which is not my case.

> Mockito version 1.10.19

**Comment by ChristianSchwarz** [comment]
I can not reproduce it with 2.1.0-RC.1 nor with 1.10.19 when I run this test code:

```
@Test
public void test() throws Exception {
	Interface mock = mock(Interface.class);
	when(mock.process( any(LocalDateTime.class), anyLong(), anyBoolean() )).thenReturn(123);
}

interface Interface {
	int process(LocalDateTime t, long l, boolean b);
}
```

@yboug Which Mockito version are you using? Can you run my test on your side?

**Comment by yboug** [comment]
this code pass correctly.
@ChristianSchwarz

**Comment by bric3** [comment]
Is `searchForList` final ? Then this method cannot be mocked at this time.

**Comment by yboug** [comment]
search for list is not final.
I have a repository interface implement a customRepository that contain the searchList

> public interface RepositoryCustom {

	List<BkgServiceListResult> searchForList(LocalDateTime now, long envId, boolean showInactives);
}

> @Repository
public interface Repository extends MultiTenantRepository<Service, Long>, RepositoryCustom {

    Service getByIdEnvAndId(long idEnv, long id);
}

this is my code

**Comment by yboug** [comment]
I solve this issue, by disabling Hibernate Aspect.
it's not a problem of mockito.
when aspect throw an exception, mockito throw matcher exception

**Comment by bric3** [comment]
Ok, we were missing a lot of context and code to see that, Glad you found your way out  ;)

**Comment by yboug** [comment]
thanx for help

**Comment by bric3** [comment]
Thanks, you're welcome here anytime ;)
