### ISSUE TITLE
Seamless mocking of final classes and methods

### ISSUE THREAD

**Issue by mockitoguy** [mockito/mockito#657]
Let's figure out how to offer seamless mocking of final mocks, without using different mock maker.

**Comment by TimvdLippe** [comment]
https://github.com/mockito/mockito/pull/648/commits/2990760889b4146cdceb10659e43693476d81bee was primarily aimed to allow this feature to be built

**Comment by reitzig** [comment]
Wouldn't using [kotlin-allopen](https://kotlinlang.org/docs/reference/compiler-plugins.html#all-open-compiler-plugin) solve the issue for users? (Not sure if the effect can be restricted to test modules/tasks only.)

**Comment by TimvdLippe** [comment]
The inline mockmaker tackles this problem, as the subclass mockmaker can not do this. Therefore, I am closing this issue.
