### ISSUE TITLE
Port external blogposts to wiki page to prevent linkrot

### ISSUE THREAD

**Issue by bric3** [mockito/mockito#658]
Dead links are bad, instead of relying on websites that can disappear anytime, the javadoc should only : 
- Have the content copied in a quoted fashion
- Link to the mockito wiki (which is git based) or a markdown page within this code repository

e.g. `Mockito` class link to this website that is not anymore available https://monkeyisland.pl/2009/01/13/subclass-and-override-vs-partial-mocking-vs-refactoring

**Comment by szczepiq** [comment]
I fixed the link so that it is no longer dead. However, I agree that links in most cases should take the user to wiki, javadocs "inside" the project. Otherwise we risk stale links.

**Comment by bric3** [comment]
Ok thanks :)

**Comment by TimvdLippe** [comment]
I wonder how up-to-date these posts are, maybe they are out of date already.

**Comment by bric3** [comment]
If @szczepiq is OK he or we could create a wiki page. Then it will have a better chance to stay up to date.

**Comment by szczepiq** [comment]
+1

**Comment by szczepiq** [comment]
If you want to create wiki for those links, go for it and replace the link.

Despite the risk of getting out of date (wikis can get out of date, or deleted too :), it's ok to link to high quality external articles of Mockito team members. Firstly, users have more links to follow and browse / learn about useful content. Secondly, it is good to be awarded for the hard work we put in, with more traffic to our blogs/articles/public content :)

**Comment by bric3** [comment]
Linkrot is an issue for released javadoc as they cannot be updated anymore. Putting the content on the wiki has still more chance to be maintained up-to-date than a website not in our reach. On that matter I even forgot it was your website.

Also having the wiki pages does not forbid links to external website either from the javadoc or from the wiki, but I tend to have the same opinion as [stackoverflow guideline](http://stackoverflow.com/help/how-to-answer) : 

> Links to external resources are encouraged, but please add context around the link so your fellow users will have some idea what it is and why it’s there. Always quote the most relevant part of an important link, in case the target site is unreachable or goes permanently offline.

That's what I did when I wrote that wiki page [how to write good tests](https://github.com/mockito/mockito/wiki/How-to-write-good-tests). This allows readers to have proper documentation at hand. Having such content on the wiki is good as well instead of greping the web.
Finally I agree work attribution is important, adding a wiki page with content form someone must have the proper author attribution.

**Comment by szczepiq** [comment]
Thanks writing this up. This makes perfect sense. I fully agree.

**Comment by LSwiatek** [comment]
Links in java doc should be addressed asap - even if it means they have to be removed. The domain monkeyisland.pl is currently being auctioned for sale ( https://www.aftermarket.pl/domena/monkeyisland.pl?nostat=1 ) .
Worst case, links will lead to malicious site in the near future

**Comment by TimvdLippe** [comment]
This was fixed in https://github.com/mockito/mockito/commit/1df5e49043fb032106f5c0fc0eec97ca9251241f#diff-ddbc0d47e06a589778a6efe24c5d71d3
