### ISSUE TITLE
Continuous integration does not use generic user everywhere

### ISSUE THREAD

**Issue by bric3** [mockito/mockito#659]
There's of course the binary upload on bintray that require a mockito account (see #631), but there is still some interactions with git that should use the _continuous delivery drone_ generic user.

See https://github.com/mockito/mockito/blob/master/gradle/release.gradle#L117, credentials are one of these : https://github.com/mockito/mockito/blob/master/.travis.yml#L35-L37

**Comment by szczepiq** [comment]
This should be easy to change, e.g. just change the user token id in the Travis encrypted variables. Anyone can do it.

**Comment by bric3** [comment]
INdeed this technical part is easy but we don't have the credentials of `continuous.delivery.drone@gmail.com`

**Comment by bric3** [comment]
Actually I just realized that `continuous.delivery.drone@gmail.com` has no github account

**Comment by szczepiq** [comment]
Ok, I will sort this out.
-- 
Szczepan Faber
Founder @ mockito.org | Twitter @ szczepiq
Author @ https://www.linkedin.com/today/author/6016386

**Comment by szczepiq** [comment]
The current setup is very open: the generic continuous.delivery.drone@gmail.com is not a GitHub user. It can be any email address. Anyone with commit rights can change the API key in travis file + update reference in release.gradle. So, adding new generic GitHub account that needs to be shared has no value.

I'll close this ticket once I document it in the release.gradle

**Comment by bric3** [comment]
I don't agree, the credentials of the team have way more reach than simply push rights, the credentials can be used against the github API to change organization settings, etc...
While having a bot account allows to narrow down the scope of what this account can do.

**Comment by szczepiq** [comment]
Good point!

**Comment by szczepiq** [comment]
The release process uses GitHub write token that has tailored permissions and it cannot alter Mockito organization settings. This token can be easily generated by any committer and the release script can be updated. Maintaining and sharing fake GitHub user does not add any value.

Thanks for brining this up and a very interesting discussion about repo security and maintainability!

Reopen if needed!
