### ISSUE TITLE
MockitoJUnitRunner not resolved

### ISSUE THREAD

**Issue by gaetan3009** [mockito/mockito#663]
Hi,
I use gradle with my android project. I put     
testCompile 'org.mockito:mockito-core:1.10.19'
jcenter()
The imports related to are not resolved. But AndroidJUnit4 is resolved 

Thank you

**Comment by TimvdLippe** [comment]
Did you run `./gradlew build`? It probably is an issue with your local setup. You might also want to try the fix at https://github.com/mockito/mockito/issues/638#issuecomment-248005406
Closing since this seems to be related to a local problem and not with Mockito.
