### ISSUE TITLE
publish.gradle is unaware of commit message version

### ISSUE THREAD

**Issue by TimvdLippe** [mockito/mockito#666]
I just tried to release a custom version with the command line, but this failed because the publish task does not honor the commit message version.

https://github.com/mockito/mockito/blob/master/gradle/publish.gradle#L9 should be changed roughly to https://github.com/mockito/mockito/blob/master/gradle/release.gradle#L114-L115

**Comment by bric3** [comment]
yep version is currently taken from property file in https://github.com/mockito/mockito/blob/master/gradle/version.gradle and used in publication

**Comment by szczepiq** [comment]
@TimvdLippe, curious, what custom version did you try to release and why?

BTW. Thanks for releasing final version!!!!!!!!!!

**Comment by TimvdLippe** [comment]
https://github.com/mockito/mockito/commit/fd27e43f041c98fabb45f53f3c829ae0496551c9

**Comment by szczepiq** [comment]
It should be very easy to implement in version.gradle, for example, 'overrideVersion' project property. No need to change the release / publication logic.

**Comment by szczepiq** [comment]
Do we still need this feature? What are the use cases?

**Comment by TimvdLippe** [comment]
I want to be able to publish a new version by commit message. This was for example a problem when I was fixing the Android dependency problem. I was unable to publish a new version since the automatic system was unable to detect a meaningful change. Since the automatic system is never 100% correct, we should be able to manually override it via commit message.

**Comment by szczepiq** [comment]
Thank you for feedback. Let's keep the ticket open.

**Comment by TimvdLippe** [comment]
Closing this as the current file has been removed.
