### ISSUE TITLE
Remove 2.2.0-beta.1 from bintray

### ISSUE THREAD

**Issue by TimvdLippe** [mockito/mockito#667]
https://bintray.com/szczepiq/maven/mockito/2.2.0-beta.1# was incorrectly generated by the delivery drone and must be removed asap from Bintray. Within 24 hours this is still possible, see https://bintray.com/docs/usermanual/uploads/uploads_deletingcontent.html

Only @szczepiq can do this because it is his account and not the Mockito organization.

**Comment by szczepiq** [comment]
I see we're making progress on avoiding beta versions confusion :)

**Comment by szczepiq** [comment]
Deleted. Are we expecting this version is maven central, too?

**Comment by TimvdLippe** [comment]
Have to see if it pops up, else we have to delete there too :sob:

**Comment by bric3** [comment]
Given the beta number and the decision to not remove them, we could have just updated the version properties

**Comment by szczepiq** [comment]
That was an option, too. I didn't see it in central so I decided that it is a good idea to rid this version. Also, I created #669

**Comment by bric3** [comment]
Artifacts takes time to propagate over there, I don't know much about how bintray do that exactly though

**Comment by bric3** [comment]
Nice for #669. :)

**Comment by bric3** [comment]
Ah it seems 2.2.0-beta.1 is on maven central http://repo1.maven.org/maven2/org/mockito/mockito-core/2.2.0-beta.1/

**Comment by szczepiq** [comment]
Yup, I saw it. I tried to delete it but it does not seem to be possible. I'm going to give up. Let's release 2.2.0 final soon to recover from beta versions trauma.

**Comment by bric3** [comment]
OK so I'll change the next beta to 2.2.0-beta.2 and disable release again until we have a beta repo

**Comment by szczepiq** [comment]
Versions 2.x don't need betas.

**Comment by szczepiq** [comment]
Closing this one. Unfortunately maven central has the artifact and I don't know how to delete it.

**Comment by bric3** [comment]
Yes agreed, it shouldn't need beta, this change is just to indicate the pending status, and avoid confusion with the accidental release on central.

**Comment by bric3** [comment]
Also we still have works for [milestone 2.2](https://github.com/mockito/mockito/milestone/3)
