### ISSUE TITLE
Publish mockito artifacts to 'mockito' organization in Bintray

### ISSUE THREAD

**Issue by szczepiq** [mockito/mockito#669]
Instead of publishing to 'szczepiq' user, the artifacts should be published to 'mockito' organization in Bintray.

**Comment by szczepiq** [comment]
In progress. I transferred ownership of "szczepiq/maven" repository to the "mockito" org. It takes forever to complete in Bintray UI api. Keeping thumbs up ;)

I spent 1.5 hours poking around oss nexus and bintray. Too long to get stuff done.

**Comment by bric3** [comment]
Things that matter can take time ;)

**Comment by szczepiq** [comment]
Reopening because it is not merged yet to the main branch (this also make it appear in release notes twice as PR and as an issue).

**Comment by szczepiq** [comment]
Let's close it. We will merge all from release branch -> master anyway.
