### ISSUE TITLE
Mockito.<MyClass>notNull() returns an Object, not a MyClass.

### ISSUE THREAD

**Issue by stantonwjones** [mockito/mockito#677]
given:
Class MyClass {}

and:
int somePublicMethod(MyClass myClass) {...}

Mockito.<MyClass>notNull() returns an Object, not a MyClass.

therefor:
when(someObject.somePublicMethod(Mockito.<myClass>notNull())).thenReturn(7);

will throw:

method somePublicMethod in class SomeObject cannot be applied to given types;

expected: MyClass
found: Object

jre 1.8
os: ubuntu
mockito version: unknown

sorry for the unknown Mockito version and lack of compile-able code. But this is pretty straightforward. Either this is (for some reason) expected, or it can be quickly fixed. It's possible I'm just using a deprecated version of the library, but please check that this is not an existing problem in Mockito 2.0 / 2.2

**Comment by ChristianSchwarz** [comment]
I can't reproduce this with v2.1.0. The implementation always returns null. 

```java
    public static <T> T notNull() {
        reportMatcher(NotNull.NOT_NULL);
        return null;
    }

**Comment by bric3** [comment]
In mockito 1.x `notNull()` returns an object and requires an explicit cast, however the API offered at some point `<T> T notNull(Class<T>)` that returns a `T`.
