### ISSUE TITLE
VerificationAfterDelayTest is unstable because it uses sleeps

### ISSUE THREAD

**Issue by szczepiq** [mockito/mockito#682]
VerificationAfterDelayTest is unstable, I will ignore this test until it is fixed. Anyone wants to pick it up and make it stable?

**Comment by TimvdLippe** [comment]
Hm this should have been fixed in #619

**Comment by bric3** [comment]
The `DelayedExecution` class still uses `sleep` (idden in the `TimeUnit.sleep` code). This change in #619 code is so much better than it was but not entirely bullet proof either. @szczepiq Do you have the build log that failed ?

**Comment by szczepiq** [comment]
It failed in release/2.x branch build on Travis CI. The fix was not merged to 2.x?

**Comment by bric3** [comment]
It is. `release/2.x` was created after the change. But the fix seems not enough, there's is still room for one thread to go slower than expected, and then the verify race the code which makes the code fail.

**Comment by TimvdLippe** [comment]
It seems that most of our builds are stable again. Shall we close it for now?

**Comment by bric3** [comment]
It works be a useful there's the retry rule, however I still think there could be correct harness for tj se tests.

**Comment by szczepiq** [comment]
I say we close the ticket. Nobody worked on it for almost 2 months and I don't think anybody will. I think there more interesting features and enhancements we can work on.

The retry rule works like a charm :) Let's move on!
