### ISSUE TITLE
Release process assumes that publications are equal when manifest file changes

### ISSUE THREAD

**Issue by mockitoguy** [mockito/mockito#684]
Release process assumes that publications are equal when manifest file changes. This is not correct, sometimes we fix bugs with OSGi bundles and the only change is in the manifest file. In this scenario the release should be triggered and new version released.

**Comment by TimvdLippe** [comment]
This should be fixed with our adoption of Shipkit with the corresponding algorithm in https://github.com/mockito/shipkit/issues/84
