### ISSUE TITLE
Mocking interface clone method

### ISSUE THREAD

**Issue by jpenglert** [mockito/mockito#688]
Mocking a `clone()` method on an interface appears to no longer be working with **Mockito 2.1.0**. The below code works fine with **Mockito 1.10.19** but throws an `IllegalAccessError` with **Mockito 2.1.0**:

    public interface CloneableInterface extends Cloneable {
       CloneableInterface clone();
    }

    public class CloneableInterfaceTest {
    
       @Test
       public void test() {      
          CloneableInterface i = Mockito.mock(CloneableInterface.class);
          Mockito.when(i.clone()).thenReturn(i); // Throws IllegalAccessError
       }
    }

Result of running above test:

    java.lang.IllegalAccessError: CloneableInterface$MockitoMock$833899610.clone()LCloneableInterface;

Environment: **JDK 1.8.0_102, JUnit 4.11, Mockito 2.1.0, Gradle 3.0, Windows 10**

EDIT: Link to [SO post](http://stackoverflow.com/questions/39967723/mocking-interface-clone-method)

**Comment by raphw** [comment]
I see what is happening here. Since `Object::clone` is protected and since Java favors subclass inheritance over interface inheritance, the subclass overrides clone as a `protected` method, rather than a `public` method. Of course, Mockito should render all mock methods public, currently we are not doing this but this is trivial to fix.

Thanks for reporting this.

**Comment by jpenglert** [comment]
@raphw thanks for the quick response. Ah, your root cause analysis makes sense. I suppose this is a bit of a corner case and completely understand why it would have been overlooked. Looking forward to the fix as this is the final item blocking us from upgrading to 2.1.0. Thanks for all the great work.

**Comment by TimvdLippe** [comment]
@jpenglert It should be fixed in `Mockito 2.2.1`, thanks a lot for reporting!

**Comment by bric3** [comment]
yes unfortunately maven sync doesn't work thanks to #683

**Comment by szczepiq** [comment]
Triggered central sync. @bric3, I will enable sync now. I wanted to manually verify few releases.

**Comment by bric3** [comment]
Thanks @szczepiq

**Comment by jpenglert** [comment]
This bug appears to be back after I upgraded from Mockito 2.2.1 -> 2.7.13. The original test case I posted is failing in the same manner. I ran the above test case with various versions and it appears the 2.7.12 re-introduced this bug. Perhaps #963 is responsible?

**Comment by raphw** [comment]
We should add it, I originally added a modified version to Byte Buddy but it seems to have missed an aspect. Feel free to send a PR.

**Comment by raphw** [comment]
I already located and fixed the error. I forgot to adjust the visibility for bridge methods.

**Comment by jpenglert** [comment]
I'll make a PR for the acceptance test.

**Comment by raphw** [comment]
I just release a new Byte Buddy version but I did not correctly apply the fix. Next version!
