### ISSUE TITLE
Removing mockingDetails API from Mockito

### ISSUE THREAD

**Issue by bric3** [mockito/mockito#69]
After some exchange with other member of the community, code such as 

```java
Mockito.mockingDetails(someObject).isMock();
Mockito.mockingDetails(someObject).isSpy();
```

It looks wrong ; Mockito is the entry point for user friendly usage from within the test. Inspecting mocks looks wrong when it's a normal _user_.

However I know framework developers may need to inspect mocks. Let's keep the `MockingDetails` type but instantiate it from another static factory method.

The drawback is the removal of this API for current users. Maybe we can mark `Mockito.mockingDetails(..)` deprecated in 1.9.x and remove it in 2.0.0

**Comment by TimvdLippe** [comment]
Per discussion in Slack with @marcingrzejszczak on Spring Boot, these methods would be the replacement for the `MockUtil` classes to be backwards compatible for both Mockito 1.9.X and Mockito 2.X.

**Comment by bric3** [comment]
Not every `MockUtil` functionality is available in `MockingDetails`. Yet I think we can keep this API and remove `debug` instead.

**Comment by szczepiq** [comment]
There's a new API I have introduced recently: Mockito.framework()

Mockito.debug() is definitely going away :)

I'm not sure Mockito.mockingDetails() needs to removed. As a user, If I needed mocking details, I would look for it on Mockito class. However, I do agree this is not quite 'users' scenario, but more like framework integrators scenario.

**Comment by bric3** [comment]
Closing as `MockingDetails` will finally stay as per #541 #542
