### ISSUE TITLE
Host javadocs at javadoc.io

### ISSUE THREAD

**Issue by szczepiq** [mockito/mockito#692]
javadoc.io offers free hosting of javadoc, see: http://www.javadoc.io/doc/org.mockito/mockito-core/2.2.0

It's completely free - no effort is needed from our end - they get javadoc from central.

Using this service, we could simplify our release pipeline and avoid growing mockito git repo with every release (javadocs are checked-in). Downside is that there is some delay in showing the docs and it's another 3rd party integration.

Currently, our release pipeline for javadoc does not fully support 2 concurrent dev branches. Releasing 3.x experimental version will replace the 'current' permalink for javadocs. I'm not very keen on spending effort on fixing that if we can get javadocs for free from an external service.

Thoughts?

**Comment by bric3** [comment]
I agree that's a good idea and that will simplify the build script too.

**Comment by szczepiq** [comment]
How is removing the branch lighten the repo given the repo contains all history?

We could keep the latest 1.x release, 2.x releases for the time being.

**Comment by bric3** [comment]
> How is removing the branch lighten the repo given the repo contains all history?
> We could keep the latest 1.x release, 2.x releases for the time being.

That's the thing : if we remove the `gh-pages` reference, I believe that git will eventually perform a gc and then remove the unreachable commits history. However if we keep `gh-pages` indeed this GC won't happen.

**Comment by szczepiq** [comment]
Cool

**Comment by szczepiq** [comment]
I'm exploring 2 options now:
 - move to javadoc.io, nice service, but
  - there is a delay in showing docs after release
  - no way to link to specific class of latest release - sent an email to javadoc.io with question
 - move javadoc to separate repo under 'mockito' project

**Comment by szczepiq** [comment]
Updated site links and README.md links. I need to go over the wikis and update links there. After that, we can build a plan for getting rid of the html from the repo and make the repo smaller. Thanks for getting into the conversation with javadoc.io!!!

**Comment by TimvdLippe** [comment]
I think we can close this one?

**Comment by bric3** [comment]
yes

**Comment by bric3** [comment]
Shall we remove gh-pages branch ?

**Comment by TimvdLippe** [comment]
Yes lets remove that

**Comment by bric3** [comment]
Note it may break current links (https://www.google.fr/webhp?sourceid=chrome-instant&ion=1&espv=2&ie=UTF-8#q=mockito%20javadoc)

**Comment by TimvdLippe** [comment]
I thought about that after posting my comment. Maybe we let it redirect to javadoc.io?

**Comment by bric3** [comment]
Is it even possible with github pages ?

**Comment by szczepiq** [comment]
Redirect should be possible. I'd recommend holding off removing gh-pages for now.

**Comment by szczepiq** [comment]
Let's close this one and track more work here: #753

**Comment by bric3** [comment]
Agreed
