### ISSUE TITLE
Remove rudimentary TestNG support

### ISSUE THREAD

**Issue by szczepiq** [mockito/mockito#694]
How about we get rid of TestNG support? We haven't released it for years, it's unlikely we will prioritize it. Less code, cleaner codebase.

**Comment by bric3** [comment]
We could still include it in the main code base.

**Comment by bric3** [comment]
Anyway I'm  against removing this code. Some people were relying on it and wanted these classes to be released.

**Comment by bric3** [comment]
See #300

**Comment by szczepiq** [comment]
I'm convinced, let's ship it instead of removing :)
