### ISSUE TITLE
Missing @Mock for @InjectMocks silently fails when it cannot find the dependency

### ISSUE THREAD

**Issue by dellinger** [mockito/mockito#70]
I stumbled across this blog post
http://tedvinke.wordpress.com/2014/02/13/mockito-why-you-should-not-use-injectmocks-annotation-to-autowire-fields/

Would it be possible to add the capability to not silently fail when Mockito cannot find a dependency in the scenario listed above?

**Comment by tvinke** [comment]
Far overdue, but for what it's worth: I quoted your reaction at the end of my article, under heading "Edit July 2020":
https://tedvinke.wordpress.com/2014/02/13/mockito-why-you-should-not-use-injectmocks-annotation-to-autowire-fields/#edit-july-2020

**Comment by bric3** [comment]
@black-snow This is an interesting approach ; I believe this is worth a discussion, possibly leading to a prototype. That said I struggled to actually contribute to this project in the last years. Even professionally I now rarely use Mockito. I might be able to review such code though.

**Comment by black-snow** [comment]
Aight, guess I should open a new issue then.
