### ISSUE TITLE
Tabular release notes format

### ISSUE THREAD

**Issue by szczepiq** [mockito/mockito#700]
Given that there are small changes in each version, tabular format would be better. Current release notes look like [that](https://github.com/mockito/mockito/blob/release/2.x/doc/release-notes/official.md). Example tabular release notes:

| Version | Date | Authors (commits) | Type | Link | Description |
| --- | --- | --- | --- | --- | --- |
| 2.2.5 | 2016-10-17 16:34 UTC | Christian Schwarz (2), Brice Dutheil (1) | Enhancement | #635 | Unified logic of argument matching and capturing |
| 2.2.4 | 2016-10-17 15:40 UTC | Rafael Winterhalter (1) | Bugfix | #699 | Fails to create mock of inner class hierarchy with type variable from outer class |
|  |  |  | Misc | #695 | Mocking final classes with Java8 when compiling with -parameters flag |

**Comment by bric3** [comment]
This representation indeed looks better.

**Comment by szczepiq** [comment]
Ticket moved to mockito-release-tools repository: https://github.com/mockito/mockito-release-tools/issues/3
