### ISSUE TITLE
Mockito 2 cannot mock kohsuke/github-api classes

### ISSUE THREAD

**Issue by bric3** [mockito/mockito#701]
A user (Adam) on the [mailing list](https://groups.google.com/d/msgid/mockito/4cbdcec2-19d6-4757-b135-2cf515ed785f%40googlegroups.com) wasn't sure if he misused mockito. So he reached us via the mailing-list.

> Hi guys, a super simple test that creates a new mock of a public non-final class `org.kohsuke.github.GHIssue` from https://github.com/kohsuke/github-api version 1.77, source https://github.com/kohsuke/github-api/blob/github-api-1.77/src/main/java/org/kohsuke/github/GHIssue.java fails with:

```
mock(GHIssue.class);
```

> ```
> org.mockito.exceptions.base.MockitoException: 
> Mockito cannot mock this class: class org.kohsuke.github.GHIssue.
> 
> Mockito can only non-private & non-final classes.
> If you're not sure why you're getting this error, please report to the mailing list.
> 
> Java               : 1.8
> JVM vendor name    : Oracle Corporation
> JVM vendor version : 25.101-b13
> JVM name           : Java HotSpot(TM) 64-Bit Server VM
> JVM version        : 1.8.0_101-b13
> JVM info           : mixed mode
> OS name            : Mac OS X
> OS version         : 10.11.6
> 
> 
> Underlying exception : java.lang.IllegalArgumentException: Cannot cast to primitive type: void
> 
>     at com.siemion.mockito.AppTest.test(AppTest.java:12)
>     at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
>     at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
>     at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
>     at java.lang.reflect.Method.invoke(Method.java:498)
>     at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
>     at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
>     at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
>     at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
>     at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
>     at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
>     at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
>     at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
>     at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
>     at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
>     at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
>     at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
>     at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
>     at org.junit.runner.JUnitCore.run(JUnitCore.java:160)
>     at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:69)
>     at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:234)
>     at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:74)
>     at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
>     at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
>     at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
>     at java.lang.reflect.Method.invoke(Method.java:498)
>     at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)
> Caused by: java.lang.IllegalArgumentException: Cannot cast to primitive type: void
>     at net.bytebuddy.implementation.bytecode.assign.TypeCasting.to(TypeCasting.java:39)
>     at net.bytebuddy.dynamic.scaffold.TypeWriter$MethodPool$Record$AccessBridgeWrapper.apply(TypeWriter.java:1100)
>     at net.bytebuddy.dynamic.scaffold.TypeWriter$Default$ForCreation.create(TypeWriter.java:3802)
>     at net.bytebuddy.dynamic.scaffold.TypeWriter$Default.make(TypeWriter.java:1618)
>     at net.bytebuddy.dynamic.scaffold.subclass.SubclassDynamicTypeBuilder.make(SubclassDynamicTypeBuilder.java:172)
>     at net.bytebuddy.dynamic.scaffold.subclass.SubclassDynamicTypeBuilder.make(SubclassDynamicTypeBuilder.java:153)
>     at net.bytebuddy.dynamic.DynamicType$Builder$AbstractBase.make(DynamicType.java:2568)
>     at net.bytebuddy.dynamic.DynamicType$Builder$AbstractBase$Delegator.make(DynamicType.java:2670)
>     at org.mockito.internal.creation.bytebuddy.SubclassBytecodeGenerator.mockClass(SubclassBytecodeGenerator.java:80)
>     at org.mockito.internal.creation.bytebuddy.TypeCachingBytecodeGenerator$CachedBytecodeGenerator.getOrGenerateMockClass(TypeCachingBytecodeGenerator.java:87)
>     at org.mockito.internal.creation.bytebuddy.TypeCachingBytecodeGenerator.mockClass(TypeCachingBytecodeGenerator.java:34)
>     at org.mockito.internal.creation.bytebuddy.SubclassByteBuddyMockMaker.createMockType(SubclassByteBuddyMockMaker.java:64)
>     at org.mockito.internal.creation.bytebuddy.SubclassByteBuddyMockMaker.createMock(SubclassByteBuddyMockMaker.java:35)
>     at org.mockito.internal.creation.bytebuddy.ByteBuddyMockMaker.createMock(ByteBuddyMockMaker.java:22)
>     at org.mockito.internal.util.MockUtil.createMock(MockUtil.java:35)
>     at org.mockito.internal.MockitoCore.mock(MockitoCore.java:63)
>     at org.mockito.Mockito.mock(Mockito.java:1629)
>     at org.mockito.Mockito.mock(Mockito.java:1542)
>     ... 27 more
> ```

Or

```
mock(GHRepository.class);
```

> ```
> java.lang.VerifyError: Bad type on operand stack
> Exception Details:
>   Location:
>     org/kohsuke/github/GHRepository$MockitoMock$667330966.getId()Ljava/lang/String; @4: checkcast
>   Reason:
>     Type integer (current frame, stack[0]) is not assignable to 'java/lang/Object'
>   Current Frame:
>     bci: @4
>     flags: { }
>     locals: { 'org/kohsuke/github/GHRepository$MockitoMock$667330966' }
>     stack: { integer }
>   Bytecode:
>     0x0000000: 2ab6 003d c000 2eb0                    
> 
> 
>     at sun.reflect.GeneratedSerializationConstructorAccessor1.newInstance(Unknown Source)
>     at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
>     at org.objenesis.instantiator.sun.SunReflectionFactoryInstantiator.newInstance(SunReflectionFactoryInstantiator.java:45)
>     at org.objenesis.ObjenesisBase.newInstance(ObjenesisBase.java:73)
>     at org.mockito.internal.creation.instance.ObjenesisInstantiator.newInstance(ObjenesisInstantiator.java:14)
> ```

Related classes declaration

```
    <dependency>
      <groupId>org.kohsuke</groupId>
      <artifactId>github-api</artifactId>
      <version>1.77</version>
    </dependency>
```

-------------------------------

After investigation on the project created by Adam Siemon [here](https://github.com/adamsiemion/mockito-bug). I’ve reproduced the issue you are seeing with mockito 2.2.3 (bb 1.4.26) and 2.2.5 (bb 1.4.33), regardless of the JDK version. It seems related to how [kohsuke/github-api](https://github.com/kohsuke/github-api) generates bridge method in the byte code for backward compatibility ; this seems highly unusual, it may produce valid bytecode but with _unmet_ bytecode patterns for mockito / bytebuddy.
For reference the tool is called [bridge-method-injector](https://github.com/infradna/bridge-method-injector), more on the [website](http://bridge-method-injector.infradna.com/)

The classes you are mentioning are modified by this tool :

* [`GHIssues`](https://github.com/kohsuke/github-api/blob/github-api-1.77/src/main/java/org/kohsuke/github/GHIssue.java#L151-L154) annotated by `@WithBridgeMethods(void.class)`
* `GHRepository` that inherits [`GHObject`](https://github.com/kohsuke/github-api/blob/github-api-1.77/src/main/java/org/kohsuke/github/GHObject.java#L66-L69) which also annotated by `@WithBridgeMethods(value=String.class, adapterMethod="intToString")`

It works with 1.10.19 because CGLIB is far less intelligent regarding bridge methods.

**Comment by raphw** [comment]
My bad, kid of forgot that bridge methods can return `void` or other primitive types. Will fix some time this week.

**Comment by raphw** [comment]
This is a difficult problem to solve. The library messes with the type structure. The method in question looks like this:

```java
@WithBridgeMethods({void.class})
public GHIssueComment comment(String message) throws IOException
```

This makes it impossible for Byte Buddy to build bridge methods as they are required by the Java-specification. A `void` type can simply not be assigned to a `GHIssueComment` type. cglib "solved" this problem by ignoring bridge methods alltogether but all in all, there is no good solution to this. The mocked class is simply not legal Java code.

**Comment by bric3** [comment]
You confirmed my fears, I was kinda prudent when I said unusual. Could we fail more graciously?

For `GhRepository` the problem is a bit different as the byte code is generated, but objenesis fails to instantiate the mock class `VerifyError` thrown by the JVM.

**Comment by raphw** [comment]
I added a filter to Byte Buddy that throws out bridge methods that are incompatible to the bridged methods signature. Its already fixed on master. I will make a new release some time soon, this makes the error go away. As bridge methods are inherited, it does neither break runtime behavior.

PS: Adding such bridge methods also breaks Javac. Adding such methods is generally not a good idea for non-final types.

**Comment by bric3** [comment]
When I discovered that bridge hack to maintain backward compatibility, I thought this is a bad idea.
I'm even less enticed to use this library.

Thanks @raphw, it seems mockito brings a whole world of weirdness to bytebuddy 😉

**Comment by raphw** [comment]
I understand the general intend to retain backwards compatibility but this is a general problem in Java and the hack might seem intelligent in the beginning but it is really problematic and might also confuse reflection. It would work much better if it was only used for final types.

I am glad I find these things out, encountering these issues makes Byte Buddy better in the long run ;)

**Comment by szczepiq** [comment]
Thanks guys for investigating the problem! Let me clarify the resolution. Although some options to fix the problem exist, there is no good solution. Therefore, some classes from github-api are not currently mockable with Mockito 2.

- Can we close this ticket for the time being? We can revisit when there are more use cases.
- Is there a way to fail more intelligently and provide better insight to the user?

**Comment by bric3** [comment]
Let's wait for @raphw to release a new version ByteBuddy before closing.

**Comment by raphw** [comment]
I fixed this already. Byte Buddy now skips incompatible bridges. Will release soon.

**Comment by bric3** [comment]
no hurry ;)
