### ISSUE TITLE
Clarify status of different versions at mockito.org and README.md

### ISSUE THREAD

**Issue by arend-von-reinersdorff** [mockito/mockito#702]
- [mockito.org](http://mockito.org/) currently lists versions 1.10.19, 2.1.0 and 2.2.5 without any explanation
- [README.md](https://github.com/mockito/mockito/blob/release/2.x/README.md) currently lists versions "latest stable" 1.10.19 and "latest beta" 2.2.5

My understanding is that Mockito 2 is out of beta and only version 2.2.5 should be listed. If that is not correct, it would be nice to clarify the status of the different versions, eg legacy/old version/stable/preferred/beta/experimental/etc.

**Comment by TimvdLippe** [comment]
There is currently a big discussion on the confusion with the version numbers in #618. The releases should indeed be clarified more.

**Comment by bric3** [comment]
@arend-von-reinersdorff thanks I will update the readme to clarify the information.

**Comment by bric3** [comment]
@arend-von-reinersdorff I updated the README, thanks for the feedback !

**Comment by bric3** [comment]
#618 still has to be addressed though !

**Comment by arend-von-reinersdorff** [comment]
Thanks for the quick reply :-)

**Comment by szczepiq** [comment]
Thanks guys for really quick turnaround!
