### ISSUE TITLE
Improve usability of arity Answers with regards to checked exceptions

### ISSUE THREAD

**Issue by bric3** [mockito/mockito#707]
Recently introduced Answer1 style answers don't declare Throwable. They should! Otherwise the user is forced to add boilerplate code to AnswerX implementations, whenever they use methods that declare checked exceptions. Plus, AnswerX should behave exactly as good old Answer interface!

Reported via the [mailing-list](https://groups.google.com/d/msgid/mockito/82d08ba9-5536-495e-90db-78c1062b6400%40googlegroups.com)

**Comment by szczepiq** [comment]
Given how Answer is supposed to be used it is a safe change to do. Plus, it is marked as @Incubating :)
