### ISSUE TITLE
Explore fully automated cadence release

### ISSUE THREAD

**Issue by mockitoguy** [mockito/mockito#708]
Explore @jeantil's idea of fully automated cadence release described [here](https://github.com/mockito/mockito/issues/618#issuecomment-253251519).

This idea **might** be a happy medium between releasing every change and manual releases.

**Comment by TimvdLippe** [comment]
See also this awesome comment of @bric3 with the proposed release model which can be semi-automated: https://github.com/mockito/mockito/issues/618#issuecomment-255415833

**Comment by TimvdLippe** [comment]
This has been implemented as https://github.com/mockito/shipkit per rationale described in #618.
