### ISSUE TITLE
Simplify release notes generation

### ISSUE THREAD

**Issue by mockitoguy** [mockito/mockito#710]
We could use https://github.com/skywinder/github-changelog-generator

**Comment by szpak** [comment]
I've been evaluating it some time ago (as an alternative to write something new on my own needs) and it looks very promising. The three main drawbacks I've noticed are:
 - written in Ruby - harder to make a PR with something that we need
 - no integration with the GitHub's release notes mechanism ([#56](https://github.com/skywinder/github-changelog-generator/issues/56)) - although it is not used by Mockito anyway
 - a need to wrap it somehow in a Gradle plugin (a separate project/plugin?)

**Comment by levithomason** [comment]
I decided to wrap all this in an API, [Github Changelog API](https://github.com/levithomason/github-changelog-api).  You can just `curl` your CHANGELOG.md right into your repo, with no deps 👍.

I also added a simple React app [demo interface](http://github-changelog-api.herokuapp.com/), if you want to try it out.  After generating, you can view it in markdown and HTML.

**Comment by szczepiq** [comment]
Wow, this rocks!!! Thank you. We will check it out!

I'm not yet sure I want to get rid of all the java code that we use for release notes generation but we will definitely try out your great little service!

**Comment by TimvdLippe** [comment]
This issue was filed upstream at https://github.com/mockito/shipkit/issues/75
