### ISSUE TITLE
Speed up Travis CI feedback

### ISSUE THREAD

**Issue by szczepiq** [mockito/mockito#712]
Instead of env variables for inline mock maker we just as easily have a separate gradle task. This way we can run 2x less Travis CI builds and make things faster.

**Comment by bric3** [comment]
@TimvdLippe spent hours just to get that working, I've trouble to make gradle work as expected. You're the expert, you probably know better. 
Keep in mind that this trick [helped Kotlin guys](http://hadihariri.com/2016/10/04/Mocking-Kotlin-With-Mockito/).

**Comment by szczepiq** [comment]
Got it :) Fantastic link, thank you!

Env variable trick is a very good starter. I'll only improve it.

**Comment by bric3** [comment]
Yes sure, I'm not against it, far from it.
We should note that travis jobs can run parallel as well.

**Comment by TimvdLippe** [comment]
Actually, the current build is faster since it does things in parallel instead of sequential. Fewer build sub-tasks means that you do more work in 1 build and therefore that build will be longer. I am not sure if changing the env variable with a separate gradle task will speed up the build, I expect it to slow down actually.

**Comment by szczepiq** [comment]
Thanks guys! Let's move on. If Travis CI runs the jobs in parallel, then indeed current setup should be faster.

BTW. do you guys understand the [build times](https://travis-ci.org/mockito/mockito/builds/170122454) reported by travis? What is 'total time' and 'elapsed time'?

**Comment by TimvdLippe** [comment]
Elapsed time is from starting all jobs and the last one finishes. Total time is the sum of all job times. E.g. we save 8 minutes by running in parallel

**Comment by szczepiq** [comment]
Really cool.

Interestingly running tests takes about 50 secs out of the entire build run. See: https://gradle.com/s/wygf6npdbr7ni
