### ISSUE TITLE
Mockito should report mismatched argument warnings when using mocks in unconfigured ways

### ISSUE THREAD

**Issue by Sarev0k** [mockito/mockito#725]
The [MockitoHint](http://site.mockito.org/mockito/docs/current/org/mockito/quality/MockitoHint.html) documentation seems to indicate that this will give you warnings about mismatched arguments, when using the MockitoJUnitRunner.  However, from my experience this doesn't seem to work with Mockito 2.1.

Here's the source I'm trying:
```java
Foo foo = mock(Foo.class);
when(foo.bar("baz")).thenReturn("bar");

foo.bar("baz");
foo.bar("test"); // expected to get a warning here
```

@szczepiq indicated that he wanted to fix this issue in #384 and requested I open a new issue to track it.

**Comment by TimvdLippe** [comment]
This has now been implemented with strict mocks: https://javadoc.io/doc/org.mockito/mockito-core/latest/org/mockito/Mockito.html#40
