### ISSUE TITLE
Code coverage has dramatically decreased after upgrade 2.2.3 -> 2.2.4

### ISSUE THREAD

**Issue by DmitriyZaitsev** [mockito/mockito#729]
I've upgraded `mockito-core` from v2.2.3 to v2.2.4 in my project and lost all my code coverage. 😄 

 / | Class, % | Method, % | Line, %
------------ | ------------ | ------------- | -------------
Before (v2.2.3) | 83% (5/6) | 85% (24/28) | 92% (79/85)
After (v2.2.4) | 33% (2/6) | 7% (2/28) | 15% (13/85)

Looks like somewhere between those versions you made very insidious changes.
Please take a look.
It's reproducible up to v2.2.9 (3 Nov 2016)

I measure code coverage in Android Studio 2.2.2, Java 1.8.0_92-b14.
`mock-maker-inline` is enabled.

**Comment by TimvdLippe** [comment]
That sounds really weird, do you have a sample project we can investigate? Right now I am not sure where to start looking for. Also in `v2.2.4` we bumped Bytebuddy, it would surprise if that suddenly broke code coverage :O @raphw

**Comment by DmitriyZaitsev** [comment]
Sure. You cah checkout [my RxViper library](https://github.com/RxViper/RxViper) and play with the value in [this line](https://github.com/RxViper/RxViper/blob/0.x/gradle/config.gradle#L38).

**Comment by TimvdLippe** [comment]
There was a similar fix to coverage in #695. Has your issue been resolved?

**Comment by raphw** [comment]
Well, `mock-maker-inline` read the class file from disk to avoid the parameter name erasure. This automatically removed the instrumentation of the code coverage tool, removing all code coverage analysis from mock classes. We overcame this in the mean-time, the problem should no longer occur.

**Comment by DmitriyZaitsev** [comment]
@raphw what version contains the fix?

**Comment by Stephan202** [comment]
@DmitriyZaitsev, see the [release notes](https://github.com/mockito/mockito/blob/release/2.x/doc/release-notes/official.md). The fix is in 2.2.17, though a regression was fixed in 2.2.21.
