### ISSUE TITLE
The mechanism to provide MockitoConfiguration is not compatible with java 9 jigsaw

### ISSUE THREAD

**Issue by arnaudroger** [mockito/mockito#732]
Error on mockito 2.2.9

If your module is a test module it cannot export a package that is already exported by another package,

it is not possible to create the `org.mockito.configuration.MockitoConfiguration` inside a jigsaw module

```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.6.0:testCompile (default-testCompile) on project sfm-datastax: Compilation failure: Compilation failure:
[ERROR] /home/aroger/dev/github/SimpleFlatMapper/sfm-datastax/src/test/java/org/mockito/configuration/MockitoConfiguration.java:[1] error: package exists in another module: mockito.core
[ERROR] /home/aroger/dev/github/SimpleFlatMapper/sfm-datastax/src/test/java/org/mockito/configuration/MockitoConfiguration.java:[3,42] error: cannot find symbol
[ERROR] symbol: class DefaultMockitoConfiguration
[ERROR] /home/aroger/dev/github/SimpleFlatMapper/sfm-datastax/src/test/java/org/mockito/configuration/MockitoConfiguration.java:[4,4] error: method does not override or implement a method from a supertype
```

**Comment by bric3** [comment]
@arnaudroger Cool thanks for the report. There maybe issues with Java 9 indeed as we didn't yet started work on the full support of the JDK 9.

This issue maybe the starting point to either document or try other approach to configure mockito.

**Comment by arnaudroger** [comment]
I forked it and put in place a quick solution that will work until the jar is an unamed module.
I just get the class name to instantiate from a system properties with default to the current class name.
and that works fine. will put a PR for that.
it you want mockito to become fully modularized then might need to use a service loader for those kind of thing

**Comment by bric3** [comment]
Aas you know mockito works with android which has a [confusing](https://code.google.com/p/android/issues/detail?id=59658) history about [`ServiceLoader`](https://developer.android.com/reference/java/util/ServiceLoader.html) and the `META-INF` directory. So not sure we can use service loader.

Thanks for the pull request! Eager to review it!

**Comment by arnaudroger** [comment]
which branch should I put the PR on release/2.x or master
?

**Comment by bric3** [comment]
@arnaudroger If that's  a simple fix it could target release/2.x otherwise it should target master

**Comment by arnaudroger** [comment]
see https://github.com/mockito/mockito/pull/740

**Comment by TimvdLippe** [comment]
Closing per https://github.com/mockito/mockito/pull/740#issuecomment-259885498
