### ISSUE TITLE
Upgrade ByteBuddy to 1.5.3

### ISSUE THREAD

**Issue by szczepiq** [mockito/mockito#737]
1. Upgrade to ByteBuddy 1.5.3, it brings following upstream fix: stack size computation when using @Advice.Origin
2. Increase the minimum ByteBuddy version for OSGI environment.

**Comment by TimvdLippe** [comment]
Already fixed in https://github.com/mockito/mockito/commit/0647dbfc8a42e828d74ca404e9da784526766f1f
