### ISSUE TITLE
backward compatibility check in the PR build

### ISSUE THREAD

**Issue by bric3** [mockito/mockito#738]
I've came across this API compatibility web site https://abi-laboratory.pro/java/tracker/timeline/mockito/

It's powered behind by https://github.com/lvc/japi-compliance-checker. The tool is nice and could help to generate compatibility report for a PR. However keep in mind this tool can misreports incompatibilities, e.g. [type parameter renaming](https://abi-laboratory.pro/java/tracker/compat_report/mockito/2.2.7/2.2.8/8eb4b/bin_compat_report.html) can be reported as api removal/addition, same for [static method move](https://abi-laboratory.pro/java/tracker/compat_report/mockito/1.10.19/2.1.0/d037f/src_compat_report.html) that still compiles.

**Comment by szczepiq** [comment]
I love this idea. Thanks a lot Brice for bringing this up.

**Comment by TimvdLippe** [comment]
This was fixed in #1021
