### ISSUE TITLE
Beta/snapshot publishing for master (mockito 3 a the moment)

### ISSUE THREAD

**Issue by bric3** [mockito/mockito#741]
I would like to reintroduce beta/snapshot publishing for the hot user or for us. For now we only have builds, but that may prove useful to deploy snapshot binaries to some snapshot repository.

I don't know it it's feasible with bintray to have a separate repository that is not synced with maven central. However OSS central offers the possibility to deploy to a snapshot repo.

**Comment by szczepiq** [comment]
Sounds good. Options:

1. Publish dev versions to bintray. Give them sensible postfix (like 'dev', 'nightly', 'eap', 'preview'). I'm not happy to use 'beta' for in-progress development versions that can radically change.

2. Bintray does not support snapshots. However, we can keep pushing 3.0.0-SNAPSHOT to https://www.jfrog.com/confluence/display/RTF/Deploying+Snapshots+to+oss.jfrog.org Snapshots are very short lived, users won't be able to refer to 'old' snapshot. Given the lessons learned from hundreds of betas, having single snapshot is tempting. We can always do 3.1.0-SNAPSHOT and continue the tradition of publishing 3.1, 4.1 :)

**Comment by szczepiq** [comment]
We could also publish snapshots to OSS central. I'd love to have that feature in the release automation. However, it's not topping my priority list ATM.

**Comment by TimvdLippe** [comment]
I vote option 1, but then in a different Bintray project (to not clutter 1 project)

**Comment by bric3** [comment]
Yes snapshot deployment on central would be just as good, but option 1 is enough at this time since it is available as a maven repo.

**Comment by szpak** [comment]
I like Maven Central, but it would ok for me to have dev versions only in a separate Bintray repo. SNAPSHOTs can be purged after some time, therefore, I would opt for having "normal" versions released (to those separate Maven (Bintray) repo), e.g. mockito-core-3.0.0-dev.1, mockito-core-3.0.0-dev.2 (to keep the build reliable/repeatable). With that naming convention, once 3.0.0 (final/production) is released to Maven Central it should be considered newer.

Btw, 3.0.0-beta would not be possible (as `b` is before `d`), however 3.0.0-rc.x yes (if needed, just before the final release).

**Comment by TimvdLippe** [comment]
As we are using Shipkit, we now get this for free.
