### ISSUE TITLE
Create redirect from gh-pages hosted javadoc to javadoc.io

### ISSUE THREAD

**Issue by szczepiq** [mockito/mockito#753]
Let's redirect from gh-pages to javadoc.io. Details need to be fleshed out. It should be possible.

Also let's ping the javadoc.io guys again to stop using 'mockito-all' as an example.

**Comment by TimvdLippe** [comment]
I think we can misuse the `404.html` for this. See https://github.com/rafrex/spa-github-pages/blob/gh-pages/404.html for an example. We can then do something similar to strip of the host and replace it with javadoc.io

**Comment by bric3** [comment]
Nice idea !

**Comment by bric3** [comment]
Also note that if we keep gh-pages reference in github, we will keep the commits, and thus the git repo size.

**Comment by TimvdLippe** [comment]
@bric3 I think if I can craft the `404.html` correctly, the `gh-pages` will have just 1 file.

**Comment by bric3** [comment]
That's ignoring the history of this reference tree in git ;)

**Comment by bric3** [comment]
Eventually we can push force on the `gh-pages` reference deleting history of this branch ?

**Comment by TimvdLippe** [comment]
Yes indeed. E.g. remove all content from `gh-pages` and just have 1 file in it.

**Comment by bric3** [comment]
OK that makes sense.

**Comment by TimvdLippe** [comment]
[`404.html`](https://github.com/mockito/mockito/blob/gh-pages/404.html) has been created. You can verify that opening http://mockito.github.io/mockito/docs/current/org/mockito/Mockito.html now redirects to javadoc.io

**Comment by szczepiq** [comment]
Great job guys!!!!!! I love this improvement.

At some point, we need to check the SEO impact. When I ask google for "mockito javadoc" I get Mockito (Mockito 2.2.8 API).
