### ISSUE TITLE
Tidy-up javadoc generation

### ISSUE THREAD

**Issue by szczepiq** [mockito/mockito#755]
I investigated the need for Javadoc doclet rule that currently is kept in buildSrc.

- currently, some javadoc links from public API lead to internal API, which gives 404 error (search for ReturnEmptyValues in public Mockito.html, click the link, 404).
- excluding files at the Javadoc task level does not prevent Javadoc from being generated for the internal classes. However, it does turn links to private API into non-clickable \<code\>\</code\> links.

I'm tempted to just start generating Javadoc for internals, and be very explicit that internal API is not intended for public use and can be changed at any time. Thoughts?

**Comment by TimvdLippe** [comment]
Was fixed in #763
