### ISSUE TITLE
Getting an absolute count of calls to a mocked method

### ISSUE THREAD

**Issue by KenYN** [mockito/mockito#77]
We can do this:

    verify(mock1, times(3)).thisMethod();
    verify(mock2, times(3)).thatMethod();

But we cannot do something like this, as far as I can see:

    verifyEquals(times(mock1.thisMethod()), times(mock2.thatMethod()));

That is, I would like to verify that two mocked methods are called the same unspecified number of times. The number of calls made to a method appears to be already available, so this would be just querying the value directly, not indirectly via `times()`, `atLeast()`, etc.

I also [posed this question to StackOverflow](http://stackoverflow.com/q/25543250/1270789), and one answer, on using an `Answer`, seems good; perhaps a standard `Answer` implementation `CountsCalls` or similar should be the solution?

**Comment by ChristianSchwarz** [comment]
You can use a custom  VerificationMode to count the invocations, here you go:

```
public class InvocationCounter {

	public static <T> T countInvocations(T mock, AtomicInteger count) {
		return Mockito.verify(mock, new Counter(count));
	}

	private InvocationCounter(){}
	
	private static class Counter implements VerificationInOrderMode, VerificationMode {
		private final AtomicInteger count;
		
		private Counter(AtomicInteger count) {
			this.count = count;
		}

		public void verify(VerificationData data) {
			count.set(data.getAllInvocations().size());
		}

		public void verifyInOrder(VerificationDataInOrder data) {
			count.set(data.getAllInvocations().size());
		}

		@Override
		public VerificationMode description(String description) {
			return VerificationModeFactory.description(this, description);
		}

	}

}
```

And then use it like this (works also with void return types):

```
@Mock
private Function<String, Integer> callable;

AtomicInteger count= new AtomicInteger(); //here is the actual invocation count stored

InvocationCounter.countInvocations(callable,count).apply( anyString());

assertThat(count.get(),is(2));
```

**Comment by szczepiq** [comment]
Mockito.mockingDetails(mock).getInvocations() API can be used to get the invocations. It's coming with 2.0. I'm closing this ticket if that's ok!
