### ISSUE TITLE
Broken Javadoc generation with Java 9

### ISSUE THREAD

**Issue by szpak** [mockito/mockito#787]
In master. Temporary disabled for Java 9.

```
Execution failed for task ':javadoc'.

> Javadoc generation failed. Generated Javadoc options file (useful for troubleshooting): '/home/travis/build/mockito/mockito/build/tmp/javadoc/javadoc.options'
```

Sample Travis build: https://travis-ci.org/mockito/mockito/jobs/179224893#L212

**Comment by bric3** [comment]
Good to know, I didn't look yet at that.

**Comment by TimvdLippe** [comment]
This is probably related to the `top` stringOption

**Comment by TimvdLippe** [comment]
This appears to have been fixed on both master and 2.x.
