### ISSUE TITLE
Failing InlineByteBuddyMockMakerTest with Java 9

### ISSUE THREAD

**Issue by szpak** [mockito/mockito#788]
InlineByteBuddyMockMakerTest seems to fail with Java 9.

```
org.mockito.internal.creation.bytebuddy.InlineByteBuddyMockMakerTest > test_parameters_retention FAILED
    org.junit.ComparisonFailure: expected:<"[bar]"> but was:<"[arg0]">
        at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(java.base@9-ea/Native Method)
        at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(java.base@9-ea/NativeConstructorAccessorImpl.java:62)
        at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(java.base@9-ea/DelegatingConstructorAccessorImpl.java:45)
        at org.mockito.internal.creation.bytebuddy.InlineByteBuddyMockMakerTest.test_parameters_retention(InlineByteBuddyMockMakerTest.java:246)

1671 tests completed, 1 failed, 43 skipped

:test FAILED
```

Detected during backporting 2.x changes to master. Sample [Travis build](https://travis-ci.org/mockito/mockito/jobs/179234063#L309-L314).

Reproducible locally with Java 8 129 and 149 and BB 1.5.5 and 1.5.7 in a `tech/backport-2.x-20161127` branch (`release/2.x` fails with Java 9 for other reasons).

**Comment by TimvdLippe** [comment]
Hm it does not fail on my machine when I was working on JDK9 compatibility. See also https://github.com/mockito/mockito/commit/818aa4c1189a812ad61bda91f5ab90ca6065e107 and the green build

**Comment by szpak** [comment]
I don't see this commit in master. Have you run it from my branch `tech/backport-2.x-20161127` or some other?

**Comment by TimvdLippe** [comment]
https://github.com/mockito/mockito/commit/c2a670cf8c8c22c7fb54e7ffcce0fdc5e7264410 was the merge commit of the PR that was merged into master

**Comment by raphw** [comment]
ASM 6 is not yet final so its not yet used by Byte Buddy. Once Java 9 is finalized, asm 6 gets merged what is required for parsing Java 9 class files.

**Comment by TimvdLippe** [comment]
Let's move the assume from the one specific test to the `@Before` of the test class. We can fix them once ASM 6 is released.

**Comment by TimvdLippe** [comment]
Since #791 has been merged, this can be closed.
