### ISSUE TITLE
No coverage with Codedov in master

### ISSUE THREAD

**Issue by szpak** [mockito/mockito#789]
In master builds with backported `release/2.x` changes Codedov reports: "No coverage report":
https://travis-ci.org/mockito/mockito/jobs/179230996#L506

To be investigated (may be related to snapshot jacoco version supporting Java 9). Occurs also in Java 8 builds from master.

**Comment by TimvdLippe** [comment]
That means that the snapshot of Jacoco was removed from maven central. Afaik no release was published with JDK9 support. I did fix it in release2.x so merging that in should be just fine.

**Comment by szpak** [comment]
Hmm, shouldn't the whole build failed in that case (due to a missing dependency)?

**Comment by TimvdLippe** [comment]
Yes, I do not know why it does not

**Comment by TimvdLippe** [comment]
Superseded by #798
