### ISSUE TITLE
Expose StubbingLookupListener publicly and create listener distinction

### ISSUE THREAD

**Issue by mockitoguy** [mockito/mockito#793]
Make StubbingLookupListener public. Originating ticket: #770

As a rule of a thumb we try to expose the internal APIs that the top level features are built upon. Since StubbingLookupListener is useful for us to implement strictness, let's get the former exposed as public API. This way we build stronger framework with the concept of "onion skin API".

**Comment by bric3** [comment]
If exposed publicly the API should use an event object.
