### ISSUE TITLE
Mocking of package-private methods does not work if Thread's context ClassLoader is changed

### ISSUE THREAD

**Issue by vyazelenko** [mockito/mockito#796]
Here is the code to reproduce this issue:
```java
public class TestWithCustomClassLoader {
  public static void main(String[] args) {
    // Thread.currentThread().setContextClassLoader(new MyClassLoader());
    MyClass mock = org.mockito.Mockito.mock(MyClass.class);
    System.out.println(mock.m1());
    System.out.println(mock.m2());
    System.out.println(mock.m3());
    System.out.println(mock.m4());
    System.out.println(mock.fm1());
    System.out.println(mock.fm2());
    System.out.println(mock.fm3());
    System.out.println(mock.fm4());
  }

  public static class MyClassLoader extends ClassLoader {
  }

  public static class MyClass {
    public Object m1() {
      return 1;
    }

    Object m2() {
      return 2;
    }

    protected Object m3() {
      return 3;
    }

    private Object m4() {
      return 4;
    }

    public final Object fm1() {
      return 11;
    }

    final Object fm2() {
      return 22;
    }

    protected final Object fm3() {
      return 33;
    }

    private final Object fm4() {
      return 44;
    }
  }
}
```
When I ran this code as is I get the following expected output:
```
null
null
null
4
11
22
33
44
```
However when the line `// Thread.currentThread().setContextClassLoader(new MyClassLoader());` is uncommented it produces the following results:
```
null
2  <--- package-private method was NOT MOCKED
null
4
11
22
33
44
```
This seems to not work in Mockito 1.x and 2.x. Is this by design or a bug?

**Comment by bric3** [comment]
I don't think we can do much here, if a member is package visible if some coditions are met in the [JLS §5.4.4](http://docs.oracle.com/javase/specs/jvms/se7/html/jvms-5.html#jvms-5.4.4-200) 
> A field or method R is accessible to a class or interface D if and only if any of the following conditions are true:
> * R is public.
> * R is protected and is declared in a class C, and D is either a subclass of C or C itself. Furthermore, if R is not static, then the symbolic reference to R must contain a symbolic reference to a class T, such that T is either a subclass of D, a superclass of D, or D itself.
> * **R is either protected or has default access (that is, neither public nor protected nor private), and is declared by a class in the same run-time package as D.**
> * R is private and is declared in D.
> 
> This discussion of access control omits a related restriction on the target of a protected field access or method invocation (the target must be of class D or a subtype of D). That requirement is checked as part of the verification process (§5.4.1); it is not part of link-time access control.

and only if the classloader is the same as per [JLS §5.3](http://docs.oracle.com/javase/specs/jvms/se7/html/jvms-5.html#jvms-5.3-300)

> At run time, a class or interface is determined not by its name alone, but by a pair: its binary name (§4.2.1) and its defining class loader. Each such class or interface belongs to a single run-time package. The run-time package of a class or interface is determined by the package name and defining class loader of the class or interface.

In the above code when the context classloader is used the _run-time package_ is not the same between the one of the test and the one of the mock.
So when `MyClass.class` is loaded it has the classloader of the test, but mockito will use the context classloader to load the mock class (in which case the mock class can not override the package visbible method).

Double checking with @raphw ;)

**Comment by raphw** [comment]
Yes, this is really a limitation of the JVM. When we mock a class, we ideally inject this class into the target class loader. But when the context class loader is set to a different loader, we have to create a new class loader that is a child of both the class's class loader and the context class loader. This way, the mock class's class loader is not equal to the base class's class loader.

In the JVM, two packages are only equal if they are loaded by the same class loader. As this is no longer the case, the package-private method is no longer considered overridden.
