### ISSUE TITLE
Update Jacoco to stable minor version 0.7.8 when released

### ISSUE THREAD

**Issue by TimvdLippe** [mockito/mockito#798]
See https://github.com/jacoco/jacoco/issues/467#issuecomment-264311016

The snapshot version of Jacoco are removed and could fail our CI. The version of Jacoco is required to build on JDK9

**Comment by bric3** [comment]
Release approaching ;)

**Comment by TimvdLippe** [comment]
`0.7.8` has been released: https://github.com/jacoco/jacoco/issues/467#issuecomment-266305876

**Comment by szpak** [comment]
Fixed by #798.
