### ISSUE TITLE
Can you support kotlin like this,mockito-kotlin

### ISSUE THREAD

**Issue by snowdream** [mockito/mockito#799]
Can you support kotlin like this,mockito-kotlin

**Comment by szpak** [comment]
Can you elaborate more on that topic?

**Comment by raphw** [comment]
We are currently considering an artifact `mockito-inline` which would have this effect.

**Comment by bric3** [comment]
@snowdream The only thing we want to support at this moment is to allow mocking final classes, which is now possible by the creation of an extension with inlining mockmaker (see [Hadi Hariri's blog](http://hadihariri.com/2016/10/04/Mocking-Kotlin-With-Mockito/)). The artefact that @raphw speaks about is to avoid the _burden_ to create a single file in his own test folders.

**Comment by bric3** [comment]
Without much new information I'd like to close the issue.

**Comment by TimvdLippe** [comment]
Closing right now until further information is provided.
