### ISSUE TITLE
Verify exception would be swallowed when specifing expected  parameter

### ISSUE THREAD

**Issue by Sausure** [mockito/mockito#804]
Android Studio Version: 2.2.3
Mockito Version: org.mockito:mockito-core:2.2.29'
Here is my test:
```java
@Test(expected = IndexOutOfBoundsException.class)
public void test(){
    List mockedList = mock(LinkedList.class);

    final Matcher<Integer> matcher = new Matcher<Integer>() {
        @Override
        public boolean matches(Object item) {
            if(!(item instanceof Integer)){
                return false;
            }

            final Integer integer = (Integer) item;

            return integer >= 0 && integer <= 10;
        }

        @Override
        public void describeMismatch(Object item, Description mismatchDescription) {}

        @Override
        public void _dont_implement_Matcher___instead_extend_BaseMatcher_() {}

        @Override
        public void describeTo(Description description) {}
    };

    when(mockedList.get(intThat(matcher))).thenReturn("Some Strings");
    when(mockedList.get(intThat(not(matcher)))).thenThrow(new IndexOutOfBoundsException());
    
    mockedList.get(0);// 1
    mockedList.get(10);// 2
    mockedList.get(10);// 3
    mockedList.get(11);// 4

    verify(mockedList).get(10);
}
```
At the last line I verify `get(10)` will be invoked once time which is invoked twice in fact , this test should  fail but passed . 
Then I remove `mockedList.get(11);` , and it would throw correct exceptions.

**Comment by bric3** [comment]
Hi,

I don't understand the problem here `mockedList.get(11);// 4` will raise the exception as described in the above stubbing. However since there's no catch the verify statement (`verify(mockedList).get(10);`) won't be executed.

Or maybe `not` has the wrong import, `MockitoHamcrest.intThat` expects an Hamcrest matcher, so either `IsNot.not` or `CoreMatchers.not`, but if using mockito `AdditionalMatchers.not` test stub would of course be broken and then probably fail with `InvalidUseOfMatchersException`.

**Comment by Sausure** [comment]
You said that I haven't gotten a verify exception because this line `verify(mockedList).get(10)` won't be executed?

**Comment by bric3** [comment]
Yes, `mockedList.get(11);// 4` will throw the `IndexOutOfBoundsException` which is expected in the test `@Test(expected = IndexOutOfBoundsException.class)`.

**Comment by Sausure** [comment]
Thanks,and I think the best if it can print any useful messages which tell me I get a correct exception in this line,and some codes under this line would not be executed.

**Comment by bric3** [comment]
I don't think that's possible, the test is just not configured properly.
