### ISSUE TITLE
Javadoc links in main Mockito doc are not linkable

### ISSUE THREAD

**Issue by szczepiq** [mockito/mockito#814]
The links to line items in the main [Mockito documentation](https://static.javadoc.io/org.mockito/mockito-core/2.3.0/org/mockito/Mockito.html) are not linkable, e.g. I cannot create a link to item no. 40 in the list.

**Comment by bric3** [comment]
I don't see what you mean I have no problem for that : 

* https://static.javadoc.io/org.mockito/mockito-core/2.3.0/org/mockito/Mockito.html#40
* https://static.javadoc.io/org.mockito/mockito-core/2.3.0/org/mockito/Mockito.html#strict_mockito

**Comment by TimvdLippe** [comment]
At first it seems to be working, but the actual issue is that the first link of @bric3 does work, but the second does not. The problem is that the headers have the second link, so they must be updated to use numbers instead.
