### ISSUE TITLE
Consume new cglib and asm versions

### ISSUE THREAD

**Issue by guw** [mockito/mockito#84]
I'd like Mockito to consume a newer cglib and asm version to address issues with class generation and class loaders in OSGi environments and for Java 8 support. It seems that Mockito needs to consume at least ASM 5 and a new - yet to be released - build for cglib.

I've initiated discussion at cglib in order to get a new cglib release.
https://github.com/cglib/cglib/issues/20

I've prepared pull requests #83 and #81 on the Mockito site in order to start preparing for consuming new bits from asm and cglib.

**Comment by bric3** [comment]
Note we may very well drop CGLIB in 2.0, see #171

**Comment by bric3** [comment]
#171 has been merged.

**Comment by szczepiq** [comment]
We will drop support of cglib in 2.*. We will continue to offer cglib-based mockmaker as an external.
