### ISSUE TITLE
Rename MockMethodDispatcher.class to MockMethodDispatcher.raw on build

### ISSUE THREAD

**Issue by raphw** [mockito/mockito#845]
The `org.mockito.internal.creation.bytebuddy.MockMethodDispatcher.class` file should be renamed to `org.mockito.internal.creation.bytebuddy.MockMethodDispatcher.raw` on building Mockito. This way, class loaders are no longer capable of loading the class directly what should never happen. Doing so, the bootstrap injection mechanism cannot be superseeded by child-first class loaders which break mockability due to the dispatcher class being loaded twice by two different class loaders.

This problem was observed with the Robolectrics class loader.

Additionally, the following change is required in the `InlineByteBuddyMockMaker` when creating the boot jar

```java
String source = "org/mockito/internal/creation/bytebuddy/MockMethodDispatcher";
outputStream.putNextEntry(new JarEntry(source + ".class"));
InputStream inputStream = InlineByteBuddyMockMaker.class.getClassLoader().getResourceAsStream(source + ".raw");
if (inputStream == null) {
  throw new MockitoInitializationException(join(
    "The MockMethodDispatcher class file could not be located " + source,
    "",
    "The class loader responsible: " + InlineByteBuddyMockMaker.class.getClassLoader()
  ));
}
try {
  int length;
  byte[] buffer = new byte[1024];
  while ((length = inputStream.read(buffer)) != -1) {
    outputStream.write(buffer, 0, length);
  }
} finally {
  inputStream.close();
}
outputStream.closeEntry();
```

**Comment by TimvdLippe** [comment]
I discovered the Robolectric ClassLoader issue as well while updating the Mockito mockmaker to ByteBuddy internally. My fix now has the correct class hierarchy, but it now fails to properly resolve the `MockMethodDispatcher`. Should we revert this change (and figure out a way to work with both the broken ClassLoader and the fixed version)?

**Comment by TimvdLippe** [comment]
For now, I have patched the Robolectric ClassLoader to special case the class:

```java
String extension = className.equals("org.mockito.internal.creation.bytebuddy.inject.MockMethodDispatcher") ? "raw" : "class";
    String classFilename = className.replace('.', '/') + "." + extension;
```
However, this introduces a version complexity matrix. E.g.:

broken Robolectric works with current Mockito
fixed Robolectric does not work with current Mockito
fixed Robolectric + workaround works with current Mockito

How can we remove the workaround in Robolectric while at the same time remove the workaround in Mockito while adhering to SemVer in BOTH projects?

**Comment by TimvdLippe** [comment]
Current thinking is (on Mockito build time) keep the `.class` and copying to `.raw`. Then we can update Mockito to just use `.class` and old Robolectric ignores `.raw`, while the new Robolectric uses the original `.class`.
