### ISSUE TITLE
Built-in android support via new 'org.mockito:mockito-android' artifact

### ISSUE THREAD

**Issue by szczepiq** [mockito/mockito#848]
- [x] change Mockito source:
	- update the version of Mockito to 2.6.0 in version.properties
	- change android jar Bintray repostory to be 'maven' (so that we can sync automatically to central) in build.gradle
	- add a javadoc note in main Mockito class
- [x] push changes to GitHub repo
	- wait for them to deploy to Bintray
	- smoke test?
- [x] publish from Bintray web ui
	- "publish" in Bintray so that jar is visible
	- "sync" in Bintray so that it is synced to central
- [x] announce & rejoice :)

**Comment by raphw** [comment]
#847 is concerned with supporting Robolectrics which implements a custom class loader. While it is typically used by Android developers it runs on a non-Android VM. The latter can be released independently of this effort.

List looks good to me. I already tested the new artifact on all kind of Android devices, works like a charm.

**Comment by TimvdLippe** [comment]
@szczepiq I have tried to sync on https://bintray.com/mockito/maven/mockito/2.6.0#central but it required a password. I am not sure if I did it correctly, could you please verify?

**Comment by szczepiq** [comment]
@TimvdLippe, thank you for pushing this forward!!! You did everything correctly, I will share the password with you using a private channel.
