### ISSUE TITLE
Performance degradation when upgrading from 1.10 to 2.2 

### ISSUE THREAD

**Issue by theigl** [mockito/mockito#851]
Hi,

I just ran into an issue when I upgraded our codebase from Mockito 1.10 to 2.2. Test execution time nearly doubled for unit tests using Mockito Mocks and Spies. We have around 4000 unit tests, so this increase was very noticeable on my development box as well as our CI server.

I couldn't believe it at first, but I did extensive profiling with Yourkit and significantly more time is spent in Mockito (and ByteBuddy) classes compared to 1.10.

Before I try to create simple sample projects to reproduce the issue, I wanted to make sure nobody else has run into this and has filed a ticket already.

- My development setup is: MacOs, Java 1.8.0_66
- Our CI setup is: Ubuntu 14.04.4, 1.8.0_101

Tests were run with Maven Surefire and with IntelliJ.

Any feedback would be greatly appreciated.

Best regards,

Thomas

**Comment by TimvdLippe** [comment]
Hello Thomas,

This is the very first report we received. We are looking forward to an example project which reproduces the issue!

**Comment by theigl** [comment]
Hi @TimvdLippe,

I created two extremely simple Maven projects. One with Mockito 1.10.19 and one wich 2.3.11. One empty POJO, and one test class that simply mocks the POJO.

When I run the projects with `mvn test` repeatedly on my box, the execution times converge around:

Mockito 1.10 | Mockito 2.3
------------ | -------------
180ms | 360ms

E.g.
`Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.181 sec` vs:
`Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.383 sec`


[mockito-performance-tests.zip](https://github.com/mockito/mockito/files/674105/mockito-performance-tests.zip)

**Comment by szczepiq** [comment]
Thank you very much for reporting the issue!

**Comment by TimvdLippe** [comment]
Opened #856 to start a benchmarking suite so we can investigate this. The results on my laptop:

```
:jmh
# JMH 1.17.3 (released 14 days ago)
# VM version: JDK 1.8.0_111, VM 25.111-b14
# VM invoker: /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java
# VM options: -Dapple.awt.UIElement=true -Djava.awt.headless=true -XX:+UseCompressedOops -Dfile.encoding=UTF-8 -Duser.country=US -Duser.language=en -Duser.variant
# Warmup: 5 iterations, 1 s each
# Measurement: 5 iterations, 1 s each
# Timeout: 10 min per iteration
# Threads: 1 thread, will synchronize iterations
# Benchmark mode: Throughput, ops/time
# Benchmark: mockitointegration.MockitoBenchmarkTest.simple_mock

# Run progress: 0.00% complete, ETA 00:00:20
# Fork: 1 of 2
# Warmup Iteration   1: 427.514 ops/ms
# Warmup Iteration   2: 1560.181 ops/ms
# Warmup Iteration   3: 2128.033 ops/ms
# Warmup Iteration   4: 2109.880 ops/ms
# Warmup Iteration   5: 2115.993 ops/ms
Iteration   1: 2105.886 ops/ms
Iteration   2: 2056.493 ops/ms
Iteration   3: 1993.194 ops/ms
Iteration   4: 1851.924 ops/ms
Iteration   5: 2044.075 ops/ms

# Run progress: 50.00% complete, ETA 00:00:10
# Fork: 2 of 2
# Warmup Iteration   1: 318.651 ops/ms
# Warmup Iteration   2: 2073.784 ops/ms
# Warmup Iteration   3: 2542.259 ops/ms
# Warmup Iteration   4: 2557.113 ops/ms
# Warmup Iteration   5: 2461.345 ops/ms
Iteration   1: 2371.299 ops/ms
Iteration   2: 2573.721 ops/ms
Iteration   3: 2608.960 ops/ms
Iteration   4: 2588.436 ops/ms
Iteration   5: 2534.948 ops/ms


Result "simple_mock":
  2272.894 ±(99.9%) 440.458 ops/ms [Average]
  (min, avg, max) = (1851.924, 2272.894, 2608.960), stdev = 291.335
  CI (99.9%): [1832.436, 2713.351] (assumes normal distribution)


# Run complete. Total time: 00:00:20

Benchmark                          Mode  Cnt     Score     Error   Units
MockitoBenchmarkTest.simple_mock  thrpt   10  2272.894 ± 440.458  ops/ms
```

Invoking the mock method is performed 2000 times per second, but the interesting observation is that the first run is 4 times slower than later runs.

**Comment by theigl** [comment]
Hi @TimvdLippe,

Thanks a lot for investigating!

My uneducated guess from looking at Yourkit was that the issue could be related to class loading. ByteBuddy loads quite a lot of classes. This would explain why the first run is by far the slowest.

But I am by no means an expert in JVM micro-optimization so it might be something completely different. 

Thomas

**Comment by TimvdLippe** [comment]
@theigl yes that was my guess too. CCing @raphw into the discussion as he is the maintainer of ByteBuddy

**Comment by raphw** [comment]
There is a chance for that. Byte Buddy does do a lot more in terms of processing, for example, it processes generic type information and annotation data what is triggers lazy loading of the related classes of the virtual machine. Generally, Byte Buddy also creates a lot more classes per mock class (one per method) what does decrease the overhead of invoking a mocked method but comes with the cost of increased time for creating code.

I think this will be a general tendency: if you mostly create mocks, Byte Buddy will take more time. If most of your time is spent executing methods of previously mocked classes, Byte Buddy will take less time. Unfortunately, you cannot have both and Byte Buddy prefers the latter outcome.

**Comment by raphw** [comment]
I do actually run benchmarks for Byte Buddy, comparing it with cglib etc: http://bytebuddy.net/#/tutorial - There is a benchmark table a bit down. We are using the case where Byte Buddy requires additional time to create a specific super class proxy for any method. As a matter of fact, we could try to avoid this by creating a different super class proxy type. I can create a patch file for testing this.

**Comment by raphw** [comment]
Feel free to try this version:

[performance.patch.zip](https://github.com/mockito/mockito/files/677353/performance.patch.zip)

**Comment by TimvdLippe** [comment]
@raphw Cool thanks for the speedy response! Could you review #856 and then open a PR with the patch? Then I will take a look at the performance improvements :smile:

**Comment by szczepiq** [comment]
Great investigation so far! How can we make progress on this ticket?

**Comment by TimvdLippe** [comment]
I was working on the benchmark, but hitting some brick walls with classloaders. You can see the PR at #856

**Comment by theigl** [comment]
I just upgraded to Mockito 2.18.3 and test performance is now the same as with 1.10.

**Comment by raphw** [comment]
I have done a lot of benchmsrking for "class ceation intensive" libraries recently and the newer versions of Byte Buddy should have improved performance by a lot.
