### ISSUE TITLE
Robolectric Inline MockMaker Broken - Mockito 2.5.0

### ISSUE THREAD

**Issue by eygraber** [mockito/mockito#855]
I have a simple Robolectric (v3.1.4) test that is failing with the inline mock maker enabled. My code and tests are in Kotlin and I am also using mockito-kotlin v1.0.1

The test is:

    @RunWith(RobolectricTestRunner::class)
    class WelcomeActivityTest {
      @Test
      fun test() {
        val foo: Foo = mock()
        whenever(foo.bar).thenReturn("baz")
        assert(foo.bar == "baz")
      }
    }

[Stacktrace posted here](http://pastebin.com/WeGcRD3u)

**Comment by raphw** [comment]
Is Mockito-Kotlin using the latest Mockito version? At this stage, there is not much we can do anymore. Robolectric needs to fix its class loader to make this work.

**Comment by eygraber** [comment]
I excluded the version it is using from my dependencies, so it should be using 2.5.0 (which I specify).

**Comment by bric3** [comment]
@eygraber Can we close this issue since it's a roboelectric bug ?

**Comment by eygraber** [comment]
Yup
