### ISSUE TITLE
Reenable tests disabled for Java 9 when new ASM is available

### ISSUE THREAD

**Issue by szpak** [mockito/mockito#863]
Those tests usually contain:
```
assumeTrue(ClassFileVersion.ofThisVm().isLessThan(JAVA_V9));
```

Some related issues: #788, #862.

**Comment by raphw** [comment]
I reenabled the tests now, do we have a Java 9 CI build? Still working on a branch.

**Comment by szpak** [comment]
@raphw Yes, we [have](https://github.com/mockito/mockito/blob/770c1c5eaa311ca4c0a78e924ab69319be523384/.travis.yml#L36-L39).

**Comment by wrprice** [comment]
ASM 6.0 in Maven Central on 23-Sep-2017

**Comment by raphw** [comment]
We have reenabled the tests and I already added ASM6 to Byte Buddy.
