### ISSUE TITLE
Travis builds from non-core developers fail on assertEnvVariables

### ISSUE THREAD

**Issue by TimvdLippe** [mockito/mockito#871]
Example build: https://travis-ci.org/mockito/mockito/jobs/188911380

Seems that this does not affect core developers, as my build has been succesful: https://travis-ci.org/mockito/mockito/builds/188321204 as well as those in #865 and #859

**Comment by TimvdLippe** [comment]
I think the easiest solution is to not assert the GH_TOKEN if the build is a pull request

**Comment by bric3** [comment]
Can't we just disable the checks if the repo is not mockito/mockito ?

**Comment by TimvdLippe** [comment]
Pull requests always have `mockito/mockito` as repository?

**Comment by bric3** [comment]
No only ours, external contributors have a fork. Since the GH_TOKEN assertion don't fail for our pull request I think this is safe assumption.

**Comment by TimvdLippe** [comment]
@szczepiq could you make this high priority on your list? Failing builds discourages external developers from publishing their work
