### ISSUE TITLE
Grammar issue in ArgumentMatchers' javadoc.

### ISSUE THREAD

**Issue by mureinik** [mockito/mockito#879]
[`ArgumentMatchers`' javadoc](https://static.javadoc.io/org.mockito/mockito-core/2.6.1/org/mockito/ArgumentMatchers.html) states that:

> This implementation is due static type safety imposed by java compiler. 

There's a word missing there. It should read:

> This implementation is due **to** static type safety imposed by java compiler. 

Version info:
- First noticed this on 2.5.5
- Confirmed it still existed in 2.5.6, 2.5.7 and 2.6.1
- Probably also existed in previous versions.

**Comment by mureinik** [comment]
@TimvdLippe should this issue be closed now that the PR is merged, or should this fix be backported to the 2.x branch too?

**Comment by TimvdLippe** [comment]
@mureinik Oh right it was to the wrong branch 😭 That's my mistake. I will backport it manually
