### ISSUE TITLE
Remove class param on AnnotationEngine.process

### ISSUE THREAD

**Issue by bric3** [mockito/mockito#888]
The class param was kept for backward compatibility, however it doesn't have any meaningful use.
It should be removed. I propose to remove it in Mockito 3 (master).

**Comment by szczepiq** [comment]
Sounds good.

**Comment by TimvdLippe** [comment]
We use this for injecting spies, so let's keep this: https://github.com/mockito/mockito/blob/6e0c22890a5da72f4a919ede3fb2ae25b9eeab8e/src/main/java/org/mockito/internal/configuration/SpyAnnotationEngine.java#L53
