### ISSUE TITLE
what's the official pronunciation of "mockito"

### ISSUE THREAD

**Issue by SylarChen** [mockito/mockito#889]
As title. Thanks~

**Comment by bric3** [comment]
Hi, 

I don't know what I can answer here by text. Looking at IPA phonetic transcription site, simply returns _mockito_. Mockito is name is a pun around _mojito_ and _mock_. Wikipedia's article on [_mojito_](https://en.wikipedia.org/wiki/Mojito) gives this IPA : `/moʊˈhiːtoʊ/`.  [_mock_](https://en.wiktionary.org/wiki/mock) alone can be transcribed in IPA by `/mɑk/` , or `[mˈɒk]` ([spellchecker](https://www.spellchecker.net/mock))

So I think mockito in IPA would be something like `/mɑkiːtoʊ/` or `/mˈɒkiːtoʊ/`.

Some other sources : https://en.wikipedia.org/wiki/Help:IPA_for_English

**Comment by bric3** [comment]
@SylarChen I'm closing this one, but feel free to reach us if needed.

**Comment by szczepiq** [comment]
Thank you raising this ticket and @bric3 for eloquent and thorough answer!

At the time when I first read it, it just made my day. I literally laughed on the floor.
