### ISSUE TITLE
Javadoc generation fails with jdk1.8.0_121

### ISSUE THREAD

**Issue by szczepiq** [mockito/mockito#894]
When I set the jdk to jdk1.8.0_121 the build fails javadoc error. 

Full log including steps to reproduce:

```
~/mockito/src$ export JAVA_HOME=/Library/Java/JavaVirtualMachines/jdk1.8.0_121.jdk/Contents/Home/
~/mockito/src$ ./gradlew javadoc -i


...

javadoc: error - Argument for -top contains JavaScript.
Use --allow-script-in-comments to allow use of JavaScript.
1 error
100 warnings
Problems generating Javadoc.

...

:javadoc FAILED
:javadoc (Thread[Task worker,5,main]) completed. Took 1.936 secs.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':javadoc'.
> Javadoc generation failed. Generated Javadoc options file (useful for troubleshooting): '/Users/sfaber/mockito/src/build/tmp/javadoc/javadoc.options'

* Try:
Run with --stacktrace option to get the stack trace. Run with --debug option to get more log output.

BUILD FAILED
```

**Comment by bric3** [comment]
I tried to add in previous Open JDK 8 (102) but the option is not recognized

```
option.addStringOption('--allow-script-in-comments')
option.addStringOption('-allow-script-in-comments')
option.addStringOption('allow-script-in-comments')
```

I'll try later with the same JDK

**Comment by bric3** [comment]
Could it be related to #787 ?

**Comment by TimvdLippe** [comment]
I will also take another look at the service-worker thing, as it does not appear to work with javadoc.io. If I can't fix it (after exams :wink: ) then I will simply revert it.

**Comment by bric3** [comment]
;)

Contiuous improvements

**Comment by cfries** [comment]
From the release notes: http://www.oracle.com/technetwork/java/javase/8u121-relnotes-3315208.html

> The javadoc tool will now reject any occurrences of JavaScript code in the javadoc documentation comments and command-line options, unless the command-line option, --allow-script-in-comments is specified.
> 
> With the --allow-script-in-comments option, the javadoc tool will preserve JavaScript code in documentation comments and command-line options. An error will be given by the javadoc tool if JavaScript code is found and the command-line option is not set.
> JDK-8138725 (not public)
