### ISSUE TITLE
Avoid pom.xml without dependencies

### ISSUE THREAD

**Issue by mockitoguy** [mockito/mockito#900]
We hit the problems twice already where the pom.xml was generated without dependencies. Let's put some check in place to avoid that in the future. 

 - [ ] When work is started on this issue, add more information to the description of the problem.

**Comment by bric3** [comment]
Question, do we want to add a check for mockito-core-dependency as well ?

mockito-android don't have such dependency I think it would be nice.

**Comment by TimvdLippe** [comment]
This should be fixed in Shipkit now.
