### ISSUE TITLE
Review usage of linter during build

### ISSUE THREAD

**Issue by TimvdLippe** [mockito/mockito#903]
Given the amount of stylistic changes lately in primarily @bric3 PRs, I think we should consider installing a linter to make sure the style is enforced project wide. In my opinion this linter should be extremely lenient, just enforce some very simple rules.

We can look into configuring Checkstyle such that it checks a handful of properties. We can always later decide to make the linter more strict.

**Comment by bric3** [comment]
I have to push the code style decided a few months ago, maybe gradle can generate a section with the mockito style for IDEA (and eclipse and netbeans)

**Comment by szczepiq** [comment]
Absolutely great idea. Perhaps it's worth waiting for Mockito3 before we do that to avoid merging problems?
