### ISSUE TITLE
Ensure Mockito uses latest version of release tools

### ISSUE THREAD

**Issue by mockitoguy** [mockito/mockito#917]
Mockito needs to be able to take advantage of the improvements and bugfixes in  ["org.mockito.release-workflow" plugin](https://github.com/mockito/mockito-release-tools) automatically, without the need to bump version manually.

I've tried to use '+' notation for the 'mockito-release-tools' dependency but it failed with:

```
* What went wrong:
A problem occurred configuring root project 'mockito'.
> Could not resolve all dependencies for configuration ':classpath'.
   > Could not find any matches for gradle.plugin.org.mockito:mockito-release-tools:0.0.+ as no versions of gradle.plugin.org.mockito:mockito-release-tools are available.
     Searched in the following locations:
         https://jcenter.bintray.com/gradle/plugin/org/mockito/mockito-release-tools/maven-metadata.xml
         https://jcenter.bintray.com/gradle/plugin/org/mockito/mockito-release-tools/
         https://plugins.gradle.org/m2/gradle/plugin/org/mockito/mockito-release-tools/maven-metadata.xml
         https://plugins.gradle.org/m2/gradle/plugin/org/mockito/mockito-release-tools/
     Required by:
         :mockito:unspecified
```

Next step: report to Gradle forums and link the ticket here. Are dynamic versions supported with Gradle plugin portal?

**Comment by szczepiq** [comment]
Update: bumped topic on Gradle forums: https://discuss.gradle.org/t/why-the-gradle-central-plugin-repository-does-not-support-dynamic-plugin-versions/11788/2?u=szczepan_faber

**Comment by TimvdLippe** [comment]
Let's not do this for now, as we have previously been broken by Shipkit. It just is a safe-handle to manually bump whenever we want to.
