### ISSUE TITLE
FAQ is not updated with Mockito 2 new features

### ISSUE THREAD

**Issue by lucasvc** [mockito/mockito#919]
The current [FAQ](https://github.com/mockito/mockito/wiki/FAQ) points that Mockito can't mock final classes or objects.
But [what's new](https://github.com/mockito/mockito/wiki/What%27s-new-in-Mockito-2#unmockable) point that can be done now.

One side-question: What about static methods and constructors? Still unmockable?

**Comment by bric3** [comment]
Thanks for the report.

Yes it still is unavailable for now. We'll see in the future, what is possible with that, **or not**.

**Comment by bric3** [comment]
Here's the updated FAQ. Note that anyone can update the wiki.

https://github.com/mockito/mockito/wiki/FAQ#what-are-the-limitations-of-mockito
