### ISSUE TITLE
Improve documentation

### ISSUE THREAD

**Issue by wernight** [mockito/mockito#93]
Documentation is missing many important features (or at least should introduce them in the main readme even they are somewhere described if you find):

* Link to the main reference documentation should be first/big:
  -> http://mockito.github.io/mockito/docs/current/org/mockito/Mockito.html
* `@Spy`: Call the real object but record what has been called
  -> http://mockito.github.io/mockito/docs/current/org/mockito/Mockito.html#spy
* `@InjectMocks`: Used as a kind of simple dependency injection.
  -> http://mockito.github.io/mockito/docs/current/org/mockito/InjectMocks.html
* `@Captor`: Used to capture what arguments where called.
  -> http://mockito.github.io/mockito/docs/current/org/mockito/Captor.html
* `any()` used to `verify()` something was called with any kind of argument.
  -> http://mockito.github.io/mockito/docs/current/org/mockito/Matchers.html#any()

For most I'd include the relevant `import` as well. I'd also put an example `verify()` with `any()` before even one verifying a specific object was called.

**Comment by bric3** [comment]
> * Moving the documentation index out of Mocking class documentation http://mockito.github.io/mockito/docs/current/org/mockito/Mockito.html

Not gonna happen. It is our documentation entry point.

> * Writing some better examples, see http://docs.typemock.com/Isolator/##Ref.chm/Documentation/Using.html for how it could be organized (the current kind of "how-to" organization is also good for more in depth).

There's always the wiki for that :)


Closing as the PR has been merge, thx again for taking care of the doc.
