### ISSUE TITLE
Update contributing guidelines

### ISSUE THREAD

**Issue by mockitoguy** [mockito/mockito#930]
Goal: get more high quality contributions

Current contributing guidelines are great. I would like to include a list tickets that potential contributors can work on. This requires vetting the tickets and scoping them so they are ready to be worked on by external contributors.

This ticket is a placeholder, more details to be added when one starts working on it. Assigning myself so that I have it on my radar. Reassign to yourself if you want to take it on!

**Comment by szczepiq** [comment]
Candidate tickets for scoping and delegating:
 - #738
 - #716
 - #697

**Comment by TimvdLippe** [comment]
We are now using the "please contribute" label on our issue list to invite external contributors to help improving Mockito: https://github.com/mockito/mockito/issues?q=is%3Aopen+is%3Aissue+label%3A%22please+contribute%22
