### ISSUE TITLE
Improve clarity of release notes

### ISSUE THREAD

**Issue by mockitoguy** [mockito/mockito#941]
Let's make Mockito release notes more useful to the community! [Current release notes](https://github.com/mockito/mockito/blob/release/2.x/doc/release-notes/official.md) are automatically generated by [Mockito Continuous Delivery Pipeline](https://github.com/mockito/mockito/wiki/Continuous-Delivery-Overview).

Main use cases for release notes:
 - to make a decision whether it is worth upgrading. This use case is not handled well currently because our [release notes](https://github.com/mockito/mockito/blob/release/2.x/doc/release-notes/official.md) contain too many details (feedback from community: https://github.com/mockito/mockito/issues/618#issuecomment-270038734).
 - to troubleshoot a bug or changed behavior that occurred after upgrading. No direct feedback about it, let's assume that the current release notes satisfy this use case.

Opened a ticket for work on this in https://github.com/mockito/mockito-release-tools/issues/9

Questionable use cases for release notes:
 - to identify if some bug is already fixed. I doubt users will go over release notes to find out if the behavior they see is a bug and if it was fixed in one of the newer versions. Most likely, the user would hit Google, StackOverflow, mailing list and/or create an issue in the tracker.

**Comment by TimvdLippe** [comment]
https://github.com/mockito/mockito/blob/release/2.x/doc/release-notes/official.md looks a lot better now. This was probably fixed during work on https://github.com/mockito/shipkit/issues/9
