### ISSUE TITLE
Should Mockito shade Bytebuddy dependency?

### ISSUE THREAD

**Issue by mockitoguy** [mockito/mockito#943]
The goal of this ticket is to collect user feedback and help making the decision whether to shade ByteBuddy dependency. At the moment, Mockito explicitly depends on ByteBuddy (no shading).

### Should Mockito shade ByteBuddy dependency?

For any dependency of Mockito, we can either explicitly declare the dependency in pom.xml or "shade" the dependency. Explicit dependencies are easier to manage by Mockito team, make dependency graph transparent, allow Mockito users to fine tune the classpath / dependency graph (for example, Mockito user can choose a different version of ByteBuddy). Shaded dependency is not declared in Mockito pom.xml, instead it is included in the jar directly, with packages rewritten to avoid classpath clashes. Shaded dependency is hidden, locked to specific version and cannot be changed by Mockito user. It also makes the build automation more complicated for Mockito team. The benefit of shaded dependency is that it prevents classpath issues / incompatibilities caused by multiple different versions of dependency on the classpath.

### Current state

At the moment, Mockito does not shade any of its dependencies. We started considering to shade ByteBuddy dependency based after user reported classpath issue (https://github.com/mockito/mockito/issues/618#issuecomment-279225904). Note that even if ByteBuddy is super strictly compatible across all versions, there is no guarantee that all 3rd partly libraries that depend on ByteBuddy, always use its API correctly (and refrain from using internal API).

**Comment by ChristianSchwarz** [comment]
@szczepiq Can you add a link to the poll you started on twitter?

**Comment by TimvdLippe** [comment]
@ChristianSchwarz https://twitter.com/MockitoJava/status/831153451228917760

**Comment by TimvdLippe** [comment]
The poll is at 32 votes: 66% voted yes. Seems like a majority do want this change.

**Comment by bric3** [comment]
I'm personnaly in favor to not shade byte buddy at this moment. While CGLIB had serious issues when it was shared for multiple libraries, ByteBuddy does not suffer from it. I would wait on this to have more tangible feedback.

-------------

Regarding the shading I had great difficulty to make work the gradle plugin, and ultimately failed when trying to shade the concurrent set from @raphw.

**Comment by raphw** [comment]
I would also recommend to not shade for the moment. I suggest to see and wait if more than a handful of people get problems. The library has matured a lot over the last year (I worked 50% of my time on the library, project related) and I got to a state where I do not see much to change in the future.

Shading does add additional complexity and size to the library. I do not think that people participating in the pool are aware of what this brings with it as we are carrying the weight.

**Comment by szpak** [comment]
+1 for not shading and introduce some deprecation policy in BB (whether possible).

**Comment by bric3** [comment]
Another thing to consider if we decide to shade, then I think we should shade everything bytebuddy and objenesis.

In the same topic, manually shaded code could be made explicit, the rare apache classes, the concurency set, etc.

**Comment by TimvdLippe** [comment]
Final Twitter poll results: 59 votes. 61% in favor of shading, 39% not.

**Comment by szpak** [comment]
@TimvdLippe it's good to know, however there were too wide context presented as a material to vote. AFAIR in some other issue/discussion @raphw acknowledged the problem and expressed his effort to try to pay closer attention of the backward compatibility issues in the future (especially that BB is getting more and more widely used (e.g. in Hiberante which doesn't shade BB at the moment). Therefore I would suspend that decision to anther "issue" :).

**Comment by TimvdLippe** [comment]
I am closing this ticket, as we have no immediate plans to do this at the moment. We might have to revisit later, but we can reopen the discussion then.
