### ISSUE TITLE
getArgumentAt is removed in 2.7.6

### ISSUE THREAD

**Issue by mkolesnikov** [mockito/mockito#945]
I could not find this method in 2.7.6 version of InvocationOnMock and there is also no information in the release notes in the [incompatible-changes](https://github.com/mockito/mockito/wiki/What%27s-new-in-Mockito-2#incompatible-changes-with-110). Are you going to add it again or what was the reason to remove?

**Comment by TimvdLippe** [comment]
It seems that the deprecated method was incorrectly removed in #404. We have 2 options here: Re-introduce or document as breaking change. Personally I think we should list this as breaking change, which is unfortunate that we didn't list it earlier.

Also as an action point, I propose to always list a "deprecated since" mention to prevent these incorrect removal of deprecated features.

**Comment by ChristianSchwarz** [comment]
`T getArgumentAt(int index, Class<T> type)` was deprecated with the introduction of `T getArgument(int index) ` in v2.0.51-beta with PR #373.  So yes this is a breaking change, the PR and the corresponding issue #365 should be labeled with [incompatible 1.*].

**Comment by ChristianSchwarz** [comment]
I changed the "What's-new-in-Mockito-2" wiki page as suggested see -> [c7c9b9c ](https://github.com/mockito/mockito/wiki/What's-new-in-Mockito-2/_history).

**Comment by bric3** [comment]
@ChristianSchwarz Thanks ! We missed that change.

I labelled the 3 tickets as 1.x incompatible.

**Comment by Yogyatha9** [comment]
Has this method been removed in 3.2.0 again ? I've just uplifted to 3.2.0 recently from 1.7.x and the usage of this method is again a compilation error !

**Comment by TimvdLippe** [comment]
No this method has not been removed. Are you sure you are compiling with the correct version of Mockito?

**Comment by Yogyatha9** [comment]
Hi... thanks for the spontaneous reply. Yes I'm using mockito-core 3.2.0 and since then the getArgumentAt method usage results in a compilation error ! I've checked my pom and 3.2.0 is the only mockito version being referred to. Is there anything that I'm missing if its not dropped/deprecated?

**Comment by TimvdLippe** [comment]
Please create a new issue with a reproduction case that we can debug.

**Comment by Yogyatha9** [comment]
Yep raised ::  https://github.com/mockito/mockito/issues/1837. Thanks

**Comment by mirabilos** [comment]
@ChristianSchwarz the documentation change you did breaks for me though.

        when(metadata.getColumnLabel(anyInt())).thenAnswer(new Answer<String>() {
            @Override
            public String answer(final InvocationOnMock invocation) throws Throwable {
                final int col = invocation.getArgument(0) - 1;
                return labels[col];
            }
        });

This reports an error because Object and int cannot be subtracted. The old form worked:

            final int col = invocation.getArgumentAt(0, Integer.class) - 1;

**Comment by mirabilos** [comment]
AHCK⸘

https://github.com/tarent/extract-tool/commit/622b4c7e42121d7ee950d7cab6fc5d7505c36f4d#diff-0eed92aa6fe056f9fc66caf89ba1149cf188dd4310b2c7968b99f3adc0a05799L63-R62

**Comment by ChristianSchwarz** [comment]
Haven't worked with Java for a long time now. You could try invocation.getArgument<int>(..) or invocation.getArgument<Integer>(..) then compiler can unbox Integer to int. Hope that helps
