### ISSUE TITLE
RunnerFactory InvocationTargetException to return one more possible reason

### ISSUE THREAD

**Issue by aarangara** [mockito/mockito#949]
Currently, RunnerFactory class returns a nice message in exception. 

```
"No tests found in " + klass.getSimpleName() + "\n" +
"Haven't you forgot @Test annotation?\n"
```

Can we have one more line added to it, like below 
```
"No tests found in " + klass.getSimpleName() + "\n" +
 "Haven't you forgot @Test annotation?\n"+
"Didn't you mark your method as public?\n"
```

I usually forget to mark my test method as public whenever I create new Test class.

**Comment by TimvdLippe** [comment]
This message is thrown by JUnit if I am not mistaken and therefore we cant do anything here.

**Comment by aarangara** [comment]
Isn't that coming from here src/main/java/org/mockito/internal/runners/RunnerFactory.java and not JUnit? Apologies if my question is dumb.

**Comment by TimvdLippe** [comment]
In 30 min I have a laptop available, then I will check. On mobile right now and I thought it was JUnit. Will investigate :)

**Comment by TimvdLippe** [comment]
Yes I was mistaken and updated the exception message. Thanks for contributing and sorry for my initial misunderstanding!
