### ISSUE TITLE
Javadoc, Answer1 code example does not compile.

### ISSUE THREAD

**Issue by lukasz-szewc** [mockito/mockito#952]
I believe that all interfaces: Answer1, Answer2 and so on have bad code example in javadoc.

For example Answer1 has this: 

`   when(mock.someMethod(anyString())).thenAnswer(new Answer<Integer, String>() {
       Integer answer(String arg) {
           return arg.length();
       }
   });`

which does not compile. 
First: Answer1 should be there instead of Answer 
Second: thenAnswer method does not accept Answer1 

BTW. I personally consider naming classes or interfaces with digits as last character as poorly named construct. 
I know that there is a "fashion" right now to give names like in some functional languages, but still bothers me as something that is not aesthetic at all. Just a thought.

**Comment by ChristianSchwarz** [comment]
Good find!

The example should be:

```java
import static org.mockito.AdditionalAnswers.answer;

//with java 8 lambdas
when(mock.someMethod(anyString())).then(answer(s->s.length());

//without lambdas
when(mock.someMethod(anyString())).then(answer(new Answer1<Integer, String>() {
  public Integer answer(String s) {
    return s.length();
  }}));
```

**Comment by ChristianSchwarz** [comment]
The docs all other functional answers are brocken too...

**Comment by bric3** [comment]
Thanks @lukasz-szewc for reporting.

> BTW. I personally consider naming classes or interfaces with digits as last character as poorly named construct.
> I know that there is a "fashion" right now to give names like in some functional languages, but still bothers me as something that is not aesthetic at all. Just a thought.

The problem is that the java runtime does not offer a way to express variable arity. So while it is not aesthetic, we are kinda stuck with that naming style until the JVM offers a better alternative. `BiFunction` is not better than `Function2`.

**Comment by lukasz-szewc** [comment]
> The problem is that the java runtime does not offer a way to express variable arity. So while it is not aesthetic, we are kinda stuck with that naming style until the JVM offers a better alternative. BiFunction is not better than Function2.

How about old school approach: `OneParameterAnswer`, `TwoParametersAnswer` ?
