### ISSUE TITLE
Invalid property reported by mocks and partial mocks

### ISSUE THREAD

**Issue by domtoupin** [mockito/mockito#963]
Hi,

We migrated to Mockito 2.x not so long ago and we came across a test that used to works back in Mockito 2.1.0 and no longer works with the latest 2.x version (2.7.11).

Here is the SSCCE to replicate the issue:

```
package com.some.company;

import static org.junit.Assert.*;

import java.beans.BeanInfo;
import java.beans.IntrospectionException;
import java.beans.Introspector;
import java.beans.PropertyDescriptor;
import java.util.HashMap;
import java.util.Map;

import org.junit.Test;
import org.mockito.Mockito;

public class Mockito2Issue
{
	public class SomeClass
	{
		String property;

		public String getAProperty()
		{
			return property;
		}

		protected String getNotAProperty()
		{
			return "abc";
		}
	}

	@Test
	public void testMockBug() throws IntrospectionException
	{
		SomeClass someClassMock = Mockito.mock(SomeClass.class);

		BeanInfo info = Introspector.getBeanInfo(someClassMock.getClass());

		Map<String, PropertyDescriptor> mockPropertyDescriptors = new HashMap<>();
		for (PropertyDescriptor propertyDescriptor : info.getPropertyDescriptors())
		{
			mockPropertyDescriptors.put(propertyDescriptor.getName(), propertyDescriptor);
		}

		assertTrue(mockPropertyDescriptors.containsKey("AProperty"));
		assertFalse(mockPropertyDescriptors.containsKey("notAProperty"));
	}

	@Test
	public void testSpyBug() throws IntrospectionException
	{
		SomeClass someClassSpy = Mockito.spy(new SomeClass());

		BeanInfo info = Introspector.getBeanInfo(someClassSpy.getClass());

		Map<String, PropertyDescriptor> spyPropertyDescriptors = new HashMap<>();
		for (PropertyDescriptor propertyDescriptor : info.getPropertyDescriptors())
		{
			spyPropertyDescriptors.put(propertyDescriptor.getName(), propertyDescriptor);
		}

		assertTrue(spyPropertyDescriptors.containsKey("AProperty"));
		assertFalse(spyPropertyDescriptors.containsKey("notAProperty"));
	}
}
```

**Before (1.10.19):**
Used to works

**After (2.7.11)**
Both tests fail on `assertFalse(mockPropertyDescriptors.containsKey("notAProperty"));`

It seems that although the `getNotAProperty` method is `protected`, the most recent version of Mockito 2.x consider this as valid property getter, but not the very first 2.x stable release (2.1.0).

Can you take a look at this?

Environment details:

Component | Version
--------- | ------
OS | Ubuntu 16.10
Java | Oracle Java(TM) SE Runtime Environment (build 1.8.0_101-b13)
Eclipse | Neon.2
JUnit | 4.8.2
Mockito | 2.1.0 (before), 2.7.11 (after)

**Comment by TimvdLippe** [comment]
This is probably a regression in ByteBuddy as Mockito 2.5.7 was released after #875 was merged.

**Comment by raphw** [comment]
We changed Mockito's use of Byte Buddy to make all mock method's public. This was the solution to #688. Byte Buddy has in the meantime however learned to automatically handle the visibility of a method that is declared by an interface but defined by a super class (in this case `Object`), so we can remove the `Visibility.PUBLIC` constraint in `SubclassBytecodeGenerator` in line 74. Do however note that cglib always made methods public, in a way it is a derivation from the status quo but with a use case like the above, I think that not expanding visibility is more correct.

What do you think @TimvdLippe, @bric3, @szczepiq?

**Comment by TimvdLippe** [comment]
@raphw Would that break #688? If it does not, I think it is okay. Better solve 2 problems than only 1.

**Comment by raphw** [comment]
It would not, I think we should remove it, too.

**Comment by domtoupin** [comment]
Thanks for the quick response and fix!

**Comment by bric3** [comment]
Sounds good to me.
