### ISSUE TITLE
Make MockSettings.useConstructor able to choose the right constructor

### ISSUE THREAD

**Issue by szczepiq** [mockito/mockito#976]
## Use case

We recently added a very nice new feature #935 - ability to mock abstract classes / use real constructor for creating mocks. Currently we fail fast when multiple constructors are found matching provided arguments. However, Mockito could potentially do a better job identifying which constructor to use. Example scenario:

```java
class A {}
class B extends A {}
class C extends B {}

class Foo {
  Foo(A a) {};
  Foo(B b) {};
}

//Below fails with current implementation:
mock(Foo, withSettings().useConstructor(new A()));
mock(Foo, withSettings().useConstructor(new B()));
//However, we could make above work because the constructor argument are not really ambiguous

//Example use case of ambiguous constructor that we can remain failing on
mock(Foo, withSettings().useConstructor(new C()));
```

## Implementation

To get started, see CreatingMocksWithConstructorTest class. Unless the code changes, the interesting test method is [this one](https://github.com/mockito/mockito/blob/release/2.x/src/test/java/org/mockitousage/constructor/CreatingMocksWithConstructorTest.java#L150).

**Comment by szczepiq** [comment]
@mureinik, do you want to take a stab at this one? :)

**Comment by mureinik** [comment]
@szczepiq sure, I'll take a crack at it, but let's first decide what exactly we want to do. 

First, a note - `mock(Foo, withSettings().useConstructor(new A()));` most definitely works with the current implementation, contrary to the comment in the above snippet.

I propose the following definition, which is pretty much what the compiler does when facing a call like `new Foo(new B())`:
- An argument will be called _better matching_ parameter X over parameter Y if the argument can be applied to either parameter X or parameter Y and X is a more specific type than Y.<br/>
For completeness' sake: An argument will be called _worse matching_ parameter X over parameter Y if it is _better matching_ parameter Y over X; An argument will be called _equally matching_ parameter X over parameter Y if it is neither _better matching_ or _worse matching_ parameter X over parameter Y.

- An argument list will be called _better matching_ a constructor's parameters list X over Y if one or more of the arguments are _better matching_ their respective parameters and the rest are _equally matching_ their respective parameters.<br/>
Note that if the argument list is larger than one argument, this is not a total order. If constructor X is _better matching_ an argument list than constructor Z and constructor Y is _better matching_ the same argument list than constructor Z, nothing can be said about the relationship between X and Y.

Using these definitions, we can implement the following behavior:
- If no constructor matches the argument list, an exception is thrown (as it is with the current implementation).
- If a single constructor matches the argument list, it's used (as it is with the current implementation).
- If multiple constructors match the argument list, and one is _better matching_ than any other constructor, it is used (new behavior).
- If multiple constructors match the argument list, and there isn't one that is _better matching_ than all the  the other constructors, an exception is thrown (similar to the current implementation, although the error message may be more precise - see below).

I'll attempt to clarify this with an example.

Consider the following:

```java
class A {}
class B extends A {}
class C extends B {}

class Foo {
  Foo(A x, A y) {}
  Foo(A x, B y) {}
  Foo(B x, A y) {}
}

A a = new A();
B b = new B();
C c = new C();

// Works, Foo(A, A) is called, obviously.
mock(Foo.class, withSettings().useConstructor(a, a)); 

// Works, Foo(A, B) is called, since B is more specific than A, hence Foo(A, B) is better matching than Foor(A, A).
mock(Foo.class, withSettings().useConstructor(a, b)); 

// Works, Foo(B, A) is called, following the same logic as above
mock(Foo.class, withSettings().useConstructor(b, a)); 

// Does not work, as we can't decide between Foo(A, B) and Foo(B, A)
mock(Foo.class, withSettings().useConstructor(b, b)); 
```

If this approach makes sense, I'll cook up a patch that implements it, so we have something concrete to discuss.

**Comment by mureinik** [comment]
@szczepiq feel free to assign this issue to me. I don't think I have the permissions to do so myself.
