### ISSUE TITLE
Misleading documentation of verifyZeroInteractions

### ISSUE THREAD

**Issue by ffissore** [mockito/mockito#977]
## Problem

The current behavior of verifyZeroInteractions can be misleading, see the #989.

In current version of Mockito (2.x), we can improve the javadoc for verifyZeroInteractions to clearly describe how it works (and mention the behavior of strict stubs, too).

Please contribute!

## Original report

Original issue reported by @ffissore:

According to the [docs](http://static.javadoc.io/org.mockito/mockito-core/2.7.13/org/mockito/Mockito.html#verifyZeroInteractions(java.lang.Object...)) `verifyZeroInteractions` is like `verify(mock, never()).method()` when the mock has only one method.

The tests below should both raise an exception. Instead, `testVerifyZeroInteractions` raises none and fails

```java
package test;

import org.junit.Before;
import org.junit.Rule;
import org.junit.Test;
import org.mockito.Mock;
import org.mockito.MockitoAnnotations;
import org.mockito.exceptions.verification.NeverWantedButInvoked;
import org.mockito.exceptions.verification.NoInteractionsWanted;
import org.mockito.junit.MockitoJUnit;
import org.mockito.junit.MockitoRule;
import org.mockito.quality.Strictness;

import static org.junit.Assert.assertEquals;
import static org.mockito.Mockito.*;

public class MockitoTest {

   private static class Collaborator {

      public String doStuff(int number) {
         throw new RuntimeException();
      }

   }

   private static class Container {

      private final Collaborator collaborator;

      public Container(Collaborator collaborator) {
         this.collaborator = collaborator;
      }

      public String doStuff(int number) {
         return collaborator.doStuff(number);
      }

   }


   @Rule
   public MockitoRule rule = MockitoJUnit.rule().strictness(Strictness.STRICT_STUBS);

   @Mock
   private Collaborator collaborator;

   @Before
   public void setUp() throws Exception {
      MockitoAnnotations.initMocks(this);
   }

   // passes
   @Test(expected = NeverWantedButInvoked.class)
   public void testVerifyNever() throws Exception {
      Container container = new Container(collaborator);
      when(collaborator.doStuff(42)).thenReturn("yeah");

      String output = container.doStuff(42);
      assertEquals("yeah", output);

      verify(collaborator, never()).doStuff(42);
   }

   // fails
   @Test(expected = NoInteractionsWanted.class)
   public void testVerifyZeroInteractions() throws Exception {
      Container container = new Container(collaborator);
      when(collaborator.doStuff(42)).thenReturn("yeah");

      String output = container.doStuff(42);
      assertEquals("yeah", output);

      verifyZeroInteractions(collaborator);
   }
}
```

**Comment by ffissore** [comment]
Forgot to say: I'm using version 2.7.13

**Comment by szczepiq** [comment]
Looking into it...

**Comment by szczepiq** [comment]
Thank you for reporting and your patience waiting for the reply!!!

It's a really good report - I was able to reproduce the problem easily. Also, THANKS a lot for using strict stubbing - I'm really happy to see it in use!

At the moment, "verifyZeroInteractions" is an alias to "verifyNoMoreInteractions", intended to be used to improve readability of tests. Let me illustrate it on a couple of examples:

Example 1 - verifyNoMoreInteractions

```java
mock.foo();
verify(mock).foo();
verifyNoMoreInteractions(mock); //pretty clear I think
```

Example 2 - verifyZeroInteractions

```java
mock.foo();
verify(mock).foo();

verifyZeroInteractions(mock);
//above passes because verifyZeroInteractions == verifyNoMoreInteractions
//and we already have verified the only method invoked on the mock
```

Example 3 - verifyZeroInteractions with regular stubbing

```java
given(mock.foo()).willReturn("x");
assertEquals("x", mock.foo());
verify(mock).foo();

verifyZeroInteractions(mock);
//above passes because verifyZeroInteractions == verifyNoMoreInteractions
```

Example 4 - verifyZeroInteractions with new strict stubbing

```java
given(mock.foo()).willReturn("x");
assertEquals("x", mock.foo());

verifyZeroInteractions(mock);
//above passes because with strict stubbing
//stubbed method are implicitly verified when they are "used"
//this is one of key features of strict stubbing (DRY, don't repeat yourself)
```

We're happy to listen to suggestions about above and the API. I think that better documentation is needed for "verifyZeroInteractions", too.

**Comment by ffissore** [comment]
Thank you for the clarification. Then I guess the problem is with the [javadoc](https://static.javadoc.io/org.mockito/mockito-core/2.7.17/org/mockito/Mockito.html#verifyZeroInteractions(java.lang.Object...)) which states "Verifies that no interactions happened on given mocks.". This made sense to me: a class X may have a number of mocked collaborators and I want to be sure that some of them have not taken part when I called X.method()

I ended up writing my version
```java
public static void verifyZeroInteractions(Object... objects) {
  for (int i = 0; i < objects.length; i++) {
    assertEquals("Expected 0 interactions with object at index " + i + " (" + objects[i].getClass() + ")", 0, Mockito.mockingDetails(objects[i]).getInvocations().size());
  }
}
```

Also thanks for the hint about implicit verification when in strict mode: I didn't get it and it will allow me to delete some tens of lines of code

**Comment by szczepiq** [comment]
Interesting idea!

Let's keep this ticket to improve the documentation (want to help out? submit a PR :). I created ticket for discussing change of verifyZeroInteractions: #989
