### ISSUE TITLE
Mock URL.class

### ISSUE THREAD

**Issue by shreyas080** [mockito/mockito#998]
Hi 
As per the update for mockito 2.2.x it supports mocking a final class, but when i try to mock the URL.class i get the values of the object null in the debug mode. I am using mockito-core-2.2.16 with java 7. I am not sure what is wrong with my code.

               URL u = mock(URL.class);
	        HttpsURLConnection huc = mock(HttpsURLConnection.class);
	        when(new URL(anyString())).thenReturn(u);
	        when(u.openConnection()).thenReturn(huc);

Thanks
Shreyas
![mock](https://cloud.githubusercontent.com/assets/19372060/24191956/71109e84-0f13-11e7-9442-7ca4c5346260.PNG)

**Comment by TimvdLippe** [comment]
Hm, I think this is working as intended? When you mock an URL, all fields are initialized with `null` and method invocations are stubbed.
Now note that you are trying to mock a whole `URL`, but you can not mock a constructor. E.g. `when(new URL(...))` is not supported by Mockito.
Usually this means your source code is not really testable, so try to see if you can extract the constructor invoaction. Moreover, try to not mock data classes. E.g. don't mock core classes such as `List` and `String`. I think `URL` is in the same category.

If you really need to, `PowerMock` can help you out, but they don't support Mockito 2 just yet.

**Comment by jw44250** [comment]
How it is possible to mock user defined final class..

public final class FinalClass {
	public final String finalMethod() {
		return "something";
	}
	
	public static String test(){
		
		return "test1";
	}
}

//Mock Class
FinalClass finalClassMock = Mockito.mock(FinalClass.class);

		when(finalClassMock.finalMethod()).thenReturn("test");

		Assert.assertEquals("test", finalClassMock.finalMethod());

		Assert.assertEquals("test1", FinalClass.test());

**Comment by TimvdLippe** [comment]
Closing per https://github.com/mockito/mockito/issues/998#issuecomment-288354458 and it seems this issue became stale.
